import Mathlib.Analysis.Calculus.Gradient.Basic
import Mathlib.Analysis.Calculus.LocalExtr.Basic
import Mathlib.Analysis.InnerProductSpace.PiL2
import Mathlib.Tactic

/-!
# Invariant risk and scalar fixed classifiers

For differentiable convex risks, linear invariant risk minimization has a
sharp first-order characterization.  If a predictor is obtained by applying
a linear representation to a classifier that minimizes every environment
risk, then the predictor is orthogonal to every environment gradient.
Conversely, those orthogonality equations already make the fixed scalar
classifier one optimal for the rank-one representation generated by the
predictor.

This file states the result for real Hilbert spaces.  A
`FirstOrderConvexRisk` stores the differentiable first-order lower bound used
by the convex argument.  The arbitrary-representation theorem proves the
necessary direction, and the scalar-representation theorem proves the
source's stronger fixed-classifier sufficiency.

The result is about simultaneous optimization of declared risks.  It does not
by itself establish causal identification, out-of-distribution
generalization, or the behavior of a finite penalty optimizer.  The positive
fixture uses a nonzero predictor and two opposed transverse gradients; the
negative fixture shows that convex differentiability without orthogonality is
insufficient.
-/

namespace Mettapedia.MachineLearning.ContinualLearning

namespace InvariantRiskRepresentation

open scoped RealInnerProductSpace

variable {Environment V W : Type*}
variable [NormedAddCommGroup V] [InnerProductSpace ℝ V] [CompleteSpace V]
variable [NormedAddCommGroup W] [NormedSpace ℝ W]

/-- A differentiable risk equipped with its global first-order convex lower
bound. -/
structure FirstOrderConvexRisk (V : Type*)
    [NormedAddCommGroup V] [InnerProductSpace ℝ V] [CompleteSpace V] where
  value : V → ℝ
  gradient : V → V
  hasGradientAt :
    ∀ point, HasGradientAt value (gradient point) point
  supporting :
    ∀ point candidate,
      value point +
          inner ℝ (gradient point) (candidate - point) ≤
        value candidate

/-- A classifier minimizes every environment risk over the image of a
representation. -/
def SimultaneouslyMinimizes
    (risks : Environment → FirstOrderConvexRisk V)
    (representation : W →L[ℝ] V)
    (classifier : W) : Prop :=
  ∀ environment candidate,
    (risks environment).value (representation classifier) ≤
      (risks environment).value (representation candidate)

/-- The rank-one representation sending a scalar classifier to a multiple of
the represented predictor. -/
noncomputable def scalarRepresentation
    (predictor : V) : ℝ →L[ℝ] V :=
  (1 : ℝ →L[ℝ] ℝ).smulRight predictor

omit [CompleteSpace V] in
@[simp] theorem scalarRepresentation_apply
    (predictor : V)
    (classifier : ℝ) :
    scalarRepresentation predictor classifier =
      classifier • predictor := by
  simp [scalarRepresentation]

omit [CompleteSpace V] in
@[simp] theorem scalarRepresentation_one
    (predictor : V) :
    scalarRepresentation predictor 1 = predictor := by
  simp

/-- Any simultaneous optimum over a linear representation is orthogonal to
each environment gradient at its represented predictor. -/
theorem simultaneousMinimizer_implies_predictor_gradient_orthogonal
    (risks : Environment → FirstOrderConvexRisk V)
    (representation : W →L[ℝ] V)
    (classifier : W)
    (hmin :
      SimultaneouslyMinimizes risks representation classifier) :
    ∀ environment,
      inner ℝ
        (representation classifier)
        ((risks environment).gradient
          (representation classifier)) = 0 := by
  intro environment
  have hlocal :
      IsLocalMin
        ((risks environment).value ∘ representation)
        classifier :=
    Filter.Eventually.of_forall (hmin environment)
  have hderiv :
      HasFDerivAt
        ((risks environment).value ∘ representation)
        ((InnerProductSpace.toDual ℝ V)
            ((risks environment).gradient
              (representation classifier)) ∘SL
          representation)
        classifier :=
    ((risks environment).hasGradientAt
      (representation classifier)).hasFDerivAt.comp classifier
        representation.hasFDerivAt
  have hzero := hlocal.hasFDerivAt_eq_zero hderiv
  have happly := DFunLike.congr_fun hzero classifier
  simpa [ContinuousLinearMap.comp_apply,
    InnerProductSpace.toDual_apply_apply, real_inner_comm] using
    happly

/-- Predictor-gradient orthogonality makes the fixed scalar classifier one a
global optimum for every first-order convex risk. -/
theorem predictor_gradient_orthogonal_implies_scalarOne_minimizer
    (risks : Environment → FirstOrderConvexRisk V)
    (predictor : V)
    (horthogonal :
      ∀ environment,
        inner ℝ
          predictor
          ((risks environment).gradient predictor) = 0) :
    SimultaneouslyMinimizes
      risks (scalarRepresentation predictor) 1 := by
  intro environment classifier
  have hgradientPredictor :
      inner ℝ
        ((risks environment).gradient predictor)
        predictor = 0 := by
    simpa [real_inner_comm] using horthogonal environment
  have hlinearTerm :
      inner ℝ
        ((risks environment).gradient predictor)
        (classifier • predictor - predictor) = 0 := by
    rw [inner_sub_right, inner_smul_right, hgradientPredictor]
    simp
  have hlower :=
    (risks environment).supporting
      predictor (classifier • predictor)
  rw [hlinearTerm, add_zero] at hlower
  simpa using hlower

/-- Fixed-scalar linear invariant-risk characterization: classifier one is
simultaneously optimal exactly when the predictor is orthogonal to every
environment gradient. -/
theorem scalarOne_simultaneouslyMinimizes_iff_gradient_orthogonal
    (risks : Environment → FirstOrderConvexRisk V)
    (predictor : V) :
    SimultaneouslyMinimizes
        risks (scalarRepresentation predictor) 1 ↔
      ∀ environment,
        inner ℝ
          predictor
          ((risks environment).gradient predictor) = 0 := by
  constructor
  · intro hmin
    simpa using
      simultaneousMinimizer_implies_predictor_gradient_orthogonal
        risks (scalarRepresentation predictor) 1 hmin
  · exact
      predictor_gradient_orthogonal_implies_scalarOne_minimizer
        risks predictor

/-- An exact-gradient affine risk used by the executable fixtures. -/
noncomputable def affineRisk
    (gradient : V) : FirstOrderConvexRisk V where
  value := fun point ↦ inner ℝ gradient point
  gradient := fun _ ↦ gradient
  hasGradientAt := by
    intro point
    change
      HasGradientAt
        (((InnerProductSpace.toDual ℝ V) gradient) : V → ℝ)
        gradient point
    simpa using
      ((InnerProductSpace.toDual ℝ V)
        gradient).hasFDerivAt.hasGradientAt
  supporting := by
    intro point candidate
    rw [inner_sub_right]
    linarith

/-! ## Positive and negative fixtures -/

private abbrev Plane :=
  EuclideanSpace ℝ (Fin 2)

private noncomputable def firstAxis : Plane :=
  EuclideanSpace.single 0 1

private noncomputable def secondAxis : Plane :=
  EuclideanSpace.single 1 1

private noncomputable def transverseRisks :
    Bool → FirstOrderConvexRisk Plane
  | false => affineRisk secondAxis
  | true => affineRisk (-secondAxis)

/-- A nonzero rank-one predictor is simultaneously optimal for two opposed
convex risks when both gradients are transverse to its span. -/
theorem transverse_affineRisks_scalarOne_simultaneouslyMinimizes :
    SimultaneouslyMinimizes
      transverseRisks (scalarRepresentation firstAxis) 1 := by
  apply
    predictor_gradient_orthogonal_implies_scalarOne_minimizer
  intro environment
  cases environment <;>
    simp [transverseRisks, affineRisk, firstAxis, secondAxis,
      EuclideanSpace.inner_single_left]

/-- Convex differentiability alone is insufficient: an aligned nonzero
gradient makes the fixed scalar classifier one fail global optimality. -/
theorem aligned_affineRisk_scalarOne_not_minimizer :
    let risk : Unit → FirstOrderConvexRisk ℝ :=
      fun _ ↦ affineRisk 1
    ¬ SimultaneouslyMinimizes
      risk (scalarRepresentation 1) 1 := by
  dsimp [SimultaneouslyMinimizes]
  intro hmin
  have hzero := hmin () 0
  norm_num [affineRisk, scalarRepresentation] at hzero

#print axioms
  simultaneousMinimizer_implies_predictor_gradient_orthogonal
#print axioms
  predictor_gradient_orthogonal_implies_scalarOne_minimizer
#print axioms
  scalarOne_simultaneouslyMinimizes_iff_gradient_orthogonal
#print axioms
  transverse_affineRisks_scalarOne_simultaneouslyMinimizes
#print axioms
  aligned_affineRisk_scalarOne_not_minimizer

end InvariantRiskRepresentation

end Mettapedia.MachineLearning.ContinualLearning
