import Mathlib.LinearAlgebra.Matrix.DotProduct
import Mathlib.Tactic

/-!
# Task-overlap geometry and finite forgetting

Doan et al., *A Theoretical Analysis of Catastrophic Forgetting through the
NTK Overlap Matrix* (2020), Lemma 1, Theorem 1, and Corollary 1, factor
source-task prediction drift through the overlap between source and target
neural-tangent feature subspaces.

This file extracts the finite linear-algebraic core independently of an SVD
or a particular kernel-regression solver.  If a target-task update lies in a
declared target basis, then its effect on a source readout is exactly the task
overlap matrix applied to the target coefficients.  The identity extends to
an arbitrary finite task trace, where distinct drifts may cancel.

The boundary results prevent common overclaims.  A large overlap need not
cause forgetting when the learned coefficient is zero; a small overlap gives
no bound without controlling the coefficient; final zero forgetting may hide
large intermediate drifts; and an overlap computed from a stale feature map
can be zero while the current feature geometry produces nonzero drift.  Thus
the source's fixed-NTK and coefficient-size hypotheses are load-bearing.
-/

namespace Mettapedia.MachineLearning.ContinualLearning

namespace TaskOverlapForgetting

noncomputable section

variable {Parameter SourceCoordinate TargetCoordinate : Type*}
  [Fintype Parameter] [Fintype SourceCoordinate]
  [Fintype TargetCoordinate]

/-- Cross-task overlap between column bases in parameter space. -/
def taskOverlap
    (sourceBasis : Matrix Parameter SourceCoordinate ℝ)
    (targetBasis : Matrix Parameter TargetCoordinate ℝ) :
    Matrix SourceCoordinate TargetCoordinate ℝ :=
  sourceBasis.transpose * targetBasis

/-- Parameter update represented in a target task's feature basis. -/
def taskBasisUpdate
    (targetBasis : Matrix Parameter TargetCoordinate ℝ)
    (coefficient : TargetCoordinate → ℝ) :
    Parameter → ℝ :=
  targetBasis.mulVec coefficient

/-- Change of the source task's fixed linearized predictions. -/
def sourcePredictionDrift
    (sourceBasis : Matrix Parameter SourceCoordinate ℝ)
    (update : Parameter → ℝ) :
    SourceCoordinate → ℝ :=
  sourceBasis.transpose.mulVec update

/-- Source-task drift generated by a target-basis coefficient. -/
def targetInducedDrift
    (sourceBasis : Matrix Parameter SourceCoordinate ℝ)
    (targetBasis : Matrix Parameter TargetCoordinate ℝ)
    (coefficient : TargetCoordinate → ℝ) :
    SourceCoordinate → ℝ :=
  sourcePredictionDrift sourceBasis
    (taskBasisUpdate targetBasis coefficient)

omit [Fintype SourceCoordinate] in
/-- Source correspondence: target-induced source drift factors exactly
through the NTK task-overlap matrix. -/
theorem targetInducedDrift_eq_overlap_mulVec
    (sourceBasis : Matrix Parameter SourceCoordinate ℝ)
    (targetBasis : Matrix Parameter TargetCoordinate ℝ)
    (coefficient : TargetCoordinate → ℝ) :
    targetInducedDrift sourceBasis targetBasis coefficient =
      (taskOverlap sourceBasis targetBasis).mulVec coefficient := by
  simp [targetInducedDrift, sourcePredictionDrift, taskBasisUpdate,
    taskOverlap, Matrix.mulVec_mulVec]

/-- Squared prediction drift, the finite forgetting quantity used by the
source. -/
def forgetting
    (sourceBasis : Matrix Parameter SourceCoordinate ℝ)
    (update : Parameter → ℝ) : ℝ :=
  let drift := sourcePredictionDrift sourceBasis update
  drift ⬝ᵥ drift

/-- Exact overlap expression for the squared forgetting generated by one
target-basis update. -/
theorem forgetting_taskBasisUpdate_eq_overlap
    (sourceBasis : Matrix Parameter SourceCoordinate ℝ)
    (targetBasis : Matrix Parameter TargetCoordinate ℝ)
    (coefficient : TargetCoordinate → ℝ) :
    forgetting sourceBasis (taskBasisUpdate targetBasis coefficient) =
      let drift :=
        (taskOverlap sourceBasis targetBasis).mulVec coefficient
      drift ⬝ᵥ drift := by
  change targetInducedDrift sourceBasis targetBasis coefficient ⬝ᵥ
      targetInducedDrift sourceBasis targetBasis coefficient =
    (taskOverlap sourceBasis targetBasis).mulVec coefficient ⬝ᵥ
      (taskOverlap sourceBasis targetBasis).mulVec coefficient
  rw [targetInducedDrift_eq_overlap_mulVec]

/-- A single later-task update packet. -/
structure TaskPacket
    (Parameter TargetCoordinate : Type*) where
  basis : Matrix Parameter TargetCoordinate ℝ
  coefficient : TargetCoordinate → ℝ

/-- Total parameter displacement from an ordered finite later-task trace. -/
def totalTaskUpdate :
    List (TaskPacket Parameter TargetCoordinate) → Parameter → ℝ
  | [] => 0
  | packet :: packets =>
      taskBasisUpdate packet.basis packet.coefficient +
        totalTaskUpdate packets

/-- Sum of the per-task source drifts. -/
def totalOverlapDrift
    (sourceBasis : Matrix Parameter SourceCoordinate ℝ) :
    List (TaskPacket Parameter TargetCoordinate) →
      SourceCoordinate → ℝ
  | [] => 0
  | packet :: packets =>
      (taskOverlap sourceBasis packet.basis).mulVec
          packet.coefficient +
        totalOverlapDrift sourceBasis packets

omit [Fintype SourceCoordinate] in
/-- Finite-trace generalization of the source factorization: the final
source drift is the sum of all overlap-weighted task coefficients. -/
theorem sourcePredictionDrift_totalTaskUpdate
    (sourceBasis : Matrix Parameter SourceCoordinate ℝ) :
    ∀ packets : List (TaskPacket Parameter TargetCoordinate),
      sourcePredictionDrift sourceBasis (totalTaskUpdate packets) =
        totalOverlapDrift sourceBasis packets := by
  intro packets
  induction packets with
  | nil =>
      simp [sourcePredictionDrift, totalTaskUpdate, totalOverlapDrift]
  | cons packet packets inductionHypothesis =>
      rw [totalTaskUpdate, totalOverlapDrift, sourcePredictionDrift,
        Matrix.mulVec_add]
      change targetInducedDrift sourceBasis packet.basis
          packet.coefficient +
          sourcePredictionDrift sourceBasis (totalTaskUpdate packets) =
        (taskOverlap sourceBasis packet.basis).mulVec
            packet.coefficient +
          totalOverlapDrift sourceBasis packets
      rw [targetInducedDrift_eq_overlap_mulVec, inductionHypothesis]

/-- Exact orthogonal-subspace retention: zero task overlap erases every
target-basis coefficient from the source readout. -/
theorem zero_taskOverlap_no_forgetting
    (sourceBasis : Matrix Parameter SourceCoordinate ℝ)
    (targetBasis : Matrix Parameter TargetCoordinate ℝ)
    (coefficient : TargetCoordinate → ℝ)
    (orthogonal : taskOverlap sourceBasis targetBasis = 0) :
    forgetting sourceBasis
        (taskBasisUpdate targetBasis coefficient) = 0 := by
  rw [forgetting_taskBasisUpdate_eq_overlap, orthogonal]
  simp

omit [Fintype SourceCoordinate] in
/-- If every later task basis is orthogonal to the source basis, an arbitrary
finite later-task trace has zero source drift. -/
theorem totalOverlapDrift_eq_zero_of_each_overlap_zero
    (sourceBasis : Matrix Parameter SourceCoordinate ℝ) :
    ∀ packets : List (TaskPacket Parameter TargetCoordinate),
      (∀ packet ∈ packets,
        taskOverlap sourceBasis packet.basis = 0) →
      totalOverlapDrift sourceBasis packets = 0 := by
  intro packets orthogonal
  induction packets with
  | nil =>
      rfl
  | cons packet packets inductionHypothesis =>
      have headZero :
          taskOverlap sourceBasis packet.basis = 0 :=
        orthogonal packet (by simp)
      have tailZero :
          ∀ later ∈ packets,
            taskOverlap sourceBasis later.basis = 0 := by
        intro later laterMem
        exact orthogonal later (by simp [laterMem])
      rw [totalOverlapDrift, headZero, inductionHypothesis tailZero]
      simp

/-! ## Positive and negative executable boundaries -/

/-- Two orthogonal one-dimensional task bases have zero overlap and exact
zero source forgetting for every target coefficient. -/
theorem orthogonalAxes_no_forgetting
    (coefficient : Unit → ℝ) :
    let source : Matrix (Fin 2) Unit ℝ :=
      fun parameter _ => if parameter = 0 then 1 else 0
    let target : Matrix (Fin 2) Unit ℝ :=
      fun parameter _ => if parameter = 1 then 1 else 0
    taskOverlap source target = 0 ∧
      forgetting source (taskBasisUpdate target coefficient) = 0 := by
  dsimp
  have overlapZero :
      taskOverlap
          (fun (parameter : Fin 2) (_ : Unit) =>
            if parameter = 0 then (1 : ℝ) else 0)
          (fun (parameter : Fin 2) (_ : Unit) =>
            if parameter = 1 then (1 : ℝ) else 0) = 0 := by
    ext sourceCoordinate targetCoordinate
    cases sourceCoordinate
    cases targetCoordinate
    norm_num [taskOverlap, Matrix.mul_apply, Fin.sum_univ_two]
  exact ⟨overlapZero,
    zero_taskOverlap_no_forgetting _ _ coefficient overlapZero⟩

/-- Final zero forgetting can hide nonzero intermediate forgetting: identical
task directions with coefficients `2` and `-2` cancel exactly. -/
theorem oppositeTaskPackets_cancel_nonzero_intermediateDrift :
    let basis : Matrix Unit Unit ℝ := fun _ _ => 1
    let positive : TaskPacket Unit Unit := ⟨basis, fun _ => 2⟩
    let negative : TaskPacket Unit Unit := ⟨basis, fun _ => -2⟩
    (taskOverlap basis positive.basis).mulVec
        positive.coefficient = (fun _ => 2) ∧
      (taskOverlap basis negative.basis).mulVec
        negative.coefficient = (fun _ => -2) ∧
      totalOverlapDrift basis [positive, negative] = 0 := by
  dsimp
  constructor
  · funext coordinate
    cases coordinate
    norm_num [taskOverlap, Matrix.mulVec, Matrix.mul_apply,
      dotProduct]
  · constructor
    · funext coordinate
      cases coordinate
      norm_num [taskOverlap, Matrix.mulVec, Matrix.mul_apply,
        dotProduct]
    · funext coordinate
      cases coordinate
      norm_num [totalOverlapDrift, taskOverlap, Matrix.mulVec,
        Matrix.mul_apply, dotProduct]

/-- Overlap magnitude alone cannot order forgetting: a smaller overlap with
a larger coefficient can produce unit drift, while a larger overlap with
zero coefficient produces no drift. -/
theorem smallerOverlap_can_forget_more :
    let source : Matrix Unit Unit ℝ := fun _ _ => 1
    let smallTarget : Matrix Unit Unit ℝ := fun _ _ => 1 / 2
    let largeTarget : Matrix Unit Unit ℝ := fun _ _ => 1
    let smallCoefficient : Unit → ℝ := fun _ => 2
    let zeroCoefficient : Unit → ℝ := fun _ => 0
    (taskOverlap source smallTarget).mulVec smallCoefficient =
        (fun _ => 1) ∧
      (taskOverlap source largeTarget).mulVec zeroCoefficient = 0 := by
  dsimp
  constructor <;>
    funext coordinate <;>
    cases coordinate <;>
    norm_num [taskOverlap, Matrix.mulVec, Matrix.mul_apply,
      dotProduct]

/-- The fixed-feature/NTK hypothesis is load-bearing.  A target direction may
be orthogonal to the stored source basis but aligned with a drifted source
basis, changing the current source prediction. -/
theorem staleZeroOverlap_currentDrift_nonzero :
    let storedSource : Matrix (Fin 2) Unit ℝ :=
      fun parameter _ => if parameter = 0 then 1 else 0
    let currentSource : Matrix (Fin 2) Unit ℝ :=
      fun parameter _ => if parameter = 1 then 1 else 0
    let target : Matrix (Fin 2) Unit ℝ :=
      fun parameter _ => if parameter = 1 then 1 else 0
    let coefficient : Unit → ℝ := fun _ => 1
    taskOverlap storedSource target = 0 ∧
      (taskOverlap currentSource target).mulVec coefficient =
        fun _ => 1 := by
  dsimp
  constructor
  · ext sourceCoordinate targetCoordinate
    cases sourceCoordinate
    cases targetCoordinate
    norm_num [taskOverlap, Matrix.mul_apply, Fin.sum_univ_two]
  · funext coordinate
    cases coordinate
    norm_num [taskOverlap, Matrix.mulVec, Matrix.mul_apply,
      dotProduct, Fin.sum_univ_two]

#print axioms targetInducedDrift_eq_overlap_mulVec
#print axioms sourcePredictionDrift_totalTaskUpdate
#print axioms oppositeTaskPackets_cancel_nonzero_intermediateDrift
#print axioms staleZeroOverlap_currentDrift_nonzero

end

end TaskOverlapForgetting

end Mettapedia.MachineLearning.ContinualLearning
