import Mettapedia.Languages.MeTTa.PureKernel.Universe.AlgebraicParallel
import Mettapedia.Languages.MeTTa.PureKernel.Universe.NativeIndexedFamilies

/-!
# Algebraic conversion coherence for native indexed families

The native List and identity eliminator equations are first presented as
three open algebraic schemas.  This module proves that their substitution
closure is exactly the root computation installed by the Prime running
hypothesis.  It then uses the generic algebraic parallel relation; the
remaining confluence theorem is the schema-overlap/complete-development
argument, not a hidden typing or checker premise.
-/

namespace Mettapedia.Languages.MeTTa.PureKernel.Universe
namespace NativeIndexedFamilies
namespace Intrinsic
namespace Confluence

open Presentation
open Presentation.Declaration
open Presentation.AlgebraicSchema
open Presentation.AlgebraicParallel

/-- The three open computation schemas currently selected by the native
strictly-positive family hypothesis. -/
inductive NativeSchema : SchemaFamily Tower.Head where
  | nil : NativeSchema nilIotaLeft nilIotaRight
  | cons : NativeSchema consIotaLeft consIotaRight
  | identity : NativeSchema identityIotaLeft identityIotaRight

/-- Every selected open schema and all of its substitutions are genuine
native root computations. -/
theorem nativeSchema_sound
    {arity ambient : Nat} {left right : Tower.Tm arity}
    (schema : NativeSchema left right)
    (substitution : Sub Tower.Head arity ambient) :
    rules.computation.step
      (Presentation.subst substitution left)
      (Presentation.subst substitution right) := by
  cases schema with
  | nil =>
      exact RootStep.declared
        ⟨(IotaEvidence.nil (.var 3) (.var 2) (.var 1) (.var 0)).substitute
          substitution⟩
  | cons =>
      exact RootStep.declared
        ⟨(IotaEvidence.cons (.var 5) (.var 4) (.var 3) (.var 2)
          (.var 1) (.var 0)).substitute substitution⟩
  | identity =>
      exact RootStep.declared
        ⟨(IotaEvidence.identity (.var 3) (.var 2) (.var 1) (.var 0)).substitute
          substitution⟩

private theorem iotaEvidence_schemaInstance
    {n : Nat} {source target : Tower.Tm n}
    (evidence : IotaEvidence n source target) :
    ∃ (arity : Nat) (left right : Tower.Tm arity)
        (substitution : Sub Tower.Head arity n),
      NativeSchema left right ∧
      Presentation.subst substitution left = source ∧
      Presentation.subst substitution right = target :=
  match evidence with
  | .nil element motive nilCase consCase =>
      ⟨4, nilIotaLeft, nilIotaRight,
        nilSchemaSubstitution element motive nilCase consCase,
        .nil, rfl, rfl⟩
  | .cons element motive nilCase consCase head tail =>
      ⟨6, consIotaLeft, consIotaRight,
        consSchemaSubstitution element motive nilCase consCase head tail,
        .cons, rfl, rfl⟩
  | .identity element point motive reflCase =>
      ⟨4, identityIotaLeft, identityIotaRight,
        identitySchemaSubstitution element point motive reflCase,
        .identity, rfl, rfl⟩

/-- Conversely, every native root computation exposes one selected open
schema and the exact substitution that generated it.  No endpoint-only tag
or post-hoc classification is used. -/
theorem nativeSchema_cover
    {n : Nat} {source target : Tower.Tm n}
    (step : rules.computation.step source target) :
    ∃ (arity : Nat) (left right : Tower.Tm arity)
        (substitution : Sub Tower.Head arity n),
      NativeSchema left right ∧
      Presentation.subst substitution left = source ∧
      Presentation.subst substitution right = target := by
  cases step with
  | inherited inherited => exact inherited.elim
  | delta unfolding =>
      rw [rawSignature_valueOf_none] at unfolding
      cases unfolding
  | declared declared =>
      rcases declared with ⟨evidence⟩
      exact iotaEvidence_schemaInstance evidence

/-- Prime's current native root computation, viewed as an exact algebraic
schema presentation. -/
def nativeSchemaPresentation : SchemaPresentation rules where
  schema := NativeSchema
  sound := nativeSchema_sound
  cover := nativeSchema_cover

/-- Parallel beta/sigma/head/iota reduction generated by the exact native
schemas. -/
abbrev NativePar {n : Nat} : Tower.Tm n → Tower.Tm n → Prop :=
  nativeSchemaPresentation.Par

/-- Positive control: the nil iota equation is a genuine algebraic parallel
step with the identity metavariable development. -/
theorem nilIota_parallel : NativePar nilIotaLeft nilIotaRight := by
  change ParRed rules.headEq NativeSchema nilIotaLeft nilIotaRight
  simpa only [Presentation.subst_ids] using
    (ParRed.algebraic NativeSchema.nil Presentation.ids Presentation.ids
      (parSub_refl Presentation.ids) :
        ParRed rules.headEq NativeSchema
          (Presentation.subst Presentation.ids nilIotaLeft)
          (Presentation.subst Presentation.ids nilIotaRight))

/-- Negative control: the selected schema family contains no equation that
reuses the nil left-hand side with the identity right-hand side. -/
theorem no_nil_to_identity_schema :
    ¬ NativeSchema nilIotaLeft identityIotaRight := by
  intro schema
  cases schema

/-! ## Metavariable geometry of the running hypothesis

These facts diagnose the exact limit of the elementary one-step complete-
development route.  They do not assert failure of confluence.  They show
that the current raw equations repeat parameters, so a confluence proof must
either retain residual coherence for repeated occurrences or justify a
left-linear presentation of the same typed computation.
-/

/-- The element parameter occurs twice in the raw nil eliminator equation:
once at the eliminator and once at the constructor. -/
theorem nilIota_element_multiplicity :
    variableMultiplicity (3 : Fin 4) nilIotaLeft = 2 := by
  rfl

/-- The element parameter is likewise repeated in the raw cons equation. -/
theorem consIota_element_multiplicity :
    variableMultiplicity (5 : Fin 6) consIotaLeft = 2 := by
  rfl

/-- The point parameter occurs at the eliminator, as its endpoint, and under
reflexivity in the raw identity equation. -/
theorem identityIota_point_multiplicity :
    variableMultiplicity (2 : Fin 4) identityIotaLeft = 3 := by
  rfl

theorem nilIota_not_leftLinear : ¬ LeftLinear nilIotaLeft :=
  not_leftLinear_of_repeatedAt (by
    unfold RepeatedAt
    rw [nilIota_element_multiplicity])

theorem consIota_not_leftLinear : ¬ LeftLinear consIotaLeft :=
  not_leftLinear_of_repeatedAt (by
    unfold RepeatedAt
    rw [consIota_element_multiplicity])

theorem identityIota_not_leftLinear : ¬ LeftLinear identityIotaLeft :=
  not_leftLinear_of_repeatedAt (by
    unfold RepeatedAt
    rw [identityIota_point_multiplicity]
    omega)

/-- Consequently the selected native schema family is not left-linear.  This
is a property of the raw presentation, not a defect in the proof-carrying
typed family mechanism. -/
theorem nativeSchema_not_leftLinearFamily :
    ¬ LeftLinearFamily NativeSchema := by
  intro linear
  exact nilIota_not_leftLinear (linear NativeSchema.nil)

/-! ## The informative occurrence-separated presentation

The repeated authored variables above are contractions of distinct
occurrence variables.  The following presentation exposes those variables
before contraction.  It is strictly more informative than the raw equations:
contracting it recovers every raw equation exactly, while the non-injective
maps retain where the equalities came from.

This section does not install the separated schemas as computation rules.
Doing so would license raw mismatched parameters unless the execution relation
also carries an appropriate coherence witness.  The point here is to isolate
that remaining obligation precisely. -/

/-- Nil iota with the eliminator element parameter and constructor element
parameter represented by distinct occurrence variables. -/
def nilOccurrenceLeft : Tower.Tm 5 :=
  eliminateApp (.var 4) (.var 3) (.var 2) (.var 1) (nilApp (.var 0))

def nilOccurrenceRight : Tower.Tm 5 := .var 2

/-- The two element occurrences contract to authored variable 3. -/
def nilOccurrenceContraction : Ren 5 4 := ![3, 0, 1, 2, 3]

theorem nilOccurrenceLeft_leftLinear : LeftLinear nilOccurrenceLeft := by
  intro index
  refine Fin.cases (by decide) (fun first =>
    Fin.cases (by decide) (fun second =>
        Fin.cases (by decide) (fun third =>
          Fin.cases (by decide) (fun fourth =>
          Fin.cases (by decide) (fun impossible => Fin.elim0 impossible)
            fourth) third) second) first) index

def nilOccurrenceSeparation :
    OccurrenceSeparatedRule nilIotaLeft nilIotaRight where
  occurrenceArity := 5
  skeletonLeft := nilOccurrenceLeft
  skeletonRight := nilOccurrenceRight
  contraction := nilOccurrenceContraction
  contractsLeft := by decide
  contractsRight := by decide
  separatedLeft := nilOccurrenceLeft_leftLinear

/-- Chosen occurrence representatives for the four authored nil-schema
metavariables.  The second copy of the element parameter remains visible in
the occurrence telescope but is not needed as a representative. -/
def nilOccurrenceRepresentative : Ren 4 5 := ![1, 2, 3, 4]

def nilOccurrenceSplit :
    nilOccurrenceSeparation.SplitContraction where
  representative := nilOccurrenceRepresentative
  rightInverse := by decide

/-- Cons iota with distinct eliminator and constructor element occurrences. -/
def consOccurrenceLeft : Tower.Tm 7 :=
  eliminateApp (.var 6) (.var 4) (.var 3) (.var 2)
    (consApp (.var 5) (.var 1) (.var 0))

def consOccurrenceRight : Tower.Tm 7 :=
  .app
    (.app
      (.app (.var 2) (.var 1))
      (.var 0))
    (eliminateApp (.var 6) (.var 4) (.var 3) (.var 2) (.var 0))

/-- Occurrence variables 5 and 6 both contract to authored element variable
5; the remaining constructor and branch variables retain their indices. -/
def consOccurrenceContraction : Ren 7 6 := ![0, 1, 2, 3, 4, 5, 5]

theorem consOccurrenceLeft_leftLinear : LeftLinear consOccurrenceLeft := by
  intro index
  refine Fin.cases (by decide) (fun first =>
    Fin.cases (by decide) (fun second =>
      Fin.cases (by decide) (fun third =>
        Fin.cases (by decide) (fun fourth =>
          Fin.cases (by decide) (fun fifth =>
            Fin.cases (by decide) (fun sixth =>
              Fin.cases (by decide) (fun impossible => Fin.elim0 impossible)
                sixth) fifth) fourth) third)
          second) first) index

def consOccurrenceSeparation :
    OccurrenceSeparatedRule consIotaLeft consIotaRight where
  occurrenceArity := 7
  skeletonLeft := consOccurrenceLeft
  skeletonRight := consOccurrenceRight
  contraction := consOccurrenceContraction
  contractsLeft := by decide
  contractsRight := by decide
  separatedLeft := consOccurrenceLeft_leftLinear

def consOccurrenceRepresentative : Ren 6 7 := ![0, 1, 2, 3, 4, 5]

def consOccurrenceSplit :
    consOccurrenceSeparation.SplitContraction where
  representative := consOccurrenceRepresentative
  rightInverse := by decide

/-- Identity iota with the fixed point, endpoint, and reflexivity point as
three distinct occurrences. -/
def identityOccurrenceLeft : Tower.Tm 6 :=
  identityEliminateApp (.var 5) (.var 4) (.var 1) (.var 0)
    (.var 3) (.refl (.var 2))

def identityOccurrenceRight : Tower.Tm 6 := .var 0

/-- Occurrence variables 2, 3, and 4 contract to authored point variable 2. -/
def identityOccurrenceContraction : Ren 6 4 := ![0, 1, 2, 2, 2, 3]

theorem identityOccurrenceLeft_leftLinear :
    LeftLinear identityOccurrenceLeft := by
  intro index
  refine Fin.cases (by decide) (fun first =>
    Fin.cases (by decide) (fun second =>
      Fin.cases (by decide) (fun third =>
        Fin.cases (by decide) (fun fourth =>
          Fin.cases (by decide) (fun fifth =>
            Fin.cases (by decide) (fun impossible => Fin.elim0 impossible)
              fifth) fourth) third) second) first)
      index

def identityOccurrenceSeparation :
    OccurrenceSeparatedRule identityIotaLeft identityIotaRight where
  occurrenceArity := 6
  skeletonLeft := identityOccurrenceLeft
  skeletonRight := identityOccurrenceRight
  contraction := identityOccurrenceContraction
  contractsLeft := by decide
  contractsRight := by decide
  separatedLeft := identityOccurrenceLeft_leftLinear

def identityOccurrenceRepresentative : Ren 4 6 := ![0, 1, 2, 5]

def identityOccurrenceSplit :
    identityOccurrenceSeparation.SplitContraction where
  representative := identityOccurrenceRepresentative
  rightInverse := by decide

/-! Each native occurrence presentation now inherits the generic exact-image
theorem.  These statements characterize the diagonal subrelation precisely;
they still do not authorize the unrestricted occurrence schemas as root
computation. -/

theorem nilCoherentOccurrence_iff_authoredInstance
    (source target : Tower.Tm ambient) :
    nilOccurrenceSeparation.CoherentOccurrenceInstance source target ↔
      nilOccurrenceSeparation.AuthoredInstance source target :=
  nilOccurrenceSeparation.coherentOccurrenceInstance_iff_authoredInstance
    nilOccurrenceSplit source target

theorem consCoherentOccurrence_iff_authoredInstance
    (source target : Tower.Tm ambient) :
    consOccurrenceSeparation.CoherentOccurrenceInstance source target ↔
      consOccurrenceSeparation.AuthoredInstance source target :=
  consOccurrenceSeparation.coherentOccurrenceInstance_iff_authoredInstance
    consOccurrenceSplit source target

theorem identityCoherentOccurrence_iff_authoredInstance
    (source target : Tower.Tm ambient) :
    identityOccurrenceSeparation.CoherentOccurrenceInstance source target ↔
      identityOccurrenceSeparation.AuthoredInstance source target :=
  identityOccurrenceSeparation.coherentOccurrenceInstance_iff_authoredInstance
    identityOccurrenceSplit source target

/-! Conversion-coherent separated instances are conservative over Prime's
authored conversion relation.  This is the usable positive side of the
nonlinearity boundary: the informative skeleton may retain independently
developed occurrences together with their conversion receipts, while raw
root computation remains exactly the authored equations. -/

theorem nilOccurrenceInstance_conv_of_fibreEvidence
    {substitution : Sub Tower.Head 5 ambient}
    (evidence : nilOccurrenceSeparation.FibreEvidence
      (fun left right =>
        Conv rules.headEq left right rules.computation)
      substitution) :
    Conv rules.headEq
      (Presentation.subst substitution nilOccurrenceLeft)
      (Presentation.subst substitution nilOccurrenceRight)
      rules.computation :=
  nilOccurrenceSplit.occurrenceInstance_conv_of_fibreEvidence
    rules.headEq rules.computation evidence
    (nativeSchema_sound NativeSchema.nil
      (nilOccurrenceSplit.contractSubstitution substitution))

theorem consOccurrenceInstance_conv_of_fibreEvidence
    {substitution : Sub Tower.Head 7 ambient}
    (evidence : consOccurrenceSeparation.FibreEvidence
      (fun left right =>
        Conv rules.headEq left right rules.computation)
      substitution) :
    Conv rules.headEq
      (Presentation.subst substitution consOccurrenceLeft)
      (Presentation.subst substitution consOccurrenceRight)
      rules.computation :=
  consOccurrenceSplit.occurrenceInstance_conv_of_fibreEvidence
    rules.headEq rules.computation evidence
    (nativeSchema_sound NativeSchema.cons
      (consOccurrenceSplit.contractSubstitution substitution))

theorem identityOccurrenceInstance_conv_of_fibreEvidence
    {substitution : Sub Tower.Head 6 ambient}
    (evidence : identityOccurrenceSeparation.FibreEvidence
      (fun left right =>
        Conv rules.headEq left right rules.computation)
      substitution) :
    Conv rules.headEq
      (Presentation.subst substitution identityOccurrenceLeft)
      (Presentation.subst substitution identityOccurrenceRight)
      rules.computation :=
  identityOccurrenceSplit.occurrenceInstance_conv_of_fibreEvidence
    rules.headEq rules.computation evidence
    (nativeSchema_sound NativeSchema.identity
      (identityOccurrenceSplit.contractSubstitution substitution))

/-- The occurrence-separated native schema family.  Unlike `NativeSchema`,
its left sides are all left-linear. -/
inductive NativeOccurrenceSchema : SchemaFamily Tower.Head where
  | nil : NativeOccurrenceSchema nilOccurrenceLeft nilOccurrenceRight
  | cons : NativeOccurrenceSchema consOccurrenceLeft consOccurrenceRight
  | identity :
      NativeOccurrenceSchema identityOccurrenceLeft identityOccurrenceRight

theorem nativeOccurrenceSchema_leftLinearFamily :
    LeftLinearFamily NativeOccurrenceSchema := by
  intro arity left right schema
  cases schema with
  | nil => exact nilOccurrenceLeft_leftLinear
  | cons => exact consOccurrenceLeft_leftLinear
  | identity => exact identityOccurrenceLeft_leftLinear

/-- Every raw native schema carries its exact occurrence-separated receipt. -/
abbrev nativeSchema_occurrenceSeparated :
    OccurrenceSeparatedFamily NativeSchema := by
  intro arity left right schema
  cases schema with
  | nil => exact ⟨nilOccurrenceSeparation⟩
  | cons => exact ⟨consOccurrenceSeparation⟩
  | identity => exact ⟨identityOccurrenceSeparation⟩

/-- Every ordinary instance of a native raw schema is exactly the contraction
of an instance of the occurrence-separated family.  Thus separating
occurrences loses no existing computation; the unresolved question is which
coherence evidence licenses additional separated instances. -/
theorem nativeSchema_exactOccurrenceInstance
    {arity ambient : Nat} {left right : Tower.Tm arity}
    (schema : NativeSchema left right)
    (substitution : Sub Tower.Head arity ambient) :
    ∃ (occurrenceArity : Nat)
        (occurrenceLeft occurrenceRight : Tower.Tm occurrenceArity)
        (occurrenceSubstitution : Sub Tower.Head occurrenceArity ambient),
      NativeOccurrenceSchema occurrenceLeft occurrenceRight ∧
      Presentation.subst occurrenceSubstitution occurrenceLeft =
        Presentation.subst substitution left ∧
      Presentation.subst occurrenceSubstitution occurrenceRight =
        Presentation.subst substitution right := by
  cases schema with
  | nil =>
      exact ⟨5, nilOccurrenceLeft, nilOccurrenceRight,
        nilOccurrenceSeparation.expandSubstitution substitution,
        .nil,
        nilOccurrenceSeparation.subst_skeletonLeft substitution,
        nilOccurrenceSeparation.subst_skeletonRight substitution⟩
  | cons =>
      exact ⟨7, consOccurrenceLeft, consOccurrenceRight,
        consOccurrenceSeparation.expandSubstitution substitution,
        .cons,
        consOccurrenceSeparation.subst_skeletonLeft substitution,
        consOccurrenceSeparation.subst_skeletonRight substitution⟩
  | identity =>
      exact ⟨6, identityOccurrenceLeft, identityOccurrenceRight,
        identityOccurrenceSeparation.expandSubstitution substitution,
        .identity,
        identityOccurrenceSeparation.subst_skeletonLeft substitution,
        identityOccurrenceSeparation.subst_skeletonRight substitution⟩

theorem nilOccurrenceContraction_not_injective :
    ¬ Function.Injective nilOccurrenceContraction := by
  intro injective
  have equality : (0 : Fin 5) = 4 := injective rfl
  omega

theorem consOccurrenceContraction_not_injective :
    ¬ Function.Injective consOccurrenceContraction := by
  intro injective
  have equality : (5 : Fin 7) = 6 := injective rfl
  omega

theorem identityOccurrenceContraction_not_injective :
    ¬ Function.Injective identityOccurrenceContraction := by
  intro injective
  have equality : (2 : Fin 6) = 3 := injective rfl
  omega

/-! ## Axiom audit -/

#print axioms nativeSchema_sound
#print axioms nativeSchema_cover
#print axioms nativeSchemaPresentation
#print axioms nilIota_parallel
#print axioms no_nil_to_identity_schema
#print axioms nilIota_element_multiplicity
#print axioms consIota_element_multiplicity
#print axioms identityIota_point_multiplicity
#print axioms nilIota_not_leftLinear
#print axioms consIota_not_leftLinear
#print axioms identityIota_not_leftLinear
#print axioms nativeSchema_not_leftLinearFamily
#print axioms nilOccurrenceLeft_leftLinear
#print axioms consOccurrenceLeft_leftLinear
#print axioms identityOccurrenceLeft_leftLinear
#print axioms nativeOccurrenceSchema_leftLinearFamily
#print axioms nativeSchema_occurrenceSeparated
#print axioms nativeSchema_exactOccurrenceInstance
#print axioms nilOccurrenceSplit
#print axioms consOccurrenceSplit
#print axioms identityOccurrenceSplit
#print axioms nilCoherentOccurrence_iff_authoredInstance
#print axioms consCoherentOccurrence_iff_authoredInstance
#print axioms identityCoherentOccurrence_iff_authoredInstance
#print axioms nilOccurrenceInstance_conv_of_fibreEvidence
#print axioms consOccurrenceInstance_conv_of_fibreEvidence
#print axioms identityOccurrenceInstance_conv_of_fibreEvidence
#print axioms nilOccurrenceContraction_not_injective
#print axioms consOccurrenceContraction_not_injective
#print axioms identityOccurrenceContraction_not_injective

end Confluence
end Intrinsic
end NativeIndexedFamilies
end Mettapedia.Languages.MeTTa.PureKernel.Universe
