import Mettapedia.GraphTheory.Representation.EdgeListToMatrixGSLT
import Mettapedia.GraphTheory.Representation.MultiView

/-!
# Worked representation-migration decisions

This module instantiates the exact break-even laws with graph workloads that
distinguish query-driven, edge-driven, and revision-heavy use.  The unit is an
authored structural event: one consumed edge occurrence, one queried edge-list
occurrence, one matrix-cell read, or one synchronized occurrence update.  It
is not a wall-clock model.

The construction account comes from the detailed edge-list-to-matrix machine:
`m` edge occurrences require `m + 1` rewrites.  An absent edge-list query
inspects all `m` occurrences, whereas a matrix query reads one cell.  Storage
counts follow the existing representation definitions: `2m` endpoint cells
for the edge list and `n²` Boolean cells for the matrix.
-/

namespace Mettapedia.GraphTheory.Representation.MigrationExamples

open Mettapedia.GraphTheory.Representation
open Mettapedia.GraphTheory.Representation.MultiView

set_option autoImplicit false

/-- The dimensions needed by the selected structural-event model. -/
structure Scenario where
  vertexCount : Nat
  edgeOccurrences : Nat
deriving DecidableEq, Repr

namespace Scenario

/-- One write rewrite per edge occurrence and one finalization rewrite. -/
def materializationEvents (scenario : Scenario) : Nat :=
  scenario.edgeOccurrences + 1

/-- A certified absent edge requires a complete edge-list scan. -/
def absentEdgeListQueryEvents (scenario : Scenario) : Nat :=
  scenario.edgeOccurrences

/-- An adjacency-matrix query performs one cell read. -/
def matrixQueryEvents (_scenario : Scenario) : Nat := 1

/-- Streaming all authored edge occurrences once. -/
def edgeListEnumerationEvents (scenario : Scenario) : Nat :=
  scenario.edgeOccurrences

/-- Scanning all ordered matrix coordinates once. -/
def matrixEnumerationEvents (scenario : Scenario) : Nat :=
  scenario.vertexCount * scenario.vertexCount

/-- Endpoint-cell account for an edge-list payload with `m` occurrences. -/
def edgeListCells (scenario : Scenario) : Nat :=
  2 * scenario.edgeOccurrences

/-- Boolean-cell account for the dense matrix payload. -/
def matrixCells (scenario : Scenario) : Nat :=
  scenario.vertexCount * scenario.vertexCount

/-- Retaining both representations simultaneously. -/
def channelledCells (scenario : Scenario) : Nat :=
  channelledStorage scenario.edgeListCells scenario.matrixCells

end Scenario

/-! ## Query-centric constraint generation -/

/-- A sparse 200-vertex instance with 800 distinct undirected edges.  Such an
instance has 19,100 absent unordered vertex pairs. -/
def sparseConstraintGraph : Scenario where
  vertexCount := 200
  edgeOccurrences := 800

def sparseConstraintAbsentPairs : Nat := 19_100

/-- Arithmetic check for the absent unordered pairs in the selected distinct,
loopless 200-vertex instance. -/
theorem sparse_constraint_absent_pair_count :
    sparseConstraintAbsentPairs = 200 * 199 / 2 - 800 := by
  decide

/-- Positive example: when a model generator probes every absent pair, paying
801 construction events is repaid by replacing 19,100 full 800-occurrence
scans with one-cell reads. -/
theorem sparse_constraint_migration_wins :
    migrateTime sparseConstraintGraph.materializationEvents
        sparseConstraintAbsentPairs sparseConstraintGraph.matrixQueryEvents <
      stayTime sparseConstraintAbsentPairs
        sparseConstraintGraph.absentEdgeListQueryEvents := by
  decide

theorem sparse_constraint_event_totals :
    stayTime sparseConstraintAbsentPairs
        sparseConstraintGraph.absentEdgeListQueryEvents = 15_280_000 ∧
      migrateTime sparseConstraintGraph.materializationEvents
        sparseConstraintAbsentPairs sparseConstraintGraph.matrixQueryEvents =
          19_901 := by
  decide

/-! ## Edge-centric constraint generation -/

/-- Negative example: graph-colouring constraints can be generated by
streaming the 800 authored edges once.  Materializing a matrix and scanning
all 200² coordinates adds work instead of removing it. -/
theorem edge_driven_colouring_keeps_edge_list :
    sparseConstraintGraph.edgeListEnumerationEvents <
      sparseConstraintGraph.materializationEvents +
        sparseConstraintGraph.matrixEnumerationEvents := by
  decide

theorem edge_driven_event_totals :
    sparseConstraintGraph.edgeListEnumerationEvents = 800 ∧
      sparseConstraintGraph.materializationEvents +
          sparseConstraintGraph.matrixEnumerationEvents = 40_801 := by
  decide

/-! ## Dynamic coherent views -/

/-- A larger sparse graph used for mixed revision/query forecasts. -/
def revisedSparseGraph : Scenario where
  vertexCount := 1_000
  edgeOccurrences := 3_000

/-- Positive example under the selected unit edit/synchronization grades: ten
absent-edge probes repay initial construction and twenty-five synchronized
edits. -/
theorem read_heavy_channel_wins :
    channelledViewTime revisedSparseGraph.materializationEvents
        25 1 1 10 revisedSparseGraph.matrixQueryEvents <
      singleViewTime 25 1 10
        revisedSparseGraph.absentEdgeListQueryEvents := by
  decide

theorem read_heavy_event_totals :
    channelledViewTime revisedSparseGraph.materializationEvents
        25 1 1 10 revisedSparseGraph.matrixQueryEvents = 3_061 ∧
      singleViewTime 25 1 10
        revisedSparseGraph.absentEdgeListQueryEvents = 30_025 := by
  decide

/-- Negative example: with four thousand edits and one query, synchronizing
the dense view is slower than retaining only the edge list. -/
theorem revision_heavy_source_wins :
    singleViewTime 4_000 1 1
        revisedSparseGraph.absentEdgeListQueryEvents <
      channelledViewTime revisedSparseGraph.materializationEvents
        4_000 1 1 1 revisedSparseGraph.matrixQueryEvents := by
  decide

theorem revision_heavy_event_totals :
    singleViewTime 4_000 1 1
        revisedSparseGraph.absentEdgeListQueryEvents = 7_000 ∧
      channelledViewTime revisedSparseGraph.materializationEvents
        4_000 1 1 1 revisedSparseGraph.matrixQueryEvents = 11_002 := by
  decide

/-- A time-winning maintained view can still violate its retained-space
budget.  Here 6,000 endpoint cells plus 1,000,000 matrix cells exceed the
750,000-cell budget. -/
theorem read_heavy_time_win_but_space_loss :
    channelledViewTime revisedSparseGraph.materializationEvents
        25 1 1 10 revisedSparseGraph.matrixQueryEvents <
        singleViewTime 25 1 10
          revisedSparseGraph.absentEdgeListQueryEvents ∧
      ¬ FitsSpace 750_000 revisedSparseGraph.channelledCells := by
  constructor
  · decide
  · simp [FitsSpace, Scenario.channelledCells, channelledStorage,
      Scenario.edgeListCells, Scenario.matrixCells, revisedSparseGraph]

theorem revised_sparse_storage_totals :
    revisedSparseGraph.edgeListCells = 6_000 ∧
      revisedSparseGraph.matrixCells = 1_000_000 ∧
      revisedSparseGraph.channelledCells = 1_006_000 := by
  decide

#print axioms sparse_constraint_migration_wins
#print axioms edge_driven_colouring_keeps_edge_list
#print axioms read_heavy_channel_wins
#print axioms revision_heavy_source_wins
#print axioms read_heavy_time_win_but_space_loss

end Mettapedia.GraphTheory.Representation.MigrationExamples
