import Mettapedia.MachineLearning.NeuralNetworks.Architecture.ExecutionSemantics

/-!
# Autonomous control and scheduled execution

An external schedule and an internally generated control trajectory are
different mechanisms even when they expose the same observations.  This file
defines an autonomous controller over an existing state carrier, proves the
exact scheduled trace generated by that controller, and states conditions
under which observations identify the command schedule.

The results are finite and transition-level.  They do not assume a
continuous-time heteroclinic realization.
-/

namespace Mettapedia.MachineLearning.NeuralNetworks.Architecture

open StateCarrier

universe uEnvironment uSlow uCommand uState uRead uRoute uProposal
  uObservation uPolicy uControl

variable {Environment : Type uEnvironment} {Slow : Type uSlow}
  {Command : Type uCommand} {State : Type uState} {Read : Type uRead}
  {Route : Type uRoute} {Proposal : Type uProposal}
  {Observation : Type uObservation} {Policy : Type uPolicy}
  {Control : Type uControl}

/-- An internal controller selects the next carrier command and updates its
private control state after seeing the realized carrier transition. -/
structure AutonomousController
    (Environment : Type uEnvironment) (Slow : Type uSlow)
    (Command : Type uCommand) (State : Type uState)
    (Control : Type uControl) where
  select : Environment → Slow → Control → State → Command
  advance : Environment → Slow → Control → State → Command → State → Control

/-- Joint controller/carrier configuration. -/
abbrev AutonomousConfiguration (Control : Type uControl) (State : Type uState) :=
  Control × State

/-- One internally controlled carrier transition. -/
def autonomousStep
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (controller : AutonomousController Environment Slow Command State Control)
    (environment : Environment) (slow : Slow)
    (configuration : AutonomousConfiguration Control State) :
    AutonomousConfiguration Control State :=
  let command := controller.select environment slow
    configuration.1 configuration.2
  let nextState := carrier.step environment slow command configuration.2
  (controller.advance environment slow configuration.1 configuration.2
      command nextState,
    nextState)

/-- Commands generated by the internal controller over a finite horizon. -/
def generatedCommands
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (controller : AutonomousController Environment Slow Command State Control)
    (environment : Environment) (slow : Slow) :
    AutonomousConfiguration Control State → Nat → List Command
  | _configuration, 0 => []
  | configuration, steps + 1 =>
      controller.select environment slow configuration.1 configuration.2 ::
        generatedCommands carrier controller environment slow
          (autonomousStep carrier controller environment slow configuration) steps

/-- Joint finite trajectory of the controller and carrier, including the
initial configuration. -/
def autonomousTrajectory
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (controller : AutonomousController Environment Slow Command State Control)
    (environment : Environment) (slow : Slow) :
    AutonomousConfiguration Control State → Nat →
      List (AutonomousConfiguration Control State)
  | configuration, 0 => [configuration]
  | configuration, steps + 1 =>
      configuration :: autonomousTrajectory carrier controller environment slow
        (autonomousStep carrier controller environment slow configuration) steps

/-- Observation trace of an internally controlled execution. -/
def autonomousObservationTrajectory
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (controller : AutonomousController Environment Slow Command State Control)
    (environment : Environment) (slow : Slow)
    (configuration : AutonomousConfiguration Control State) (steps : Nat) :
    List Observation :=
  (autonomousTrajectory carrier controller environment slow configuration steps).map
    (fun current =>
      carrier.observeAtState environment slow current.2)

/-- The internally controlled carrier-state trace is exactly the scheduled
trace under the commands generated by the controller. -/
theorem autonomousTrajectory_map_state_eq_scheduled
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (controller : AutonomousController Environment Slow Command State Control)
    (environment : Environment) (slow : Slow) :
    ∀ configuration steps,
      (autonomousTrajectory carrier controller environment slow configuration
          steps).map Prod.snd =
        carrier.trajectory environment slow configuration.2
          (generatedCommands carrier controller environment slow configuration
            steps)
  | _configuration, 0 => rfl
  | configuration, steps + 1 => by
      simp only [autonomousTrajectory, generatedCommands,
        StateCarrier.trajectory_cons, List.map_cons]
      rw [autonomousTrajectory_map_state_eq_scheduled carrier controller
        environment slow
        (autonomousStep carrier controller environment slow configuration) steps]
      rfl

/-- Observation-level form of the exact internal-to-scheduled simulation. -/
theorem autonomousObservationTrajectory_eq_scheduled
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (controller : AutonomousController Environment Slow Command State Control)
    (environment : Environment) (slow : Slow)
    (configuration : AutonomousConfiguration Control State) (steps : Nat) :
    autonomousObservationTrajectory carrier controller environment slow
        configuration steps =
      carrier.observationTrajectory environment slow configuration.2
        (generatedCommands carrier controller environment slow configuration
          steps) := by
  unfold autonomousObservationTrajectory StateCarrier.observationTrajectory
  calc
    List.map (fun current =>
        carrier.observeAtState environment slow current.2)
        (autonomousTrajectory carrier controller environment slow
          configuration steps) =
      List.map (carrier.observeAtState environment slow)
        (List.map Prod.snd
          (autonomousTrajectory carrier controller environment slow
            configuration steps)) := by
          rw [List.map_map]
          rfl
    _ = List.map (carrier.observeAtState environment slow)
        (carrier.trajectory environment slow configuration.2
          (generatedCommands carrier controller environment slow configuration
            steps)) :=
      congrArg (List.map (carrier.observeAtState environment slow))
        (autonomousTrajectory_map_state_eq_scheduled carrier controller
          environment slow configuration steps)

/-- Every internally generated horizon contains exactly that many commands. -/
theorem generatedCommands_length
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (controller : AutonomousController Environment Slow Command State Control)
    (environment : Environment) (slow : Slow) :
    ∀ configuration steps,
      (generatedCommands carrier controller environment slow configuration
        steps).length = steps
  | _configuration, 0 => rfl
  | configuration, steps + 1 => by
      simp only [generatedCommands, List.length_cons]
      rw [generatedCommands_length carrier controller environment slow
        (autonomousStep carrier controller environment slow configuration) steps]

/-! ## Explicit schedule clamping -/

/-- A controller whose private state is an external schedule.  During the
declared horizon it emits the head command and advances to the tail. -/
def replayController [Inhabited Command] :
    AutonomousController Environment Slow Command State (List Command) where
  select := fun _environment _slow commands _state =>
    commands.headD default
  advance := fun _environment _slow commands _state _command _nextState =>
    commands.tail

/-- Clamping the internal controller to a finite schedule recovers that exact
command sequence, not merely the same execution-regime label. -/
theorem replayController_generatedCommands [Inhabited Command]
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (environment : Environment) (slow : Slow) :
    ∀ commands state,
      generatedCommands carrier replayController environment slow
        (commands, state) commands.length = commands
  | [], _state => rfl
  | command :: commands, state => by
      simp only [List.length_cons, generatedCommands, replayController,
        List.headD_cons, autonomousStep, List.tail_cons]
      exact congrArg (List.cons command)
        (replayController_generatedCommands carrier environment slow commands
          (carrier.step environment slow command state))

/-- Transition-level clamping theorem: the carrier component of the internal
trajectory equals ordinary scheduled execution pointwise. -/
theorem replayController_trajectory_eq_scheduled [Inhabited Command]
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (environment : Environment) (slow : Slow)
    (commands : List Command) (state : State) :
    (autonomousTrajectory carrier replayController environment slow
        (commands, state) commands.length).map Prod.snd =
      carrier.trajectory environment slow state commands := by
  rw [autonomousTrajectory_map_state_eq_scheduled,
    replayController_generatedCommands]

/-- Observation-level clamping follows from the transition-level theorem. -/
theorem replayController_observation_eq_scheduled [Inhabited Command]
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (environment : Environment) (slow : Slow)
    (commands : List Command) (state : State) :
    autonomousObservationTrajectory carrier replayController environment slow
        (commands, state) commands.length =
      carrier.observationTrajectory environment slow state commands := by
  rw [autonomousObservationTrajectory_eq_scheduled,
    replayController_generatedCommands]

/-! ## When observations identify the controlling schedule -/

/-- One-step observations separate commands when two commands with the same
pre-state cannot produce the same next observation. -/
def ObservationSeparatesCommands
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (environment : Environment) (slow : Slow) : Prop :=
  ∀ state first second,
    carrier.observeAtState environment slow
        (carrier.step environment slow first state) =
      carrier.observeAtState environment slow
        (carrier.step environment slow second state) →
    first = second

/-- Every observation trajectory starts with the supplied state's
observation, independently of the remaining schedule. -/
theorem observationTrajectory_head?
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (environment : Environment) (slow : Slow) (state : State)
    (commands : List Command) :
    (carrier.observationTrajectory environment slow state commands).head? =
      some (carrier.observeAtState environment slow state) := by
  unfold StateCarrier.observationTrajectory
  rw [List.head?_map, StateCarrier.trajectory_head?]
  rfl

/-- Observation trajectories contain one more element than their command
schedules. -/
theorem observationTrajectory_length
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (environment : Environment) (slow : Slow) (state : State)
    (commands : List Command) :
    (carrier.observationTrajectory environment slow state commands).length =
      commands.length + 1 := by
  unfold StateCarrier.observationTrajectory
  rw [List.length_map, StateCarrier.trajectory_length]

/-- Under one-step command separation, the complete observation trajectory
identifies the finite command schedule. -/
theorem commands_eq_of_observationTrajectory_eq
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (environment : Environment) (slow : Slow)
    (separates : ObservationSeparatesCommands carrier environment slow) :
    ∀ state first second,
      carrier.observationTrajectory environment slow state first =
          carrier.observationTrajectory environment slow state second →
        first = second
  | _state, [], [], _equal => rfl
  | state, [], _command :: _commands, equal => by
      have lengths := congrArg List.length equal
      rw [observationTrajectory_length, observationTrajectory_length] at lengths
      have commandLengths := Nat.add_right_cancel lengths
      simp at commandLengths
  | state, _command :: _commands, [], equal => by
      have lengths := congrArg List.length equal
      rw [observationTrajectory_length, observationTrajectory_length] at lengths
      have commandLengths := Nat.add_right_cancel lengths
      simp at commandLengths
  | state, firstCommand :: firstCommands, secondCommand :: secondCommands,
      equal => by
      have tailsEqual :
          carrier.observationTrajectory environment slow
              (carrier.step environment slow firstCommand state) firstCommands =
            carrier.observationTrajectory environment slow
              (carrier.step environment slow secondCommand state) secondCommands := by
        simpa only [StateCarrier.observationTrajectory,
          StateCarrier.trajectory, List.map_cons] using (List.cons.inj equal).2
      have nextObservationsEqual :
          carrier.observeAtState environment slow
              (carrier.step environment slow firstCommand state) =
            carrier.observeAtState environment slow
              (carrier.step environment slow secondCommand state) := by
        have headsEqual := congrArg List.head? tailsEqual
        rw [observationTrajectory_head?, observationTrajectory_head?] at headsEqual
        exact Option.some.inj headsEqual
      have commandEqual : firstCommand = secondCommand :=
        separates state firstCommand secondCommand nextObservationsEqual
      subst secondCommand
      have remainingEqual :=
        commands_eq_of_observationTrajectory_eq carrier environment slow
          separates (carrier.step environment slow firstCommand state)
          firstCommands secondCommands tailsEqual
      exact congrArg (List.cons firstCommand) remainingEqual

/-- With command-separating observations, an internal control trajectory is
observationally equivalent to an external schedule exactly when it generated
that schedule. -/
theorem autonomous_observation_eq_scheduled_iff_generatedCommands_eq
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (controller : AutonomousController Environment Slow Command State Control)
    (environment : Environment) (slow : Slow)
    (separates : ObservationSeparatesCommands carrier environment slow)
    (configuration : AutonomousConfiguration Control State)
    (steps : Nat) (commands : List Command) :
    autonomousObservationTrajectory carrier controller environment slow
          configuration steps =
        carrier.observationTrajectory environment slow configuration.2 commands ↔
      generatedCommands carrier controller environment slow configuration steps =
        commands := by
  rw [autonomousObservationTrajectory_eq_scheduled]
  constructor
  · exact commands_eq_of_observationTrajectory_eq carrier environment slow
      separates configuration.2 _ commands
  · intro equal
    rw [equal]

/-! ## Halting is a separate execution certificate -/

/-- A declared halting predicate over the internal control and carrier state.
The predicate is data; absorption is a separate proof obligation below. -/
def DeclaredHalt
    (halt : Environment → Slow → Control → State → Prop)
    (environment : Environment) (slow : Slow)
    (configuration : AutonomousConfiguration Control State) : Prop :=
  halt environment slow configuration.1 configuration.2

/-- A declared halt is operationally sound when every halted joint
configuration is fixed by the internally controlled transition. -/
def AbsorbingHalt
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (controller : AutonomousController Environment Slow Command State Control)
    (halt : Environment → Slow → Control → State → Prop)
    (environment : Environment) (slow : Slow) : Prop :=
  ∀ configuration,
    DeclaredHalt halt environment slow configuration →
      autonomousStep carrier controller environment slow configuration =
        configuration

/-- An absorbing declared halt yields a constant joint trajectory for every
remaining finite horizon. -/
theorem autonomousTrajectory_eq_replicate_of_absorbingHalt
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (controller : AutonomousController Environment Slow Command State Control)
    (halt : Environment → Slow → Control → State → Prop)
    (environment : Environment) (slow : Slow)
    (absorbing : AbsorbingHalt carrier controller halt environment slow)
    (configuration : AutonomousConfiguration Control State)
    (halted : DeclaredHalt halt environment slow configuration) :
    ∀ steps,
      autonomousTrajectory carrier controller environment slow configuration
          steps =
        List.replicate (steps + 1) configuration
  | 0 => rfl
  | steps + 1 => by
      simp only [autonomousTrajectory]
      rw [absorbing configuration halted]
      rw [autonomousTrajectory_eq_replicate_of_absorbingHalt carrier controller
        halt environment slow absorbing configuration halted steps]
      simp [List.replicate_succ, Nat.add_assoc]

/-- An absorbing halt also yields a constant observation trajectory. -/
theorem autonomousObservationTrajectory_eq_replicate_of_absorbingHalt
    (carrier : StateCarrier Environment Slow Command State Read Route Proposal
      Observation Policy)
    (controller : AutonomousController Environment Slow Command State Control)
    (halt : Environment → Slow → Control → State → Prop)
    (environment : Environment) (slow : Slow)
    (absorbing : AbsorbingHalt carrier controller halt environment slow)
    (configuration : AutonomousConfiguration Control State)
    (halted : DeclaredHalt halt environment slow configuration)
    (steps : Nat) :
    autonomousObservationTrajectory carrier controller environment slow
        configuration steps =
      List.replicate (steps + 1)
        (carrier.observeAtState environment slow configuration.2) := by
  unfold autonomousObservationTrajectory
  rw [autonomousTrajectory_eq_replicate_of_absorbingHalt carrier controller
    halt environment slow absorbing configuration halted steps]
  simp

/-! ## Nontrivial autonomous and failed-channel fixtures -/

/-- A controller that alternates between commands zero and one. -/
def alternatingNatController :
    AutonomousController Unit Unit Nat Nat Bool where
  select := fun _environment _slow phase _state => if phase then 1 else 0
  advance := fun _environment _slow phase _state _command _nextState => !phase

/-- A failed controller whose phase never advances, so it keeps emitting zero. -/
def frozenZeroController :
    AutonomousController Unit Unit Nat Nat Bool where
  select := fun _environment _slow _phase _state => 0
  advance := fun _environment _slow phase _state _command _nextState => phase

/-- Every joint state is declared halted in the positive absorption fixture. -/
def alwaysHalt (_environment : Unit) (_slow : Unit)
    (_phase : Bool) (_state : Nat) : Prop := True

/-- No joint state is declared halted in the fixed-but-not-halted fixture. -/
def neverHalt (_environment : Unit) (_slow : Unit)
    (_phase : Bool) (_state : Nat) : Prop := False

/-- Internal phase switching realizes a nonconstant observation itinerary. -/
theorem alternatingController_realizes_itinerary :
    autonomousObservationTrajectory movingScalarCarrier
      alternatingNatController () () (false, 0) 3 = [0, 1, 3, 4] := rfl

/-- The same internal controller generates the explicit external schedule. -/
theorem alternatingController_generates_schedule :
    generatedCommands movingScalarCarrier alternatingNatController () ()
      (false, 0) 3 = [0, 1, 0] := rfl

/-- The frozen control channel cannot realize the alternating itinerary even
though it operates the same nontrivial carrier for the same number of steps. -/
theorem frozenZeroController_fails_alternating_itinerary :
    autonomousObservationTrajectory movingScalarCarrier frozenZeroController
      () () (false, 0) 3 ≠ [0, 1, 3, 4] := by decide

/-- The frozen carrier and frozen controller satisfy the absorbing-halt
obligation non-vacuously under the declared always-halt predicate. -/
theorem frozenController_alwaysHalt_absorbing :
    AbsorbingHalt frozenScalarCarrier frozenZeroController alwaysHalt () () := by
  intro configuration _halted
  rcases configuration with ⟨phase, state⟩
  rfl

/-- A declared halt without an absorption certificate can still move. -/
theorem declaredHalt_without_absorption_can_move :
    ¬ AbsorbingHalt movingScalarCarrier alternatingNatController alwaysHalt
      () () := by
  intro absorbing
  have fixed := absorbing (false, 0) trivial
  simp [autonomousStep, alternatingNatController, movingScalarCarrier,
    replacementCarrier, StateCarrier.step] at fixed

/-- Conversely, a joint fixed point is not a declared halt: the frozen joint
configuration is stationary while `neverHalt` remains false. -/
theorem jointFixedPoint_does_not_imply_declaredHalt :
    autonomousStep frozenScalarCarrier frozenZeroController () () (false, 0) =
        (false, 0) ∧
      ¬ DeclaredHalt neverHalt () () (false, 0) := by
  constructor
  · rfl
  · simp [DeclaredHalt, neverHalt]

/-- Moving scalar observations separate its natural-number commands. -/
theorem movingScalarCarrier_observationSeparatesCommands :
    ObservationSeparatesCommands movingScalarCarrier () () := by
  intro state first second equal
  have sumEqual : state + first + 1 = state + second + 1 := by
    simpa [movingScalarCarrier, replacementCarrier, StateCarrier.step,
      StateCarrier.observeAtState] using equal
  exact Nat.add_left_cancel (Nat.add_right_cancel sumEqual)

/-- A moving but command-opaque carrier: every command advances the state by
one, so distinct commands can expose exactly the same observation trace. -/
def commandOpaqueMovingCarrier :
    StateCarrier Unit Unit Bool Nat Nat Unit Nat Nat Nat :=
  replacementCarrier
    (fun _environment _slow => 0)
    (fun _environment _slow _command state => state + 1)
    (fun _environment _slow state => state)
    (fun _environment _slow observation => observation)

/-- Equal observation traces do not imply equal schedules without a command-
separation premise. -/
theorem observation_equivalence_does_not_identify_opaque_commands :
    commandOpaqueMovingCarrier.observationTrajectory () () 0 [false] =
        commandOpaqueMovingCarrier.observationTrajectory () () 0 [true] ∧
      [false] ≠ ([true] : List Bool) := by
  constructor
  · rfl
  · decide

#print axioms autonomousTrajectory_map_state_eq_scheduled
#print axioms autonomousObservationTrajectory_eq_scheduled
#print axioms replayController_generatedCommands
#print axioms replayController_trajectory_eq_scheduled
#print axioms commands_eq_of_observationTrajectory_eq
#print axioms autonomous_observation_eq_scheduled_iff_generatedCommands_eq
#print axioms autonomousTrajectory_eq_replicate_of_absorbingHalt
#print axioms autonomousObservationTrajectory_eq_replicate_of_absorbingHalt
#print axioms alternatingController_realizes_itinerary
#print axioms frozenZeroController_fails_alternating_itinerary
#print axioms frozenController_alwaysHalt_absorbing
#print axioms declaredHalt_without_absorption_can_move
#print axioms jointFixedPoint_does_not_imply_declaredHalt
#print axioms observation_equivalence_does_not_identify_opaque_commands

end Mettapedia.MachineLearning.NeuralNetworks.Architecture
