import Mettapedia.Languages.Metamath.InferenceProjection
import Mettapedia.Languages.Metamath.InferenceSideConditionsSemantics

/-!
# Variable-classification bridge for Metamath inference

The generated `Vars` judgment follows explicit runtime symbol tags, while the
live verifier and operational specification classify symbol names relative to
the caller's active variables.  This file states the exact frame-respect
condition under which those ordered, duplicate-preserving lists agree.
-/

namespace Mettapedia.Languages.Metamath.InferenceVariableClassification

open Mettapedia.Languages.Metamath.MMLean4Bridge
open Mettapedia.Languages.Metamath.InferenceEncoding
open Mettapedia.Languages.Metamath.InferenceProjection
open Mettapedia.Languages.Metamath.InferenceSideConditionsSemantics

/-- On the supported constant-headed carrier, operational `varsInExpr` is the
runtime name-filtering `varsIn`, mapped to the specification's variable
wrapper.  Order and duplicates are preserved. -/
theorem varsInExpr_toOperationalExpr_eq_runtimeVarsIn
    (activeVariables : List Metamath.Spec.Variable)
    (formula : ConstantHeadedFormula) :
    Metamath.Spec.varsInExpr activeVariables
        (Metamath.Kernel.toExpr formula.toRuntime) =
      (formula.toRuntime.varsIn
        (Metamath.Kernel.varNames activeVariables)).map
        Metamath.Spec.Variable.mk := by
  rcases formula with ⟨typecode, body⟩
  simp [ConstantHeadedFormula.toRuntime, Metamath.Kernel.toExpr,
    Metamath.Verify.Formula.varsIn, Metamath.Spec.varsInExpr,
    Metamath.Kernel.toSym, Metamath.Kernel.varNames]
  induction body with
  | nil => rfl
  | cons symbol body ih =>
      by_cases hactive :
          Metamath.Spec.Variable.mk symbol.value ∈ activeVariables
      · have hexists :
            ∃ activeVariable,
              activeVariable ∈ activeVariables ∧
                activeVariable.v = symbol.value :=
          ⟨Metamath.Spec.Variable.mk symbol.value, hactive, rfl⟩
        simp [hactive, hexists, ih]
      · have hnotExists :
            ¬∃ activeVariable,
              activeVariable ∈ activeVariables ∧
                activeVariable.v = symbol.value := by
          rintro ⟨⟨activeName⟩, hmem, hname⟩
          apply hactive
          change activeName = symbol.value at hname
          subst activeName
          exact hmem
        simp [hactive, hnotExists, ih]

/-- The two independently defined explicit-tag traversals coincide. -/
theorem bodyVariables_eq_taggedVariableNames (body : List RuntimeSym) :
    BodyVariables body = taggedVariableNames body := by
  induction body with
  | nil => rfl
  | cons symbol body ih =>
      cases symbol <;> simp [BodyVariables, taggedVariableNames, ih]

/-- The projection's frame-symbol gate is exactly the live runtime gate once
the floating-variable list is read from the same database frame. -/
theorem formulaSymbolsRespectFrame_eq_runtime
    (db : RuntimeDB) (frame : RuntimeFrame)
    (formula : ConstantHeadedFormula) :
    formulaSymbolsRespectFrame (db.frameFloatVars frame) formula =
      db.formulaSymsRespectFrame formula.toRuntime frame := by
  rcases formula with ⟨typecode, body⟩
  simp only [formulaSymbolsRespectFrame,
    Metamath.Verify.DB.formulaSymsRespectFrame,
    ConstantHeadedFormula.toRuntime, List.tail_cons]
  congr 1
  funext symbol
  cases symbol <;> simp [symbolRespectsFrame]

/-- Frame-respecting explicit tags turn the active-name classification into
the exact ordered variable list generated by the side calculus. -/
theorem varsInExpr_eq_bodyVariables_of_respectsFrame
    (activeVariables : List Metamath.Spec.Variable)
    (floatingVariables : List String)
    (formula : ConstantHeadedFormula)
    (hnames :
      Metamath.Kernel.varNames activeVariables = floatingVariables)
    (hrespect :
      formulaSymbolsRespectFrame floatingVariables formula = true) :
    Metamath.Spec.varsInExpr activeVariables
        (Metamath.Kernel.toExpr formula.toRuntime) =
      (BodyVariables formula.body).map Metamath.Spec.Variable.mk := by
  rw [varsInExpr_toOperationalExpr_eq_runtimeVarsIn, hnames,
    varsIn_toRuntime_eq_taggedVariableNames floatingVariables formula hrespect,
    ← bodyVariables_eq_taggedVariableNames]

/-- Package the classification condition required by the DVOK-to-spec bridge.
The substitution-image and frame-respect hypotheses remain explicit because
they come respectively from the finite-map bridge and reachable-stack
invariant, not from bare lookup syntax. -/
theorem lookup_varsInExpr_classification
    (substitution : FiniteSubstitution)
    (activeVariables : List Metamath.Spec.Variable)
    (floatingVariables : List String)
    (specSubstitution : Metamath.Spec.Subst)
    (hnames :
      Metamath.Kernel.varNames activeVariables = floatingVariables)
    (himage : ∀ name replacement,
      LookupSemantics substitution name replacement →
        specSubstitution ⟨name⟩ =
          Metamath.Kernel.toExpr replacement.toRuntime)
    (hrespect : ∀ name replacement,
      LookupSemantics substitution name replacement →
        formulaSymbolsRespectFrame floatingVariables replacement = true) :
    ∀ name replacement,
      LookupSemantics substitution name replacement →
        Metamath.Spec.varsInExpr activeVariables
            (specSubstitution ⟨name⟩) =
          (BodyVariables replacement.body).map
            Metamath.Spec.Variable.mk := by
  intro name replacement hlookup
  rw [himage name replacement hlookup]
  exact varsInExpr_eq_bodyVariables_of_respectsFrame
    activeVariables floatingVariables replacement hnames
      (hrespect name replacement hlookup)

section Examples

private def activeX : List Metamath.Spec.Variable := [⟨"x"⟩]

private def taggedExample : ConstantHeadedFormula :=
  ⟨"wff", [.var "x", .const "c", .var "x"]⟩

/-- Positive boundary: ordered duplicate variable occurrences survive every
classification layer. -/
example :
    Metamath.Spec.varsInExpr activeX
        (Metamath.Kernel.toExpr taggedExample.toRuntime) =
      [⟨"x"⟩, ⟨"x"⟩] := by
  decide

/-- Negative boundary: an active variable name carrying a constant tag is not
a frame-respecting replacement. -/
example :
    formulaSymbolsRespectFrame ["x"]
      ⟨"wff", [.const "x"]⟩ = false := by
  decide

end Examples

end Mettapedia.Languages.Metamath.InferenceVariableClassification
