import Mathlib.Data.Fin.Basic

/-!
# Stream finality and open-ended finite observation

Streams form the final coalgebra for the functor `A × -`.  This module proves
that universal property directly, without choosing a programming language or
an object type theory.

It also isolates the exact finite-view phenomenon needed by open-ended
semantics:

* every observation at one fixed finite depth loses stream information;
* the coherent tower of all finite observations separates streams.

Thus an unbounded semantic object can be approached through finite views
without pretending that any one view is complete.  This is ordinary
coalgebraic mathematics; no claim of an ultrainfinite foundation follows from
it alone.
-/

set_option autoImplicit false

namespace Mettapedia.Coalgebra.StreamFinality

universe uLabel uSource uTarget uThird

/-! ## Coalgebras and their morphisms -/

/-- A deterministic stream coalgebra with one visible label and one successor
state. -/
structure Coalgebra (Label : Type uLabel) where
  Carrier : Type uSource
  observe : Carrier → Label
  next : Carrier → Carrier

/-- A coalgebra morphism preserves both the current observation and the next
state. -/
structure Hom {Label : Type uLabel}
    (source : Coalgebra.{uLabel, uSource} Label)
    (target : Coalgebra.{uLabel, uTarget} Label) where
  toFun : source.Carrier → target.Carrier
  observe_preserved : ∀ state,
    target.observe (toFun state) = source.observe state
  next_preserved : ∀ state,
    target.next (toFun state) = toFun (source.next state)

namespace Hom

@[ext]
theorem ext {Label : Type uLabel}
    {source : Coalgebra.{uLabel, uSource} Label}
    {target : Coalgebra.{uLabel, uTarget} Label}
    {first second : Hom source target}
    (functions : first.toFun = second.toFun) : first = second := by
  cases first
  cases second
  cases functions
  rfl

def id {Label : Type uLabel}
    (coalgebra : Coalgebra.{uLabel, uSource} Label) :
    Hom coalgebra coalgebra where
  toFun := _root_.id
  observe_preserved := by intro; rfl
  next_preserved := by intro; rfl

def comp {Label : Type uLabel}
    {first : Coalgebra.{uLabel, uSource} Label}
    {second : Coalgebra.{uLabel, uTarget} Label}
    {third : Coalgebra.{uLabel, uThird} Label}
    (earlier : Hom first second) (later : Hom second third) :
    Hom first third where
  toFun := later.toFun ∘ earlier.toFun
  observe_preserved := by
    intro state
    change third.observe (later.toFun (earlier.toFun state)) =
      first.observe state
    rw [later.observe_preserved, earlier.observe_preserved]
  next_preserved := by
    intro state
    change third.next (later.toFun (earlier.toFun state)) =
      later.toFun (earlier.toFun (first.next state))
    rw [later.next_preserved, earlier.next_preserved]

end Hom

/-! ## The stream coalgebra -/

/-- The semantic carrier of infinite streams. -/
abbrev Stream (Label : Type uLabel) := Nat → Label

def head {Label : Type uLabel} (stream : Stream Label) : Label :=
  stream 0

def tail {Label : Type uLabel} (stream : Stream Label) : Stream Label :=
  fun index => stream (index + 1)

/-- Streams expose their head and advance to their tail. -/
def streamCoalgebra (Label : Type uLabel) :
    Coalgebra.{uLabel, uLabel} Label where
  Carrier := Stream Label
  observe := head
  next := tail

/-- Observe the label reached after exactly `depth` successor steps. -/
def unfoldAt {Label : Type uLabel}
    (coalgebra : Coalgebra.{uLabel, uSource} Label) :
    Nat → coalgebra.Carrier → Label
  | 0, state => coalgebra.observe state
  | depth + 1, state => unfoldAt coalgebra depth (coalgebra.next state)

/-- The complete behavior generated by one coalgebra state. -/
def unfold {Label : Type uLabel}
    (coalgebra : Coalgebra.{uLabel, uSource} Label)
    (state : coalgebra.Carrier) : Stream Label :=
  fun depth => unfoldAt coalgebra depth state

@[simp]
theorem unfold_zero {Label : Type uLabel}
    (coalgebra : Coalgebra.{uLabel, uSource} Label)
    (state : coalgebra.Carrier) :
    unfold coalgebra state 0 = coalgebra.observe state :=
  rfl

@[simp]
theorem unfold_succ {Label : Type uLabel}
    (coalgebra : Coalgebra.{uLabel, uSource} Label)
    (state : coalgebra.Carrier) (depth : Nat) :
    unfold coalgebra state (depth + 1) =
      unfold coalgebra (coalgebra.next state) depth :=
  rfl

@[simp]
theorem head_unfold {Label : Type uLabel}
    (coalgebra : Coalgebra.{uLabel, uSource} Label)
    (state : coalgebra.Carrier) :
    head (unfold coalgebra state) = coalgebra.observe state :=
  rfl

@[simp]
theorem tail_unfold {Label : Type uLabel}
    (coalgebra : Coalgebra.{uLabel, uSource} Label)
    (state : coalgebra.Carrier) :
    tail (unfold coalgebra state) =
      unfold coalgebra (coalgebra.next state) := by
  funext depth
  rfl

/-- Every coalgebra has its canonical behavior map into streams. -/
def unfoldHom {Label : Type uLabel}
    (coalgebra : Coalgebra.{uLabel, uSource} Label) :
    Hom coalgebra (streamCoalgebra Label) where
  toFun := unfold coalgebra
  observe_preserved := head_unfold coalgebra
  next_preserved := tail_unfold coalgebra

/-- Every coalgebra morphism into streams is the canonical unfolding map. -/
theorem hom_to_stream_eq_unfold {Label : Type uLabel}
    (coalgebra : Coalgebra.{uLabel, uSource} Label)
    (morphism : Hom coalgebra (streamCoalgebra Label)) :
    morphism.toFun = unfold coalgebra := by
  funext state depth
  induction depth generalizing state with
  | zero =>
      exact morphism.observe_preserved state
  | succ depth inductionHypothesis =>
      have nextEquality := congrFun (morphism.next_preserved state) depth
      calc
        morphism.toFun state (depth + 1) =
            morphism.toFun (coalgebra.next state) depth := nextEquality
        _ = unfold coalgebra (coalgebra.next state) depth :=
          inductionHypothesis (coalgebra.next state)
        _ = unfold coalgebra state (depth + 1) := rfl

/-- A final coalgebra supplies one morphism from every source, and every other
morphism is equal to it. -/
structure IsFinal {Label : Type uLabel}
    (terminal : Coalgebra.{uLabel, uTarget} Label) where
  lift : (source : Coalgebra.{uLabel, uSource} Label) → Hom source terminal
  unique : ∀ (source : Coalgebra.{uLabel, uSource} Label)
    (morphism : Hom source terminal), morphism = lift source

/-- Streams satisfy the final-coalgebra universal property. -/
def streamFinal (Label : Type uLabel) :
    IsFinal.{uLabel, uSource, uLabel} (streamCoalgebra Label) where
  lift := unfoldHom
  unique := by
    intro source morphism
    apply Hom.ext
    exact hom_to_stream_eq_unfold source morphism

/-! ## Coherent finite observations -/

/-- The observation available at one fixed finite depth. -/
abbrev Prefix (Label : Type uLabel) (depth : Nat) := Fin depth → Label

def finiteView {Label : Type uLabel} (depth : Nat) :
    Stream Label → Prefix Label depth :=
  fun stream index => stream index.val

/-- Restrict a longer finite observation to an earlier depth. -/
def restrictPrefix {Label : Type uLabel} {earlier later : Nat}
    (bounded : earlier ≤ later) :
    Prefix Label later → Prefix Label earlier :=
  fun observation index =>
    observation ⟨index.val, lt_of_lt_of_le index.isLt bounded⟩

@[simp]
theorem restrictPrefix_finiteView {Label : Type uLabel}
    {earlier later : Nat} (bounded : earlier ≤ later)
    (stream : Stream Label) :
    restrictPrefix bounded (finiteView later stream) =
      finiteView earlier stream := by
  funext index
  rfl

/-- The complete tower of all finite observations. -/
def allPrefixes {Label : Type uLabel} (stream : Stream Label) :
    (depth : Nat) → Prefix Label depth :=
  fun depth => finiteView depth stream

/-- Although every component is finite, the entire coherent tower separates
infinite streams. -/
theorem allPrefixes_injective {Label : Type uLabel} :
    Function.Injective (@allPrefixes Label) := by
  intro first second equalPrefixes
  funext index
  have prefixEquality := congrFun equalPrefixes (index + 1)
  simpa [allPrefixes, finiteView] using
    congrFun prefixEquality ⟨index, Nat.lt_succ_self index⟩

/-! ## Every fixed finite view is lossy -/

def constant {Label : Type uLabel} (label : Label) : Stream Label :=
  fun _ => label

/-- Change exactly the first label outside the prefix of length `depth`. -/
def changedAt {Label : Type uLabel}
    (depth : Nat) (ordinary changed : Label) : Stream Label :=
  fun index => if index = depth then changed else ordinary

theorem finiteView_constant_changedAt {Label : Type uLabel}
    (depth : Nat) (ordinary changed : Label) :
    finiteView depth (constant ordinary) =
      finiteView depth (changedAt depth ordinary changed) := by
  funext index
  have different : index.val ≠ depth := Nat.ne_of_lt index.isLt
  simp [finiteView, constant, changedAt, different]

theorem constant_ne_changedAt {Label : Type uLabel}
    (depth : Nat) {ordinary changed : Label}
    (different : ordinary ≠ changed) :
    constant ordinary ≠ changedAt depth ordinary changed := by
  intro equalStreams
  have atDepth := congrFun equalStreams depth
  simp [constant, changedAt] at atDepth
  exact different atDepth

/-- No fixed finite prefix map is injective when the label type has two
distinguishable values. -/
theorem finiteView_not_injective {Label : Type uLabel}
    (depth : Nat) {ordinary changed : Label}
    (different : ordinary ≠ changed) :
    ¬ Function.Injective (@finiteView Label depth) := by
  intro injectivePrefix
  exact constant_ne_changedAt depth different
    (injectivePrefix
      (finiteView_constant_changedAt depth ordinary changed))

/-! ## Boolean controls -/

namespace Canary

theorem every_fixed_boolean_prefix_is_lossy (depth : Nat) :
    ¬ Function.Injective (@finiteView Bool depth) :=
  finiteView_not_injective depth Bool.false_ne_true

theorem complete_boolean_prefix_tower_is_faithful :
    Function.Injective (@allPrefixes Bool) :=
  allPrefixes_injective

/-- The paired control states the open-ended observation law in one theorem:
each bounded observer forgets, while the unbounded compatible family does
not. -/
theorem finite_views_lossy_tower_faithful :
    (∀ depth, ¬ Function.Injective (@finiteView Bool depth)) ∧
      Function.Injective (@allPrefixes Bool) :=
  ⟨every_fixed_boolean_prefix_is_lossy,
    complete_boolean_prefix_tower_is_faithful⟩

end Canary

/-! ## Axiom audit -/

#print axioms hom_to_stream_eq_unfold
#print axioms streamFinal
#print axioms restrictPrefix_finiteView
#print axioms allPrefixes_injective
#print axioms finiteView_not_injective
#print axioms Canary.finite_views_lossy_tower_faithful

end Mettapedia.Coalgebra.StreamFinality
