import Mettapedia.GSLT.Logic.ResourceFrame
import Mettapedia.OSLF.Framework.GSLTTypeSynthesis

/-!
# Resource separation in the generated native logic

The bag separation assertions of the resource-system frame calculus are
predicates in the existing OSLF generated by that system. The operational
frame theorem gives the native entailment `(diamond P) * F <= diamond (P * F)`.
A fixed frame gives the converse when it enables no new resource instance.

The generated OSLF box quantifies predecessors. It is not the forward demonic
postcondition used by `ResourceFrame.SafeTriple`; the distinction is retained
by the explicit specifications below.
-/

set_option autoImplicit false

namespace Mettapedia.OSLF.Bridges.GSLT.ResourceSeparation

open Mettapedia.GSLT.Causality.ResourceInteraction
open Mettapedia.GSLT.Logic.ResourceFrame
open Mettapedia.GSLT.SeparationAlgebra
open Mettapedia.OSLF.Framework.GSLTTypeSynthesis

universe u v

variable {R : Type u} [DecidableEq R] (S : System.{u, v} R)

/-- Resource-system equality is literal equality, so every bag assertion is a
predicate on its equation classes. -/
def nativePredicate (P : Multiset R → Prop) : EquationPredicate S.theory :=
  ⟨P, by intro left right equal; change left = right at equal; cases equal; rfl⟩

/-- Separating conjunction in the existing native predicate carrier, using the
existing resource separation algebra. -/
def nativeStar (P F : EquationPredicate S.theory) : EquationPredicate S.theory :=
  nativePredicate S (sepConj P.1 F.1)

/-- The generated native diamond is exactly existential resource execution. -/
theorem nativeDiamond_iff (P : EquationPredicate S.theory) (source : Multiset R) :
    (semanticDiamond S.theory P).1 source ↔
      ∃ target : Multiset R, S.theory.rewrites source target ∧ P.1 target :=
  gsltDiamond_spec S.theory P.1 source

/-- The resource-system may specification is a native-diamond entailment. -/
theorem mayTriple_iff_native (pre post : Multiset R → Prop) :
    MayTriple S (fun _ => True) pre post ↔
      ∀ source, pre source → (semanticDiamond S.theory (nativePredicate S post)).1 source := by
  constructor
  · intro specification source holds
    obtain ⟨target, step, result⟩ := specification source holds
    exact (nativeDiamond_iff S _ _).mpr
      ⟨target, (selectedStep_iff_rewrites S _ _).mp step, result⟩
  · intro specification source holds
    obtain ⟨target, step, result⟩ := (nativeDiamond_iff S _ _).mp (specification source holds)
    exact ⟨target, (selectedStep_iff_rewrites S _ _).mpr step, result⟩

/-- Native spatial/modal framing: replaying the witnessed firing preserves the
supplied frame. This is an entailment, not an unrestricted equivalence. -/
theorem nativeDiamond_star_frame (P F : EquationPredicate S.theory) :
    sepConj (α := Multiset R) (semanticDiamond S.theory P).1 F.1 ≤
      (semanticDiamond S.theory (nativeStar S P F)).1 := by
  rintro _ ⟨owned, frame, _, rfl, possible, framed⟩
  obtain ⟨target, step, result⟩ := (nativeDiamond_iff S P owned).mp possible
  exact (nativeDiamond_iff S _ _).mpr
    ⟨target + frame, rewrites_add_frame S step frame,
      ⟨target, frame, trivial, rfl, result, framed⟩⟩

/-- With a fixed operationally inert frame the actual global successor and
the local successor give equivalent native-diamond observations. -/
theorem nativeDiamond_fixedFrame_iff (P : EquationPredicate S.theory)
    (source frame : Multiset R)
    (inert : NoNewEnabled S (fun _ => True) source frame) :
    (semanticDiamond S.theory
      (nativeStar S P (nativePredicate S (fun bag => bag = frame)))).1 (source + frame) ↔
        (semanticDiamond S.theory P).1 source := by
  constructor
  · intro possible
    obtain ⟨actual, step, owned, extension, _, split, holds, rfl⟩ :=
      (nativeDiamond_iff S _ _).mp possible
    obtain ⟨target, localStep, actualEq⟩ :=
      (selectedStep_iff_frame S inert).mp ((selectedStep_iff_rewrites S _ _).mpr step)
    have same : target = owned := add_right_cancel (actualEq.symm.trans split)
    exact (nativeDiamond_iff S P source).mpr
      ⟨target, (selectedStep_iff_rewrites S _ _).mp localStep, same.symm ▸ holds⟩
  · intro possible
    exact nativeDiamond_star_frame S P (nativePredicate S (fun bag => bag = frame)) _
      ⟨source, frame, trivial, rfl, possible, rfl⟩

/-- A complete read-inclusive footprint has its expected native successor. -/
theorem footprint_nativeDiamond (entry : S.Entry) :
    (semanticDiamond S.theory
      (nativePredicate S (fun target => target = S.read entry.2 + S.produce entry.2))).1
      (demand S entry) := by
  obtain ⟨target, ⟨candidate, _, enabled, endpoint⟩, result⟩ :=
    SafeTriple.may S (footprint_safeTriple S entry) (demand S entry) rfl
  exact (nativeDiamond_iff S _ _).mpr
    ⟨target, ⟨candidate.1, candidate.2, enabled, endpoint⟩, result⟩

/-- OSLF's generated right adjoint describes all predecessors of the observed
target, rather than all future successors of a source. -/
theorem nativeBox_predecessors (P : EquationPredicate S.theory) (target : Multiset R) :
    (semanticBox S.theory P).1 target ↔
      ∀ source, S.theory.rewrites source target → P.1 source :=
  gsltBox_spec S.theory P.1 target

end Mettapedia.OSLF.Bridges.GSLT.ResourceSeparation
