import Mettapedia.GSLT.LanguageDef.CostElaboratedCarrier
import Mettapedia.GSLT.LanguageDef.EquationOccurrence
import Mettapedia.GSLT.LanguageDef.CostElaborationDecoration
import Mettapedia.GSLT.LanguageDef.CostElaborationTransport
import Mettapedia.GSLT.LanguageDef.CostElaboratedSection
import Mettapedia.GSLT.LanguageDef.CostOneElaboratedObject
import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostIterationElaboratedCarrier

#print axioms Mettapedia.GSLT.LanguageDef.OpenElaborationSemantics.ComputableSection.ofGeneratorInvariant
#print axioms Mettapedia.GSLT.LanguageDef.OpenElaborationSemantics.ComputableSection.ofPathInvariant
#print axioms Mettapedia.GSLT.LanguageDef.EquationSemantics.AuthoredEquationInstanceWitness.exists_erasing_to
#print axioms Mettapedia.GSLT.LanguageDef.EquationSemantics.AuthoredEquationInstanceWitness.TargetApplicationTemplate.selects
#print axioms Mettapedia.GSLT.LanguageDef.EquationSemantics.AuthoredGeneratorWitness.exists_erasing_to
#print axioms Mettapedia.GSLT.LanguageDef.EquationSemantics.AuthoredGeneratorWitness.erase_mapCostStatic
#print axioms Mettapedia.GSLT.LanguageDef.EquationSemantics.AuthoredGeneratorWitness.mapCostStatic_renameAmbientBVarsAt
#print axioms Mettapedia.GSLT.LanguageDef.EquationSemantics.AuthoredGeneratorWitness.mapCostStatic_substitute
#print axioms Mettapedia.GSLT.LanguageDef.CostStaticChoiceOccurrence.IntroducedByGenerator.selects
#print axioms Mettapedia.GSLT.LanguageDef.CostStaticPlanLift.targetChoice_has_origin_of_reflectiveGenerator
#print axioms Mettapedia.GSLT.LanguageDef.OpenElaborationGeneratorLift.erasesToAuthored
#print axioms Mettapedia.GSLT.LanguageDef.OpenElaborationPathLift.erasesToAuthored
#print axioms Mettapedia.GSLT.LanguageDef.OpenElaborationSemantics.Identity.compact_but_not_preserving
#print axioms Mettapedia.GSLT.LanguageDef.CIGSLT.costStructuralSemantics_rootIdentity_eq
#print axioms Mettapedia.GSLT.LanguageDef.CIGSLT.compact_but_not_costStructuralSemantics
#print axioms Mettapedia.GSLT.LanguageDef.CostStaticChoiceOriginMap.comp_assoc
#print axioms Mettapedia.GSLT.LanguageDef.CostStaticChoiceOriginMap.origin_eq_none_of_source_empty
#print axioms Mettapedia.GSLT.LanguageDef.CostStaticPlanLift.targetChoiceInRedex_of_sourceChoices_eq_nil
#print axioms Mettapedia.GSLT.LanguageDef.CostStaticPlanLift.targetContextChoice_has_origin
#print axioms Mettapedia.GSLT.LanguageDef.CostElaboratedNormalizationLaws.sectionData
#print axioms Mettapedia.GSLT.LanguageDef.CostElaboratedCompactification.iff_compactCostNormalizationCoherent
#print axioms Mettapedia.GSLT.LanguageDef.CostStaticPlanLift.noTargetBoundaryWithoutChoice
#print axioms Mettapedia.GSLT.LanguageDef.CostElaboratedSectionData.equivalent_iff_normalize_eq
#print axioms Mettapedia.GSLT.LanguageDef.CostElaboratedSectionData.normalize_rootIdentity_eq
#print axioms Mettapedia.GSLT.LanguageDef.CostElaboratedCompactification.sameCompact_but_distinctNormalForms
#print axioms Mettapedia.GSLT.LanguageDef.CostOneDomainObject.normalize_erase_commutes
#print axioms Mettapedia.GSLT.LanguageDef.CostOneDomainObject.sameCompact_but_distinctSemanticNormalForms
#print axioms Mettapedia.GSLT.LanguageDef.CIGSLT.costCompactErasureFaithful_iff_fibersSubsingleton
#print axioms Mettapedia.GSLT.LanguageDef.CIGSLT.costNormalizationFactorsThroughCompactErasure_iff
#print axioms Mettapedia.GSLT.LanguageDef.CIGSLT.compact_but_not_sameCostDecoration
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rhoCostOne_not_normalizationFactorsThroughCompactErasure
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rhoCostOne_not_costCompactErasureFaithful
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rhoCostOne_no_normalizationCommutingCompactification
