import Mathlib
#check List.idxOf
#check List.idxOf_eq_getElem
#check List.idxOf_map
#check List.idxOf_map_eq
#check List.eraseDups_map_eq_map_eraseDups
#check List.eraseDups_map_injective
#check List.map_eraseDups_of_injective
#check List.Nodup.idxOf_lt
#check List.idxOf_lt_length_iff
#check List.idxOf_eq_idxOf_iff
#check List.idxOf_injective
#check List.eraseDups_idem
#check List.eraseDups_eq_self.mpr
#check List.nodup_eraseDups
#check List.mem_eraseDups
#check List.idxOf_cons_self
#check List.idxOf_cons_eq_zero
#check List.idxOf_append
#check List.idxOf_map
