import Mettapedia.OSLF.Syntax.CategoricalAuthoredNullaryFree
import Mathlib.CategoryTheory.Limits.Shapes.BinaryProducts

/-!
# Free adjoining of a premise-free firing rule

Over a fixed binding interpretation, the scoped-premise polynomial of a
nullary rule is constant. If event graphs over the program endpoint object
have binary coproducts, its free algebra over an existing graph is their
coproduct with the graph of parameter assignments. In a target with disjoint
coproducts this literally retains old occurrences and adjoins new ones; the
general theorem needs only the coproduct universal property.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency.types false

namespace Mettapedia.OSLF.Binding.CategoricalAuthoredNullaryAdjunction

open _root_.CategoryTheory
open _root_.CategoryTheory.Limits
open Mettapedia.OSLF.Binding
open Mettapedia.OSLF.Binding.CategoricalBindingModel
open Mettapedia.OSLF.Binding.CategoricalAuthoredRuleInterpretation
open Mettapedia.OSLF.Binding.CategoricalAuthoredRulePolynomial
open Mettapedia.OSLF.Binding.CategoricalAuthoredNullaryFree

universe u v
variable {S : Signature} {schema : List (MetaArity S)}
variable {D : Type u} [Category.{v} D] [CartesianMonoidalCategory D]
  [MonoidalClosed D] [HasPullbacks D]
variable (M : Model S D) (P : ProgramCarrier M)
variable (conclusion : PositionedRewrite (withMetas S schema))

/-- The event graph generated by the authored rule's parameters. -/
def parameterGraph : EventSlice M P :=
  Over.mk (𝟙 (Parameters (schema := schema) M conclusion.ctx) ≫
    ruleConclusion M P (nullaryRule conclusion))

theorem nullaryPolynomial_obj (G : EventSlice M P) :
    (rulePolynomial M P (nullaryRule conclusion)).obj G =
      parameterGraph M P conclusion := rfl

@[simp] theorem nullaryPolynomial_map {G H : EventSlice M P} (f : G ⟶ H) :
    (rulePolynomial M P (nullaryRule conclusion)).map f =
      𝟙 ((rulePolynomial M P (nullaryRule conclusion)).obj G) := by
  apply Over.OverMorphism.ext
  change (𝟙 _ ≫ 𝟙 _) = 𝟙 _
  simp

variable [HasBinaryCoproducts (EventSlice M P)]

/-- The free algebra is the coproduct of the old event graph and the graph
demanded by the new rule. The structure arrow selects the rule summand. -/
noncomputable def freeOn (G : EventSlice M P) :
    Endofunctor.Algebra (rulePolynomial M P (nullaryRule conclusion)) where
  a := G ⨿ parameterGraph M P conclusion
  str := coprod.inr

/-- The old graph's coproduct injection. It is monic when the target's
coproducts have that property; binary coproducts alone do not imply it. -/
noncomputable def oldInclusion (G : EventSlice M P) :
    G ⟶ (freeOn M P conclusion G).a :=
  coprod.inl

/-- The rule-parameter graph's coproduct injection. -/
noncomputable def newInclusion (G : EventSlice M P) :
    parameterGraph M P conclusion ⟶
      (freeOn M P conclusion G).a :=
  coprod.inr

/-- An interpretation of the new rule and a map of the old event graph
determine one map out of the freely extended graph. -/
noncomputable def extend {G : EventSlice M P}
    (A : Endofunctor.Algebra (rulePolynomial M P (nullaryRule conclusion)))
    (f : G ⟶ A.a) : freeOn M P conclusion G ⟶ A := by
  refine { f := coprod.desc f A.str, h := ?_ }
  simp only [nullaryPolynomial_map]
  change (𝟙 _ ≫ A.str) = coprod.inr ≫ coprod.desc f A.str
  exact (Category.id_comp A.str).trans (coprod.inr_desc f A.str).symm

/-- Restriction of the universal map to old events is the chosen map. -/
theorem extend_on_old {G : EventSlice M P}
    (A : Endofunctor.Algebra (rulePolynomial M P (nullaryRule conclusion)))
    (f : G ⟶ A.a) :
    coprod.inl ≫ (extend M P conclusion A f).f = f := by
  exact coprod.inl_desc _ _

/-- The extension also interprets every newly generated event by exactly
the target's authored firing action. -/
theorem extend_on_new {G : EventSlice M P}
    (A : Endofunctor.Algebra (rulePolynomial M P (nullaryRule conclusion)))
    (f : G ⟶ A.a) :
    coprod.inr ≫ (extend M P conclusion A f).f = A.str := by
  exact coprod.inr_desc _ _

/-- The two summands exhaust the free graph. Hence a lawful algebra map
with the given restriction to old events is uniquely the extension above. -/
theorem extend_unique {G : EventSlice M P}
    (A : Endofunctor.Algebra (rulePolynomial M P (nullaryRule conclusion)))
    (f : G ⟶ A.a)
    (g : freeOn M P conclusion G ⟶ A)
    (old : coprod.inl ≫ g.f = f) :
    g = extend M P conclusion A f := by
  apply Endofunctor.Algebra.Hom.ext
  apply coprod.hom_ext
  · exact old.trans (extend_on_old M P conclusion A f).symm
  · have h := g.h
    simp only [nullaryPolynomial_map] at h
    change (𝟙 _ ≫ A.str) = coprod.inr ≫ g.f at h
    have hnew : coprod.inr ≫ g.f = A.str := by
      exact h.symm.trans (Category.id_comp A.str)
    exact hnew.trans (extend_on_new M P conclusion A f).symm

/-- The free-extension universal property, including arbitrary existing
events: maps from the extended operational graph are exactly maps from the
old graph into a target interpretation of the new authored rule. -/
noncomputable def freeOnHomEquiv (G : EventSlice M P)
    (A : Endofunctor.Algebra
      (rulePolynomial M P (nullaryRule conclusion))) :
    (freeOn M P conclusion G ⟶ A) ≃ (G ⟶ A.a) where
  toFun g := coprod.inl ≫ g.f
  invFun f := extend M P conclusion A f
  left_inv g := by
    exact (extend_unique M P conclusion A
      (coprod.inl ≫ g.f) g rfl).symm
  right_inv f := extend_on_old M P conclusion A f

end Mettapedia.OSLF.Binding.CategoricalAuthoredNullaryAdjunction
