import Mettapedia.OSLF.Syntax.IndexedRulePolynomialMorphisms

/-!
# Finite authored premise lists and indexed rule polynomials

A rule declaration lists its recursive premises in an order. An indexed
polynomial addresses them by a position type. An exact premise listing
identifies every position with one list entry and proves that the recursive
child judgment is that entry. It therefore gives an isomorphism of derivation
trees, retaining premise order and repeated judgments as distinct positions.

This file concerns recursive step premises. Nonrecursive guards and premises
that produce new matching assignments require separate data in an authored
rule constructor.
-/

set_option autoImplicit false
set_option linter.checkUnivs false

namespace Mettapedia.OSLF.Binding.FiniteRulePremiseLists

open Mettapedia.TypeTheory
open Mettapedia.OSLF.Binding.IndexedRulePolynomialMorphisms

universe uBase uIndex uShape uPosition

variable {Base : Type uBase} {Index : Base → Type uIndex}
  (P : IndexedPolynomial.{uBase, uIndex, uShape, uPosition} Base Index)

/-- A finite recursive rule signature as an author can supply it: each
constructor has an ordered list of required judgment instances. Different
entries remain different premise positions even when their judgments agree. -/
structure FinitePresentation (Base : Type uBase)
    (Index : Base → Type uIndex) where
  Shape : (b : Base) → Index b → Type uShape
  premises : ∀ b i (_shape : Shape b i), List (Index b)

namespace FinitePresentation

/-- Compile an authored finite premise list to a strictly positive indexed
polynomial without choosing or merging any premise witnesses. -/
def polynomial (F : FinitePresentation.{uBase, uIndex, uShape} Base Index) :
    IndexedPolynomial.{uBase, uIndex, uShape, 0} Base Index where
  Shape := F.Shape
  Position := fun shape => Fin (F.premises _ _ shape).length
  next shape position := (F.premises _ _ shape).get position

/-- The least proof-relevant derivation family generated by the listed
rules. Its recursive branches follow the list in their original order. -/
abbrev Derivation (F : FinitePresentation.{uBase, uIndex, uShape} Base Index)
    (b : Base) (i : Index b) := F.polynomial.Fix b i

/-- A predicate model must accept each conclusion when it accepts all of
that rule's listed recursive premises. -/
def RuleClosed (F : FinitePresentation.{uBase, uIndex, uShape} Base Index)
    (R : ∀ b, Index b → Prop) : Prop :=
  ∀ b i (shape : F.Shape b i),
    (∀ position : Fin (F.premises b i shape).length,
      R b ((F.premises b i shape).get position)) → R b i

/-- Every finite-premise derivation is interpreted in every predicate model
closed under the author's rule list. This is the least-rule-closure law. -/
theorem derivation_least
    (F : FinitePresentation.{uBase, uIndex, uShape} Base Index)
    (R : ∀ b, Index b → Prop) (closed : F.RuleClosed R)
    (b : Base) (i : Index b) (tree : F.Derivation b i) : R b i := by
  exact IndexedPolynomial.Fix.eliminate F.polynomial
    (fun b i _ => R b i)
    (fun b i shape _children ih => closed b i shape ih)
    b i tree

end FinitePresentation

/-- A finite, ordered enumeration of the recursive premises of each
constructor, with an exact comparison to the original position type. -/
structure Listing where
  premises : ∀ b i (_shape : P.Shape b i), List (Index b)
  positions : ∀ b i (shape : P.Shape b i),
    P.Position shape ≃ Fin (premises b i shape).length
  next_eq : ∀ b i (shape : P.Shape b i) (position : P.Position shape),
    P.next shape position =
      (premises b i shape).get (positions b i shape position)

/-- A predicate interpreting judgments is closed under every rule exactly
when it accepts a conclusion after all of that rule's recursive premises. -/
def RuleClosed (R : ∀ b, Index b → Prop) : Prop :=
  ∀ b i (shape : P.Shape b i),
    (∀ position : P.Position shape, R b (P.next shape position)) → R b i

namespace Listing

variable {P}

/-- Regard an exact enumeration of an existing polynomial as a finite
authored premise-list presentation. -/
def toFinite (L : Listing P) :
    FinitePresentation.{uBase, uIndex, uShape} Base Index where
  Shape := P.Shape
  premises := L.premises

/-- The list-based polynomial has one recursive address per listed premise. -/
def polynomial (L : Listing P) :
    IndexedPolynomial.{uBase, uIndex, uShape, 0} Base Index :=
  L.toFinite.polynomial

/-- Readdress a polynomial derivation by the exact authored premise list. -/
def toListed (L : Listing P) :
    Hom P L.polynomial (fun _ i => i) where
  onShape := fun _ _ shape => shape
  onPosition := fun b i shape => (L.positions b i shape).symm
  onNext := by
    intro b i shape position
    change Fin (L.premises b i shape).length at position
    have h := L.next_eq b i shape
      ((L.positions b i shape).symm position)
    have h' : P.next shape ((L.positions b i shape).symm position) =
        (L.premises b i shape).get position := by
      rw [(L.positions b i shape).apply_symm_apply] at h
      exact h
    exact h'.symm

/-- Recover the original premise addresses from the ordered list. -/
def fromListed (L : Listing P) :
    Hom L.polynomial P (fun _ i => i) where
  onShape := fun _ _ shape => shape
  onPosition := L.positions
  onNext := by
    intro b i shape position
    exact L.next_eq b i shape position

/-- Readdressing to a list and back is the original polynomial map. -/
theorem toListed_fromListed (L : Listing P) :
    Hom.comp L.toListed L.fromListed = Hom.id P := by
  apply Hom.ext
  · rfl
  · apply heq_of_eq
    funext b i shape
    apply Equiv.ext
    intro position
    exact (L.positions b i shape).symm_apply_apply position

/-- Readdressing from the list and back also changes nothing. -/
theorem fromListed_toListed (L : Listing P) :
    Hom.comp L.fromListed L.toListed = Hom.id L.polynomial := by
  apply Hom.ext
  · rfl
  · apply heq_of_eq
    funext b i shape
    apply Equiv.ext
    intro position
    exact (L.positions b i shape).apply_symm_apply position

/-- An exact premise listing induces an equivalence of complete derivation
trees at every judgment. Neither repeated premises nor their histories are
identified. -/
noncomputable def treeEquiv (L : Listing P) (b : Base) (i : Index b) :
    P.Fix b i ≃ L.polynomial.Fix b i where
  toFun := L.toListed.mapFix b i
  invFun := L.fromListed.mapFix b i
  left_inv := by
    intro tree
    calc
      L.fromListed.mapFix b i (L.toListed.mapFix b i tree) =
          (Hom.comp L.toListed L.fromListed).mapFix b i tree :=
        (Hom.mapFix_comp L.toListed L.fromListed b i tree).symm
      _ = (Hom.id P).mapFix b i tree := by rw [L.toListed_fromListed]
      _ = tree := Hom.mapFix_id P b i tree
  right_inv := by
    intro tree
    calc
      L.toListed.mapFix b i (L.fromListed.mapFix b i tree) =
          (Hom.comp L.fromListed L.toListed).mapFix b i tree :=
        (Hom.mapFix_comp L.fromListed L.toListed b i tree).symm
      _ = (Hom.id L.polynomial).mapFix b i tree := by
        rw [L.fromListed_toListed]
      _ = tree := Hom.mapFix_id L.polynomial b i tree

/-- The list presentation and original polynomial generate precisely the
same inhabited judgments, without asserting proof irrelevance. -/
theorem nonempty_iff (L : Listing P) (b : Base) (i : Index b) :
    Nonempty (P.Fix b i) ↔ Nonempty (L.polynomial.Fix b i) :=
  (L.treeEquiv b i).nonempty_congr

/-- Readdressing a finite premise list changes neither the predicate models
of the rules nor which premise each rule requires. -/
theorem ruleClosed_iff (L : Listing P)
    (R : ∀ b, Index b → Prop) :
    RuleClosed P R ↔ RuleClosed L.polynomial R := by
  constructor
  · intro original b i shape listedPremises
    apply original b i shape
    intro position
    rw [L.next_eq b i shape position]
    exact listedPremises (L.positions b i shape position)
  · intro listed b i shape originalPremises
    apply listed b i shape
    intro position
    change Fin (L.premises b i shape).length at position
    have h := L.next_eq b i shape
      ((L.positions b i shape).symm position)
    rw [(L.positions b i shape).apply_symm_apply] at h
    change R b ((L.premises b i shape).get position)
    rw [← h]
    exact originalPremises ((L.positions b i shape).symm position)

#print axioms toListed_fromListed
#print axioms fromListed_toListed
#print axioms treeEquiv
#print axioms nonempty_iff
#print axioms ruleClosed_iff
#print axioms FinitePresentation.derivation_least

end Listing

namespace RepeatedPremiseControl

/-- Two alternative leaf firings and one constructor with two ordered
premises at the same judgment. -/
inductive Shape : Bool → Type where
  | left : Shape false
  | right : Shape false
  | pair : Shape true

def presentation : FinitePresentation Unit (fun _ => Bool) where
  Shape _ index := Shape index
  premises := by
    intro _ _ shape
    cases shape with
    | left => exact []
    | right => exact []
    | pair => exact [false, false]

def leftTree : presentation.Derivation () false :=
  .roll .left (fun impossible => Fin.elim0 impossible)

def rightTree : presentation.Derivation () false :=
  .roll .right (fun impossible => Fin.elim0 impossible)

/-- Both children have the same judgment but distinct addresses and
individually retained firing histories. -/
def pairLeftRight : presentation.Derivation () true :=
  .roll .pair (fun position => by
    change Fin 2 at position
    cases position using Fin.cases with
    | zero => exact leftTree
    | succ rest =>
        cases rest using Fin.cases with
        | zero => exact rightTree
        | succ impossible => exact Fin.elim0 impossible)

def pairRightLeft : presentation.Derivation () true :=
  .roll .pair (fun position => by
    change Fin 2 at position
    cases position using Fin.cases with
    | zero => exact rightTree
    | succ rest =>
        cases rest using Fin.cases with
        | zero => exact leftTree
        | succ impossible => exact Fin.elim0 impossible)

def firstChild : presentation.Derivation () true →
    presentation.Derivation () false
  | .roll .pair children => children ⟨0, by decide⟩

theorem left_ne_right : leftTree ≠ rightTree := by
  intro equal
  cases equal

/-- A premise list is not a set: swapping two histories at repeated child
judgments yields a different derivation of the same conclusion. -/
theorem pair_order_matters : pairLeftRight ≠ pairRightLeft := by
  intro equal
  have child := congrArg firstChild equal
  simp only [firstChild, pairLeftRight, pairRightLeft] at child
  exact left_ne_right child

#print axioms pair_order_matters

end RepeatedPremiseControl

end Mettapedia.OSLF.Binding.FiniteRulePremiseLists
