import Mettapedia.OSLF.Syntax.IndexedRulePresentationCategory
import Mathlib.CategoryTheory.Functor.Basic

/-!
# Functorial free firing trees

The least proof-relevant rule derivations of a presentation form a family
indexed by contexts and judgments. A cartesian map of rule presentations
acts on every constructor and recursive premise. The resulting free-tree
assignment preserves identity and composition as a functor.
-/

set_option autoImplicit false

namespace Mettapedia.OSLF.Binding.IndexedRuleTreeFunctor

open CategoryTheory
open Mettapedia.TypeTheory
open Mettapedia.OSLF.Binding.IndexedRulePolynomialMorphisms
open Mettapedia.OSLF.Binding.IndexedRulePresentationCategory

universe uBase uIndex uCarrier uShape uPosition

set_option linter.checkUnivs false in
/-- A family of values over a context-indexed family of judgments. -/
structure IndexedFamily (Base : Type uBase) where
  Judgment : Base → Type uIndex
  value : (b : Base) → Judgment b → Type uCarrier

namespace IndexedFamily

variable {Base : Type uBase}

/-- A map reindexes judgments and transports the values in their exact
judgment fibres. -/
structure Map (source target : IndexedFamily.{uBase, uIndex, uCarrier} Base) where
  judgment : ∀ b, source.Judgment b → target.Judgment b
  value : ∀ b i, source.value b i → target.value b (judgment b i)

namespace Map

variable {source middle target fourth :
  IndexedFamily.{uBase, uIndex, uCarrier} Base}

def id (source : IndexedFamily.{uBase, uIndex, uCarrier} Base) :
    Map source source where
  judgment := fun _ i => i
  value := fun _ _ x => x

def comp (earlier : Map source middle) (later : Map middle target) :
    Map source target where
  judgment := fun b i => later.judgment b (earlier.judgment b i)
  value := fun b i x => later.value b _ (earlier.value b i x)

theorem id_comp (f : Map source target) : comp (id source) f = f := by
  cases f
  rfl

theorem comp_id (f : Map source target) : comp f (id target) = f := by
  cases f
  rfl

theorem comp_assoc (f : Map source middle) (g : Map middle target)
    (h : Map target fourth) :
    comp (comp f g) h = comp f (comp g h) := by
  cases f
  cases g
  cases h
  rfl

end Map

instance : CategoryTheory.Category
    (IndexedFamily.{uBase, uIndex, uCarrier} Base) where
  Hom source target := Map source target
  id := Map.id
  comp := Map.comp
  id_comp := by
    intro source target f
    exact Map.id_comp f
  comp_id := by
    intro source target f
    exact Map.comp_id f
  assoc := by
    intro source middle target fourth f g h
    exact Map.comp_assoc f g h

end IndexedFamily

variable {Base : Type uBase}

/-- The least family generated by every rule constructor of a presentation.
Its values are complete firing histories, not just endpoint facts. -/
def freeTree (P : Presentation.{uBase, uIndex, uShape, uPosition} Base) :
    IndexedFamily.{uBase, uIndex, max uIndex (max uShape uPosition)} Base where
  Judgment := P.Judgment
  value := P.rules.Fix

/-- Interpret complete firing histories along a cartesian presentation map. -/
noncomputable def freeTreeMap
    {P Q : Presentation.{uBase, uIndex, uShape, uPosition} Base}
    (h : Presentation.Map P Q) :
    IndexedFamily.Map (freeTree P) (freeTree Q) where
  judgment := h.judgment
  value := h.rules.mapFix

/-- The free-tree construction is functorial on actual rule-presentation
morphisms. No proof history is collapsed to a mere endpoint predicate. -/
noncomputable def freeTreeFunctor :
    Presentation.{uBase, uIndex, uShape, uPosition} Base ⥤
      IndexedFamily.{uBase, uIndex, max uIndex (max uShape uPosition)} Base where
  obj := freeTree
  map := fun h => freeTreeMap h
  map_id := by
    intro P
    apply congrArg (IndexedFamily.Map.mk (fun _ i => i))
    funext b i tree
    exact Hom.mapFix_id P.rules b i tree
  map_comp := by
    intro P Q R f g
    change freeTreeMap (Presentation.Map.comp f g) =
      IndexedFamily.Map.comp (freeTreeMap f) (freeTreeMap g)
    dsimp only [freeTreeMap, Presentation.Map.comp, IndexedFamily.Map.comp]
    congr 1
    funext b i tree
    exact Hom.mapFix_comp f.rules g.rules b i tree

#print axioms freeTreeFunctor

end Mettapedia.OSLF.Binding.IndexedRuleTreeFunctor
