import Mettapedia.OSLF.Syntax.IntrinsicScopedLocalActedCoherence
import Mettapedia.OSLF.Syntax.SecondOrderEquationModelNaturality

/-!
# Rule-local event contexts vary functorially with the binding model

A natural assignment of event-variable uses is determined by its values on
bare variables: every other use is a bare variable followed by its recorded
substitution, and the model's own action interprets that substitution. Base
change of a finite event context keeps every variable position; base change
of an arrow translates the tree assigned to each variable. These translations
form a functor from binding clones to categories, with identity and
composition holding as equalities of functors.
-/

set_option autoImplicit false

namespace Mettapedia.OSLF.Binding.IntrinsicScopedLocalActedFibres

open CategoryTheory
open Mettapedia.TypeTheory
open Mettapedia.OSLF.Binding
open Mettapedia.OSLF.Binding.BindingSubstitutionAlgebra
open Mettapedia.OSLF.Binding.AuthoredPositionedRulePolynomial (Judgment mapJudgment)
open Mettapedia.OSLF.Binding.IntrinsicScopedConditionalSubstitution
  (substJudgment heq_transport)
open Mettapedia.OSLF.Binding.IntrinsicScopedConditionalJudgmentCategory
open Mettapedia.OSLF.Binding.IntrinsicScopedConditionalEventOrbit
open Mettapedia.OSLF.Binding.IntrinsicScopedLocalPolynomial
open Mettapedia.OSLF.Binding.IntrinsicScopedLocalSubstitutionModel
open Mettapedia.OSLF.Binding.IntrinsicScopedLocalActedFree
open Mettapedia.OSLF.Binding.IntrinsicScopedConditionalActedBaseChange (pushState pushMap pushOrbit
  pushOrbit_unit)
open Mettapedia.OSLF.Binding.IntrinsicScopedLocalActedBaseChange
open Mettapedia.OSLF.Binding.IntrinsicScopedLocalActedCoherence
open Mettapedia.OSLF.Binding.IntrinsicScopedLocalActedFiniteContext (Context seeds exactHole Hom)

variable {S : Signature}
variable (R : List (LocalRule S))

/-! ## Natural assignments are determined by bare variables -/

section Generators

variable (A : BindingCloneAlgebra.Algebra.{0} S)
variable (Seed : (sort : S.Srt) → State A sort → Type)

/-- The natural assignment generated by values on bare event variables. -/
noncomputable def ofGenerators (model : SubstitutionModel R A)
    (assigned : ∀ sort (state : State A sort),
      Seed sort state → model.carrier (state.asJudgment A)) :
    NaturalAssignment R A Seed model where
  value judgment hole := hole.interpret A Seed model.toAction (assigned judgment.2.1)
  map := by
    intro judgment hole Δ σ target h
    subst h
    exact Orbit.interpret_map A Seed model.toAction (assigned judgment.2.1) hole
      (substitutionArrow A judgment σ)

/-- The bare-variable values of a natural assignment. -/
noncomputable def generators (model : SubstitutionModel R A)
    (assignment : NaturalAssignment R A Seed model) :
    ∀ sort (state : State A sort),
      Seed sort state → model.carrier (state.asJudgment A) :=
  fun _ state seed => assignment.value (state.asJudgment A) (Orbit.unit A Seed seed)

/-- The target of an arrow is the substituted source. -/
theorem ofJudgment_substitute (judgment : Judgment A)
    {first : State A judgment.2.1} (f : first ⟶ ofJudgment A judgment) :
    (ofJudgment A (substJudgment (first.asJudgment A) f.environment) :
        State A judgment.2.1) = ofJudgment A judgment := by
  exact congrArg₂ (fun source target => (State.mk judgment.1 source target :
    State A judgment.2.1)) f.sourceEq f.targetEq

/-- Every natural assignment is generated by its values on bare variables. -/
theorem eq_ofGenerators (model : SubstitutionModel R A)
    (assignment : NaturalAssignment R A Seed model) :
    assignment = ofGenerators R A Seed model (generators R A Seed model assignment) := by
  apply NaturalAssignment.ext R A Seed model
  intro judgment hole
  obtain ⟨original, seed, arrow⟩ := hole
  have natural := assignment.map (original.asJudgment A) (Orbit.unit A Seed seed)
    arrow.environment judgment (Map.as_substitution A arrow)
  refine Eq.trans ?_ natural
  have sameHole : HEq (Orbit.mk original seed arrow : Holes A Seed judgment)
      (IntrinsicScopedConditionalActedFree.mapHole A Seed (original.asJudgment A)
        (Orbit.unit A Seed seed) arrow.environment) := by
    refine IntrinsicScopedLocalActedCoherence.orbit_heq_of_environment seed
      (ofJudgment_substitute A judgment arrow).symm arrow _ ?_
    exact heq_of_eq (funext fun _ => funext fun v =>
      (A.substitution.substitute_var arrow.environment v).symm)
  exact eq_of_heq ((NaturalAssignment.value_heq R A Seed assignment
    (Map.as_substitution A arrow).symm sameHole).trans (heq_transport _ _).symm)

/-- Substituting an arrow's trees and then interpreting in a model. -/
noncomputable def composeAssignment
    {Seed' : (sort : S.Srt) → State A sort → Type}
    (substitution : NaturalAssignment R A Seed (freeModel R A Seed'))
    {model : SubstitutionModel R A} (assigned : NaturalAssignment R A Seed' model) :
    NaturalAssignment R A Seed model :=
  assignmentOfHom R A Seed model (SubstitutionModel.Hom.comp R A
    (foldHom R A Seed (freeModel R A Seed') substitution) (foldHom R A Seed' model assigned))

theorem interpret_composeAssignment
    {Seed' : (sort : S.Srt) → State A sort → Type}
    (substitution : NaturalAssignment R A Seed (freeModel R A Seed'))
    {model : SubstitutionModel R A} (assigned : NaturalAssignment R A Seed' model)
    (judgment : Judgment A) (tree : Tree R A Seed judgment) :
    interpret R A Seed model (composeAssignment R A Seed substitution assigned) judgment tree =
      interpret R A Seed' model assigned judgment
        (interpret R A Seed (freeModel R A Seed') substitution judgment tree) :=
  congrArg (fun hom : SubstitutionModel.Hom R A (freeModel R A Seed) model =>
      hom.evidence.toFun () judgment tree)
    ((freeModelUniversal R A Seed model).right_inv _)

end Generators

/-! ## Arrows of event contexts are tuples of trees -/

section Slots

variable (A : BindingCloneAlgebra.Algebra.{0} S)
variable {Γ Δ : Context R A}

/-- The tree an arrow assigns to one listed variable of its target. -/
noncomputable def atSlot (f : Hom R A Γ Δ) (position : Fin Δ.listed.length) :
    Tree R A (seeds R A Γ) (Δ.listed.label position) :=
  f.value (Δ.listed.label position) (exactHole R A Δ ⟨position, ⟨rfl⟩⟩)

/-- A bare use of a listed variable, at any judgment equal to its label, is
interpreted as that variable. -/
theorem value_exactHole_transport {model : SubstitutionModel R A}
    (assigned : NaturalAssignment R A (seeds R A Δ) model) (position : Fin Δ.listed.length)
    {judgment : Judgment A} (equal : Δ.listed.label position = judgment) :
    assigned.value judgment (exactHole R A Δ ⟨position, ⟨equal⟩⟩) =
      equal ▸ assigned.value _ (exactHole R A Δ ⟨position, ⟨rfl⟩⟩) := by
  subst equal
  rfl

/-- Interpretations of the listed variables' uses agreeing on the variables
themselves are equal. -/
theorem assignment_ext_slot {model : SubstitutionModel R A}
    {first second : NaturalAssignment R A (seeds R A Δ) model}
    (same : ∀ position : Fin Δ.listed.length,
      first.value _ (exactHole R A Δ ⟨position, ⟨rfl⟩⟩) =
        second.value _ (exactHole R A Δ ⟨position, ⟨rfl⟩⟩)) :
    first = second := by
  refine (eq_ofGenerators R A (seeds R A Δ) model first).trans
    (Eq.trans ?_ (eq_ofGenerators R A (seeds R A Δ) model second).symm)
  congr 1
  funext sort state slot
  obtain ⟨position, ⟨equal⟩⟩ := slot
  exact (value_exactHole_transport R A first position equal).trans
    ((congrArg (fun value => equal ▸ value) (same position)).trans
      (value_exactHole_transport R A second position equal).symm)

/-- A bare use of a listed variable, at any judgment equal to its label,
reads the tree assigned to that variable. -/
theorem value_exactHole (f : Hom R A Γ Δ) (position : Fin Δ.listed.length)
    {judgment : Judgment A} (equal : Δ.listed.label position = judgment) :
    f.value judgment (exactHole R A Δ ⟨position, ⟨equal⟩⟩) =
      equal ▸ atSlot R A f position :=
  value_exactHole_transport R A f position equal

/-- Arrows assigning the same tree to every listed variable are equal. -/
theorem hom_ext_slot {f g : Hom R A Γ Δ}
    (same : ∀ position, atSlot R A f position = atSlot R A g position) :
    f = g :=
  assignment_ext_slot R A same

/-- The interpretation of every use of the listed variables with the given
values at the variables themselves. -/
noncomputable def ofSlotValues (model : SubstitutionModel R A) (Δ : Context R A)
    (values : ∀ position : Fin Δ.listed.length,
      model.carrier (Δ.listed.label position)) :
    NaturalAssignment R A (seeds R A Δ) model :=
  ofGenerators R A (seeds R A Δ) model (fun _ _ slot => slot.2.down ▸ values slot.1)

theorem value_ofSlotValues (model : SubstitutionModel R A) (Δ : Context R A)
    (values : ∀ position : Fin Δ.listed.length,
      model.carrier (Δ.listed.label position))
    (position : Fin Δ.listed.length) :
    (ofSlotValues R A model Δ values).value _ (exactHole R A Δ ⟨position, ⟨rfl⟩⟩) =
      values position := by
  change Orbit.interpret (state := ofJudgment A (Δ.listed.label position))
      A (seeds R A Δ) model.toAction
      (fun _ slot => slot.2.down ▸ values slot.1)
      (Orbit.unit A (seeds R A Δ) ((State.as_of A (Δ.listed.label position)).symm ▸
        (⟨position, ⟨rfl⟩⟩ : (IndexedRuleFiniteListSkeleton.toContext (rules R A)
          Δ.listed).slots (Δ.listed.label position)))) = values position
  rw [Orbit.interpret_unit]

/-- The arrow assigning the given tree to each listed variable. -/
noncomputable def ofSlots
    (values : ∀ position : Fin Δ.listed.length,
      Tree R A (seeds R A Γ) (Δ.listed.label position)) :
    Hom R A Γ Δ :=
  ofSlotValues R A (freeModel R A (seeds R A Γ)) Δ values

theorem atSlot_ofSlots
    (values : ∀ position : Fin Δ.listed.length,
      Tree R A (seeds R A Γ) (Δ.listed.label position))
    (position : Fin Δ.listed.length) :
    atSlot R A (ofSlots R A values) position = values position :=
  value_ofSlotValues R A (freeModel R A (seeds R A Γ)) Δ values position

/-- Arrows between finite event contexts are exactly tuples of firing
trees, one for each listed variable of the target. -/
noncomputable def slotEquiv :
    Hom R A Γ Δ ≃ ∀ position : Fin Δ.listed.length,
      Tree R A (seeds R A Γ) (Δ.listed.label position) where
  toFun f position := atSlot R A f position
  invFun := ofSlots R A
  left_inv f := hom_ext_slot R A fun position =>
    atSlot_ofSlots R A (fun position => atSlot R A f position) position
  right_inv values := funext fun position => atSlot_ofSlots R A values position

theorem atSlot_id (Γ : Context R A) (position : Fin Γ.listed.length) :
    atSlot R A (IntrinsicScopedLocalActedFiniteContext.Hom.id R A Γ) position =
      IndexedPolynomial.Free.pure (rules R A)
        (exactHole R A Γ ⟨position, ⟨rfl⟩⟩) := rfl

/-- Composition substitutes the first arrow's trees into the second's. -/
theorem atSlot_comp {Θ : Context R A} (first : Hom R A Γ Δ)
    (second : Hom R A Δ Θ) (position : Fin Θ.listed.length) :
    atSlot R A (IntrinsicScopedLocalActedFiniteContext.Hom.comp R A first second)
        position =
      interpret R A (seeds R A Δ) (freeModel R A (seeds R A Γ)) first _
        (atSlot R A second position) := rfl

/-- Following an arrow by a cast of its target context reads the same trees
at the corresponding positions. -/
theorem atSlot_comp_eqToHom {Θ : Context R A} (f : Hom R A Γ Δ) (same : Δ = Θ)
    {position : Fin Δ.listed.length} {castPosition : Fin Θ.listed.length}
    (samePosition : HEq position castPosition) :
    HEq (atSlot R A (f ≫ eqToHom same : Hom R A Γ Θ) castPosition)
      (atSlot R A f position) := by
  subst same
  cases samePosition
  rw [eqToHom_refl, Category.comp_id]

theorem atSlot_comp_comp_eqToHom {Θ Ψ : Context R A} (f : Γ ⟶ Δ)
    (g : Δ ⟶ Θ) (same : Θ = Ψ)
    {position : Fin Θ.listed.length} {castPosition : Fin Ψ.listed.length}
    (samePosition : HEq position castPosition) :
    HEq (atSlot R A (f ≫ g ≫ eqToHom same : Γ ⟶ Ψ) castPosition)
      (atSlot R A (f ≫ g : Γ ⟶ Θ) position) := by
  subst same
  cases samePosition
  rw [eqToHom_refl, Category.comp_id]

theorem interpret_heq (f : Hom R A Γ Δ) {first second : Judgment A} (same : first = second)
    {one : Tree R A (seeds R A Δ) first} {two : Tree R A (seeds R A Δ) second}
    (sameTree : HEq one two) :
    HEq (interpret R A (seeds R A Δ) (freeModel R A (seeds R A Γ)) f first one)
      (interpret R A (seeds R A Δ) (freeModel R A (seeds R A Γ)) f second two) := by
  subst same
  cases sameTree
  rfl

end Slots

/-! ## Contexts with no variable, one added variable, or one variable -/

section Extension

variable (A : BindingCloneAlgebra.Algebra.{0} S)

/-- The event context with no variables. -/
def _root_.Mettapedia.OSLF.Binding.IntrinsicScopedLocalActedFiniteContext.Context.empty :
    Context R A :=
  ⟨⟨0, Fin.elim0⟩⟩

/-- Add one event variable, in the first position. -/
def _root_.Mettapedia.OSLF.Binding.IntrinsicScopedLocalActedFiniteContext.Context.cons
    (judgment : Judgment A) (Γ : Context R A) : Context R A :=
  ⟨⟨Γ.listed.length + 1, Fin.cons judgment Γ.listed.label⟩⟩

/-- The event context with exactly one variable. -/
def _root_.Mettapedia.OSLF.Binding.IntrinsicScopedLocalActedFiniteContext.Context.single
    (judgment : Judgment A) : Context R A :=
  ⟨⟨1, fun _ => judgment⟩⟩

variable {A}

/-- Arrows into a context without variables are equal. -/
theorem hom_ext_empty {Γ Δ : Context R A} (empty : Δ.listed.length = 0)
    (f g : Hom R A Γ Δ) : f = g :=
  hom_ext_slot R A fun position => absurd position.isLt (by omega)

/-- The arrow into a context without variables. -/
noncomputable def toEmpty (Γ Δ : Context R A) (empty : Δ.listed.length = 0) :
    Hom R A Γ Δ :=
  ofSlots R A fun position => absurd position.isLt (by omega)

/-- The use of one listed variable as a tree. -/
noncomputable def leaf (Γ : Context R A) (position : Fin Γ.listed.length) :
    Tree R A (seeds R A Γ) (Γ.listed.label position) :=
  IndexedPolynomial.Free.pure (rules R A) (exactHole R A Γ ⟨position, ⟨rfl⟩⟩)

/-- Substituting an arrow's trees into the use of a listed variable gives
that variable's tree. -/
theorem interpret_leaf {Γ Δ : Context R A} (f : Hom R A Γ Δ) (position : Fin Δ.listed.length) :
    interpret R A (seeds R A Δ) (freeModel R A (seeds R A Γ)) f _
        (leaf R Δ position) =
      atSlot R A f position :=
  rfl

/-- The position of the added variable. -/
def first (judgment : Judgment A) (Γ : Context R A) :
    Fin (Γ.cons R A judgment).listed.length :=
  (0 : Fin (Γ.listed.length + 1))

/-- Forget the first event variable. -/
noncomputable def weaken (judgment : Judgment A) (Γ : Context R A) :
    Hom R A (Γ.cons R A judgment) Γ :=
  ofSlots R A fun position => leaf R (Γ.cons R A judgment) position.succ

theorem atSlot_weaken (judgment : Judgment A) (Γ : Context R A)
    (position : Fin Γ.listed.length) :
    atSlot R A (weaken R judgment Γ) position = leaf R (Γ.cons R A judgment) position.succ :=
  atSlot_ofSlots R A _ position

/-- An authored rule occurrence as an arrow from its ordered, binder-local
premises to its conclusion. -/
noncomputable def constructorArrow {judgment : Judgment A}
    (shape : Shape R A judgment) :
    Hom R A ⟨⟨(R.get shape.1.index).2.premises.length, childJudgment R A shape.1⟩⟩
      (Context.single R A judgment) :=
  ofSlots R A fun _ => IndexedPolynomial.Free.node (rules R A) shape
    fun position => leaf R ⟨⟨(R.get shape.1.index).2.premises.length,
      childJudgment R A shape.1⟩⟩ position

/-- One event variable used through a contextual substitution. -/
noncomputable def substitutionArrow (judgment : Judgment A) {Δ : Ctx S}
    (σ : Environment S A.substitution.Carrier judgment.1 Δ) :
    Hom R A (Context.single R A judgment)
      (Context.single R A (substJudgment judgment σ)) :=
  ofSlots R A fun _ => IndexedPolynomial.Free.pure (rules R A)
    (IntrinsicScopedConditionalActedFree.mapHole A _ judgment
      (exactHole R A (Context.single R A judgment) ⟨(0 : Fin 1), ⟨rfl⟩⟩) σ)

theorem interpret_comp_eqToHom {Γ Δ Θ : Context R A} (f : Γ ⟶ Δ) (same : Δ = Θ)
    {first second : Judgment A} (sameJudgment : first = second)
    {one : Tree R A (seeds R A Θ) first} {two : Tree R A (seeds R A Δ) second}
    (sameTree : HEq one two) :
    HEq (interpret R A (seeds R A Θ) (freeModel R A (seeds R A Γ))
        (f ≫ eqToHom same : Γ ⟶ Θ) first one)
      (interpret R A (seeds R A Δ) (freeModel R A (seeds R A Γ)) f second two) := by
  subst same
  subst sameJudgment
  cases sameTree
  rw [eqToHom_refl, Category.comp_id]

/-- A cast of contexts assigns to each variable the use of the same variable. -/
theorem atSlot_eqToHom {Γ Δ : Context R A} (same : Γ = Δ) {position : Fin Γ.listed.length}
    {castPosition : Fin Δ.listed.length} (samePosition : HEq position castPosition) :
    HEq (atSlot R A (eqToHom same : Γ ⟶ Δ) castPosition) (leaf R Γ position) := by
  subst same
  cases samePosition
  rfl

/-- Interpretations in equal models agree when the assignments agree on the
listed variables. -/
theorem interpret_heq_of_slots {Δ : Context R A} {first second : SubstitutionModel R A}
    (same : first = second)
    (firstAssigned : NaturalAssignment R A (seeds R A Δ) first)
    (secondAssigned : NaturalAssignment R A (seeds R A Δ) second)
    (slots : ∀ position : Fin Δ.listed.length,
      HEq (firstAssigned.value _ (exactHole R A Δ ⟨position, ⟨rfl⟩⟩))
        (secondAssigned.value _ (exactHole R A Δ ⟨position, ⟨rfl⟩⟩)))
    (judgment : Judgment A) (tree : Tree R A (seeds R A Δ) judgment) :
    HEq (interpret R A (seeds R A Δ) first firstAssigned judgment tree)
      (interpret R A (seeds R A Δ) second secondAssigned judgment tree) := by
  subst same
  have assignments : firstAssigned = secondAssigned :=
    assignment_ext_slot R A fun position => eq_of_heq (slots position)
  subst assignments
  rfl

end Extension

/-! ## Base change of event contexts -/

section BaseChange

variable {A B C : BindingCloneAlgebra.Algebra.{0} S}

/-- Base change keeps every listed event variable and its position. -/
def pushContext (h : FreeBindingClone.Hom A B) (Γ : Context R A) : Context R B :=
  ⟨Γ.listed.relabel (mapJudgment h)⟩

/-- A listed variable keeps its position under base change. -/
def pushSeed (h : FreeBindingClone.Hom A B) (Γ : Context R A) :
    ∀ sort (state : State A sort),
      seeds R A Γ sort state → seeds R B (pushContext R h Γ) sort (pushState h state) :=
  fun _ _ slot => Γ.listed.relabelSlot (mapJudgment h) slot

/-- Base change translates the tree assigned to each listed variable. -/
noncomputable def pushArrow (h : FreeBindingClone.Hom A B) {Γ Δ : Context R A}
    (f : Hom R A Γ Δ) : Hom R B (pushContext R h Γ) (pushContext R h Δ) :=
  ofSlots R B fun position =>
    pushTree R h (pushSeed R h Γ) (Δ.listed.label position) (atSlot R A f position)

theorem atSlot_pushArrow (h : FreeBindingClone.Hom A B) {Γ Δ : Context R A}
    (f : Hom R A Γ Δ) (position : Fin Δ.listed.length) :
    atSlot R B (pushArrow R h f) position =
      pushTree R h (pushSeed R h Γ) (Δ.listed.label position) (atSlot R A f position) :=
  atSlot_ofSlots R B (Γ := pushContext R h Γ) (Δ := pushContext R h Δ) _ position

theorem pushArrow_id (h : FreeBindingClone.Hom A B) (Γ : Context R A) :
    pushArrow R h (IntrinsicScopedLocalActedFiniteContext.Hom.id R A Γ) =
      IntrinsicScopedLocalActedFiniteContext.Hom.id R B (pushContext R h Γ) := by
  apply hom_ext_slot R B
  intro position
  refine (atSlot_pushArrow R h (IntrinsicScopedLocalActedFiniteContext.Hom.id R A Γ)
    position).trans ?_
  refine (pushTree_pure R h (pushSeed R h Γ) _ _).trans ?_
  exact congrArg (IndexedPolynomial.Free.pure (rules R B))
    (pushOrbit_unit h (pushSeed R h Γ) _)

/-- Base change of a use of a listed variable reads the translated tree of
that variable, substituted along the translated arrow. -/
theorem pushTree_value (h : FreeBindingClone.Hom A B) {Γ Δ : Context R A}
    (f : Hom R A Γ Δ) (judgment : Judgment A)
    (hole : Holes A (seeds R A Δ) judgment) :
    pushTree R h (pushSeed R h Γ) judgment (f.value judgment hole) =
      (pushArrow R h f).value (mapJudgment h judgment)
        (pushHole h (pushSeed R h Δ) judgment hole) := by
  obtain ⟨original, ⟨position, ⟨equal⟩⟩, arrow⟩ := hole
  have generated := congrArg
    (fun g : Hom R A Γ Δ => g.value judgment ⟨original, ⟨position, ⟨equal⟩⟩, arrow⟩)
    (eq_ofGenerators R A (seeds R A Δ) (freeModel R A (seeds R A Γ)) f)
  refine (congrArg (pushTree R h (pushSeed R h Γ) judgment) generated).trans ?_
  refine (congrArg (fun tree => pushTree R h (pushSeed R h Γ) judgment
      (substitute R A (seeds R A Γ) (original.asJudgment A) tree
        arrow.environment judgment (Map.as_substitution A arrow)))
      (value_exactHole R A f position equal)).trans ?_
  refine (pushTree_substitute R h (pushSeed R h Γ) (original.asJudgment A)
      (equal ▸ atSlot R A f position) arrow.environment judgment _).trans ?_
  refine (congrArg (fun tree => substitute R B (seeds R B (pushContext R h Γ))
      (mapJudgment h (original.asJudgment A)) tree
      (fun t v => h.raw.map (arrow.environment t v)) (mapJudgment h judgment) _)
      (pushTree_transport R h (pushSeed R h Γ) equal _)).trans ?_
  rfl

/-- Base change commutes with substituting an arrow's trees for the listed
variables of a firing tree. -/
theorem pushTree_interpret (h : FreeBindingClone.Hom A B) {Γ Δ : Context R A}
    (f : Hom R A Γ Δ) (judgment : Judgment A)
    (tree : Tree R A (seeds R A Δ) judgment) :
    pushTree R h (pushSeed R h Γ) judgment
        (interpret R A (seeds R A Δ) (freeModel R A (seeds R A Γ)) f judgment tree) =
      interpret R B (seeds R B (pushContext R h Δ))
        (freeModel R B (seeds R B (pushContext R h Γ))) (pushArrow R h f)
        (mapJudgment h judgment) (pushTree R h (pushSeed R h Δ) judgment tree) :=
  IndexedRuleFreeSubstitutionNaturality.mapFree_bind (presentationMap R h).rules
    (fun _ j hole => pushHole h (pushSeed R h Δ) j hole)
    (fun _ j hole => pushHole h (pushSeed R h Γ) j hole)
    (fun _ j hole => f.value j hole)
    (fun _ j hole => (pushArrow R h f).value j hole)
    (fun _ j hole => pushTree_value R h f j hole) () judgment tree

theorem pushArrow_comp (h : FreeBindingClone.Hom A B) {Γ Δ Θ : Context R A}
    (first : Hom R A Γ Δ) (second : Hom R A Δ Θ) :
    pushArrow R h (IntrinsicScopedLocalActedFiniteContext.Hom.comp R A first second) =
      IntrinsicScopedLocalActedFiniteContext.Hom.comp R B
        (pushArrow R h first) (pushArrow R h second) := by
  apply hom_ext_slot R B
  intro position
  refine (atSlot_pushArrow R h
    (IntrinsicScopedLocalActedFiniteContext.Hom.comp R A first second) position).trans ?_
  refine Eq.trans ?_ (atSlot_comp R B (pushArrow R h first) (pushArrow R h second)
    position).symm
  refine (pushTree_interpret R h first _ (atSlot R A second position)).trans ?_
  exact congrArg _ (atSlot_pushArrow R h second position).symm

/-- Base change maps the use of a listed variable to the use of the same
variable in the base-changed context. -/
theorem pushHole_exactHole (h : FreeBindingClone.Hom A B) (Γ : Context R A)
    (position : Fin Γ.listed.length) :
    pushHole h (pushSeed R h Γ) (Γ.listed.label position)
        (exactHole R A Γ ⟨position, ⟨rfl⟩⟩) =
      exactHole R B (pushContext R h Γ) ⟨position, ⟨rfl⟩⟩ :=
  pushOrbit_unit h (pushSeed R h Γ) _

theorem pushTree_leaf (h : FreeBindingClone.Hom A B) (Γ : Context R A)
    (position : Fin Γ.listed.length) :
    pushTree R h (pushSeed R h Γ) (Γ.listed.label position) (leaf R Γ position) =
      leaf R (pushContext R h Γ) position :=
  (pushTree_pure R h (pushSeed R h Γ) _ _).trans
    (congrArg (IndexedPolynomial.Free.pure (rules R B)) (pushHole_exactHole R h Γ position))

theorem pushTree_heq (h : FreeBindingClone.Hom A B)
    {Seed : (sort : S.Srt) → State A sort → Type}
    {TargetSeed : (sort : S.Srt) → State B sort → Type}
    (seedMap : ∀ sort (state : State A sort),
      Seed sort state → TargetSeed sort (pushState h state))
    {first second : Judgment A} (same : first = second)
    {one : Tree R A Seed first} {two : Tree R A Seed second} (sameTree : HEq one two) :
    HEq (pushTree R h seedMap first one) (pushTree R h seedMap second two) := by
  subst same
  cases sameTree
  rfl

/-- Base change along a map equal to the identity leaves trees unchanged. -/
theorem pushTree_heq_of_eq_id {h : FreeBindingClone.Hom A A}
    (identity : h = FreeBindingClone.Hom.id A) (Γ : Context R A) (judgment : Judgment A)
    (tree : Tree R A (seeds R A Γ) judgment) :
    HEq (pushTree R h (pushSeed R h Γ) judgment tree) tree := by
  subst identity
  exact heq_of_eq (pushTree_id R judgment tree)

/-- Base change of rule-local event contexts along a binding-clone map. -/
noncomputable def pushFunctor (h : FreeBindingClone.Hom A B) :
    Context R A ⥤ Context R B where
  obj := pushContext R h
  map := pushArrow R h
  map_id := pushArrow_id R h
  map_comp first second := pushArrow_comp R h first second

theorem pushArrow_id_base {Γ Δ : Context R A} (f : Hom R A Γ Δ) :
    pushArrow R (FreeBindingClone.Hom.id A) f = f := by
  apply hom_ext_slot R A
  intro position
  exact (atSlot_pushArrow R _ f position).trans (pushTree_id R _ (atSlot R A f position))

theorem pushArrow_comp_base (first : FreeBindingClone.Hom A B)
    (second : FreeBindingClone.Hom B C) {Γ Δ : Context R A} (f : Hom R A Γ Δ) :
    pushArrow R (FreeBindingClone.Hom.comp first second) f =
      pushArrow R second (pushArrow R first f) := by
  apply hom_ext_slot R C
  intro position
  refine (atSlot_pushArrow R _ f position).trans ?_
  refine Eq.trans ?_ (atSlot_pushArrow R second (pushArrow R first f) position).symm
  refine Eq.trans ?_ (congrArg _ (atSlot_pushArrow R first f position).symm)
  exact pushTree_comp R first second (pushSeed R first Γ)
    (pushSeed R second (pushContext R first Γ)) _ (atSlot R A f position)

/-- The identity binding map changes no context and no arrow. -/
theorem pushFunctor_id (A : BindingCloneAlgebra.Algebra.{0} S) :
    pushFunctor R (FreeBindingClone.Hom.id A) = 𝟭 (Context R A) :=
  Functor.hext (fun _ => rfl) fun _ _ f => heq_of_eq (pushArrow_id_base R f)

/-- Successive binding maps act on event contexts as their composite. -/
theorem pushFunctor_comp (first : FreeBindingClone.Hom A B)
    (second : FreeBindingClone.Hom B C) :
    pushFunctor R (FreeBindingClone.Hom.comp first second) =
      pushFunctor R first ⋙ pushFunctor R second :=
  Functor.hext (fun _ => rfl) fun _ _ f =>
    heq_of_eq (pushArrow_comp_base R first second f)

end BaseChange

/-! ## Functoriality in the binding model and in equation contexts -/

/-- Rule-local event contexts vary functorially with the binding model. -/
noncomputable def localActedFibres :
    BindingCloneAlgebra.Algebra.{0} S ⥤ Cat.{0, 0} where
  obj A := Cat.of (Context R A)
  map h := (pushFunctor R h).toCatHom
  map_id A := by
    apply Cat.Hom.ext
    exact pushFunctor_id R A
  map_comp first second := by
    apply Cat.Hom.ext
    exact pushFunctor_comp R first second

/-- Over authored equation contexts, event contexts live in the equation-class
binding model; an equation-context arrow, a class of contextual assignments,
changes them through its model map. -/
noncomputable def authoredLocalActedFibres {M : List (MetaArity S)}
    (equations : List (EqAxiom S M)) :
    (SecondOrderContext.EquationContexts
        (SecondOrderContext.authoredEquationPresentation S equations))ᵒᵖ ⥤
      Cat.{0, 0} :=
  SecondOrderContext.authoredEquationQuotientModelPresheaf S equations ⋙
    SecondOrderContext.forgetEquations equations ⋙ localActedFibres R

end Mettapedia.OSLF.Binding.IntrinsicScopedLocalActedFibres
