import Mettapedia.OSLF.Syntax.EquationExtensionEventGraph
import Mettapedia.OSLF.Syntax.RhoSourceEventComparison

/-!
# The rho equation-and-event comparison

The actual ACU-to-source equation extension changes the name-state quotient:
the source's quote/drop equation identifies two ACU-distinct name classes.
It does not identify communication or Drop firing occurrences. The general
equation-extension graph map specializes to this presentation, and its square
with the literal COMM-to-COMM-plus-Drop rule extension commutes.
-/

set_option autoImplicit false

namespace Mettapedia.OSLF.Binding.RhoEquationEventComparison

open _root_.CategoryTheory
open Mettapedia.OSLF.Binding.RhoSchema
open Mettapedia.OSLF.Binding.RhoSourceEquationModel
open Mettapedia.OSLF.Binding.RhoSourceEventComparison
open Mettapedia.OSLF.Binding.EquationExtensionEventGraph
open Mettapedia.OSLF.Binding.RuleListEventEmbedding

/-- The source's extra equation acts on the actual combined COMM/Drop event
graph, at each of rho's two sorted state fibres. -/
def acuToSourceGraph (sort : Srt) :
    EventGraphHom
      (presentedGraph rhoE rhoSourceWithDrop.toUnpositioned.rules sort)
      (presentedGraph rhoSourceE rhoSourceWithDrop.toUnpositioned.rules sort) :=
  equationGraphMap acu_in_source _ sort

/-- Its state component is exactly the previously constructed morphism
between the initial ACU and full source binding-equation models. -/
theorem acuToSourceGraph_state (sort : Srt)
    (X : (Syntactic.Ctxt sig)ᵒᵖ)
    (q : TermQ rhoE X.unop.vars sort) :
    (acuToSourceGraph sort).vertexMap.app X q =
      acu_to_source.raw.map q :=
  compareStates_eq_comparisonHom acu_in_source sort X q

/-- Neither rule identity nor its located firing is quotiented by adding
the source reflection equation. -/
theorem acuToSourceGraph_event (sort : Srt)
    (X : (Syntactic.Ctxt sig)ᵒᵖ)
    (event : (presentedGraph rhoE
      rhoSourceWithDrop.toUnpositioned.rules sort).edge.obj X) :
    (acuToSourceGraph sort).edgeMap.app X event = event := rfl

/-- The new source equation genuinely coarsens the name-state fibre. This
negative control rules out treating equation extension as an event-graph
embedding on both components. -/
theorem name_state_map_not_injective :
    ¬ Function.Injective
      ((acuToSourceGraph Srt.nm).vertexMap.app
        (Opposite.op ⟨[Srt.nm]⟩)) := by
  intro injective
  apply acu_to_source_not_injective
  intro first later same
  apply injective
  exact (acuToSourceGraph_state Srt.nm
    (Opposite.op ⟨[Srt.nm]⟩) first).trans
      (same.trans (acuToSourceGraph_state Srt.nm
        (Opposite.op ⟨[Srt.nm]⟩) later).symm)

/-- Any actual COMM/Drop step valid modulo the older ACU equations remains
valid modulo the full source equations, witnessed by that same event. -/
theorem acu_step_remains_source_step {sort : Srt}
    {source target : Term sig [] sort}
    (step :
      (presentation rhoE rhoSourceWithDrop.toUnpositioned.rules).StepModE
        source target) :
    (presentation rhoSourceE rhoSourceWithDrop.toUnpositioned.rules).StepModE
      source target :=
  stepModE_of_equation_inclusion acu_in_source _ step

/-- The source's two additions, the reflection equation and the Drop rule,
commute as morphisms of the actual rho event graphs. -/
theorem comm_drop_equation_square :
    EventGraphHom.comp
        (ruleGraphMap (E := rhoE) sourceCommRuleEmbedding Srt.pr)
        (equationGraphMap acu_in_source
          rhoSourceWithDrop.toUnpositioned.rules Srt.pr) =
      EventGraphHom.comp
        (equationGraphMap acu_in_source
          rhoSourceComm.toUnpositioned.rules Srt.pr)
        (ruleGraphMap (E := rhoSourceE) sourceCommRuleEmbedding Srt.pr) :=
  rule_equation_square acu_in_source sourceCommRuleEmbedding Srt.pr

/-- The combined rho comparison is a single morphism generated by the
two-axis presentation functor. -/
private def acuCommObject :
    EquationCatalogue sig metas × Catalogue sig metas :=
  (⟨rhoE⟩, ⟨rhoSourceComm.toUnpositioned.rules⟩)

private def sourceDropObject :
    EquationCatalogue sig metas × Catalogue sig metas :=
  (⟨rhoSourceE⟩, ⟨rhoSourceWithDrop.toUnpositioned.rules⟩)

private def acuCommToSourceDrop : acuCommObject ⟶ sourceDropObject :=
  (⟨acu_in_source⟩, sourceCommRuleEmbedding)

def rhoTwoAxisMap :
    EventGraphHom
      (presentedGraph rhoE rhoSourceComm.toUnpositioned.rules Srt.pr)
      (presentedGraph rhoSourceE
        rhoSourceWithDrop.toUnpositioned.rules Srt.pr) :=
  (presentationGraphBifunctor (S := sig) (M := metas) Srt.pr).map
    acuCommToSourceDrop

/-- The functorial combined map transports process states by the same
initial-model comparison used on the separate equation axis. -/
theorem rhoTwoAxisMap_state (X : (Syntactic.Ctxt sig)ᵒᵖ)
    (q : TermQ rhoE X.unop.vars Srt.pr) :
    rhoTwoAxisMap.vertexMap.app X q = acu_to_source.raw.map q :=
  compareStates_eq_comparisonHom acu_in_source Srt.pr X q

/-- The combined map retains each located COMM firing as the same occurrence
in the COMM-plus-Drop catalogue. -/
theorem rhoTwoAxisMap_event (X : (Syntactic.Ctxt sig)ᵒᵖ)
    (event : (presentedGraph rhoE
      rhoSourceComm.toUnpositioned.rules Srt.pr).edge.obj X) :
    rhoTwoAxisMap.edgeMap.app X event = embedCommEvent event :=
  sourceCommEmbedding_agrees event

/-- Equation-first and rule-first paths through the rho ladder are equal
as graph maps, not merely extensionally equal on a selected closed step. -/
theorem rhoTwoAxisMap_rule_first :
    rhoTwoAxisMap =
      EventGraphHom.comp
        (ruleGraphMap (E := rhoE) sourceCommRuleEmbedding Srt.pr)
        (equationGraphMap acu_in_source
          rhoSourceWithDrop.toUnpositioned.rules Srt.pr) :=
  comm_drop_equation_square.symm

end Mettapedia.OSLF.Binding.RhoEquationEventComparison
