import Mettapedia.OSLF.Syntax.SecondOrderVariableAbstraction
import Mettapedia.OSLF.Syntax.SecondOrderAuthoredEquationPresentation

/-!
# Equation boundaries for variable abstraction

Ordinary variables and fresh nullary metavariables are equivalent in raw
syntax. Contextual equation instantiation follows that equivalence in the
authored collapsing-schema example. Empty equations retain the distinction
between a variable and a constant. Binder controls keep the scope and
metavariable argument positions explicit.
-/

set_option autoImplicit false

namespace Mettapedia.OSLF.Binding.SecondOrderVariableAbstraction.Controls

open Mettapedia.OSLF.Binding
open Mettapedia.OSLF.Binding.SecondOrderContext

variable {S : Signature}

/-- Observe whether the outermost term constructor is an ordinary variable. -/
def rootVariable {Γ : Ctx S} {s : S.Srt} : Term S Γ s → Bool
  | .var _ => true
  | .op _ _ => false

/-- Substituting into a closed term cannot produce an outermost variable. -/
theorem rootVariable_bind_closed {Γ Δ : Ctx S} (closed : Γ = [])
    (sigma : Sub S Γ Δ) {s : S.Srt} (t : Term S Γ s) :
    rootVariable (bind sigma t) = false := by
  subst Γ
  cases t with
  | var v => nomatch v
  | op _ _ => rfl

/-- The equation closure preserves this observation whenever all authored
equation contexts are empty. Closure beneath operators does not change it. -/
theorem rootVariable_eqClosure
    (E : List (EqAxiom S [])) (closed : ∀ i : Fin E.length, (E.get i).ctx = []) :
    ∀ {Γ : Ctx S} {s : S.Srt} {left right : Term S Γ s},
      EqClosure E left right → rootVariable left = rootVariable right
  | _, _, _, _, .ax i body ambient env => by
      simp only [ContextualAssignment.instantiate_noMetas (S := S)]
      exact (rootVariable_bind_closed (closed i) env
        (instantiate (M := []) (fun k => Fin.elim0 k) (E.get i).lhs)).trans
        (rootVariable_bind_closed (closed i) env
          (instantiate (M := []) (fun k => Fin.elim0 k) (E.get i).rhs)).symm
  | _, _, _, _, .refl _ => rfl
  | _, _, _, _, .symm h => (rootVariable_eqClosure E closed h).symm
  | _, _, _, _, .trans h h' =>
      (rootVariable_eqClosure E closed h).trans (rootVariable_eqClosure E closed h')
  | _, _, _, _, .cong _ _ => rfl

/-- One sort and one nullary base constant. -/
def signature : Signature where
  Srt := Unit
  Op := fun _ => Unit
  arity := fun _ => []

abbrev schemaMetas : List (MetaArity signature) := [([], ())]
abbrev noMetas : List (MetaArity signature) := []
abbrev freshMetas : List (MetaArity signature) := headMetas () noMetas

def constant {Γ : Ctx signature} : Term signature Γ () := .op () .nil

/-- The authored equation identifies every admitted closed instance of P()
with the constant. Its ordinary-variable context is empty. -/
def closedEquation : EqAxiom signature schemaMetas where
  ctx := []
  sort := ()
  lhs := metaVar (S := signature) (M := schemaMetas) ⟨0, by decide⟩
  rhs := embed (S := signature) (M := schemaMetas) constant

abbrev equations : List (EqAxiom signature schemaMetas) := [closedEquation]
abbrev oldObject : Object signature := ⟨noMetas⟩
abbrev freshObject : Object signature := ⟨freshMetas⟩
abbrev oldEquations := equations.map (liftEquation oldObject)
abbrev freshEquations := equations.map (liftEquation freshObject)

def oldConstant {Γ : Ctx signature} : Term (withMetas signature noMetas) Γ () :=
  embed (S := signature) (M := noMetas) constant

def freshConstant {Γ : Ctx signature} : Term (withMetas signature freshMetas) Γ () :=
  embed (S := signature) (M := freshMetas) constant

def ordinaryVariable : Term (withMetas signature noMetas) [()] () := .var .zero
def freshVariable : Term (withMetas signature freshMetas) [] () :=
  fresh (S := signature) (M := noMetas) () []

/-- The fresh declaration is a valid closed schema body, so its equation
with the constant is generated by the actual authored presentation. -/
theorem freshVariable_eq_constant : EqClosure freshEquations freshVariable freshConstant := by
  let body : (i : Fin schemaMetas.length) →
      Term (withMetas signature freshMetas) (schemaMetas.get i).1 (schemaMetas.get i).2 :=
    fun i => Fin.cases freshVariable (fun i => Fin.elim0 i) i
  let env : Sub (withMetas signature freshMetas) [] [] := fun _ v => nomatch v
  exact EqClosure.ax_closed freshEquations (⟨0, by decide⟩) body env

theorem oldEquations_closed (i : Fin oldEquations.length) : (oldEquations.get i).ctx = [] := by
  rcases i with ⟨n, h⟩
  have zero : n = 0 := by change n < 1 at h; omega
  subst n
  rfl

/-- The same authored schema admits the ordinary-variable instance. -/
theorem ordinaryVariable_eq_constant : EqClosure oldEquations ordinaryVariable oldConstant := by
  let body : ContextualAssignment (withMetas signature noMetas) schemaMetas [()] :=
    fun i => Fin.cases ordinaryVariable (fun i => Fin.elim0 i) i
  exact EqClosure.ax (E := oldEquations) ⟨0, by decide⟩ body
    (fun _ v => .var v) (fun _ v => nomatch v)

/-- Without an authored equation, the variable and constant remain distinct. -/
theorem ordinaryVariable_ne_constant_without_equations :
    ¬ EqClosure ([] : List (EqAxiom (withMetas signature noMetas) schemaMetas))
      ordinaryVariable oldConstant := by
  intro related
  have same := eqClosure_empty_eq related
  have observed := congrArg rootVariable same
  change true = false at observed
  cases observed

/-- The raw restoration sends the fresh generator to the ordinary variable. -/
theorem openHead_freshVariable :
    openHead (S := signature) (M := noMetas) freshVariable = ordinaryVariable := rfl

theorem openHead_freshConstant :
    openHead (S := signature) (M := noMetas) (Γ := []) freshConstant = oldConstant := rfl

/-- The discriminating equation is preserved by actual raw restoration. -/
theorem restoration_preserves_control_equation :
    EqClosure freshEquations freshVariable freshConstant ∧
      EqClosure oldEquations
        (openHead (S := signature) (M := noMetas) freshVariable)
        (openHead (S := signature) (M := noMetas) (Γ := []) freshConstant) :=
  ⟨freshVariable_eq_constant, ordinaryVariable_eq_constant⟩


namespace BinderExample

inductive Op where
  | lam
  | pair

def sig : Signature where
  Srt := Unit
  Op := fun _ => Op
  arity := fun op => match op with
    | .lam => [([()], ())]
    | .pair => [([], ()), ([], ())]

abbrev metas : List (MetaArity sig) := [([()], ())]
abbrev ambient : Ctx sig := [(), ()]

/-- A local lambda variable and an ambient variable remain distinct. The old
metavariable explicitly receives the first ambient variable as its argument. -/
def original : Term (withMetas sig metas) ambient () :=
  .op (.inl .lam) (.cons
    (.op (.inl .pair) (.cons (.var .zero)
      (.cons (.op (.inr (.mk ⟨0, by decide⟩)) (.cons (.var (.succ .zero)) .nil)) .nil))) .nil)

/-- The old declaration shifts past both fresh declarations; the ambient
variable becomes the second fresh declaration, while the local variable stays bound. -/
def expected : Term (withMetas sig (extendedMetas ambient metas)) [] () := by
  apply Term.op (Sum.inl Op.lam)
  apply Args.cons
  · apply Term.op (Sum.inl Op.pair)
    apply Args.cons
    · exact .var .zero
    · apply Args.cons
      · apply Term.op (Sum.inr (MetaOp.mk (S := sig)
          (M := extendedMetas ambient metas) ⟨2, by decide⟩))
        exact Args.cons (bs := [])
          (Term.op (Sum.inr (MetaOp.mk (S := sig)
            (M := extendedMetas ambient metas) ⟨1, by decide⟩)) .nil) .nil
      · exact .nil
  · exact .nil

/-- An independently written binder-local expected result agrees with the
actual abstraction computation. -/
theorem binder_local_abstraction :
    abstractVars (S := sig) (M := metas) original = expected := rfl

/-- Restoring this explicit result recovers the old contextual metavariable
application and both kinds of variable positions. -/
theorem binder_local_restoration :
    restoreVars (S := sig) (M := metas) (Γ := ambient) expected = original := by
  rw [← binder_local_abstraction]
  exact restoreVars_abstractVars original

/-- Equal-sort ambient variables are not merged by abstraction. -/
theorem same_sort_variables_distinct :
    abstractVars (S := sig) (M := metas) (Γ := ambient) (.var .zero : Term (withMetas sig metas) ambient ()) ≠
      abstractVars (S := sig) (M := metas) (Γ := ambient)
        (.var (.succ .zero) : Term (withMetas sig metas) ambient ()) := by
  intro same
  have originalSame := (variablesEquiv (S := sig) ambient metas ()).injective same
  cases originalSame

end BinderExample

end Mettapedia.OSLF.Binding.SecondOrderVariableAbstraction.Controls
