import Mettapedia.GSLT.Core.InferenceControl
import Mettapedia.Languages.MeTTa.PrimeNeedExecutionMachine

/-!
# Inference control for the Prime Need machine

This module instantiates occurrence-preserving inference control on Prime's
rich Need reference machine.  Search nodes therefore retain branch-local
worlds, causal receipt DAGs, and exact work counters while a controller orders
their execution.

The controller is not allowed to manufacture machine successors.  A generated
work occurrence is proved to carry an ordinary `PrimeNeedReference.Steps`
derivation whose length is exactly its successor-index trace length.  The
existing transition-counter theorem then turns that trace length into an exact
semantic cost.

The final section records the smaller receipt-erased realization boundary.
Rich and erased machines expose the same immediate answers and successor
occurrences.  This is not a claim that a C executor is already verified.
-/

namespace Mettapedia.Languages.MeTTa.PrimeNeedInferenceControl

open Mettapedia.GSLT.Core.BranchingTemporal
open Mettapedia.GSLT.Core.InferenceControl

namespace Reference

open Mettapedia.Languages.MeTTa.PrimeNeedReference

variable {Origin Local Resume Rule Value StableFault RetryableFault Effect :
  Type*}

/-- Prime's rich machine as the semantic branching authority for inference
control. -/
def branchingSystem
    (spec : Spec Origin Local Resume Rule Value StableFault RetryableFault Effect) :
    BranchingSystem
      (Machine Origin Local Resume Rule Value StableFault RetryableFault Effect)
      (Produced Value StableFault RetryableFault) where
  emit := haltedOutcome
  successors := step spec

/-- Add exact successor-index traces without erasing worlds or receipts. -/
def occurrenceSystem
    (spec : Spec Origin Local Resume Rule Value StableFault RetryableFault Effect) :
    BranchingSystem
      (WorkOccurrence
        (Machine Origin Local Resume Rule Value StableFault RetryableFault Effect))
      (Produced Value StableFault RetryableFault × List Nat) :=
  WorkOccurrence.lift (branchingSystem spec)

private theorem getElem?_eq_some_of_mem_zipIdx {State : Type*}
    {values : List State} {value : State} {index : Nat}
    (member : (value, index) ∈ values.zipIdx) :
    values[index]? = some value := by
  have located := List.exists_mem_zipIdx'.mp
    (show ∃ entry ∈ values.zipIdx, entry = (value, index) from
      ⟨_, member, rfl⟩)
  obtain ⟨foundIndex, foundBound, pairEquality⟩ := located
  have indexEquality : foundIndex = index :=
    (Prod.ext_iff.mp pairEquality).2
  subst indexEquality
  rw [List.getElem?_eq_getElem foundBound]
  exact congrArg some (Prod.ext_iff.mp pairEquality).1

/-- Every occurrence generated by the generic controller frontier denotes an
exact Prime execution path. -/
theorem generated_has_steps
    (spec : Spec Origin Local Resume Rule Value StableFault RetryableFault Effect)
    {initial :
      Machine Origin Local Resume Rule Value StableFault RetryableFault Effect}
    {occurrence : WorkOccurrence
      (Machine Origin Local Resume Rule Value StableFault RetryableFault Effect)}
    (generated : Generated (occurrenceSystem spec)
      [WorkOccurrence.root initial] occurrence) :
    Steps spec occurrence.trace.length initial occurrence.state := by
  induction generated with
  | root member =>
      simp only [List.mem_singleton] at member
      rw [member]
      exact Steps.refl initial
  | @successor parent child parentGenerated childMember inductionHypothesis =>
      change child ∈
        ((step spec parent.state).zipIdx.map fun (state, edge) =>
          (⟨state, parent.trace ++ [edge]⟩ : WorkOccurrence _)) at childMember
      rcases List.mem_map.mp childMember with
        ⟨⟨next, edge⟩, edgeMember, childEquality⟩
      subst child
      have edgeLookup : (step spec parent.state)[edge]? = some next :=
        getElem?_eq_some_of_mem_zipIdx edgeMember
      have finalStep : Steps spec 1 parent.state next :=
        Steps.cons ⟨edge, edgeLookup⟩ (Steps.refl next)
      have composed := Steps.trans spec inductionHypothesis finalStep
      simpa using composed

/-- The occurrence trace is also an exact semantic transition cost. -/
theorem generated_transition_clock
    (spec : Spec Origin Local Resume Rule Value StableFault RetryableFault Effect)
    {initial :
      Machine Origin Local Resume Rule Value StableFault RetryableFault Effect}
    {occurrence : WorkOccurrence
      (Machine Origin Local Resume Rule Value StableFault RetryableFault Effect)}
    (generated : Generated (occurrenceSystem spec)
      [WorkOccurrence.root initial] occurrence) :
    occurrence.state.work.transitions =
      initial.work.transitions + occurrence.trace.length :=
  Steps.transitions_eq spec (generated_has_steps spec generated)

/-- A controlled Prime answer retains a replayable rich-machine path.  The
path includes the causal receipt world and work account at its endpoint. -/
theorem controlled_emission_has_steps
    (spec : Spec Origin Local Resume Rule Value StableFault RetryableFault Effect)
    {Memory : Type*}
    (controller : Controller
      (WorkOccurrence
        (Machine Origin Local Resume Rule Value StableFault RetryableFault Effect))
      (Produced Value StableFault RetryableFault × List Nat) Memory)
    (initial :
      Machine Origin Local Resume Rule Value StableFault RetryableFault Effect)
    (fuel : Nat)
    {event : Emission
      (WorkOccurrence
        (Machine Origin Local Resume Rule Value StableFault RetryableFault Effect))
      (Produced Value StableFault RetryableFault × List Nat)}
    (member : event ∈
      (Mettapedia.GSLT.Core.InferenceControl.Snapshot.run
        (occurrenceSystem spec) controller fuel
        (Mettapedia.GSLT.Core.InferenceControl.Snapshot.initial controller
          [WorkOccurrence.root initial])).search.events) :
    Steps spec event.origin.trace.length initial event.origin.state ∧
      haltedOutcome event.origin.state = some event.value.1 ∧
      event.value.2 = event.origin.trace := by
  have runSound := Mettapedia.GSLT.Core.InferenceControl.Snapshot.sound_run
    (occurrenceSystem spec) controller
    (roots := [WorkOccurrence.root initial])
    (snapshot := Mettapedia.GSLT.Core.InferenceControl.Snapshot.initial controller
      [WorkOccurrence.root initial])
    (initial_sound (occurrenceSystem spec) [WorkOccurrence.root initial]) fuel
  have eventValid := runSound.2 event member
  have path := generated_has_steps spec eventValid.1
  have emitted := eventValid.2
  change (haltedOutcome event.origin.state).map
    (fun answer => (answer, event.origin.trace)) = some event.value at emitted
  cases observed : haltedOutcome event.origin.state with
  | none =>
      rw [observed] at emitted
      contradiction
  | some answer =>
      rw [observed] at emitted
      have valueEquality : event.value = (answer, event.origin.trace) :=
        (Option.some.inj emitted).symm
      exact ⟨path, by simp [valueEquality],
        by simp [valueEquality]⟩

end Reference

namespace Erasure

open Mettapedia.Languages.MeTTa.PrimeNeedReference
open Mettapedia.Languages.MeTTa.PrimeNeedExecution

variable {Origin Local Resume Rule Value StableFault RetryableFault Effect :
  Type*}

/-- Receipt-erased Prime core machine as a branching realization. -/
def coreBranchingSystem
    (spec : Spec Origin Local Resume Rule Value StableFault RetryableFault Effect) :
    BranchingSystem
      (CoreMachine Origin Local Resume Rule Value StableFault RetryableFault Effect)
      (Produced Value StableFault RetryableFault) where
  emit := haltedOutcome
  successors := step spec

def coreOccurrenceSystem
    (spec : Spec Origin Local Resume Rule Value StableFault RetryableFault Effect) :
    BranchingSystem
      (WorkOccurrence
        (CoreMachine Origin Local Resume Rule Value StableFault RetryableFault Effect))
      (Produced Value StableFault RetryableFault × List Nat) :=
  WorkOccurrence.lift (coreBranchingSystem spec)

/-- Erase receipts from a work occurrence without erasing its transition
identity. -/
def eraseOccurrence
    (occurrence : WorkOccurrence
      (Machine Origin Local Resume Rule Value StableFault RetryableFault Effect)) :
    WorkOccurrence
      (CoreMachine Origin Local Resume Rule Value StableFault RetryableFault Effect) :=
  ⟨eraseMachine occurrence.state, occurrence.trace⟩

@[simp] theorem eraseOccurrence_trace
    (occurrence : WorkOccurrence
      (Machine Origin Local Resume Rule Value StableFault RetryableFault Effect)) :
    (eraseOccurrence occurrence).trace = occurrence.trace :=
  rfl

/-- Receipt erasure preserves the immediate answer observation, including the
occurrence trace attached to it. -/
theorem occurrence_emit_erases
    (spec : Spec Origin Local Resume Rule Value StableFault RetryableFault Effect)
    (occurrence : WorkOccurrence
      (Machine Origin Local Resume Rule Value StableFault RetryableFault Effect)) :
    (Reference.occurrenceSystem spec).emit occurrence =
      (coreOccurrenceSystem spec).emit (eraseOccurrence occurrence) := by
  simp [Reference.occurrenceSystem, Reference.branchingSystem,
    coreOccurrenceSystem, coreBranchingSystem, WorkOccurrence.lift,
    eraseOccurrence]

/-- Receipt erasure preserves the complete ordered successor-occurrence list.
Thus it retains duplicate alternatives and their trace identities. -/
theorem occurrence_successors_erase
    (spec : Spec Origin Local Resume Rule Value StableFault RetryableFault Effect)
    (occurrence : WorkOccurrence
      (Machine Origin Local Resume Rule Value StableFault RetryableFault Effect)) :
    ((Reference.occurrenceSystem spec).successors occurrence).map
        eraseOccurrence =
      (coreOccurrenceSystem spec).successors (eraseOccurrence occurrence) := by
  simp only [Reference.occurrenceSystem, Reference.branchingSystem,
    coreOccurrenceSystem, coreBranchingSystem, WorkOccurrence.lift,
    eraseOccurrence, List.map_map]
  rw [← step_commutes spec occurrence.state, List.zipIdx_map]
  rw [List.map_map]
  apply List.map_congr_left
  intro entry _
  rcases entry with ⟨state, index⟩
  rfl

end Erasure

#print axioms Reference.generated_has_steps
#print axioms Reference.generated_transition_clock
#print axioms Reference.controlled_emission_has_steps
#print axioms Erasure.occurrence_emit_erases
#print axioms Erasure.occurrence_successors_erase

end Mettapedia.Languages.MeTTa.PrimeNeedInferenceControl
