import Mettapedia.Logic.HostingStyles.Intuitionistic
import Mettapedia.Logic.HostingStyles.JudgmentsAsTypes

/-!
# An encoding in which the framework computes proofs

The rules-as-constants encoding keeps every derivation apart
(`RuleSignature.Finitary.encodingMap_hosting`).  That is a property of the
encoding and not of the framework.  The same framework admits another
encoding of the implicational Hilbert calculus, the one customary in the
lambda-Pi calculus modulo: implication is read as the framework's own
function type, so a proof of `φ ➝ ψ` is a function, modus ponens is
application, and the two axioms are the combinators

  `K = λ x y. x`     `S = λ x y z. x z (y z)`.

In Dedukti this reading is declared by the rewrite rule
`Prf (imp a b) ↪ Prf a → Prf b` on types; here the translation of formulas to
types (`formulaType`) is that rule applied throughout.  No constant is
needed: the signature is empty.

Under this encoding the framework's conversion *computes* derivations.  A
derivation that uses `K` to discard a subderivation is convertible to the
derivation without it (`computingTerm_discard`).  So:

* the two derivations of `φ ➝ φ` are identified (`computing_identifies`),
  and the encoding is not hosting (`computingMap_not_hosting`);
* there are derivations of every size `5 + 8 n` that are all identified with
  the one of size `5` (`discardTower_conv`, `size_discardTower`): the number
  of steps a derivation takes is visible natively and invisible up to the
  framework's conversion.

The calculus here is the fragment of the worked logic generated by `K`, `S`
and modus ponens (`minimalSignature`), which is minimal implicational logic.
The other axioms of the worked logic conclude formulas whose translated type
may be a function type; reading them as constants would need constants of
function type results, which the signatures of this framework do not have.
-/

set_option autoImplicit false

namespace Mettapedia.Logic.HostingStyles

open LO
open Mettapedia.TypeTheory
open Mettapedia.TypeTheory.IndexedPolynomial
open Mettapedia.GSLT
open Framework

/-! ## Minimal implicational logic -/

/-- The rule instances of the implicational Hilbert calculus. -/
inductive MinRule : IntFormula → Type where
  | implyK (φ ψ : IntFormula) : MinRule (φ ➝ ψ ➝ φ)
  | implyS (φ ψ χ : IntFormula) : MinRule ((φ ➝ ψ ➝ χ) ➝ (φ ➝ ψ) ➝ φ ➝ χ)
  | mdp (φ ψ : IntFormula) : MinRule ψ

/-- The premises of a rule instance. -/
def MinRule.Position : {φ : IntFormula} → MinRule φ → Type
  | _, .implyK _ _ => Empty
  | _, .implyS _ _ _ => Empty
  | _, .mdp _ _ => Bool

/-- The premises of modus ponens are the implication and its antecedent. -/
def MinRule.premise : {φ : IntFormula} → (rule : MinRule φ) → rule.Position → IntFormula
  | _, .implyK _ _, position => nomatch position
  | _, .implyS _ _ _, position => nomatch position
  | _, .mdp φ ψ, position => cond position φ (φ ➝ ψ)

/-- **Minimal implicational logic**, as a rule signature. -/
def minimalSignature : RuleSignature IntFormula where
  Shape := fun _ φ => MinRule φ
  Position := fun rule => rule.Position
  next := fun rule position => rule.premise position

/-- Every rule has finitely many premises. -/
def minimalFinitary : minimalSignature.Finitary where
  arity := fun rule => match rule with
    | .implyK _ _ => 0
    | .implyS _ _ _ => 0
    | .mdp _ _ => 2
  position := fun rule => match rule with
    | .implyK _ _ => finZeroEquiv
    | .implyS _ _ _ => finZeroEquiv
    | .mdp _ _ => finTwoEquiv

/-- The derivations of minimal implicational logic. -/
abbrev MinProof (φ : IntFormula) : Type := minimalSignature.Proof φ

/-- The axiom `K`. -/
def minK (φ ψ : IntFormula) : MinProof (φ ➝ ψ ➝ φ) :=
  minimalSignature.node (.implyK φ ψ) fun position => nomatch position

/-- The axiom `S`. -/
def minS (φ ψ χ : IntFormula) : MinProof ((φ ➝ ψ ➝ χ) ➝ (φ ➝ ψ) ➝ φ ➝ χ) :=
  minimalSignature.node (.implyS φ ψ χ) fun position => nomatch position

/-- Modus ponens. -/
def minMdp {φ ψ : IntFormula} (major : MinProof (φ ➝ ψ)) (minor : MinProof φ) : MinProof ψ :=
  minimalSignature.node (.mdp φ ψ) fun position =>
    match position with
    | false => major
    | true => minor

/-- Every derivation of the fragment is a derivation of the worked logic. -/
noncomputable def MinProof.toInt {φ : IntFormula} (proof : MinProof φ) : IntProof φ :=
  Fix.fold minimalSignature (carrier := fun _ φ => IntProof φ)
    (fun _ conclusion layer =>
      match conclusion, layer with
      | _, ⟨.implyK φ ψ, _⟩ => axiomProof (.implyK φ ψ)
      | _, ⟨.implyS φ ψ χ, _⟩ => axiomProof (.implyS φ ψ χ)
      | _, ⟨.mdp _ _, children⟩ => mdpProof (children false) (children true))
    PUnit.unit φ proof

theorem size_minMdp {φ ψ : IntFormula} (major : MinProof (φ ➝ ψ)) (minor : MinProof φ) :
    RuleSignature.size minimalFinitary (minMdp major minor) =
      1 + (RuleSignature.size minimalFinitary major +
        (RuleSignature.size minimalFinitary minor + 0)) := rfl

/-- The derivation of `φ ➝ φ` from `S` and `K`. -/
def minIdentity (φ : IntFormula) : MinProof (φ ➝ φ) :=
  minMdp (minMdp (minS φ (φ ➝ φ) φ) (minK φ (φ ➝ φ))) (minK φ φ)

theorem size_minIdentity (φ : IntFormula) :
    RuleSignature.size minimalFinitary (minIdentity φ) = 5 := by
  simp only [minIdentity, size_minMdp]
  rfl

/-- Use `K` to discard a second derivation. -/
def discard {φ ψ : IntFormula} (kept : MinProof φ) (discarded : MinProof ψ) : MinProof φ :=
  minMdp (minMdp (minK φ ψ) kept) discarded

theorem size_discard {φ ψ : IntFormula} (kept : MinProof φ) (discarded : MinProof ψ) :
    RuleSignature.size minimalFinitary (discard kept discarded) =
      3 + RuleSignature.size minimalFinitary kept +
        RuleSignature.size minimalFinitary discarded := by
  simp only [discard, size_minMdp]
  have axiomSize : RuleSignature.size minimalFinitary (minK φ ψ) = 1 := rfl
  omega

/-- A derivation of `φ ➝ φ` that discards a copy of the short one `count`
times. -/
def discardTower (φ : IntFormula) : Nat → MinProof (φ ➝ φ)
  | 0 => minIdentity φ
  | count + 1 => discard (discardTower φ count) (minIdentity φ)

/-- **The size of the derivation grows with the number of discards.** -/
theorem size_discardTower (φ : IntFormula) (count : Nat) :
    RuleSignature.size minimalFinitary (discardTower φ count) = 5 + 8 * count := by
  induction count with
  | zero => exact size_minIdentity φ
  | succ count ih =>
      rw [discardTower, size_discard, ih, size_minIdentity]
      omega

/-! ## Implication as the framework's function type -/

/-- **The type of a formula**: an implication is a function type, any other
formula is a base type. -/
def formulaType : IntFormula → Ty IntFormula
  | .imp φ ψ => .arrow (formulaType φ) (formulaType ψ)
  | φ => .base φ

@[simp] theorem formulaType_imp (φ ψ : IntFormula) :
    formulaType (φ ➝ ψ) = .arrow (formulaType φ) (formulaType ψ) := rfl

/-- The signature of this encoding has no constant. -/
def emptySignature : Signature IntFormula where
  Const := Empty
  arity := fun constant => nomatch constant
  argument := fun constant => nomatch constant
  result := fun constant => nomatch constant

variable {Hole : Type} {holes : Hole → Ty IntFormula}

/-- The combinator `K`. -/
def combinatorK (first second : Ty IntFormula) :
    Tm emptySignature holes [] (.arrow first (.arrow second first)) :=
  .lam (.lam (.var (.succ .zero)))

/-- The combinator `S`. -/
def combinatorS (first second third : Ty IntFormula) :
    Tm emptySignature holes []
      (.arrow (.arrow first (.arrow second third))
        (.arrow (.arrow first second) (.arrow first third))) :=
  .lam (.lam (.lam (.app (.app (.var (.succ (.succ .zero))) (.var .zero))
    (.app (.var (.succ .zero)) (.var .zero)))))

/-- The terms of the framework carry an algebra of minimal implicational
logic: the axioms are combinators and modus ponens is application. -/
def computingAlgebra (holes : Hole → Ty IntFormula) :
    minimalSignature.Algebra (fun _ φ => Tm emptySignature holes [] (formulaType φ)) where
  act := fun _ conclusion layer =>
    match conclusion, layer with
    | _, ⟨.implyK φ ψ, _⟩ => combinatorK (formulaType φ) (formulaType ψ)
    | _, ⟨.implyS φ ψ χ, _⟩ => combinatorS (formulaType φ) (formulaType ψ) (formulaType χ)
    | _, ⟨.mdp _ _, children⟩ => .app (children false) (children true)

/-- **The computing encoding of a derivation.** -/
noncomputable def computingTerm {φ : IntFormula} (proof : MinProof φ) :
    Closed emptySignature (formulaType φ) :=
  Fix.fold minimalSignature (computingAlgebra noHoles).act PUnit.unit φ proof

/-- The computing encoding of a derived rule. -/
noncomputable def computingContext {arity : Type} {assumptions : arity → IntFormula}
    {φ : IntFormula} (context : minimalSignature.Open assumptions φ) :
    Tm emptySignature (fun index => formulaType (assumptions index)) [] (formulaType φ) :=
  Free.fold minimalSignature
    (fun _ _ hole => RuleSignature.HoleAt.elim
      (motive := fun φ => Tm emptySignature (fun index => formulaType (assumptions index)) []
        (formulaType φ))
      (fun index => Tm.hole index) hole)
    (computingAlgebra _) PUnit.unit φ context

theorem computingTerm_minMdp {φ ψ : IntFormula} (major : MinProof (φ ➝ ψ)) (minor : MinProof φ) :
    computingTerm (minMdp major minor) = .app (computingTerm major) (computingTerm minor) := rfl

theorem computingTerm_minK (φ ψ : IntFormula) :
    computingTerm (minK φ ψ) = combinatorK (formulaType φ) (formulaType ψ) := rfl

/-- The encoding commutes with plugging derivations into assumptions. -/
theorem computingTerm_fill {arity : Type} {assumptions : arity → IntFormula} {φ : IntFormula}
    (context : minimalSignature.Open assumptions φ)
    (filling : (index : arity) → MinProof (assumptions index)) :
    computingTerm (minimalSignature.fill context filling) =
      (computingContext context).fill fun index => computingTerm (filling index) := by
  induction context using RuleSignature.Open.induction with
  | assume index => exact (Tm.rename_closed _ _).symm
  | node rule children ih =>
      cases rule with
      | implyK φ ψ => rfl
      | implyS φ ψ χ => rfl
      | mdp φ =>
          change Tm.app (computingTerm (minimalSignature.fill (children false) filling))
              (computingTerm (minimalSignature.fill (children true) filling)) =
            Tm.app ((computingContext (children false)).fill _)
              ((computingContext (children true)).fill _)
          exact congrArg₂ Tm.app (ih false) (ih true)

/-- **The computing encoding, as a map of theories.** -/
noncomputable def computingMap :
    ContextMap (minimalSignature.proofTheory (RuleSignature.ProofCongruence.identity _))
      (frameworkTheory emptySignature) where
  interface := formulaType
  term := fun proof => computingTerm proof
  context := fun context => computingContext context
  term_resp := fun same => by
    have equal := same
    subst equal
    exact .refl _
  equivariant := fun context filling => Conv.of_eq (computingTerm_fill context filling)

/-! ## The framework computes -/

/-- **A discarded derivation disappears up to conversion.** -/
theorem computingTerm_discard {φ ψ : IntFormula} (kept : MinProof φ) (discarded : MinProof ψ) :
    Conv (computingTerm (discard kept discarded)) (computingTerm kept) := by
  have first : Step
      (Tm.app (Tm.app (combinatorK (holes := noHoles) (formulaType φ) (formulaType ψ))
        (computingTerm kept)) (computingTerm discarded))
      (Tm.app (Tm.lam ((computingTerm kept).rename (Renaming.weaken [] (formulaType ψ))))
        (computingTerm discarded)) :=
    .appLeft (.beta _ _)
  have second : Step
      (Tm.app (Tm.lam ((computingTerm kept).rename (Renaming.weaken [] (formulaType ψ))))
        (computingTerm discarded))
      (((computingTerm kept).rename (Renaming.weaken [] (formulaType ψ))).inst
        (computingTerm discarded)) :=
    .beta _ _
  rw [Tm.inst_weaken] at second
  exact .trans _ _ _ (.rel _ _ first) (.rel _ _ second)

/-- **Derivations of every size, all identified**: the tower of discards is
convertible to the short derivation. -/
theorem discardTower_conv (φ : IntFormula) (count : Nat) :
    Conv (computingTerm (discardTower φ count)) (computingTerm (minIdentity φ)) := by
  induction count with
  | zero => exact .refl _
  | succ count ih => exact .trans _ _ _ (computingTerm_discard _ _) ih

/-- The two derivations are different. -/
theorem discardTower_ne (φ : IntFormula) (count : Nat) :
    discardTower φ (count + 1) ≠ minIdentity φ := by
  intro same
  have sizes := congrArg (RuleSignature.size minimalFinitary) same
  rw [size_discardTower, size_minIdentity] at sizes
  omega

/-- **The computing encoding identifies two different derivations.** -/
theorem computing_identifies (φ : IntFormula) :
    discardTower φ 1 ≠ minIdentity φ ∧
      Conv (computingTerm (discardTower φ 1)) (computingTerm (minIdentity φ)) :=
  ⟨discardTower_ne φ 0, discardTower_conv φ 1⟩

/-- **The computing encoding is not hosting.** -/
theorem computingMap_not_hosting : ¬ computingMap.Hosting :=
  ContextMap.not_hosting_of_identifies computingMap (discardTower_ne (.atom 0) 0)
    (discardTower_conv (.atom 0) 1)

/-- The rules-as-constants encoding of the same calculus is hosting. -/
theorem minimal_encodingMap_hosting : minimalFinitary.encodingMap.Hosting :=
  minimalFinitary.encodingMap_hosting

#print axioms computingTerm_discard
#print axioms discardTower_conv
#print axioms size_discardTower
#print axioms computingMap_not_hosting

end Mettapedia.Logic.HostingStyles
