/-
# Soup presentations: structural congruence is component-bag equality

Two developments in this tree prove the same theorem about different carriers.
The rho calculus proves that its structural congruence coincides with equality
of parallel-component bags; the rho combinators prove it again, for their own
term type, with their own `componentList` and their own congruence. The proofs
are the same proof.

This file states it once. A `Soup` is a carrier with a parallel composition, a
decomposition of terms into components, and one genuine assumption — that every
term is congruent to the parallel composition of its own components. From those,
**both directions** of the soup theorem are derived:

```
    Cong p q  ↔  componentList p = componentList q  (as bags)
```

Soundness is induction on the congruence; completeness routes through the
normal form. Neither direction is assumed, which is what keeps the abstraction
from being packaging: a carrier has to earn `decomposes`, and `decomposes` alone
does not give either direction away.

The generic statement is what an arbitrary presentation needs. A presentation
whose parallel composition satisfies these three laws gets the normal form, the
rearrangement principle, and everything built on them — including the bag
reactive-system reading, whose own load-bearing lemma is already generic in its
carrier.
-/
import Mathlib.Data.Multiset.Basic
import Mathlib.Data.Multiset.AddSub

set_option autoImplicit false

namespace Mettapedia.GSLT.SoupPresentation

universe u

/-- Right-nested parallel composition of a list of components. -/
def ofList {T : Type u} (unit : T) (comp : T → T → T) : List T → T
  | [] => unit
  | atom :: rest => comp atom (ofList unit comp rest)

/-- The structural congruence generated by the commutative-monoid laws on a
parallel composition, closed under that composition and nothing else. -/
inductive Cong {T : Type u} (unit : T) (comp : T → T → T) : T → T → Prop
  | refl (p : T) : Cong unit comp p p
  | symm {p q : T} : Cong unit comp p q → Cong unit comp q p
  | trans {p q r : T} : Cong unit comp p q → Cong unit comp q r → Cong unit comp p r
  | compUnit (p : T) : Cong unit comp (comp p unit) p
  | compComm (p q : T) : Cong unit comp (comp p q) (comp q p)
  | compAssoc (p q r : T) :
      Cong unit comp (comp (comp p q) r) (comp p (comp q r))
  | compLeft (q : T) {p p' : T} :
      Cong unit comp p p' → Cong unit comp (comp p q) (comp p' q)
  | compRight (p : T) {q q' : T} :
      Cong unit comp q q' → Cong unit comp (comp p q) (comp p q')

/-- A soup presentation: a carrier whose terms decompose into components under a
parallel composition, and are recovered by recomposing them. -/
structure Soup where
  /-- The carrier. -/
  Term : Type u
  /-- The empty soup. -/
  unit : Term
  /-- Parallel composition. -/
  comp : Term → Term → Term
  /-- The components of a term. -/
  componentList : Term → List Term
  componentList_unit : componentList unit = []
  componentList_comp :
    ∀ p q, componentList (comp p q) = componentList p ++ componentList q
  /-- The one substantive assumption: a term is its own components, recomposed. -/
  decomposes : ∀ t, Cong unit comp t (ofList unit comp (componentList t))

namespace Soup

variable (S : Soup)

/-! ## Soundness -/

/-- Congruent terms have the same components up to order. -/
theorem componentList_perm_of_cong {p q : S.Term} (h : Cong S.unit S.comp p q) :
    (S.componentList p).Perm (S.componentList q) := by
  induction h with
  | refl => exact List.Perm.refl _
  | symm _ ih => exact ih.symm
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | compUnit p =>
      simp only [S.componentList_comp, S.componentList_unit, List.append_nil]
      exact List.Perm.refl _
  | compComm p q => simp only [S.componentList_comp]; exact List.perm_append_comm
  | compAssoc p q r =>
      simp only [S.componentList_comp, List.append_assoc]
      exact List.Perm.refl _
  | compLeft q _ ih => simp only [S.componentList_comp]; exact ih.append_right _
  | compRight p _ ih => simp only [S.componentList_comp]; exact ih.append_left _

/-! ## Completeness -/

/-- Recomposing a concatenation is composing the recompositions. -/
theorem ofList_append (l₁ l₂ : List S.Term) :
    Cong S.unit S.comp (ofList S.unit S.comp (l₁ ++ l₂))
      (S.comp (ofList S.unit S.comp l₁) (ofList S.unit S.comp l₂)) := by
  induction l₁ with
  | nil =>
      exact Cong.symm (Cong.trans (Cong.compComm _ _) (Cong.compUnit _))
  | cons atom rest ih =>
      exact Cong.trans (Cong.compRight atom ih) (Cong.symm (Cong.compAssoc _ _ _))

/-- Recomposition does not see the order of the components. -/
theorem ofList_perm {l₁ l₂ : List S.Term} (h : l₁.Perm l₂) :
    Cong S.unit S.comp (ofList S.unit S.comp l₁) (ofList S.unit S.comp l₂) := by
  induction h with
  | nil => exact Cong.refl _
  | cons atom _ ih => exact Cong.compRight atom ih
  | swap x y l =>
      exact Cong.trans (Cong.symm (Cong.compAssoc _ _ _))
        (Cong.trans (Cong.compLeft _ (Cong.compComm _ _)) (Cong.compAssoc _ _ _))
  | trans _ _ ih₁ ih₂ => exact Cong.trans ih₁ ih₂

/-- **Completeness of the normal form.**  Terms whose components agree up to
order are congruent, so every rearrangement is one application of this. -/
theorem cong_of_perm {p q : S.Term}
    (h : (S.componentList p).Perm (S.componentList q)) : Cong S.unit S.comp p q :=
  Cong.trans (S.decomposes p)
    (Cong.trans (S.ofList_perm h) (Cong.symm (S.decomposes q)))

/-! ## The soup theorem -/

/-- The component bag of a term. -/
def components (t : S.Term) : Multiset S.Term := (S.componentList t : Multiset S.Term)

theorem components_unit : S.components S.unit = 0 := by
  simp only [components, S.componentList_unit]; rfl

theorem components_comp (p q : S.Term) :
    S.components (S.comp p q) = S.components p + S.components q := by
  simp only [components, S.componentList_comp]
  rfl

/-- **The soup theorem.**  Structural congruence is exactly equality of
component bags — proved once, for every carrier that decomposes. -/
theorem cong_iff_components (p q : S.Term) :
    Cong S.unit S.comp p q ↔ S.components p = S.components q :=
  ⟨fun h => Multiset.coe_eq_coe.mpr (S.componentList_perm_of_cong h),
    fun h => S.cong_of_perm (Multiset.coe_eq_coe.mp h)⟩

theorem cong_components {p q : S.Term} (h : Cong S.unit S.comp p q) :
    S.components p = S.components q := (S.cong_iff_components p q).mp h

theorem cong_of_components {p q : S.Term} (h : S.components p = S.components q) :
    Cong S.unit S.comp p q := (S.cong_iff_components p q).mpr h

/-- Congruence is decidable whenever the carrier's equality is: one bag
comparison, with no search. -/
def decidableCong [DecidableEq S.Term] (p q : S.Term) : Decidable (Cong S.unit S.comp p q) :=
  decidable_of_iff _ (S.cong_iff_components p q).symm

end Soup

end Mettapedia.GSLT.SoupPresentation
