import Mettapedia.Languages.LambdaCalculus.NamePassingContexts
import Mettapedia.Languages.ProcessCalculi.PolyadicPi.ProtocolContexts
import Mettapedia.Languages.ProcessCalculi.PolyadicPi.Bridges.NamePassingLambda

/-!
# Compositional interpretation of scoped clients as pi protocols

The source and target context grammars are independently authored. Plugging
commutes with the actual five-clause compiler, including stored expressions,
bound bodies, name reindexing and one-shot carriers. Target admission retains
a syntactic source context; it is not a namespace-only privacy assertion.
-/

set_option autoImplicit false

namespace Mettapedia.Languages.ProcessCalculi.PolyadicPi.Bridges.NamePassingContexts

open Mettapedia.OSLF.Binding
open Mettapedia.Languages.LambdaCalculus
open NamePassingLambda

abbrev SourceContext (Γ Δ : Ctx sig) := NamePassing.Context Srt.nm Γ Δ

def program {Γ : Ctx sig} (source : Expr Γ) : ProtocolContexts.Program Γ :=
  fun environment result => NamePassingLambda.compile source environment result

def translate {Γ : Ctx sig} : {Δ : Ctx sig} → SourceContext Γ Δ → ProtocolContexts.Context Γ Δ
  | _, .hole => .hole
  | _, .reindex names inner => .reindex names (translate inner)
  | _, .lam inner => .receive (translate inner)
  | _, .app inner argument => .call (translate inner) argument
  | _, .defValue inner body => .storedValue (translate inner) (program body)
  | _, .defBody value inner => .storedBody (program value) (translate inner)
  | _, .carrierValue name inner body => .carrierValue name (translate inner) (program body)
  | _, .carrierBody name value inner => .carrierBody name (program value) (translate inner)

theorem plug_agreement {Γ Δ : Ctx sig} (context : SourceContext Γ Δ) (source : Expr Γ) :
    ((translate context).plug (program source) : ProtocolContexts.Program Δ) =
      (program (context.plug source) : ProtocolContexts.Program Δ) := by
  induction context with
  | hole => rfl
  | reindex names _ ih =>
      funext Θ environment result
      simp only [translate, ProtocolContexts.Context.plug, ih, NamePassing.Context.plug,
        program, NamePassingLambda.compile_source_rename]
  | lam _ ih =>
      funext Θ environment result
      simp only [translate, ProtocolContexts.Context.plug, ih, NamePassing.Context.plug]
      rfl
  | app _ argument ih =>
      funext Θ environment result
      simp only [translate, ProtocolContexts.Context.plug, ih, NamePassing.Context.plug]
      rfl
  | defValue _ body ih =>
      funext Θ environment result
      simp only [translate, ProtocolContexts.Context.plug, ih, NamePassing.Context.plug]
      rfl
  | defBody value _ ih =>
      funext Θ environment result
      simp only [translate, ProtocolContexts.Context.plug, ih, NamePassing.Context.plug]
      rfl
  | carrierValue name _ body ih =>
      funext Θ environment result
      simp only [translate, ProtocolContexts.Context.plug, ih, NamePassing.Context.plug]
      rfl
  | carrierBody name value _ ih =>
      funext Θ environment result
      simp only [translate, ProtocolContexts.Context.plug, ih, NamePassing.Context.plug]
      rfl

@[simp] theorem translate_compose {Γ Δ Θ : Ctx sig} (outer : SourceContext Δ Θ)
    (inner : SourceContext Γ Δ) :
    translate (outer.compose inner) = (translate outer).compose (translate inner) := by
  induction outer <;> simp only [NamePassing.Context.compose, translate,
    ProtocolContexts.Context.compose, *]

/-- Admission is generated by the independently authored source syntax.
Its execution adequacy is proved in NamePassingObserverAdequacy. -/
def Admitted {Γ Δ : Ctx sig} (context : ProtocolContexts.Context Γ Δ) : Prop :=
  ∃ source : SourceContext Γ Δ, translate source = context

theorem translated_admitted {Γ Δ : Ctx sig} (context : SourceContext Γ Δ) :
    Admitted (translate context) := ⟨context, rfl⟩

theorem admitted_compose {Γ Δ Θ : Ctx sig} {outer : ProtocolContexts.Context Δ Θ}
    {inner : ProtocolContexts.Context Γ Δ} (outerAdmitted : Admitted outer)
    (innerAdmitted : Admitted inner) : Admitted (outer.compose inner) := by
  obtain ⟨outerSource, rfl⟩ := outerAdmitted
  obtain ⟨innerSource, rfl⟩ := innerAdmitted
  exact ⟨outerSource.compose innerSource, translate_compose outerSource innerSource⟩

end Mettapedia.Languages.ProcessCalculi.PolyadicPi.Bridges.NamePassingContexts
