import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryBoundarySideCell

open Mettapedia.GSLT.LanguageDef
open Mettapedia.Languages.ProcessCalculi.RhoCalculus

#check @Mettapedia.GSLT.LanguageDef.CostStaticAtomKeyCospan.exists_reifyWith_fvar
#check @Mettapedia.GSLT.LanguageDef.CostStaticAtomKeyCospan.reifyWith_bvar
#check @Mettapedia.GSLT.LanguageDef.CostStaticAtomKeyCospan.not_restoresTogether_reifyWith_fvar_bvar
#check @Mettapedia.GSLT.LanguageDef.CostStaticAtomKeyCospan.not_restoresTogether_reifyWith_bvar_fvar
#check @Mettapedia.GSLT.LanguageDef.CostStaticAtomKeyCospan.not_restoresTogether_transported_fvar_bvar
#check @Mettapedia.GSLT.LanguageDef.CostStaticAtomKeyCospan.not_restoresTogether_transported_bvar_fvar
#check @CostStaticRegionPlan.rigid_cases
#check @rho_planStop_boundarySide_rigid_rawStop
#check @rho_planStop_rigid_boundarySide_rawStop
#check @not_boundarySide_bvarPartner_sourcePatternLeafAligned
#check @not_bvarPartner_boundarySide_sourcePatternLeafAligned
#check @rho_planStop_boundarySide_bvarPartner_canonicalize_eq_bvar
#check @canonicalize_rhoParallel_singleton_bvar
#check @canonicalize_rhoQuoteDrop_bvar
#check @boundarySourceVariablePlanStops_sourcePatternLeafAligned_of_closeSmaller
#check @sourceVariableBoundaryPlanStops_sourcePatternLeafAligned_of_closeSmaller
#check @rhoPlanStopBoundarySide_sourceVariablePartner_sourceAligned
#check @rhoPlanStopSourceVariablePartner_boundarySide_sourceAligned

#print axioms Mettapedia.GSLT.LanguageDef.CostStaticAtomKeyCospan.exists_reifyWith_fvar
#print axioms Mettapedia.GSLT.LanguageDef.CostStaticAtomKeyCospan.reifyWith_bvar
#print axioms Mettapedia.GSLT.LanguageDef.CostStaticAtomKeyCospan.not_restoresTogether_reifyWith_fvar_bvar
#print axioms Mettapedia.GSLT.LanguageDef.CostStaticAtomKeyCospan.not_restoresTogether_reifyWith_bvar_fvar
#print axioms Mettapedia.GSLT.LanguageDef.CostStaticAtomKeyCospan.not_restoresTogether_transported_fvar_bvar
#print axioms Mettapedia.GSLT.LanguageDef.CostStaticAtomKeyCospan.not_restoresTogether_transported_bvar_fvar
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostStaticRegionPlan.rigid_cases
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rho_planStop_boundarySide_rigid_rawStop
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rho_planStop_rigid_boundarySide_rawStop
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.not_boundarySide_bvarPartner_sourcePatternLeafAligned
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.not_bvarPartner_boundarySide_sourcePatternLeafAligned
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rho_planStop_boundarySide_bvarPartner_canonicalize_eq_bvar
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.canonicalize_rhoParallel_singleton_bvar
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.canonicalize_rhoQuoteDrop_bvar
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.boundarySourceVariablePlanStops_sourcePatternLeafAligned_of_closeSmaller
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.sourceVariableBoundaryPlanStops_sourcePatternLeafAligned_of_closeSmaller
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rhoPlanStopBoundarySide_sourceVariablePartner_sourceAligned
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rhoPlanStopSourceVariablePartner_boundarySide_sourceAligned
