import Mettapedia.GSLT.LanguageDef.CostRestorationApexSymm
import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostKeyedFixedPointFalsifier

#print axioms Mettapedia.GSLT.LanguageDef.ReflectiveContextSupport.substituteAt_eq_of_liftStable_on_freeFvars
#print axioms Mettapedia.GSLT.LanguageDef.WellSorted.SupportedOpenAssignment.liftBVars_zero_eq_self_of_support_eq_nil
#print axioms Mettapedia.GSLT.LanguageDef.WellSorted.SupportedOpenAssignment.substituteAt_eq_of_free_support_eq_nil
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostKeyedFixedPointFalsifier.rhoDepthApexShiftingKey_not_typed
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostKeyedFixedPointFalsifier.rhoTypedDepthSensitiveAtom_lift_differs
