import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryCanonical
import Mettapedia.OSLF.MeTTaIL.ReflectiveCanonicalKeyedNormalForm
import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostKeyedFixedPointFalsifier

#print axioms Mettapedia.OSLF.MeTTaIL.PatternCode.sortPatternsBy_idempotent
#print axioms Mettapedia.OSLF.MeTTaIL.ReflectiveCanonical.canonicalizeByAt_parallel_singleton_not_across_quote_reset
#print axioms Mettapedia.GSLT.LanguageDef.CostStaticAtomEnvironment.reifyWith_targetReflectiveSupportSafeAt
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostCanonicalLaws.rho_no_collection_at_reflectiveNameSort
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostCanonicalLaws.rho_costStatic_quoteDrop_inner_typed
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostStaticRegionNode.canonicalizeReifiedTargetFrame_toCommon_supportSafe
#print axioms Mettapedia.OSLF.MeTTaIL.ReflectiveCanonical.canonicalizeByAt_parallelOrderAgnostic
#print axioms Mettapedia.OSLF.MeTTaIL.ReflectiveCanonical.ParallelOrderAgnostic.canonicalize_eq
#print axioms Mettapedia.OSLF.MeTTaIL.ReflectiveCanonical.canonicalize_canonicalizeByAt_unconditional
#print axioms Mettapedia.OSLF.MeTTaIL.ReflectiveCanonical.canonicalize_keyed_eq_of_canonicalize_eq
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostKeyedFixedPointFalsifier.keyedTies_output_parallelOrderAgnostic_plain
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostKeyedFixedPointFalsifier.rhoDepthApex_sameKeyDepth
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostKeyedFixedPointFalsifier.rhoDepthApex_unequalKeyDepths_no_commonApex
