import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryCrossColorRestoration

open Mettapedia.GSLT.LanguageDef
open Mettapedia.Languages.ProcessCalculi.RhoCalculus

#check @CostStaticRegionPlan.not_bvar_of_available_nil
#check @rhoCalc_label_eq_quote_of_category_name
#check @rho_costStaticCollectionTypingChoices_name_eq_nil
#check @rho_sourceSort_eq_name_of_ne_interacting
#check @rhoNameFibre_canonicalFrame_shape
#check @decodeCostStaticConstructor_color_disjoint
#check @rhoCrossColorNameFibre_framesRestoreTogether_of_restorationAligned
#check @RhoCollapsingCrossColorFramesRestoreTogetherInDomain
#check @rhoCollapsingCrossColorViewsRestorationAlignedInDomain_of_framesRestoreTogether
#check @rhoCollapsingCrossColorFramesRestoreTogetherInDomain_of_restorationAligned

#print axioms CostStaticRegionPlan.not_bvar_of_available_nil
#print axioms rhoNameFibre_canonicalFrame_shape
#print axioms decodeCostStaticConstructor_color_disjoint
#print axioms rhoCrossColorNameFibre_framesRestoreTogether_of_restorationAligned
#print axioms rhoCollapsingCrossColorViewsRestorationAlignedInDomain_of_framesRestoreTogether
#print axioms rhoCollapsingCrossColorFramesRestoreTogetherInDomain_of_restorationAligned
