import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryExposureBridge

open Mettapedia.Languages.ProcessCalculi.RhoCalculus
open Mettapedia.OSLF.MeTTaIL.ReflectiveCanonical

#check @eq_bvar_or_collapsingRoot_of_canonicalize_eq_bvar
#check @eq_fvar_or_collapsingRoot_of_canonicalize_eq_fvar
#check @Mettapedia.GSLT.LanguageDef.CostRegionTree.rootIsStatic_eq_false_of_fvar
#check @rho_normalize_pattern_of_bvar
#check @rho_normalize_pattern_of_fvar
#check @rho_bvar_lookup_of_tree
#check @rho_fvar_lookup_of_tree
#check @rho_collapsingLeafExposureBVarRoute_of_staticNormal
#check @rho_collapsingLeafExposureFVarRoute_of_sourceVariable
#check @RhoCollapsingLeafExposureAdmittedBVarRoute
#check @RhoCollapsingLeafExposureAdmittedFVarRoute
#check @RhoCollapsingLeafExposureAdmittedApplyRoute
#check @rho_collapsingLeafExposureInDomain_of_admittedLeafRoutes
#check @RhoCollapsingBVarLeafDichotomy
#check @RhoCollapsingFVarLeafDichotomy
#check @RhoCollapsingApplyLeafBoundary
#check @rho_collapsingLeafExposureAdmittedBVarRoute_of_dichotomy
#check @rho_collapsingLeafExposureAdmittedFVarRoute_of_dichotomy
#check @rho_collapsingLeafExposureAdmittedApplyRoute_of_boundary
#check @rho_collapsingLeafExposureInDomain_of_classifications

#print axioms eq_bvar_or_collapsingRoot_of_canonicalize_eq_bvar
#print axioms eq_fvar_or_collapsingRoot_of_canonicalize_eq_fvar
#print axioms Mettapedia.GSLT.LanguageDef.CostRegionTree.rootIsStatic_eq_false_of_fvar
#print axioms rho_normalize_pattern_of_bvar
#print axioms rho_normalize_pattern_of_fvar
#print axioms rho_bvar_lookup_of_tree
#print axioms rho_fvar_lookup_of_tree
#print axioms rho_collapsingLeafExposureBVarRoute_of_staticNormal
#print axioms rho_collapsingLeafExposureFVarRoute_of_sourceVariable
#print axioms rho_collapsingLeafExposureInDomain_of_admittedLeafRoutes
#print axioms rho_collapsingLeafExposureAdmittedBVarRoute_of_dichotomy
#print axioms rho_collapsingLeafExposureAdmittedFVarRoute_of_dichotomy
#print axioms rho_collapsingLeafExposureAdmittedApplyRoute_of_boundary
#print axioms rho_collapsingLeafExposureInDomain_of_classifications
