import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryResidualSwitchboard
open Mettapedia.Languages.ProcessCalculi.RhoCalculus
#check @costStaticReflectivePresentationDecl_parallelCollection
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.costStaticReflectivePresentationDecl_parallelCollection
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.RhoStaticNonBoundaryPlanStopCommonApex.not_sameColorResidual
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.RhoStaticNonBoundaryPlanStopCommonApex.afterSameColorBoundarySide_of_foreign
