import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryAlignedRestoration

open Mettapedia.Languages.ProcessCalculi.RhoCalculus

#check @canonicalize_eq_of_canonicalRootAligned
#check @RhoStaticViewsRestorationAlignedInDomain.toAligned
#check @RhoStaticPlanStopSourceAligned
#check @rhoAlignedViewsRestorationAligned_of_planStopSourceAligned
#check @RhoStaticNonBoundaryPlanStopSourceAligned
#check @rightRootAdmissible_of_admissible
#check @RhoStaticPlanStopSourceAligned.of_nonBoundaryRemainder
#check @rhoAlignedViewsRestorationAligned_of_nonBoundaryRemainder
#check @rhoAlignedViewsPlanStopApex_of_sourceAligned
#check @rhoCanonicalStaticPairSemanticCut_aligned_of_planStopApex

#print axioms canonicalize_eq_of_canonicalRootAligned
#print axioms RhoStaticViewsRestorationAlignedInDomain.toAligned
#print axioms rhoAlignedViewsRestorationAligned_of_planStopSourceAligned
#print axioms rightRootAdmissible_of_admissible
#print axioms RhoStaticPlanStopSourceAligned.of_nonBoundaryRemainder
#print axioms rhoAlignedViewsRestorationAligned_of_nonBoundaryRemainder
#print axioms rhoAlignedViewsPlanStopApex_of_sourceAligned
#print axioms rhoCanonicalStaticPairSemanticCut_aligned_of_planStopApex
