import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryProviderApexSlice
open Mettapedia.Languages.ProcessCalculi.RhoCalculus
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.RhoCanonicalStaticPairSemanticCut.rightStaticEnclosingOfPlanStops
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.nonempty_rhoCanonicalStaticPairSemanticCut_rightCollapsing_of_routes
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rhoCanonicalStaticPairSemanticCutProviderInDomain_of_apexSliceObligations
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rhoHereditaryCostOneDomainObject_ofApexSliceObligations
