import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryCollapsingRestoration
open Mettapedia.Languages.ProcessCalculi.RhoCalculus
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.not_canonicalStopAligned_endpoints_of_collapsing
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rho_collapsingViewsRestorationAlignedInDomain_of_residuals
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rhoCollapsingViewsPlanStopSourceAligned_of_nonBoundaryRemainder
