import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryAlignedRestoration
open Mettapedia.Languages.ProcessCalculi.RhoCalculus
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rhoCanonicalStaticPairSemanticCutProviderInDomain_of_apexObligations
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rhoHereditaryCostOneDomainObject_ofApexObligations
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rhoHereditaryCostOneObjectLaws_ofApexObligations
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.RhoStaticViewsRestorationAlignedInDomain.toAligned
