import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryQuoteParallelCells
open Mettapedia.Languages.ProcessCalculi.RhoCalculus
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.RhoPlanStopQuotePairCell.toSameColorQuoteSideCell
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.RhoStaticNonBoundaryPlanStopSourceAligned.of_boundarySide_and_stops
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rhoCanonicalRawStop_endpoints_at_succ_and_not_at_endpointMeasure
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.rho_planStop_rawStop_of_delegatedCell
