import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryLeafDichotomyProbe
open Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryLeafDichotomyProbe
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryLeafDichotomyProbe.isStaticRoot_or_bvar_of_rhoProcess_canonicalize_eq_bvar
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryLeafDichotomyProbe.isStaticRoot_or_fvar_of_rhoProcess_canonicalize_eq_fvar
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryLeafDichotomyProbe.boundaryHead_canonicalize_ne_bvar
