import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryMatchedFramesCanonicalCanary
open Mettapedia.Languages.ProcessCalculi.RhoCalculus
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryMatchedFramesCanonicalCanary.frame_canonical_false_but_apex_true
#print axioms Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryMatchedFramesCanonicalCanary.aligned_views_have_restoration_alignment
