import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryRecursiveStep

open Mettapedia.Languages.ProcessCalculi.RhoCalculus

#check @rhoStaticPlanStopCommonApex_sameColor_of_recursiveStep
#check @rhoAlignedViewsPlanStopApexInDomain_of_recursiveStep
#check @rhoCollapsingViewsPlanStopApexInDomain_of_recursiveStep
#check @costCanonicalStaticPairClosedInDomain_of_recursiveStep
#check @rhoCanonicalPairRecursiveStep_of_pairs_and_apexActions

#print axioms rhoStaticPlanStopCommonApex_sameColor_of_recursiveStep
#print axioms rhoAlignedViewsPlanStopApexInDomain_of_recursiveStep
#print axioms rhoCollapsingViewsPlanStopApexInDomain_of_recursiveStep
#print axioms costCanonicalStaticPairClosedInDomain_of_recursiveStep
#print axioms rhoCanonicalPairRecursiveStep_of_pairs_and_apexActions
