import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryQuoteParallelCells

open Mettapedia.Languages.ProcessCalculi.RhoCalculus

#check @rho_rawStop_of_ownColorQuoteLeftPayload
#check @rho_rawStop_of_ownColorQuoteRightPayload
#check @rho_planStop_rawStop_of_sameColorQuoteSide
#check @RhoPlanStopQuotePairCell.toSameColorQuoteSideCell
#check @RhoPlanStopForeignQuotePairCell
#check @RhoStaticNonBoundaryPlanStopSourceAlignedOn.quotePair_of_halves
#check @RhoPlanStopDelegatedCell
#check @rho_planStop_rawStop_of_delegatedCell
#check @rho_planStop_delegatedCell_size_lt
#check @rho_planStop_delegatedCell_size_le_at_succ
#check @rhoCanonicalRawStop_endpoints_at_succ_and_not_at_endpointMeasure
#check @RhoPlanStopDelegatedSourceLeaf
#check @RhoStaticNonBoundaryPlanStopSourceAlignedOn.of_delegated
#check @RhoStaticNonBoundaryPlanStopSourceAlignedOn.parallelSide_of_delegated
#check @RhoStaticNonBoundaryPlanStopSourceAlignedOn.sameColorQuoteSide_of_delegated
#check @rho_planStop_foreignQuotePair_arguments
#check @RhoPlanStopForeignQuotePairSourceLeaf
#check @RhoStaticNonBoundaryPlanStopSourceAlignedOn.foreignQuotePair_of_delegated
#check @RhoStaticNonBoundaryPlanStopSourceAligned.of_boundarySide_and_stops
#check @RhoStaticNonBoundaryPlanStopSourceAligned.of_boundarySide_and_stops_rawStop

#print axioms rho_rawStop_of_ownColorQuoteLeftPayload
#print axioms rho_rawStop_of_ownColorQuoteRightPayload
#print axioms rho_planStop_rawStop_of_sameColorQuoteSide
#print axioms RhoPlanStopQuotePairCell.toSameColorQuoteSideCell
#print axioms RhoStaticNonBoundaryPlanStopSourceAlignedOn.quotePair_of_halves
#print axioms rho_planStop_rawStop_of_delegatedCell
#print axioms rho_planStop_delegatedCell_size_lt
#print axioms rho_planStop_delegatedCell_size_le_at_succ
#print axioms rhoCanonicalRawStop_endpoints_at_succ_and_not_at_endpointMeasure
#print axioms RhoStaticNonBoundaryPlanStopSourceAlignedOn.of_delegated
#print axioms RhoStaticNonBoundaryPlanStopSourceAlignedOn.parallelSide_of_delegated
#print axioms RhoStaticNonBoundaryPlanStopSourceAlignedOn.sameColorQuoteSide_of_delegated
#print axioms rho_planStop_foreignQuotePair_arguments
#print axioms RhoStaticNonBoundaryPlanStopSourceAlignedOn.foreignQuotePair_of_delegated
#print axioms RhoStaticNonBoundaryPlanStopSourceAligned.of_boundarySide_and_stops
#print axioms RhoStaticNonBoundaryPlanStopSourceAligned.of_boundarySide_and_stops_rawStop
