import Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId.TypedEquality.Impredicative.Domain.AlignedEliminator

/-!
# The witnesses of the eliminator read at the reflexivity point

A token of the identity eliminator read at the reflexivity point (`jAlignedConst`),
applied to arguments that are elements of their parameter types, is entailed by tokens
of the method typed at the motive at the path's point and its reflexivity
(`mem_appSpine_jAlignedConst`); the path then has the reflexivity tag.

A token of the motive at a point and its reflexivity comes from one entry of the motive
whose first input is below the point and whose second input is below the reflexivity
(`motive_entry`). The point of an element of an identity type is below both endpoints
(`reflPoint_le_endpoints`). When the path is an element of a type, its point is
generated by its point tokens typed at that type (`reflPoint_projT_le`): finitely many
of them entail the first input, and the reflexivity tag with them entails the second
(`aligned_inputs`).
-/

set_option autoImplicit false

namespace Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId.Presentation
namespace TypedEquality
namespace Impredicative
namespace Domain

namespace Ideal

/-- A token of an element guarded by a tag observes nothing, or the tag is present and
the token is one of the element's. -/
theorem mem_whenTag {k : Kind} {ν I : Ideal} {t : Tok} (h : (whenTag k ν I).Mem t) :
    ent [] t = true ∨ (ν.Mem (.tag k) ∧ I.Mem t) := by
  obtain ⟨v, hv, ht⟩ := h
  cases v with
  | nil => exact .inl ht
  | cons s w =>
      exact .inr ⟨(hv s List.mem_cons_self).1, I.closed (fun r hr => (hv r hr).2) ht⟩

/-- An entry whose output entails a token yields the entry with that token as its
output. -/
theorem ent_fn_single {w X Y : List Tok} {r : Tok}
    (h : ent w (.fn .lam [] X Y) = true) (hr : ent Y r = true) :
    ent w (.fn .lam [] X [r]) = true := by
  rw [ent_fn, Bool.and_eq_true, List.all_eq_true, List.all_eq_true] at h ⊢
  refine ⟨h.1, fun y hy => ?_⟩
  rw [List.mem_singleton.1 hy]
  exact ent_cut hr fun y' hy' => h.2 y' hy'

/-- **A token of the motive at a point and its reflexivity** comes from one entry of the
motive whose first input is below the point and whose second input is below the
reflexivity. -/
theorem motive_entry {π q : Ideal} {r : Tok} (h : (app (app π q) (refl q)).Mem r) :
    ∃ Z₁ Z₂, π.Mem (.fn .lam [] Z₁ [.fn .lam [] Z₂ [r]]) ∧ Below Z₁ q ∧
      Below Z₂ (refl q) := by
  obtain ⟨X, Y, hX, hXY, hYr⟩ := mem_app.1 h
  obtain ⟨X', Y', hX', hπ, hY'⟩ := mem_app.1 hXY
  refine ⟨X', X, π.closed (v := [.fn .lam [] X' Y']) (fun s hs => by
    rw [List.mem_singleton.1 hs]; exact hπ) ?_, hX', hX⟩
  refine ent_fn_single (X := X') (Y := [.fn .lam [] X Y]) ?_ (ent_fn_single ?_ hYr)
  · rw [ent_fn, Bool.and_eq_true, List.all_eq_true, List.all_eq_true]
    refine ⟨fun c hc => absurd hc List.not_mem_nil, fun y hy => ?_⟩
    rw [List.mem_singleton.1 hy]
    exact ent_cut hY' fun y' hy' => ent_of_mem (mem_fnApp.2 ⟨[], X', Y', List.mem_cons_self,
      fun s hs => ent_of_mem hs, hy'⟩)
  · exact ent_of_mem List.mem_cons_self

/-- The typed point tokens of a path. -/
def TypedPoint (T p : Ideal) (s : Tok) : Prop :=
  p.Mem (.arg .refl 0 [] s) ∧ TypedAt T (.arg .refl 0 [] s)

/-- The components of the point tokens of typed tokens are typed point tokens. -/
theorem typedPoint_of_args {T p : Ideal} {w : List Tok}
    (hw : ∀ t ∈ w, p.Mem t ∧ TypedAt T t) : ∀ s ∈ args .refl 0 w, TypedPoint T p s := by
  intro s hs
  rcases mem_args_iff.1 hs with ⟨C, hC⟩ | ⟨-, t, ht, hk, hd⟩
  · obtain ⟨hp, a, ha, hau, hat⟩ := hw _ hC
    obtain ⟨-, rfl, -⟩ := tyTok_reflPoint.1 hat
    exact ⟨hp, a, ha, hau, hat⟩
  · obtain ⟨-, a, -, -, hat⟩ := hw t ht
    cases t with
    | tag k => cases hd
    | arg k i C s' =>
        simp only [Tok.kind] at hk
        subst hk
        cases i with
        | zero =>
            obtain ⟨-, rfl, -⟩ := tyTok_reflPoint.1 hat
            cases hd
        | succ i =>
            refine absurd hat ?_
            rw [TyTok]
            · exact id
            all_goals
              intro h₁ h₂
              first | exact Kind.noConfusion h₁ | exact Nat.noConfusion h₂
    | fn k C X Y =>
        simp only [Tok.kind] at hk
        subst hk
        exact absurd hat (tyTok_fn_other ⟨by decide, by decide, by decide⟩)

/-- **The point of a typed path is generated by its typed point tokens.** -/
theorem reflPoint_projT_le (T p : Ideal) :
    reflPoint (projT T p) ≤ closure (TypedPoint T p) := by
  intro s hs
  obtain ⟨v, hv, hvs⟩ := hs
  refine (closure (TypedPoint T p)).closed (v := v) (fun s' hs' => ?_) hvs
  obtain ⟨w, hwp, hwT, hws⟩ := projT_eq_iSup.1 (hv s' hs')
  rw [ent_arg, List.all_nil, Bool.true_and] at hws
  exact (closure (TypedPoint T p)).closed (v := args .refl 0 w)
    (fun r hr => subset_closure (typedPoint_of_args (fun t ht => ⟨hwp t ht, hwT t ht⟩) r hr))
    hws

theorem args_refl_cons_tag (L : List Tok) : args .refl 0 (.tag .refl :: L) = args .refl 0 L :=
  rfl

/-- **The inputs of an entry of the motive at the point of a typed path are aligned**:
finitely many typed point tokens entail the first input, and the reflexivity tag with
them entails the second. -/
theorem aligned_inputs {T p : Ideal} (hp : projT T p = p) {Z₁ Z₂ : List Tok}
    (h₁ : Below Z₁ (reflPoint p)) (h₂ : Below Z₂ (refl (reflPoint p))) :
    ∃ S : List Tok, (∀ s ∈ S, TypedPoint T p s) ∧ (∀ z ∈ Z₁, ent S z = true) ∧
      ∀ z ∈ Z₂, ent (.tag .refl :: S.map (.arg .refl 0 [])) z = true := by
  have hle : reflPoint p ≤ closure (TypedPoint T p) := by
    conv_lhs => rw [← hp]
    exact reflPoint_projT_le T p
  obtain ⟨S₁, hS₁, hZ₁⟩ := below_closure_iff.1 (h₁.mono hle)
  obtain ⟨w, hw, hZ₂⟩ := below_closure_iff.1 h₂
  -- the point tokens among the generators of the reflexivity
  obtain ⟨S₂, hS₂, hgen⟩ := gather (P := TypedPoint T p)
    (Q := fun G (g : Tok) => ent (.tag .refl :: G.map (.arg .refl 0 [])) g = true)
    (fun hsub h => ent_mono (fun s hs => by
      rcases List.mem_cons.1 hs with rfl | hs
      · exact List.mem_cons_self
      · obtain ⟨s', hs', rfl⟩ := List.mem_map.1 hs
        exact List.mem_cons_of_mem _ (List.mem_map_of_mem (hsub s' hs'))) h)
    (Y := w) fun g hg => by
      rcases hw g hg with rfl | ⟨s, rfl, hs⟩
      · exact ⟨[], fun _ h => absurd h List.not_mem_nil, ent_of_mem List.mem_cons_self⟩
      · obtain ⟨S, hS, hs'⟩ := hle s hs
        refine ⟨S, hS, ?_⟩
        rw [ent_arg, List.all_nil, Bool.true_and, args_refl_cons_tag, args_map_arg_same]
        exact hs'
  refine ⟨S₁ ++ S₂, fun s hs => ?_, fun z hz => ?_, fun z hz => ?_⟩
  · rcases List.mem_append.1 hs with hs | hs
    · exact hS₁ s hs
    · exact hS₂ s hs
  · exact ent_mono (fun s hs => List.mem_append_left _ hs) (hZ₁ z hz)
  · refine ent_cut (hZ₂ z hz) fun g hg => ent_mono (fun s hs => ?_) (hgen g hg)
    rcases List.mem_cons.1 hs with rfl | hs
    · exact List.mem_cons_self
    · obtain ⟨s', hs', rfl⟩ := List.mem_map.1 hs
      exact List.mem_cons_of_mem _ (List.mem_map_of_mem (List.mem_append_right _ hs'))

/-- **The point of an element of an identity type is below both endpoints.** -/
theorem reflPoint_le_endpoints {A I J p : Ideal} (hp : projT (ident A I J) p = p) :
    reflPoint p ≤ I ∧ reflPoint p ≤ J := by
  have hle : reflPoint p ≤ closure (TypedPoint (ident A I J) p) := by
    conv_lhs => rw [← hp]
    exact reflPoint_projT_le _ _
  have key : ∀ s, TypedPoint (ident A I J) p s → I.Mem s ∧ J.Mem s := by
    rintro s ⟨-, a, ha, -, hat⟩
    obtain ⟨-, -, -, h1, h2⟩ := tyTok_reflPoint.1 hat
    refine ⟨I.closed (fun r hr => ?_) h1, J.closed (fun r hr => ?_) h2⟩
    · rcases mem_args_iff.1 hr with ⟨C, hC⟩ | ⟨h, -⟩
      · exact (mem_ident_arg (ha _ hC)).2.1 rfl
      · exact absurd h Nat.one_ne_zero
    · rcases mem_args_iff.1 hr with ⟨C, hC⟩ | ⟨h, -⟩
      · exact (mem_ident_arg (ha _ hC)).2.2 rfl
      · exact absurd h (by decide)
  exact ⟨le_trans hle (closure_le fun s hs => (key s hs).1),
    le_trans hle (closure_le fun s hs => (key s hs).2)⟩

end Ideal

open Ideal

variable {Head : Type}

/-- **The tokens of the eliminator read at the reflexivity point**, at arguments that are
elements of their parameter types, are entailed by tokens of the method typed at the
motive at the path's point and its reflexivity, the path carrying the reflexivity
tag. -/
theorem mem_appSpine_jAlignedConst {Rd : Reading Head} {u : Head} {α ξ π δ η p : Ideal}
    (spine : SpineTyped (jTypeI Rd u) [α, ξ, π, δ, η, p]) {s : Tok}
    (h : (appSpine (jAlignedConst Rd u) [α, ξ, π, δ, η, p]).Mem s) :
    ∃ v, ent v s = true ∧ ∀ t ∈ v, p.Mem (.tag .refl) ∧ δ.Mem t ∧
      TypedAt (app (app π (reflPoint p)) (refl (reflPoint p))) t := by
  rw [jAlignedConst, appSpine_churchConst _ (churchTele_cinterp Rd (jTypeC u) Env.nil)
    (Nat.le_refl _) spine, appSpine_jAlignedRaw] at h
  rcases mem_whenTag (projT_le _ _ s h) with hv | ⟨hp, hδ⟩
  · exact ⟨[], hv, fun _ h => absurd h List.not_mem_nil⟩
  · obtain ⟨v, hvδ, hvT, hvs⟩ := projT_eq_iSup.1 hδ
    exact ⟨v, hvs, fun t ht => ⟨hp, hvδ t ht, hvT t ht⟩⟩

end Domain
end Impredicative
end TypedEquality
end Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId.Presentation
