import Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId.TypedEquality.Impredicative.Domain.ProjectionLaws

/-!
# Continuous maps of ideals

A map of ideals is *continuous* (`Ideal.Cont`) when it is monotone and every token
of a value is already a token of the value at a finite part of the argument. A map
of two ideals is continuous when it is continuous in each argument (`Ideal.Cont₂`);
it is then continuous in both jointly (`Ideal.Cont₂.comp`). A map from environments
to ideals is continuous (`EnvCont`) when every token of a value is a token of the
value at a finite approximation of the environment.

* Every ideal generated by a condition on finite parts of the argument is
  continuous (`Ideal.Cont.of_closure`, `EnvCont.of_closure`). This covers the
  operations of the domain: the projection onto a type, in the type and in the
  element (`Ideal.cont₂_projT`); application and the family of a dependent type
  (`Ideal.cont₂_app`, `Ideal.cont₂_fam`); the domain of a dependent type, pairs,
  projections, reflexivity, successors and predecessors, joins, and the element
  that is a given ideal when a tag is present (`Ideal.whenTag`).
* **Extension** (`Ideal.app_lam_principal`, `Ideal.fam_former_principal`): the
  function whose value at each compact element `X` is `H (principal X)`, applied to
  an ideal `y`, is `H y`, when `H` is continuous; likewise the family of a dependent
  type presented this way. This is β at every argument for functions defined on
  compact elements.
* A function whose value depends continuously on a parameter depends continuously
  on it as a function (`Ideal.cont_lam_param`).

The join of two ideals (`Ideal.join`) and case analysis on a tag (`Ideal.whenTag`) are
defined over any type of kinds, like the ideals themselves; continuity is stated for the
domain's kinds.

Examples. Positive: a constant map and the identity are continuous (`Ideal.Cont.const`,
`Ideal.Cont.id`), and case analysis on a tag that is present returns its branch
(`Ideal.whenTag_of_mem`). Negative: case analysis on a tag that is absent returns the least
element whatever the branch (`Ideal.whenTag_of_not_mem`).
-/

set_option autoImplicit false

namespace Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId.Presentation
namespace TypedEquality
namespace Impredicative
namespace Domain
namespace Ideal

/-! ## Continuous maps -/

/-- A continuous map of ideals: monotone, and every token of a value is a token of
the value at a finite part of the argument. -/
structure Cont (H : Ideal → Ideal) : Prop where
  mono : ∀ {I J : Ideal}, I ≤ J → H I ≤ H J
  finite : ∀ {I : Ideal} {t : Tok}, (H I).Mem t → ∃ X, Below X I ∧ (H (principal X)).Mem t

/-- Finitely many tokens of a value are tokens of the value at one finite part of the
argument. -/
theorem Cont.below {H : Ideal → Ideal} (hH : Cont H) {I : Ideal} :
    ∀ {v : List Tok}, Below v (H I) → ∃ X, Below X I ∧ Below v (H (principal X))
  | [], _ => ⟨[], fun _ h => absurd h List.not_mem_nil, fun _ h => absurd h List.not_mem_nil⟩
  | t :: v, h => by
      obtain ⟨X₁, h₁, ht⟩ := hH.finite (h t List.mem_cons_self)
      obtain ⟨X₂, h₂, hv⟩ := Cont.below hH (v := v) fun s hs => h s (List.mem_cons_of_mem _ hs)
      refine ⟨X₁ ++ X₂, h₁.append h₂, fun s hs => ?_⟩
      rcases List.mem_cons.1 hs with rfl | hs
      · exact hH.mono (principal_mono (Le.append_left _ _)) _ ht
      · exact hH.mono (principal_mono (Le.append_right _ _)) _ (hv s hs)

/-- An ideal generated by a condition that is monotone in the argument and witnessed
at a finite part of it is continuous in the argument. -/
theorem Cont.of_closure {P : Ideal → Tok → Prop}
    (mono : ∀ {I J : Ideal}, I ≤ J → ∀ t, P I t → P J t)
    (finite : ∀ {I : Ideal} {t : Tok}, P I t → ∃ X, Below X I ∧ P (principal X) t) :
    Cont fun I => closure (P I) where
  mono h := closure_mono (mono h)
  finite := by
    intro I t ⟨v, hv, ht⟩
    obtain ⟨X, hX, hvX⟩ := gather (P := fun g => I.Mem g)
      (Q := fun G (s : Tok) => P (principal G) s)
      (fun hsub h => mono (principal_mono (Le.of_subset hsub)) _ h) (Y := v)
      fun s hs => finite (hv s hs)
    exact ⟨X, hX, v, hvX, ht⟩

theorem Cont.id : Cont fun I => I where
  mono h := h
  finite {I t} ht := ⟨[t], fun s hs => by rw [List.mem_singleton.1 hs]; exact ht,
    ent_of_mem List.mem_cons_self⟩

theorem Cont.const (K : Ideal) : Cont fun _ => K where
  mono _ := le_refl K
  finite ht := ⟨[], fun _ h => absurd h List.not_mem_nil, ht⟩

theorem Cont.comp {H K : Ideal → Ideal} (hH : Cont H) (hK : Cont K) : Cont fun I => H (K I) where
  mono h := hH.mono (hK.mono h)
  finite := by
    intro I t ht
    obtain ⟨X, hX, ht'⟩ := hH.finite ht
    obtain ⟨Y, hY, hXY⟩ := hK.below hX
    exact ⟨Y, hY, hH.mono (principal_le_iff.2 hXY) _ ht'⟩

/-- A map of two ideals, continuous in each argument. -/
structure Cont₂ (H : Ideal → Ideal → Ideal) : Prop where
  left : ∀ J, Cont fun I => H I J
  right : ∀ I, Cont fun J => H I J

theorem Cont₂.mono {H : Ideal → Ideal → Ideal} (hH : Cont₂ H) {I I' J J' : Ideal} (hI : I ≤ I')
    (hJ : J ≤ J') : H I J ≤ H I' J' :=
  le_trans ((hH.left J).mono hI) ((hH.right I').mono hJ)

/-- **Separate continuity is joint continuity.** -/
theorem Cont₂.comp {H : Ideal → Ideal → Ideal} (hH : Cont₂ H) {K L : Ideal → Ideal}
    (hK : Cont K) (hL : Cont L) : Cont fun z => H (K z) (L z) where
  mono h := hH.mono (hK.mono h) (hL.mono h)
  finite := by
    intro z t ht
    obtain ⟨X, hX, ht₁⟩ := (hH.left (L z)).finite ht
    obtain ⟨Y, hY, ht₂⟩ := (hH.right (principal X)).finite ht₁
    obtain ⟨X', hX', hXX'⟩ := hK.below hX
    obtain ⟨Y', hY', hYY'⟩ := hL.below hY
    refine ⟨X' ++ Y', hX'.append hY', hH.mono ?_ ?_ _ ht₂⟩
    · exact le_trans (principal_le_iff.2 hXX') (hK.mono (principal_mono (Le.append_left _ _)))
    · exact le_trans (principal_le_iff.2 hYY') (hL.mono (principal_mono (Le.append_right _ _)))

/-! ## The operations are continuous -/

theorem cont_projT (T : Ideal) : Cont (projT T) :=
  Cont.of_closure (P := fun I t => I.Mem t ∧ TypedAt T t) (fun h t ht => ⟨h t ht.1, ht.2⟩)
    fun {_ t} ht => ⟨[t], fun s hs => by rw [List.mem_singleton.1 hs]; exact ht.1,
      ent_of_mem List.mem_cons_self, ht.2⟩

theorem cont_projT_type (I : Ideal) : Cont fun T => projT T I :=
  Cont.of_closure (P := fun T t => I.Mem t ∧ TypedAt T t) (fun h t ht => ⟨ht.1, ht.2.mono h⟩)
    fun {_ _} ht => by
      obtain ⟨a, ha, hau, hat⟩ := ht.2
      exact ⟨a, ha, ht.1, a, fun s hs => ent_of_mem hs, hau, hat⟩

theorem cont₂_projT : Cont₂ projT := ⟨cont_projT_type, cont_projT⟩

theorem cont_fam_type (k : Kind) (y : Ideal) : Cont fun T => fam k T y :=
  Cont.of_closure (P := fun T t => ∃ C Z Y, T.Mem (.fn k C Z Y) ∧ Below Z y ∧ t ∈ Y)
    (fun h _ ⟨C, Z, Y, hm, hZ, ht⟩ => ⟨C, Z, Y, h _ hm, hZ, ht⟩)
    fun {_ _} ⟨C, Z, Y, hm, hZ, ht⟩ =>
      ⟨[.fn k C Z Y], fun s hs => by rw [List.mem_singleton.1 hs]; exact hm,
        C, Z, Y, ent_of_mem List.mem_cons_self, hZ, ht⟩

theorem cont_fam_arg (k : Kind) (T : Ideal) : Cont (fam k T) :=
  Cont.of_closure (P := fun y t => ∃ C Z Y, T.Mem (.fn k C Z Y) ∧ Below Z y ∧ t ∈ Y)
    (fun h _ ⟨C, Z, Y, hm, hZ, ht⟩ => ⟨C, Z, Y, hm, hZ.mono h, ht⟩)
    fun {_ _} ⟨C, Z, Y, hm, hZ, ht⟩ => ⟨Z, hZ, C, Z, Y, hm, fun _ hs => ent_of_mem hs, ht⟩

theorem cont₂_fam (k : Kind) : Cont₂ (fam k) := ⟨cont_fam_type k, cont_fam_arg k⟩

theorem cont₂_app : Cont₂ app := cont₂_fam .lam

theorem cont_dom (k : Kind) : Cont (dom k) :=
  Cont.of_closure (P := fun T s => T.Mem (.arg k 0 [] s)) (fun h _ hs => h _ hs)
    fun {_ s} hs => ⟨[.arg k 0 [] s], fun r hr => by rw [List.mem_singleton.1 hr]; exact hs,
      ent_of_mem List.mem_cons_self⟩

theorem cont_refl : Cont refl :=
  Cont.of_closure (P := fun I t => t = .tag .refl ∨ ∃ s, t = .arg .refl 0 [] s ∧ I.Mem s)
    (fun h _ ht => ht.imp_right fun ⟨s, e, hs⟩ => ⟨s, e, h s hs⟩)
    fun {_ _} ht => by
      rcases ht with rfl | ⟨s, rfl, hs⟩
      · exact ⟨[], fun _ h => absurd h List.not_mem_nil, .inl rfl⟩
      · exact ⟨[s], fun r hr => by rw [List.mem_singleton.1 hr]; exact hs,
          .inr ⟨s, rfl, ent_of_mem List.mem_cons_self⟩⟩

theorem cont_fst : Cont fst :=
  Cont.of_closure (P := fun I s => I.Mem (.arg .pair 0 [] s)) (fun h s hs => h _ hs)
    fun {_ s} hs => ⟨[.arg .pair 0 [] s], fun r hr => by rw [List.mem_singleton.1 hr]; exact hs,
      ent_of_mem List.mem_cons_self⟩

theorem cont_snd : Cont snd :=
  Cont.of_closure (P := fun I s => ∃ C, I.Mem (.arg .pair 1 C s))
    (fun h s ⟨C, hs⟩ => ⟨C, h _ hs⟩)
    fun {_ s} ⟨C, hs⟩ => ⟨[.arg .pair 1 C s], fun r hr => by rw [List.mem_singleton.1 hr]; exact hs,
      C, ent_of_mem List.mem_cons_self⟩

theorem cont₂_pair : Cont₂ pair where
  left J := Cont.of_closure
    (P := fun I t => (∃ s, t = .arg .pair 0 [] s ∧ I.Mem s) ∨
      ∃ C s, t = .arg .pair 1 C s ∧ Below C I ∧ J.Mem s)
    (fun h _ ht => ht.imp (fun ⟨s, e, hs⟩ => ⟨s, e, h s hs⟩)
      fun ⟨C, s, e, hC, hs⟩ => ⟨C, s, e, hC.mono h, hs⟩)
    fun {_ _} ht => by
      rcases ht with ⟨s, rfl, hs⟩ | ⟨C, s, rfl, hC, hs⟩
      · exact ⟨[s], fun r hr => by rw [List.mem_singleton.1 hr]; exact hs,
          .inl ⟨s, rfl, ent_of_mem List.mem_cons_self⟩⟩
      · exact ⟨C, hC, .inr ⟨C, s, rfl, fun c hc => ent_of_mem hc, hs⟩⟩
  right I := Cont.of_closure
    (P := fun J t => (∃ s, t = .arg .pair 0 [] s ∧ I.Mem s) ∨
      ∃ C s, t = .arg .pair 1 C s ∧ Below C I ∧ J.Mem s)
    (fun h _ ht => ht.imp_right fun ⟨C, s, e, hC, hs⟩ => ⟨C, s, e, hC, h s hs⟩)
    fun {_ _} ht => by
      rcases ht with ⟨s, rfl, hs⟩ | ⟨C, s, rfl, hC, hs⟩
      · exact ⟨[], fun _ h => absurd h List.not_mem_nil, .inl ⟨s, rfl, hs⟩⟩
      · exact ⟨[s], fun r hr => by rw [List.mem_singleton.1 hr]; exact hs,
          .inr ⟨C, s, rfl, hC, ent_of_mem List.mem_cons_self⟩⟩

section JoinTag

variable {κ : Type} [DecidableEq κ]

/-- The join of two ideals. -/
def join (I J : Ideal κ) : Ideal κ := closure fun t => I.Mem t ∨ J.Mem t

theorem le_join_left (I J : Ideal κ) : I ≤ join I J := fun _ h => subset_closure (.inl h)

theorem le_join_right (I J : Ideal κ) : J ≤ join I J := fun _ h => subset_closure (.inr h)

theorem join_le {I J K : Ideal κ} (hI : I ≤ K) (hJ : J ≤ K) : join I J ≤ K :=
  closure_le fun t ht => ht.elim (hI t) (hJ t)

theorem join_bot (I : Ideal κ) : join I bot = I :=
  le_antisymm (join_le (le_refl I) (bot_le I)) (le_join_left I bot)

theorem bot_join (I : Ideal κ) : join bot I = I :=
  le_antisymm (join_le (bot_le I) (le_refl I)) (le_join_right bot I)

/-- `I` when `ν` has the tag of kind `k`, the least element otherwise. -/
def whenTag (k : κ) (ν I : Ideal κ) : Ideal κ := closure fun t => ν.Mem (.tag k) ∧ I.Mem t

theorem whenTag_of_mem {k : κ} {ν : Ideal κ} (h : ν.Mem (.tag k)) (I : Ideal κ) :
    whenTag k ν I = I :=
  le_antisymm (closure_le fun _ ht => ht.2) fun _ ht => subset_closure ⟨h, ht⟩

theorem whenTag_of_not_mem {k : κ} {ν : Ideal κ} (h : ¬ ν.Mem (.tag k)) (I : Ideal κ) :
    whenTag k ν I = bot :=
  le_antisymm (closure_le fun _ ht => absurd ht.1 h) (bot_le _)

theorem whenTag_le (k : κ) (ν I : Ideal κ) : whenTag k ν I ≤ I := closure_le fun _ ht => ht.2

end JoinTag

theorem cont₂_join : Cont₂ join where
  left J := Cont.of_closure (P := fun I t => I.Mem t ∨ J.Mem t)
    (fun h t ht => ht.imp_left (h t))
    fun {_ t} ht => by
      rcases ht with ht | ht
      · exact ⟨[t], fun r hr => by rw [List.mem_singleton.1 hr]; exact ht,
          .inl (ent_of_mem List.mem_cons_self)⟩
      · exact ⟨[], fun _ h => absurd h List.not_mem_nil, .inr ht⟩
  right I := Cont.of_closure (P := fun J t => I.Mem t ∨ J.Mem t)
    (fun h t ht => ht.imp_right (h t))
    fun {_ t} ht => by
      rcases ht with ht | ht
      · exact ⟨[], fun _ h => absurd h List.not_mem_nil, .inl ht⟩
      · exact ⟨[t], fun r hr => by rw [List.mem_singleton.1 hr]; exact ht,
          .inr (ent_of_mem List.mem_cons_self)⟩

theorem cont₂_whenTag (k : Kind) : Cont₂ (whenTag k) where
  left I := Cont.of_closure (P := fun ν t => ν.Mem (.tag k) ∧ I.Mem t)
    (fun h _ ht => ⟨h _ ht.1, ht.2⟩)
    fun {_ _} ht => ⟨[.tag k], fun r hr => by rw [List.mem_singleton.1 hr]; exact ht.1,
      ent_of_mem List.mem_cons_self, ht.2⟩
  right ν := Cont.of_closure (P := fun I t => ν.Mem (.tag k) ∧ I.Mem t)
    (fun h t ht => ⟨ht.1, h t ht.2⟩)
    fun {_ t} ht => ⟨[t], fun r hr => by rw [List.mem_singleton.1 hr]; exact ht.2,
      ht.1, ent_of_mem List.mem_cons_self⟩

/-! ## Successors and predecessors -/

/-- The successor of an ideal. -/
def succI (m : Ideal) : Ideal :=
  closure fun t => t = .tag .succ ∨ ∃ s, t = .arg .succ 0 [] s ∧ m.Mem s

/-- The predecessor of an ideal: the components of its successor tokens. -/
def predI (ν : Ideal) : Ideal := closure fun s => ∃ C, ν.Mem (.arg .succ 0 C s)

theorem cont_succI : Cont succI :=
  Cont.of_closure (P := fun I t => t = .tag .succ ∨ ∃ s, t = .arg .succ 0 [] s ∧ I.Mem s)
    (fun h _ ht => ht.imp_right fun ⟨s, e, hs⟩ => ⟨s, e, h s hs⟩)
    fun {_ _} ht => by
      rcases ht with rfl | ⟨s, rfl, hs⟩
      · exact ⟨[], fun _ h => absurd h List.not_mem_nil, .inl rfl⟩
      · exact ⟨[s], fun r hr => by rw [List.mem_singleton.1 hr]; exact hs,
          .inr ⟨s, rfl, ent_of_mem List.mem_cons_self⟩⟩

theorem cont_predI : Cont predI :=
  Cont.of_closure (P := fun I s => ∃ C, I.Mem (.arg .succ 0 C s))
    (fun h s ⟨C, hs⟩ => ⟨C, h _ hs⟩)
    fun {_ s} ⟨C, hs⟩ => ⟨[.arg .succ 0 C s], fun r hr => by rw [List.mem_singleton.1 hr]; exact hs,
      C, ent_of_mem List.mem_cons_self⟩

/-- The successor's generators have their component in the argument. -/
private theorem succI_args_below {m : Ideal} {w : List Tok}
    (hw : ∀ s ∈ w, s = .tag .succ ∨ ∃ r, s = .arg .succ 0 [] r ∧ m.Mem r) :
    Below (args .succ 0 w) m := by
  intro c hc
  rcases mem_args_iff.1 hc with ⟨C, hC⟩ | ⟨-, t, ht, -, hd⟩
  · rcases hw _ hC with h | ⟨r, h, hr⟩
    · cases h
    · cases h
      exact hr
  · rcases hw _ ht with rfl | ⟨r, rfl, -⟩
    · cases hd
    · cases hd

/-- The predecessor of a successor is its argument. -/
theorem predI_succI (m : Ideal) : predI (succI m) = m := by
  apply le_antisymm
  · refine closure_le fun s ⟨C, hs⟩ => ?_
    obtain ⟨w, hw, h⟩ := hs
    rw [ent_arg, Bool.and_eq_true] at h
    exact (succI_args_below hw).ent h.2
  · intro s hs
    refine subset_closure ⟨[], subset_closure (.inr ⟨s, rfl, hs⟩)⟩

theorem succI_mem_succ (m : Ideal) : (succI m).Mem (.tag .succ) := subset_closure (.inl rfl)

theorem succI_not_mem_tag {k : Kind} (hk : k ≠ .succ) (m : Ideal) : ¬ (succI m).Mem (.tag k) := by
  intro h
  rcases closure_tag h with h | ⟨s, h, -⟩
  · exact hk (Tok.tag.inj h)
  · cases h

/-! ## Extension of functions defined on compact elements -/

/-- **Extension**: applying the function whose value at each compact `X` is
`H (principal X)` to an ideal `y` gives `H y`, when `H` is continuous. -/
theorem app_lam_principal {H : Ideal → Ideal} (hH : Cont H) (y : Ideal) :
    app (lam fun X => H (principal X)) y = H y := by
  have hG : Monotone fun X => H (principal X) := fun h => hH.mono (principal_mono h)
  apply le_antisymm
  · intro t ht
    obtain ⟨X, Y, hX, hl, hY⟩ := mem_app.1 ht
    exact hH.mono (principal_le_iff.2 hX) t ((H (principal X)).closed ((mem_lam_fn hG).1 hl) hY)
  · intro t ht
    obtain ⟨X, hX, ht'⟩ := hH.finite ht
    exact mem_app.2 ⟨X, [t], hX, (mem_lam_fn hG).2 fun s hs => by
      rw [List.mem_singleton.1 hs]; exact ht', ent_of_mem List.mem_cons_self⟩

/-- Applying a constant function. -/
theorem app_lam_const (K y : Ideal) : app (lam fun _ => K) y = K :=
  app_lam_principal (Cont.const K) y

/-- **Extension for families**: the family of the dependent type whose value at each
compact `X` is `H (principal X)`, at an ideal `y`, is `H y`, when `H` is continuous. -/
theorem fam_former_principal {k : Kind} (A : Ideal) {H : Ideal → Ideal} (hH : Cont H) (y : Ideal) :
    fam k (former k A fun X => H (principal X)) y = H y := by
  have hG : Monotone fun X => H (principal X) := fun h => hH.mono (principal_mono h)
  apply le_antisymm
  · intro t ht
    obtain ⟨Z, hZ, ht'⟩ := (mem_fam_former hG).1 ht
    exact hH.mono (principal_le_iff.2 hZ) t ht'
  · intro t ht
    obtain ⟨X, hX, ht'⟩ := hH.finite ht
    exact (mem_fam_former hG).2 ⟨X, hX, ht'⟩

/-- A function whose values depend continuously on a parameter depends continuously
on it. -/
theorem cont_lam_param {G : Ideal → List Tok → Ideal} (hG : ∀ X, Cont fun z => G z X) :
    Cont fun z => lam (G z) :=
  Cont.of_closure (P := fun z t => ∃ X Y, t = .fn .lam [] X Y ∧ Below Y (G z X))
    (fun h _ ⟨X, Y, e, hY⟩ => ⟨X, Y, e, hY.mono ((hG X).mono h)⟩)
    fun {_ _} ⟨X, Y, e, hY⟩ => by
      obtain ⟨Z, hZ, hYZ⟩ := (hG X).below hY
      exact ⟨Z, hZ, X, Y, e, hYZ⟩

/-! ## The projection of an ideal generated by typed tokens -/

/-- An ideal generated by `P` is fixed by the projection onto `T` when each
generator is entailed by finitely many of its tokens typed at `T`. -/
theorem projT_closure_eq {T : Ideal} {P : Tok → Prop}
    (h : ∀ g, P g → ∃ v, (∀ s ∈ v, (closure P).Mem s ∧ TypedAt T s) ∧ ent v g = true) :
    projT T (closure P) = closure P := by
  refine le_antisymm (projT_le _ _) fun t ⟨v, hv, htv⟩ => ?_
  obtain ⟨G, hG, hvG⟩ := gather (P := fun s => (closure P).Mem s ∧ TypedAt T s)
    (Q := fun G (g : Tok) => ent G g = true) (fun hsub h => ent_mono hsub h) (Y := v)
    fun g hg => h g (hv g hg)
  exact ⟨G, hG, ent_cut htv hvG⟩

/-- The principal ideal of a compact element typed at a compact type below `T` is
its own projection onto `T`. -/
theorem projT_principal_eq {T : Ideal} {a u : List Tok} (ha : Below a T) (hau : Ty a Elem.univ)
    (hu : Ty u a) : projT T (principal u) = principal u :=
  le_antisymm (projT_le _ _) fun _ ht =>
    ⟨u, fun s hs => ⟨ent_of_mem hs, a, ha, hau, hu s hs⟩, ht⟩

end Ideal

/-! ## Continuous maps from environments -/

open Ideal

/-- A continuous map from environments to ideals: monotone, and every token of a
value is a token of the value at a finite approximation of the environment. -/
structure EnvCont {n : Nat} (H : Env n → Ideal) : Prop where
  mono : ∀ {ρ ρ' : Env n}, Env.Le ρ ρ' → H ρ ≤ H ρ'
  finite : ∀ {ρ : Env n} {t : Tok}, (H ρ).Mem t → ∃ X, Approximates X ρ ∧ (H (Env.approx X)).Mem t

namespace EnvCont

variable {n : Nat}

theorem below {H : Env n → Ideal} (hH : EnvCont H) {ρ : Env n} :
    ∀ {v : List Tok}, Below v (H ρ) → ∃ X, Approximates X ρ ∧ Below v (H (Env.approx X))
  | [], _ => ⟨fun _ => [], Approximates.nil ρ, fun _ h => absurd h List.not_mem_nil⟩
  | t :: v, h => by
      obtain ⟨X₁, h₁, ht⟩ := hH.finite (h t List.mem_cons_self)
      obtain ⟨X₂, h₂, hv⟩ := EnvCont.below hH (v := v) fun s hs => h s (List.mem_cons_of_mem _ hs)
      refine ⟨approxJoin X₁ X₂, h₁.join h₂, fun s hs => ?_⟩
      rcases List.mem_cons.1 hs with rfl | hs
      · exact hH.mono (approx_le_join_left X₁ X₂) _ ht
      · exact hH.mono (approx_le_join_right X₁ X₂) _ (hv s hs)

/-- An ideal generated by a condition that is monotone in the environment and
witnessed at a finite approximation of it is continuous. -/
theorem of_closure {P : Env n → Tok → Prop}
    (mono : ∀ {ρ ρ' : Env n}, Env.Le ρ ρ' → ∀ t, P ρ t → P ρ' t)
    (finite : ∀ {ρ : Env n} {t : Tok}, P ρ t → ∃ X, Approximates X ρ ∧ P (Env.approx X) t) :
    EnvCont fun ρ => closure (P ρ) where
  mono h := closure_mono (mono h)
  finite := by
    intro ρ t ⟨v, hv, ht⟩
    suffices h : ∃ X, Approximates X ρ ∧ ∀ s ∈ v, P (Env.approx X) s by
      obtain ⟨X, hX, hv'⟩ := h
      exact ⟨X, hX, v, hv', ht⟩
    clear ht
    induction v with
    | nil => exact ⟨fun _ => [], Approximates.nil ρ, fun _ h => absurd h List.not_mem_nil⟩
    | cons s v ih =>
      obtain ⟨X₁, h₁, hs⟩ := finite (hv s List.mem_cons_self)
      obtain ⟨X₂, h₂, hv₂⟩ := ih fun r hr => hv r (List.mem_cons_of_mem _ hr)
      refine ⟨approxJoin X₁ X₂, h₁.join h₂, fun r hr => ?_⟩
      rcases List.mem_cons.1 hr with rfl | hr
      · exact mono (approx_le_join_left X₁ X₂) _ hs
      · exact mono (approx_le_join_right X₁ X₂) _ (hv₂ r hr)

theorem var (i : Fin n) : EnvCont fun ρ => ρ i where
  mono h := h i
  finite {ρ t} ht := by
    refine ⟨fun j => if j = i then [t] else [], fun j => ?_, ?_⟩
    · by_cases h : j = i
      · subst h
        simp only [if_true]
        intro s hs
        rw [List.mem_singleton.1 hs]
        exact ht
      · simp only [h, if_false]
        exact fun _ hs => absurd hs List.not_mem_nil
    · show ent (if i = i then [t] else []) t = true
      simp only [if_true]
      exact ent_of_mem List.mem_cons_self

theorem const (K : Ideal) : EnvCont fun _ : Env n => K where
  mono _ := le_refl K
  finite {ρ _} ht := ⟨fun _ => [], Approximates.nil ρ, ht⟩

theorem comp {H : Ideal → Ideal} {K : Env n → Ideal} (hH : Cont H) (hK : EnvCont K) :
    EnvCont fun ρ => H (K ρ) where
  mono h := hH.mono (hK.mono h)
  finite := by
    intro ρ t ht
    obtain ⟨X, hX, ht'⟩ := hH.finite ht
    obtain ⟨Y, hY, hXY⟩ := hK.below hX
    exact ⟨Y, hY, hH.mono (principal_le_iff.2 hXY) _ ht'⟩

theorem comp₂ {H : Ideal → Ideal → Ideal} {K L : Env n → Ideal} (hH : Cont₂ H) (hK : EnvCont K)
    (hL : EnvCont L) : EnvCont fun ρ => H (K ρ) (L ρ) where
  mono h := hH.mono (hK.mono h) (hL.mono h)
  finite := by
    intro ρ t ht
    obtain ⟨X, hX, ht₁⟩ := (hH.left (L ρ)).finite ht
    obtain ⟨Y, hY, ht₂⟩ := (hH.right (principal X)).finite ht₁
    obtain ⟨X', hX', hXX'⟩ := hK.below hX
    obtain ⟨Y', hY', hYY'⟩ := hL.below hY
    refine ⟨approxJoin X' Y', hX'.join hY', hH.mono ?_ ?_ _ ht₂⟩
    · exact le_trans (principal_le_iff.2 hXX') (hK.mono (approx_le_join_left X' Y'))
    · exact le_trans (principal_le_iff.2 hYY') (hL.mono (approx_le_join_right X' Y'))

/-- Continuity in the newest variable, the others fixed. -/
theorem cons_left {B : Env (n + 1) → Ideal} (hB : EnvCont B) (ρ : Env n) :
    Cont fun y => B (Env.cons y ρ) where
  mono h := hB.mono (Env.Le.cons h (Env.Le.refl ρ))
  finite := by
    intro y t ht
    obtain ⟨X, hX, ht'⟩ := hB.finite ht
    refine ⟨X 0, hX 0, hB.mono (fun i => ?_) _ ht'⟩
    refine Fin.cases ?_ (fun j => ?_) i
    · exact le_refl _
    · exact principal_le_iff.2 (hX j.succ)

/-- Substituting a continuous value for the newest variable. -/
theorem subst_cons {B : Env (n + 1) → Ideal} {K : Env n → Ideal} (hB : EnvCont B)
    (hK : EnvCont K) : EnvCont fun ρ => B (Env.cons (K ρ) ρ) where
  mono h := hB.mono (Env.Le.cons (hK.mono h) h)
  finite := by
    intro ρ t ht
    obtain ⟨X, hX, ht'⟩ := hB.finite ht
    obtain ⟨Y, hY, hXY⟩ := hK.below (hX 0)
    refine ⟨approxJoin (fun i => X i.succ) Y,
      (show Approximates (fun i => X i.succ) ρ from fun i => hX i.succ).join hY,
      hB.mono (fun i => ?_) _ ht'⟩
    refine Fin.cases ?_ (fun j => ?_) i
    · exact le_trans (principal_le_iff.2 hXY) (hK.mono (approx_le_join_right _ Y))
    · exact approx_le_join_left (fun i => X i.succ) Y j

end EnvCont

end Domain
end Impredicative
end TypedEquality
end Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId.Presentation
