import Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId.TypedEquality.Impredicative.Domain.ChurchInterp

/-!
# The identity eliminator and numeral recursion as constants that carry their types

Two eliminators, each interpreted as a function projected onto its declared type
(`ChurchInterp`), and their computation rules validated in the domain.

**Numeral recursion** (`Ideal.natRec z step`) with zero case `z` and successor step
`step` is the union of its approximants, each unfolding the recursion once more
(`Ideal.natRecApprox`). For a continuous step:

* at zero it is the zero case, and at a successor one step at the predecessor
  (`Ideal.natRec_zeroI`, `Ideal.natRec_succI`); it is strict (`Ideal.natRec_bot`);
* it is continuous in the numeral, and in any parameter the zero case and the step
  depend on continuously (`Ideal.cont_natRec`, `Ideal.cont_natRec_param`).

**The identity eliminator** `J : Π (A : U) (x : A) (P : Π (y : A). Id A x y → U).
P x (refl x) → Π (y : A) (p : Id A x y). P y p` is the function "the method when the
path is a reflexivity" (`Ideal.jRaw`) projected onto its declared type (`jConst`).
**Its linear rule is valid** (`jConst_linear`): at a spine `J A x P d y (refl a)`
with spine facts at `τ`, if the method `d` is an element of `τ`, the spine denotes
`d`. No equation between `a`, `x` and `y` is assumed: the argument projections are
the identity by the spine facts, and the value's projection onto `τ` is the identity
because the method is an element of `τ`.

**The recursor** `num-rec : Π (P : num → U). P zero → (Π (v : num). P v → P (suc v)) →
Π (t : num). P t` is numeral recursion whose step projects the recursive value onto
the motive at the predecessor (`Ideal.nrStep`), curried and projected onto the
declared type (`nrConst`). With the successor constant (`sucConst`, the successor
projected onto `num → num`), **both computation rules are valid**
(`nrConst_iotaZero`, `nrConst_iotaSucc`): at a spine with spine facts at `τ` whose
contractum is an element of `τ`, the spine denotes the contractum. The recursive
call of the successor rule's contractum is the recursor itself, whose projections
the step reproduces.

**The decoder of proposition codes** (`Ideal.holdsConst`, the identity on codes
projected onto `prop → U`), **implication** (`Ideal.impConst`) and **the equation code
at a carrier** (`Ideal.eqConst`) are each projected onto their declared types. The
decoding of an implication is valid with no hypothesis (`Ideal.decode_impConst`). The
decoding of an equation, `holds (eq@A x y) ⟶ Id A x y`, is valid whenever the
contractum is a type (`Ideal.decode_eqConst`): an identity type generated by its type
tokens has its endpoints in its carrier (`Ideal.typeGenerated_ident_endpoints`).
-/

set_option autoImplicit false

namespace Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId.Presentation
namespace TypedEquality
namespace Impredicative
namespace Domain

open Annotated (CTm)

namespace Ideal

/-! ## Numbers -/

/-- The type of numbers. -/
def natI : Ideal := principal Elem.nat

/-- Zero. -/
def zeroI : Ideal := principal Elem.zero

theorem zeroI_mem_zero : zeroI.Mem (.tag .zero) := ent_of_mem List.mem_cons_self

theorem zeroI_not_mem_succ : ¬ zeroI.Mem (.tag .succ) := by
  intro h
  change ent Elem.zero (.tag .succ) = true at h
  simp [ent_tag, hasTag, Elem.zero] at h

theorem bot_not_mem_tag {κ : Type} [DecidableEq κ] (k : κ) : ¬ (bot : Ideal κ).Mem (.tag k) := by
  intro h
  change ent [] (.tag k) = true at h
  simp [ent_tag, hasTag] at h

theorem refl_mem_tag (a : Ideal) : (refl a).Mem (.tag .refl) := subset_closure (.inl rfl)

theorem nat_type : Ty Elem.nat Elem.univ := Elem.ty_tag (k := .nat) trivial Elem.isUniv_univ

theorem below_nat : Below Elem.nat natI := fun _ ht => ent_of_mem ht

/-- A token typed at a compact type below the numbers is typed at the numbers. -/
theorem tyTok_nat_of_typedAt {t : Tok} (h : TypedAt natI t) : TyTok Elem.nat t := by
  obtain ⟨a, ha, -, hat⟩ := h
  exact hat.mono ha

theorem projT_natI_zeroI : projT natI zeroI = zeroI :=
  projT_principal_eq below_nat nat_type (Elem.ty_zero List.mem_cons_self)

/-- The successor of a number is a number. -/
theorem projT_natI_succI {m : Ideal} (h : projT natI m = m) : projT natI (succI m) = succI m := by
  unfold succI
  refine projT_closure_eq fun g hg => ?_
  rcases hg with rfl | ⟨s, rfl, hs⟩
  · exact ⟨[.tag .succ], fun r hr => by
      rw [List.mem_singleton.1 hr]
      exact ⟨subset_closure (.inl rfl), Elem.nat, below_nat, nat_type,
        tyTok_tag_succ.2 List.mem_cons_self⟩, ent_of_mem List.mem_cons_self⟩
  · rw [← h] at hs
    obtain ⟨v, hv, hsv⟩ := hs
    refine ⟨v.map (.arg .succ 0 []), fun r hr => ?_, ?_⟩
    · obtain ⟨r', hr', rfl⟩ := List.mem_map.1 hr
      exact ⟨subset_closure (.inr ⟨r', rfl, (hv r' hr').1⟩), Elem.nat, below_nat, nat_type,
        tyTok_pred.2 ⟨List.mem_cons_self, rfl, tyTok_nat_of_typedAt (hv r' hr').2⟩⟩
    · rw [ent_arg, List.all_nil, Bool.true_and, args_map_arg_same]
      exact hsv

/-! ## Numeral recursion -/

/-- The approximants of numeral recursion with zero case `z` and successor step
`step`: the `k`-th unfolds the recursion `k` times. -/
def natRecApprox (z : Ideal) (step : Ideal → Ideal → Ideal) : Nat → Ideal → Ideal
  | 0, _ => bot
  | k + 1, ν => join (whenTag .zero ν z)
      (whenTag .succ ν (step (predI ν) (natRecApprox z step k (predI ν))))

/-- **Numeral recursion**: the union of the approximants. -/
def natRec (z : Ideal) (step : Ideal → Ideal → Ideal) (ν : Ideal) : Ideal :=
  closure fun t => ∃ k, (natRecApprox z step k ν).Mem t

section NatRec

variable {z : Ideal} {step : Ideal → Ideal → Ideal}

theorem natRecApprox_le_succ (hstep : Cont₂ step) :
    ∀ (k : Nat) (ν : Ideal), natRecApprox z step k ν ≤ natRecApprox z step (k + 1) ν
  | 0, _ => bot_le _
  | k + 1, ν => by
      show join _ _ ≤ join _ _
      exact cont₂_join.mono (le_refl _) (((cont₂_whenTag .succ).right ν).mono
        ((hstep.right _).mono (natRecApprox_le_succ hstep k _)))

theorem natRecApprox_mono (hstep : Cont₂ step) {k k' : Nat} (h : k ≤ k') (ν : Ideal) :
    natRecApprox z step k ν ≤ natRecApprox z step k' ν := by
  induction h with
  | refl => exact le_refl _
  | step _ ih => exact le_trans ih (natRecApprox_le_succ hstep _ ν)

/-- Finitely many tokens of the approximants are tokens of one approximant. -/
theorem natRecApprox_bound (hstep : Cont₂ step) {ν : Ideal} :
    ∀ {v : List Tok}, (∀ s ∈ v, ∃ k, (natRecApprox z step k ν).Mem s) →
      ∃ K, Below v (natRecApprox z step K ν)
  | [], _ => ⟨0, fun _ h => absurd h List.not_mem_nil⟩
  | s :: v, h => by
      obtain ⟨k₁, h₁⟩ := h s List.mem_cons_self
      obtain ⟨k₂, h₂⟩ := natRecApprox_bound hstep (v := v) fun r hr =>
        h r (List.mem_cons_of_mem _ hr)
      refine ⟨max k₁ k₂, fun r hr => ?_⟩
      rcases List.mem_cons.1 hr with rfl | hr
      · exact natRecApprox_mono hstep (Nat.le_max_left _ _) ν _ h₁
      · exact natRecApprox_mono hstep (Nat.le_max_right _ _) ν _ (h₂ r hr)

theorem mem_natRec (hstep : Cont₂ step) {ν : Ideal} {t : Tok} :
    (natRec z step ν).Mem t ↔ ∃ k, (natRecApprox z step k ν).Mem t := by
  constructor
  · rintro ⟨v, hv, ht⟩
    obtain ⟨K, hK⟩ := natRecApprox_bound hstep hv
    exact ⟨K, (natRecApprox z step K ν).closed hK ht⟩
  · intro h
    exact subset_closure h

theorem natRecApprox_le_natRec (k : Nat) (ν : Ideal) :
    natRecApprox z step k ν ≤ natRec z step ν :=
  fun _ ht => subset_closure ⟨k, ht⟩

theorem below_natRec (hstep : Cont₂ step) {ν : Ideal} {X : List Tok}
    (h : Below X (natRec z step ν)) : ∃ K, Below X (natRecApprox z step K ν) :=
  natRecApprox_bound hstep fun s hs => (mem_natRec hstep).1 (h s hs)

theorem natRecApprox_zeroI (k : Nat) : natRecApprox z step (k + 1) zeroI = z := by
  rw [natRecApprox, whenTag_of_mem zeroI_mem_zero, whenTag_of_not_mem zeroI_not_mem_succ, join_bot]

/-- **Numeral recursion at zero is the zero case.** -/
theorem natRec_zeroI (hstep : Cont₂ step) : natRec z step zeroI = z := by
  apply le_antisymm
  · intro t ht
    obtain ⟨k, hk⟩ := (mem_natRec hstep).1 ht
    cases k with
    | zero => exact bot_le z t hk
    | succ k => rwa [natRecApprox_zeroI] at hk
  · intro t ht
    exact subset_closure ⟨1, by rw [natRecApprox_zeroI]; exact ht⟩

theorem natRecApprox_succI (k : Nat) (m : Ideal) :
    natRecApprox z step (k + 1) (succI m) = step m (natRecApprox z step k m) := by
  rw [natRecApprox, whenTag_of_not_mem (succI_not_mem_tag (by decide) m),
    whenTag_of_mem (succI_mem_succ m), predI_succI, bot_join]

/-- **Numeral recursion at a successor is one step at the predecessor.** -/
theorem natRec_succI (hstep : Cont₂ step) (m : Ideal) :
    natRec z step (succI m) = step m (natRec z step m) := by
  apply le_antisymm
  · intro t ht
    obtain ⟨k, hk⟩ := (mem_natRec hstep).1 ht
    cases k with
    | zero => exact bot_le _ t hk
    | succ k =>
      rw [natRecApprox_succI] at hk
      exact (hstep.right m).mono (natRecApprox_le_natRec k m) t hk
  · intro t ht
    obtain ⟨X, hX, ht'⟩ := (hstep.right m).finite ht
    obtain ⟨K, hK⟩ := below_natRec hstep hX
    refine subset_closure ⟨K + 1, ?_⟩
    rw [natRecApprox_succI]
    exact (hstep.right m).mono (principal_le_iff.2 hK) t ht'

/-- **Numeral recursion is strict.** -/
theorem natRec_bot (hstep : Cont₂ step) : natRec z step bot = bot := by
  refine le_antisymm (fun t ht => ?_) (bot_le _)
  obtain ⟨k, hk⟩ := (mem_natRec hstep).1 ht
  cases k with
  | zero => exact hk
  | succ k =>
    rw [natRecApprox, whenTag_of_not_mem (bot_not_mem_tag _),
      whenTag_of_not_mem (bot_not_mem_tag _), join_bot] at hk
    exact hk

theorem cont_natRecApprox (hstep : Cont₂ step) : ∀ k, Cont (natRecApprox z step k)
  | 0 => by
      show Cont fun _ => bot
      exact Cont.const bot
  | k + 1 => by
      show Cont fun ν => join (whenTag .zero ν z)
        (whenTag .succ ν (step (predI ν) (natRecApprox z step k (predI ν))))
      exact cont₂_join.comp ((cont₂_whenTag .zero).left z)
        ((cont₂_whenTag .succ).comp Cont.id
          (hstep.comp cont_predI ((cont_natRecApprox hstep k).comp cont_predI)))

/-- Numeral recursion is continuous in the numeral. -/
theorem cont_natRec (hstep : Cont₂ step) : Cont (natRec z step) :=
  Cont.of_closure (P := fun ν t => ∃ k, (natRecApprox z step k ν).Mem t)
    (fun h t ⟨k, hk⟩ => ⟨k, (cont_natRecApprox hstep k).mono h t hk⟩)
    fun {_ _} ⟨k, hk⟩ => by
      obtain ⟨X, hX, hX'⟩ := (cont_natRecApprox hstep k).finite hk
      exact ⟨X, hX, k, hX'⟩

end NatRec

section Param

variable {Z : Ideal → Ideal} {S : Ideal → Ideal → Ideal → Ideal}

theorem cont_natRecApprox_param (hZ : Cont Z) (hS : ∀ m r, Cont fun w => S w m r)
    (hS₂ : ∀ w, Cont₂ (S w)) :
    ∀ (k : Nat) (ν : Ideal), Cont fun w => natRecApprox (Z w) (S w) k ν
  | 0, _ => Cont.const bot
  | k + 1, ν => by
      have hS' : Cont₂ fun w r => S w (predI ν) r :=
        ⟨fun r => hS (predI ν) r, fun w => (hS₂ w).right (predI ν)⟩
      show Cont fun w => join (whenTag .zero ν (Z w))
        (whenTag .succ ν (S w (predI ν) (natRecApprox (Z w) (S w) k (predI ν))))
      exact cont₂_join.comp (((cont₂_whenTag .zero).right ν).comp hZ)
        (((cont₂_whenTag .succ).right ν).comp
          (hS'.comp Cont.id (cont_natRecApprox_param hZ hS hS₂ k (predI ν))))

/-- Numeral recursion is continuous in a parameter its zero case and step depend on
continuously. -/
theorem cont_natRec_param (hZ : Cont Z) (hS : ∀ m r, Cont fun w => S w m r)
    (hS₂ : ∀ w, Cont₂ (S w)) (ν : Ideal) : Cont fun w => natRec (Z w) (S w) ν :=
  Cont.of_closure (P := fun w t => ∃ k, (natRecApprox (Z w) (S w) k ν).Mem t)
    (fun h t ⟨k, hk⟩ => ⟨k, (cont_natRecApprox_param hZ hS hS₂ k ν).mono h t hk⟩)
    fun {_ _} ⟨k, hk⟩ => by
      obtain ⟨X, hX, hX'⟩ := (cont_natRecApprox_param hZ hS hS₂ k ν).finite hk
      exact ⟨X, hX, k, hX'⟩

end Param

/-! ## The functions of the eliminators -/

/-- The function of the identity eliminator: the method when the path is a
reflexivity. -/
def jRaw : Ideal :=
  lam fun _ => lam fun _ => lam fun _ => lam fun D => lam fun _ => lam fun Q =>
    whenTag .refl (principal Q) (principal D)

theorem appSpine_jRaw (α ξ π δ η p : Ideal) :
    appSpine jRaw [α, ξ, π, δ, η, p] = whenTag .refl p δ := by
  have hD : Cont fun d => lam fun _ => lam fun Q => whenTag .refl (principal Q) d :=
    cont_lam_param fun _ => cont_lam_param fun Q => (cont₂_whenTag .refl).right (principal Q)
  have e : app (lam fun D => lam fun _ => lam fun Q => whenTag .refl (principal Q) (principal D)) δ =
      lam fun _ => lam fun Q => whenTag .refl (principal Q) δ :=
    app_lam_principal hD δ
  have e' : app (lam fun Q => whenTag .refl (principal Q) δ) p = whenTag .refl p δ :=
    app_lam_principal ((cont₂_whenTag .refl).left δ) p
  show app (app (app (app (app (app jRaw α) ξ) π) δ) η) p = _
  unfold jRaw
  rw [app_lam_const, app_lam_const, app_lam_const, e, app_lam_const, e']

/-- The successor step of the recursor: the method at the predecessor and the
recursive value projected onto the motive at the predecessor. -/
def nrStep (π σ m r : Ideal) : Ideal := app (app σ m) (projT (app π m) r)

theorem cont₂_nrStep (π σ : Ideal) : Cont₂ (nrStep π σ) where
  left r := cont₂_app.comp (cont₂_app.right σ) (cont₂_projT.comp (cont₂_app.right π) (Cont.const r))
  right m := (cont₂_app.right (app σ m)).comp (cont_projT (app π m))

theorem cont_nrStep_motive (σ m r : Ideal) : Cont fun π => nrStep π σ m r :=
  (cont₂_app.right (app σ m)).comp ((cont_projT_type r).comp (cont₂_app.left m))

theorem cont_nrStep_method (π m r : Ideal) : Cont fun σ => nrStep π σ m r :=
  (cont₂_app.left (projT (app π m) r)).comp (cont₂_app.left m)

/-- The function of the recursor: numeral recursion, curried. -/
def nrRaw : Ideal :=
  lam fun P => lam fun Z => lam fun S => lam fun N =>
    natRec (principal Z) (nrStep (principal P) (principal S)) (principal N)

theorem appSpine_nrRaw (π ζ σ ν : Ideal) :
    appSpine nrRaw [π, ζ, σ, ν] = natRec ζ (nrStep π σ) ν := by
  have h₁ : Cont fun p => lam fun Z => lam fun S => lam fun N =>
      natRec (principal Z) (nrStep p (principal S)) (principal N) :=
    cont_lam_param fun Z => cont_lam_param fun S => cont_lam_param fun N =>
      cont_natRec_param (Z := fun _ => principal Z) (S := fun p => nrStep p (principal S))
        (Cont.const _) (fun m r => cont_nrStep_motive _ m r) (fun p => cont₂_nrStep p _)
        (principal N)
  have h₂ : Cont fun z' => lam fun S => lam fun N =>
      natRec z' (nrStep π (principal S)) (principal N) :=
    cont_lam_param fun S => cont_lam_param fun N =>
      cont_natRec_param (Z := fun z' => z') (S := fun _ => nrStep π (principal S))
        Cont.id (fun _ _ => Cont.const _) (fun _ => cont₂_nrStep π _) (principal N)
  have h₃ : Cont fun s => lam fun N => natRec ζ (nrStep π s) (principal N) :=
    cont_lam_param fun N =>
      cont_natRec_param (Z := fun _ => ζ) (S := fun s => nrStep π s)
        (Cont.const _) (fun m r => cont_nrStep_method π m r) (fun s => cont₂_nrStep π s)
        (principal N)
  have e₁ : app nrRaw π = lam fun Z => lam fun S => lam fun N =>
      natRec (principal Z) (nrStep π (principal S)) (principal N) :=
    app_lam_principal h₁ π
  have e₂ : app (lam fun Z => lam fun S => lam fun N =>
      natRec (principal Z) (nrStep π (principal S)) (principal N)) ζ =
        lam fun S => lam fun N => natRec ζ (nrStep π (principal S)) (principal N) :=
    app_lam_principal h₂ ζ
  have e₃ : app (lam fun S => lam fun N => natRec ζ (nrStep π (principal S)) (principal N)) σ =
      lam fun N => natRec ζ (nrStep π σ) (principal N) :=
    app_lam_principal h₃ σ
  have e₄ : app (lam fun N => natRec ζ (nrStep π σ) (principal N)) ν = natRec ζ (nrStep π σ) ν :=
    app_lam_principal (cont_natRec (cont₂_nrStep π σ)) ν
  show app (app (app (app nrRaw π) ζ) σ) ν = _
  rw [e₁, e₂, e₃, e₄]

/-- The function of the successor. -/
def sucRaw : Ideal := lam fun X => succI (principal X)

end Ideal

open Ideal

variable {Head : Type}

/-! ## The identity eliminator -/

/-- The declared type of the identity eliminator, with the universe `U` the head `u`:
`Π (A : U) (x : A) (P : Π (y : A). Id A x y → U). P x (refl x) →
Π (y : A) (p : Id A x y). P y p`. -/
def jTypeC (u : Head) : CTm Head 0 :=
  .pi (.head u) (.pi (.var 0) (.pi (.pi (.var 1) (.pi (.id (.var 2) (.var 1) (.var 0)) (.head u)))
    (.pi (.app (.app (.var 0) (.var 1)) (.refl (.var 1)))
      (.pi (.var 3) (.pi (.id (.var 4) (.var 3) (.var 0)) (.app (.app (.var 3) (.var 1)) (.var 0)))))))

/-- The declared type of the identity eliminator, interpreted. -/
abbrev jTypeI (Rd : Reading Head) (u : Head) : Ideal := cinterp Rd (jTypeC u) Env.nil

/-- **The identity eliminator**: its function projected onto its declared type. -/
def jConst (Rd : Reading Head) (u : Head) : Ideal := projT (jTypeI Rd u) jRaw

/-- The declared type of the eliminator instantiated at a spine with spine facts is
the motive at the endpoint and the path. -/
theorem instPi_jType {Rd : Reading Head} {u : Head} {α ξ π δ η p : Ideal}
    (spine : SpineTyped (jTypeI Rd u) [α, ξ, π, δ, η, p]) :
    instPi (jTypeI Rd u) [α, ξ, π, δ, η, p] = app (app π η) p := by
  obtain ⟨h1, s1⟩ := (spineTyped_cinterp_pi Rd _ _ _ _ _).1 spine
  obtain ⟨h2, s2⟩ := (spineTyped_cinterp_pi Rd _ _ _ _ _).1 s1
  obtain ⟨h3, s3⟩ := (spineTyped_cinterp_pi Rd _ _ _ _ _).1 s2
  obtain ⟨h4, s4⟩ := (spineTyped_cinterp_pi Rd _ _ _ _ _).1 s3
  obtain ⟨h5, s5⟩ := (spineTyped_cinterp_pi Rd _ _ _ _ _).1 s4
  obtain ⟨h6, -⟩ := (spineTyped_cinterp_pi Rd _ _ _ _ _).1 s5
  exact (instPi_cinterp_pi_of Rd _ h1).trans ((instPi_cinterp_pi_of Rd _ h2).trans
    ((instPi_cinterp_pi_of Rd _ h3).trans ((instPi_cinterp_pi_of Rd _ h4).trans
      ((instPi_cinterp_pi_of Rd _ h5).trans ((instPi_cinterp_pi_of Rd [] h6).trans rfl)))))

/-- **The linear rule of the identity eliminator is valid.** At a spine
`J A x P d y (refl a)` with spine facts at `τ`, if the method is an element of `τ`,
the spine denotes the method. -/
theorem jConst_linear (Rd : Reading Head) (u : Head) {α ξ π δ η a τ : Ideal}
    (facts : SpineFacts (jTypeI Rd u) [α, ξ, π, δ, η, Ideal.refl a] τ) (right : projT τ δ = δ) :
    appSpine (jConst Rd u) [α, ξ, π, δ, η, Ideal.refl a] = δ := by
  obtain ⟨rfl, spine⟩ := facts
  exact churchConst_root (churchTele_cinterp Rd (jTypeC u) Env.nil) (Nat.le_refl _) spine
    (by rw [appSpine_jRaw, whenTag_of_mem (refl_mem_tag a)]) right

/-! ## Numeral recursion -/

/-- The names the declared type of numeral recursion refers to. -/
structure NumNames (Head : Type) where
  /-- The universe of the motive. -/
  univ : Head
  num : DeclName
  zero : DeclName
  suc : DeclName

/-- The type of the successor method, `Π (v : num). P v → P (suc v)`, over the motive
and the zero case. -/
def nrStepTypeC (N : NumNames Head) : CTm Head 2 :=
  .pi (.const N.num) (.pi (.app (.var 2) (.var 0)) (.app (.var 3) (.app (.const N.suc) (.var 1))))

/-- The declared type of numeral recursion,
`Π (P : num → U). P zero → (Π (v : num). P v → P (suc v)) → Π (t : num). P t`. -/
def nrTypeC (N : NumNames Head) : CTm Head 0 :=
  .pi (.pi (.const N.num) (.head N.univ)) (.pi (.app (.var 0) (.const N.zero))
    (.pi (nrStepTypeC N) (.pi (.const N.num) (.app (.var 3) (.var 0)))))

/-- The declared type of numeral recursion, interpreted. -/
abbrev nrTypeI (Rd : Reading Head) (N : NumNames Head) : Ideal := cinterp Rd (nrTypeC N) Env.nil

/-- **The recursor**: numeral recursion, curried, projected onto its declared type. -/
def nrConst (Rd : Reading Head) (N : NumNames Head) : Ideal := projT (nrTypeI Rd N) nrRaw

/-- The declared type of the successor, `num → num`. -/
def sucTypeC (N : NumNames Head) : CTm Head 0 := .pi (.const N.num) (.const N.num)

/-- **The successor**: its function projected onto its declared type. -/
def sucConst (Rd : Reading Head) (N : NumNames Head) : Ideal :=
  projT (cinterp Rd (sucTypeC N) Env.nil) sucRaw

/-- **Zero**: its value projected onto its declared type. -/
def zeroConst (Rd : Reading Head) (N : NumNames Head) : Ideal := projT (Rd.const N.num) zeroI

section Numbers

variable (Rd : Reading Head) (N : NumNames Head)

theorem zeroConst_eq (hnum : Rd.const N.num = natI) : zeroConst Rd N = zeroI := by
  rw [zeroConst, hnum, projT_natI_zeroI]

/-- The successor constant applied is the successor of the projected argument. -/
theorem app_sucConst (hnum : Rd.const N.num = natI) (ν : Ideal) :
    app (sucConst Rd N) ν = succI (projT natI ν) := by
  have hT : cinterp Rd (sucTypeC N) Env.nil = cpi natI fun _ => natI := by
    show cpi (Rd.const N.num) (fun _ => Rd.const N.num) = _
    rw [hnum]
  unfold sucConst
  rw [hT, app_projT_cpi (Cont.const natI), sucRaw, app_lam_principal cont_succI]
  exact projT_natI_succI (projT_projT _ _)

variable {Rd N}

/-- The spine facts of the first three arguments of the recursor: the motive, the
zero case and the successor method are elements of their parameter types. -/
theorem nr_prefix {π ζ σ : Ideal} (h : SpineTyped (nrTypeI Rd N) [π, ζ, σ]) :
    projT (cinterp Rd (.pi (.const N.num) (.head N.univ)) Env.nil) π = π ∧
    projT (cinterp Rd (.app (.var 0) (.const N.zero)) (Env.cons π Env.nil)) ζ = ζ ∧
    projT (cinterp Rd (nrStepTypeC N) (Env.cons ζ (Env.cons π Env.nil))) σ = σ := by
  unfold nrTypeI nrTypeC at h
  rw [spineTyped_cinterp_pi] at h
  obtain ⟨hπ, h⟩ := h
  rw [spineTyped_cinterp_pi] at h
  obtain ⟨hζ, h⟩ := h
  rw [spineTyped_cinterp_pi] at h
  exact ⟨hπ, hζ, h.1⟩

/-- The declared type of the recursor instantiated at typed first arguments: the
motive at the projected numeral. -/
theorem instPi_nr {π ζ σ : Ideal} (h : SpineTyped (nrTypeI Rd N) [π, ζ, σ]) (x : Ideal) :
    instPi (nrTypeI Rd N) [π, ζ, σ, x] = app π (projT (Rd.const N.num) x) := by
  obtain ⟨hπ, hζ, hσ⟩ := nr_prefix h
  unfold nrTypeI nrTypeC
  rw [instPi_cinterp_pi, hπ, instPi_cinterp_pi, hζ, instPi_cinterp_pi, hσ, instPi_cinterp_pi]
  rfl

theorem projArgs_nr {π ζ σ : Ideal} (h : SpineTyped (nrTypeI Rd N) [π, ζ, σ]) (x : Ideal) :
    projArgs (nrTypeI Rd N) [π, ζ, σ, x] = [π, ζ, σ, projT (Rd.const N.num) x] := by
  obtain ⟨hπ, hζ, hσ⟩ := nr_prefix h
  unfold nrTypeI nrTypeC
  rw [projArgs_cinterp_pi, hπ, projArgs_cinterp_pi, hζ, projArgs_cinterp_pi, hσ,
    projArgs_cinterp_pi]
  rfl

/-- The recursor applied to typed first arguments: numeral recursion at the projected
numeral, projected onto the motive there. -/
theorem appSpine_nrConst {π ζ σ : Ideal} (h : SpineTyped (nrTypeI Rd N) [π, ζ, σ])
    (hnum : Rd.const N.num = natI) (x : Ideal) :
    appSpine (nrConst Rd N) [π, ζ, σ, x] =
      projT (app π (projT natI x)) (natRec ζ (nrStep π σ) (projT natI x)) := by
  unfold nrConst
  rw [appSpine_projT nrRaw (churchTele_cinterp Rd (nrTypeC N) Env.nil) (Nat.le_refl _),
    projArgs_nr h, instPi_nr h, appSpine_nrRaw, hnum]

/-- **The zero rule of the recursor is valid**: at a spine `num-rec P z s zero` with
spine facts at `τ`, if the zero case is an element of `τ`, the spine denotes it. -/
theorem nrConst_iotaZero {π ζ σ τ : Ideal} (facts : SpineFacts (nrTypeI Rd N) [π, ζ, σ, zeroI] τ)
    (right : projT τ ζ = ζ) : appSpine (nrConst Rd N) [π, ζ, σ, zeroI] = ζ := by
  obtain ⟨rfl, spine⟩ := facts
  exact churchConst_root (churchTele_cinterp Rd (nrTypeC N) Env.nil) (Nat.le_refl _) spine
    (by rw [appSpine_nrRaw, natRec_zeroI (cont₂_nrStep π σ)]) right

/-- **The successor rule of the recursor is valid**: at a spine
`num-rec P z s (suc n)` with spine facts at `τ`, if the contractum
`s n (num-rec P z s n)` is an element of `τ`, the spine denotes it. -/
theorem nrConst_iotaSucc (hnum : Rd.const N.num = natI) {π ζ σ ν τ : Ideal}
    (facts : SpineFacts (nrTypeI Rd N) [π, ζ, σ, app (sucConst Rd N) ν] τ)
    (right : projT τ (app (app σ ν) (appSpine (nrConst Rd N) [π, ζ, σ, ν])) =
      app (app σ ν) (appSpine (nrConst Rd N) [π, ζ, σ, ν])) :
    appSpine (nrConst Rd N) [π, ζ, σ, app (sucConst Rd N) ν] =
      app (app σ ν) (appSpine (nrConst Rd N) [π, ζ, σ, ν]) := by
  obtain ⟨rfl, spine⟩ := facts
  have pre : SpineTyped (nrTypeI Rd N) [π, ζ, σ] :=
    ((spineTyped_append (args := [π, ζ, σ]) (args' := [app (sucConst Rd N) ν])).1 spine).1
  obtain ⟨-, -, hσ⟩ := nr_prefix pre
  have hσ' : app σ (projT natI ν) = app σ ν := by
    rw [← hnum]
    exact app_projT_arg (cinterp_cont_cons Rd _ _) hσ ν
  refine churchConst_root (churchTele_cinterp Rd (nrTypeC N) Env.nil) (Nat.le_refl _) spine ?_ right
  rw [appSpine_nrRaw, app_sucConst Rd N hnum, natRec_succI (cont₂_nrStep π σ),
    appSpine_nrConst pre hnum, nrStep, hσ']

end Numbers

/-! ## The decoder at implication and equation codes -/

namespace Ideal

/-- The components of the generators of an identity type are in its carrier and
endpoints. -/
private theorem ident_gen_args {A I J : Ideal} {w : List Tok}
    (hw : ∀ s ∈ w, s = .tag .ident ∨ (∃ d, s = .arg .ident 0 [] d ∧ A.Mem d) ∨
      (∃ C r, s = .arg .ident 1 C r ∧ Below C A ∧ I.Mem r) ∨
      ∃ C r, s = .arg .ident 2 C r ∧ Below C A ∧ J.Mem r) :
    Below (args .ident 0 w) A ∧ Below (args .ident 1 w) I ∧ Below (args .ident 2 w) J := by
  refine ⟨fun c hc => ?_, fun c hc => ?_, fun c hc => ?_⟩
  · rcases mem_args_iff.1 hc with ⟨C, hC⟩ | ⟨-, t, ht, -, hd⟩
    · rcases hw _ hC with h | ⟨d, h, hd⟩ | ⟨C', r, h, -, -⟩ | ⟨C', r, h, -, -⟩
      · cases h
      · cases h
        exact hd
      · simp at h
      · simp at h
    · rcases hw _ ht with rfl | ⟨d, rfl, -⟩ | ⟨C', r, rfl, hC', -⟩ | ⟨C', r, rfl, hC', -⟩
      · simp [Tok.dep] at hd
      · simp [Tok.dep] at hd
      · exact hC' c hd
      · exact hC' c hd
  · rcases mem_args_iff.1 hc with ⟨C, hC⟩ | ⟨h1, -⟩
    · rcases hw _ hC with h | ⟨d, h, -⟩ | ⟨C', r, h, -, hr⟩ | ⟨C', r, h, -, -⟩
      · cases h
      · simp at h
      · simp only [Tok.arg.injEq, true_and] at h
        obtain ⟨-, rfl⟩ := h
        exact hr
      · simp at h
    · simp at h1
  · rcases mem_args_iff.1 hc with ⟨C, hC⟩ | ⟨h2, -⟩
    · rcases hw _ hC with h | ⟨d, h, -⟩ | ⟨C', r, h, -, -⟩ | ⟨C', r, h, -, hr⟩
      · cases h
      · simp at h
      · simp at h
      · simp only [Tok.arg.injEq, true_and] at h
        obtain ⟨-, rfl⟩ := h
        exact hr
    · simp at h2

/-- An endpoint token of an identity type has its dependency in the carrier and its
component in the endpoint. -/
theorem mem_ident_arg {A I J : Ideal} {i : Nat} {C : List Tok} {s : Tok}
    (h : (ident A I J).Mem (.arg .ident i C s)) :
    Below C A ∧ (i = 1 → I.Mem s) ∧ (i = 2 → J.Mem s) := by
  obtain ⟨w, hw, h⟩ := h
  rw [ent_arg, Bool.and_eq_true, List.all_eq_true] at h
  obtain ⟨h0, h1, h2⟩ := ident_gen_args hw
  refine ⟨fun c hc => A.closed h0 (h.1 c hc), ?_, ?_⟩
  · rintro rfl
    exact I.closed h1 h.2
  · rintro rfl
    exact J.closed h2 h.2

/-- **An identity type generated by its type tokens has its endpoints in its
carrier.** -/
theorem typeGenerated_ident_endpoints {A I J : Ideal} (hG : TypeGenerated (ident A I J)) :
    projT A I = I ∧ projT A J = J := by
  have key : ∀ {i : Nat} {K : Ideal}, (i = 1 ∨ i = 2) →
      (∀ {s : Tok}, K.Mem s → (ident A I J).Mem (.arg .ident i [] s)) →
      (∀ {C : List Tok} {s : Tok}, (ident A I J).Mem (.arg .ident i C s) → K.Mem s) →
      projT A K = K := by
    intro i K hi hmem hback
    refine le_antisymm (projT_le _ _) fun t ht => ?_
    obtain ⟨v, hv, hent⟩ := hG _ (hmem ht)
    rw [ent_arg, List.all_nil, Bool.true_and] at hent
    refine (projT A K).closed (v := args .ident i v) (fun c hc => ?_) hent
    rcases mem_args_iff.1 hc with ⟨C, hC⟩ | ⟨h0, -⟩
    · obtain ⟨hm, hty⟩ := hv _ hC
      obtain ⟨-, hCty, hc'⟩ := (tyTok_endpoint hi).1 hty
      exact subset_closure ⟨hback hm, C, (mem_ident_arg hm).1, hCty, hc'⟩
    · rcases hi with rfl | rfl <;> simp at h0
  exact ⟨key (.inl rfl)
      (fun hs => subset_closure (.inr (.inr (.inl ⟨[], _, rfl, fun _ h => absurd h List.not_mem_nil, hs⟩))))
      (fun h => (mem_ident_arg h).2.1 rfl),
    key (.inr rfl)
      (fun hs => subset_closure (.inr (.inr (.inr ⟨[], _, rfl, fun _ h => absurd h List.not_mem_nil, hs⟩))))
      (fun h => (mem_ident_arg h).2.2 rfl)⟩

theorem cont_ident_left (A J : Ideal) : Cont fun z => ident A z J :=
  Cont.of_closure (P := fun z t => t = .tag .ident ∨ (∃ d, t = .arg .ident 0 [] d ∧ A.Mem d) ∨
      (∃ C s, t = .arg .ident 1 C s ∧ Below C A ∧ z.Mem s) ∨
      ∃ C s, t = .arg .ident 2 C s ∧ Below C A ∧ J.Mem s)
    (fun h _ ht => ht.imp_right (Or.imp_right (Or.imp_left
      fun ⟨C, s, e, hC, hs⟩ => ⟨C, s, e, hC, h s hs⟩)))
    fun {_ _} ht => by
      rcases ht with rfl | ⟨d, rfl, hd⟩ | ⟨C, s, rfl, hC, hs⟩ | ⟨C, s, rfl, hC, hs⟩
      · exact ⟨[], fun _ h => absurd h List.not_mem_nil, .inl rfl⟩
      · exact ⟨[], fun _ h => absurd h List.not_mem_nil, .inr (.inl ⟨d, rfl, hd⟩)⟩
      · exact ⟨[s], fun r hr => by rw [List.mem_singleton.1 hr]; exact hs,
          .inr (.inr (.inl ⟨C, s, rfl, hC, ent_of_mem List.mem_cons_self⟩))⟩
      · exact ⟨[], fun _ h => absurd h List.not_mem_nil, .inr (.inr (.inr ⟨C, s, rfl, hC, hs⟩))⟩

theorem cont_ident_right (A I : Ideal) : Cont fun z => ident A I z :=
  Cont.of_closure (P := fun z t => t = .tag .ident ∨ (∃ d, t = .arg .ident 0 [] d ∧ A.Mem d) ∨
      (∃ C s, t = .arg .ident 1 C s ∧ Below C A ∧ I.Mem s) ∨
      ∃ C s, t = .arg .ident 2 C s ∧ Below C A ∧ z.Mem s)
    (fun h _ ht => ht.imp_right (Or.imp_right (Or.imp_right
      fun ⟨C, s, e, hC, hs⟩ => ⟨C, s, e, hC, h s hs⟩)))
    fun {_ _} ht => by
      rcases ht with rfl | ⟨d, rfl, hd⟩ | ⟨C, s, rfl, hC, hs⟩ | ⟨C, s, rfl, hC, hs⟩
      · exact ⟨[], fun _ h => absurd h List.not_mem_nil, .inl rfl⟩
      · exact ⟨[], fun _ h => absurd h List.not_mem_nil, .inr (.inl ⟨d, rfl, hd⟩)⟩
      · exact ⟨[], fun _ h => absurd h List.not_mem_nil, .inr (.inr (.inl ⟨C, s, rfl, hC, hs⟩))⟩
      · exact ⟨[s], fun r hr => by rw [List.mem_singleton.1 hr]; exact hs,
          .inr (.inr (.inr ⟨C, s, rfl, hC, ent_of_mem List.mem_cons_self⟩))⟩

theorem cont₂_former_const (k : Kind) : Cont₂ fun A B => former k A fun _ => B where
  left B := Cont.of_closure (P := fun A t => t = .tag k ∨ (∃ d, t = .arg k 0 [] d ∧ A.Mem d) ∨
      ∃ D X Y, t = .fn k D X Y ∧ Below D A ∧ Below Y B)
    (fun h _ ht => ht.imp_right (Or.imp (fun ⟨d, e, hd⟩ => ⟨d, e, h d hd⟩)
      fun ⟨D, X, Y, e, hD, hY⟩ => ⟨D, X, Y, e, hD.mono h, hY⟩))
    fun {_ _} ht => by
      rcases ht with rfl | ⟨d, rfl, hd⟩ | ⟨D, X, Y, rfl, hD, hY⟩
      · exact ⟨[], fun _ h => absurd h List.not_mem_nil, .inl rfl⟩
      · exact ⟨[d], fun r hr => by rw [List.mem_singleton.1 hr]; exact hd,
          .inr (.inl ⟨d, rfl, ent_of_mem List.mem_cons_self⟩)⟩
      · exact ⟨D, hD, .inr (.inr ⟨D, X, Y, rfl, fun c hc => ent_of_mem hc, hY⟩)⟩
  right A := Cont.of_closure (P := fun B t => t = .tag k ∨ (∃ d, t = .arg k 0 [] d ∧ A.Mem d) ∨
      ∃ D X Y, t = .fn k D X Y ∧ Below D A ∧ Below Y B)
    (fun h _ ht => ht.imp_right (Or.imp_right
      fun ⟨D, X, Y, e, hD, hY⟩ => ⟨D, X, Y, e, hD, hY.mono h⟩))
    fun {_ _} ht => by
      rcases ht with rfl | ⟨d, rfl, hd⟩ | ⟨D, X, Y, rfl, hD, hY⟩
      · exact ⟨[], fun _ h => absurd h List.not_mem_nil, .inl rfl⟩
      · exact ⟨[], fun _ h => absurd h List.not_mem_nil, .inr (.inl ⟨d, rfl, hd⟩)⟩
      · exact ⟨Y, hY, .inr (.inr ⟨D, X, Y, rfl, hD, fun c hc => ent_of_mem hc⟩)⟩

/-- The decoder, `prop → U`: the identity on codes, projected onto its type. -/
def holdsConst : Ideal := projT (cpi codesIdeal fun _ => univIdeal) (lam fun X => principal X)

/-- Implication of codes, `prop → prop → prop`: the dependent function type with a
constant family, projected onto its type. -/
def impConst : Ideal :=
  projT (cpi codesIdeal fun _ => cpi codesIdeal fun _ => codesIdeal)
    (lam fun P => lam fun Q => former .pi (principal P) fun _ => principal Q)

/-- The equation code at the carrier `A`, `A → A → prop`: the identity type between
its arguments, projected onto its type. -/
def eqConst (A : Ideal) : Ideal :=
  projT (cpi A fun _ => cpi A fun _ => codesIdeal)
    (lam fun X => lam fun Y => ident A (principal X) (principal Y))

theorem app_holdsConst (c : Ideal) : app holdsConst c = projT univIdeal (projT codesIdeal c) := by
  rw [holdsConst, app_projT_cpi (Cont.const univIdeal)]
  exact congrArg (projT univIdeal) (app_lam_principal Cont.id _)

theorem appSpine_impConst (p q : Ideal) :
    appSpine impConst [p, q] =
      projT codesIdeal (former .pi (projT codesIdeal p) fun _ => projT codesIdeal q) := by
  have e₁ : app (lam fun P => lam fun Q => former .pi (principal P) fun _ => principal Q)
      (projT codesIdeal p) = lam fun Q => former .pi (projT codesIdeal p) fun _ => principal Q :=
    app_lam_principal (H := fun z => lam fun Q => former .pi z fun _ => principal Q)
      (cont_lam_param fun Q => (cont₂_former_const .pi).left (principal Q)) _
  have e₂ : app (lam fun Q => former .pi (projT codesIdeal p) fun _ => principal Q)
      (projT codesIdeal q) = former .pi (projT codesIdeal p) fun _ => projT codesIdeal q :=
    app_lam_principal ((cont₂_former_const .pi).right (projT codesIdeal p)) _
  show app (app impConst p) q = _
  rw [impConst, app_projT_cpi (Cont.const _), app_projT_cpi (Cont.const _), e₁, e₂]

theorem appSpine_eqConst (A x y : Ideal) :
    appSpine (eqConst A) [x, y] = projT codesIdeal (ident A (projT A x) (projT A y)) := by
  have e₁ : app (lam fun X => lam fun Y => ident A (principal X) (principal Y)) (projT A x) =
      lam fun Y => ident A (projT A x) (principal Y) :=
    app_lam_principal (H := fun z => lam fun Y => ident A z (principal Y))
      (cont_lam_param fun Y => cont_ident_left A (principal Y)) _
  have e₂ : app (lam fun Y => ident A (projT A x) (principal Y)) (projT A y) =
      ident A (projT A x) (projT A y) :=
    app_lam_principal (cont_ident_right A (projT A x)) _
  show app (app (eqConst A) x) y = _
  rw [eqConst, app_projT_cpi (Cont.const _), app_projT_cpi (Cont.const _), e₁, e₂]

/-- **The decoding of an implication code is valid**, with no hypothesis:
`holds (imp p q)` denotes `holds p → holds q`. -/
theorem decode_impConst (p q : Ideal) :
    app holdsConst (appSpine impConst [p, q]) =
      cpi (app holdsConst p) fun _ => app holdsConst q := by
  have hp : projT univIdeal (projT codesIdeal p) = projT codesIdeal p :=
    projT_univ_eq_self_iff.2 (typeGenerated_projT_codes p)
  have hq : projT univIdeal (projT codesIdeal q) = projT codesIdeal q :=
    projT_univ_eq_self_iff.2 (typeGenerated_projT_codes q)
  have hG : TypeGenerated (former .pi (projT codesIdeal p) fun _ => projT codesIdeal q) :=
    typeGenerated_former_const (.inl rfl) (typeGenerated_projT_codes p) (typeGenerated_projT_codes q)
  rw [app_holdsConst, app_holdsConst, app_holdsConst, appSpine_impConst, projT_projT, hp, hq,
    projT_codes_eq_self_iff.2 hG, projT_univ_eq_self_iff.2 hG]
  rfl

/-- **The decoding of an equation code is valid**: `holds (eq@A x y)` denotes
`Id A x y` whenever the contractum `Id A x y` is a type. The spine facts of `holds`
say nothing about `x` and `y`; the contractum's typing puts them in the carrier. -/
theorem decode_eqConst {A x y : Ideal} (right : projT univIdeal (ident A x y) = ident A x y) :
    app holdsConst (appSpine (eqConst A) [x, y]) = ident A x y := by
  have hG := projT_univ_eq_self_iff.1 right
  obtain ⟨hx, hy⟩ := typeGenerated_ident_endpoints hG
  rw [app_holdsConst, appSpine_eqConst, hx, hy, projT_projT, projT_codes_eq_self_iff.2 hG, right]

end Ideal

end Domain
end Impredicative
end TypedEquality
end Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId.Presentation
