import Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId.TypedEquality.Impredicative.Domain.Families

/-!
# The η-laws of the projections, and the projection onto the universe of codes

The projection onto a type (`Ideal.projT`) keeps the tokens of an element that
are typed at a compact type below it. For dependent types it decomposes along
the components, as the finitary projections of the model of Carneiro, Coquand,
Frabetti Mathieu, Lennon-Bertrand, Melliès and Weirich, *Definitional Inversion,
Without Normalisation*, do (§2.4–2.5):

* **at a dependent pair type** (`projT_sigma`): the projection of `x` onto
  `Σ A F` is the pair of the projection of `fst x` onto `A` and the projection
  of `snd x` onto the family's value *at the projected first component*,
  `π_{Σ A F} x = (π_A x.1, π_{F (π_A x.1)} x.2)`. The family's value at the
  unprojected first component is too large: a first component with untyped
  observations can make the family larger than at any typed first component
  (the controls module has the counterexample);
* **at a dependent function type** (`projT_pi`): the projection of `f` onto
  `Π A F` is the function that projects its argument onto `A`, applies `f`, and
  projects the value onto the family's value at the projected argument,
  `π_{Π A F} f = λ X. π_{F (π_A X)} (f (π_A X))`. This is the reading of a
  function that carries its domain (§2.5): `⟦λ (x : A). M⟧` sees its argument
  only through `A`;
* both at the interpretation of `Σ A B` and `Π A B` (`projT_interp_sigma`,
  `projT_interp_pi`), where the family's value is the interpretation of `B` at
  the projected value.

The function that projects its argument onto `T` (`churchId T`, the value of
`λ (x : T). x` for functions carrying their domain) applied to `y` is the
projection of `y` onto `T` (`app_churchId`).

**The universe of codes.** The type of proposition codes is interpreted by the
universe of codes (`codesIdeal`). A token typed at it is exactly a type token,
a token typed at the universe (`typedAt_codes_iff`), so the projection onto the
universe of codes is the projection onto the universe (`projT_codes_eq_univ`):
it keeps every type token of an element untouched (`mem_projT_codes`), and the
elements it fixes are exactly those generated by their type tokens
(`projT_codes_eq_self_iff`). The values the code constructors denote are of this
kind: a dependent function type with a constant family (implication), one whose
family sees its argument only through its typed observations (a quantifier), and
an identity type between elements of its carrier (an equation), each over types
generated by type tokens (`typeGenerated_former_const`, `typeGenerated_former_pi`,
`typeGenerated_ident`); dependent pair types whose family sees its argument only
through its typed observations are too (`typeGenerated_former`). So decoding a
code by the function that projects onto the universe of codes returns the code
(`app_churchId_codes`).
-/

set_option autoImplicit false

namespace Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId.Presentation
namespace TypedEquality
namespace Impredicative
namespace Domain
namespace Ideal

/-! ## Finite combinations -/

/-- Finitely many witnesses, each a list of tokens with a property, combine into
one list with the property, for any statement preserved by enlarging the list. -/
theorem gather {α : Type} {P : Tok → Prop} {Q : List Tok → α → Prop}
    (hQ : ∀ {G G' : List Tok} {y : α}, (∀ g ∈ G, g ∈ G') → Q G y → Q G' y) :
    ∀ {Y : List α}, (∀ y ∈ Y, ∃ G, (∀ g ∈ G, P g) ∧ Q G y) →
      ∃ G, (∀ g ∈ G, P g) ∧ ∀ y ∈ Y, Q G y
  | [], _ => ⟨[], fun _ h => absurd h List.not_mem_nil, fun _ h => absurd h List.not_mem_nil⟩
  | y :: Y, h => by
      obtain ⟨G₁, hP₁, hQ₁⟩ := h y List.mem_cons_self
      obtain ⟨G₂, hP₂, hQ₂⟩ := gather (P := P) (Q := Q) hQ (Y := Y) fun z hz =>
        h z (List.mem_cons_of_mem _ hz)
      refine ⟨G₁ ++ G₂, fun g hg => ?_, fun z hz => ?_⟩
      · rcases List.mem_append.1 hg with hg | hg
        · exact hP₁ g hg
        · exact hP₂ g hg
      · rcases List.mem_cons.1 hz with rfl | hz
        · exact hQ (fun g hg => List.mem_append_left _ hg) hQ₁
        · exact hQ (fun g hg => List.mem_append_right _ hg) (hQ₂ z hz)

/-- Finitely many tokens typed at a type are typed at one compact type below it. -/
theorem typedAt_list {T : Ideal} :
    ∀ {w : List Tok}, (∀ s ∈ w, TypedAt T s) → ∃ a, Below a T ∧ Ty a Elem.univ ∧ Ty w a
  | [], _ => ⟨[], fun _ h => absurd h List.not_mem_nil, Ty.nil _, Ty.nil _⟩
  | s :: w, h => by
      obtain ⟨a₁, h₁, u₁, t₁⟩ := h s List.mem_cons_self
      obtain ⟨a₂, h₂, u₂, t₂⟩ := typedAt_list (w := w) fun r hr => h r (List.mem_cons_of_mem _ hr)
      refine ⟨a₁ ++ a₂, h₁.append h₂, u₁.append u₂, fun r hr => ?_⟩
      rcases List.mem_cons.1 hr with rfl | hr
      · exact t₁.mono (Le.append_left _ _)
      · exact (t₂ r hr).mono (Le.append_right _ _)

/-- A token of a generated ideal that is a tag is a generator. -/
theorem closure_tag {P : Tok → Prop} {k : Kind} (h : (closure P).Mem (.tag k)) : P (.tag k) := by
  obtain ⟨v, hv, ht⟩ := h
  rw [ent_tag, hasTag_iff] at ht
  exact hv _ ht

/-- A tag of a projection is a typed tag of the element. -/
theorem mem_projT_tag {T I : Ideal} {k : Kind} (h : (projT T I).Mem (.tag k)) :
    I.Mem (.tag k) ∧ TypedAt T (.tag k) :=
  closure_tag h

/-! ## Components of typed dependent types -/

/-- The domain of a compact type of kind `pi` or `sigma` is a type. -/
theorem ty_args_dom {k : Kind} (hk : k = .pi ∨ k = .sigma) {a : List Tok}
    (ha : Ty a Elem.univ) : Ty (args k 0 a) Elem.univ := by
  have hk' : k = .pi ∨ k = .sigma ∨ k = .ident := by
    rcases hk with rfl | rfl
    · exact .inl rfl
    · exact .inr (.inl rfl)
  intro s hs
  rcases mem_args_iff.1 hs with ⟨C, hC⟩ | ⟨-, t, ht, htk, hd⟩
  · exact ((tyTok_dom hk').1 (ha _ hC)).2.2
  · cases t with
    | tag => cases hd
    | arg k' i C s' =>
        change k' = k at htk
        subst htk
        change s ∈ C at hd
        have h := ha _ ht
        rcases Nat.eq_zero_or_pos i with rfl | hi
        · obtain ⟨-, hC, -⟩ := (tyTok_dom hk').1 h
          subst hC
          cases hd
        · refine absurd h (tyTok_arg_other ?_)
          rcases hk with rfl | rfl <;> simp [argSlots] <;> omega
    | fn k' C X Y =>
        change k' = k at htk
        subst htk
        exact ((tyTok_family hk).1 (ha _ ht)).2.1 s hd

/-- The family values of a compact type of kind `pi` or `sigma` are types. -/
theorem ty_fnApp {k : Kind} (hk : k = .pi ∨ k = .sigma) {a : List Tok} (ha : Ty a Elem.univ)
    (X : List Tok) : Ty (fnApp k a X) Elem.univ := by
  intro s hs
  obtain ⟨C, X', Y', hm, -, hs⟩ := mem_fnApp'.1 hs
  exact ((tyTok_family hk).1 (ha _ hm)).2.2.2 s hs

/-- A compact element below a dependent type of kind `k` has no tag but `k`. -/
theorem tag_of_below_former {k k' : Kind} {A : Ideal} {F : List Tok → Ideal} {a : List Tok}
    (ha : Below a (former k A F)) (h : Tok.tag k' ∈ a) : k' = k :=
  former_mem_tag_iff.1 (ha _ h)

/-- The domain of a compact element below a dependent type is below its domain. -/
theorem below_args_former {k : Kind} {A : Ideal} {F : List Tok → Ideal} {a : List Tok}
    (ha : Below a (former k A F)) : Below (args k 0 a) A := by
  have h := below_dom_args (k := k) ha
  rwa [dom_former] at h

/-- The compact dependent type with domain `a₁` and entries `f` is below the
dependent type with domain `A` and family `F` when `a₁` is below `A` and each
entry's output is below the family's value at its input. -/
theorem below_former_elem {k : Kind} {A : Ideal} {F : List Tok → Ideal} (hF : Monotone F)
    {a₁ : List Tok} {f : List (List Tok × List Tok)} (ha₁ : Below a₁ A)
    (hf : ∀ p ∈ f, Below p.2 (F p.1)) : Below (Elem.former k a₁ f) (former k A F) := by
  intro t ht
  simp only [Elem.former, List.mem_cons, List.mem_append, List.mem_map] at ht
  rcases ht with rfl | ⟨d, hd, rfl⟩ | ⟨p, hp, rfl⟩
  · exact mem_former_tag k A F
  · exact mem_former_dom.2 (ha₁ d hd)
  · exact (mem_former_fn hF).2 ⟨ha₁, hf p hp⟩

/-- The tokens typed at a compact type below a dependent pair type are the
components of pairs. -/
theorem tyTok_below_sigma {A : Ideal} {F : List Tok → Ideal} {a : List Tok}
    (ha : Below a (former .sigma A F)) {t : Tok} (ht : TyTok a t) :
    (∃ s, t = .arg .pair 0 [] s ∧ TyTok (args .sigma 0 a) s) ∨
      ∃ C s, t = .arg .pair 1 C s ∧ (∀ c ∈ C, TyTok (args .sigma 0 a) c) ∧
        TyTok (fnApp .sigma a C) s := by
  have notTag : ∀ {k : Kind}, k ≠ .sigma → Tok.tag k ∉ a := fun hk h =>
    hk (tag_of_below_former ha h)
  have notUniv : ¬ IsUniv a := by
    rintro (h | h)
    · exact notTag (by decide) h
    · exact notTag (by decide) h
  cases t with
  | tag k =>
      exfalso
      rcases tag_cases k with hk | rfl | rfl | rfl | rfl | rfl
      · exact notUniv ((tyTok_tag_former hk).1 ht)
      · exact notTag (by decide) (tyTok_tag_zero.1 ht)
      · exact notTag (by decide) (tyTok_tag_succ.1 ht)
      · exact notTag (by decide) (tyTok_tag_refl.1 ht)
      · exact tyTok_tag_lam ht
      · exact tyTok_tag_pair ht
  | arg k i C s =>
      rcases Decidable.em ((k, i) ∈ argSlots) with hs | hother
      swap
      · exact absurd ht (tyTok_arg_other hother)
      simp only [argSlots, List.mem_cons, Prod.mk.injEq, List.not_mem_nil, or_false] at hs
      rcases hs with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ |
        ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
      · exact absurd ((tyTok_dom (.inl rfl)).1 ht).1 notUniv
      · exact absurd ((tyTok_dom (.inr (.inl rfl))).1 ht).1 notUniv
      · exact absurd ((tyTok_dom (.inr (.inr rfl))).1 ht).1 notUniv
      · exact absurd ((tyTok_endpoint (.inl rfl)).1 ht).1 notUniv
      · exact absurd ((tyTok_endpoint (.inr rfl)).1 ht).1 notUniv
      · exact absurd (tyTok_pred.1 ht).1 (notTag (by decide))
      · exact absurd (tyTok_reflPoint.1 ht).1 (notTag (by decide))
      · obtain ⟨-, rfl, hs⟩ := tyTok_fst.1 ht
        exact .inl ⟨s, rfl, hs⟩
      · obtain ⟨-, hC, hs⟩ := tyTok_snd.1 ht
        exact .inr ⟨C, s, rfl, hC, hs⟩
  | fn k C X Y =>
      exfalso
      rcases fn_cases k with hk | rfl | hother
      · exact notUniv ((tyTok_family hk).1 ht).1
      · exact notTag (by decide) (tyTok_lam.1 ht).1
      · exact tyTok_fn_other hother ht

/-- The tokens typed at a compact type below a dependent function type are the
entries of functions. -/
theorem tyTok_below_pi {A : Ideal} {F : List Tok → Ideal} {a : List Tok}
    (ha : Below a (former .pi A F)) {t : Tok} (ht : TyTok a t) :
    ∃ X Y, t = .fn .lam [] X Y ∧ (∀ x ∈ X, TyTok (args .pi 0 a) x) ∧
      ∀ y ∈ Y, TyTok (fnApp .pi a X) y := by
  have notTag : ∀ {k : Kind}, k ≠ .pi → Tok.tag k ∉ a := fun hk h =>
    hk (tag_of_below_former ha h)
  have notUniv : ¬ IsUniv a := by
    rintro (h | h)
    · exact notTag (by decide) h
    · exact notTag (by decide) h
  cases t with
  | tag k =>
      exfalso
      rcases tag_cases k with hk | rfl | rfl | rfl | rfl | rfl
      · exact notUniv ((tyTok_tag_former hk).1 ht)
      · exact notTag (by decide) (tyTok_tag_zero.1 ht)
      · exact notTag (by decide) (tyTok_tag_succ.1 ht)
      · exact notTag (by decide) (tyTok_tag_refl.1 ht)
      · exact tyTok_tag_lam ht
      · exact tyTok_tag_pair ht
  | arg k i C s =>
      exfalso
      rcases Decidable.em ((k, i) ∈ argSlots) with hs | hother
      swap
      · exact tyTok_arg_other hother ht
      simp only [argSlots, List.mem_cons, Prod.mk.injEq, List.not_mem_nil, or_false] at hs
      rcases hs with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ |
        ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
      · exact notUniv ((tyTok_dom (.inl rfl)).1 ht).1
      · exact notUniv ((tyTok_dom (.inr (.inl rfl))).1 ht).1
      · exact notUniv ((tyTok_dom (.inr (.inr rfl))).1 ht).1
      · exact notUniv ((tyTok_endpoint (.inl rfl)).1 ht).1
      · exact notUniv ((tyTok_endpoint (.inr rfl)).1 ht).1
      · exact notTag (by decide) (tyTok_pred.1 ht).1
      · exact notTag (by decide) (tyTok_reflPoint.1 ht).1
      · exact notTag (by decide) (tyTok_fst.1 ht).1
      · exact notTag (by decide) (tyTok_snd.1 ht).1
  | fn k C X Y =>
      rcases fn_cases k with hk | rfl | hother
      · exact absurd ((tyTok_family hk).1 ht).1 notUniv
      · obtain ⟨-, rfl, hX, hY⟩ := tyTok_lam.1 ht
        exact ⟨X, Y, rfl, hX, hY⟩
      · exact absurd ht (tyTok_fn_other hother)

/-! ## The family of a dependent type built by `former` -/

/-- A token of the family's value at `y` is a token of the family at a finite
part of `y`. -/
theorem mem_fam_former {k : Kind} {A : Ideal} {F : List Tok → Ideal} (hF : Monotone F)
    {y : Ideal} {t : Tok} :
    (fam k (former k A F) y).Mem t ↔ ∃ Z, Below Z y ∧ (F Z).Mem t := by
  constructor
  · rintro ⟨v, hv, ht⟩
    have key : ∀ {v : List Tok}, (∀ s ∈ v, ∃ C Z Y, (former k A F).Mem (.fn k C Z Y) ∧
        Below Z y ∧ s ∈ Y) → ∃ Z, Below Z y ∧ Below v (F Z) := by
      intro v
      induction v with
      | nil => exact fun _ => ⟨[], fun _ h => absurd h List.not_mem_nil,
          fun _ h => absurd h List.not_mem_nil⟩
      | cons s v ih =>
          intro h
          obtain ⟨C, Z₁, Y, hm, hZ₁, hs⟩ := h s List.mem_cons_self
          obtain ⟨Z₂, hZ₂, hv⟩ := ih fun r hr => h r (List.mem_cons_of_mem _ hr)
          refine ⟨Z₁ ++ Z₂, hZ₁.append hZ₂, fun r hr => ?_⟩
          rcases List.mem_cons.1 hr with rfl | hr
          · exact hF (Le.append_left _ _) r (((mem_former_fn hF).1 hm).2 r hs)
          · exact hF (Le.append_right _ _) r (hv r hr)
    obtain ⟨Z, hZ, hvZ⟩ := key hv
    exact ⟨Z, hZ, (F Z).closed hvZ ht⟩
  · rintro ⟨Z, hZ, ht⟩
    exact subset_closure ⟨[], Z, [t], (mem_former_fn hF).2 ⟨fun _ h => absurd h List.not_mem_nil,
      fun s hs => by rw [List.mem_singleton.1 hs]; exact ht⟩, hZ, List.mem_singleton_self t⟩

/-- A compact element below the family's value at `y` is below the family at a
finite part of `y`. -/
theorem below_fam_former {k : Kind} {A : Ideal} {F : List Tok → Ideal} (hF : Monotone F)
    {y : Ideal} : ∀ {b : List Tok}, Below b (fam k (former k A F) y) →
      ∃ Z, Below Z y ∧ Below b (F Z)
  | [], _ => ⟨[], fun _ h => absurd h List.not_mem_nil, fun _ h => absurd h List.not_mem_nil⟩
  | s :: b, h => by
      obtain ⟨Z₁, hZ₁, hs⟩ := (mem_fam_former hF).1 (h s List.mem_cons_self)
      obtain ⟨Z₂, hZ₂, hb⟩ := below_fam_former hF (b := b) fun r hr =>
        h r (List.mem_cons_of_mem _ hr)
      refine ⟨Z₁ ++ Z₂, hZ₁.append hZ₂, fun r hr => ?_⟩
      rcases List.mem_cons.1 hr with rfl | hr
      · exact hF (Le.append_left _ _) r hs
      · exact hF (Le.append_right _ _) r (hb r hr)

/-! ## Pairs -/

/-- The first component of an element holds its first-projection tokens. -/
theorem mem_arg0_of_mem_fst {x : Ideal} {s : Tok} (h : (fst x).Mem s) :
    x.Mem (.arg .pair 0 [] s) := by
  obtain ⟨v, hv, hs⟩ := h
  refine x.closed (v := v.map (.arg .pair 0 [])) ?_ ?_
  · intro r hr
    obtain ⟨r', hr', rfl⟩ := List.mem_map.1 hr
    exact hv r' hr'
  · rw [ent_arg, List.all_nil, Bool.true_and, args_map_arg_same]
    exact hs

/-- The dependency of a second-projection token is in the first projection. -/
theorem mem_fst_of_arg1 {x : Ideal} {C : List Tok} {s c : Tok}
    (h : x.Mem (.arg .pair 1 C s)) (hc : c ∈ C) : (fst x).Mem c :=
  mem_dom_of_arg_dep (k := .pair) h hc

/-- A token of the second projection, with a dependency below the first
projection, is a second-projection token of the element. -/
theorem mem_arg1_of_mem_snd {x : Ideal} {W : List Tok} {s : Tok} (hW : Below W (fst x))
    (h : (snd x).Mem s) : x.Mem (.arg .pair 1 W s) := by
  obtain ⟨u, hu, hs⟩ := h
  refine x.closed (v := W.map (.arg .pair 0 []) ++ u.map (.arg .pair 1 [])) ?_ ?_
  · intro r hr
    rcases List.mem_append.1 hr with hr | hr
    · obtain ⟨w, hw, rfl⟩ := List.mem_map.1 hr
      exact mem_arg0_of_mem_fst (hW w hw)
    · obtain ⟨r', hr', rfl⟩ := List.mem_map.1 hr
      obtain ⟨C, hC⟩ := hu r' hr'
      refine x.closed (v := [.arg .pair 1 C r'])
        (fun q hq => by rw [List.mem_singleton.1 hq]; exact hC) ?_
      rw [ent_arg, List.all_nil, Bool.true_and]
      exact ent_of_mem (mem_args_of_arg (List.mem_singleton_self _))
  · rw [ent_arg, Bool.and_eq_true, List.all_eq_true]
    refine ⟨fun w hw => ent_of_mem (mem_args_of_arg (C := [])
      (List.mem_append_left _ (List.mem_map_of_mem hw))), ?_⟩
    exact ent_mono (fun r hr => mem_args_of_arg (C := [])
      (List.mem_append_right _ (List.mem_map_of_mem hr))) hs

/-! ## The η-law of the projection onto a dependent pair type -/

/-- **The projection onto a dependent pair type is componentwise**, the second
component projected onto the family's value at the projected first component:
`π_{Σ A F} x = (π_A x.1, π_{F (π_A x.1)} x.2)`. -/
theorem projT_sigma {A : Ideal} {F : List Tok → Ideal} (hF : Monotone F) (x : Ideal) :
    projT (former .sigma A F) x =
      pair (projT A (fst x)) (projT (fam .sigma (former .sigma A F) (projT A (fst x))) (snd x)) := by
  apply le_antisymm
  · refine closure_le fun t ⟨hx, a, ha, hau, hat⟩ => ?_
    have hdom := below_args_former ha
    have hdomTy := ty_args_dom (.inr rfl) hau
    rcases tyTok_below_sigma ha hat with ⟨s, rfl, hs⟩ | ⟨C, s, rfl, hC, hs⟩
    · exact subset_closure (.inl ⟨s, rfl, subset_closure ⟨subset_closure hx, _, hdom, hdomTy, hs⟩⟩)
    · have hCI : Below C (projT A (fst x)) := fun c hc =>
        subset_closure ⟨mem_fst_of_arg1 hx hc, _, hdom, hdomTy, hC c hc⟩
      exact subset_closure (.inr ⟨C, s, rfl, hCI, subset_closure ⟨subset_closure ⟨C, hx⟩,
        _, below_fam_fnApp ha hCI, ty_fnApp (.inr rfl) hau C, hs⟩⟩)
  · -- a first-projection token of the projection, from a typed first component
    have gen0 : ∀ {s : Tok}, (fst x).Mem s → TypedAt A s →
        (projT (former .sigma A F) x).Mem (.arg .pair 0 [] s) := by
      intro s hs ⟨a₁, h₁, u₁, t₁⟩
      refine subset_closure ⟨mem_arg0_of_mem_fst hs, Elem.former .sigma a₁ [],
        below_former_elem hF h₁ (fun _ h => absurd h List.not_mem_nil),
        Elem.ty_former (.inr rfl) Elem.isUniv_univ u₁ (fun _ h => absurd h List.not_mem_nil), ?_⟩
      exact tyTok_fst.2 ⟨List.mem_cons_self, rfl, t₁.mono (Elem.dom_former _ _ _).2⟩
    refine closure_le fun t ht => ?_
    rcases ht with ⟨d, rfl, hd⟩ | ⟨C, s, rfl, hC, hs⟩
    · obtain ⟨v, hv, hdv⟩ := hd
      refine (projT (former .sigma A F) x).closed (v := v.map (.arg .pair 0 [])) ?_ ?_
      · intro r hr
        obtain ⟨s, hs, rfl⟩ := List.mem_map.1 hr
        exact gen0 (hv s hs).1 (hv s hs).2
      · rw [ent_arg, List.all_nil, Bool.true_and, args_map_arg_same]
        exact hdv
    · obtain ⟨v, hv, hsv⟩ := hs
      obtain ⟨w, hw, hCw⟩ := below_closure_iff.1 hC
      -- each typed token of the second projection has a typed second-projection token
      obtain ⟨G, hG, hvG⟩ := gather (P := fun g => (projT (former .sigma A F) x).Mem g)
        (Q := fun G (s' : Tok) => s' ∈ args .pair 1 G)
        (fun hsub h => args_subset hsub _ h) (Y := v) fun s' hs' => by
          obtain ⟨hs'x, b, hb, hbu, hbs⟩ := hv s' hs'
          obtain ⟨Z, hZ, hbZ⟩ := below_fam_former hF hb
          obtain ⟨w₁, hw₁, hZw₁⟩ := below_closure_iff.1 hZ
          obtain ⟨a₁, ha₁, hu₁, hty₁⟩ := typedAt_list fun r hr => (hw₁ r hr).2
          have hbw : Below b (F w₁) := fun r hr => hF hZw₁ r (hbZ r hr)
          refine ⟨[.arg .pair 1 w₁ s'], fun g hg => ?_,
            mem_args_of_arg (List.mem_singleton_self _)⟩
          rw [List.mem_singleton.1 hg]
          refine subset_closure ⟨mem_arg1_of_mem_snd (fun r hr => (hw₁ r hr).1) hs'x,
            Elem.former .sigma a₁ [(w₁, b)],
            below_former_elem hF ha₁ (fun p hp => by rw [List.mem_singleton.1 hp]; exact hbw),
            Elem.ty_former (.inr rfl) Elem.isUniv_univ hu₁
              (fun p hp => by rw [List.mem_singleton.1 hp]; exact ⟨hty₁, hbu⟩), ?_⟩
          refine tyTok_snd.2 ⟨List.mem_cons_self,
            fun c hc => (hty₁ c hc).mono (Elem.dom_former _ _ _).2, ?_⟩
          rw [show fnApp .sigma (Elem.former .sigma a₁ [(w₁, b)]) w₁ = stepApp [(w₁, b)] w₁ from
            Elem.fam_former _ _ _ _]
          exact hbs.mono (Le.of_subset fun r hr =>
            mem_stepApp.2 ⟨(w₁, b), List.mem_singleton_self _, Le.refl _, hr⟩)
      refine (projT (former .sigma A F) x).closed (v := w.map (.arg .pair 0 []) ++ G) ?_ ?_
      · intro r hr
        rcases List.mem_append.1 hr with hr | hr
        · obtain ⟨s, hs, rfl⟩ := List.mem_map.1 hr
          exact gen0 (hw s hs).1 (hw s hs).2
        · exact hG r hr
      · rw [ent_arg, Bool.and_eq_true, List.all_eq_true]
        refine ⟨fun c hc => ent_mono (fun r hr => mem_args_of_arg (C := [])
          (List.mem_append_left _ (List.mem_map_of_mem hr))) (hCw c hc), ?_⟩
        exact ent_mono (fun r hr => args_subset (fun g hg => List.mem_append_right _ hg) r
          (hvG r hr)) hsv

/-! ## The η-law of the projection onto a dependent function type -/

/-- The value at `X` of the projection of `f` onto `Π A F`: the argument
projected onto `A`, and the value projected onto the family there. -/
def piProj (A : Ideal) (F : List Tok → Ideal) (f : Ideal) (X : List Tok) : Ideal :=
  projT (fam .pi (former .pi A F) (projT A (principal X))) (app f (projT A (principal X)))

theorem piProj_monotone (A : Ideal) (F : List Tok → Ideal) (f : Ideal) :
    Monotone (piProj A F f) := by
  intro X X' h
  have hp : projT A (principal X) ≤ projT A (principal X') := projT_mono (principal_mono h)
  exact le_trans (projT_mono_type (fam_mono (le_refl _) hp) _) (projT_mono (app_mono (le_refl f) hp))

/-- **The projection onto a dependent function type projects the argument onto
the domain**: `π_{Π A F} f = λ X. π_{F (π_A X)} (f (π_A X))`, the reading of a
function that carries its domain. -/
theorem projT_pi {A : Ideal} {F : List Tok → Ideal} (hF : Monotone F) (f : Ideal) :
    projT (former .pi A F) f = lam (piProj A F f) := by
  apply le_antisymm
  · refine closure_le fun t ⟨hf, a, ha, hau, hat⟩ => ?_
    obtain ⟨X, Y, rfl, hX, hY⟩ := tyTok_below_pi ha hat
    have hdom := below_args_former ha
    have hdomTy := ty_args_dom (.inl rfl) hau
    have hXp : Below X (projT A (principal X)) := fun x hx =>
      subset_closure ⟨ent_of_mem hx, _, hdom, hdomTy, hX x hx⟩
    exact (mem_lam_fn (piProj_monotone A F f)).2 fun y hy =>
      subset_closure ⟨mem_app.2 ⟨X, Y, hXp, hf, ent_of_mem hy⟩,
        _, below_fam_fnApp ha hXp, ty_fnApp (.inl rfl) hau X, hY y hy⟩
  · refine closure_le fun t ⟨X', Y', ht, hY'⟩ => ?_
    subst ht
    have per : ∀ y ∈ Y', ∃ G, (∀ g ∈ G, (projT (former .pi A F) f).Mem g) ∧
        ent (fnApp .lam G X') y = true := by
      intro y hy
      obtain ⟨v, hv, hyv⟩ := hY' y hy
      obtain ⟨G, hG, hvG⟩ := gather (P := fun g => (projT (former .pi A F) f).Mem g)
        (Q := fun G (s : Tok) => s ∈ fnApp .lam G X')
        (fun hsub h => fnApp_subset X' hsub _ h) (Y := v) fun s hs => by
          obtain ⟨hsf, b, hb, hbu, hbs⟩ := hv s hs
          obtain ⟨X₀, Y₀, hX₀, hf₀, hY₀⟩ := mem_app.1 hsf
          obtain ⟨Z, hZ, hbZ⟩ := below_fam_former hF hb
          obtain ⟨w, hw, hw'⟩ := below_closure_iff.1 (hX₀.append hZ)
          obtain ⟨a₁, ha₁, hu₁, hty₁⟩ := typedAt_list fun r hr => (hw r hr).2
          have hbw : Below b (F w) := fun r hr =>
            hF ((Le.append_right _ _).trans hw') r (hbZ r hr)
          have hfw : f.Mem (.fn .lam [] w [s]) := by
            refine f.closed (v := [.fn .lam [] X₀ Y₀])
              (fun q hq => by rw [List.mem_singleton.1 hq]; exact hf₀) ?_
            rw [ent_fn, Bool.and_eq_true, List.all_eq_true, List.all_eq_true]
            refine ⟨fun c hc => absurd hc List.not_mem_nil, fun r hr => ?_⟩
            rw [List.mem_singleton.1 hr]
            exact ent_mono (fun q hq => mem_fnApp'.2 ⟨[], X₀, Y₀, List.mem_singleton_self _,
              (Le.append_left _ _).trans hw', hq⟩) hY₀
          refine ⟨[.fn .lam [] w [s]], fun g hg => ?_,
            mem_fnApp'.2 ⟨[], w, [s], List.mem_singleton_self _, fun r hr => (hw r hr).1,
              List.mem_singleton_self _⟩⟩
          rw [List.mem_singleton.1 hg]
          refine subset_closure ⟨hfw, Elem.former .pi a₁ [(w, b)],
            below_former_elem hF ha₁ (fun p hp => by rw [List.mem_singleton.1 hp]; exact hbw),
            Elem.ty_former (.inl rfl) Elem.isUniv_univ hu₁
              (fun p hp => by rw [List.mem_singleton.1 hp]; exact ⟨hty₁, hbu⟩), ?_⟩
          refine tyTok_lam.2 ⟨List.mem_cons_self, rfl,
            fun c hc => (hty₁ c hc).mono (Elem.dom_former _ _ _).2, fun r hr => ?_⟩
          rw [List.mem_singleton.1 hr,
            show fnApp .pi (Elem.former .pi a₁ [(w, b)]) w = stepApp [(w, b)] w from
              Elem.fam_former _ _ _ _]
          exact hbs.mono (Le.of_subset fun q hq =>
            mem_stepApp.2 ⟨(w, b), List.mem_singleton_self _, Le.refl _, hq⟩)
      exact ⟨G, hG, ent_mono (fun s hs => hvG s hs) hyv⟩
    obtain ⟨G, hG, hYG⟩ := gather (P := fun g => (projT (former .pi A F) f).Mem g)
      (Q := fun G (y : Tok) => ent (fnApp .lam G X') y = true)
      (fun hsub h => ent_mono (fnApp_subset X' hsub) h) per
    refine (projT (former .pi A F) f).closed (v := G) hG ?_
    rw [ent_fn, Bool.and_eq_true, List.all_eq_true, List.all_eq_true]
    exact ⟨fun c hc => absurd hc List.not_mem_nil, hYG⟩

/-! ## At the interpretations of dependent types -/

section Interp

variable {Head : Type} (Rd : Reading Head)

/-- The η-law at the interpretation of `Σ A B`: the second component is
projected onto `B` at the projected first component. -/
theorem projT_interp_sigma {n : Nat} (A : Tm Head n) (B : Tm Head (n + 1)) (ρ : Env n)
    (x : Ideal) :
    projT (interp Rd (.sigma A B) ρ) x =
      pair (projT (interp Rd A ρ) (fst x))
        (projT (interp Rd B (Env.cons (projT (interp Rd A ρ) (fst x)) ρ)) (snd x)) := by
  have h := projT_sigma (A := interp Rd A ρ) (interp_family_monotone Rd B ρ) x
  rw [fam_interp_former] at h
  exact h

/-- The η-law at the interpretation of `Π A B`: the argument is projected onto
`A`, and the value onto `B` at the projected argument. -/
theorem projT_interp_pi {n : Nat} (A : Tm Head n) (B : Tm Head (n + 1)) (ρ : Env n)
    (f : Ideal) :
    projT (interp Rd (.pi A B) ρ) f =
      lam fun X => projT (interp Rd B (Env.cons (projT (interp Rd A ρ) (principal X)) ρ))
        (app f (projT (interp Rd A ρ) (principal X))) := by
  have h := projT_pi (A := interp Rd A ρ) (interp_family_monotone Rd B ρ) f
  unfold piProj at h
  simp only [fam_interp_former] at h
  exact h

end Interp

/-! ## The function that projects its argument -/

/-- The value of `λ (x : T). x` for functions that carry their domain: the
function that projects its argument onto `T`. -/
def churchId (T : Ideal) : Ideal := lam fun X => projT T (principal X)

theorem churchId_monotone (T : Ideal) : Monotone fun X => projT T (principal X) :=
  fun h => projT_mono (principal_mono h)

/-- **Applying the function that projects onto `T` is projecting onto `T`.** -/
theorem app_churchId (T y : Ideal) : app (churchId T) y = projT T y := by
  apply le_antisymm
  · intro t ht
    obtain ⟨X, Y, hX, hl, hY⟩ := mem_app.1 ht
    have hY' := (mem_lam_fn (churchId_monotone T)).1 hl
    exact projT_mono (principal_le_iff.2 hX) t ((projT T (principal X)).closed hY' hY)
  · intro t ht
    obtain ⟨v, hv, hvT, htv⟩ := projT_eq_iSup.1 ht
    refine mem_app.2 ⟨v, [t], hv, (mem_lam_fn (churchId_monotone T)).2 fun s hs => ?_,
      ent_of_mem List.mem_cons_self⟩
    rw [List.mem_singleton.1 hs]
    exact projT_eq_iSup.2 ⟨v, fun r hr => ent_of_mem hr, hvT, htv⟩

/-! ## The universe of codes -/

/-- The universe, as an ideal. -/
def univIdeal : Ideal := principal Elem.univ

/-- The universe of codes, as an ideal: the interpretation of the type of
proposition codes. -/
def codesIdeal : Ideal := principal Elem.codes

/-- The typing of a token at a compact element whose only tags that type tokens
are universes is its typing as a type. -/
theorem tyTok_of_univLike {a b : List Tok}
    (hna : ∀ k, (k = .nat ∨ k = .ident ∨ k = .sigma ∨ k = .pi) → Tok.tag k ∉ a)
    (hb : IsUniv b) {t : Tok} (ht : TyTok a t) : TyTok b t := by
  cases t with
  | tag k =>
      rcases tag_cases k with hk | rfl | rfl | rfl | rfl | rfl
      · exact (tyTok_tag_former hk).2 hb
      · exact absurd (tyTok_tag_zero.1 ht) (hna _ (.inl rfl))
      · exact absurd (tyTok_tag_succ.1 ht) (hna _ (.inl rfl))
      · exact absurd (tyTok_tag_refl.1 ht) (hna _ (.inr (.inl rfl)))
      · exact absurd ht tyTok_tag_lam
      · exact absurd ht tyTok_tag_pair
  | arg k i C s =>
      rcases Decidable.em ((k, i) ∈ argSlots) with hs | hother
      swap
      · exact absurd ht (tyTok_arg_other hother)
      simp only [argSlots, List.mem_cons, Prod.mk.injEq, List.not_mem_nil, or_false] at hs
      rcases hs with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ |
        ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
      · obtain ⟨-, hC, hs⟩ := (tyTok_dom (.inl rfl)).1 ht
        exact (tyTok_dom (.inl rfl)).2 ⟨hb, hC, hs⟩
      · obtain ⟨-, hC, hs⟩ := (tyTok_dom (.inr (.inl rfl))).1 ht
        exact (tyTok_dom (.inr (.inl rfl))).2 ⟨hb, hC, hs⟩
      · obtain ⟨-, hC, hs⟩ := (tyTok_dom (.inr (.inr rfl))).1 ht
        exact (tyTok_dom (.inr (.inr rfl))).2 ⟨hb, hC, hs⟩
      · obtain ⟨-, hC, hs⟩ := (tyTok_endpoint (.inl rfl)).1 ht
        exact (tyTok_endpoint (.inl rfl)).2 ⟨hb, hC, hs⟩
      · obtain ⟨-, hC, hs⟩ := (tyTok_endpoint (.inr rfl)).1 ht
        exact (tyTok_endpoint (.inr rfl)).2 ⟨hb, hC, hs⟩
      · exact absurd (tyTok_pred.1 ht).1 (hna _ (.inl rfl))
      · exact absurd (tyTok_reflPoint.1 ht).1 (hna _ (.inr (.inl rfl)))
      · exact absurd (tyTok_fst.1 ht).1 (hna _ (.inr (.inr (.inl rfl))))
      · exact absurd (tyTok_snd.1 ht).1 (hna _ (.inr (.inr (.inl rfl))))
  | fn k C X Y =>
      rcases fn_cases k with hk | rfl | hother
      · obtain ⟨-, hC, hX, hY⟩ := (tyTok_family hk).1 ht
        exact (tyTok_family hk).2 ⟨hb, hC, hX, hY⟩
      · exact absurd (tyTok_lam.1 ht).1 (hna _ (.inr (.inr (.inr rfl))))
      · exact absurd ht (tyTok_fn_other hother)

/-- The tags of the compact element of one tag. -/
theorem mem_principal_tag {k k' : Kind} : (principal [Tok.tag k]).Mem (.tag k') ↔ k' = k := by
  rw [mem_principal, ent_tag, hasTag_iff, List.mem_singleton]
  exact ⟨Tok.tag.inj, fun h => h ▸ rfl⟩

/-- A universe-like compact element: its only tag is a universe. -/
theorem typedAt_iff_of_univ {k : Kind} (hk : k = .univ ∨ k = .codes) {t : Tok} :
    TypedAt (principal [Tok.tag k]) t ↔ TyTok Elem.univ t := by
  have hno : ∀ {a : List Tok}, Below a (principal [Tok.tag k]) →
      ∀ k', (k' = .nat ∨ k' = .ident ∨ k' = .sigma ∨ k' = .pi) → Tok.tag k' ∉ a := by
    intro a ha k' hk' h
    have e := mem_principal_tag.1 (ha _ h)
    subst e
    rcases hk with rfl | rfl <;> rcases hk' with h | h | h | h <;> cases h
  constructor
  · rintro ⟨a, ha, -, hat⟩
    exact tyTok_of_univLike (hno ha) Elem.isUniv_univ hat
  · intro ht
    have hU : IsUniv [Tok.tag k] := by
      rcases hk with rfl | rfl
      · exact Elem.isUniv_univ
      · exact Elem.isUniv_codes
    refine ⟨[Tok.tag k], fun s hs => ent_of_mem hs,
      Elem.ty_tag (by rcases hk with rfl | rfl <;> trivial) Elem.isUniv_univ, ?_⟩
    refine tyTok_of_univLike (a := Elem.univ) (fun k' hk' h => ?_) hU ht
    rw [Elem.univ, List.mem_singleton] at h
    rcases hk' with rfl | rfl | rfl | rfl <;> cases h

/-- **A token is typed at the universe of codes iff it is a type token.** -/
theorem typedAt_codes_iff {t : Tok} : TypedAt codesIdeal t ↔ TyTok Elem.univ t :=
  typedAt_iff_of_univ (.inr rfl)

/-- A token is typed at the universe iff it is a type token. -/
theorem typedAt_univ_iff {t : Tok} : TypedAt univIdeal t ↔ TyTok Elem.univ t :=
  typedAt_iff_of_univ (.inl rfl)

/-- The projection onto the universe of codes keeps exactly the type tokens. -/
theorem projT_codes_eq (I : Ideal) :
    projT codesIdeal I = closure fun t => I.Mem t ∧ TyTok Elem.univ t :=
  le_antisymm (closure_mono fun _ h => ⟨h.1, typedAt_codes_iff.1 h.2⟩)
    (closure_mono fun _ h => ⟨h.1, typedAt_codes_iff.2 h.2⟩)

/-- The projection onto the universe keeps exactly the type tokens. -/
theorem projT_univ_eq (I : Ideal) :
    projT univIdeal I = closure fun t => I.Mem t ∧ TyTok Elem.univ t :=
  le_antisymm (closure_mono fun _ h => ⟨h.1, typedAt_univ_iff.1 h.2⟩)
    (closure_mono fun _ h => ⟨h.1, typedAt_univ_iff.2 h.2⟩)

/-- **The projection onto the universe of codes is the projection onto the
universe**: a code and the type it decodes to are projected alike. -/
theorem projT_codes_eq_univ (I : Ideal) : projT codesIdeal I = projT univIdeal I := by
  rw [projT_codes_eq, projT_univ_eq]

/-- **The projection onto the universe of codes leaves type tokens untouched.** -/
theorem mem_projT_codes {I : Ideal} {t : Tok} (h : I.Mem t) (ht : TyTok Elem.univ t) :
    (projT codesIdeal I).Mem t :=
  subset_closure ⟨h, typedAt_codes_iff.2 ht⟩

/-- An ideal generated by its type tokens. -/
def TypeGenerated (I : Ideal) : Prop :=
  ∀ t, I.Mem t → ∃ v, (∀ s ∈ v, I.Mem s ∧ TyTok Elem.univ s) ∧ ent v t = true

/-- **The elements the projection onto the universe of codes fixes are those
generated by their type tokens.** -/
theorem projT_codes_eq_self_iff {I : Ideal} : projT codesIdeal I = I ↔ TypeGenerated I := by
  constructor
  · intro h t ht
    rw [← h] at ht
    obtain ⟨v, hv, htv⟩ := ht
    refine ⟨v, fun s hs => ⟨?_, typedAt_codes_iff.1 (hv s hs).2⟩, htv⟩
    exact (hv s hs).1
  · intro h
    refine le_antisymm (projT_le _ _) fun t ht => ?_
    obtain ⟨v, hv, htv⟩ := h t ht
    exact ⟨v, fun s hs => ⟨(hv s hs).1, typedAt_codes_iff.2 (hv s hs).2⟩, htv⟩

theorem projT_univ_eq_self_iff {I : Ideal} : projT univIdeal I = I ↔ TypeGenerated I := by
  rw [← projT_codes_eq_univ]
  exact projT_codes_eq_self_iff

/-- The projection onto the universe of codes is generated by type tokens. -/
theorem typeGenerated_projT_codes (I : Ideal) : TypeGenerated (projT codesIdeal I) :=
  projT_codes_eq_self_iff.1 (projT_projT _ _)

/-- The principal ideal of a compact type is generated by its type tokens. -/
theorem typeGenerated_principal {u : List Tok} (hu : Ty u Elem.univ) :
    TypeGenerated (principal u) :=
  fun _ ht => ⟨u, fun s hs => ⟨ent_of_mem hs, hu s hs⟩, ht⟩

/-- An ideal generated by `P` is generated by its type tokens when each
generator is entailed by finitely many of its type tokens. -/
theorem typeGenerated_closure {P : Tok → Prop}
    (h : ∀ g, P g → ∃ v, (∀ s ∈ v, (closure P).Mem s ∧ TyTok Elem.univ s) ∧ ent v g = true) :
    TypeGenerated (closure P) := by
  intro t ⟨v, hv, htv⟩
  obtain ⟨G, hG, hvG⟩ := gather (P := fun s => (closure P).Mem s ∧ TyTok Elem.univ s)
    (Q := fun G (g : Tok) => ent G g = true) (fun hsub h => ent_mono hsub h) (Y := v)
    fun g hg => h g (hv g hg)
  exact ⟨G, hG, ent_cut htv hvG⟩

/-- The domain tokens of a type generated by its type tokens are entailed by
finitely many typed domain tokens. -/
theorem typed_dom_tokens {k : Kind} (hk : k = .pi ∨ k = .sigma ∨ k = .ident) {A : Ideal}
    (hA : TypeGenerated A) {D : List Tok} (hD : Below D A) :
    ∃ w, (∀ s ∈ w, A.Mem s ∧ TyTok Elem.univ (.arg k 0 [] s)) ∧ D ⊑ w := by
  obtain ⟨G, hG, hDG⟩ := gather (P := fun s => A.Mem s ∧ TyTok Elem.univ (.arg k 0 [] s))
    (Q := fun G (d : Tok) => ent G d = true) (fun hsub h => ent_mono hsub h) (Y := D)
    fun d hd => by
      obtain ⟨v, hv, hdv⟩ := hA d (hD d hd)
      exact ⟨v, fun s hs => ⟨(hv s hs).1,
        (tyTok_dom hk).2 ⟨Elem.isUniv_univ, rfl, (hv s hs).2⟩⟩, hdv⟩
  exact ⟨G, hG, hDG⟩

/-- **A dependent type with a constant family over types generated by type
tokens is generated by type tokens** (the value of implication). -/
theorem typeGenerated_former_const {k : Kind} (hk : k = .pi ∨ k = .sigma) {A B : Ideal}
    (hA : TypeGenerated A) (hB : TypeGenerated B) :
    TypeGenerated (former k A fun _ => B) := by
  have hF : Monotone fun _ : List Tok => B := fun _ => le_refl B
  have hk3 : k = .pi ∨ k = .sigma ∨ k = .ident := by
    rcases hk with rfl | rfl
    · exact .inl rfl
    · exact .inr (.inl rfl)
  have hkF : k.IsFormer := by rcases hk with rfl | rfl <;> trivial
  refine typeGenerated_closure fun g hg => ?_
  rcases hg with rfl | ⟨d, rfl, hd⟩ | ⟨D, X, Y, rfl, hD, hY⟩
  · exact ⟨[.tag k], fun s hs => by
      rw [List.mem_singleton.1 hs]
      exact ⟨mem_former_tag _ _ _, (tyTok_tag_former hkF).2 Elem.isUniv_univ⟩,
      ent_of_mem List.mem_cons_self⟩
  · obtain ⟨v, hv, hdv⟩ := hA d hd
    refine ⟨v.map (.arg k 0 []), fun s hs => ?_, ?_⟩
    · obtain ⟨s', hs', rfl⟩ := List.mem_map.1 hs
      exact ⟨mem_former_dom.2 (hv s' hs').1, (tyTok_dom hk3).2 ⟨Elem.isUniv_univ, rfl, (hv s' hs').2⟩⟩
    · rw [ent_arg, List.all_nil, Bool.true_and, args_map_arg_same]
      exact hdv
  · obtain ⟨w, hw, hDw⟩ := typed_dom_tokens hk3 hA hD
    obtain ⟨u, hu, hYu⟩ := gather (P := fun s => B.Mem s ∧ TyTok Elem.univ s)
      (Q := fun G (y : Tok) => ent G y = true) (fun hsub h => ent_mono hsub h) (Y := Y)
      fun y hy => hB y (hY y hy)
    refine ⟨w.map (.arg k 0 []) ++ [.fn k [] [] u], fun s hs => ?_, ?_⟩
    · rcases List.mem_append.1 hs with hs | hs
      · obtain ⟨s', hs', rfl⟩ := List.mem_map.1 hs
        exact ⟨mem_former_dom.2 (hw s' hs').1, (hw s' hs').2⟩
      · rw [List.mem_singleton.1 hs]
        refine ⟨(mem_former_fn hF).2 ⟨fun _ h => absurd h List.not_mem_nil,
          fun y hy => (hu y hy).1⟩, (tyTok_family hk).2 ⟨Elem.isUniv_univ,
            fun _ h => absurd h List.not_mem_nil, fun _ h => absurd h List.not_mem_nil,
            fun y hy => (hu y hy).2⟩⟩
    · rw [ent_fn, Bool.and_eq_true, List.all_eq_true, List.all_eq_true]
      refine ⟨fun c hc => ent_mono (fun r hr => mem_args_of_arg (C := [])
        (List.mem_append_left _ (List.mem_map_of_mem hr))) (hDw c hc), fun y hy => ?_⟩
      refine ent_mono (fun r hr => mem_fnApp'.2 ⟨[], [], u,
        List.mem_append_right _ (List.mem_singleton_self _), Le.nil _, hr⟩) (hYu y hy)

/-- **A dependent function or pair type whose family sees its argument only
through its typed observations, over types generated by type tokens, is generated
by type tokens.** -/
theorem typeGenerated_former {k : Kind} (hk : k = .pi ∨ k = .sigma) {A : Ideal}
    {F : List Tok → Ideal} (hF : Monotone F)
    (hA : TypeGenerated A) (hFty : ∀ X, TypeGenerated (F X))
    (hFA : ∀ X t, (F X).Mem t → ∃ w, w ⊑ X ∧ (∀ s ∈ w, TypedAt A s) ∧ (F w).Mem t) :
    TypeGenerated (former k A F) := by
  have hk3 : k = .pi ∨ k = .sigma ∨ k = .ident := hk.imp_right Or.inl
  have hkF : k.IsFormer := by rcases hk with rfl | rfl <;> trivial
  refine typeGenerated_closure fun g hg => ?_
  rcases hg with rfl | ⟨d, rfl, hd⟩ | ⟨D, X, Y, rfl, hD, hY⟩
  · exact ⟨[.tag k], fun s hs => by
      rw [List.mem_singleton.1 hs]
      exact ⟨mem_former_tag _ _ _, (tyTok_tag_former hkF).2 Elem.isUniv_univ⟩,
      ent_of_mem List.mem_cons_self⟩
  · obtain ⟨v, hv, hdv⟩ := hA d hd
    refine ⟨v.map (.arg k 0 []), fun s hs => ?_, ?_⟩
    · obtain ⟨s', hs', rfl⟩ := List.mem_map.1 hs
      exact ⟨mem_former_dom.2 (hv s' hs').1,
        (tyTok_dom hk3).2 ⟨Elem.isUniv_univ, rfl, (hv s' hs').2⟩⟩
    · rw [ent_arg, List.all_nil, Bool.true_and, args_map_arg_same]
      exact hdv
  · obtain ⟨w, hw, hDw⟩ := typed_dom_tokens hk3 hA hD
    -- each output token comes from a typed entry at a typed input below `X`
    obtain ⟨G, hG, hYG⟩ := gather
      (P := fun s => (former k A F).Mem s ∧ TyTok Elem.univ s)
      (Q := fun G (y : Tok) => ent (fnApp k G X) y = true)
      (fun hsub h => ent_mono (fnApp_subset X hsub) h) (Y := Y) fun y hy => by
        obtain ⟨w₁, hw₁X, hw₁, hy₁⟩ := hFA X y (hY y hy)
        obtain ⟨a₁, ha₁, hu₁, hty₁⟩ := typedAt_list hw₁
        obtain ⟨u, hu, hyu⟩ := hFty w₁ y hy₁
        refine ⟨[.fn k a₁ w₁ u], fun s hs => ?_, ?_⟩
        · rw [List.mem_singleton.1 hs]
          exact ⟨(mem_former_fn hF).2 ⟨ha₁, fun r hr => (hu r hr).1⟩,
            (tyTok_family hk).2 ⟨Elem.isUniv_univ, hu₁, hty₁, fun r hr => (hu r hr).2⟩⟩
        · exact ent_mono (fun r hr => mem_fnApp'.2 ⟨a₁, w₁, u, List.mem_singleton_self _,
            hw₁X, hr⟩) hyu
    refine ⟨w.map (.arg k 0 []) ++ G, fun s hs => ?_, ?_⟩
    · rcases List.mem_append.1 hs with hs | hs
      · obtain ⟨s', hs', rfl⟩ := List.mem_map.1 hs
        exact ⟨mem_former_dom.2 (hw s' hs').1, (hw s' hs').2⟩
      · exact hG s hs
    · rw [ent_fn, Bool.and_eq_true, List.all_eq_true, List.all_eq_true]
      refine ⟨fun c hc => ent_mono (fun r hr => mem_args_of_arg (C := [])
        (List.mem_append_left _ (List.mem_map_of_mem hr))) (hDw c hc), fun y hy => ?_⟩
      exact ent_mono (fnApp_subset X fun g hg => List.mem_append_right _ hg) (hYG y hy)

/-- **A dependent function type whose family sees its argument only through its
typed observations, over types generated by type tokens, is generated by type
tokens** (the value of a quantifier). -/
theorem typeGenerated_former_pi {A : Ideal} {F : List Tok → Ideal} (hF : Monotone F)
    (hA : TypeGenerated A) (hFty : ∀ X, TypeGenerated (F X))
    (hFA : ∀ X t, (F X).Mem t → ∃ w, w ⊑ X ∧ (∀ s ∈ w, TypedAt A s) ∧ (F w).Mem t) :
    TypeGenerated (former .pi A F) :=
  typeGenerated_former (.inl rfl) hF hA hFty hFA

/-- **An identity type between elements of its carrier, over a carrier generated
by type tokens, is generated by type tokens** (the value of an equation). -/
theorem typeGenerated_ident {A I J : Ideal} (hA : TypeGenerated A) (hI : projT A I = I)
    (hJ : projT A J = J) : TypeGenerated (ident A I J) := by
  -- an endpoint token is entailed by typed endpoint tokens and typed carrier tokens
  have endpoint : ∀ {i : Nat}, (i = 1 ∨ i = 2) → ∀ {K : Ideal}, projT A K = K →
      (∀ {C s}, Below C A → K.Mem s → (ident A I J).Mem (.arg .ident i C s)) →
      ∀ {C : List Tok} {s : Tok}, Below C A → K.Mem s →
        ∃ v, (∀ r ∈ v, (ident A I J).Mem r ∧ TyTok Elem.univ r) ∧
          ent v (.arg .ident i C s) = true := by
    intro i hi K hK hmem C s hC hs
    rw [← hK] at hs
    obtain ⟨v, hv, hsv⟩ := hs
    obtain ⟨a₁, ha₁, hu₁, hty₁⟩ := typedAt_list fun r hr => (hv r hr).2
    obtain ⟨w, hw, hCw⟩ := typed_dom_tokens (.inr (.inr rfl)) hA hC
    have hvK : Below v K := fun r hr => (hv r hr).1
    refine ⟨w.map (.arg .ident 0 []) ++ v.map (.arg .ident i a₁), fun r hr => ?_, ?_⟩
    · rcases List.mem_append.1 hr with hr | hr
      · obtain ⟨s, hs, rfl⟩ := List.mem_map.1 hr
        exact ⟨subset_closure (.inr (.inl ⟨s, rfl, (hw s hs).1⟩)), (hw s hs).2⟩
      · obtain ⟨s, hs, rfl⟩ := List.mem_map.1 hr
        exact ⟨hmem ha₁ (hvK s hs), (tyTok_endpoint hi).2 ⟨Elem.isUniv_univ, hu₁, hty₁ s hs⟩⟩
    · rw [ent_arg, Bool.and_eq_true, List.all_eq_true]
      refine ⟨fun c hc => ent_mono (fun r hr => mem_args_of_arg (C := [])
        (List.mem_append_left _ (List.mem_map_of_mem hr))) (hCw c hc), ?_⟩
      exact ent_mono (fun r hr => mem_args_of_arg
        (List.mem_append_right _ (List.mem_map_of_mem hr))) hsv
  refine typeGenerated_closure fun g hg => ?_
  rcases hg with rfl | ⟨d, rfl, hd⟩ | ⟨C, s, rfl, hC, hs⟩ | ⟨C, s, rfl, hC, hs⟩
  · exact ⟨[.tag .ident], fun r hr => by
      rw [List.mem_singleton.1 hr]
      exact ⟨subset_closure (.inl rfl), (tyTok_tag_former (k := .ident) trivial).2 Elem.isUniv_univ⟩,
      ent_of_mem List.mem_cons_self⟩
  · obtain ⟨v, hv, hdv⟩ := hA d hd
    refine ⟨v.map (.arg .ident 0 []), fun r hr => ?_, ?_⟩
    · obtain ⟨r', hr', rfl⟩ := List.mem_map.1 hr
      exact ⟨subset_closure (.inr (.inl ⟨r', rfl, (hv r' hr').1⟩)),
        (tyTok_dom (.inr (.inr rfl))).2 ⟨Elem.isUniv_univ, rfl, (hv r' hr').2⟩⟩
    · rw [ent_arg, List.all_nil, Bool.true_and, args_map_arg_same]
      exact hdv
  · exact endpoint (.inl rfl) hI
      (fun hC hs => subset_closure (.inr (.inr (.inl ⟨_, _, rfl, hC, hs⟩)))) hC hs
  · exact endpoint (.inr rfl) hJ
      (fun hC hs => subset_closure (.inr (.inr (.inr ⟨_, _, rfl, hC, hs⟩)))) hC hs

/-- **Decoding a code by the function that projects onto the universe of codes
returns the code**, for every code generated by type tokens. -/
theorem app_churchId_codes {c : Ideal} (hc : TypeGenerated c) :
    app (churchId codesIdeal) c = c := by
  rw [app_churchId]
  exact projT_codes_eq_self_iff.2 hc

end Ideal
end Domain
end Impredicative
end TypedEquality
end Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId.Presentation
