import Mettapedia.GSLT.Dynamics.ServiceEffectProtocol
import Mettapedia.Languages.MeTTa.PrimeCandidates.SharedJudgmentServices
import Mettapedia.Languages.MeTTa.PrimeCandidates.DeclarationBased.ScopedComputationEffectTree

/-!
# Operational and OSLF meaning of the shared judgment services

The actual submitted service request produces its actual indexed response.
A successful response binds its native payload in the authored scoped body.
Completion then requires a step of the authored effect-tree LanguageDef; it
is not defined as the graph of the reference world evaluator. A third step
emits a precise occurrence from that complete ordered list.

The resulting OSLF observation preserves the request, response, native value,
branch, state and deferred intents. Decline remains an observable response
without a continuation. HOL proof acceptance still means source derivability
and formation of its native representation, not native proof inhabitation.

This is an internal typed request protocol with a compiled effect backend.
It is not a codec for external HOL proof bytes or a textual language frontend.
Its finite continuation semantics does not establish termination of general
proof search or completeness of arbitrary OSLF formula checking.
-/

open Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId
open Mettapedia.TypeTheory.UniverseLevel

set_option autoImplicit false

open Mettapedia.TypeTheory.Calculi.CumulativePiSigmaId

namespace Mettapedia.Languages.MeTTa.PrimeCandidates.SharedJudgmentServiceOSLF

open Mettapedia.Languages.MeTTa.PrimeCandidates.DeclarationBased
open Presentation Presentation.ScopedComputation
open Mettapedia.GSLT.Dynamics.ContextualEffectHandlers
open SharedJudgmentFragment SharedJudgmentServices

open Mettapedia.GSLT.Dynamics Mettapedia.GSLT.LanguageDef
open Mettapedia.OSLF.Framework.GSLTTypeSynthesis

variable {n : Nat}

def protocol (assembly : Assembly) (n : Nat) :
    ServiceEffectProtocol.Protocol (Source n) (fun source => Response source.request) Bool (Tower.Tm n) Nat where
  invoke source := invoke assembly source.request
  continuation := continuationProgram assembly

/-- The evaluator is the independently authored target language. The native
world codec preserves the entire list, rather than accepting only its image
as an unproved well-formedness assumption on the target. -/
def completion : ServiceEffectProtocol.Completion (State := Bool) (Answer := Tower.Tm n) (Intent := Nat) :=
  fun program state branch worlds =>
    ContextualEffectTreeLanguage.theory.Step (ScopedComputationEffectTree.request program state branch) (ScopedComputationEffectTree.completion worlds)

theorem completion_exact : ServiceEffectProtocol.CompletionExact (completion (n := n)) :=
  ScopedComputationEffectTree.native_complete_iff

abbrev theory (assembly : Assembly) (n : Nat) :=
  ServiceEffectProtocol.gslt (protocol assembly n) completion

def produces (assembly : Assembly)
    (observation : (source : Source n) → Response source.request →
      WorldResult Bool (Tower.Tm n) Nat → Prop) :
    ServiceEffectProtocol.Term (protocol assembly n) → Prop :=
  ServiceEffectProtocol.produces (protocol assembly n) completion observation

/-- The actual equation-invariant native type generated by the protocol's
three stages. Its base predicate observes the retained complete-world data. -/
def answerNativeType (assembly : Assembly)
    (observation : (source : Source n) → Response source.request →
      WorldResult Bool (Tower.Tm n) Nat → Prop) : GSLTNativeType (theory assembly n) where
  sort := ()
  pred := semanticDiamond (theory assembly n)
    (semanticDiamond (theory assembly n)
      (semanticDiamond (theory assembly n)
        (saturatePredicate (theory assembly n)
          (ServiceEffectProtocol.observesAnswer (protocol assembly n) observation))))

theorem answerNativeType_iff (assembly : Assembly)
    (observation : (source : Source n) → Response source.request →
      WorldResult Bool (Tower.Tm n) Nat → Prop)
    (term : ServiceEffectProtocol.Term (protocol assembly n)) :
    (gsltOSLF (theory assembly n)).satisfies (S := ()) term
      (answerNativeType assembly observation).pred ↔ produces assembly observation term := by
  have base :
      (saturatePredicate (theory assembly n)
        (ServiceEffectProtocol.observesAnswer (protocol assembly n) observation)).1 =
      ServiceEffectProtocol.observesAnswer (protocol assembly n) observation := by
    funext input
    exact propext (saturatePredicate_apply_iff_of_equiv_iff_eq (theory assembly n)
      (fun _ _ => Iff.rfl) _ input)
  change gsltDiamond (theory assembly n)
    (gsltDiamond (theory assembly n)
      (gsltDiamond (theory assembly n)
        (saturatePredicate (theory assembly n)
          (ServiceEffectProtocol.observesAnswer (protocol assembly n) observation)).1)) term ↔ _
  rw [base]
  rfl

/-- The first transition is exactly one of the five actual service rules. -/
theorem request_crossing_iff (assembly : Assembly) (source : Source n)
    (initial : Bool) (branch : BranchTrace) (response : Response source.request) :
    (theory assembly n).Step (.request source initial branch)
      (.returned source initial branch response) ↔
      Invocation assembly source.request response := by
  rw [ServiceEffectProtocol.request_step_iff]
  constructor
  · intro equality
    cases equality
    exact invoke_crossing assembly source.request
  · intro crossing
    have same := (invoke_iff assembly source.request response).mpr crossing
    rw [← same]
    rfl

/-- A returned response can complete only with the exact worlds of the
selected continuation, even though its execution is licensed by target rules. -/
theorem returned_completion_iff (assembly : Assembly) (source : Source n)
    (initial : Bool) (branch : BranchTrace) (response : Response source.request)
    (worlds : List (WorldResult Bool (Tower.Tm n) Nat)) :
    (theory assembly n).Step (.returned source initial branch response)
      (.completed source initial branch response worlds) ↔
      ∃ program,
        continuationProgram assembly source response = some program ∧
        worlds = runWorldsAt program initial branch := by
  constructor
  · intro step
    cases step with
    | completed selected execution =>
        exact ⟨_, selected, (completion_exact _ _ _ _).mp execution⟩
  · rintro ⟨program, selected, exactWorlds⟩
    exact ServiceEffectProtocol.Step.completed selected ((completion_exact _ _ _ _).mpr exactWorlds)

/-- The generated modality refers to the same submitted request, actual
service reply, selected body and ordered answer occurrence. -/
theorem produces_iff (assembly : Assembly)
    (observation : (source : Source n) → Response source.request →
      WorldResult Bool (Tower.Tm n) Nat → Prop)
    (source : Source n) (initial : Bool) (branch : BranchTrace) :
    produces assembly observation (.request source initial branch) ↔
      ∃ program, ∃ occurrence : Fin (runWorldsAt program initial branch).length,
        continuationProgram assembly source (invoke assembly source.request) = some program ∧
        observation source (invoke assembly source.request)
          ((runWorldsAt program initial branch).get occurrence) :=
  ServiceEffectProtocol.produces_request_iff_worlds (protocol assembly n) completion completion_exact
    observation source initial branch

/-- Success is observable as an emitted world. Nonemptiness here is a law of
the existing finite effect grammar, not an assumption that all proof search
terminates or that every submitted request succeeds. -/
theorem has_emitted_world_iff (assembly : Assembly) (source : Source n)
    (initial : Bool) (branch : BranchTrace) :
    (∃ world, produces assembly (fun _ _ actual => actual = world)
      (.request source initial branch)) ↔
      (invoke assembly source.request).status = .success := by
  constructor
  · rintro ⟨world, produced⟩
    obtain ⟨program, occurrence, selected, _⟩ :=
      (produces_iff assembly _ source initial branch).mp produced
    by_contra notSuccess
    have absent := (continuation_absent_iff (assembly := assembly) (source := source)
      (invoke assembly source.request)).mpr notSuccess
    rw [absent] at selected
    cases selected
  · intro success
    cases selected : continuationProgram assembly source (invoke assembly source.request) with
    | none =>
        exact False.elim ((continuation_absent_iff (assembly := assembly) (source := source)
          (invoke assembly source.request)).mp selected success)
    | some program =>
        have positive := List.length_pos_of_ne_nil (runWorldsAt_ne_nil program initial branch)
        let occurrence : Fin (runWorldsAt program initial branch).length := ⟨0, positive⟩
        refine ⟨(runWorldsAt program initial branch).get occurrence, ?_⟩
        exact (produces_iff assembly _ source initial branch).mpr
          ⟨program, occurrence, selected, rfl⟩

theorem matching_has_emitted_world_iff (assembly : Assembly)
    (qualified : specification.Satisfies assembly)
    (expected : PolarizedNeedMatchedIndex.Request) (input : NativeWireData.Wire)
    (body : Code Tower.Head NativeExamples.Operation (n + 1))
    (initial : Bool) (branch : BranchTrace) :
    (∃ world, produces assembly (fun _ _ actual => actual = world)
      (.request ⟨.matching expected input, body⟩ initial branch)) ↔
      (MatchedIndexDependentTransport.consume? expected input).isSome = true := by
  rw [has_emitted_world_iff]
  exact matching_success_iff qualified expected input

theorem hol_has_emitted_world_iff (assembly : Assembly)
    (qualified : specification.Satisfies assembly)
    (gamma : Mettapedia.Logic.HOL.Ctx Mettapedia.Logic.HOL.UniformListInduction.BaseSort)
    (replay : UniformListChartNIKService.ReplayRequest gamma)
    (environment : Sub Tower.Head gamma.length n)
    (body : Code Tower.Head NativeExamples.Operation (n + 1))
    (initial : Bool) (branch : BranchTrace) :
    (∃ world, produces assembly (fun _ _ actual => actual = world)
      (.request ⟨.hol gamma replay environment, body⟩ initial branch)) ↔
      UniformListChartNIKService.replayAccepted gamma replay = true := by
  rw [has_emitted_world_iff]
  exact hol_success_iff qualified gamma replay environment

/-- A native result obtained through the operational/modality path obeys
the independently admitted dependent continuation type on that same assembly. -/
theorem emitted_world_admitted (assembly : Assembly)
    (qualified : specification.Satisfies assembly) {context : Tower.Ctx n}
    {source : Source n} {payload type : Tower.Tm n} {resultType : Tower.Tm (n + 1)}
    (environment : EnvironmentAdmitted assembly context source.request)
    (returned : (invoke assembly source.request).nativePayload? = some (payload, type))
    (body : Judgment assembly.rules NativeExamples.signature (.snoc context type)
      source.continuation resultType)
    {initial : Bool} {branch : BranchTrace} {world : WorldResult Bool (Tower.Tm n) Nat}
    (produced : produces assembly (fun _ _ actual => actual = world)
      (.request source initial branch)) :
    FormationSensitive.Judgment assembly.rules context world.answer (inst0 payload resultType) := by
  obtain ⟨program, occurrence, selected, observed⟩ :=
    (produces_iff assembly _ source initial branch).mp produced
  have selectedActual := continuation_success (assembly := assembly) (source := source) returned
  have same := Option.some.inj (selected.symm.trans selectedActual)
  subst program
  rw [← observed]
  exact continuation_preserves qualified environment (invoke_crossing assembly source.request)
    returned body (List.get_mem _ occurrence)

namespace HOLMeaning

open Mettapedia.Logic HOL.UniformListInduction
open NativeHOLFragmentDenotation

universe w

/-- The generated native type can observe the actual returned formula.
Such an observation inherits its constructorwise meaning and conditional
truth through the same request, response and interpreted native substitution.
No truth of the source assumptions is supplied by operational success. -/
theorem observed_payload_model_sound (assembly : Assembly)
    (qualified : specification.Satisfies assembly)
    (model : HOL.HenkinModel.{0, 0, w} BaseSort Symbol)
    (respects : model.FunctionsRespectEqv)
    {gamma delta : HOL.Ctx BaseSort}
    (replay : UniformListChartNIKService.ReplayRequest gamma)
    (substitution : Sub Tower.Head gamma.length delta.length)
    (environment : model.Valuation delta → model.Valuation gamma)
    (components : ∀ {type} (index : HOL.Var gamma type),
      Denotes model (substitution (FormationSensitiveHOLInterface.variableIndex index))
        (fun valuation => environment valuation index))
    (body : Code Tower.Head NativeExamples.Operation (delta.length + 1))
    (initial : Bool) (branch : BranchTrace) (payload type : Tower.Tm delta.length)
    (observed : (gsltOSLF (theory assembly delta.length)).satisfies (S := ())
      (.request ⟨.hol gamma replay substitution, body⟩ initial branch)
      (answerNativeType assembly
        (fun _ reply _ => reply.nativePayload? = some (payload, type))).pred) :
    Denotes model payload (fun valuation => model.denote replay.claim.2 (environment valuation)) ∧
      ∀ valuation, model.ValuationAdmissible valuation →
        HOL.Soundness.SatisfiesHyps model (environment valuation) replay.claim.1 →
        (model.denote replay.claim.2 (environment valuation)).down := by
  have produced := (answerNativeType_iff assembly _ _).mp observed
  obtain ⟨_, _, _, returned⟩ := (produces_iff assembly _ _ initial branch).mp produced
  exact SharedJudgmentServices.HOLMeaning.payload_model_sound qualified model respects
    environment components (invoke_crossing assembly (.hol gamma replay substitution)) returned

/-- Any constructorwise interpretation of an actually observed payload has
the source claim's value at the interpreted request environment. Observing a
payload fixes its meaning; it does not supply truth of the assumptions. -/
theorem observed_payload_meaning_unique (assembly : Assembly)
    (model : HOL.HenkinModel.{0, 0, w} BaseSort Symbol)
    {gamma delta : HOL.Ctx BaseSort}
    (replay : UniformListChartNIKService.ReplayRequest gamma)
    (substitution : Sub Tower.Head gamma.length delta.length)
    (environment : model.Valuation delta → model.Valuation gamma)
    (components : ∀ {type} (index : HOL.Var gamma type),
      Denotes model (substitution (FormationSensitiveHOLInterface.variableIndex index))
        (fun valuation => environment valuation index))
    (body : Code Tower.Head NativeExamples.Operation (delta.length + 1))
    (initial : Bool) (branch : BranchTrace) (payload type : Tower.Tm delta.length)
    (observed : (gsltOSLF (theory assembly delta.length)).satisfies (S := ())
      (.request ⟨.hol gamma replay substitution, body⟩ initial branch)
      (answerNativeType assembly
        (fun _ reply _ => reply.nativePayload? = some (payload, type))).pred)
    {value : model.Valuation delta → HOL.Ty.denote model.Carrier .prop}
    (meaning : Denotes model payload value) (valuation : model.Valuation delta) :
    value valuation = model.denote replay.claim.2 (environment valuation) := by
  have produced := (answerNativeType_iff assembly _ _).mp observed
  obtain ⟨_, _, _, returned⟩ := (produces_iff assembly _ _ initial branch).mp produced
  exact SharedJudgmentServices.HOLMeaning.payload_meaning_unique model
    environment components (invoke_crossing assembly (.hol gamma replay substitution))
    returned meaning valuation

end HOLMeaning

/-- Declined requests still expose their reply; their absence of answers is
not a statement that the requested mathematical proposition is false. -/
theorem declined_has_reply_and_no_answer (assembly : Assembly) (source : Source n)
    (initial : Bool) (branch : BranchTrace)
    (declined : (invoke assembly source.request).status = .declined) :
    (theory assembly n).Step (.request source initial branch)
      (.returned source initial branch (invoke assembly source.request)) ∧
    ¬ ∃ world, produces assembly (fun _ _ actual => actual = world)
      (.request source initial branch) := by
  constructor
  · exact ServiceEffectProtocol.Step.invoked source initial branch
  · rw [has_emitted_world_iff, declined]
    decide

/-! ## Connected native service observations and distinguishing controls -/

namespace Examples

open SharedJudgmentServices.Examples

def firstWorld (payload : Tower.Tm 2) (branch : BranchTrace) :
    WorldResult Bool (Tower.Tm 2) Nat :=
  { branch := false :: branch, answer := .pair payload (.refl payload),
    state := true, intents := [10, 30] }

def secondWorld (payload : Tower.Tm 2) (branch : BranchTrace) :
    WorldResult Bool (Tower.Tm 2) Nat :=
  { branch := true :: branch, answer := .pair payload (.refl payload),
    state := false, intents := [20, 40] }

private theorem observes_both {source : Source 2} {payload : Tower.Tm 2}
    {program : Program Bool (Tower.Tm 2) Nat} (initial : Bool) (branch : BranchTrace)
    (selected : continuationProgram common source (invoke common source.request) = some program)
    (worlds : runWorldsAt program initial branch = [firstWorld payload branch, secondWorld payload branch]) :
    produces common (fun _ _ world => world = firstWorld payload branch)
        (.request source initial branch) ∧
      produces common (fun _ _ world => world = secondWorld payload branch)
        (.request source initial branch) := by
  constructor
  · apply (produces_iff common _ source initial branch).mpr
    refine ⟨program, ⟨0, by simp [worlds]⟩, selected, ?_⟩
    simp [worlds]
  · apply (produces_iff common _ source initial branch).mpr
    refine ⟨program, ⟨1, by simp [worlds]⟩, selected, ?_⟩
    simp [worlds]

theorem matching_observes_both (initial : Bool) (branch : BranchTrace) :
    produces common (fun _ _ world => world = firstWorld (liftClosed canonicalTransport.source) branch)
        (.request canonicalMatchingSource initial branch) ∧
      produces common (fun _ _ world => world = secondWorld (liftClosed canonicalTransport.source) branch)
        (.request canonicalMatchingSource initial branch) := by
  obtain ⟨program, selected, worlds, _⟩ := canonical_matching_workload initial branch
  exact observes_both initial branch selected worlds

theorem hol_observes_both (initial : Bool) (branch : BranchTrace) :
    produces common (fun _ _ world => world = firstWorld holPayload branch)
        (.request actualHOLSource initial branch) ∧
      produces common (fun _ _ world => world = secondWorld holPayload branch)
        (.request actualHOLSource initial branch) := by
  obtain ⟨program, selected, worlds, _⟩ := actual_hol_workload initial branch
  exact observes_both initial branch selected worlds

/-- Equal native answer payloads do not identify the actual returned states.
The counterexample runs through the service and authored backend, not a
separate table of hypothetical outputs. -/
theorem matching_answer_cannot_recover_state (initial : Bool) (branch : BranchTrace) :
    ¬ ∃ recover : Tower.Tm 2 → Bool,
      ∀ world, produces common (fun _ _ actual => actual = world)
        (.request canonicalMatchingSource initial branch) → recover world.answer = world.state := by
  rintro ⟨recover, recovers⟩
  have left := recovers _ (matching_observes_both initial branch).1
  have right := recovers _ (matching_observes_both initial branch).2
  change recover (.pair (liftClosed canonicalTransport.source)
    (.refl (liftClosed canonicalTransport.source))) = true at left
  change recover (.pair (liftClosed canonicalTransport.source)
    (.refl (liftClosed canonicalTransport.source))) = false at right
  exact Bool.noConfusion (left.symm.trans right)

theorem matching_cannot_drop_intents (initial : Bool) (branch : BranchTrace) :
    ¬ produces common
      (fun _ _ world => world = { firstWorld (liftClosed canonicalTransport.source) branch with intents := [] })
      (.request canonicalMatchingSource initial branch) := by
  intro produced
  obtain ⟨program, occurrence, selected, observed⟩ :=
    (produces_iff common _ canonicalMatchingSource initial branch).mp produced
  have same := Option.some.inj (selected.symm.trans canonical_matching_program)
  subst program
  have member := List.get_mem _ occurrence
  rw [observed, nativeContinuation_worlds] at member
  simp [firstWorld] at member

theorem malformed_hol_has_reply_without_answers (initial : Bool) (branch : BranchTrace) :
    (theory common 2).Step (.request malformedHOLSource initial branch)
      (.returned malformedHOLSource initial branch (invoke common malformedHOLSource.request)) ∧
    ¬ ∃ world, produces common (fun _ _ actual => actual = world)
      (.request malformedHOLSource initial branch) := by
  apply declined_has_reply_and_no_answer
  rw [malformed_hol_declines]
  rfl

theorem altered_matching_has_reply_without_answers (initial : Bool) (branch : BranchTrace) :
    (theory common 2).Step (.request alteredOutputSource initial branch)
      (.returned alteredOutputSource initial branch (invoke common alteredOutputSource.request)) ∧
    ¬ ∃ world, produces common (fun _ _ actual => actual = world)
      (.request alteredOutputSource initial branch) := by
  apply declined_has_reply_and_no_answer
  rw [altered_output_declines]
  rfl

end Examples

#print axioms completion_exact
#print axioms answerNativeType_iff
#print axioms request_crossing_iff
#print axioms returned_completion_iff
#print axioms produces_iff
#print axioms has_emitted_world_iff
#print axioms matching_has_emitted_world_iff
#print axioms hol_has_emitted_world_iff
#print axioms emitted_world_admitted
#print axioms HOLMeaning.observed_payload_model_sound
#print axioms HOLMeaning.observed_payload_meaning_unique
#print axioms declined_has_reply_and_no_answer
#print axioms Examples.matching_observes_both
#print axioms Examples.hol_observes_both
#print axioms Examples.matching_answer_cannot_recover_state
#print axioms Examples.matching_cannot_drop_intents
#print axioms Examples.malformed_hol_has_reply_without_answers
#print axioms Examples.altered_matching_has_reply_without_answers

end Mettapedia.Languages.MeTTa.PrimeCandidates.SharedJudgmentServiceOSLF
