import Mettapedia.Languages.MeTTa.PrimeCandidates.DeclarationBased.SetProfile.Basic
import Mettapedia.TypeTheory.Calculi.CumulativePiSigmaId.Declarations.CertifiedTransforms
import Mettapedia.TypeTheory.Calculi.CumulativePiSigmaId.Declarations.NativeIndexedFamilies
import Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId.Instances.RussellTarskiBoundary

/-!
# The certified-transform declarations of the Prime draft

`set:define` admits a definition by equations and stores each equation as a
kernel rule `(PrimeRule head n (p₁ … pₙ) rhs)`: `n` is the number of argument
patterns and `PVar k` is the `k`-th pattern slot.  In the calculus the equation
telescope has one variable per slot, slot `k` of `m` slots is the de Bruijn
index `m - 1 - k`, and instantiating an equation is ordinary substitution, which
shifts under the binders of the right-hand side exactly as the kernel's
instantiation does (`CertifiedTransformProgram.ArtifactComparison` checks this against the stored
rules).

This module declares the dependent library of the draft over the `set:`
profile and its proof family: identity elimination `id:eliminate` (the
language-owned eliminator, at carrier and motive level zero), the recursor
`num-rec` generated by `set:inductive num`, the definitions `eqAt`,
`sucMove`, `keepCert`, `transportCert`, `composeCert`, `iterCert`,
`returnIter` and `sucStep`, and a consumer over the represented source family
`holdsAt n = Holds (add zero n = n)` whose step is the translated induction
step of the source proof of `zero-add`.

The successor equations of `composeCert` and `iterCert` are the authored shared
applications `(λ pack. step₂ (fst pack) (snd pack)) (step x e)`, which is
`CertifiedTransforms.shared`.
-/

set_option autoImplicit false

namespace Mettapedia.Languages.MeTTa.PrimeCandidates.DeclarationBased.CertifiedTransformProgram.Package

open Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId
open Mettapedia.TypeTheory.Calculi.CumulativePiSigmaId
open Mettapedia.TypeTheory.UniverseLevel
open Presentation Presentation.Declaration Presentation.FormationSensitive
open Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId.Presentation.AlgebraicSchema
  (SchemaTable SchemaFamily)
open SetProfile (baseName constantName numTy zeroNative sucNative addNative
  eqNumNative holdsName targetRules)
open CertifiedTransforms (stepOver shared sharedBody)
open Mettapedia.Logic

/-! ## Names -/

def jName : DeclName := .mkSimple "id:eliminate"
def numRecName : DeclName := .mkSimple "num-rec"
def eqAtName : DeclName := .mkSimple "eqAt"
def sucMoveName : DeclName := .mkSimple "sucMove"
def keepName : DeclName := .mkSimple "keepCert"
def transportName : DeclName := .mkSimple "transportCert"
def composeName : DeclName := .mkSimple "composeCert"
def iterName : DeclName := .mkSimple "iterCert"
def returnIterName : DeclName := .mkSimple "returnIter"
def sucStepName : DeclName := .mkSimple "sucStep"
def holdsAtName : DeclName := .mkSimple "holdsAt"
def holdsMoveName : DeclName := .mkSimple "holdsMove"
def holdsStepName : DeclName := .mkSimple "holdsStep"

/-! ## Terms -/

section Terms

variable {n : Nat}

abbrev U0 : Tower.Tm n := sortTm Tower.zero
abbrev numT : Tower.Tm n := .const (baseName .num)

def app2 (function first second : Tower.Tm n) : Tower.Tm n :=
  .app (.app function first) second

def app4 (function a b c d : Tower.Tm n) : Tower.Tm n :=
  .app (.app (.app (.app function a) b) c) d

def app6 (function a b c d e f : Tower.Tm n) : Tower.Tm n :=
  .app (.app (app4 function a b c d) e) f

def jApp (carrier point motive reflCase endpoint path : Tower.Tm n) : Tower.Tm n :=
  app6 (.const jName) carrier point motive reflCase endpoint path

def numRecApp (motive zeroCase succCase number : Tower.Tm n) : Tower.Tm n :=
  app4 (.const numRecName) motive zeroCase succCase number

def eqAtApp (number : Tower.Tm n) : Tower.Tm n := .app (.const eqAtName) number

def holdsAtApp (number : Tower.Tm n) : Tower.Tm n := .app (.const holdsAtName) number

/-- `iterCert n A P step`, awaiting the value and its evidence. -/
def iterPartial (count carrier family step : Tower.Tm n) : Tower.Tm n :=
  app4 (.const iterName) count carrier family step

def iterApp (count carrier family step value evidence : Tower.Tm n) : Tower.Tm n :=
  app2 (iterPartial count carrier family step) value evidence

def transportApp (carrier family function move value evidence : Tower.Tm n) : Tower.Tm n :=
  app6 (.const transportName) carrier family function move value evidence

/-- The supplied-family step type `Π x : A. P x → Σ y : A. P y` for a
function-valued family `P`, the second newest variable `A` and newest `P`. -/
def stepFamily : Tower.Tm (n + 2) :=
  stepOver (.var 1) (.app (.var 1) (.var 0))

end Terms

/-! ## Declared types -/

/-- `id:eliminate` at carrier and motive level zero: the language-owned
eliminator with its two level parameters instantiated. -/
def jType : Tower.Tm 0 :=
  RussellTarski.substLevelsTm (fun _ => Tower.zero)
    NativeIndexedFamilies.Intrinsic.identityEliminateType

/-- `num-rec : Π P. P zero → (Π v. P v → P (suc v)) → Π t. P t`. -/
def numRecType : Tower.Tm 0 :=
  .pi (.pi numT U0)
    (.pi (.app (.var 0) zeroNative)
      (.pi (.pi numT (.pi (.app (.var 2) (.var 0)) (.app (.var 3) (sucNative (.var 1)))))
        (.pi numT (.app (.var 3) (.var 0)))))

def eqAtType : Tower.Tm 0 := .pi numT U0

def sucMoveType : Tower.Tm 0 :=
  .pi numT (.pi (eqAtApp (.var 0)) (eqAtApp (sucNative (.var 1))))

def keepType : Tower.Tm 0 :=
  .pi U0 (.pi (.pi (.var 0) U0)
    (.pi (.var 1) (.pi (.app (.var 1) (.var 0)) (.sigma (.var 3) (.app (.var 3) (.var 0))))))

def transportType : Tower.Tm 0 :=
  .pi U0 (.pi (.pi (.var 0) U0)
    (.pi (.pi (.var 1) (.var 2))
      (.pi (.pi (.var 2) (.pi (.app (.var 2) (.var 0)) (.app (.var 3) (.app (.var 2) (.var 1)))))
        (.pi (.var 3) (.pi (.app (.var 3) (.var 0))
          (.sigma (.var 5) (.app (.var 5) (.var 0))))))))

def composeType : Tower.Tm 0 :=
  .pi U0 (.pi (.pi (.var 0) U0)
    (.pi stepFamily (.pi (rename wk stepFamily)
      (.pi (.var 3) (.pi (.app (.var 3) (.var 0)) (.sigma (.var 5) (.app (.var 5) (.var 0))))))))

def iterType : Tower.Tm 0 :=
  .pi numT (.pi U0 (.pi (.pi (.var 0) U0)
    (.pi stepFamily
      (.pi (.var 2) (.pi (.app (.var 2) (.var 0)) (.sigma (.var 4) (.app (.var 4) (.var 0))))))))

def returnIterType : Tower.Tm 0 :=
  .pi U0 (.pi (.pi (.var 0) U0)
    (.pi numT (.pi (rename wk stepFamily)
      (.pi (.var 3) (.pi (.app (.var 3) (.var 0)) (.sigma (.var 5) (.app (.var 5) (.var 0))))))))

def sucStepType : Tower.Tm 0 :=
  .pi numT (.pi (eqAtApp (.var 0)) (.sigma numT (eqAtApp (.var 0))))

def holdsAtType : Tower.Tm 0 := .pi numT U0

def holdsMoveType : Tower.Tm 0 :=
  .pi numT (.pi (holdsAtApp (.var 0)) (holdsAtApp (sucNative (.var 1))))

def holdsStepType : Tower.Tm 0 :=
  .pi numT (.pi (holdsAtApp (.var 0)) (.sigma numT (holdsAtApp (.var 0))))

/-! ## Stored equations -/

/-- The translated induction step of the source proof of `zero-add`: the third
argument of its native proof term. -/
def zeroAddStepTerm : Tower.Tm 0 :=
  .lam (.lam
    (.app
      (.app
        (.app
          (.app
            (.app (.const SetProfile.substName)
              (.lam (eqNumNative (sucNative (addNative zeroNative (.var 2)))
                (sucNative (.var 0)))))
            (addNative zeroNative (.var 1)))
          (.var 1))
        (.var 0))
      (.app (.const SetProfile.reflName) (sucNative (addNative zeroNative (.var 1))))))

theorem zeroAddTerm_step :
    SetProfile.zeroAddTerm =
      .app (.app (.app (.const SetProfile.inductionName)
          (.lam (eqNumNative (addNative zeroNative (.var 0)) (.var 0))))
        (.app (.const SetProfile.reflName) zeroNative))
        zeroAddStepTerm :=
  rfl

/-- `id:eliminate A x P d x (refl x) = d`. -/
abbrev jIota : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity :=
  ⟨4, (jApp (.var 3) (.var 2) (.var 1) (.var 0) (.var 2) (.refl (.var 2)), .var 0)⟩

abbrev numRecZeroEquation : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity :=
  ⟨3, (numRecApp (.var 2) (.var 1) (.var 0) zeroNative, .var 1)⟩

abbrev numRecSucEquation : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity :=
  ⟨4, (numRecApp (.var 3) (.var 2) (.var 1) (sucNative (.var 0)),
    app2 (.var 1) (.var 0) (numRecApp (.var 3) (.var 2) (.var 1) (.var 0)))⟩

abbrev eqAtEquation : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity :=
  ⟨1, (eqAtApp (.var 0), .id numT (addNative zeroNative (.var 0)) (.var 0))⟩

/-- The motive `λ y p. suc (add zero n) = suc y` of the successor move. -/
def sucMotive {n : Nat} (number : Tower.Tm n) : Tower.Tm n :=
  .lam (.lam (.id numT (sucNative (addNative zeroNative (rename wk (rename wk number))))
    (sucNative (.var 1))))

abbrev sucMoveEquation : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity :=
  ⟨2, (app2 (.const sucMoveName) (.var 1) (.var 0),
    jApp numT (addNative zeroNative (.var 1)) (sucMotive (.var 1))
      (.refl (sucNative (addNative zeroNative (.var 1)))) (.var 1) (.var 0))⟩

abbrev keepEquation : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity :=
  ⟨4, (app4 (.const keepName) (.var 3) (.var 2) (.var 1) (.var 0), .pair (.var 1) (.var 0))⟩

abbrev transportEquation : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity :=
  ⟨6, (transportApp (.var 5) (.var 4) (.var 3) (.var 2) (.var 1) (.var 0),
    .pair (.app (.var 3) (.var 1)) (app2 (.var 2) (.var 1) (.var 0)))⟩

abbrev composeEquation : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity :=
  ⟨6, (app6 (.const composeName) (.var 5) (.var 4) (.var 3) (.var 2) (.var 1) (.var 0),
    shared (.var 3) (.var 2) (.var 1) (.var 0))⟩

abbrev iterZeroEquation : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity :=
  ⟨5, (iterApp zeroNative (.var 4) (.var 3) (.var 2) (.var 1) (.var 0), .pair (.var 1) (.var 0))⟩

abbrev iterSucEquation : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity :=
  ⟨6, (iterApp (sucNative (.var 5)) (.var 4) (.var 3) (.var 2) (.var 1) (.var 0),
    shared (.var 2) (iterPartial (.var 5) (.var 4) (.var 3) (.var 2)) (.var 1) (.var 0))⟩

abbrev returnIterEquation : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity :=
  ⟨1, (.app (.const returnIterName) (.var 0),
    .lam (.lam (.lam (.lam (.lam
      (iterApp (.var 3) (.var 5) (.var 4) (.var 2) (.var 1) (.var 0)))))))⟩

abbrev sucStepEquation : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity :=
  ⟨2, (app2 (.const sucStepName) (.var 1) (.var 0),
    transportApp numT (.const eqAtName) (.const (constantName .suc)) (.const sucMoveName)
      (.var 1) (.var 0))⟩

abbrev holdsAtEquation : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity :=
  ⟨1, (holdsAtApp (.var 0), FormationSensitiveHOLGenericProofFamily.proof holdsName
    (eqNumNative (addNative zeroNative (.var 0)) (.var 0)))⟩

abbrev holdsMoveEquation : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity :=
  ⟨2, (app2 (.const holdsMoveName) (.var 1) (.var 0),
    app2 (liftClosed zeroAddStepTerm) (.var 1) (.var 0))⟩

abbrev holdsStepEquation : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity :=
  ⟨2, (app2 (.const holdsStepName) (.var 1) (.var 0),
    transportApp numT (.const holdsAtName) (.const (constantName .suc)) (.const holdsMoveName)
      (.var 1) (.var 0))⟩

/-- The stored rules of the package, in the order the checker lists them. -/
def packageEquations : SchemaTable Tower.Head :=
  [jIota, numRecZeroEquation, numRecSucEquation, eqAtEquation, sucMoveEquation, keepEquation,
   transportEquation, composeEquation, iterZeroEquation, iterSucEquation, returnIterEquation,
   sucStepEquation, holdsAtEquation, holdsMoveEquation, holdsStepEquation]

def packageDeclarations : Signature Tower.Head where
  entries := (Signature.ofList
    [(jName, { type := jType }),
     (numRecName, { type := numRecType }),
     (eqAtName, { type := eqAtType }),
     (sucMoveName, { type := sucMoveType }),
     (keepName, { type := keepType }),
     (transportName, { type := transportType }),
     (composeName, { type := composeType }),
     (iterName, { type := iterType }),
     (returnIterName, { type := returnIterType }),
     (sucStepName, { type := sucStepType }),
     (holdsAtName, { type := holdsAtType }),
     (holdsMoveName, { type := holdsMoveType }),
     (holdsStepName, { type := holdsStepType })]).entries
  computation := SchemaFamily.computation packageEquations.family

/-- The rules of the whole program: the `set:` profile, its proof family and
assumed facts, and the package. -/
noncomputable abbrev packageRules : Rules Tower.Head :=
  extendRules targetRules packageDeclarations


/-! ## Formation toolkit for the cumulative tower -/

section Toolkit

variable {n : Nat}

noncomputable abbrev R := packageRules

def level1 : LevelExpr := .succ Tower.zero

abbrev U1 : Tower.Tm n := sortTm level1

theorem isUniverseAt (level : LevelExpr) : R.isUniverse (.sort level) :=
  Tower.IsUniverse.sort level

theorem sort_typed {Γ : Tower.Ctx n} (level : LevelExpr) :
    Typing R Γ (sortTm level) (sortTm (.succ level)) :=
  .headType (Tower.HeadTyping.sort level)

theorem U0_typed {Γ : Tower.Ctx n} : Typing R Γ U0 U1 := sort_typed Tower.zero

theorem raise {Γ : Tower.Ctx n} {type : Tower.Tm n} (typed : Typing R Γ type U0) :
    Typing R Γ type U1 :=
  .cumul typed (fun valuation => by simp [LevelExpr.eval, Tower.zero, level1])

/-- A dependent function type over a universe, formed at the join and
lowered to that universe. -/
theorem pi_at {Γ : Tower.Ctx n} {domain : Tower.Tm n} {codomain : Tower.Tm (n + 1)}
    {level : LevelExpr}
    (domainTyped : Typing R Γ domain (sortTm level))
    (codomainTyped : Typing R (.snoc Γ domain) codomain (sortTm level)) :
    Typing R Γ (.pi domain codomain) (sortTm level) :=
  .cumul (.piForm domainTyped (isUniverseAt level) codomainTyped (isUniverseAt level)
      (Tower.Join.sorts level level))
    (fun valuation => by simp [LevelExpr.eval])

theorem sigma_at {Γ : Tower.Ctx n} {domain : Tower.Tm n} {codomain : Tower.Tm (n + 1)}
    {level : LevelExpr}
    (domainTyped : Typing R Γ domain (sortTm level))
    (codomainTyped : Typing R (.snoc Γ domain) codomain (sortTm level)) :
    Typing R Γ (.sigma domain codomain) (sortTm level) :=
  .cumul (.sigmaForm domainTyped (isUniverseAt level) codomainTyped (isUniverseAt level)
      (Tower.Join.sorts level level))
    (fun valuation => by simp [LevelExpr.eval])

theorem id_at {Γ : Tower.Ctx n} {carrier left right : Tower.Tm n} {level : LevelExpr}
    (carrierTyped : Typing R Γ carrier (sortTm level))
    (leftTyped : Typing R Γ left carrier) (rightTyped : Typing R Γ right carrier) :
    Typing R Γ (.id carrier left right) (sortTm level) :=
  .idForm carrierTyped (isUniverseAt level) leftTyped rightTyped

end Toolkit

/-! ## Inherited declarations -/

/-- The profile embeds in the program's rules: source, proof family,
assumed facts, package. -/
theorem profileMorphism :
    SetProfile.rules.Morphism packageRules (fun head => head) := by
  have first := FormationSensitiveHOLGenericProofFamily.sourceMorphism
    SetProfile.signature holdsName
  have second := includeMorphism SetProfile.proofRules
    SetProfile.assumptionDeclarations
  have third := includeMorphism targetRules packageDeclarations
  exact {
    headTyping := fun typing => typing
    isUniverse := fun isU => isU
    join := fun joined => joined
    cumulative := fun order => order
    headEq := fun equality => equality
    constantType := by
      intro name type known
      simpa only [Tm.mapHead_id] using
        third.constantType (second.constantType (first.constantType known))
    computation := by
      intro n left right step
      simpa only [Tm.mapHead_id] using
        third.computation (second.computation (first.computation step))
  }

theorem targetMorphism : targetRules.Morphism packageRules (fun head => head) :=
  includeMorphism targetRules packageDeclarations

theorem include_profile {n : Nat} {Γ : Tower.Ctx n} {term type : Tower.Tm n}
    (typed : Typing SetProfile.rules Γ term type) : Typing R Γ term type := by
  simpa only [Ctx.mapHead_id, Tm.mapHead_id] using typed.mapHead profileMorphism

theorem include_target {n : Nat} {Γ : Tower.Ctx n} {term type : Tower.Tm n}
    (typed : Typing targetRules Γ term type) : Typing R Γ term type := by
  simpa only [Ctx.mapHead_id, Tm.mapHead_id] using typed.mapHead targetMorphism

theorem include_profile_conversion {n : Nat} {left right : Tower.Tm n}
    (conversion : Conv SetProfile.rules.headEq left right
      SetProfile.rules.computation) :
    Conv R.headEq left right R.computation := by
  have mapped := conversion.mapHead (fun head => head)
    profileMorphism.headEq profileMorphism.computation
  simpa only [Tm.mapHead_id] using mapped

theorem numT_typed {n : Nat} {Γ : Tower.Ctx n} : Typing R Γ numT U0 := by
  have typed := SetProfile.sort_formed (context := Γ)
    (SetProfile.lookup_base .num)
  exact include_profile typed

/-- A profile constant at its simple type, in any context. -/
theorem constant_typed {n : Nat} {Γ : Tower.Ctx n} {type : HOL.Ty SetProfile.SetBase}
    (symbol : SetProfile.SetConst type) :
    Typing R Γ (.const (constantName symbol))
      (FormationSensitiveHOLInterface.typeAt SetProfile.types n type) := by
  have closed := SetProfile.declared_typed (SetProfile.lookup_constant symbol)
  have lifted := FormationSensitiveHOLInterface.closed_typed closed Γ
  simp only [liftClosed, FormationSensitiveHOLInterface.typeAt_rename] at lifted
  exact include_profile lifted

theorem zeroNative_typed {n : Nat} {Γ : Tower.Ctx n} : Typing R Γ zeroNative numT :=
  constant_typed .zero

theorem sucNative_typed {n : Nat} {Γ : Tower.Ctx n} {number : Tower.Tm n}
    (typed : Typing R Γ number numT) : Typing R Γ (sucNative number) numT :=
  Typing.appElim (B := numT) (constant_typed .suc) typed

theorem addNative_typed {n : Nat} {Γ : Tower.Ctx n} {left right : Tower.Tm n}
    (leftTyped : Typing R Γ left numT) (rightTyped : Typing R Γ right numT) :
    Typing R Γ (addNative left right) numT :=
  Typing.appElim (B := numT) (Typing.appElim (B := .pi numT numT) (constant_typed .add) leftTyped)
    rightTyped


/-! ## Formation of the declared types -/

/-- The instantiated eliminator type, spelled out. -/
theorem jType_eq : jType =
    .pi U0 (.pi (.var 0)
      (.pi (.pi (.var 1) (.pi (.id (.var 2) (.var 1) (.var 0)) U0))
        (.pi (.app (.app (.var 0) (.var 1)) (.refl (.var 1)))
          (.pi (.var 3) (.pi (.id (.var 4) (.var 3) (.var 0))
            (.app (.app (.var 3) (.var 1)) (.var 0))))))) :=
  rfl

theorem lowered_zero : R.cumulative (.sort (.max Tower.zero Tower.zero)) (.sort Tower.zero) :=
  fun valuation => by simp [LevelExpr.eval]

theorem jType_formed : Typing R .nil jType U1 := by
  rw [jType_eq]
  -- the motive type, in the context `A, x`
  have motiveTyped : Typing R (.snoc (.snoc .nil U0) (.var 0))
      (.pi (.var 1) (.pi (.id (.var 2) (.var 1) (.var 0)) U0)) U1 :=
    pi_at (raise (Typing.var 1))
      (pi_at (raise (id_at (Typing.var 2) (Typing.var 1) (Typing.var 0))) U0_typed)
  -- the reflexivity case, in the context `A, x, P`
  have reflTyped : Typing R
      (.snoc (.snoc (.snoc .nil U0) (.var 0)) (.pi (.var 1) (.pi (.id (.var 2) (.var 1) (.var 0)) U0)))
      (.app (.app (.var 0) (.var 1)) (.refl (.var 1))) U0 :=
    Typing.appElim (B := U0)
      (Typing.appElim (B := .pi (.id (.var 3) (.var 2) (.var 0)) U0) (Typing.var 0) (Typing.var 1))
      (Typing.reflIntro (Typing.var 1))
  -- the result, in the context `A, x, P, d`
  have resultTyped : Typing R
      (.snoc (.snoc (.snoc (.snoc .nil U0) (.var 0))
        (.pi (.var 1) (.pi (.id (.var 2) (.var 1) (.var 0)) U0)))
        (.app (.app (.var 0) (.var 1)) (.refl (.var 1))))
      (.pi (.var 3) (.pi (.id (.var 4) (.var 3) (.var 0)) (.app (.app (.var 3) (.var 1)) (.var 0))))
      U0 :=
    pi_at (Typing.var 3)
      (pi_at (id_at (Typing.var 4) (Typing.var 3) (Typing.var 0))
        (Typing.appElim (B := U0)
          (Typing.appElim (B := .pi (.id (.var 6) (.var 5) (.var 0)) U0) (Typing.var 3)
            (Typing.var 1))
          (Typing.var 0)))
  exact pi_at U0_typed (pi_at (raise (Typing.var 0))
    (pi_at motiveTyped (pi_at (raise reflTyped) (raise resultTyped))))

/-- `Π x : A. P x → Σ y : A. P y`, for `P` a function into the lowest sort. -/
theorem stepFamily_formed {n : Nat} {Γ : Tower.Ctx n} :
    Typing R (.snoc (.snoc Γ U0) (.pi (.var 0) U0)) stepFamily U0 :=
  CertifiedTransforms.stepOver_typed_cumulative (Typing.var 1)
    (Typing.appElim (B := U0) (Typing.var 1) (Typing.var 0))
    (isUniverseAt Tower.zero) (Tower.Join.sorts _ _) lowered_zero

theorem iterType_formed : Typing R .nil iterType U1 :=
  pi_at (raise numT_typed) (pi_at U0_typed (pi_at (pi_at (raise (Typing.var 0)) U0_typed)
    (pi_at (raise stepFamily_formed)
      (pi_at (raise (Typing.var 2))
        (pi_at (raise (Typing.appElim (B := U0) (Typing.var 2) (Typing.var 0)))
          (raise (sigma_at (Typing.var 4)
            (Typing.appElim (B := U0) (Typing.var 4) (Typing.var 0)))))))))


/-! ## Package lookups -/

theorem target_none {spelling : String}
    (notAll : spelling.toList.take 4 ≠ ['a', 'l', 'l', '@'])
    (notEq : spelling.toList.take 3 ≠ ['e', 'q', '@'])
    (notFixed : SetProfile.fixedEntry (.mkSimple spelling) = none)
    (notHolds : Lean.Name.mkSimple spelling ≠ holdsName)
    (notAssumed :
      SetProfile.assumptionDeclarations.typeOf? (.mkSimple spelling) = none) :
    targetRules.constantType (.mkSimple spelling) = none := by
  have profileNone : SetProfile.rules.constantType (.mkSimple spelling) = none := by
    rw [SetProfile.lookup_fixed notAll notEq, notFixed]
    rfl
  have proofNone := SetProfile.proofRules_lookup_none profileNone notHolds
  change combinedType SetProfile.proofRules
    SetProfile.assumptionDeclarations _ = none
  rw [combinedType, proofNone]
  exact notAssumed

/-- A name the reader reads as no instance, with no fixed declaration, other
than the proof family and no assumption constant, is fresh for the target. -/
theorem target_none_of_reader {name : DeclName}
    (notAll : SetProfile.allInstance? name = none)
    (notEq : SetProfile.eqInstance? name = none)
    (notFixed : SetProfile.fixedEntry name = none)
    (notHolds : name ≠ holdsName)
    (notAssumed : SetProfile.assumptionDeclarations.typeOf? name = none) :
    targetRules.constantType name = none := by
  have profileNone : SetProfile.rules.constantType name = none := by
    rw [SetProfile.lookup_fixedName notAll notEq, notFixed]
    rfl
  have proofNone := SetProfile.proofRules_lookup_none profileNone notHolds
  change combinedType SetProfile.proofRules SetProfile.assumptionDeclarations _ = none
  rw [combinedType, proofNone]
  exact notAssumed

theorem package_lookup {spelling : String} {type : Tower.Tm 0}
    (fresh : targetRules.constantType (.mkSimple spelling) = none)
    (listed : packageDeclarations.typeOf? (.mkSimple spelling) = some type) :
    R.constantType (.mkSimple spelling) = some type :=
  combinedType_of_signature targetRules packageDeclarations fresh listed

theorem lookup_j : R.constantType jName = some jType :=
  package_lookup (target_none_of_reader (by decide) (by decide) rfl (by decide) rfl) rfl
theorem lookup_numRec : R.constantType numRecName = some numRecType :=
  package_lookup (target_none_of_reader (by decide) (by decide) rfl (by decide) rfl) rfl
theorem lookup_eqAt : R.constantType eqAtName = some eqAtType :=
  package_lookup (target_none_of_reader (by decide) (by decide) rfl (by decide) rfl) rfl
theorem lookup_sucMove : R.constantType sucMoveName = some sucMoveType :=
  package_lookup (target_none_of_reader (by decide) (by decide) rfl (by decide) rfl) rfl
theorem lookup_keep : R.constantType keepName = some keepType :=
  package_lookup (target_none_of_reader (by decide) (by decide) rfl (by decide) rfl) rfl
theorem lookup_transport : R.constantType transportName = some transportType :=
  package_lookup (target_none_of_reader (by decide) (by decide) rfl (by decide) rfl) rfl
theorem lookup_compose : R.constantType composeName = some composeType :=
  package_lookup (target_none_of_reader (by decide) (by decide) rfl (by decide) rfl) rfl
theorem lookup_iter : R.constantType iterName = some iterType :=
  package_lookup (target_none_of_reader (by decide) (by decide) rfl (by decide) rfl) rfl
theorem lookup_returnIter : R.constantType returnIterName = some returnIterType :=
  package_lookup (target_none_of_reader (by decide) (by decide) rfl (by decide) rfl) rfl
theorem lookup_sucStep : R.constantType sucStepName = some sucStepType :=
  package_lookup (target_none_of_reader (by decide) (by decide) rfl (by decide) rfl) rfl
theorem lookup_holdsAt : R.constantType holdsAtName = some holdsAtType :=
  package_lookup (target_none_of_reader (by decide) (by decide) rfl (by decide) rfl) rfl
theorem lookup_holdsMove : R.constantType holdsMoveName = some holdsMoveType :=
  package_lookup (target_none_of_reader (by decide) (by decide) rfl (by decide) rfl) rfl
theorem lookup_holdsStep : R.constantType holdsStepName = some holdsStepType :=
  package_lookup (target_none_of_reader (by decide) (by decide) rfl (by decide) rfl) rfl

/-- A package constant at its declared type, in any context. -/
theorem declared_typed {name : DeclName} {type : Tower.Tm 0} {level : LevelExpr}
    (lookup : R.constantType name = some type) (formed : Typing R .nil type (sortTm level))
    {n : Nat} (Γ : Tower.Ctx n) : Typing R Γ (.const name) (liftClosed type) :=
  .const lookup formed (isUniverseAt level)

/-! ### The families `eqAt` and `holdsAt` -/

theorem eqAtType_formed : Typing R .nil eqAtType U1 :=
  pi_at (raise numT_typed) U0_typed

theorem holdsAtType_formed : Typing R .nil holdsAtType U1 :=
  pi_at (raise numT_typed) U0_typed

theorem eqAt_typed {n : Nat} {Γ : Tower.Ctx n} {number : Tower.Tm n}
    (typed : Typing R Γ number numT) : Typing R Γ (eqAtApp number) U0 :=
  Typing.appElim (B := U0) (declared_typed lookup_eqAt eqAtType_formed Γ) typed

theorem holdsAt_typed {n : Nat} {Γ : Tower.Ctx n} {number : Tower.Tm n}
    (typed : Typing R Γ number numT) : Typing R Γ (holdsAtApp number) U0 :=
  Typing.appElim (B := U0) (declared_typed lookup_holdsAt holdsAtType_formed Γ) typed

/-! ### The remaining declarations -/

theorem numRecType_formed : Typing R .nil numRecType U1 :=
  pi_at (pi_at (raise numT_typed) U0_typed)
    (pi_at (raise (Typing.appElim (B := U0) (Typing.var 0) zeroNative_typed))
      (pi_at
        (raise (pi_at numT_typed
          (pi_at (Typing.appElim (B := U0) (Typing.var 2) (Typing.var 0))
            (Typing.appElim (B := U0) (Typing.var 3) (sucNative_typed (Typing.var 1))))))
        (raise (pi_at numT_typed (Typing.appElim (B := U0) (Typing.var 3) (Typing.var 0))))))

theorem sucMoveType_formed : Typing R .nil sucMoveType U0 :=
  pi_at numT_typed (pi_at (eqAt_typed (Typing.var 0)) (eqAt_typed (sucNative_typed (Typing.var 1))))

theorem holdsMoveType_formed : Typing R .nil holdsMoveType U0 :=
  pi_at numT_typed
    (pi_at (holdsAt_typed (Typing.var 0)) (holdsAt_typed (sucNative_typed (Typing.var 1))))

theorem sucStepType_formed : Typing R .nil sucStepType U0 :=
  pi_at numT_typed (pi_at (eqAt_typed (Typing.var 0))
    (sigma_at numT_typed (eqAt_typed (Typing.var 0))))

theorem holdsStepType_formed : Typing R .nil holdsStepType U0 :=
  pi_at numT_typed (pi_at (holdsAt_typed (Typing.var 0))
    (sigma_at numT_typed (holdsAt_typed (Typing.var 0))))

theorem keepType_formed : Typing R .nil keepType U1 :=
  pi_at U0_typed (pi_at (pi_at (raise (Typing.var 0)) U0_typed)
    (pi_at (raise (Typing.var 1))
      (pi_at (raise (Typing.appElim (B := U0) (Typing.var 1) (Typing.var 0)))
        (raise (sigma_at (Typing.var 3) (Typing.appElim (B := U0) (Typing.var 3) (Typing.var 0)))))))

theorem transportType_formed : Typing R .nil transportType U1 :=
  pi_at U0_typed (pi_at (pi_at (raise (Typing.var 0)) U0_typed)
    (pi_at (raise (pi_at (Typing.var 1) (Typing.var 2)))
      (pi_at
        (raise (pi_at (Typing.var 2)
          (pi_at (Typing.appElim (B := U0) (Typing.var 2) (Typing.var 0))
            (Typing.appElim (B := U0) (Typing.var 3)
              (Typing.appElim (B := .var 5) (Typing.var 2) (Typing.var 1))))))
        (pi_at (raise (Typing.var 3))
          (pi_at (raise (Typing.appElim (B := U0) (Typing.var 3) (Typing.var 0)))
            (raise (sigma_at (Typing.var 5)
              (Typing.appElim (B := U0) (Typing.var 5) (Typing.var 0)))))))))

theorem composeType_formed : Typing R .nil composeType U1 :=
  pi_at U0_typed (pi_at (pi_at (raise (Typing.var 0)) U0_typed)
    (pi_at (raise stepFamily_formed)
      (pi_at (raise (stepFamily_formed.weaken (extension := stepFamily)))
        (pi_at (raise (Typing.var 3))
          (pi_at (raise (Typing.appElim (B := U0) (Typing.var 3) (Typing.var 0)))
            (raise (sigma_at (Typing.var 5)
              (Typing.appElim (B := U0) (Typing.var 5) (Typing.var 0)))))))))

theorem returnIterType_formed : Typing R .nil returnIterType U1 :=
  pi_at U0_typed (pi_at (pi_at (raise (Typing.var 0)) U0_typed)
    (pi_at (raise numT_typed)
      (pi_at (raise (stepFamily_formed.weaken (extension := numT)))
        (pi_at (raise (Typing.var 3))
          (pi_at (raise (Typing.appElim (B := U0) (Typing.var 3) (Typing.var 0)))
            (raise (sigma_at (Typing.var 5)
              (Typing.appElim (B := U0) (Typing.var 5) (Typing.var 0)))))))))


/-! ## Typed equations

`set:define` checks both endpoints of an equation at the result type in the
equation's pattern telescope.  A typed equation records that judgment.  Its
instances at a typed substitution are typed at the instantiated type: this is
preservation for every firing whose arguments inhabit the telescope, the only
firings the evaluator makes. -/

structure TypedEquation (equation : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity) where
  telescope : Tower.Ctx equation.1
  type : Tower.Tm equation.1
  left_typed : Typing R telescope equation.2.1 type
  right_typed : Typing R telescope equation.2.2 type

/-- An equation instance at a typed substitution: redex and contractum share the
instantiated type. -/
theorem TypedEquation.instance_typed
    {equation : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity} (typed : TypedEquation equation)
    {m : Nat} {Δ : Tower.Ctx m} {substitution : Sub Tower.Head equation.1 m}
    (morphism : FormationSensitive.CtxMor R typed.telescope Δ substitution) :
    Typing R Δ (subst substitution equation.2.1) (subst substitution typed.type) ∧
      Typing R Δ (subst substitution equation.2.2) (subst substitution typed.type) :=
  ⟨typed.left_typed.substitute morphism, typed.right_typed.substitute morphism⟩

/-! ### Identity elimination -/

abbrev jTelescope : Tower.Ctx 4 :=
  .snoc (.snoc (.snoc (.snoc .nil U0) (.var 0))
    (.pi (.var 1) (.pi (.id (.var 2) (.var 1) (.var 0)) U0)))
    (.app (.app (.var 0) (.var 1)) (.refl (.var 1)))

theorem j_typed {n : Nat} (Γ : Tower.Ctx n) : Typing R Γ (.const jName) (liftClosed jType) :=
  declared_typed lookup_j jType_formed Γ

def jEquationTyped : TypedEquation jIota where
  telescope := jTelescope
  type := .app (.app (.var 1) (.var 2)) (.refl (.var 2))
  left_typed := by
    have j0 := j_typed jTelescope
    rw [jType_eq] at j0
    have j1 := Typing.appElim j0 (Typing.var 3)
    have j2 := Typing.appElim j1 (Typing.var 2)
    have j3 := Typing.appElim j2 (Typing.var 1)
    have j4 := Typing.appElim j3 (Typing.var 0)
    have j5 := Typing.appElim j4 (Typing.var 2)
    have j6 := Typing.appElim j5 (Typing.reflIntro (Typing.var 2))
    exact j6
  right_typed := Typing.var 0

/-! ### The recursor of `num` -/

abbrev numRecStepType {n : Nat} : Tower.Tm (n + 2) :=
  .pi numT (.pi (.app (.var 2) (.var 0)) (.app (.var 3) (sucNative (.var 1))))

abbrev numRecTelescope : Tower.Ctx 3 :=
  .snoc (.snoc (.snoc .nil (.pi numT U0)) (.app (.var 0) zeroNative)) numRecStepType

theorem numRec_typed {n : Nat} (Γ : Tower.Ctx n) :
    Typing R Γ (.const numRecName) (liftClosed numRecType) :=
  declared_typed lookup_numRec numRecType_formed Γ

def numRecZeroTyped : TypedEquation numRecZeroEquation where
  telescope := numRecTelescope
  type := .app (.var 2) zeroNative
  left_typed := by
    have r1 := Typing.appElim (numRec_typed numRecTelescope) (Typing.var 2)
    have r2 := Typing.appElim r1 (Typing.var 1)
    have r3 := Typing.appElim r2 (Typing.var 0)
    exact Typing.appElim r3 zeroNative_typed
  right_typed := Typing.var 1

def numRecSucTyped : TypedEquation numRecSucEquation where
  telescope := .snoc numRecTelescope numT
  type := .app (.var 3) (sucNative (.var 0))
  left_typed := by
    have r1 := Typing.appElim (numRec_typed (.snoc numRecTelescope numT)) (Typing.var 3)
    have r2 := Typing.appElim r1 (Typing.var 2)
    have r3 := Typing.appElim r2 (Typing.var 1)
    exact Typing.appElim r3 (sucNative_typed (Typing.var 0))
  right_typed := by
    have r1 := Typing.appElim (numRec_typed (.snoc numRecTelescope numT)) (Typing.var 3)
    have r2 := Typing.appElim r1 (Typing.var 2)
    have r3 := Typing.appElim r2 (Typing.var 1)
    have recursive := Typing.appElim r3 (Typing.var 0)
    have s1 := Typing.appElim (Typing.var (R := R) (Γ := .snoc numRecTelescope numT) 1)
      (Typing.var 0)
    exact Typing.appElim s1 recursive

/-! ### The families -/

def eqAtTyped : TypedEquation eqAtEquation where
  telescope := .snoc .nil numT
  type := U0
  left_typed := eqAt_typed (Typing.var 0)
  right_typed := id_at numT_typed (addNative_typed zeroNative_typed (Typing.var 0)) (Typing.var 0)

/-- The sort of propositions of the profile. -/
abbrev propT {n : Nat} : Tower.Tm n := .const SetProfile.propName

theorem propT_typed {n : Nat} {Γ : Tower.Ctx n} : Typing R Γ propT U0 :=
  include_profile (SetProfile.sort_formed SetProfile.lookup_prop)

/-- The represented equality of numbers is a proposition. -/
theorem eqNum_typed {n : Nat} {Γ : Tower.Ctx n} {left right : Tower.Tm n}
    (leftTyped : Typing R Γ left numT) (rightTyped : Typing R Γ right numT) :
    Typing R Γ (eqNumNative left right) propT := by
  have equality := SetProfile.declared_typed
    (SetProfile.lookup_eqName numTy)
  have lifted := FormationSensitiveHOLInterface.closed_typed equality Γ
  simp only [liftClosed, FormationSensitiveHOLInterface.typeAt_rename] at lifted
  exact Typing.appElim (B := propT)
    (Typing.appElim (B := .pi numT propT) (include_profile lifted) leftTyped) rightTyped

/-- The proof family at a proposition is a type of the lowest sort. -/
theorem proof_typed {n : Nat} {Γ : Tower.Ctx n} {proposition : Tower.Tm n}
    (typed : Typing R Γ proposition propT) :
    Typing R Γ (FormationSensitiveHOLGenericProofFamily.proof holdsName proposition) U0 := by
  have family := FormationSensitiveHOLGenericProofFamily.proofConstant_typed
    SetProfile.signature holdsName SetProfile.holdsName_fresh Γ
  have familyHere : Typing R Γ (.const holdsName)
      (liftClosed (FormationSensitiveHOLGenericProofFamily.proofType SetProfile.signature)) := by
    have mapped := family.mapHead (includeMorphism SetProfile.proofRules
      SetProfile.assumptionDeclarations)
    simp only [Ctx.mapHead_id, Tm.mapHead_id] at mapped
    exact include_target mapped
  exact Typing.appElim (B := U0) familyHere typed

theorem holdsAt_proposition_typed {n : Nat} {Γ : Tower.Ctx n} {number : Tower.Tm n}
    (typed : Typing R Γ number numT) :
    Typing R Γ (FormationSensitiveHOLGenericProofFamily.proof holdsName
      (eqNumNative (addNative zeroNative number) number)) U0 :=
  proof_typed (eqNum_typed (addNative_typed zeroNative_typed typed) typed)

def holdsAtTyped : TypedEquation holdsAtEquation where
  telescope := .snoc .nil numT
  type := U0
  left_typed := holdsAt_typed (Typing.var 0)
  right_typed := holdsAt_proposition_typed (Typing.var 0)

/-! ### Keeping and iterating from zero -/

abbrev familyTelescope : Tower.Ctx 2 := .snoc (.snoc .nil U0) (.pi (.var 0) U0)

theorem keep_typed {n : Nat} (Γ : Tower.Ctx n) :
    Typing R Γ (.const keepName) (liftClosed keepType) :=
  declared_typed lookup_keep keepType_formed Γ

theorem iter_typed {n : Nat} (Γ : Tower.Ctx n) :
    Typing R Γ (.const iterName) (liftClosed iterType) :=
  declared_typed lookup_iter iterType_formed Γ

def keepTyped : TypedEquation keepEquation where
  telescope := .snoc (.snoc familyTelescope (.var 1)) (.app (.var 1) (.var 0))
  type := .sigma (.var 3) (.app (.var 3) (.var 0))
  left_typed := by
    have k1 := Typing.appElim (keep_typed (.snoc (.snoc familyTelescope (.var 1))
      (.app (.var 1) (.var 0)))) (Typing.var 3)
    have k2 := Typing.appElim k1 (Typing.var 2)
    have k3 := Typing.appElim k2 (Typing.var 1)
    exact Typing.appElim k3 (Typing.var 0)
  right_typed :=
    Typing.pairIntro
      (sigma_at (Typing.var 3) (Typing.appElim (B := U0) (Typing.var 3) (Typing.var 0)))
      (isUniverseAt Tower.zero) (Typing.var 1) (Typing.var 0)

abbrev iterTelescope : Tower.Ctx 5 :=
  .snoc (.snoc (.snoc familyTelescope stepFamily) (.var 2)) (.app (.var 2) (.var 0))

def iterZeroTyped : TypedEquation iterZeroEquation where
  telescope := iterTelescope
  type := .sigma (.var 4) (.app (.var 4) (.var 0))
  left_typed := by
    have i1 := Typing.appElim (iter_typed iterTelescope) zeroNative_typed
    have i2 := Typing.appElim i1 (Typing.var 4)
    have i3 := Typing.appElim i2 (Typing.var 3)
    have i4 := Typing.appElim i3 (Typing.var 2)
    have i5 := Typing.appElim i4 (Typing.var 1)
    exact Typing.appElim i5 (Typing.var 0)
  right_typed :=
    Typing.pairIntro
      (sigma_at (Typing.var 4) (Typing.appElim (B := U0) (Typing.var 4) (Typing.var 0)))
      (isUniverseAt Tower.zero) (Typing.var 1) (Typing.var 0)


/-! ### Transport -/

/-- `Π x : A. P x → P (h x)`, in the context `A, P, h`. -/
abbrev moveType {n : Nat} : Tower.Tm (n + 3) :=
  .pi (.var 2) (.pi (.app (.var 2) (.var 0)) (.app (.var 3) (.app (.var 2) (.var 1))))

abbrev transportTelescope : Tower.Ctx 6 :=
  .snoc (.snoc (.snoc (.snoc familyTelescope (.pi (.var 1) (.var 2))) moveType) (.var 3))
    (.app (.var 3) (.var 0))

theorem transport_typed {n : Nat} (Γ : Tower.Ctx n) :
    Typing R Γ (.const transportName) (liftClosed transportType) :=
  declared_typed lookup_transport transportType_formed Γ

def transportTyped : TypedEquation transportEquation where
  telescope := transportTelescope
  type := .sigma (.var 5) (.app (.var 5) (.var 0))
  left_typed := by
    have t1 := Typing.appElim (transport_typed transportTelescope) (Typing.var 5)
    have t2 := Typing.appElim t1 (Typing.var 4)
    have t3 := Typing.appElim t2 (Typing.var 3)
    have t4 := Typing.appElim t3 (Typing.var 2)
    have t5 := Typing.appElim t4 (Typing.var 1)
    exact Typing.appElim t5 (Typing.var 0)
  right_typed := by
    have value := Typing.appElim (B := .var 6)
      (Typing.var (R := R) (Γ := transportTelescope) 3) (Typing.var 1)
    have moved := Typing.appElim
      (Typing.appElim (Typing.var (R := R) (Γ := transportTelescope) 2) (Typing.var 1))
      (Typing.var 0)
    exact Typing.pairIntro
      (sigma_at (Typing.var 5) (Typing.appElim (B := U0) (Typing.var 5) (Typing.var 0)))
      (isUniverseAt Tower.zero) value moved

/-! ### The successor steps over `eqAt` and `holdsAt` -/

theorem eqAtConst_typed {n : Nat} (Γ : Tower.Ctx n) :
    Typing R Γ (.const eqAtName) (liftClosed eqAtType) :=
  declared_typed lookup_eqAt eqAtType_formed Γ

theorem holdsAtConst_typed {n : Nat} (Γ : Tower.Ctx n) :
    Typing R Γ (.const holdsAtName) (liftClosed holdsAtType) :=
  declared_typed lookup_holdsAt holdsAtType_formed Γ

theorem sucMove_typed {n : Nat} (Γ : Tower.Ctx n) :
    Typing R Γ (.const sucMoveName) (liftClosed sucMoveType) :=
  declared_typed lookup_sucMove sucMoveType_formed Γ

theorem holdsMove_typed {n : Nat} (Γ : Tower.Ctx n) :
    Typing R Γ (.const holdsMoveName) (liftClosed holdsMoveType) :=
  declared_typed lookup_holdsMove holdsMoveType_formed Γ

theorem sucStep_typed {n : Nat} (Γ : Tower.Ctx n) :
    Typing R Γ (.const sucStepName) (liftClosed sucStepType) :=
  declared_typed lookup_sucStep sucStepType_formed Γ

theorem holdsStep_typed {n : Nat} (Γ : Tower.Ctx n) :
    Typing R Γ (.const holdsStepName) (liftClosed holdsStepType) :=
  declared_typed lookup_holdsStep holdsStepType_formed Γ

abbrev eqAtTelescope : Tower.Ctx 2 := .snoc (.snoc .nil numT) (eqAtApp (.var 0))

abbrev holdsAtTelescope : Tower.Ctx 2 := .snoc (.snoc .nil numT) (holdsAtApp (.var 0))

def sucStepTyped : TypedEquation sucStepEquation where
  telescope := eqAtTelescope
  type := .sigma numT (eqAtApp (.var 0))
  left_typed :=
    Typing.appElim (Typing.appElim (sucStep_typed eqAtTelescope) (Typing.var 1)) (Typing.var 0)
  right_typed := by
    have t1 := Typing.appElim (transport_typed eqAtTelescope) numT_typed
    have t2 := Typing.appElim t1 (eqAtConst_typed eqAtTelescope)
    have t3 := Typing.appElim t2 (constant_typed .suc)
    have t4 := Typing.appElim t3 (sucMove_typed eqAtTelescope)
    have t5 := Typing.appElim t4 (Typing.var 1)
    exact Typing.appElim t5 (Typing.var 0)

def holdsStepTyped : TypedEquation holdsStepEquation where
  telescope := holdsAtTelescope
  type := .sigma numT (holdsAtApp (.var 0))
  left_typed :=
    Typing.appElim (Typing.appElim (holdsStep_typed holdsAtTelescope) (Typing.var 1))
      (Typing.var 0)
  right_typed := by
    have t1 := Typing.appElim (transport_typed holdsAtTelescope) numT_typed
    have t2 := Typing.appElim t1 (holdsAtConst_typed holdsAtTelescope)
    have t3 := Typing.appElim t2 (constant_typed .suc)
    have t4 := Typing.appElim t3 (holdsMove_typed holdsAtTelescope)
    have t5 := Typing.appElim t4 (Typing.var 1)
    exact Typing.appElim t5 (Typing.var 0)

/-! ### Sharing: composition and the iterator's successor equation -/

theorem compose_typed {n : Nat} (Γ : Tower.Ctx n) :
    Typing R Γ (.const composeName) (liftClosed composeType) :=
  declared_typed lookup_compose composeType_formed Γ

abbrev composeTelescope : Tower.Ctx 6 :=
  .snoc (.snoc (.snoc (.snoc familyTelescope stepFamily) (rename wk stepFamily)) (.var 3))
    (.app (.var 3) (.var 0))

def composeTyped : TypedEquation composeEquation where
  telescope := composeTelescope
  type := .sigma (.var 5) (.app (.var 5) (.var 0))
  left_typed := by
    have c1 := Typing.appElim (compose_typed composeTelescope) (Typing.var 5)
    have c2 := Typing.appElim c1 (Typing.var 4)
    have c3 := Typing.appElim c2 (Typing.var 3)
    have c4 := Typing.appElim c3 (Typing.var 2)
    have c5 := Typing.appElim c4 (Typing.var 1)
    exact Typing.appElim c5 (Typing.var 0)
  right_typed := by
    have package : Typing R (.snoc composeTelescope (.sigma (.var 5) (.app (.var 5) (.var 0))))
        (.var 0) (.sigma (.var 6) (.app (.var 6) (.var 0))) := Typing.var 0
    have b1 := Typing.appElim
      (Typing.var (R := R) (Γ := .snoc composeTelescope (.sigma (.var 5) (.app (.var 5) (.var 0))))
        3)
      (Typing.fstElim package)
    have b2 := Typing.appElim b1 (Typing.sndElim package)
    exact CertifiedTransforms.iter_successor_typed_cumulative
      (A := .var 5) (P := .app (.var 5) (.var 0))
      (sigma_at (Typing.var 5) (Typing.appElim (B := U0) (Typing.var 5) (Typing.var 0)))
      (isUniverseAt Tower.zero) (Tower.Join.sorts _ _) lowered_zero
      (Typing.var 3) (Typing.var 1) (Typing.var 0) b2

abbrev iterSucTelescope : Tower.Ctx 6 :=
  .snoc (.snoc (.snoc (.snoc (.snoc (.snoc .nil numT) U0) (.pi (.var 0) U0)) stepFamily)
    (.var 2)) (.app (.var 2) (.var 0))

def iterSucTyped : TypedEquation iterSucEquation where
  telescope := iterSucTelescope
  type := .sigma (.var 4) (.app (.var 4) (.var 0))
  left_typed := by
    have i1 := Typing.appElim (iter_typed iterSucTelescope) (sucNative_typed (Typing.var 5))
    have i2 := Typing.appElim i1 (Typing.var 4)
    have i3 := Typing.appElim i2 (Typing.var 3)
    have i4 := Typing.appElim i3 (Typing.var 2)
    have i5 := Typing.appElim i4 (Typing.var 1)
    exact Typing.appElim i5 (Typing.var 0)
  right_typed := by
    have package : Typing R (.snoc iterSucTelescope (.sigma (.var 4) (.app (.var 4) (.var 0))))
        (.var 0) (.sigma (.var 5) (.app (.var 5) (.var 0))) := Typing.var 0
    have c1 := Typing.appElim
      (iter_typed (.snoc iterSucTelescope (.sigma (.var 4) (.app (.var 4) (.var 0)))))
      (Typing.var 6)
    have c2 := Typing.appElim c1 (Typing.var 5)
    have c3 := Typing.appElim c2 (Typing.var 4)
    have c4 := Typing.appElim c3 (Typing.var 3)
    have c5 := Typing.appElim c4 (Typing.fstElim package)
    have c6 := Typing.appElim c5 (Typing.sndElim package)
    exact CertifiedTransforms.iter_successor_typed_cumulative
      (A := .var 4) (P := .app (.var 4) (.var 0))
      (sigma_at (Typing.var 4) (Typing.appElim (B := U0) (Typing.var 4) (Typing.var 0)))
      (isUniverseAt Tower.zero) (Tower.Join.sorts _ _) lowered_zero
      (Typing.var 2) (Typing.var 1) (Typing.var 0) c6

/-! ### Returning the iterator at a carrier -/

theorem returnIter_typed {n : Nat} (Γ : Tower.Ctx n) :
    Typing R Γ (.const returnIterName) (liftClosed returnIterType) :=
  declared_typed lookup_returnIter returnIterType_formed Γ

/-- The result type of `returnIter A`, in the context `A`. -/
abbrev returnIterResult : Tower.Tm 1 :=
  .pi (.pi (.var 0) U0)
    (.pi numT (.pi (rename wk stepFamily)
      (.pi (.var 3) (.pi (.app (.var 3) (.var 0)) (.sigma (.var 5) (.app (.var 5) (.var 0)))))))

/-- The contexts under the five binders of `returnIter A`. -/
abbrev returnContext3 : Tower.Ctx 3 := .snoc familyTelescope numT
abbrev returnContext4 : Tower.Ctx 4 := .snoc returnContext3 (rename wk stepFamily)
abbrev returnContext5 : Tower.Ctx 5 := .snoc returnContext4 (.var 3)
abbrev returnContext6 : Tower.Ctx 6 := .snoc returnContext5 (.app (.var 3) (.var 0))

def returnIterTyped : TypedEquation returnIterEquation where
  telescope := .snoc .nil U0
  type := returnIterResult
  left_typed := Typing.appElim (returnIter_typed (.snoc .nil U0)) (Typing.var 0)
  right_typed := by
    -- the innermost body, in the context `A, P, n, step, x, e`
    have i1 := Typing.appElim (iter_typed returnContext6) (Typing.var 3)
    have i2 := Typing.appElim i1 (Typing.var 5)
    have i3 := Typing.appElim i2 (Typing.var 4)
    have i4 := Typing.appElim i3 (Typing.var 2)
    have i5 := Typing.appElim i4 (Typing.var 1)
    have body := Typing.appElim i5 (Typing.var 0)
    -- the formation of each remaining function type
    have fe : Typing R returnContext5
        (.pi (.app (.var 3) (.var 0)) (.sigma (.var 5) (.app (.var 5) (.var 0)))) U0 :=
      pi_at (Typing.appElim (B := U0) (Typing.var 3) (Typing.var 0))
        (sigma_at (Typing.var 5) (Typing.appElim (B := U0) (Typing.var 5) (Typing.var 0)))
    have fx : Typing R returnContext4
        (.pi (.var 3) (.pi (.app (.var 3) (.var 0)) (.sigma (.var 5) (.app (.var 5) (.var 0)))))
        U0 :=
      pi_at (Typing.var 3) fe
    have fs : Typing R returnContext3
        (.pi (rename wk stepFamily)
          (.pi (.var 3) (.pi (.app (.var 3) (.var 0)) (.sigma (.var 5) (.app (.var 5) (.var 0))))))
        U0 :=
      pi_at (stepFamily_formed.weaken (extension := numT)) fx
    have fn : Typing R familyTelescope
        (.pi numT (.pi (rename wk stepFamily)
          (.pi (.var 3) (.pi (.app (.var 3) (.var 0)) (.sigma (.var 5) (.app (.var 5) (.var 0)))))))
        U0 :=
      pi_at numT_typed fs
    have fp : Typing R (.snoc .nil U0) returnIterResult U1 :=
      pi_at (pi_at (raise (Typing.var 0)) U0_typed) (raise fn)
    exact Typing.lamIntro fp (isUniverseAt level1)
      (Typing.lamIntro fn (isUniverseAt Tower.zero)
        (Typing.lamIntro fs (isUniverseAt Tower.zero)
          (Typing.lamIntro fx (isUniverseAt Tower.zero)
            (Typing.lamIntro fe (isUniverseAt Tower.zero) body))))

/-! ### Conversion by the stored equations -/

/-- The instance of a one-variable equation. -/
def at1 {n : Nat} (term : Tower.Tm n) : Sub Tower.Head 1 n := fun _ => term

/-- The instance of a two-variable equation: `older` for its first pattern
variable, `newer` for its second. -/
def at2 {n : Nat} (older newer : Tower.Tm n) : Sub Tower.Head 2 n
  | ⟨0, _⟩ => newer
  | ⟨_ + 1, _⟩ => older

/-- An instance of a listed equation is one step of the program's computation. -/
theorem package_step {arity n : Nat} {left right : Tower.Tm arity}
    (listed : (⟨arity, (left, right)⟩ : Σ arity : Nat, Tower.Tm arity × Tower.Tm arity) ∈
      packageEquations)
    (substitution : Sub Tower.Head arity n) :
    Conv R.headEq (subst substitution left) (subst substitution right) R.computation :=
  .rel _ _ (.root (RootStep.declared
    (SchemaTable.step_of_mem packageEquations listed substitution)))

theorem listed_jIota : jIota ∈ packageEquations :=
  List.getElem_mem (l := packageEquations) (n := 0) (by decide)
theorem listed_numRecZero : numRecZeroEquation ∈ packageEquations :=
  List.getElem_mem (l := packageEquations) (n := 1) (by decide)
theorem listed_numRecSuc : numRecSucEquation ∈ packageEquations :=
  List.getElem_mem (l := packageEquations) (n := 2) (by decide)
theorem listed_eqAt : eqAtEquation ∈ packageEquations :=
  List.getElem_mem (l := packageEquations) (n := 3) (by decide)
theorem listed_sucMove : sucMoveEquation ∈ packageEquations :=
  List.getElem_mem (l := packageEquations) (n := 4) (by decide)
theorem listed_keep : keepEquation ∈ packageEquations :=
  List.getElem_mem (l := packageEquations) (n := 5) (by decide)
theorem listed_transport : transportEquation ∈ packageEquations :=
  List.getElem_mem (l := packageEquations) (n := 6) (by decide)
theorem listed_compose : composeEquation ∈ packageEquations :=
  List.getElem_mem (l := packageEquations) (n := 7) (by decide)
theorem listed_iterZero : iterZeroEquation ∈ packageEquations :=
  List.getElem_mem (l := packageEquations) (n := 8) (by decide)
theorem listed_iterSuc : iterSucEquation ∈ packageEquations :=
  List.getElem_mem (l := packageEquations) (n := 9) (by decide)
theorem listed_returnIter : returnIterEquation ∈ packageEquations :=
  List.getElem_mem (l := packageEquations) (n := 10) (by decide)
theorem listed_sucStep : sucStepEquation ∈ packageEquations :=
  List.getElem_mem (l := packageEquations) (n := 11) (by decide)
theorem listed_holdsAt : holdsAtEquation ∈ packageEquations :=
  List.getElem_mem (l := packageEquations) (n := 12) (by decide)
theorem listed_holdsMove : holdsMoveEquation ∈ packageEquations :=
  List.getElem_mem (l := packageEquations) (n := 13) (by decide)
theorem listed_holdsStep : holdsStepEquation ∈ packageEquations :=
  List.getElem_mem (l := packageEquations) (n := 14) (by decide)

/-- `add x (suc y) = suc (add x y)`, under the left endpoint of an identity. -/
theorem add_suc_step {n : Nat} (left right other : Tower.Tm n) :
    Conv R.headEq (.id numT (addNative left (sucNative right)) other)
      (.id numT (sucNative (addNative left right)) other) R.computation :=
  include_profile_conversion (.rel _ _ (.congIdLeft (.root (RootStep.declared
    (SchemaTable.step_of_mem SetProfile.nativeEquations
      (List.getElem_mem (l := SetProfile.nativeEquations) (n := 1) (by decide))
      (at2 left right))))))

/-- Two beta steps. -/
theorem beta_two {n : Nat} (body : Tower.Tm (n + 2)) (first second : Tower.Tm n) :
    Conv R.headEq (.app (.app (.lam (.lam body)) first) second)
      (inst0 second (subst (liftSub (subst0 first)) body)) R.computation :=
  .trans _ _ _ (.rel _ _ (.congAppFun (.betaPi (.lam body) first)))
    (.rel _ _ (.betaPi (subst (liftSub (subst0 first)) body) second))

/-! ### The successor move by identity elimination -/

def sucMoveTyped : TypedEquation sucMoveEquation where
  telescope := eqAtTelescope
  type := eqAtApp (sucNative (.var 1))
  left_typed :=
    Typing.appElim (Typing.appElim (sucMove_typed eqAtTelescope) (Typing.var 1)) (Typing.var 0)
  right_typed := by
    have point : Typing R eqAtTelescope (addNative zeroNative (.var 1)) numT :=
      addNative_typed zeroNative_typed (Typing.var 1)
    -- the motive `λ y p. suc (add zero n) = suc y`
    have motiveFormed₂ : Typing R (.snoc eqAtTelescope numT)
        (.pi (.id numT (addNative zeroNative (.var 2)) (.var 0)) U0) U1 :=
      pi_at (raise (id_at numT_typed (addNative_typed zeroNative_typed (Typing.var 2))
        (Typing.var 0))) U0_typed
    have motiveFormed : Typing R eqAtTelescope
        (.pi numT (.pi (.id numT (addNative zeroNative (.var 2)) (.var 0)) U0)) U1 :=
      pi_at (raise numT_typed) motiveFormed₂
    have motiveTyped : Typing R eqAtTelescope (sucMotive (.var 1))
        (.pi numT (.pi (.id numT (addNative zeroNative (.var 2)) (.var 0)) U0)) :=
      Typing.lamIntro motiveFormed (isUniverseAt level1)
        (Typing.lamIntro motiveFormed₂ (isUniverseAt level1)
          (id_at numT_typed (sucNative_typed (addNative_typed zeroNative_typed (Typing.var 3)))
            (sucNative_typed (Typing.var 1))))
    -- the reflexivity case, retyped by beta
    have reflCaseFormed : Typing R eqAtTelescope
        (.app (.app (sucMotive (.var 1)) (addNative zeroNative (.var 1)))
          (.refl (addNative zeroNative (.var 1)))) U0 :=
      Typing.appElim (B := U0) (Typing.appElim motiveTyped point) (Typing.reflIntro point)
    have reflCase := Typing.conv (Typing.reflIntro (sucNative_typed point)) reflCaseFormed
      (isUniverseAt Tower.zero) (.symm _ _ (beta_two _ _ _))
    -- the evidence, retyped by the equation of `eqAt`
    have path : Typing R eqAtTelescope (.var 0)
        (.id numT (addNative zeroNative (.var 1)) (.var 1)) :=
      Typing.conv (Typing.var 0) (id_at numT_typed point (Typing.var 1))
        (isUniverseAt Tower.zero) (package_step listed_eqAt (at1 (.var 1)))
    have j0 := j_typed eqAtTelescope
    rw [jType_eq] at j0
    have j1 := Typing.appElim j0 numT_typed
    have j2 := Typing.appElim j1 point
    have j3 := Typing.appElim j2 motiveTyped
    have j4 := Typing.appElim j3 reflCase
    have j5 := Typing.appElim j4 (Typing.var 1)
    have j6 := Typing.appElim j5 path
    -- the motive at the endpoint is `eqAt (suc n)`: beta, `eqAt`, `add`
    exact Typing.conv j6 (eqAt_typed (sucNative_typed (Typing.var 1))) (isUniverseAt Tower.zero)
      (.trans _ _ _ (beta_two _ _ _)
        (.symm _ _ (.trans _ _ _ (package_step listed_eqAt (at1 (sucNative (.var 1))))
          (add_suc_step zeroNative (.var 1) (sucNative (.var 1))))))

/-! ### The represented consumer

The step of `holdsAt` is the translated induction step of the source proof,
compiled on its own and checked in the program's rules. -/

/-- The proof family embeds in the program's rules. -/
theorem proofToPackage :
    SetProfile.proofRules.Morphism packageRules (fun head => head) := by
  have first := includeMorphism SetProfile.proofRules
    SetProfile.assumptionDeclarations
  have second := targetMorphism
  exact {
    headTyping := fun typing => typing
    isUniverse := fun isU => isU
    join := fun joined => joined
    cumulative := fun order => order
    headEq := fun equality => equality
    constantType := by
      intro name type known
      simpa only [Tm.mapHead_id] using second.constantType (first.constantType known)
    computation := by
      intro n left right step
      simpa only [Tm.mapHead_id] using second.computation (first.computation step)
  }

/-- The logical proof operations, checked in the program's rules. -/
noncomputable def packageOperations :
    HOLNativeGenericProofCompiler.Operations SetProfile.signature holdsName :=
  HOLNativeGenericProofCompiler.Operations.logicalOnlyAt SetProfile.signature holdsName
    SetProfile.holdsName_fresh packageRules proofToPackage

/-- `λ k. add zero k = k`, represented. -/
def motiveCode {n : Nat} : Tower.Tm n := .lam (eqNumNative (addNative zeroNative (.var 0)) (.var 0))

theorem motiveCode_typed {n : Nat} {Γ : Tower.Ctx n} : Typing R Γ motiveCode (.pi numT propT) :=
  Typing.lamIntro (pi_at numT_typed propT_typed) (isUniverseAt Tower.zero)
    (eqNum_typed (addNative_typed zeroNative_typed (Typing.var 0)) (Typing.var 0))

/-- `motive k → motive (suc k)`, represented, with `k` the newest variable. -/
noncomputable def stepProposition {n : Nat} : Tower.Tm (n + 1) :=
  FormationSensitiveHOLGenericProofFamily.rawImp SetProfile.signature
    (.app motiveCode (.var 0)) (.app motiveCode (sucNative (.var 0)))

/-- `∀ k. motive k → motive (suc k)`, the conclusion of the induction step. -/
def stepStatement : HOL.Formula SetProfile.SetConst [] :=
  .all (.imp (.app SetProfile.motive (.var .vz))
    (.app SetProfile.motive (SetProfile.sucT (.var .vz))))

/-- The induction step of the source proof of `zero-add`, as a proof of its own. -/
def zeroAddStepProof : HOL.ProofSyntaxModulo SetProfile.sourceEquations
    SetProfile.zeroAddAssumptions stepStatement :=
  .allI (.impI SetProfile.zeroAddStep)

theorem zeroAddStep_compiles :
    HOLNativeGenericProofCompiler.Modulo.compileModulo SetProfile.signature
      zeroAddStepProof Fin.elim0 SetProfile.zeroAddHypotheses = some zeroAddStepTerm :=
  rfl

theorem stepStatement_represented :
    FormationSensitiveHOLInterface.represent SetProfile.signature stepStatement =
      some (FormationSensitiveHOLGenericProofFamily.universalProposition
        SetProfile.signature numTy (.lam stepProposition)) :=
  rfl

theorem packageHypotheses_typed :
    HOLNativeGenericProofCompiler.GenericTyping.Hypotheses SetProfile.signature
      packageOperations (.nil : Tower.Ctx 0) Fin.elim0 SetProfile.zeroAddHypotheses := by
  intro index
  obtain ⟨code, represented, typed⟩ := SetProfile.hypotheses_typed index
  exact ⟨code, represented, include_target typed⟩

/-- The translated induction step is a proof of `∀ k. motive k → motive (suc k)`
in the program's rules. -/
theorem zeroAddStep_typed :
    Typing R .nil zeroAddStepTerm
      (FormationSensitiveHOLGenericProofFamily.proof holdsName
        (FormationSensitiveHOLGenericProofFamily.universalProposition
          SetProfile.signature numTy (.lam stepProposition))) := by
  obtain ⟨code, represented, typed⟩ :=
    HOLNativeGenericProofCompiler.Modulo.compileModulo_typed SetProfile.signature
      holdsName packageOperations SetProfile.realization zeroAddStepProof
      (objects := Fin.elim0) (fun index => index.elim0) packageHypotheses_typed
      zeroAddStep_compiles
  rw [stepStatement_represented] at represented
  cases represented
  rw [SetProfile.subst_elim0] at typed
  exact typed

def holdsMoveTyped : TypedEquation holdsMoveEquation where
  telescope := holdsAtTelescope
  type := holdsAtApp (sucNative (.var 1))
  left_typed :=
    Typing.appElim (Typing.appElim (holdsMove_typed holdsAtTelescope) (Typing.var 1))
      (Typing.var 0)
  right_typed := by
    -- the step at the index `n`
    have domain := SetProfile.simple_formed numTy
      (.snoc .nil (FormationSensitiveHOLInterface.typeAt SetProfile.types 0 numTy))
    have proposition : Typing SetProfile.signature.rules
        (.snoc (.snoc .nil (FormationSensitiveHOLInterface.typeAt SetProfile.types 0 numTy))
          (FormationSensitiveHOLInterface.typeAt SetProfile.types 1 numTy))
        stepProposition (FormationSensitiveHOLInterface.typeAt SetProfile.types 2 .prop) :=
      FormationSensitiveHOLInterface.represent_typed SetProfile.signature
        (gamma := [numTy, numTy])
        (.imp (.app SetProfile.motive (.var .vz))
          (.app SetProfile.motive (SetProfile.sucT (.var .vz)))) rfl
    have argument : Typing SetProfile.signature.rules
        (.snoc .nil (FormationSensitiveHOLInterface.typeAt SetProfile.types 0 numTy))
        (.var 0) (FormationSensitiveHOLInterface.typeAt SetProfile.types 1 numTy) := by
      simpa only [Ctx.lookup_snoc_zero, FormationSensitiveHOLInterface.typeAt_rename] using
        (Typing.var (R := SetProfile.signature.rules)
          (Γ := .snoc .nil (FormationSensitiveHOLInterface.typeAt SetProfile.types 0 numTy))
          0)
    have atIndex := packageOperations.universalElim domain proposition
      (zeroAddStep_typed.weaken
        (extension := FormationSensitiveHOLInterface.typeAt SetProfile.types 0 numTy))
      argument
    -- the two sides of the implication, past the evidence
    have premise : Typing SetProfile.signature.rules
        (.snoc .nil (FormationSensitiveHOLInterface.typeAt SetProfile.types 0 numTy))
        (.app motiveCode (.var 0)) (FormationSensitiveHOLInterface.typeAt SetProfile.types 1 .prop) :=
      FormationSensitiveHOLInterface.represent_typed SetProfile.signature
        (gamma := [numTy]) (.app SetProfile.motive (.var .vz)) rfl
    have conclusion : Typing SetProfile.signature.rules
        (.snoc .nil (FormationSensitiveHOLInterface.typeAt SetProfile.types 0 numTy))
        (.app motiveCode (sucNative (.var 0)))
        (FormationSensitiveHOLInterface.typeAt SetProfile.types 1 .prop) :=
      FormationSensitiveHOLInterface.represent_typed SetProfile.signature
        (gamma := [numTy]) (.app SetProfile.motive (SetProfile.sucT (.var .vz))) rfl
    have premiseHere := premise.weaken (extension := holdsAtApp (.var 0))
    have conclusionHere := conclusion.weaken (extension := holdsAtApp (.var 0))
    simp only [FormationSensitiveHOLInterface.typeAt_rename] at premiseHere conclusionHere
    -- the evidence, retyped by `holdsAt` and beta
    have premiseFormed : Typing R holdsAtTelescope
        (FormationSensitiveHOLGenericProofFamily.proof holdsName (.app motiveCode (.var 1))) U0 :=
      packageOperations.includeProofTyping
        (FormationSensitiveHOLGenericProofFamily.proof_formed SetProfile.signature holdsName
          SetProfile.holdsName_fresh
          (FormationSensitiveHOLGenericProofFamily.include_typed SetProfile.signature
            holdsName premiseHere))
    have evidence : Typing R holdsAtTelescope (.var 0)
        (FormationSensitiveHOLGenericProofFamily.proof holdsName (.app motiveCode (.var 1))) :=
      Typing.conv (Typing.var 0) premiseFormed (isUniverseAt Tower.zero)
        (.trans _ _ _ (package_step listed_holdsAt (at1 (.var 1)))
          (.symm _ _ (.rel _ _ (.congAppArg (.betaPi _ _)))))
    have step := packageOperations.implicationElim premiseHere conclusionHere
      (atIndex.weaken (extension := holdsAtApp (.var 0))) evidence
    exact Typing.conv step (holdsAt_typed (sucNative_typed (Typing.var 1)))
      (isUniverseAt Tower.zero)
      (.trans _ _ _ (.rel _ _ (.congAppArg (.betaPi _ _)))
        (.symm _ _ (package_step listed_holdsAt (at1 (sucNative (.var 1))))))

/-! ## Axiom audit -/

#print axioms jType_formed
#print axioms iterType_formed
#print axioms TypedEquation.instance_typed
#print axioms jEquationTyped
#print axioms numRecZeroTyped
#print axioms numRecSucTyped
#print axioms eqAtTyped
#print axioms sucMoveTyped
#print axioms keepTyped
#print axioms transportTyped
#print axioms composeTyped
#print axioms iterZeroTyped
#print axioms iterSucTyped
#print axioms returnIterTyped
#print axioms sucStepTyped
#print axioms holdsAtTyped
#print axioms holdsMoveTyped
#print axioms holdsStepTyped
#print axioms zeroAddStep_compiles
#print axioms zeroAddStep_typed

end Mettapedia.Languages.MeTTa.PrimeCandidates.DeclarationBased.CertifiedTransformProgram.Package
