import Mettapedia.Languages.MeTTa.PrimeCandidates.DeclarationBased.CertifiedTransformProgram.ExecutableModel.ObjectChurchModel
import Mettapedia.Languages.MeTTa.PrimeCandidates.DeclarationBased.CertifiedTransformProgram.ExecutableModel.ObjectDatatypes
import Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId.TypedEquality.Impredicative.Domain.ConstructorTokens

/-!
# The object package with a declared datatype, read in the domain

The object package with its numbers is read in the domain by `objectChurchReading`, which
validates it (`objectChurchReading_valid`). This module reads the object package with any simple
datatype admissible over it (`dataChurch d`, for `d.Admissible objectChurch`): a type, constructors
whose fields are the datatype itself or closed types of the object package, and a recursor with
one computation rule for each constructor. The reading `dataReading d` validates the package and
agrees with the object reading on every constant of the object package (`dataReading_valid`,
`objectChurch_data_reading`).

**The reading.** The datatype denotes the declared datatype of the domain at its parameters, the
closed field types of its constructors in order, read by the object reading (`dataTypeI`,
`dataParams`). A constructor's kind records the datatype and the shape of each field: the datatype
itself, or the next parameter (`fieldShapes`, `ctorShapes`). Each new constant denotes a Church
constant, a function projected onto the denotation of its declared type:

* a constructor denotes the constructor element of its arguments, curried (`curryI`) and projected
  onto the nondependent function type of its fields (`ctorConstI`, `cinterp_ctorType`), so at
  elements of its field types it is the constructor element (`appSpine_ctorConstI`);
* the recursor denotes recursion over the datatype by approximation (`Ideal.recI`), with one method
  for each constructor (`methodsAt`): at a constructor, its method applied to the fields and to the
  recursive values, each read at the motive at its field (`caseValue`, `caseValue_eval`); curried
  over the motive, the methods and the element, and projected onto the denotation of its declared
  type (`recConstI`, `dataReading_recursor_eq`).

**Why it is valid.** Universes, heads and head equality are read as in the object package. The
object package's constants keep their values, and their declared types mention only its own
constants. The type of the datatype is generated by type tokens, since its parameters are types of
the object package (`typeGenerated_dataTypeI`); the constructors and the recursor are Church
constants (`dataReading_constants`). A root step of the object package is valid because its schema
mentions only the object package's constants, so its spine facts carry over to the object reading
(`dataReading_objectRoot`). The computation rule of the recursor at a constructor is valid
(`dataReading_iota`): the spine facts of its left side make the constructor's arguments elements of
their field types, recursion computes at the constructor element by the constructor's method
(`Ideal.recI_ctorI`, `recursor_at_ctor`), and the recursor at a recursive field is recursion there,
read at the motive (`appSpine_recursor`).

**The three faces.** This is the typed judgment's face read in the domain. The extensional face of
the same package is its set model (`objectDeclarations_model`), where the datatype is the least set
closed under its constructors; the operational face is the recursor's computation rules, whose
validity in the reading is shown here.

**The lists of numbers** are an instance (`listDecl`: `nil`, `cons : num → list → list`,
`list-rec`); the binary trees of numbers are another (`ObjectTrees`). Positive: the length of the
one-element list of the numeral one denotes one (`lengthOf_one_value`). Negative: reading `cons`
as the constant function to the empty list keeps it an element of its declared type but breaks the
recursor's rule at `cons`, so that reading is not valid (`badCons_not_valid`). The reading
separates the constructors of every admissible datatype (`appSpine_ctorConstI_proj`,
`Ideal.ctorI_ne_of_ne`); with the typing of their arguments this gives that no closed equality
of two different constructors is derivable (`ConstructorView`, `ctor_not_equal_ctor`).
-/

set_option autoImplicit false

namespace Mettapedia.Languages.MeTTa.PrimeCandidates.DeclarationBased.CertifiedTransformProgram.ExecutableModel

open Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId
open Mettapedia.TypeTheory.Calculi.ParameterizedPiSigmaId.TowerInterpretation (closedTerm_iff)
open Mettapedia.TypeTheory.UniverseLevel
open Presentation
open Presentation.TypedEquality
open Presentation.TypedEquality.Normalization
open Presentation.TypedEquality.Annotated
open Presentation.TypedEquality.Impredicative.Domain
open Presentation.TypedEquality.Impredicative.Domain.Ideal (projT TypeGenerated principal univIdeal
  natI zeroI cpi clam instPi projArgs SpineTyped ctorI recI succI)

/-! ## Spine facts at the values of a substitution, and under another reading -/

section Transfer

variable {Head : Type} {R R' : Rules Head}

/-- **Spine facts of a substituted term are spine facts of the term** in the environment of the
values of the substitution. -/
theorem SpineFacts.of_subst {Rd : Reading Head} {P : ChurchRules R} :
    ∀ {n m : Nat} (t : CTm Head n) (σ : CSub Head n m) {τ : Ideal} {ρ : Env m},
      SpineFacts Rd P (t.subst σ) τ ρ → SpineFacts Rd P t τ fun i => cinterp Rd (σ i) ρ
  | _, _, .var _, _, _, _, _ => trivial
  | _, _, .const _, _, _, _, h => h
  | _, _, .head _, _, _, _, _ => trivial
  | _, _, .pi _ _, _, _, _, _ => trivial
  | _, _, .sigma _ _, _, _, _, _ => trivial
  | _, _, .id _ _ _, _, _, _, _ => trivial
  | _, _, .lam _ _, _, _, _, _ => trivial
  | _, _, .pair _ _, _, _, _, _ => trivial
  | _, _, .fst _, _, _, _, _ => trivial
  | _, _, .snd _, _, _, _, _ => trivial
  | _, _, .app f a, σ, _, ρ, h => by
      obtain ⟨T, G, hG, e, ⟨hf, sf⟩, ⟨ha, sa⟩⟩ := spineFacts_app.1 h
      rw [cinterp_subst] at e hf ha
      exact spineFacts_app.2 ⟨T, G, hG, e, ⟨hf, SpineFacts.of_subst f σ sf⟩,
        ⟨ha, SpineFacts.of_subst a σ sa⟩⟩
  | _, _, .refl a, σ, _, ρ, h => by
      obtain ⟨T, e, ha, sa⟩ := spineFacts_refl.1 h
      rw [cinterp_subst] at e ha
      exact spineFacts_refl.2 ⟨T, e, ha, SpineFacts.of_subst a σ sa⟩

/-- **Spine facts carry over to another reading and another package** that agree on the
constants of the term: the readings give them the same values, and each declared type the
second package gives them is one the first gives them, read alike by both readings. -/
theorem SpineFacts.congr {Rd Rd' : Reading Head} {P : ChurchRules R} {P' : ChurchRules R'}
    (heads : Rd.head = Rd'.head) :
    ∀ {n : Nat} (t : CTm Head n), (∀ c ∈ termConsts t, Rd.const c = Rd'.const c) →
      (∀ c ∈ termConsts t, ∀ D, P'.constantType c = some D →
        P.constantType c = some D ∧ cinterp Rd D Env.nil = cinterp Rd' D Env.nil) →
      ∀ {τ : Ideal} {ρ : Env n}, SpineFacts Rd P t τ ρ → SpineFacts Rd' P' t τ ρ
  | _, .var _, _, _, _, _, _ => trivial
  | _, .head _, _, _, _, _, _ => trivial
  | _, .pi _ _, _, _, _, _, _ => trivial
  | _, .sigma _ _, _, _, _, _, _ => trivial
  | _, .id _ _ _, _, _, _, _, _ => trivial
  | _, .lam _ _, _, _, _, _, _ => trivial
  | _, .pair _ _, _, _, _, _, _ => trivial
  | _, .fst _, _, _, _, _, _ => trivial
  | _, .snd _, _, _, _, _, _ => trivial
  | _, .const c, _, decl, _, _, h => fun D hD => by
      obtain ⟨hD', e⟩ := decl c List.mem_cons_self D hD
      rw [h D hD', e]
  | _, .app f a, agree, decl, _, ρ, h => by
      have agreeF : ∀ c ∈ termConsts f, Rd.const c = Rd'.const c :=
        fun c hc => agree c (List.mem_append_left _ hc)
      have agreeA : ∀ c ∈ termConsts a, Rd.const c = Rd'.const c :=
        fun c hc => agree c (List.mem_append_right _ hc)
      obtain ⟨T, G, hG, e, ⟨hf, sf⟩, ⟨ha, sa⟩⟩ := spineFacts_app.1 h
      rw [cinterp_congr heads f agreeF] at hf
      rw [cinterp_congr heads a agreeA] at e ha
      exact spineFacts_app.2 ⟨T, G, hG, e,
        ⟨hf, SpineFacts.congr heads f agreeF
          (fun c hc => decl c (List.mem_append_left _ hc)) sf⟩,
        ⟨ha, SpineFacts.congr heads a agreeA
          (fun c hc => decl c (List.mem_append_right _ hc)) sa⟩⟩
  | _, .refl a, agree, decl, _, ρ, h => by
      obtain ⟨T, e, ha, sa⟩ := spineFacts_refl.1 h
      rw [cinterp_congr heads a agree] at e ha
      exact spineFacts_refl.2 ⟨T, e, ha, SpineFacts.congr heads a agree decl sa⟩

end Transfer

namespace CodeModel


/-! ## Lists with one entry changed -/

theorem getElem?_append_cons_self {α : Type} (pre post : List α) (x : α) :
    (pre ++ x :: post)[pre.length]? = some x := by
  simp only [List.length_append, List.length_cons, Nat.lt_add_right_iff_pos, Nat.lt_add_one_iff,
      zero_le, getElem?_pos, Std.le_refl, List.getElem_append_right, tsub_self,
      List.getElem_cons_zero]

theorem getElem?_append_cons_ne {α : Type} (pre post : List α) (x y : α) {i : Nat}
    (h : i ≠ pre.length) : (pre ++ x :: post)[i]? = (pre ++ y :: post)[i]? := by
  rcases Nat.lt_or_gt_of_ne h with h | h
  · rw [List.getElem?_append_left h, List.getElem?_append_left h]
  · rw [List.getElem?_append_right h.le, List.getElem?_append_right h.le]
    obtain ⟨j, hj⟩ : ∃ j, i - pre.length = j + 1 := ⟨i - pre.length - 1, by omega⟩
    rw [hj]
    rfl

/-- An entry of a list with one entry varying is continuous in it. -/
theorem cont_getD_at (pre post : List Ideal) (j : Nat) :
    Ideal.Cont fun x => (pre ++ x :: post).getD j Ideal.bot := by
  by_cases h : j = pre.length
  · subst h
    simp only [List.getD_eq_getElem?_getD, getElem?_append_cons_self, Option.getD_some]
    exact Ideal.Cont.id
  · have e : ∀ x,
        (pre ++ x :: post).getD j Ideal.bot = (pre ++ Ideal.bot :: post).getD j Ideal.bot :=
      fun x => by
        simp only [List.getD_eq_getElem?_getD]
        rw [getElem?_append_cons_ne pre post x Ideal.bot h]
    simp only [e]
    exact Ideal.Cont.const _

/-! ## Constructor elements are continuous in each field -/

/-- **The constructor element is continuous in each field.** -/
theorem cont_ctorI_at (k : Kind) (pre post : List Ideal) :
    Ideal.Cont fun x => ctorI k (pre ++ x :: post) := by
  unfold Ideal.ctorI
  exact Ideal.Cont.of_closure
    (P := fun x t => t = .tag k ∨
      ∃ i f s, (pre ++ x :: post)[i]? = some f ∧ f.Mem s ∧ t = .arg k i [] s)
    (fun {x x'} h t ht => by
      rcases ht with rfl | ⟨i, f, s, hf, hs, rfl⟩
      · exact .inl rfl
      · by_cases hi : i = pre.length
        · subst hi
          rw [getElem?_append_cons_self] at hf
          cases hf
          exact .inr ⟨pre.length, x', s, getElem?_append_cons_self pre post x', h s hs, rfl⟩
        · exact .inr ⟨i, f, s, by rw [getElem?_append_cons_ne pre post x' x hi]; exact hf, hs,
            rfl⟩)
    fun {x t} ht => by
      rcases ht with rfl | ⟨i, f, s, hf, hs, rfl⟩
      · exact ⟨[], fun _ h => absurd h List.not_mem_nil, .inl rfl⟩
      · by_cases hi : i = pre.length
        · subst hi
          rw [getElem?_append_cons_self] at hf
          cases hf
          exact ⟨[s], fun r hr => by rw [List.mem_singleton.1 hr]; exact hs,
            .inr ⟨pre.length, principal [s], s, getElem?_append_cons_self pre post _,
              ent_of_mem List.mem_cons_self, rfl⟩⟩
        · exact ⟨[], fun _ h => absurd h List.not_mem_nil,
            .inr ⟨i, f, s, by rw [getElem?_append_cons_ne pre post _ x hi]; exact hf, hs, rfl⟩⟩

/-! ## Curried functions of finitely many arguments -/

/-- **A function of `n` more arguments**, after the arguments `acc` (the latest first): at all
of them it is `H` of the arguments in order. -/
def curryI (H : List Ideal → Ideal) : Nat → List Ideal → Ideal
  | 0, acc => H acc.reverse
  | n + 1, acc => Ideal.lam fun X => curryI H n (principal X :: acc)

/-- A map of lists continuous in each entry. -/
def ContEach (H : List Ideal → Ideal) : Prop :=
  ∀ pre post : List Ideal, Ideal.Cont fun x => H (pre ++ x :: post)

theorem ContList.contEach {H : List Ideal → Ideal} (hH : Ideal.ContList H) : ContEach H := by
  intro pre post
  have h := hH.comp_list (Fs := pre.map (fun p _ => p) ++ (fun x => x) :: post.map (fun p _ => p))
    (fun F hF => by
      rcases List.mem_append.1 hF with hF | hF
      · obtain ⟨p, -, rfl⟩ := List.mem_map.1 hF
        exact Ideal.Cont.const p
      · rcases List.mem_cons.1 hF with rfl | hF
        · exact Ideal.Cont.id
        · obtain ⟨p, -, rfl⟩ := List.mem_map.1 hF
          exact Ideal.Cont.const p)
  simpa only [List.map_append, List.map_map, Function.comp_def, List.map_id_fun', id_eq,
      List.map_cons] using h

theorem cont_curryI {H : List Ideal → Ideal} (hH : ContEach H) :
    ∀ (n : Nat) (acc₁ acc₂ : List Ideal), Ideal.Cont fun x => curryI H n (acc₁ ++ x :: acc₂)
  | 0, acc₁, acc₂ => by
      have e : ∀ x : Ideal, (acc₁ ++ x :: acc₂).reverse = acc₂.reverse ++ x :: acc₁.reverse :=
        fun x => by simp only [List.reverse_append, List.reverse_cons, List.append_assoc,
            List.cons_append, List.nil_append]
      simp only [curryI, e]
      exact hH _ _
  | n + 1, acc₁, acc₂ =>
      Ideal.cont_lam_param fun X => cont_curryI hH n (principal X :: acc₁) acc₂

/-- **A curried function applied to all its arguments** is `H` of them. -/
theorem appSpine_curryI {H : List Ideal → Ideal} (hH : ContEach H) :
    ∀ (n : Nat) (acc args : List Ideal), args.length = n →
      Ideal.appSpine (curryI H n acc) args = H (acc.reverse ++ args)
  | 0, acc, [], _ => by simp only [Ideal.appSpine, curryI, List.append_nil]
  | n + 1, acc, a :: args, hlen => by
      show Ideal.appSpine
          (Ideal.app (Ideal.lam fun X => curryI H n (principal X :: acc)) a) args = _
      rw [Ideal.app_lam_principal (H := fun x => curryI H n (x :: acc)) (cont_curryI hH n [] acc) a,
        appSpine_curryI hH n (a :: acc) args (by simpa only [List.length_cons,
            Nat.add_right_cancel_iff] using hlen)]
      simp only [List.reverse_cons, List.append_assoc, List.cons_append, List.nil_append]

/-! ## Spines of arguments, continuous in a list -/

theorem contList_appSpine {F : List Ideal → Ideal} (hF : Ideal.ContList F) :
    ∀ (gs : List (List Ideal → Ideal)), (∀ g ∈ gs, Ideal.ContList g) →
      Ideal.ContList fun zs => Ideal.appSpine (F zs) (gs.map (· zs))
  | [], _ => hF
  | g :: gs, hg =>
      contList_appSpine (Ideal.ContList.comp₂ Ideal.cont₂_app hF (hg g List.mem_cons_self)) gs
        fun g' h => hg g' (List.mem_cons_of_mem _ h)

theorem cont_appSpine {F : Ideal → Ideal} (hF : Ideal.Cont F) :
    ∀ (gs : List (Ideal → Ideal)), (∀ g ∈ gs, Ideal.Cont g) →
      Ideal.Cont fun w => Ideal.appSpine (F w) (gs.map (· w))
  | [], _ => hF
  | g :: gs, hg =>
      cont_appSpine (Ideal.cont₂_app.comp hF (hg g List.mem_cons_self)) gs
        fun g' h => hg g' (List.mem_cons_of_mem _ h)

/-! ## The value of a method -/

/-- The hypotheses of the recursive fields `xs` at their recursive values `rs`, over the motive
`π`: each value read at the motive at its field. -/
def hypsI (π : Ideal) : List Ideal → List Ideal → List Ideal
  | x :: xs, r :: rs => projT (Ideal.app π x) r :: hypsI π xs rs
  | _, _ => []

theorem hypsI_map (π : Ideal) (r : Ideal → Ideal) :
    ∀ xs : List Ideal, hypsI π xs (xs.map r) = xs.map fun x => projT (Ideal.app π x) (r x)
  | [] => rfl
  | x :: xs => by rw [List.map_cons, hypsI, hypsI_map π r xs, List.map_cons]

/-- The hypotheses of a method as functions of the motive and of the fields followed by the
recursive values: for each recursive flag, the field at position `p` and its value at `q`. -/
def hypFns : List Bool → Nat → Nat → List (Ideal → List Ideal → Ideal)
  | [], _, _ => []
  | true :: bs, p, q =>
      (fun π zs => projT (Ideal.app π (zs.getD p Ideal.bot)) (zs.getD q Ideal.bot)) ::
        hypFns bs (p + 1) (q + 1)
  | false :: bs, p, q => hypFns bs (p + 1) q

/-- **The arguments of a method** of a constructor with the recursive flags `bs`, as functions
of the motive and of the fields followed by the recursive values: the fields, then the
hypotheses of the recursive fields. -/
def caseFns (bs : List Bool) : List (Ideal → List Ideal → Ideal) :=
  (List.range bs.length).map (fun i _ zs => zs.getD i Ideal.bot) ++ hypFns bs 0 bs.length

/-- **The value of a method** `μ` over the motive `π`, at the fields followed by the recursive
values: `μ` applied to the fields and to the hypotheses. -/
def caseValue (π μ : Ideal) (bs : List Bool) (zs : List Ideal) : Ideal :=
  Ideal.appSpine μ ((caseFns bs).map fun g => g π zs)

theorem hypFns_cases {g : Ideal → List Ideal → Ideal} (bs : List Bool) :
    ∀ {p q : Nat}, g ∈ hypFns bs p q →
      ∃ p' q', g = fun π zs =>
        projT (Ideal.app π (zs.getD p' Ideal.bot)) (zs.getD q' Ideal.bot) := by
  induction bs with
  | nil => intro _ _ h; exact absurd h List.not_mem_nil
  | cons b bs ih =>
      intro p q h
      cases b with
      | true =>
          rcases List.mem_cons.1 h with rfl | h
          · exact ⟨_, _, rfl⟩
          · exact ih h
      | false => exact ih h

theorem caseFns_cases {bs : List Bool} {g : Ideal → List Ideal → Ideal} (h : g ∈ caseFns bs) :
    (∃ i, g = fun _ zs => zs.getD i Ideal.bot) ∨
      ∃ p q, g = fun π zs => projT (Ideal.app π (zs.getD p Ideal.bot)) (zs.getD q Ideal.bot) := by
  rcases List.mem_append.1 h with h | h
  · obtain ⟨i, -, rfl⟩ := List.mem_map.1 h
    exact .inl ⟨i, rfl⟩
  · exact .inr (hypFns_cases bs h)

theorem contList_caseValue (π μ : Ideal) (bs : List Bool) : Ideal.ContList (caseValue π μ bs) := by
  have h := contList_appSpine (Ideal.ContList.const μ) ((caseFns bs).map fun g zs => g π zs)
    fun g' hg' => by
      obtain ⟨g, hg, rfl⟩ := List.mem_map.1 hg'
      rcases caseFns_cases hg with ⟨i, rfl⟩ | ⟨p, q, rfl⟩
      · exact Ideal.ContList.getD i
      · exact Ideal.ContList.comp₂ Ideal.cont₂_projT
          (Ideal.ContList.comp (Ideal.cont₂_app.right π) (Ideal.ContList.getD p))
          (Ideal.ContList.getD q)
  simp only [List.map_map, Function.comp_def] at h
  exact h

theorem cont_caseValue_motive (μ : Ideal) (bs : List Bool) (zs : List Ideal) :
    Ideal.Cont fun π => caseValue π μ bs zs := by
  have h := cont_appSpine (Ideal.Cont.const μ) ((caseFns bs).map fun g π => g π zs)
    fun g' hg' => by
      obtain ⟨g, hg, rfl⟩ := List.mem_map.1 hg'
      rcases caseFns_cases hg with ⟨i, rfl⟩ | ⟨p, q, rfl⟩
      · exact Ideal.Cont.const _
      · exact (Ideal.cont₂_projT.left _).comp (Ideal.cont₂_app.left _)
  simp only [List.map_map, Function.comp_def] at h
  exact h

theorem cont_caseValue_method (π : Ideal) (bs : List Bool) (zs : List Ideal) :
    Ideal.Cont fun μ => caseValue π μ bs zs := by
  have h := cont_appSpine Ideal.Cont.id (((caseFns bs).map fun g => g π zs).map fun a _ => a)
    fun g' hg' => by
      obtain ⟨a, -, rfl⟩ := List.mem_map.1 hg'
      exact Ideal.Cont.const a
  simp only [List.map_map, Function.comp_def] at h
  exact h

/-- The hypotheses at a list whose entries from `p` are the fields and from `q` the recursive
values. -/
theorem hypFns_eval (π : Ideal) (zs : List Ideal) :
    ∀ (bs : List Bool) (p q : Nat) (xs rs : List Ideal), xs.length = bs.length →
      rs.length = (Ideal.recFields bs xs).length →
      (∀ i, i < bs.length → zs.getD (p + i) Ideal.bot = xs.getD i Ideal.bot) →
      (∀ j, j < rs.length → zs.getD (q + j) Ideal.bot = rs.getD j Ideal.bot) →
      (hypFns bs p q).map (fun g => g π zs) = hypsI π (Ideal.recFields bs xs) rs
  | [], _, _, _, _, _, _, _, _ => by simp only [hypFns, List.map_nil, Ideal.recFields, hypsI]
  | true :: bs, p, q, x :: xs, rs, hx, hr, hxs, hrs => by
      obtain ⟨r, rs, rfl⟩ : ∃ r rs', rs = r :: rs' := by
        cases rs with
        | nil =>
            simp only [List.length_nil, Ideal.recFields, List.length_cons] at hr
            exact absurd hr (by omega)
        | cons r rs => exact ⟨r, rs, rfl⟩
      have h0 := hxs 0 (by simp only [List.length_cons, Nat.lt_add_one_iff, zero_le])
      have h0' := hrs 0 (by simp only [List.length_cons, Nat.lt_add_one_iff, zero_le])
      simp only [Nat.add_zero, List.getD_cons_zero] at h0 h0'
      simp only [hypFns, List.map_cons, Ideal.recFields, hypsI, h0, h0']
      congr 1
      exact hypFns_eval π zs bs (p + 1) (q + 1) xs rs (by simpa only [List.length_cons,
          Nat.add_right_cancel_iff] using hx)
        (by simpa only [List.length_cons, Ideal.recFields, Nat.add_right_cancel_iff] using hr)
        (fun i hi => by
          have := hxs (i + 1) (by simpa only [List.length_cons, Nat.lt_add_one_iff,
              Nat.add_one_le_iff] using hi)
          rwa [show p + (i + 1) = p + 1 + i by omega, List.getD_cons_succ] at this)
        (fun j hj => by
          have := hrs (j + 1) (by simpa only [List.length_cons, Nat.lt_add_one_iff,
              Nat.add_one_le_iff] using hj)
          rwa [show q + (j + 1) = q + 1 + j by omega, List.getD_cons_succ] at this)
  | false :: bs, p, q, x :: xs, rs, hx, hr, hxs, hrs => by
      simp only [hypFns, Ideal.recFields]
      exact hypFns_eval π zs bs (p + 1) q xs rs (by simpa only [List.length_cons,
          Nat.add_right_cancel_iff] using hx) (by simpa only [Ideal.recFields] using hr)
        (fun i hi => by
          have := hxs (i + 1) (by simpa only [List.length_cons, Nat.lt_add_one_iff,
              Nat.add_one_le_iff] using hi)
          rwa [show p + (i + 1) = p + 1 + i by omega, List.getD_cons_succ] at this)
        hrs
  | _ :: _, _, _, [], _, hx, _, _, _ => by
      simp only [List.length_nil, List.length_cons] at hx
      exact absurd hx (by omega)

/-- **The value of a method at the fields and the recursive values** is the method applied to
the fields and to the recursive values, each read at the motive at its field. -/
theorem caseValue_eval (π μ : Ideal) (bs : List Bool) {xs : List Ideal}
    (hx : xs.length = bs.length) (r : Ideal → Ideal) :
    caseValue π μ bs (xs ++ (Ideal.recFields bs xs).map r) =
      Ideal.appSpine μ
        (xs ++ (Ideal.recFields bs xs).map fun x => projT (Ideal.app π x) (r x)) := by
  unfold caseValue caseFns
  rw [List.map_append, List.map_map]
  congr 1
  congr 1
  · apply List.ext_getElem (by simp only [List.getD_eq_getElem?_getD, List.length_map,
      List.length_range, hx])
    intro i h₁ h₂
    simp only [List.getElem_map, List.getElem_range, Function.comp_apply]
    rw [List.getD_eq_getElem?_getD, List.getElem?_append_left (by omega),
      List.getElem?_eq_getElem h₂, Option.getD_some]
  · rw [hypFns_eval π _ bs 0 bs.length xs ((Ideal.recFields bs xs).map r) hx
      (by simp only [List.length_map])
      (fun i hi => by
        rw [Nat.zero_add, List.getD_eq_getElem?_getD, List.getD_eq_getElem?_getD,
          List.getElem?_append_left (by omega)])
      (fun j hj => by
        rw [List.getD_eq_getElem?_getD, List.getD_eq_getElem?_getD, ← hx,
          List.getElem?_append_right (by omega), Nat.add_sub_cancel_left]),
      hypsI_map]

/-! ## The methods of a recursion -/

/-- **The methods of a recursion** over the constructors `cs`, with the motive `π` and one
method for each constructor: at a constructor, the value of its method. -/
def methodsAt (π : Ideal) : List (Kind × List Bool) → List Ideal → Ideal.Methods Kind
  | [], _ => fun _ _ => Ideal.bot
  | c :: cs, μs => fun k zs =>
      if k = c.1 then caseValue π (μs.headD Ideal.bot) c.2 zs else methodsAt π cs μs.tail k zs

theorem contList_methodsAt (π : Ideal) :
    ∀ (cs : List (Kind × List Bool)) (μs : List Ideal) (k : Kind),
      Ideal.ContList (methodsAt π cs μs k)
  | [], _, _ => Ideal.ContList.const _
  | c :: cs, μs, k => by
      by_cases h : k = c.1
      · simp only [methodsAt, if_pos h]
        exact contList_caseValue _ _ _
      · simp only [methodsAt, if_neg h]
        exact contList_methodsAt π cs μs.tail k

theorem cont_methodsAt_motive :
    ∀ (cs : List (Kind × List Bool)) (μs : List Ideal) (k : Kind) (zs : List Ideal),
      Ideal.Cont fun π => methodsAt π cs μs k zs
  | [], _, _, _ => Ideal.Cont.const _
  | c :: cs, μs, k, zs => by
      by_cases h : k = c.1
      · simp only [methodsAt, if_pos h]
        exact cont_caseValue_motive _ _ _
      · simp only [methodsAt, if_neg h]
        exact cont_methodsAt_motive cs μs.tail k zs

theorem cont_methodsAt_method (π : Ideal) :
    ∀ (cs : List (Kind × List Bool)) (pre post : List Ideal) (k : Kind) (zs : List Ideal),
      Ideal.Cont fun x => methodsAt π cs (pre ++ x :: post) k zs
  | [], _, _, _, _ => Ideal.Cont.const _
  | c :: cs, pre, post, k, zs => by
      by_cases h : k = c.1
      · simp only [methodsAt, if_pos h]
        cases pre with
        | nil => exact cont_caseValue_method π c.2 zs
        | cons p pre =>
            simp only [List.cons_append, List.headD_cons]
            exact Ideal.Cont.const _
      · simp only [methodsAt, if_neg h]
        cases pre with
        | nil =>
            simp only [List.nil_append, List.tail_cons]
            exact Ideal.Cont.const _
        | cons p pre =>
            simp only [List.cons_append, List.tail_cons]
            exact cont_methodsAt_method π cs pre post k zs

/-- **At a listed constructor the methods are its method.** -/
theorem methodsAt_getElem (π : Ideal) :
    ∀ {cs : List (Kind × List Bool)} (μs : List Ideal) {i : Nat} {k : Kind} {bs : List Bool},
      (cs.map Prod.fst).Nodup → cs[i]? = some (k, bs) →
        methodsAt π cs μs k = caseValue π (μs.getD i Ideal.bot) bs
  | [], _, _, _, _, _, h => nomatch h
  | c :: cs, μs, 0, k, bs, _, h => by
      cases h
      funext zs
      simp only [methodsAt]
      cases μs <;> rfl
  | c :: cs, μs, i + 1, k, bs, nodup, h => by
      rw [List.map_cons, List.nodup_cons] at nodup
      have hk : k ≠ c.1 := fun e => nodup.1 (e ▸ List.mem_map.2 ⟨(k, bs), List.mem_of_getElem? h,
          rfl⟩)
      funext zs
      simp only [methodsAt, if_neg hk]
      rw [methodsAt_getElem π μs.tail nodup.2 h]
      cases μs <;> rfl

/-! ## The recursion as a function of its arguments -/

/-- **Recursion over the constructors `cs`, as a function of its arguments**: the motive, a
method for each constructor, and the element. -/
def recH (cs : List (Kind × List Bool)) (args : List Ideal) : Ideal :=
  recI cs (methodsAt (args.headD Ideal.bot) cs args.tail) (args.getD (cs.length + 1) Ideal.bot)

theorem contEach_recH (cs : List (Kind × List Bool)) : ContEach (recH cs) := by
  intro pre post
  have hM : ∀ w k, Ideal.ContList (methodsAt ((pre ++ w :: post).headD Ideal.bot) cs
      (pre ++ w :: post).tail k) := fun w k => contList_methodsAt _ cs _ k
  have hMw : ∀ k zs, Ideal.Cont fun w => methodsAt ((pre ++ w :: post).headD Ideal.bot) cs
      (pre ++ w :: post).tail k zs := by
    intro k zs
    cases pre with
    | nil => exact cont_methodsAt_motive cs post k zs
    | cons p pre => exact cont_methodsAt_method p cs pre post k zs
  have h₂ : Ideal.Cont₂ fun w ν => recI cs (methodsAt ((pre ++ w :: post).headD Ideal.bot) cs
      (pre ++ w :: post).tail) ν :=
    ⟨fun ν => Ideal.cont_recI_param hM hMw ν, fun w => Ideal.cont_recI (hM w)⟩
  exact h₂.comp Ideal.Cont.id (cont_getD_at pre post _)

/-! ## Nondependent function types in the domain -/

/-- **Nondependent function types** `A₁ → ⋯ → Aₙ → B`. -/
def arrowsI : List Ideal → Ideal → Ideal
  | [], B => B
  | A :: As, B => cpi A fun _ => arrowsI As B

theorem churchTele_arrowsI (B : Ideal) :
    ∀ As : List Ideal, Ideal.ChurchTele As.length (arrowsI As B)
  | [] => trivial
  | A :: As => ⟨A, fun _ => arrowsI As B, Ideal.Cont.const _, rfl, fun _ => churchTele_arrowsI B As⟩

theorem arrowsI_append (A B : Ideal) :
    ∀ As : List Ideal, arrowsI (As ++ [A]) B = arrowsI As (cpi A fun _ => B)
  | [] => rfl
  | A' :: As => by
      show (cpi A' fun _ => arrowsI (As ++ [A]) B) = cpi A' fun _ => arrowsI As (cpi A fun _ => B)
      rw [arrowsI_append A B As]

/-- At as many arguments as arrows, the instantiated type is the result type. -/
theorem instPi_arrowsI (B : Ideal) :
    ∀ (As args : List Ideal), args.length = As.length → instPi (arrowsI As B) args = B
  | [], [], _ => rfl
  | A :: As, a :: args, h => by
      show instPi (Ideal.fam .pi (cpi A fun _ => arrowsI As B)
        (projT (Ideal.dom .pi (cpi A fun _ => arrowsI As B)) a)) args = B
      rw [Ideal.dom_cpi, Ideal.fam_cpi (Ideal.Cont.const _)]
      exact instPi_arrowsI B As args (by simpa only [List.length_cons,
          Nat.add_right_cancel_iff] using h)
  | [], _ :: _, h => by simp only [List.length_cons, List.length_nil, Nat.add_eq_zero_iff,
      List.length_eq_zero_iff, one_ne_zero, and_false] at h
  | _ :: _, [], h => by
      simp only [List.length_nil, List.length_cons] at h
      exact absurd h (by omega)

/-- Spine facts at nondependent function types: each argument is an element of its arrow. -/
theorem spineTyped_arrowsI (B : Ideal) :
    ∀ (As args : List Ideal), SpineTyped (arrowsI As B) args → args.length ≤ As.length →
      ∀ (i : Nat) (a A : Ideal), args[i]? = some a → As[i]? = some A → projT A a = a
  | [], [], _, _, _, _, _, h, _ => nomatch h
  | [], _ :: _, _, hl, _, _, _, _, _ => by simp only [List.length_cons, List.length_nil,
      nonpos_iff_eq_zero, Nat.add_eq_zero_iff, List.length_eq_zero_iff, one_ne_zero,
      and_false] at hl
  | _ :: _, [], _, _, _, _, _, h, _ => nomatch h
  | A :: As, a :: args, ⟨ha, hs⟩, hl, i, x, X, hx, hX => by
      change projT (Ideal.dom .pi (cpi A fun _ => arrowsI As B)) a = a at ha
      change SpineTyped (Ideal.fam .pi (cpi A fun _ => arrowsI As B)
        (projT (Ideal.dom .pi (cpi A fun _ => arrowsI As B)) a)) args at hs
      rw [Ideal.dom_cpi] at ha hs
      rw [Ideal.fam_cpi (Ideal.Cont.const _)] at hs
      cases i with
      | zero =>
          cases hx
          cases hX
          exact ha
      | succ i => exact spineTyped_arrowsI B As args hs (by simpa only [List.length_cons,
          Nat.add_le_add_iff_right] using hl) i x X hx hX

/-! ## Telescopes of declared types -/

theorem liftTm_closeType : ∀ {k : Nat} (Θ : Ctx Tower.Head k) (C : Tm Tower.Head k),
    liftTm (TelescopeAbstraction.closeType Θ C) = pisCtx (liftCtx Θ) (liftTm C)
  | _, .nil, _ => rfl
  | _, .snoc Θ A, C => liftTm_closeType Θ (.pi A C)

/-- **A telescope of closed entries denotes nondependent function types.** -/
theorem cinterp_closeType_closed (Rd : Reading Tower.Head) (F : Nat → Tm Tower.Head 0) :
    ∀ (N : Nat) (C : Tm Tower.Head N) (K : Ideal), (∀ ρ, cinterp Rd (liftTm C) ρ = K) →
      cinterp Rd (liftTm (TelescopeAbstraction.closeType
          (ofEntries (fun j => Presentation.liftClosed (F j)) N) C)) Env.nil =
        arrowsI ((List.range N).map fun j => cinterp Rd (liftTm (F j)) Env.nil) K
  | 0, C, K, hC => hC Env.nil
  | N + 1, C, K, hC => by
      rw [closeType_ofEntries_succ]
      rw [cinterp_closeType_closed Rd F N (.pi (Presentation.liftClosed (F N)) C)
        (cpi (cinterp Rd (liftTm (F N)) Env.nil) fun _ => K) fun ρ => by
          show cpi (cinterp Rd (liftTm (Presentation.liftClosed (F N))) ρ)
            (fun y => cinterp Rd (liftTm C) (Env.cons y ρ)) = _
          rw [liftTm_liftClosed, cinterp_liftClosed]
          simp only [hC]]
      rw [List.range_succ, List.map_append, List.map_singleton, arrowsI_append]

/-- The projected arguments of a telescope given by its entries: each argument projected onto
its entry, read at the projected arguments before it. -/
theorem projArgs_cinterp_ofEntries (Rd : Reading Tower.Head) (e : (j : Nat) → Tm Tower.Head j) :
    ∀ (N : Nat) (C : Tm Tower.Head N) (args : List Ideal), args.length = N →
      ∀ j, j < N →
        (projArgs (cinterp Rd (liftTm (TelescopeAbstraction.closeType (ofEntries e N) C)) Env.nil)
            args)[j]? =
          some (projT (cinterp Rd (liftTm (e j)) (Env.ofArgs j
            ((projArgs (cinterp Rd (liftTm (TelescopeAbstraction.closeType (ofEntries e N) C))
              Env.nil) args).take j))) (args.getD j Ideal.bot))
  | 0, _, _, _, _, hj => absurd hj (Nat.not_lt_zero _)
  | N + 1, C, args, hlen, j, hj => by
      rcases List.eq_nil_or_concat args with rfl | ⟨xs, a, rfl⟩
      · exact absurd hlen (by simp only [List.length_nil]; omega)
      rw [List.concat_eq_append] at hlen ⊢
      have hxs : xs.length = N := by simpa only [List.length_append, List.length_cons,
          List.length_nil, zero_add, Nat.add_right_cancel_iff] using hlen
      rw [closeType_ofEntries_succ]
      have hT := liftTm_closeType (ofEntries e N) (.pi (e N) C)
      have inst := instPi_cinterp_pisCtx Rd (liftCtx (ofEntries e N)) (liftTm (.pi (e N) C)) xs hxs
      rw [← hT] at inst
      rw [projArgs_append, inst]
      have hlenP : (projArgs (cinterp Rd (liftTm (TelescopeAbstraction.closeType (ofEntries e N)
          (.pi (e N) C))) Env.nil) xs).length = N := by rw [length_projArgs, hxs]
      rcases Nat.lt_or_ge j N with hjN | hjN
      · rw [List.getElem?_append_left (by omega),
          projArgs_cinterp_ofEntries Rd e N (.pi (e N) C) xs hxs j hjN,
          List.take_append_of_le_length (by omega)]
        congr 2
        rw [List.getD_eq_getElem?_getD, List.getD_eq_getElem?_getD,
          List.getElem?_append_left (by omega)]
      · obtain rfl : j = N := by omega
        rw [List.getElem?_append_right (by omega), hlenP, Nat.sub_self,
          List.take_append_of_le_length (by omega), List.take_of_length_le (by omega)]
        show some (projT (Ideal.dom .pi (cinterp Rd (.pi (liftTm (e j)) (liftTm C))
          (Env.ofArgs j _))) a) = _
        rw [dom_cinterp_pi, List.getD_eq_getElem?_getD, List.getElem?_append_right (by omega),
          hxs, Nat.sub_self]
        rfl

/-- **A spine with spine facts at a telescope given by its entries**: each argument is an
element of its entry, read at the arguments before it. -/
theorem spineTyped_ofEntries (Rd : Reading Tower.Head) (e : (j : Nat) → Tm Tower.Head j)
    (N : Nat) (C : Tm Tower.Head N) {args : List Ideal} (hlen : args.length = N)
    (spine : SpineTyped (cinterp Rd (liftTm (TelescopeAbstraction.closeType (ofEntries e N) C))
      Env.nil) args) (j : Nat) (hj : j < N) :
    projT (cinterp Rd (liftTm (e j)) (Env.ofArgs j (args.take j))) (args.getD j Ideal.bot) =
      args.getD j Ideal.bot := by
  have h := projArgs_cinterp_ofEntries Rd e N C args hlen j hj
  rw [Ideal.projArgs_of_spineTyped spine] at h
  rw [List.getD_eq_getElem?_getD] at h ⊢
  rw [List.getElem?_eq_getElem (by omega)] at h ⊢
  exact (Option.some.inj h).symm

/-- The instantiated type of a telescope given by its entries at all of its arguments. -/
theorem instPi_cinterp_ofEntries (Rd : Reading Tower.Head) (e : (j : Nat) → Tm Tower.Head j)
    (N : Nat) (C : Tm Tower.Head N) (args : List Ideal) (hlen : args.length = N) :
    instPi (cinterp Rd (liftTm (TelescopeAbstraction.closeType (ofEntries e N) C)) Env.nil) args =
      cinterp Rd (liftTm C) (Env.ofArgs N
        (projArgs (cinterp Rd (liftTm (TelescopeAbstraction.closeType (ofEntries e N) C))
          Env.nil) args)) := by
  have h := instPi_cinterp_pisCtx Rd (liftCtx (ofEntries e N)) (liftTm C) args hlen
  rw [← liftTm_closeType] at h
  exact h

theorem piArity_closeType (e : (j : Nat) → Tm Tower.Head j) (N : Nat) (C : Tm Tower.Head N) :
    N ≤ piArity (liftTm (TelescopeAbstraction.closeType (ofEntries e N) C)) := by
  rw [liftTm_closeType, piArity_pisCtx]
  exact Nat.le_add_right _ _

/-! ## The fields of a declared datatype in the domain -/

/-- Whether a field is recursive. -/
def fieldFlag : CtorField → Bool
  | .recursive => true
  | .closed _ => false

/-- The closed field types of a constructor, in order. -/
def closedTypes : List (CtorField) → List (Tm Tower.Head 0)
  | [] => []
  | .recursive :: fs => closedTypes fs
  | .closed F :: fs => F :: closedTypes fs

/-- **The shapes of a constructor's fields**, its closed fields numbered from `j`: the datatype
itself for a recursive field, the next parameter for a closed one. -/
def fieldShapes : Nat → List (CtorField) → List FieldShape
  | _, [] => []
  | j, .recursive :: fs => .self :: fieldShapes j fs
  | j, .closed _ :: fs => .param j :: fieldShapes (j + 1) fs

/-- **The parameters of a declared datatype**: the closed field types of its constructors, in
order. -/
def paramTypes (cs : List (DeclName × List (CtorField))) : List (Tm Tower.Head 0) :=
  cs.flatMap fun c => closedTypes c.2

/-- The shapes of the constructors' fields, the parameters numbered from `j`. -/
def ctorShapes : Nat → List (DeclName × List (CtorField)) →
    List (DeclName × List FieldShape)
  | _, [] => []
  | j, c :: cs => (c.1, fieldShapes j c.2) :: ctorShapes (j + (closedTypes c.2).length) cs

/-- The shapes of the fields of the constructor `k`, if it is listed. -/
def shapesOf : Nat → List (DeclName × List (CtorField)) → DeclName →
    Option (List FieldShape)
  | _, [], _ => none
  | j, c :: cs, k =>
      if k = c.1 then some (fieldShapes j c.2) else shapesOf (j + (closedTypes c.2).length) cs k

theorem fieldShapes_length : ∀ (j : Nat) (fs : List (CtorField)),
    (fieldShapes j fs).length = fs.length
  | _, [] => rfl
  | j, .recursive :: fs => by simp only [fieldShapes, List.length_cons, fieldShapes_length j fs]
  | j, .closed _ :: fs => by simp only [fieldShapes, List.length_cons,
      fieldShapes_length (j + 1) fs]

theorem fieldShapes_flags : ∀ (j : Nat) (fs : List (CtorField)),
    (fieldShapes j fs).map FieldShape.isSelf = fs.map fieldFlag
  | _, [] => rfl
  | j, .recursive :: fs => by
      simp only [fieldShapes, List.map_cons, fieldShapes_flags j fs]
      rfl
  | j, .closed _ :: fs => by
      simp only [fieldShapes, List.map_cons, fieldShapes_flags (j + 1) fs]
      rfl

/-- **The type of each field shape is the field's type**, when the parameters from `j` are the
constructor's closed field types. -/
theorem fieldShapes_typeI (T : DeclName) (ps : List Ideal) (read : Tm Tower.Head 0 → Ideal) :
    ∀ (j : Nat) (fs : List (CtorField)),
      (∀ q F, (closedTypes fs)[q]? = some F → ps[j + q]? = some (read F)) →
      (fieldShapes j fs).map (FieldShape.typeI T ps) =
        fs.map fun f => match f with
          | .recursive => ctorI (Kind.data T) ps
          | .closed F => read F
  | _, [], _ => rfl
  | j, .recursive :: fs, h => by
      simp only [fieldShapes, List.map_cons]
      rw [fieldShapes_typeI T ps read j fs h]
      rfl
  | j, .closed F :: fs, h => by
      simp only [fieldShapes, List.map_cons]
      have h0 := h 0 F rfl
      rw [Nat.add_zero] at h0
      rw [fieldShapes_typeI T ps read (j + 1) fs fun q F' hq => by
        have := h (q + 1) F' (by simpa only [closedTypes, List.getElem?_cons_succ] using hq)
        rwa [show j + (q + 1) = j + 1 + q by omega] at this]
      show (ps[j]?.getD Ideal.bot) :: _ = _
      rw [h0]
      rfl

theorem ctorShapes_names : ∀ (j : Nat) (cs : List (DeclName × List (CtorField))),
    (ctorShapes j cs).map Prod.fst = cs.map Prod.fst
  | _, [] => rfl
  | j, c :: cs => by simp only [ctorShapes, List.map_cons, ctorShapes_names _ cs]

theorem ctorShapes_getElem? :
    ∀ (j : Nat) {cs : List (DeclName × List (CtorField))} {i : Nat} {k : DeclName}
      {fs : List (CtorField)}, cs[i]? = some (k, fs) →
        (ctorShapes j cs)[i]? = some (k, fieldShapes (j + (paramTypes (cs.take i)).length) fs)
  | _, [], _, _, _, h => nomatch h
  | j, c :: cs, 0, k, fs, h => by
      cases h
      simp only [ctorShapes, List.length_cons, Nat.lt_add_one_iff, zero_le, getElem?_pos,
          List.getElem_cons_zero, paramTypes, List.take_zero, List.flatMap_nil, List.length_nil,
          add_zero]
  | j, c :: cs, i + 1, k, fs, h => by
      have h' : cs[i]? = some (k, fs) := by simpa only [List.getElem?_cons_succ] using h
      simp only [ctorShapes, List.getElem?_cons_succ]
      rw [ctorShapes_getElem? _ h']
      simp only [List.take_succ_cons, paramTypes, List.flatMap_cons, List.length_append,
        Nat.add_assoc]

theorem shapesOf_getElem? :
    ∀ (j : Nat) {cs : List (DeclName × List (CtorField))} {i : Nat} {k : DeclName}
      {fs : List (CtorField)}, (cs.map Prod.fst).Nodup → cs[i]? = some (k, fs) →
        shapesOf j cs k = some (fieldShapes (j + (paramTypes (cs.take i)).length) fs)
  | _, [], _, _, _, _, h => nomatch h
  | j, c :: cs, 0, k, fs, _, h => by
      cases h
      simp only [shapesOf, ↓reduceIte, paramTypes, List.take_zero, List.flatMap_nil,
          List.length_nil, add_zero]
  | j, c :: cs, i + 1, k, fs, nodup, h => by
      rw [List.map_cons, List.nodup_cons] at nodup
      have hk : k ≠ c.1 := fun e =>
        nodup.1 (e ▸ List.mem_map.2 ⟨(k, fs), List.mem_of_getElem? h, rfl⟩)
      have h' : cs[i]? = some (k, fs) := by simpa only [List.getElem?_cons_succ] using h
      rw [shapesOf, if_neg hk, shapesOf_getElem? _ nodup.2 h']
      simp only [List.take_succ_cons, paramTypes, List.flatMap_cons, List.length_append,
        Nat.add_assoc]

theorem shapesOf_none : ∀ (j : Nat) {cs : List (DeclName × List (CtorField))} {k : DeclName},
    k ∉ cs.map Prod.fst → shapesOf j cs k = none
  | _, [], _, _ => rfl
  | j, c :: cs, k, h => by
      rw [List.map_cons, List.mem_cons, not_or] at h
      rw [shapesOf, if_neg h.1, shapesOf_none _ h.2]

/-- The parameters of the constructors around the constructor at `i`. -/
theorem paramTypes_split {cs : List (DeclName × List (CtorField))} {i : Nat} {k : DeclName}
    {fs : List (CtorField)} (h : cs[i]? = some (k, fs)) :
    paramTypes cs = paramTypes (cs.take i) ++ closedTypes fs ++ paramTypes (cs.drop (i + 1)) := by
  have hi : i < cs.length := by
    rcases Nat.lt_or_ge i cs.length with hi | hi
    · exact hi
    · rw [List.getElem?_eq_none hi] at h; cases h
  conv_lhs => rw [← List.take_append_drop i cs]
  rw [List.drop_eq_getElem_cons hi]
  have e : cs[i] = (k, fs) := by rw [List.getElem?_eq_getElem hi] at h; exact Option.some.inj h
  simp only [paramTypes, e, List.flatMap_append, List.flatMap_cons, List.append_assoc]

/-! ## A declared datatype in the domain -/

variable (d : Datatype Tower.Head)

/-- The parameters of the datatype in the domain: its closed field types, read by the object
reading. -/
def dataParams : List Ideal :=
  (paramTypes d.ctors).map fun F => cinterp objectChurchReading (liftTm F) Env.nil

/-- **The type of a declared datatype**: the type former of the datatype at its parameters. -/
def dataTypeI : Ideal := ctorI (Kind.data d.type) (dataParams d)

/-- The constructors of the datatype as recursion reads them. -/
def dataCs : List (Kind × List Bool) := Ideal.dataCtors d.type (ctorShapes 0 d.ctors)

/-- The type of a field: the datatype for a recursive field, the closed type read by the object
reading for a closed one. -/
def fieldTypeI : CtorField → Ideal
  | .recursive => dataTypeI d
  | .closed F => cinterp objectChurchReading (liftTm F) Env.nil

/-- **A constructor**: the constructor element of its arguments, curried and projected onto the
nondependent function type of its field shapes. -/
def ctorConstI (k : DeclName) (shapes : List FieldShape) : Ideal :=
  projT (arrowsI (shapes.map (FieldShape.typeI d.type (dataParams d))) (dataTypeI d))
    (curryI (ctorI (Kind.ctor d.type k shapes)) shapes.length [])

/-- The object reading with the type and the constructors of the datatype. -/
def dataStage : Reading Tower.Head where
  head := objectChurchReading.head
  const c := if c = d.type then dataTypeI d else
    match shapesOf 0 d.ctors c with
    | some shapes => ctorConstI d c shapes
    | none => objectChurchReading.const c

/-- **The recursor**: recursion over the datatype, curried over the motive, the methods and the
element, projected onto the denotation of its declared type. -/
def recConstI : Ideal :=
  projT (cinterp (dataStage d) (liftTm (recType d.type d.motiveUniverse d.ctors)) Env.nil)
    (curryI (recH (dataCs d)) (d.ctors.length + 2) [])

/-- **The reading of the object package with a declared datatype**: the object reading, the
datatype at its parameters, its constructors and its recursor. -/
def dataReading : Reading Tower.Head where
  head := objectChurchReading.head
  const c := if c = d.recursor then recConstI d else (dataStage d).const c

/-- The kinds of the constructors are distinct when their names are. -/
theorem dataCs_nodup (h : (d.ctors.map Prod.fst).Nodup) : ((dataCs d).map Prod.fst).Nodup :=
  Ideal.dataCtors_nodup d.type (by rw [ctorShapes_names]; exact h)

theorem ctorShapes_length : ∀ (j : Nat) (cs : List (DeclName × List CtorField)),
    (ctorShapes j cs).length = cs.length
  | _, [] => rfl
  | j, _ :: cs => by simp only [ctorShapes, List.length_cons, ctorShapes_length _ cs]

theorem dataCs_length : (dataCs d).length = d.ctors.length := by
  simp only [dataCs, Ideal.dataCtors, List.length_map, ctorShapes_length]

/-! ## Constants a term avoids -/

/-- The constants of a lifted term avoid `f` when the term does. -/
theorem termConsts_liftTm_ne {f : DeclName} :
    ∀ {n : Nat} (t : Tm Tower.Head n), lamFree t = true → ConstFree f t →
      ∀ c ∈ termConsts (liftTm t), c ≠ f
  | _, .var _, _, _, c, h => absurd h List.not_mem_nil
  | _, .const _, _, free, c, h => by
      rw [List.mem_singleton.1 h]
      exact free
  | _, .head _, _, _, c, h => absurd h List.not_mem_nil
  | _, .pi A B, lf, free, c, h => by
      simp only [lamFree, Bool.and_eq_true] at lf
      rcases List.mem_append.1 h with h | h
      · exact termConsts_liftTm_ne A lf.1 free.1 c h
      · exact termConsts_liftTm_ne B lf.2 free.2 c h
  | _, .sigma A B, lf, free, c, h => by
      simp only [lamFree, Bool.and_eq_true] at lf
      rcases List.mem_append.1 h with h | h
      · exact termConsts_liftTm_ne A lf.1 free.1 c h
      · exact termConsts_liftTm_ne B lf.2 free.2 c h
  | _, .id A a b, lf, free, c, h => by
      simp only [lamFree, Bool.and_eq_true] at lf
      rcases List.mem_append.1 h with h | h
      · exact termConsts_liftTm_ne A lf.1.1 free.1 c h
      · rcases List.mem_append.1 h with h | h
        · exact termConsts_liftTm_ne a lf.1.2 free.2.1 c h
        · exact termConsts_liftTm_ne b lf.2 free.2.2 c h
  | _, .lam _, lf, _, _, _ => nomatch lf
  | _, .app g a, lf, free, c, h => by
      simp only [lamFree, Bool.and_eq_true] at lf
      rcases List.mem_append.1 h with h | h
      · exact termConsts_liftTm_ne g lf.1 free.1 c h
      · exact termConsts_liftTm_ne a lf.2 free.2 c h
  | _, .pair a b, lf, free, c, h => by
      simp only [lamFree, Bool.and_eq_true] at lf
      rcases List.mem_append.1 h with h | h
      · exact termConsts_liftTm_ne a lf.1 free.1 c h
      · exact termConsts_liftTm_ne b lf.2 free.2 c h
  | _, .fst p, lf, free, c, h => termConsts_liftTm_ne p lf free c h
  | _, .snd p, lf, free, c, h => termConsts_liftTm_ne p lf free c h
  | _, .refl a, lf, free, c, h => termConsts_liftTm_ne a lf free c h

/-- A term avoids `f` when the constants of its lift do. -/
theorem constFree_of_termConsts {f : DeclName} :
    ∀ {n : Nat} (t : Tm Tower.Head n), (∀ c ∈ termConsts (liftTm t), c ≠ f) → ConstFree f t
  | _, .var _, _ => trivial
  | _, .const _, h => h _ List.mem_cons_self
  | _, .head _, _ => trivial
  | _, .pi A B, h => ⟨constFree_of_termConsts A fun c hc => h c (List.mem_append_left _ hc),
      constFree_of_termConsts B fun c hc => h c (List.mem_append_right _ hc)⟩
  | _, .sigma A B, h => ⟨constFree_of_termConsts A fun c hc => h c (List.mem_append_left _ hc),
      constFree_of_termConsts B fun c hc => h c (List.mem_append_right _ hc)⟩
  | _, .id A a b, h => ⟨constFree_of_termConsts A fun c hc => h c (List.mem_append_left _ hc),
      constFree_of_termConsts a fun c hc =>
        h c (List.mem_append_right _ (List.mem_append_left _ hc)),
      constFree_of_termConsts b fun c hc =>
        h c (List.mem_append_right _ (List.mem_append_right _ hc))⟩
  | _, .lam b, h => constFree_of_termConsts b fun c hc => h c (List.mem_append_right _ hc)
  | _, .app g a, h => ⟨constFree_of_termConsts g fun c hc => h c (List.mem_append_left _ hc),
      constFree_of_termConsts a fun c hc => h c (List.mem_append_right _ hc)⟩
  | _, .pair a b, h => ⟨constFree_of_termConsts a fun c hc => h c (List.mem_append_left _ hc),
      constFree_of_termConsts b fun c hc => h c (List.mem_append_right _ hc)⟩
  | _, .fst p, h => constFree_of_termConsts p h
  | _, .snd p, h => constFree_of_termConsts p h
  | _, .refl a, h => constFree_of_termConsts a h

theorem constFree_caseHyps_length {f : DeclName} :
    ∀ (k : Nat) {n : Nat} (rs : List (Tm Tower.Head n)), rs.length = k →
      ∀ (p target : Tm Tower.Head n), ConstFree f p → ConstFree f target →
        (∀ r ∈ rs, ConstFree f r) → ConstFree f (caseHyps p rs target)
  | _, _, [], _, p, target, hp, ht, _ => by
      rw [caseHyps_nil]
      exact ⟨hp, ht⟩
  | k + 1, _, r :: rs, hk, p, target, hp, ht, hr => by
      rw [caseHyps_cons]
      exact ⟨⟨hp, hr r List.mem_cons_self⟩, constFree_caseHyps_length k
        (rs.map (Presentation.rename wk)) (by rw [List.length_map]; exact Nat.succ.inj hk)
        _ _ (hp.rename wk) (ht.rename wk) fun r' hr' => by
          obtain ⟨r₀, h₀, rfl⟩ := List.mem_map.1 hr'
          exact (hr r₀ (List.mem_cons_of_mem _ h₀)).rename wk⟩
  | 0, _, _ :: _, hk, _, _, _, _, _ => absurd hk (Nat.succ_ne_zero _)

theorem constFree_caseHyps {f : DeclName} {n : Nat} (rs : List (Tm Tower.Head n))
    (p target : Tm Tower.Head n) (hp : ConstFree f p) (ht : ConstFree f target)
    (hr : ∀ r ∈ rs, ConstFree f r) : ConstFree f (caseHyps p rs target) :=
  constFree_caseHyps_length rs.length rs rfl p target hp ht hr

theorem constFree_caseFields {f T k : DeclName} (hT : T ≠ f) (hk : k ≠ f) :
    ∀ (fs : List CtorField) {n : Nat} (p : Tm Tower.Head n) (xs recs : List (Tm Tower.Head n)),
      (∀ F, Field.closed F ∈ fs → ConstFree f F) → ConstFree f p →
      (∀ x ∈ xs, ConstFree f x) → (∀ r ∈ recs, ConstFree f r) →
      ConstFree f (caseFields T k fs p xs recs)
  | [], _, p, xs, recs, _, hp, hxs, hrecs =>
      constFree_caseHyps recs p _ hp (ConstFree.appSpine (constFree_const.mpr hk) hxs) hrecs
  | .recursive :: fs, _, p, xs, recs, hF, hp, hxs, hrecs => by
      refine ⟨constFree_const.mpr hT, constFree_caseFields hT hk fs _ _ _
        (fun F h => hF F (List.mem_cons_of_mem _ h)) (hp.rename wk) ?_ ?_⟩
      · intro x hx
        rcases List.mem_append.1 hx with hx | hx
        · obtain ⟨x₀, h₀, rfl⟩ := List.mem_map.1 hx
          exact (hxs x₀ h₀).rename wk
        · rw [List.mem_singleton.1 hx]; trivial
      · intro r hr
        rcases List.mem_append.1 hr with hr | hr
        · obtain ⟨r₀, h₀, rfl⟩ := List.mem_map.1 hr
          exact (hrecs r₀ h₀).rename wk
        · rw [List.mem_singleton.1 hr]; trivial
  | .closed F :: fs, _, p, xs, recs, hF, hp, hxs, hrecs => by
      refine ⟨(hF F List.mem_cons_self).liftClosed, constFree_caseFields hT hk fs _ _ _
        (fun F h => hF F (List.mem_cons_of_mem _ h)) (hp.rename wk) ?_ ?_⟩
      · intro x hx
        rcases List.mem_append.1 hx with hx | hx
        · obtain ⟨x₀, h₀, rfl⟩ := List.mem_map.1 hx
          exact (hxs x₀ h₀).rename wk
        · rw [List.mem_singleton.1 hx]; trivial
      · intro r hr
        obtain ⟨r₀, h₀, rfl⟩ := List.mem_map.1 hr
        exact (hrecs r₀ h₀).rename wk

theorem constFree_closeType {f : DeclName} (e : (j : Nat) → Tm Tower.Head j)
    (he : ∀ j, ConstFree f (e j)) :
    ∀ (N : Nat) (C : Tm Tower.Head N), ConstFree f C →
      ConstFree f (TelescopeAbstraction.closeType (ofEntries e N) C)
  | 0, _, hC => hC
  | N + 1, C, hC => by
      rw [closeType_ofEntries_succ]
      exact constFree_closeType e he N _ ⟨he N, hC⟩

/-- **The recursor's declared type avoids every constant other than the datatype, its
constructors and the constants of its closed field types.** -/
theorem constFree_recType {f T : DeclName} (v : Tower.Head) {cs : List (DeclName × List CtorField)}
    (hT : T ≠ f) (hk : ∀ c ∈ cs, c.1 ≠ f)
    (hF : ∀ c ∈ cs, ∀ F, Field.closed F ∈ c.2 → ConstFree f F) :
    ConstFree f (recType T v cs) := by
  refine constFree_closeType _ (fun j => ?_) _ _ ⟨trivial, trivial⟩
  cases j with
  | zero => exact ⟨constFree_const.mpr hT, trivial⟩
  | succ j =>
      cases entry : cs[j]? with
      | none =>
          rw [show recEntry T v cs (j + 1) = .const T by simp only [recEntry, entry]]
          exact constFree_const.mpr hT
      | some c =>
          obtain ⟨k, fs⟩ := c
          rw [recEntry_method T v cs entry]
          exact constFree_caseFields hT (hk _ (List.mem_of_getElem? entry)) fs _ [] []
            (hF _ (List.mem_of_getElem? entry)) trivial (fun _ h => nomatch h)
            (fun _ h => nomatch h)


/-! ## Raw spines lifted -/

theorem liftTm_appSpine {n : Nat} : ∀ (xs : List (Tm Tower.Head n)) (f : Tm Tower.Head n),
    liftTm (appSpine f xs) = CTm.appSpine (liftTm f) (xs.map liftTm)
  | [], _ => rfl
  | x :: xs, f => liftTm_appSpine xs (.app f x)

theorem recArgs_eq_recFields {n : Nat} : ∀ (fs : List CtorField) (xs : List (Tm Tower.Head n)),
    recArgs fs xs = Ideal.recFields (fs.map fieldFlag) xs
  | .recursive :: fs, x :: xs => by
      rw [recArgs, recArgs_eq_recFields fs xs]
      rfl
  | .closed _ :: fs, _ :: xs => by
      rw [recArgs, recArgs_eq_recFields fs xs]
      rfl
  | [], _ => by simp only [recArgs, List.map_nil, Ideal.recFields]
  | .recursive :: _, [] => by simp only [recArgs, List.map_cons, List.cons.injEq, List.nil_eq,
      reduceCtorEq, imp_self, implies_true, Ideal.recFields]
  | .closed _ :: _, [] => by simp only [recArgs, List.map_cons, List.cons.injEq, List.nil_eq,
      reduceCtorEq, imp_self, implies_true, Ideal.recFields]

theorem methodsAt_append (π : Ideal) :
    ∀ (cs : List (Kind × List Bool)) (μs extra : List Ideal), μs.length = cs.length →
      methodsAt π cs (μs ++ extra) = methodsAt π cs μs
  | [], _, _, _ => rfl
  | c :: cs, μ :: μs, extra, h => by
      funext k zs
      simp only [methodsAt, List.cons_append, List.headD_cons, List.tail_cons]
      rw [methodsAt_append π cs μs extra (by simpa only [List.length_cons,
          Nat.add_right_cancel_iff] using h)]
  | _ :: _, [], _, h => by
      simp only [List.length_nil, List.length_cons] at h
      exact absurd h (by omega)

/-! ## The package with a declared datatype and its reading -/

/-- **The object package with a declared datatype.** -/
abbrev dataChurch (d : Datatype Tower.Head) : ChurchRules (rulesWith objectRules [.datatype d]) :=
  withDeclarations objectChurch [.datatype d]

/-- The declared type of the recursor, read. -/
abbrev recTypeI (d : Datatype Tower.Head) : Ideal :=
  cinterp (dataReading d) (liftTm (recType d.type d.motiveUniverse d.ctors)) Env.nil

theorem dataReading_recursor : (dataReading d).const d.recursor = recConstI d := if_pos rfl

section Admissible

variable {d : Datatype Tower.Head} (hd : d.Admissible objectChurch)
include hd

theorem dataReading_type : (dataReading d).const d.type = dataTypeI d := by
  simp only [dataReading, dataStage, if_neg (Ne.symm hd.distinct.recNotType), if_true]

theorem dataReading_ctor {i : Nat} {k : DeclName} {fs : List CtorField}
    (h : d.ctors[i]? = some (k, fs)) :
    (dataReading d).const k =
      ctorConstI d k (fieldShapes (paramTypes (d.ctors.take i)).length fs) := by
  have mem : k ∈ d.ctors.map Prod.fst := List.mem_map.2 ⟨(k, fs), List.mem_of_getElem? h, rfl⟩
  have h₁ : k ≠ d.recursor := fun e => hd.distinct.recNotCtor (e ▸ mem)
  have h₂ : k ≠ d.type := fun e => hd.distinct.typeNotCtor (e ▸ mem)
  simp only [dataReading, dataStage, if_neg h₁, if_neg h₂,
    shapesOf_getElem? 0 hd.distinct.ctorsNodup h, Nat.zero_add]

/-- **The reading agrees with the object reading** on every constant the object package
declares. -/
theorem dataReading_object {c : DeclName} (h : objectChurch.constantType c ≠ none) :
    (dataReading d).const c = objectChurchReading.const c := by
  have ne : ∀ {n : DeclName}, objectChurch.constantType n = none → c ≠ n := fun hn e => h (e ▸ hn)
  have notCtor : c ∉ d.ctors.map Prod.fst := fun hc => by
    obtain ⟨e, he, rfl⟩ := List.mem_map.1 hc
    exact h (hd.new.ctorsNew e he)
  simp only [dataReading, dataStage, if_neg (ne hd.new.recNew), if_neg (ne hd.new.typeNew),
    shapesOf_none 0 notCtor]

/-- A closed field type is read as the object reading reads it. -/
theorem dataReading_closedField {entry : DeclName × List CtorField} (hmem : entry ∈ d.ctors)
    {F : Tm Tower.Head 0} (hF : Field.closed F ∈ entry.2) :
    cinterp (dataReading d) (liftTm F) Env.nil = cinterp objectChurchReading (liftTm F) Env.nil :=
  congrFun (cinterp_congr (Rd := dataReading d) (Rd' := objectChurchReading) rfl (liftTm F)
    fun c hc => dataReading_object hd
      (TowerInterpretation.CDerivable.consts_declared (hd.fields entry hmem F hF) c hc)) Env.nil

/-- The type of a field, read. -/
theorem dataReading_fieldType {entry : DeclName × List CtorField} (hmem : entry ∈ d.ctors)
    {f : CtorField} (hf : f ∈ entry.2) :
    cinterp (dataReading d) (liftTm (f.type d.type)) Env.nil = fieldTypeI d f := by
  cases f with
  | recursive => exact dataReading_type hd
  | closed F => exact dataReading_closedField hd hmem hf

/-- **The declared type of a constructor denotes the nondependent function type of its
fields.** -/
theorem cinterp_ctorType {entry : DeclName × List CtorField} (hmem : entry ∈ d.ctors) :
    cinterp (dataReading d) (liftTm (ctorType d.type entry.2)) Env.nil =
      arrowsI (entry.2.map (fieldTypeI d)) (dataTypeI d) := by
  show cinterp (dataReading d) (liftTm (TelescopeAbstraction.closeType
    (ofEntries (fun j => Presentation.liftClosed ((entry.2.getD j .recursive).type d.type))
      entry.2.length) (.const d.type))) Env.nil = _
  rw [cinterp_closeType_closed (dataReading d) (fun j => (entry.2.getD j .recursive).type d.type)
    entry.2.length (.const d.type) (dataTypeI d) (fun _ => dataReading_type hd)]
  congr 1
  apply List.ext_getElem (by simp only [List.getD_eq_getElem?_getD, List.length_map,
      List.length_range])
  intro j h₁ h₂
  simp only [List.getElem_map, List.getElem_range]
  rw [List.getD_eq_getElem?_getD,
      List.getElem?_eq_getElem (by simpa only [List.getD_eq_getElem?_getD, List.length_map,
      List.length_range] using h₁), Option.getD_some]
  exact dataReading_fieldType hd hmem (List.getElem_mem _)

omit hd in
/-- **The types of a constructor's field shapes are the types of its fields.** -/
theorem dataShapes_typeI {i : Nat} {k : DeclName} {fs : List CtorField}
    (h : d.ctors[i]? = some (k, fs)) :
    (fieldShapes (paramTypes (d.ctors.take i)).length fs).map
        (FieldShape.typeI d.type (dataParams d)) = fs.map (fieldTypeI d) := by
  rw [fieldShapes_typeI d.type (dataParams d)
    (fun F => cinterp objectChurchReading (liftTm F) Env.nil) _ fs fun q F hq => ?_]
  · congr 1
  · have hq' : q < (closedTypes fs).length := by
      rcases Nat.lt_or_ge q (closedTypes fs).length with hlt | hge
      · exact hlt
      · rw [List.getElem?_eq_none hge] at hq; cases hq
    rw [dataParams, paramTypes_split h, List.map_append, List.map_append, List.append_assoc,
      List.getElem?_append_right (by simp only [List.length_map,
          Nat.le_add_right]), List.length_map, Nat.add_sub_cancel_left,
      List.getElem?_append_left (by simpa only [List.length_map] using hq'), List.getElem?_map, hq]
    rfl

omit hd in
/-- **A constructor applied to elements of its field types** is its constructor element. -/
theorem appSpine_ctorConstI (k : DeclName) (shapes : List FieldShape) {αs : List Ideal}
    (hlen : αs.length = shapes.length)
    (spine : SpineTyped (arrowsI (shapes.map (FieldShape.typeI d.type (dataParams d)))
      (dataTypeI d)) αs) :
    Ideal.appSpine (ctorConstI d k shapes) αs = ctorI (Kind.ctor d.type k shapes) αs := by
  unfold ctorConstI
  rw [Ideal.appSpine_projT _ (churchTele_arrowsI _ _) (by simp only [hlen, List.length_map,
      Std.le_refl]),
    Ideal.projArgs_of_spineTyped spine, instPi_arrowsI _ _ _ (by simp only [hlen, List.length_map]),
    appSpine_curryI (fun pre post => cont_ctorI_at _ pre post) _ _ _ hlen, List.reverse_nil,
    List.nil_append]
  refine Ideal.projT_data_ctorI fun i x hx => ?_
  have hi : i < shapes.length := by
    rw [← hlen]
    rcases Nat.lt_or_ge i αs.length with hlt | hge
    · exact hlt
    · rw [List.getElem?_eq_none hge] at hx; cases hx
  refine ⟨shapes[i], List.getElem?_eq_getElem hi, ?_⟩
  exact spineTyped_arrowsI _ _ _ spine (by simp only [hlen, List.length_map,
      Std.le_refl]) i x _ hx (by simp only [List.length_map, hi, getElem?_pos, List.getElem_map])

omit hd in
/-- The projected arguments of nondependent function types. -/
theorem projArgs_arrowsI (B : Ideal) :
    ∀ (As args : List Ideal), args.length ≤ As.length →
      projArgs (arrowsI As B) args = List.zipWith projT As args
  | _, [], _ => by rw [List.zipWith_nil_right]; rfl
  | A :: As, a :: args, h => by
      show projT (Ideal.dom .pi (cpi A fun _ => arrowsI As B)) a ::
        projArgs (Ideal.fam .pi (cpi A fun _ => arrowsI As B)
          (projT (Ideal.dom .pi (cpi A fun _ => arrowsI As B)) a)) args = _
      rw [Ideal.dom_cpi, Ideal.fam_cpi (Ideal.Cont.const _),
        projArgs_arrowsI B As args (by simpa only [List.length_cons,
            Nat.add_le_add_iff_right] using h)]
      rfl
  | [], _ :: _, h => by simp only [List.length_cons, List.length_nil, nonpos_iff_eq_zero,
      Nat.add_eq_zero_iff, List.length_eq_zero_iff, one_ne_zero, and_false] at h

omit hd in
/-- **A constructor applied to as many arguments as it has fields** is its constructor element of
the arguments, each projected onto its field's type. -/
theorem appSpine_ctorConstI_proj (k : DeclName) (shapes : List FieldShape) {αs : List Ideal}
    (hlen : αs.length = shapes.length) :
    Ideal.appSpine (ctorConstI d k shapes) αs = ctorI (Kind.ctor d.type k shapes)
      (List.zipWith projT (shapes.map (FieldShape.typeI d.type (dataParams d))) αs) := by
  unfold ctorConstI
  rw [Ideal.appSpine_projT _ (churchTele_arrowsI _ _) (by simp only [hlen, List.length_map,
      Std.le_refl]),
    projArgs_arrowsI _ _ _ (by simp only [hlen, List.length_map,
        Std.le_refl]), instPi_arrowsI _ _ _ (by simp only [hlen, List.length_map]),
    appSpine_curryI (fun pre post => cont_ctorI_at _ pre post) _ _ _
      (by simp only [List.length_zipWith, List.length_map, hlen, min_self]),
    List.reverse_nil, List.nil_append]
  refine Ideal.projT_data_ctorI fun i x hx => ?_
  obtain ⟨hi, hx'⟩ := List.getElem?_eq_some_iff.1 hx
  rw [List.getElem_zipWith] at hx'
  have hi' : i < shapes.length := by
    simp only [List.length_zipWith, List.length_map, lt_inf_iff] at hi
    omega
  refine ⟨shapes[i], List.getElem?_eq_getElem hi', ?_⟩
  rw [← hx']
  simp only [List.getElem_map]
  exact Ideal.projT_projT _ _

/-- The recursor's declared type mentions no recursor. -/
theorem recType_termConsts : ∀ c ∈ termConsts (liftTm (recType d.type d.motiveUniverse d.ctors)),
    c ≠ d.recursor :=
  termConsts_liftTm_ne _ (lamFree_recType _ _ hd.lamFree)
    (constFree_recType _ (Ne.symm hd.distinct.recNotType)
      (fun c hc e => hd.distinct.recNotCtor (e ▸ List.mem_map.2 ⟨c, hc, rfl⟩))
      fun entry hmem F hF => constFree_of_termConsts F fun c hc e =>
        TowerInterpretation.CDerivable.consts_declared (hd.fields entry hmem F hF) c hc
          (e ▸ hd.new.recNew))

/-- **The recursor denotes recursion over the datatype**, curried and projected onto its declared
type. -/
theorem dataReading_recursor_eq :
    (dataReading d).const d.recursor =
      projT (recTypeI d) (curryI (recH (dataCs d)) (d.ctors.length + 2) []) := by
  rw [dataReading_recursor, recConstI]
  congr 1
  exact congrFun (cinterp_congr (Rd := dataStage d) (Rd' := dataReading d) rfl _
    fun c hc => (if_neg (recType_termConsts hd c hc)).symm) Env.nil

omit hd in
/-- **The recursor's declared type after its motive and methods** is the function type from
the datatype to the motive. -/
theorem recTypeI_prefix {pre : List Ideal} (hpre : pre.length = d.ctors.length + 1)
    (spine : SpineTyped (recTypeI d) pre) :
    instPi (recTypeI d) pre = cpi ((dataReading d).const d.type) (fun y =>
      Ideal.app (pre.getD 0 Ideal.bot) y) := by
  have e : recType d.type d.motiveUniverse d.ctors = TelescopeAbstraction.closeType
      (ofEntries (recEntry d.type d.motiveUniverse d.ctors) (d.ctors.length + 1))
      (.pi (recEntry d.type d.motiveUniverse d.ctors (d.ctors.length + 1))
        (recBody d.ctors.length)) :=
    closeType_ofEntries_succ _ _ _
  have spine' := spine
  unfold recTypeI at spine' ⊢
  rw [e] at spine' ⊢
  rw [instPi_cinterp_ofEntries _ _ _ _ pre hpre, Ideal.projArgs_of_spineTyped spine',
    recEntry_scrutinee]
  show cpi ((dataReading d).const d.type)
    (fun y => cinterp (dataReading d) (liftTm (recBody d.ctors.length))
      (Env.cons y (Env.ofArgs (d.ctors.length + 1) pre))) = _
  congr 1
  funext y
  show Ideal.app (Env.cons y (Env.ofArgs (d.ctors.length + 1) pre) (Fin.last (d.ctors.length + 1)))
    y = _
  congr 1
  show Env.ofArgs (d.ctors.length + 1) pre (Fin.last d.ctors.length) = _
  simp only [Env.ofArgs, Nat.add_sub_cancel, Fin.val_last, tsub_self, List.getD_eq_getElem?_getD]

end Admissible


/-! ## The recursor at a constructor -/

theorem mem_recFields {α : Type} {x : α} :
    ∀ {bs : List Bool} {xs : List α}, x ∈ Ideal.recFields bs xs →
      ∃ p : Nat, xs[p]? = some x ∧ bs[p]? = some true
  | true :: bs, y :: xs, h => by
      rcases List.mem_cons.1 h with rfl | h
      · exact ⟨0, rfl, rfl⟩
      · obtain ⟨p, hp, hb⟩ := mem_recFields h
        exact ⟨p + 1, hp, hb⟩
  | false :: bs, _ :: xs, h => by
      obtain ⟨p, hp, hb⟩ := mem_recFields (bs := bs) (xs := xs) h
      exact ⟨p + 1, hp, hb⟩
  | [], _, h => by simp only [Ideal.recFields, List.not_mem_nil] at h
  | true :: _, [], h => by simp only [Ideal.recFields, List.not_mem_nil] at h
  | false :: _, [], h => by simp only [Ideal.recFields, List.not_mem_nil] at h

section Recursion

variable {d : Datatype Tower.Head} (hd : d.Admissible objectChurch)
include hd

omit hd in
/-- A recursive field of an element of the fields' types is an element of the datatype. -/
theorem recField_typed {fs : List CtorField} {αs : List Ideal} (hα : αs.length = fs.length)
    (spine : SpineTyped (arrowsI (fs.map (fieldTypeI d)) (dataTypeI d)) αs) {α : Ideal}
    (mem : α ∈ Ideal.recFields (fs.map fieldFlag) αs) : projT (dataTypeI d) α = α := by
  obtain ⟨p, hp, hb⟩ := mem_recFields mem
  have hpl : p < fs.length := by
    rw [← hα]
    rcases Nat.lt_or_ge p αs.length with hlt | hge
    · exact hlt
    · rw [List.getElem?_eq_none hge] at hp; cases hp
  rw [List.getElem?_map, List.getElem?_eq_getElem hpl] at hb
  have hrec : fs[p] = .recursive := by
    cases e : fs[p] with
    | recursive => rfl
    | closed F => rw [e] at hb; cases hb
  exact spineTyped_arrowsI _ _ _ spine (by simp only [hα, List.length_map, Std.le_refl]) p α _ hp
    (by rw [List.getElem?_map, List.getElem?_eq_getElem hpl, hrec]; rfl)

/-- **The recursor applied to its motive and methods, at an element of the datatype**:
recursion at it, read at the motive there. -/
theorem appSpine_recursor {pre : List Ideal} (hpre : pre.length = d.ctors.length + 1)
    (spine : SpineTyped (recTypeI d) pre) {α : Ideal} (hα : projT (dataTypeI d) α = α) :
    Ideal.appSpine ((dataReading d).const d.recursor) (pre ++ [α]) =
      projT (Ideal.app (pre.getD 0 Ideal.bot) α)
        (recI (dataCs d) (methodsAt (pre.headD Ideal.bot) (dataCs d) pre.tail) α) := by
  have inst := recTypeI_prefix (d := d) hpre spine
  rw [dataReading_type hd] at inst
  have hlen : (pre ++ [α]).length ≤ piArity (liftTm (recType d.type d.motiveUniverse d.ctors)) :=
    le_trans (by simp only [List.length_append, hpre, List.length_cons, List.length_nil, zero_add,
        Std.le_refl]) (piArity_closeType _ _ _)
  rw [dataReading_recursor_eq hd, Ideal.appSpine_projT _ (churchTele_cinterp _ _ _) hlen,
    projArgs_append, Ideal.projArgs_of_spineTyped spine, Ideal.instPi_append, inst,
    projArgs_singleton,
    Ideal.dom_cpi, hα]
  have hfam : Ideal.instPi (cpi (dataTypeI d) fun y => Ideal.app (pre.getD 0 Ideal.bot) y) [α] =
      Ideal.app (pre.getD 0 Ideal.bot) α := by
    show Ideal.fam .pi (cpi (dataTypeI d) _) (projT (Ideal.dom .pi (cpi (dataTypeI d) _)) α) = _
    rw [Ideal.dom_cpi, hα, Ideal.fam_cpi (Ideal.cont₂_app.right _), hα]
  rw [hfam, appSpine_curryI (contEach_recH _) _ _ _ (by simp only [List.length_append, hpre,
      List.length_cons, List.length_nil, zero_add]), List.reverse_nil,
    List.nil_append]
  obtain ⟨π, rest, rfl⟩ : ∃ π rest, pre = π :: rest := by
    cases pre with
    | nil => simp only [List.length_nil] at hpre; exact absurd hpre (by omega)
    | cons π rest => exact ⟨π, rest, rfl⟩
  have hrest : rest.length = (dataCs d).length := by
    rw [dataCs_length]; simpa only [List.length_cons, Nat.add_right_cancel_iff] using hpre
  simp only [recH, List.cons_append, List.headD_cons, List.tail_cons, List.getD_cons_zero]
  rw [methodsAt_append _ _ _ _ hrest]
  congr 1
  rw [List.getD_cons_succ, List.getD_eq_getElem?_getD, List.getElem?_append_right (by omega), hrest,
    Nat.sub_self]
  rfl

/-- **The recursor at a constructor computes by its method**: the recursion's function, at the
motive, the methods and a constructor applied to elements of its field types, is the
constructor's method applied to the fields and to the recursor at each recursive field. -/
theorem recursor_at_ctor {i : Nat} {k : DeclName} {fs : List CtorField}
    (h : d.ctors[i]? = some (k, fs)) {pre αs : List Ideal}
    (hpre : pre.length = d.ctors.length + 1) (hα : αs.length = fs.length)
    (spinePre : SpineTyped (recTypeI d) pre)
    (spineα : SpineTyped (arrowsI (fs.map (fieldTypeI d)) (dataTypeI d)) αs) :
    Ideal.appSpine (curryI (recH (dataCs d)) (d.ctors.length + 2) [])
        (pre ++ [Ideal.appSpine ((dataReading d).const k) αs]) =
      Ideal.appSpine (pre.getD (1 + i) Ideal.bot) (αs ++ (Ideal.recFields (fs.map fieldFlag) αs).map
        fun α => Ideal.appSpine ((dataReading d).const d.recursor) (pre ++ [α])) := by
  have hshapes := dataShapes_typeI h
  have hk : Ideal.appSpine ((dataReading d).const k) αs =
      ctorI (Kind.ctor d.type k (fieldShapes (paramTypes (d.ctors.take i)).length fs)) αs := by
    rw [dataReading_ctor hd h]
    exact appSpine_ctorConstI k _ (by rw [fieldShapes_length]; exact hα)
      (by rw [hshapes]; exact spineα)
  have hdcs : (dataCs d)[i]? = some
      (Kind.ctor d.type k (fieldShapes (paramTypes (d.ctors.take i)).length fs),
          fs.map fieldFlag) := by
    unfold dataCs Ideal.dataCtors
    rw [List.getElem?_map, ctorShapes_getElem? 0 h, Nat.zero_add]
    simp only [Option.map_some, fieldShapes_flags]
  have nodup := dataCs_nodup d hd.distinct.ctorsNodup
  obtain ⟨π, rest, rfl⟩ : ∃ π rest, pre = π :: rest := by
    cases pre with
    | nil => simp only [List.length_nil] at hpre; exact absurd hpre (by omega)
    | cons π rest => exact ⟨π, rest, rfl⟩
  have hrest : rest.length = (dataCs d).length := by
    rw [dataCs_length]; simpa only [List.length_cons, Nat.add_right_cancel_iff] using hpre
  rw [appSpine_curryI (contEach_recH _) _ _ _
    (by simp only [List.length_append, List.length_cons, List.length_nil] at hpre ⊢; omega),
    List.reverse_nil, List.nil_append]
  simp only [recH, List.cons_append, List.headD_cons, List.tail_cons]
  rw [methodsAt_append _ _ _ _ hrest]
  have hscr :
      ((Ideal.appSpine ((dataReading d).const k) αs) :: ([] : List Ideal)).getD 0 Ideal.bot =
      Ideal.appSpine ((dataReading d).const k) αs := rfl
  rw [List.getD_cons_succ, List.getD_eq_getElem?_getD, List.getElem?_append_right (by omega), hrest,
    Nat.sub_self]
  simp only [List.getElem?_cons_zero, Option.getD_some]
  rw [hk, Ideal.recI_ctorI (contList_methodsAt _ _ _) (List.mem_of_getElem? hdcs) nodup
      (by simp only [hα, List.length_map]),
    methodsAt_getElem _ _ nodup hdcs, caseValue_eval _ _ _ (by simp only [hα, List.length_map])]
  congr 1
  · rw [Nat.add_comm, List.getD_cons_succ]
  · congr 1
    apply List.map_congr_left
    intro α mem
    rw [show π :: (rest ++ [α]) = (π :: rest) ++ [α] from rfl,
      appSpine_recursor hd hpre spinePre (recField_typed hα spineα mem)]
    rfl

end Recursion


/-! ## Validity -/

theorem closed_mem_of_closedTypes {F : Tm Tower.Head 0} :
    ∀ {fs : List CtorField}, F ∈ closedTypes fs → Field.closed F ∈ fs
  | [], h => absurd h (by simp only [closedTypes, List.not_mem_nil, not_false_eq_true])
  | .recursive :: _, h => List.mem_cons_of_mem _ (closed_mem_of_closedTypes h)
  | .closed _ :: _, h => by
      rcases List.mem_cons.1 h with rfl | h
      · exact List.mem_cons_self
      · exact List.mem_cons_of_mem _ (closed_mem_of_closedTypes h)

section Validity

variable {d : Datatype Tower.Head} (hd : d.Admissible objectChurch)
include hd

/-- A declared type of the object package is read alike by both readings. -/
theorem dataReading_objectDecl {c : DeclName} {D : CTm Tower.Head 0}
    (declared : objectChurch.constantType c = some D) :
    cinterp (dataReading d) D Env.nil = cinterp objectChurchReading D Env.nil := by
  refine congrFun (cinterp_congr (Rd := dataReading d) (Rd' := objectChurchReading) rfl D
    fun c' hc' => dataReading_object hd (objectChurch_constantType_ne_none ?_)) Env.nil
  rw [declType_of_declared declared] at hc'
  exact closedTerm_iff.1 (ObjConst.declType_closed _) c' hc'

/-- **The type of a declared datatype is a type**: its parameters, the closed field types, are
types of the object package. -/
theorem typeGenerated_dataTypeI : TypeGenerated (dataTypeI d) := by
  refine Ideal.typeGenerated_data d.type fun p hp => ?_
  obtain ⟨F, hF, rfl⟩ := List.mem_map.1 hp
  obtain ⟨entry, hmem, hFe⟩ := List.mem_flatMap.1 hF
  have hcl : Field.closed F ∈ entry.2 := closed_mem_of_closedTypes hFe
  have typed := objectChurchReading_valid.soundnessFacts.typing (hd.fields entry hmem F hcl)
    Env.nil trivial
  have hu : cinterp objectChurchReading (.head d.typeUniverse : CTm Tower.Head 0) Env.nil =
      univIdeal := by
    show principal (objectChurchReading.head d.typeUniverse) = _
    rw [objectChurchReading_valid.universes hd.typeUniverse]
    rfl
  rw [hu] at typed
  exact Ideal.projT_univ_eq_self_iff.1 typed.2

/-- **Every constant of the package denotes an element of its declared type.** -/
theorem dataReading_constants {c : DeclName} {D : CTm Tower.Head 0}
    (declared : (dataChurch d).constantType c = some D) :
    projT (cinterp (dataReading d) D Env.nil) ((dataReading d).const c) =
      (dataReading d).const c := by
  have declared' : sumDecls objectChurch.constantType
      (inductiveChurch objectRules d.type d.typeUniverse d.ctors d.recursor
        d.motiveUniverse).constantType c = some D := declared
  cases hobj : objectChurch.constantType c with
  | some D₀ =>
    obtain rfl : D = D₀ := Option.some.inj (declared'.symm.trans (sumDecls_left hobj))
    rw [dataReading_objectDecl hd hobj, dataReading_object hd (by rw [hobj]; exact nofun)]
    exact objectChurchReading_constants hobj
  | none =>
    rw [sumDecls_right hobj] at declared'
    rcases inductiveChurch_constantType objectRules hd.lamFree declared' with
      ⟨rfl, rfl⟩ | ⟨i, fields, entry, rfl⟩ | ⟨rfl, rfl⟩
    · show projT (principal (objectChurchReading.head d.typeUniverse))
        ((dataReading d).const d.type) = _
      rw [objectChurchReading_valid.universes hd.typeUniverse, dataReading_type hd]
      exact Ideal.projT_univ_eq_self_iff.2 (typeGenerated_dataTypeI hd)
    · rw [cinterp_ctorType hd (entry := (c, fields)) (List.mem_of_getElem? entry),
        dataReading_ctor hd entry, ctorConstI, dataShapes_typeI entry]
      exact Ideal.projT_projT _ _
    · rw [dataReading_recursor_eq hd]
      exact Ideal.projT_projT _ _

/-- **A root step of the object package is valid in the reading**: its schema mentions only the
object package's constants, so its spine facts carry over to the object reading at the values of
its metavariables, where the schema is valid. -/
theorem dataReading_objectRoot {n : Nat} {l r : CTm Tower.Head n} {τ : Ideal} {ρ : Env n}
    (step : objectChurch.computation.step l r)
    (facts : SpineFacts (dataReading d) (dataChurch d) l τ ρ)
    (right : projT τ (cinterp (dataReading d) r ρ) = cinterp (dataReading d) r ρ) :
    cinterp (dataReading d) l ρ = cinterp (dataReading d) r ρ := by
  cases step with
  | instantiate rule σ =>
    obtain ⟨L, R', hS, rfl, rfl⟩ := rule
    have closed := objectSchemas_closed hS
    have agreeL : ∀ c ∈ termConsts (elabLeft objectDecls L),
        (dataReading d).const c = objectChurchReading.const c :=
      fun c hc => dataReading_object hd (objectChurch_constantType_ne_none
        (closedTerm_iff.1 closed.left c hc))
    have agreeR : ∀ c ∈ termConsts (elabRight objectDecls L R'),
        (dataReading d).const c = objectChurchReading.const c :=
      fun c hc => dataReading_object hd (objectChurch_constantType_ne_none
        (closedTerm_iff.1 closed.right c hc))
    have eL : cinterp (dataReading d) ((elabLeft objectDecls L).subst σ) ρ =
        cinterp objectChurchReading (elabLeft objectDecls L)
          fun i => cinterp (dataReading d) (σ i) ρ := by
      rw [cinterp_subst, cinterp_congr (Rd := dataReading d) (Rd' := objectChurchReading) rfl _
        agreeL]
    have eR : cinterp (dataReading d) ((elabRight objectDecls L R').subst σ) ρ =
        cinterp objectChurchReading (elabRight objectDecls L R')
          fun i => cinterp (dataReading d) (σ i) ρ := by
      rw [cinterp_subst, cinterp_congr (Rd := dataReading d) (Rd' := objectChurchReading) rfl _
        agreeR]
    have facts' : SpineFacts objectChurchReading objectChurch
        ((elabLeft objectDecls L).subst CTm.ids) τ
          (fun i => cinterp (dataReading d) (σ i) ρ) := by
      rw [CTm.subst_ids]
      exact SpineFacts.congr (Rd := dataReading d) (Rd' := objectChurchReading)
        (P := dataChurch d) (P' := objectChurch) rfl _ agreeL
        (fun _ _ _ hD => ⟨sumDecls_left hD, dataReading_objectDecl hd hD⟩)
        (SpineFacts.of_subst _ σ facts)
    have right' : projT τ (cinterp objectChurchReading ((elabRight objectDecls L R').subst CTm.ids)
        fun i => cinterp (dataReading d) (σ i) ρ) =
          cinterp objectChurchReading ((elabRight objectDecls L R').subst CTm.ids)
            fun i => cinterp (dataReading d) (σ i) ρ := by
      rw [CTm.subst_ids, ← eR]
      exact right
    have v := objectSchemas_valid hS CTm.ids facts' right'
    rw [CTm.subst_ids, CTm.subst_ids] at v
    rw [eL, eR, v]

end Validity


/-! ## The computation rules of the recursor are valid -/

/-- The left side of a computation rule of the recursor, substituted. -/
theorem iotaLeft_subst (rec k : DeclName) (c a : Nat) {n : Nat}
    (σ : CSub Tower.Head (1 + c + a) n) :
    (liftTm (iotaLeft rec k c a)).subst σ =
      CTm.appSpine (.const rec)
        (((metaVars (1 + c + a)).map fun t => (liftTm t).subst σ).take (1 + c) ++
          [CTm.appSpine (.const k)
            (((metaVars (1 + c + a)).map fun t => (liftTm t).subst σ).drop (1 + c))]) := by
  simp only [iotaLeft, recApp, liftTm_appSpine, csubst_appSpine, List.map_append, List.map_take,
    List.map_drop, List.map_map, List.map_cons, List.map_nil, Function.comp_def]
  rfl

/-- The right side of the computation rule of the constructor at `i`, substituted. -/
theorem iotaRight_subst (rec : DeclName) (c i : Nat) (fs : List CtorField) {n : Nat}
    (σ : CSub Tower.Head (1 + c + fs.length) n) :
    (liftTm (iotaRight rec c i fs)).subst σ =
      CTm.appSpine ((liftTm (((metaVars (1 + c + fs.length)).take (1 + c)).getD (1 + i)
          defaultTm)).subst σ)
        (((metaVars (1 + c + fs.length)).map fun t => (liftTm t).subst σ).drop (1 + c) ++
          (Ideal.recFields (fs.map fieldFlag)
            (((metaVars (1 + c + fs.length)).map fun t => (liftTm t).subst σ).drop (1 + c))).map
            fun t => CTm.appSpine (.const rec)
              (((metaVars (1 + c + fs.length)).map fun t => (liftTm t).subst σ).take (1 + c) ++
                [t])) := by
  simp only [iotaRight, recApp, liftTm_appSpine, csubst_appSpine, List.map_append, List.map_take,
    List.map_drop, List.map_map, List.map_cons, List.map_nil, Function.comp_def,
    recArgs_eq_recFields]
  simp only [← List.map_drop, Ideal.recFields_map, List.map_map, Function.comp_def]
  rfl

section Iota

variable {d : Datatype Tower.Head} (hd : d.Admissible objectChurch)
include hd

/-- **The computation rule of the recursor at a constructor is valid in the reading.** -/
theorem dataReading_iota {i : Nat} {k : DeclName} {fs : List CtorField}
    (entry : d.ctors[i]? = some (k, fs)) {n : Nat}
    (σ : CSub Tower.Head (1 + d.ctors.length + fs.length) n) {τ : Ideal} {ρ : Env n}
    (facts : SpineFacts (dataReading d) (dataChurch d)
      ((liftTm (iotaLeft d.recursor k d.ctors.length fs.length)).subst σ) τ ρ)
    (right : projT τ (cinterp (dataReading d)
        ((liftTm (iotaRight d.recursor d.ctors.length i fs)).subst σ) ρ) =
      cinterp (dataReading d) ((liftTm (iotaRight d.recursor d.ctors.length i fs)).subst σ) ρ) :
    cinterp (dataReading d) ((liftTm (iotaLeft d.recursor k d.ctors.length fs.length)).subst σ) ρ =
      cinterp (dataReading d) ((liftTm (iotaRight d.recursor d.ctors.length i fs)).subst σ) ρ := by
  have hi : i < d.ctors.length := by
    rcases Nat.lt_or_ge i d.ctors.length with hlt | hge
    · exact hlt
    · rw [List.getElem?_eq_none hge] at entry; cases entry
  -- the head of the right side is the method of the constructor
  have hhead : cinterp (dataReading d) ((liftTm (((metaVars (1 + d.ctors.length + fs.length)).take
        (1 + d.ctors.length)).getD (1 + i) defaultTm)).subst σ) ρ =
      ((((metaVars (1 + d.ctors.length + fs.length)).map fun t => (liftTm t).subst σ).map
        (cinterp (dataReading d) · ρ)).take (1 + d.ctors.length)).getD (1 + i) Ideal.bot := by
    have hlen : 1 + i < ((metaVars (Head := Tower.Head) (1 + d.ctors.length + fs.length)).take
        (1 + d.ctors.length)).length := by
      simp only [List.length_take, length_metaVars, Nat.le_add_right, Nat.min_eq_left,
        add_lt_add_iff_left]
      omega
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_getElem hlen, Option.getD_some,
      List.getD_eq_getElem?_getD, ← List.map_take, ← List.map_take, List.getElem?_map,
      List.getElem?_map, List.getElem?_eq_getElem hlen]
    rfl
  rw [iotaLeft_subst] at facts ⊢
  rw [iotaRight_subst] at right ⊢
  generalize hts : ((metaVars (1 + d.ctors.length + fs.length)).map
    fun t => (liftTm t).subst σ) = ts at facts right hhead ⊢
  have htsl : ts.length = 1 + d.ctors.length + fs.length := by
    rw [← hts, List.length_map, length_metaVars]
  rw [cinterp_appSpine] at right
  rw [cinterp_appSpine, cinterp_appSpine]
  rw [hhead] at right ⊢
  -- spine facts of the recursor's spine and of its constructor argument
  obtain ⟨⟨hτ, spine⟩, argFacts⟩ :=
    SpineFacts.constSpine (sum_rec_declared objectChurch hd.distinct hd.lamFree hd.new) facts
  have ctorFacts := argFacts (ts.take (1 + d.ctors.length)) _ [] rfl
  have eL : (ts.take (1 + d.ctors.length) ++
        [CTm.appSpine (.const k) (ts.drop (1 + d.ctors.length))]).map
        (cinterp (dataReading d) · ρ) =
      (ts.take (1 + d.ctors.length)).map (cinterp (dataReading d) · ρ) ++
        [Ideal.appSpine ((dataReading d).const k)
          ((ts.drop (1 + d.ctors.length)).map (cinterp (dataReading d) · ρ))] := by
    simp only [List.map_append, List.map_take, List.map_cons, cinterp_appSpine, cinterp_const,
        List.map_drop, List.map_nil]
  have eR : (ts.drop (1 + d.ctors.length) ++
        (Ideal.recFields (fs.map fieldFlag) (ts.drop (1 + d.ctors.length))).map
          (fun t => CTm.appSpine (.const d.recursor) (ts.take (1 + d.ctors.length) ++ [t]))).map
        (cinterp (dataReading d) · ρ) =
      (ts.drop (1 + d.ctors.length)).map (cinterp (dataReading d) · ρ) ++
        (Ideal.recFields (fs.map fieldFlag)
          ((ts.drop (1 + d.ctors.length)).map (cinterp (dataReading d) · ρ))).map
          (fun α => Ideal.appSpine ((dataReading d).const d.recursor)
            ((ts.take (1 + d.ctors.length)).map (cinterp (dataReading d) · ρ) ++ [α])) := by
    rw [List.map_append, List.map_map, Ideal.recFields_map, List.map_map]
    congr 1
    apply List.map_congr_left
    intro t _
    simp only [Function.comp_apply, cinterp_appSpine, cinterp_const, List.map_append, List.map_take,
        List.map_cons, List.map_nil]
  have eH : (ts.map (cinterp (dataReading d) · ρ)).take (1 + d.ctors.length) =
      (ts.take (1 + d.ctors.length)).map (cinterp (dataReading d) · ρ) := by
    rw [List.map_take]
  rw [eL] at spine hτ
  rw [cinterp_const, eL, eR, eH]
  rw [eR, eH] at right
  have hpre : ((ts.take (1 + d.ctors.length)).map (cinterp (dataReading d) · ρ)).length =
      d.ctors.length + 1 := by
    simp only [List.map_take, List.length_take, List.length_map, htsl, Nat.le_add_right,
      Nat.min_eq_left]
    omega
  have hα : ((ts.drop (1 + d.ctors.length)).map (cinterp (dataReading d) · ρ)).length =
      fs.length := by simp only [List.map_drop, List.length_drop, List.length_map, htsl,
          Nat.add_sub_cancel_left]
  have spinePre : SpineTyped (recTypeI d)
      ((ts.take (1 + d.ctors.length)).map (cinterp (dataReading d) · ρ)) :=
    (Ideal.spineTyped_append.1 spine).1
  rw [recTypeI_prefix hpre spinePre, Ideal.dom_cpi, dataReading_type hd] at ctorFacts
  obtain ⟨⟨-, spineα⟩, -⟩ := SpineFacts.constSpine
    (sum_ctor_declared objectChurch hd.distinct hd.lamFree hd.new entry) ctorFacts
  rw [cinterp_ctorType hd (entry := (k, fs)) (List.mem_of_getElem? entry)] at spineα
  generalize (ts.take (1 + d.ctors.length)).map (cinterp (dataReading d) · ρ) = pre
    at spine hτ right hpre spinePre ⊢
  generalize (ts.drop (1 + d.ctors.length)).map (cinterp (dataReading d) · ρ) = αs
    at spine hτ right hα spineα ⊢
  have hlen : (pre ++ [Ideal.appSpine ((dataReading d).const k) αs]).length ≤
      piArity (liftTm (recType d.type d.motiveUniverse d.ctors)) :=
    le_trans (by simp only [List.length_append, hpre, List.length_cons, List.length_nil, zero_add,
        Std.le_refl])
      (piArity_closeType (recEntry d.type d.motiveUniverse d.ctors) (d.ctors.length + 2)
        (recBody d.ctors.length))
  conv_lhs => rw [dataReading_recursor_eq hd]
  rw [← hτ] at right
  exact Ideal.churchConst_root (churchTele_cinterp _ _ _) hlen spine
    (recursor_at_ctor hd entry hpre hα spinePre spineα) right

end Iota


/-! ## The reading is valid -/

section Valid

variable {d : Datatype Tower.Head} (hd : d.Admissible objectChurch)
include hd

/-- **The root steps of the package are valid in the reading**: the object package's by its
schemas, the recursor's by its computation at a constructor. -/
theorem dataReading_roots {n : Nat} {l r : CTm Tower.Head n} {τ : Ideal} {ρ : Env n}
    (step : (dataChurch d).computation.step l r)
    (facts : SpineFacts (dataReading d) (dataChurch d) l τ ρ)
    (right : projT τ (cinterp (dataReading d) r ρ) = cinterp (dataReading d) r ρ) :
    cinterp (dataReading d) l ρ = cinterp (dataReading d) r ρ := by
  rcases step with step | step
  · exact dataReading_objectRoot hd step facts right
  · cases step with
    | instantiate rule σ =>
      obtain ⟨L, R', hS, rfl, rfl⟩ := rule
      obtain ⟨i, k, fields, entry, e⟩ := hS
      cases e
      have eL := elabLeft_firstOrder (elabDeclarations (inductiveRules (rulesWith objectRules [])
        d.type d.typeUniverse d.ctors d.recursor d.motiveUniverse).constantType)
        (firstOrder_iotaLeft d.recursor k d.ctors.length fields.length)
      have eR : elabRight (elabDeclarations (inductiveRules (rulesWith objectRules []) d.type
          d.typeUniverse d.ctors d.recursor d.motiveUniverse).constantType)
          (iotaLeft d.recursor k d.ctors.length fields.length)
          (iotaRight d.recursor d.ctors.length i fields) =
          liftTm (iotaRight d.recursor d.ctors.length i fields) :=
        elab_lamFree _ (lamFree_iotaRight _ _ i fields) _ _ _
      rw [eL] at facts ⊢
      rw [eR] at right ⊢
      exact dataReading_iota hd entry σ facts right

/-- **The reading validates the object package with an admissible declared datatype.** -/
theorem dataReading_valid : ReadingValid (dataReading d) (dataChurch d) :=
  ReadingValid.ofLevels (levelsWith ConvRules.objectLevels [.datatype d])
    (fun hu => objectChurchReading_valid.universes hu)
    (fun h => by
      cases h with
      | sort _ => exact Elem.ty_univ_univ
      | legacyGround => exact Elem.ty_tag (k := .ground) trivial Elem.isUniv_univ)
    (fun same => objectChurchReading_valid.headEq same)
    (fun declared _ => dataReading_constants hd declared)
    (fun step _ _ facts right _ => dataReading_roots hd step facts right)

/-- **A valid reading of the object package with an admissible declared datatype**, agreeing
with the object reading on the heads and on every constant of the object package. -/
theorem objectChurch_data_reading :
    ∃ Rd : Reading Tower.Head, Rd.head = objectChurchReading.head ∧
      (∀ c, (objectChurch.constantType c).isSome → Rd.const c = objectChurchReading.const c) ∧
      ReadingValid Rd (withDeclarations objectChurch [.datatype d]) :=
  ⟨dataReading d, rfl, fun _ h => dataReading_object hd (Option.isSome_iff_ne_none.1 h),
    dataReading_valid hd⟩

end Valid


/-! ## The lists of numbers -/

section Lists

/-- The empty list's kind. -/
abbrev nilK : Kind := .ctor listN nilN []

/-- The kind of a number before a list. -/
abbrev consK : Kind := .ctor listN consN [.param 0, .self]

theorem dataParams_listDecl : dataParams listDecl = [natI] := by
  show [cinterp objectChurchReading (.const numN : CTm Tower.Head 0) Env.nil] = [natI]
  rw [cinterp_const, objectChurchReading_num]

/-- The lists of numbers are the declared datatype `list` at the numbers. -/
theorem dataTypeI_listDecl : dataTypeI listDecl = ctorI (Kind.data listN) [natI] := by
  rw [dataTypeI, dataParams_listDecl]
  rfl

/-- **Positive**: the length of the one-element list of the numeral one denotes one. -/
theorem lengthOf_one_value :
    cinterp (dataReading listDecl) (lengthOf (ccons (csuc czero) cnil)) Env.nil = succI zeroI := by
  rw [CEqual.sound (dataReading_valid listDecl_admissible)
    (lengthOf_one : CEqual (dataChurch listDecl) _ _ _ _) (ρ := Env.nil) trivial]
  change Ideal.app ((dataReading listDecl).const sucN) ((dataReading listDecl).const zeroN) = _
  rw [dataReading_object listDecl_admissible (c := sucN)
      (objectChurch_constantType_ne_none (by decide)),
    dataReading_object listDecl_admissible (c := zeroN)
      (objectChurch_constantType_ne_none (by decide)),
    objectChurchReading_suc, objectChurchReading_zero,
    app_sucConst objectChurchReading numNames objectChurchReading_num, Ideal.projT_natI_zeroI]

/-- **Recursion over the lists at the empty list is its value there**: the recursor at a motive
into the numbers, zero at the empty list, any step and the empty list denotes zero, the step
being read only through its projection. -/
theorem listRec_nil_zero (s : Ideal) :
    Ideal.appSpine ((dataReading listDecl).const listRecN)
      [clam (dataTypeI listDecl) (fun _ => natI), zeroI, s, ctorI nilK []] = zeroI := by
  have hπ : projT (cpi (dataTypeI listDecl) fun _ => univIdeal)
      (clam (dataTypeI listDecl) fun _ => natI) = clam (dataTypeI listDecl) fun _ => natI :=
    Ideal.semTyped_clam (Ideal.Cont.const _) (Ideal.Cont.const _) fun _ _ =>
      Ideal.projT_univ_eq_self_iff.2 Ideal.typeGenerated_natI
  have happ : ∀ y, Ideal.app (clam (dataTypeI listDecl) fun _ => natI) y = natI :=
    Ideal.app_clam (Ideal.Cont.const _)
  have hnilT : projT (dataTypeI listDecl) (ctorI nilK []) = ctorI nilK [] :=
    Ideal.projT_data_ctorI fun _ _ h => by simp only [List.length_nil, not_lt_zero,
        not_false_eq_true, getElem?_neg, reduceCtorEq] at h
  have hnil : (dataReading listDecl).const nilN = ctorI nilK [] := by
    rw [dataReading_ctor listDecl_admissible (i := 0) rfl]
    exact appSpine_ctorConstI_proj (d := listDecl) nilN [] (αs := []) rfl
  have hlen : [clam (dataTypeI listDecl) (fun _ => natI), zeroI, s, ctorI nilK []].length ≤
      piArity (liftTm (recType listDecl.type listDecl.motiveUniverse listDecl.ctors)) :=
    piArity_closeType (recEntry listDecl.type listDecl.motiveUniverse listDecl.ctors) 4
      (recBody 2)
  have hT : (dataReading listDecl).const listN = dataTypeI listDecl :=
    dataReading_type listDecl_admissible
  show Ideal.appSpine ((dataReading listDecl).const listDecl.recursor) _ = _
  rw [dataReading_recursor_eq listDecl_admissible, Ideal.appSpine_projT _ (churchTele_cinterp _ _ _)
    hlen]
  have pa := projArgs_cinterp_ofEntries (dataReading listDecl)
    (recEntry listDecl.type listDecl.motiveUniverse listDecl.ctors) 4 (recBody 2)
    [clam (dataTypeI listDecl) (fun _ => natI), zeroI, s, ctorI nilK []] rfl
  have inst := instPi_cinterp_ofEntries (dataReading listDecl)
    (recEntry listDecl.type listDecl.motiveUniverse listDecl.ctors) 4 (recBody 2)
    [clam (dataTypeI listDecl) (fun _ => natI), zeroI, s, ctorI nilK []] rfl
  have hRT : cinterp (dataReading listDecl) (liftTm (TelescopeAbstraction.closeType
      (ofEntries (recEntry listDecl.type listDecl.motiveUniverse listDecl.ctors) 4) (recBody 2)))
      Env.nil = recTypeI listDecl := rfl
  rw [hRT] at pa inst
  change projT (instPi (recTypeI listDecl) _) (Ideal.appSpine _ (projArgs (recTypeI listDecl) _)) =
    zeroI
  have hlenP : (projArgs (recTypeI listDecl)
      [clam (dataTypeI listDecl) (fun _ => natI), zeroI, s, ctorI nilK []]).length = 4 := by
    rw [length_projArgs]; rfl
  obtain ⟨x₀, x₁, x₂, x₃, hx⟩ : ∃ x₀ x₁ x₂ x₃, projArgs (recTypeI listDecl)
      [clam (dataTypeI listDecl) (fun _ => natI), zeroI, s, ctorI nilK []] = [x₀, x₁, x₂, x₃] := by
    generalize projArgs (recTypeI listDecl) _ = l at hlenP
    match l, hlenP with
    | [x₀, x₁, x₂, x₃], _ => exact ⟨x₀, x₁, x₂, x₃, rfl⟩
  rw [hx] at pa inst ⊢
  have p₀ := pa 0 (by decide)
  have p₁ := pa 1 (by decide)
  have p₃ := pa 3 (by decide)
  simp only [List.getElem?_cons_zero, List.getElem?_cons_succ, List.take_zero, List.take_succ_cons,
    List.getD_cons_zero, List.getD_cons_succ, Option.some.injEq] at p₀ p₁ p₃
  have hu : objectChurchReading.head listMotives = Elem.univ :=
    objectChurchReading_valid.universes (LevelTower.IsUniverse.sort _)
  have hx₀ : x₀ = clam (dataTypeI listDecl) fun _ => natI := by
    rw [p₀]
    show projT (cpi ((dataReading listDecl).const listN)
      fun _ => principal (objectChurchReading.head listMotives)) _ = _
    rw [hu, hT]
    exact hπ
  have hx₃ : x₃ = ctorI nilK [] := by
    rw [p₃]
    show projT ((dataReading listDecl).const listN) _ = _
    rw [hT]
    exact hnilT
  have hx₁ : x₁ = zeroI := by
    rw [p₁]
    show projT (Ideal.app (Env.ofArgs 1 [x₀] 0) ((dataReading listDecl).const nilN)) zeroI = _
    rw [show Env.ofArgs 1 [x₀] 0 = x₀ from rfl, hx₀, happ]
    exact Ideal.projT_natI_zeroI
  subst hx₀ hx₁ hx₃
  have hcs : (dataCs listDecl)[0]? = some (nilK, []) := rfl
  rw [appSpine_curryI (contEach_recH _) (listDecl.ctors.length + 2) [] _ rfl, List.reverse_nil,
    List.nil_append]
  show projT (instPi (recTypeI listDecl) _) (recI (dataCs listDecl)
    (methodsAt _ (dataCs listDecl) [zeroI, x₂, ctorI nilK []]) (ctorI nilK [])) = zeroI
  rw [Ideal.recI_ctorI (contList_methodsAt _ _ _) (List.mem_of_getElem? hcs)
      (dataCs_nodup listDecl listDecl_admissible.distinct.ctorsNodup) (xs := []) rfl,
    methodsAt_getElem _ _ (dataCs_nodup listDecl listDecl_admissible.distinct.ctorsNodup) hcs, inst]
  show projT (Ideal.app (clam (dataTypeI listDecl) fun _ => natI) (ctorI nilK []))
    (caseValue _ zeroI [] []) = zeroI
  rw [happ]
  exact Ideal.projT_natI_zeroI

/-- `cons` read as the constant function to the empty list, projected onto its declared type. -/
def badConsConst : Ideal :=
  projT (arrowsI [natI, dataTypeI listDecl] (dataTypeI listDecl))
    (Ideal.lam fun _ => Ideal.lam fun _ => ctorI nilK [])

/-- The reading with that `cons`. -/
def badConsReading : Reading Tower.Head where
  head := objectChurchReading.head
  const c := if c = consN then badConsConst else (dataReading listDecl).const c

theorem badConsReading_of_ne {c : DeclName} (h : c ≠ consN) :
    badConsReading.const c = (dataReading listDecl).const c :=
  if_neg h

/-- That `cons` is an element of its declared type, and sends every number and list to the
empty list. -/
theorem app_badCons (a l : Ideal) : Ideal.app (Ideal.app badConsConst a) l = ctorI nilK [] := by
  unfold badConsConst
  simp only [arrowsI]
  rw [Ideal.app_projT_cpi (Ideal.Cont.const _), Ideal.app_projT_cpi (Ideal.Cont.const _),
    Ideal.app_lam_const, Ideal.app_lam_const]
  exact Ideal.projT_data_ctorI fun _ _ h => by simp only [List.length_nil, not_lt_zero,
      not_false_eq_true, getElem?_neg, reduceCtorEq] at h

theorem badCons_typed :
    projT (arrowsI [natI, dataTypeI listDecl] (dataTypeI listDecl)) badConsConst = badConsConst :=
  Ideal.projT_projT _ _

/-- **Negative: reading `cons` as the constant function to the empty list is not valid.** The
length of the one-element list of one is then the length of the empty list, zero, while the
recursor's rule at `cons` makes it one. -/
theorem badCons_not_valid : ¬ ReadingValid badConsReading (dataChurch listDecl) := by
  intro valid
  have e := CEqual.sound valid (lengthOf_one : CEqual (dataChurch listDecl) _ _ _ _)
    (ρ := Env.nil) trivial
  have hlist : badConsReading.const listN = dataTypeI listDecl := by
    rw [badConsReading_of_ne (by decide)]
    exact dataReading_type listDecl_admissible
  have hnum : badConsReading.const numN = natI := by
    rw [badConsReading_of_ne (by decide), dataReading_object listDecl_admissible
      (objectChurch_constantType_ne_none (c := numN) (by decide)), objectChurchReading_num]
  have hzero : badConsReading.const zeroN = zeroI := by
    rw [badConsReading_of_ne (by decide), dataReading_object listDecl_admissible
      (objectChurch_constantType_ne_none (c := zeroN) (by decide)), objectChurchReading_zero]
  have hsuc : badConsReading.const sucN = sucConst objectChurchReading numNames := by
    rw [badConsReading_of_ne (by decide), dataReading_object listDecl_admissible
      (objectChurch_constantType_ne_none (c := sucN) (by decide)), objectChurchReading_suc]
  change Ideal.app (Ideal.app (Ideal.app (Ideal.app (badConsReading.const listRecN)
      (clam (badConsReading.const listN) fun _ => badConsReading.const numN))
      (badConsReading.const zeroN)) (cinterp badConsReading lenStep Env.nil))
      (Ideal.app (Ideal.app (badConsReading.const consN)
        (Ideal.app (badConsReading.const sucN) (badConsReading.const zeroN)))
        (badConsReading.const nilN)) =
    Ideal.app (badConsReading.const sucN) (badConsReading.const zeroN) at e
  have hcons : badConsReading.const consN = badConsConst := by
    simp only [badConsReading, if_true]
  rw [hcons, app_badCons, hlist, hnum, hzero, hsuc,
    app_sucConst objectChurchReading numNames objectChurchReading_num,
    Ideal.projT_natI_zeroI, badConsReading_of_ne (by decide)] at e
  have h := listRec_nil_zero (cinterp badConsReading lenStep Env.nil)
  change Ideal.app (Ideal.app (Ideal.app (Ideal.app ((dataReading listDecl).const listRecN) _) _) _)
    _ = _ at h
  rw [h] at e
  exact Ideal.succI_not_mem_tag (by decide) zeroI (e ▸ Ideal.zeroI_mem_zero)

end Lists

end CodeModel

end Mettapedia.Languages.MeTTa.PrimeCandidates.DeclarationBased.CertifiedTransformProgram.ExecutableModel
