import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.FormationSensitiveMIL
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.FormationSensitiveMILArgumentRecovery
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.FormationSensitiveMILElimination
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.FormationSensitiveMILEliminationIota
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.FormationSensitiveMILIotaPreservation
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.FormationSensitiveMILQualification
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.IntrinsicMILHypothesis
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.IntrinsicMILSemanticAdequacy
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.MILCheckedChain
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.MILCheckedNativeListOpenSearchTrinity
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.MILCheckedNativeListPrograms
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.MILCheckedNativePrograms
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.MILConversionCompletion
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.MILConversionDevelopment
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.MILConversionDevelopmentChain
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.MILConversionDevelopmentComplete
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.MILConversionParallel
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.MILConversionParallelCoherence
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.MILConversionParallelSpine
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.MILConversionParallelSubstitution
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.MILLearnedProofRelevantAdmission
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.MILRootConversionCode
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.MILSchemaElaboration
import Mettapedia.Logic.MetaInterpretiveLearning.CumulativeTheory.NativeRelationLifting

/-! Typed meta-interpretive hypotheses and their cumulative dependent interpretation. -/
