import Mettapedia.TypeTheory.CategoryIndexedFamilyGeneralPi
import Mettapedia.TypeTheory.CategoryIndexedFamilyTypeFormers
import Mettapedia.TypeTheory.PresheafElementSubstitutionLifting

/-!
# Directed variance boundary for general indexed-family products

Right Kan extension yields a semantic dependent product for every small
category-indexed family. Its value at a context can depend on future arrows
and arguments not generated by the current fibre. The directed-edge control
below exposes that dependence; an adjoint product is not automatically a
substitution-stable product former for an authored dependent type theory.
-/

set_option autoImplicit false

namespace Mettapedia.TypeTheory.CategoryIndexedFamilyGeneralPiBoundary

open CategoryTheory
open Mettapedia.TypeTheory.CategoryIndexedFamilyCwf
open Mettapedia.TypeTheory.CategoryIndexedFamilyGeneralPi
open Mettapedia.TypeTheory.CategoryIndexedFamilyTypeFormers.Canary
open Mettapedia.TypeTheory.PresheafElementSubstitutionLifting

/-- At the source of the directed edge, the general Π cannot be inhabited:
any value transports forward and would have to answer at the missing target
argument, where the representable codomain has no value. -/
theorem generalPi_source_empty :
    IsEmpty ((generalPiFamily directedVaryingDomain
      missingPreimageCodomain).obj DirectedPoint.source) := by
  refine ⟨fun function => ?_⟩
  let forwardFunction :=
    (generalPiFamily directedVaryingDomain missingPreimageCodomain).map
      DirectedHom.forward function
  have missingAnswer : missingPreimageCodomain.obj missingElement :=
    (generalPiEvaluation directedVaryingDomain missingPreimageCodomain).app
      missingElement forwardFunction
  exact noHom_source_to_missing missingAnswer

/-- Restrict the walking directed edge to its source context. -/
def sourceOnlyContext : Context.{0} :=
  Cat.of (Discrete PUnit)

/-- The source-only inclusion removes the future target context, while
retaining the source's sole argument. -/
def sourceOnlyInclusion : ContextHom sourceOnlyContext directedContext where
  obj _ := DirectedPoint.source
  map _ := DirectedHom.stay .source
  map_id _ := rfl
  map_comp _ _ := rfl

/-- Unlike a category-of-elements map induced by a natural substitution,
the source-only inclusion has no endpoint above the directed target. Thus
the forward arrow in the product counterexample cannot lift through it. -/
theorem sourceOnlyInclusion_no_forward_target :
    ¬ ∃ endpoint : sourceOnlyContext,
      sourceOnlyInclusion.obj endpoint = DirectedPoint.target := by
  rintro ⟨endpoint, same⟩
  cases endpoint with
  | mk value =>
      cases value
      exact DirectedPoint.noConfusion same

/-- The Pi counterexample changes indexing categories along a functor
outside the arrow-lifting class enjoyed by presheaf context substitutions.
This distinction does not itself prove Beck-Chevalley for the latter. -/
theorem sourceOnlyInclusion_not_outgoingLifts :
    ¬ OutgoingLiftProperty sourceOnlyInclusion := by
  intro lifts
  rcases lifts (Discrete.mk PUnit.unit) DirectedHom.forward with
    ⟨endpoint, _liftedArrow, sameEndpoint, _sameArrow⟩
  exact sourceOnlyInclusion_no_forward_target ⟨endpoint, sameEndpoint⟩

private def restrictedDomain : IndexedFamily sourceOnlyContext :=
  reindexFamily directedVaryingDomain sourceOnlyInclusion

private def restrictedCodomain :
    IndexedFamily (extend sourceOnlyContext restrictedDomain) :=
  reindexFamily missingPreimageCodomain
    (CategoryIndexedFamilyTypeFormers.liftIndexedSubstitution
      sourceOnlyInclusion directedVaryingDomain)

/-- Every local argument has the identity proof in the restricted
codomain. There is no missing future argument in this context. -/
def sourceOnlyBody :
    reindexFamily (unitFamily sourceOnlyContext)
        (weaken restrictedDomain) ⟶ restrictedCodomain where
  app point := TypeCat.ofHom fun _ => by
    cases point with
    | mk context argument =>
        cases context
        cases argument
        exact 𝟙 sourceElement
  naturality := by
    intro first second arrow
    apply ConcreteCategory.hom_ext
    intro _
    cases first with
    | mk firstContext firstArgument =>
        cases second with
        | mk secondContext secondArgument =>
            cases firstContext
            cases secondContext
            cases firstArgument
            cases secondArgument
            rfl

/-- The source-only product has an actual inhabitant obtained by currying
the retained identity proof. -/
noncomputable def sourceOnlyPiInhabitant :
    (generalPiFamily restrictedDomain restrictedCodomain).obj
      (Discrete.mk PUnit.unit) :=
  (generalPiTranspose restrictedDomain sourceOnlyBody).app
    (Discrete.mk PUnit.unit) PUnit.unit

/-- The product formed before restricting the context has an empty source
fibre, whereas the product formed after restriction has an inhabitant.
Thus no fibrewise equivalence can be the unrestricted Beck-Chevalley map. -/
theorem generalPi_baseChange_no_pointwise_equivalence :
    ¬ Nonempty
      (((reindexFamily
          (generalPiFamily directedVaryingDomain missingPreimageCodomain)
          sourceOnlyInclusion).obj (Discrete.mk PUnit.unit)) ≃
        (generalPiFamily restrictedDomain restrictedCodomain).obj
          (Discrete.mk PUnit.unit)) := by
  rintro ⟨equivalence⟩
  exact generalPi_source_empty.false
    (equivalence.symm sourceOnlyPiInhabitant)

/-- In particular, unrestricted substitution cannot identify the two
dependent-product families even by equality of indexed functors. -/
theorem generalPi_baseChange_ne :
    reindexFamily
        (generalPiFamily directedVaryingDomain missingPreimageCodomain)
        sourceOnlyInclusion ≠
      generalPiFamily restrictedDomain restrictedCodomain := by
  intro equal
  have fibreEqual := congrArg
    (fun family : IndexedFamily sourceOnlyContext =>
      family.obj (Discrete.mk PUnit.unit)) equal
  exact generalPi_source_empty.false
    (fibreEqual.symm ▸ sourceOnlyPiInhabitant)

#print axioms generalPi_source_empty
#print axioms sourceOnlyInclusion_no_forward_target
#print axioms sourceOnlyInclusion_not_outgoingLifts
#print axioms sourceOnlyBody
#print axioms sourceOnlyPiInhabitant
#print axioms generalPi_baseChange_no_pointwise_equivalence
#print axioms generalPi_baseChange_ne

end Mettapedia.TypeTheory.CategoryIndexedFamilyGeneralPiBoundary
