import Mettapedia.GSLT.Core.ContextualLadderTerminal
import Mettapedia.Logic.Institution
import Mathlib.CategoryTheory.Discrete.Basic

/-!
# The global-inhabitation institution of a category with families

A category with families and a chosen terminal context determines a small
institution without identifying types with propositions.  A signature is a
context, read contravariantly; a sentence is a type over that context; and a
model is a global substitution from the empty context.  A type is satisfied
at a global substitution exactly when its reindexing has a term.

The institution satisfaction law is precisely substitution composition for
types.  This construction exposes the logical face already present in every
such CwF and gives comparisons of simple and dependent CwFs a common semantic
target.
-/

set_option autoImplicit false

namespace Mettapedia.TypeTheory.CwfInhabitationInstitution

open CategoryTheory
open scoped CategoryTheory
open Mettapedia.Logic
open Mettapedia.GSLT.Core.ContextualLadder

universe u v w w'

/-- Contexts, with arrows reversed so type substitution translates sentences
covariantly. -/
abbrev Signature (C : CwfWithTerminal.{u, v, w, w'}) :=
  C.toCwf.base.Contextᵒᵖ

/-- Types over contexts form the sentence functor. -/
@[reducible] def typeSentence (C : CwfWithTerminal.{u, v, w, w'}) :
    Signature C ⥤ Type w where
  obj context := C.toCwf.Ty context.unop.val
  map := fun {source _target} substitution =>
    TypeCat.ofHom fun type : C.toCwf.Ty source.unop.val =>
      C.toCwf.tySub type substitution.unop
  map_id context := by
    apply TypeCat.Hom.ext
    apply TypeCat.Fun.ext
    funext type
    exact C.toCwf.tySub_id type
  map_comp first second := by
    apply TypeCat.Hom.ext
    apply TypeCat.Fun.ext
    funext type
    exact C.toCwf.tySub_comp type first.unop second.unop

/-- A model of a context is a global substitution into it.  The category is
discrete: the bare CwF interface supplies substitutions, not transformations
between global substitutions. -/
@[reducible] def globalModel (C : CwfWithTerminal.{u, v, w, w'}) :
    (Signature C)ᵒᵖ ⥤ Cat.{v, v} where
  obj context := Cat.of
    (Discrete (C.toCwf.Sub C.empty context.unop.unop.val))
  map := fun {source target} substitution =>
    (Discrete.functor fun global :
        C.toCwf.Sub C.empty source.unop.unop.val =>
      Discrete.mk
        (C.toCwf.compS substitution.unop.unop global)).toCatHom
  map_id context := by
    apply Cat.Hom.ext
    apply Discrete.functor_ext
    intro global
    apply Discrete.ext
    exact C.toCwf.id_comp global
  map_comp first second := by
    apply Cat.Hom.ext
    apply Discrete.functor_ext
    intro global
    apply Discrete.ext
    exact C.toCwf.comp_assoc second.unop.unop first.unop.unop global

/-- A type is satisfied by a global point when its fibre at that point is
inhabited by a term. -/
def satisfies (C : CwfWithTerminal.{u, v, w, w'})
    (context : Signature C)
    (global : Discrete (C.toCwf.Sub C.empty context.unop.val))
    (type : C.toCwf.Ty context.unop.val) : Prop :=
  Nonempty
    (C.toCwf.Tm C.empty (C.toCwf.tySub type global.as))

/-- The global-inhabitation institution generated by a CwF with terminal
context. -/
def ofCwf (C : CwfWithTerminal.{u, v, w, w'}) :
    Institution.{u, v, w, v, v} (Signature C) where
  sentence := typeSentence C
  model := globalModel C
  satisfies := satisfies C
  satisfaction_condition := by
    intro source target substitution targetModel sourceType
    change Nonempty
        (C.toCwf.Tm C.empty
          (C.toCwf.tySub
            (C.toCwf.tySub sourceType substitution.unop)
            targetModel.as)) ↔
      Nonempty
        (C.toCwf.Tm C.empty
          (C.toCwf.tySub sourceType
            (C.toCwf.compS substitution.unop targetModel.as)))
    rw [C.toCwf.tySub_comp]

/-- Satisfaction unfolds to fibrewise inhabitation at a global point. -/
theorem satisfies_iff
    (C : CwfWithTerminal.{u, v, w, w'})
    (context : Signature C)
    (global : Discrete (C.toCwf.Sub C.empty context.unop.val))
    (type : C.toCwf.Ty context.unop.val) :
    (ofCwf C).satisfies context global type ↔
      Nonempty
        (C.toCwf.Tm C.empty (C.toCwf.tySub type global.as)) :=
  Iff.rfl

/-- Positive control: an explicitly given term at a global point witnesses
satisfaction. -/
theorem satisfies_of_term
    (C : CwfWithTerminal.{u, v, w, w'})
    (context : Signature C)
    (global : Discrete (C.toCwf.Sub C.empty context.unop.val))
    (type : C.toCwf.Ty context.unop.val)
    (term : C.toCwf.Tm C.empty (C.toCwf.tySub type global.as)) :
    (ofCwf C).satisfies context global type :=
  ⟨term⟩

/-! ## The proof-relevance boundary of inhabitation -/

/-- The native witness fibre observed by proposition-valued satisfaction. -/
abbrev Witness
    (C : CwfWithTerminal.{u, v, w, w'})
    (context : Signature C)
    (global : Discrete (C.toCwf.Sub C.empty context.unop.val))
    (type : C.toCwf.Ty context.unop.val) :=
  C.toCwf.Tm C.empty (C.toCwf.tySub type global.as)

/-- Forget a native term to the proposition that its fibre is inhabited. -/
def witnessSupport
    (C : CwfWithTerminal.{u, v, w, w'})
    (context : Signature C)
    (global : Discrete (C.toCwf.Sub C.empty context.unop.val))
    (type : C.toCwf.Ty context.unop.val) :
    Witness C context global type →
      (ofCwf C).satisfies context global type :=
  fun term => ⟨term⟩

/-- Proposition-valued inhabitation retains exact witness identity precisely
when the native term fibre is a subsingleton. -/
theorem witnessSupport_injective_iff_subsingleton
    (C : CwfWithTerminal.{u, v, w, w'})
    (context : Signature C)
    (global : Discrete (C.toCwf.Sub C.empty context.unop.val))
    (type : C.toCwf.Ty context.unop.val) :
    Function.Injective (witnessSupport C context global type) ↔
      Subsingleton (Witness C context global type) := by
  constructor
  · intro injective
    constructor
    intro left right
    apply injective
    exact Subsingleton.elim _ _
  · intro thin left right _sameSupport
    exact thin.allEq left right

#print axioms typeSentence
#print axioms globalModel
#print axioms ofCwf
#print axioms satisfies_iff
#print axioms satisfies_of_term
#print axioms witnessSupport
#print axioms witnessSupport_injective_iff_subsingleton

end Mettapedia.TypeTheory.CwfInhabitationInstitution
