import Mettapedia.TypeTheory.JudgmentalEquality

/-!
# The free proof-relevant syntax of judgmental conversion

`ConversionEvidence` retains reflexivity, symmetry, transitivity, every
intermediate typed state, and the complete binary composition tree.  It is not
yet a category or groupoid quotient: association, cancellation, and unit laws
may remain observable until explicit higher cells identify them.

This file proves the precise universal property available before making any
such coherence choice.  Given interpretations of primitive steps,
reflexivity, symmetry, and transitivity in an arbitrary indexed target family,
there is a unique structural fold from conversion evidence.  Exact
equivalences of primitive step fibres consequently lift to exact equivalences
of complete conversion trees.

The result is deliberately more intensional than the free directed-path
category used for ordinary GSLT execution.  It supplies the safe common theorem
under both constructions without silently quotienting proof histories.
-/

set_option autoImplicit false

namespace Mettapedia.TypeTheory
namespace FreeConversion

open JudgmentalEquality

universe uIndex uState uStep uTargetStep uTarget

variable {Index : Type uIndex}

/-! ## A computation generated by an indexed step family -/

/-- Package one indexed state family and one proof-relevant step family as a
judgmental computation. -/
@[reducible] def computation
    (State : Index → Type uState)
    (Step : {index : Index} → State index → State index → Type uStep) :
    JudgmentalComputation Index where
  State := State
  Step := fun {index} source target =>
    Step (index := index) source target

/-- Reflexive, symmetric, transitive conversion trees freely generated by one
indexed step family. -/
abbrev Path
    (State : Index → Type uState)
    (Step : {index : Index} → State index → State index → Type uStep)
    {index : Index} (source target : State index) :=
  ConversionEvidence (computation State Step) source target

/-! ## The initial conversion algebra -/

/-- An interpretation of all four conversion constructors in an arbitrary
indexed target family.  No associativity, unit, cancellation, or involution
law is required of the target. -/
structure Algebra
    (State : Index → Type uState)
    (Step : {index : Index} → State index → State index → Type uStep)
    (Target : {index : Index} → State index → State index →
      Type uTarget) where
  onStep : ∀ {index : Index} {source target : State index},
    Step source target → Target source target
  onRefl : ∀ {index : Index} (state : State index), Target state state
  onSymm : ∀ {index : Index} {source target : State index},
    Target source target → Target target source
  onTrans : ∀ {index : Index} {source middle target : State index},
    Target source middle → Target middle target → Target source target

namespace Algebra

/-- Structural recursion is the canonical interpretation of conversion
trees. -/
def fold
    {State : Index → Type uState}
    {Step : {index : Index} → State index → State index → Type uStep}
    {Target : {index : Index} → State index → State index → Type uTarget}
    (algebra : Algebra State Step Target) :
    {index : Index} → {source target : State index} →
      Path State Step source target → Target source target
  | _, _, _, .step evidence => algebra.onStep evidence
  | _, _, _, .refl state => algebra.onRefl state
  | _, _, _, .symm path => algebra.onSymm (fold algebra path)
  | _, _, _, .trans first second =>
      algebra.onTrans (fold algebra first) (fold algebra second)

@[simp] theorem fold_step
    {State : Index → Type uState}
    {Step : {index : Index} → State index → State index → Type uStep}
    {Target : {index : Index} → State index → State index → Type uTarget}
    (algebra : Algebra State Step Target)
    {index : Index} {source target : State index}
    (evidence : Step source target) :
    algebra.fold (.step evidence) = algebra.onStep evidence :=
  by simp [fold]

@[simp] theorem fold_refl
    {State : Index → Type uState}
    {Step : {index : Index} → State index → State index → Type uStep}
    {Target : {index : Index} → State index → State index → Type uTarget}
    (algebra : Algebra State Step Target)
    {index : Index} (state : State index) :
    algebra.fold
        (ConversionEvidence.refl
          (computation := computation State Step) state) =
      algebra.onRefl state :=
  by simp [fold]

@[simp] theorem fold_symm
    {State : Index → Type uState}
    {Step : {index : Index} → State index → State index → Type uStep}
    {Target : {index : Index} → State index → State index → Type uTarget}
    (algebra : Algebra State Step Target)
    {index : Index} {source target : State index}
    (path : Path State Step source target) :
    algebra.fold (.symm path) = algebra.onSymm (algebra.fold path) :=
  by simp [fold]

@[simp] theorem fold_trans
    {State : Index → Type uState}
    {Step : {index : Index} → State index → State index → Type uStep}
    {Target : {index : Index} → State index → State index → Type uTarget}
    (algebra : Algebra State Step Target)
    {index : Index} {source middle target : State index}
    (first : Path State Step source middle)
    (second : Path State Step middle target) :
    algebra.fold (.trans first second) =
      algebra.onTrans (algebra.fold first) (algebra.fold second) :=
  by simp [fold]

end Algebra

/-! ## Existence and uniqueness of structural extensions -/

/-- A complete structural interpretation agreeing with one conversion
algebra on every constructor. -/
structure Extension
    {State : Index → Type uState}
    {Step : {index : Index} → State index → State index → Type uStep}
    {Target : {index : Index} → State index → State index → Type uTarget}
    (algebra : Algebra State Step Target) where
  onPath : {index : Index} → {source target : State index} →
    Path State Step source target → Target source target
  onStep : ∀ {index : Index} {source target : State index}
    (evidence : Step source target),
    onPath (.step evidence) = algebra.onStep evidence
  onRefl : ∀ {index : Index} (state : State index),
    onPath (ConversionEvidence.refl
      (computation := computation State Step) state) = algebra.onRefl state
  onSymm : ∀ {index : Index} {source target : State index}
    (path : Path State Step source target),
    onPath (.symm path) = algebra.onSymm (onPath path)
  onTrans : ∀ {index : Index} {source middle target : State index}
    (first : Path State Step source middle)
    (second : Path State Step middle target),
    onPath (.trans first second) =
      algebra.onTrans (onPath first) (onPath second)

namespace Extension

/-- Structural recursion supplies an extension of every conversion algebra. -/
def canonical
    {State : Index → Type uState}
    {Step : {index : Index} → State index → State index → Type uStep}
    {Target : {index : Index} → State index → State index → Type uTarget}
    (algebra : Algebra State Step Target) : Extension algebra where
  onPath := algebra.fold
  onStep := Algebra.fold_step algebra
  onRefl := Algebra.fold_refl algebra
  onSymm := Algebra.fold_symm algebra
  onTrans := Algebra.fold_trans algebra

/-- Any constructor-preserving interpretation is pointwise the structural
fold. -/
theorem onPath_unique
    {State : Index → Type uState}
    {Step : {index : Index} → State index → State index → Type uStep}
    {Target : {index : Index} → State index → State index → Type uTarget}
    {algebra : Algebra State Step Target}
    (extension : Extension algebra) :
    ∀ {index : Index} {source target : State index}
      (path : Path State Step source target),
      extension.onPath path = algebra.fold path
  | _, _, _, .step evidence => by
      simpa [Algebra.fold] using extension.onStep evidence
  | _, _, _, .refl state => by
      simpa [Algebra.fold] using extension.onRefl state
  | _, _, _, .symm path => by
      rw [extension.onSymm path, Algebra.fold_symm,
        onPath_unique extension path]
  | _, _, _, .trans first second => by
      rw [extension.onTrans first second, Algebra.fold_trans,
        onPath_unique extension first, onPath_unique extension second]

@[ext] theorem ext
    {State : Index → Type uState}
    {Step : {index : Index} → State index → State index → Type uStep}
    {Target : {index : Index} → State index → State index → Type uTarget}
    {algebra : Algebra State Step Target}
    {first second : Extension algebra}
    (paths : ∀ {index : Index} {source target : State index}
      (path : Path State Step source target),
      first.onPath path = second.onPath path) :
    first = second := by
  cases first with
  | mk firstPath firstStep firstRefl firstSymm firstTrans =>
      cases second with
      | mk secondPath secondStep secondRefl secondSymm secondTrans =>
          have pathEqual : @firstPath = @secondPath := by
            funext index source target path
            exact paths path
          cases pathEqual
          rfl

/-- The structural fold is the unique extension of the supplied conversion
algebra. -/
theorem unique
    {State : Index → Type uState}
    {Step : {index : Index} → State index → State index → Type uStep}
    {Target : {index : Index} → State index → State index → Type uTarget}
    (algebra : Algebra State Step Target)
    (extension : Extension algebra) :
    extension = canonical algebra := by
  apply Extension.ext
  intro index source target path
  exact extension.onPath_unique path

/-- Structural extensions form a contractible type. -/
instance
    {State : Index → Type uState}
    {Step : {index : Index} → State index → State index → Type uStep}
    {Target : {index : Index} → State index → State index → Type uTarget}
    (algebra : Algebra State Step Target) : Unique (Extension algebra) where
  default := canonical algebra
  uniq extension := unique algebra extension

theorem contractible
    {State : Index → Type uState}
    {Step : {index : Index} → State index → State index → Type uStep}
    {Target : {index : Index} → State index → State index → Type uTarget}
    (algebra : Algebra State Step Target) :
    Nonempty (Extension algebra) ∧ Subsingleton (Extension algebra) :=
  ⟨⟨canonical algebra⟩, inferInstance⟩

end Extension

/-! ## Mapping and exact step-fibre equivalence -/

/-- The conversion algebra generated by a map of primitive step fibres. -/
def pathAlgebra
    {State : Index → Type uState}
    {SourceStep :
      {index : Index} → State index → State index → Type uStep}
    {TargetStep :
      {index : Index} → State index → State index → Type uTargetStep}
    (onStep : ∀ {index : Index} {source target : State index},
      SourceStep source target → TargetStep source target) :
    Algebra State SourceStep
      (fun {_} source target => Path State TargetStep source target) where
  onStep := fun evidence =>
    ConversionEvidence.step
      (computation := computation State TargetStep) (onStep evidence)
  onRefl := fun state =>
    ConversionEvidence.refl
      (computation := computation State TargetStep) state
  onSymm := fun path =>
    ConversionEvidence.symm path
  onTrans := fun first second =>
    ConversionEvidence.trans first second

/-- Map primitive step evidence while preserving the complete conversion
constructor tree. -/
def mapSteps
    {State : Index → Type uState}
    {SourceStep :
      {index : Index} → State index → State index → Type uStep}
    {TargetStep :
      {index : Index} → State index → State index → Type uTargetStep}
    (onStep : ∀ {index : Index} {source target : State index},
      SourceStep source target → TargetStep source target)
    {index : Index} {source target : State index} :
    Path State SourceStep source target → Path State TargetStep source target :=
  (pathAlgebra onStep).fold

@[simp] theorem mapSteps_step
    {State : Index → Type uState}
    {SourceStep :
      {index : Index} → State index → State index → Type uStep}
    {TargetStep :
      {index : Index} → State index → State index → Type uTargetStep}
    (onStep : ∀ {index : Index} {source target : State index},
      SourceStep source target → TargetStep source target)
    {index : Index} {source target : State index}
    (evidence : SourceStep source target) :
    mapSteps (State := State) (SourceStep := SourceStep)
        (TargetStep := TargetStep) onStep (.step evidence) =
      @ConversionEvidence.step Index (computation State TargetStep)
        index source target (onStep evidence) :=
  by simp [mapSteps, pathAlgebra]

@[simp] theorem mapSteps_refl
    {State : Index → Type uState}
    {SourceStep :
      {index : Index} → State index → State index → Type uStep}
    {TargetStep :
      {index : Index} → State index → State index → Type uTargetStep}
    (onStep : ∀ {index : Index} {source target : State index},
      SourceStep source target → TargetStep source target)
    {index : Index} (state : State index) :
    mapSteps (State := State) (SourceStep := SourceStep)
        (TargetStep := TargetStep) onStep
        (ConversionEvidence.refl
          (computation := computation State SourceStep) state) =
      ConversionEvidence.refl
        (computation := computation State TargetStep) state :=
  by simp [mapSteps, pathAlgebra]

@[simp] theorem mapSteps_symm
    {State : Index → Type uState}
    {SourceStep :
      {index : Index} → State index → State index → Type uStep}
    {TargetStep :
      {index : Index} → State index → State index → Type uTargetStep}
    (onStep : ∀ {index : Index} {source target : State index},
      SourceStep source target → TargetStep source target)
    {index : Index} {source target : State index}
    (path : Path State SourceStep source target) :
    mapSteps (State := State) (SourceStep := SourceStep)
        (TargetStep := TargetStep) onStep (.symm path) =
      ConversionEvidence.symm
        (mapSteps (State := State) (SourceStep := SourceStep)
          (TargetStep := TargetStep) onStep path) :=
  by simp [mapSteps, pathAlgebra]

@[simp] theorem mapSteps_trans
    {State : Index → Type uState}
    {SourceStep :
      {index : Index} → State index → State index → Type uStep}
    {TargetStep :
      {index : Index} → State index → State index → Type uTargetStep}
    (onStep : ∀ {index : Index} {source target : State index},
      SourceStep source target → TargetStep source target)
    {index : Index} {source middle target : State index}
    (first : Path State SourceStep source middle)
    (second : Path State SourceStep middle target) :
    mapSteps (State := State) (SourceStep := SourceStep)
        (TargetStep := TargetStep) onStep (.trans first second) =
      ConversionEvidence.trans
        (mapSteps (State := State) (SourceStep := SourceStep)
          (TargetStep := TargetStep) onStep first)
        (mapSteps (State := State) (SourceStep := SourceStep)
          (TargetStep := TargetStep) onStep second) :=
  by simp [mapSteps, pathAlgebra]

/-- Mapping primitive steps twice is exactly mapping their composite once. -/
theorem mapSteps_comp
    {State : Index → Type uState}
    {FirstStep :
      {index : Index} → State index → State index → Type uStep}
    {MiddleStep :
      {index : Index} → State index → State index → Type uTargetStep}
    {LastStep :
      {index : Index} → State index → State index → Type uTarget}
    (firstMap : ∀ {index : Index} {source target : State index},
      FirstStep source target → MiddleStep source target)
    (secondMap : ∀ {index : Index} {source target : State index},
      MiddleStep source target → LastStep source target) :
    ∀ {index : Index} {source target : State index}
      (path : Path State FirstStep source target),
      mapSteps (State := State) (SourceStep := MiddleStep)
          (TargetStep := LastStep) secondMap
          (mapSteps (State := State) (SourceStep := FirstStep)
            (TargetStep := MiddleStep) firstMap path) =
        mapSteps (State := State) (SourceStep := FirstStep)
          (TargetStep := LastStep)
          (fun evidence => secondMap (firstMap evidence)) path
  | _, _, _, .step evidence => by simp
  | _, _, _, .refl state => by simp
  | _, _, _, .symm path => by
      simp [mapSteps_comp firstMap secondMap path]
  | _, _, _, .trans first second => by
      simp [mapSteps_comp firstMap secondMap first,
        mapSteps_comp firstMap secondMap second]

/-- Pointwise inverse step maps remain inverse after structural path lifting. -/
theorem mapSteps_inverse
    {State : Index → Type uState}
    {SourceStep :
      {index : Index} → State index → State index → Type uStep}
    {TargetStep :
      {index : Index} → State index → State index → Type uTargetStep}
    (forward : ∀ {index : Index} {source target : State index},
      SourceStep source target → TargetStep source target)
    (backward : ∀ {index : Index} {source target : State index},
      TargetStep source target → SourceStep source target)
    (inverse : ∀ {index : Index} {source target : State index}
      (evidence : SourceStep source target),
      backward (forward evidence) = evidence) :
    ∀ {index : Index} {source target : State index}
      (path : Path State SourceStep source target),
      mapSteps (State := State) (SourceStep := TargetStep)
          (TargetStep := SourceStep) backward
          (mapSteps (State := State) (SourceStep := SourceStep)
            (TargetStep := TargetStep) forward path) = path
  | _, _, _, .step evidence => by simp [inverse evidence]
  | _, _, _, .refl state => by simp
  | _, _, _, .symm path => by
      simp [mapSteps_inverse forward backward inverse path]
  | _, _, _, .trans first second => by
      simp [mapSteps_inverse forward backward inverse first,
        mapSteps_inverse forward backward inverse second]

/-- Exact equivalence of every primitive step fibre lifts to exact equivalence
of complete proof-relevant conversion trees. -/
def pathEquivOfStepEquiv
    {State : Index → Type uState}
    {SourceStep :
      {index : Index} → State index → State index → Type uStep}
    {TargetStep :
      {index : Index} → State index → State index → Type uTargetStep}
    (stepEquiv : ∀ {index : Index} (source target : State index),
      SourceStep source target ≃ TargetStep source target)
    {index : Index} (source target : State index) :
    Path State SourceStep source target ≃ Path State TargetStep source target where
  toFun := mapSteps
    (fun {index : Index} {source target : State index}
      (evidence : SourceStep source target) =>
      stepEquiv source target evidence)
  invFun := mapSteps
    (fun {index : Index} {source target : State index}
      (evidence : TargetStep source target) =>
      (stepEquiv source target).symm evidence)
  left_inv := mapSteps_inverse
    (fun {index : Index} {source target : State index}
      (evidence : SourceStep source target) =>
      stepEquiv source target evidence)
    (fun {index : Index} {source target : State index}
      (evidence : TargetStep source target) =>
      (stepEquiv source target).symm evidence)
    (fun evidence => (stepEquiv _ _).symm_apply_apply evidence)
  right_inv := mapSteps_inverse
    (fun {index : Index} {source target : State index}
      (evidence : TargetStep source target) =>
      (stepEquiv source target).symm evidence)
    (fun {index : Index} {source target : State index}
      (evidence : SourceStep source target) =>
      stepEquiv source target evidence)
    (fun evidence => (stepEquiv _ _).apply_symm_apply evidence)

/-! ## Non-collapse controls -/

namespace Canary

abbrev State : Unit → Type := fun _ => Unit
abbrev Step : {index : Unit} → State index → State index → Type :=
  fun {_} _ _ => Bool

def generator : Path State Step (index := ()) () () :=
  .step false

def witnessedRoundTrip : Path State Step (index := ()) () () :=
  .trans generator (.symm generator)

def emptyPath : Path State Step (index := ()) () () :=
  ConversionEvidence.refl (computation := computation State Step) ()

/-- Equal endpoints do not collapse a witnessed conversion to reflexivity. -/
theorem witnessed_roundtrip_ne_empty : witnessedRoundTrip ≠ emptyPath := by
  intro equality
  cases equality

def leftAssociated : Path State Step (index := ()) () () :=
  .trans (.trans generator (.symm generator)) generator

def rightAssociated : Path State Step (index := ()) () () :=
  .trans generator (.trans (.symm generator) generator)

/-- Association trees remain distinct before an explicit higher-coherence
relation is supplied. -/
theorem association_trees_distinct : leftAssociated ≠ rightAssociated := by
  intro equality
  cases equality

/-- Even an identity equivalence of generator fibres preserves the distinct
association trees. -/
theorem identity_step_equivalence_does_not_collapse_paths :
    (pathEquivOfStepEquiv
      (fun (_source _target : State ()) => Equiv.refl _)
      () ()).toFun leftAssociated ≠
    (pathEquivOfStepEquiv
      (fun (_source _target : State ()) => Equiv.refl _)
      () ()).toFun rightAssociated := by
  intro equality
  exact association_trees_distinct
    ((pathEquivOfStepEquiv
      (fun (_source _target : State ()) => Equiv.refl _)
      () ()).injective equality)

end Canary

/-! ## Axiom audit -/

#print axioms Extension.contractible
#print axioms mapSteps_comp
#print axioms pathEquivOfStepEquiv
#print axioms Canary.witnessed_roundtrip_ne_empty
#print axioms Canary.association_trees_distinct
#print axioms Canary.identity_step_equivalence_does_not_collapse_paths

end FreeConversion
end Mettapedia.TypeTheory
