import Mettapedia.TypeTheory.JudgmentalComputation

/-!
# Judgment-indexed conversion evidence

Definitional equality belongs in a judgment fibre.  Its endpoints are typed
states at one common index, and its evidence retains the complete reflexive,
symmetric, transitive derivation.  Raw endpoint conversion is a support
quotient obtained only after that index and evidence have been fixed.

This construction is independent of any particular syntax, universe algebra,
or evaluator.  A concrete calculus may interpret its computation steps here;
it does not acquire conversion authority merely by presenting an untyped
rewrite relation.
-/

namespace Mettapedia.TypeTheory
namespace JudgmentalEquality

universe uIndex uState uStep

variable {Index : Type uIndex}
variable (computation : JudgmentalComputation.{uIndex, uState, uStep} Index)

/-! ## Proof-relevant conversion inside one fibre -/

/-- Reflexive, symmetric, transitive conversion evidence generated by the
proof-relevant steps of one judgment fibre. -/
inductive ConversionEvidence {index : Index} :
    computation.State index → computation.State index →
      Type (max uState uStep) where
  | step {source target : computation.State index} :
      computation.Step source target → ConversionEvidence source target
  | refl (state : computation.State index) : ConversionEvidence state state
  | symm {source target : computation.State index} :
      ConversionEvidence source target → ConversionEvidence target source
  | trans {source middle target : computation.State index} :
      ConversionEvidence source middle →
      ConversionEvidence middle target →
      ConversionEvidence source target

namespace ConversionEvidence

/-- Propositional step support, used only as a quotient readout. -/
abbrev StepSupport {index : Index}
    (source target : computation.State index) : Prop :=
  Nonempty (computation.Step source target)

/-- The ordinary proposition-valued equivalence closure of supported steps. -/
abbrev Support {index : Index}
    (source target : computation.State index) : Prop :=
  Relation.EqvGen (StepSupport computation) source target

/-- Erasing a conversion receipt retains only reachability support. -/
def toSupport {index : Index} {source target : computation.State index} :
    ConversionEvidence computation source target →
      Support computation source target
  | .step evidence => .rel _ _ ⟨evidence⟩
  | .refl state => .refl state
  | .symm conversion => .symm _ _ conversion.toSupport
  | .trans first second =>
      .trans _ _ _ first.toSupport second.toSupport

/-- Supported conversion is exactly the propositional quotient of retained
conversion evidence.  The reverse direction yields only `Nonempty`; it cannot
choose or reconstruct a particular receipt. -/
theorem support_iff_nonempty_evidence
    {index : Index} {source target : computation.State index} :
    Support computation source target ↔
      Nonempty (ConversionEvidence computation source target) := by
  constructor
  · intro support
    induction support with
    | rel source target step =>
        rcases step with ⟨evidence⟩
        exact ⟨.step evidence⟩
    | refl state => exact ⟨.refl state⟩
    | symm source target relation ih =>
        rcases ih with ⟨evidence⟩
        exact ⟨.symm evidence⟩
    | trans source middle target first second ihFirst ihSecond =>
        rcases ihFirst with ⟨firstEvidence⟩
        rcases ihSecond with ⟨secondEvidence⟩
        exact ⟨.trans firstEvidence secondEvidence⟩
  · rintro ⟨evidence⟩
    exact evidence.toSupport

/-- Conversion composition retains the intermediate typed state and both
derivations, rather than flattening them to endpoint equality. -/
def compose {index : Index}
    {source middle target : computation.State index}
    (first : ConversionEvidence computation source middle)
    (second : ConversionEvidence computation middle target) :
    ConversionEvidence computation source target :=
  .trans first second

end ConversionEvidence

/-! ## Total states and the no-cross-fibre law -/

/-- Package a state with its judgment index. -/
abbrev TotalState : Type (max uIndex uState) :=
  Σ index, computation.State index

/-- Transport a state along equality of judgment indices. -/
def castState {sourceIndex targetIndex : Index}
    (sameIndex : sourceIndex = targetIndex)
    (state : computation.State sourceIndex) :
    computation.State targetIndex :=
  sameIndex ▸ state

/-- A conversion between total states must carry equality of their judgment
indices before its endpoint evidence can even be stated. -/
def TotalConversion (source target : TotalState computation) :
    Type (max uState uStep) :=
  Σ sameIndex : PLift (source.1 = target.1),
    ConversionEvidence computation
      (castState computation sameIndex.down source.2) target.2

def TotalConversion.indexEquality
    {source target : TotalState computation}
    (conversion : TotalConversion computation source target) :
    source.1 = target.1 :=
  conversion.1.down

/-- Identity conversion is always available at a total typed state. -/
def TotalConversion.refl (state : TotalState computation) :
    TotalConversion computation state state :=
  ⟨⟨rfl⟩, .refl state.2⟩

/-- Distinct judgment indices make conversion uninhabited.  This is a
formation-level exclusion, not a later subject-reduction theorem. -/
theorem noTotalConversionOfIndexNe
    {source target : TotalState computation}
    (different : source.1 ≠ target.1) :
    IsEmpty (TotalConversion computation source target) :=
  ⟨fun conversion => different conversion.indexEquality⟩

/-! ## Information-loss canary -/

namespace ReceiptCanary

def canaryComputation : JudgmentalComputation Unit where
  State := fun _ => Unit
  Step := fun _ _ => Bool

def first : ConversionEvidence canaryComputation (index := ()) () () :=
  .step false

def second : ConversionEvidence canaryComputation (index := ()) () () :=
  .step true

theorem first_ne_second : first ≠ second := by
  intro equality
  have evidenceEquality : false = true := by
    injection equality
  cases evidenceEquality

/-- Conversion support is inhabited while its receipt type is not a
subsingleton.  Thus truth-valued definitional equality cannot reconstruct
which computational derivation occurred. -/
theorem support_does_not_retain_receipt :
    ConversionEvidence.Support canaryComputation (index := ()) () () ∧
      ¬ Subsingleton
        (ConversionEvidence canaryComputation (index := ()) () ()) := by
  refine ⟨first.toSupport, ?_⟩
  intro subsingleton
  exact first_ne_second (subsingleton.allEq first second)

end ReceiptCanary

/-! ## Axiom audit -/

#print axioms ConversionEvidence.support_iff_nonempty_evidence
#print axioms TotalConversion.indexEquality
#print axioms noTotalConversionOfIndexNe
#print axioms ReceiptCanary.support_does_not_retain_receipt

end JudgmentalEquality
end Mettapedia.TypeTheory
