import Mathlib.CategoryTheory.Bicategory.LocallyDiscrete
import Mathlib.CategoryTheory.SingleObj
import Mathlib.Algebra.FreeMonoid.Basic
import Mettapedia.TypeTheory.FreeWhiskeredCell
import Mettapedia.TypeTheory.LocallyThinCellReflection

/-!
# A locally thin bicategory generated by authored cells

Let `B` be a bicategory and let `Authored` be an additional family of
parallel two-generators between its one-cells.  There are two sources of raw
two-dimensional evidence:

* the existing two-cells of `B`; and
* the additional authored generators.

Closing their sum under reflexivity, vertical composition, and whiskering
gives a raw free-cell calculus.  Pointwise thin reflection of that calculus
then gives an actual locally thin bicategory.  Bicategory coherence is lawful
because structural cells of `B` are included as generators, while every
parallel two-cell in the reflection is propositionally unique.

This construction establishes a coherent `M1` candidate itself.  It does not
claim a bicategorical universal property, nor that a proof-relevant
interpretation factors through the thinning.  The latter requires the separate
fibre-invariance criterion from `LocallyThinCellReflection`.
-/

set_option autoImplicit false

namespace Mettapedia.TypeTheory
namespace LocallyThinWhiskeredCellBicategory

open CategoryTheory CategoryTheory.Bicategory
open FreeWhiskeredCell
open LocallyThinCellReflection

universe uObject uHom uCell uGenerator

variable {B : Type uObject} [Bicategory.{uCell, uHom} B]

/-! ## Raw structural and authored cells -/

/-- Forget the laws of a bicategory down to the one-cell boundary consumed by
the free whiskered-cell construction. -/
def oneCellBase (B : Type uObject) [Bicategory.{uCell, uHom} B] :
    FreeWhiskeredCell.Base.{uObject, uHom} where
  Object := B
  Hom := fun source target => source ⟶ target
  compose := fun first second => first ≫ second

/-- The disjoint sources of primitive two-dimensional evidence: a structural
cell already in the base bicategory, or an added authored generator. -/
inductive ExtendedGenerator
    (Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator) :
    {source target : B} →
      (source ⟶ target) → (source ⟶ target) →
        Type (max uCell uGenerator) where
  | structural {source target : B} {first second : source ⟶ target} :
      (first ⟶ second) → ExtendedGenerator Authored first second
  | authored {source target : B} {first second : source ⟶ target} :
      Authored first second → ExtendedGenerator Authored first second

/-- Raw cells generated jointly by the base bicategory and the authored
two-generators. -/
abbrev RawGeneratedCell
    (Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator)
    {source target : B} (first second : source ⟶ target) :=
  FreeWhiskeredCell.Cell (oneCellBase B)
    (ExtendedGenerator Authored) first second

/-- The pointwise locally thin reflection of a generated cell fibre. -/
abbrev ThinCell
    (Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator)
    {source target : B} (first second : source ⟶ target) :=
  ThinReflection (RawGeneratedCell Authored first second)

/-- Include a structural cell of the base bicategory. -/
def ofStructural
    {Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator}
    {source target : B} {first second : source ⟶ target}
    (cell : first ⟶ second) : ThinCell Authored first second :=
  reflect (.generator (.structural cell))

/-- Include an authored generator. -/
def ofAuthored
    {Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator}
    {source target : B} {first second : source ⟶ target}
    (cell : Authored first second) : ThinCell Authored first second :=
  reflect (.generator (.authored cell))

/-- Reflexivity in the reflected cell calculus. -/
def identity
    {Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator}
    {source target : B} (path : source ⟶ target) :
    ThinCell Authored path path :=
  reflect
    (FreeWhiskeredCell.Cell.refl (base := oneCellBase B)
      (Generator := ExtendedGenerator Authored) path)

/-- Vertical composition descends because the target fibre is subsingleton. -/
def vertical
    {Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator}
    {source target : B} {first middle last : source ⟶ target} :
    ThinCell Authored first middle → ThinCell Authored middle last →
      ThinCell Authored first last :=
  fun earlier later =>
    Quotient.liftOn₂ earlier later
      (fun earlierRaw laterRaw =>
        reflect (.vertical earlierRaw laterRaw))
      (by
        intro _ _ _ _ _ _
        exact Subsingleton.elim _ _)

/-- Left whiskering descends to the thin reflection. -/
def whiskerLeft
    {Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator}
    {source middle target : B} (prior : source ⟶ middle)
    {first second : middle ⟶ target} :
    ThinCell Authored first second →
      ThinCell Authored (prior ≫ first) (prior ≫ second) :=
  Quotient.lift
    (fun raw =>
      reflect
        (FreeWhiskeredCell.Cell.whiskerLeft
          (base := oneCellBase B) (Generator := ExtendedGenerator Authored)
          prior raw))
    (by
      intro _ _ _
      exact Subsingleton.elim _ _)

/-- Right whiskering descends to the thin reflection. -/
def whiskerRight
    {Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator}
    {source middle target : B}
    {first second : source ⟶ middle} (suffix : middle ⟶ target) :
    ThinCell Authored first second →
      ThinCell Authored (first ≫ suffix) (second ≫ suffix) :=
  Quotient.lift
    (fun raw =>
      reflect
        (FreeWhiskeredCell.Cell.whiskerRight
          (base := oneCellBase B) (Generator := ExtendedGenerator Authored)
          suffix raw))
    (by
      intro _ _ _
      exact Subsingleton.elim _ _)

@[simp] theorem vertical_reflect
    {Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator}
    {source target : B} {first middle last : source ⟶ target}
    (earlier : RawGeneratedCell Authored first middle)
    (later : RawGeneratedCell Authored middle last) :
    vertical (reflect earlier) (reflect later) =
      reflect (.vertical earlier later) :=
  rfl

@[simp] theorem whiskerLeft_reflect
    {Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator}
    {source middle target : B} (prior : source ⟶ middle)
    {first second : middle ⟶ target}
    (cell : RawGeneratedCell Authored first second) :
    whiskerLeft prior (reflect cell) =
      reflect
        (FreeWhiskeredCell.Cell.whiskerLeft
          (base := oneCellBase B) (Generator := ExtendedGenerator Authored)
          prior cell) :=
  rfl

@[simp] theorem whiskerRight_reflect
    {Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator}
    {source middle target : B}
    {first second : source ⟶ middle} (suffix : middle ⟶ target)
    (cell : RawGeneratedCell Authored first second) :
    whiskerRight suffix (reflect cell) =
      reflect
        (FreeWhiskeredCell.Cell.whiskerRight
          (base := oneCellBase B) (Generator := ExtendedGenerator Authored)
          suffix cell) :=
  rfl

/-! ## The actual locally thin bicategory -/

/-- A wrapper separating the extended bicategory from its base object type. -/
structure Extension
    (B : Type uObject) [Bicategory.{uCell, uHom} B]
    (Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator) where
  as : B

/-- One-cells retain the one-cells of the base bicategory. -/
structure Hom
    {Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator}
    (source target : Extension B Authored) where
  as : source.as ⟶ target.as

instance extensionCategoryStruct
    {Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator} :
    CategoryStruct (Extension B Authored) where
  Hom := Hom
  id object := ⟨𝟙 object.as⟩
  comp first second := ⟨first.as ≫ second.as⟩

instance extensionHomCategory
    {Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator}
    (source target : Extension B Authored) :
    Category (source ⟶ target) where
  Hom first second := ThinCell Authored first.as second.as
  id first := identity first.as
  comp earlier later := vertical earlier later
  id_comp _ := Subsingleton.elim _ _
  comp_id _ := Subsingleton.elim _ _
  assoc _ _ _ := Subsingleton.elim _ _

instance extensionLocallyThin
    {Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator}
    (source target : Extension B Authored) :
    Quiver.IsThin (source ⟶ target) :=
  fun _ _ => thinReflectionSubsingleton _

/-- The locally thin closure is a bicategory. Structural associators and
unitors come from the base; all coherence laws follow from local thinness. -/
instance extensionBicategory
    {Authored : {source target : B} →
      (source ⟶ target) → (source ⟶ target) → Type uGenerator} :
    Bicategory (Extension B Authored) where
  homCategory := extensionHomCategory
  whiskerLeft first _ _ cell := whiskerLeft first.as cell
  whiskerRight cell last := whiskerRight last.as cell
  associator first middle last :=
    { hom := ofStructural (α_ first.as middle.as last.as).hom
      inv := ofStructural (α_ first.as middle.as last.as).inv
      hom_inv_id := Subsingleton.elim _ _
      inv_hom_id := Subsingleton.elim _ _ }
  leftUnitor first :=
    { hom := ofStructural (λ_ first.as).hom
      inv := ofStructural (λ_ first.as).inv
      hom_inv_id := Subsingleton.elim _ _
      inv_hom_id := Subsingleton.elim _ _ }
  rightUnitor first :=
    { hom := ofStructural (ρ_ first.as).hom
      inv := ofStructural (ρ_ first.as).inv
      hom_inv_id := Subsingleton.elim _ _
      inv_hom_id := Subsingleton.elim _ _ }
  whiskerLeft_id := by intros; apply Subsingleton.elim
  whiskerLeft_comp := by intros; apply Subsingleton.elim
  id_whiskerLeft := by intros; apply Subsingleton.elim
  comp_whiskerLeft := by intros; apply Subsingleton.elim
  id_whiskerRight := by intros; apply Subsingleton.elim
  comp_whiskerRight := by intros; apply Subsingleton.elim
  whiskerRight_id := by intros; apply Subsingleton.elim
  whiskerRight_comp := by intros; apply Subsingleton.elim
  whisker_assoc := by intros; apply Subsingleton.elim
  whisker_exchange := by intros; apply Subsingleton.elim
  pentagon := by intros; apply Subsingleton.elim
  triangle := by intros; apply Subsingleton.elim

/-! ## Positive and negative generic controls -/

namespace Canary

/-- A locally discrete one-object bicategory with free-monoid one-cells. -/
abbrev TestBase := LocallyDiscrete (SingleObj (FreeMonoid Unit))

def testObject : TestBase :=
  ⟨SingleObj.star (FreeMonoid Unit)⟩

def identityPath : testObject ⟶ testObject :=
  ⟨(1 : FreeMonoid Unit)⟩

def generatorPath : testObject ⟶ testObject :=
  ⟨FreeMonoid.of ()⟩

abbrev EmptyAuthored : {source target : TestBase} →
    (source ⟶ target) → (source ⟶ target) → Type :=
  fun _ _ => Empty

/-- Equality of one-cells is an algebra for the empty authored extension of
the locally discrete test base. -/
def emptyPathEqualityAlgebra :
    FreeWhiskeredCell.Algebra (oneCellBase TestBase)
      (ExtendedGenerator EmptyAuthored)
      (fun {_source _target} first second => PLift (first = second)) where
  onRefl := fun _ => ⟨rfl⟩
  onGenerator := by
    intro source target first second evidence
    cases evidence with
    | structural structural =>
        exact ⟨LocallyDiscrete.eq_of_hom structural⟩
    | authored authored =>
        exact Empty.elim authored
  onVertical := fun earlier later => ⟨earlier.down.trans later.down⟩
  onWhiskerLeft := by
    intro source middle target prior first second equality
    exact ⟨congrArg (fun path => prior ≫ path) equality.down⟩
  onWhiskerRight := by
    intro source middle target first second suffix equality
    exact ⟨congrArg (fun path => path ≫ suffix) equality.down⟩

/-- With no authored generators, generated cells over the locally discrete
test base preserve their exact one-cell. -/
theorem empty_raw_preserves_path
    {source target : TestBase} {first second : source ⟶ target}
    (cell : RawGeneratedCell (B := TestBase) EmptyAuthored first second) :
    first = second :=
  (emptyPathEqualityAlgebra.fold cell).down

/-- Negative control: local thinning does not manufacture a cell between
distinct paths when neither the base nor the authored family supplies one. -/
theorem no_empty_cell_identity_to_generator :
    IsEmpty
      (ThinCell (B := TestBase) EmptyAuthored identityPath generatorPath) :=
  ⟨fun reflected => by
    obtain ⟨raw, _⟩ := reflect_surjective reflected
    have pathEquality := empty_raw_preserves_path raw
    have valueEquality := congrArg Discrete.as pathEquality
    exact FreeMonoid.one_ne_of () valueEquality⟩

inductive StepAuthored : {source target : TestBase} →
    (source ⟶ target) → (source ⟶ target) → Type where
  | step : StepAuthored identityPath generatorPath

/-- Positive control: an authored generator creates its selected cell in the
locally thin extension. -/
def authored_step_exists :
    ThinCell (B := TestBase) StepAuthored identityPath generatorPath :=
  ofAuthored (B := TestBase) .step

/-- The completed hom categories are genuinely thin. -/
example (source target : Extension TestBase StepAuthored) :
    Quiver.IsThin (source ⟶ target) :=
  inferInstance

end Canary

/-! ## Axiom audit -/

#print axioms vertical_reflect
#print axioms whiskerLeft_reflect
#print axioms whiskerRight_reflect
#print axioms extensionBicategory
#print axioms Canary.empty_raw_preserves_path
#print axioms Canary.no_empty_cell_identity_to_generator
#print axioms Canary.authored_step_exists

end LocallyThinWhiskeredCellBicategory
end Mettapedia.TypeTheory
