import Mettapedia.TypeTheory.UniversalDependentFamilyDescent

/-!
# Dependent-family descent through a quotient

A raw quotient map is surjective and therefore admits a classical section.
Regarded as a split readout, it transports every dependent family up to
fibrewise equivalence exactly when the quotient map is injective.  Thus a
genuinely identifying quotient cannot be the base of universal dependent
descent.

This is a statement about transport of all families.  Selected invariant
families may still descend, and other pushforward constructions require their
own comprehension and substitution laws.
-/

set_option autoImplicit false

namespace Mettapedia.TypeTheory.QuotientDependentFamilyDescent

open Mettapedia.TypeTheory.DependentFamilyObserverFactorization
open Mettapedia.TypeTheory.ExtensionalReadout
open Mettapedia.TypeTheory.UniversalDependentFamilyDescent

universe uSource uFibre

/-- Every element of a raw quotient has a representative. -/
theorem quotMk_surjective {Source : Type uSource}
    (relation : Source -> Source -> Prop) :
    Function.Surjective (Quot.mk relation) := by
  intro quotient
  refine @Quot.ind Source relation
    (fun target => ∃ source, Quot.mk relation source = target) ?_ quotient
  intro source
  exact ⟨source, rfl⟩

/-- A raw quotient map equipped with a selected representative of every
quotient class. -/
noncomputable def quotientReadout {Source : Type uSource}
    (relation : Source -> Source -> Prop) :
    SplitReadout Source (Quot relation) where
  observe := Quot.mk relation
  representative quotient :=
    Classical.choose (quotMk_surjective relation quotient)
  observe_representative quotient :=
    Classical.choose_spec (quotMk_surjective relation quotient)

/-- Universal dependent-family descent through a quotient is equivalent to
injectivity of its quotient map. -/
theorem allFamiliesDescend_iff_quotMk_injective
    {Source : Type uSource} (relation : Source -> Source -> Prop) :
    AllFamiliesDescend.{uSource, uSource, uFibre}
        (quotientReadout relation) <->
      Function.Injective (Quot.mk relation) := by
  change
    AllFamiliesDescend.{uSource, uSource, uFibre}
        (quotientReadout relation) <->
      (quotientReadout relation).Faithful
  exact
    (exact_iff_allFamiliesDescend.{uSource, uSource, uFibre}
      (quotientReadout relation)).symm.trans
        (quotientReadout relation).exact_iff_faithful

/-- If the generating relation identifies only equal elements, the quotient
map is injective. -/
theorem quotMk_injective_of_relation_implies_eq
    {Source : Type uSource} {relation : Source -> Source -> Prop}
    (reflectsEquality : forall {left right}, relation left right -> left = right) :
    Function.Injective (Quot.mk relation) := by
  intro left right sameQuotient
  have reflected := congrArg
    (Quot.lift id
      (fun first second related => reflectsEquality related))
    sameQuotient
  exact reflected

/-- Consequently, a quotient generated only by equality supports every
dependent family. -/
theorem allFamiliesDescend_of_relation_implies_eq
    {Source : Type uSource} {relation : Source -> Source -> Prop}
    (reflectsEquality : forall {left right}, relation left right -> left = right) :
    AllFamiliesDescend.{uSource, uSource, uFibre}
      (quotientReadout relation) :=
  (allFamiliesDescend_iff_quotMk_injective.{uSource, uFibre}
    relation).2
      (quotMk_injective_of_relation_implies_eq reflectsEquality)

/-! ## Positive control -/

/-- The quotient generated by ordinary equality transports every dependent
family. -/
theorem equalityQuotient_allFamiliesDescend (Source : Type uSource) :
    AllFamiliesDescend.{uSource, uSource, uFibre}
      (quotientReadout (Eq : Source -> Source -> Prop)) :=
  allFamiliesDescend_of_relation_implies_eq.{uSource, uFibre}
    (fun equality => equality)

#print axioms quotMk_surjective
#print axioms quotientReadout
#print axioms allFamiliesDescend_iff_quotMk_injective
#print axioms quotMk_injective_of_relation_implies_eq
#print axioms allFamiliesDescend_of_relation_implies_eq
#print axioms equalityQuotient_allFamiliesDescend

end Mettapedia.TypeTheory.QuotientDependentFamilyDescent
