import Mettapedia.TypeTheory.IdentityObservationComparison

/-!
# Morphisms and exactness for reflexive route families

This module gives the minimal algebraic comparison between two proof-relevant
route families on one object carrier.  A morphism preserves reflexivity;
optional groupoid structure adds preservation of composition and inverse.
Fullness, faithfulness, and exactness are kept separate.

The construction has two uses.  First, a route-to-observed-equality comparison
is exactly a morphism into the lifted equality layer generated by the
observation.  Second, the strict-versus-fibrant equality boundary of a
two-level discipline has this algebraic shape: a thin strict route layer may
embed faithfully into a route-plural layer without being full.

This is not a definition of two-level type theory.  A complete calculus still
owes contextual structure, identity elimination, universes, conversion,
coherence, and a conservativity or model theorem.
-/

set_option autoImplicit false

namespace Mettapedia.TypeTheory.ReflexiveRouteComparison

open Mettapedia.TypeTheory.ScopedIdentity
open Mettapedia.TypeTheory.IdentityRouteCapabilities
open Mettapedia.TypeTheory.IdentityObservationComparison

universe uObject uSourceRoute uTargetRoute uObservation

/-! ## Reflexive route morphisms -/

/-- A fibrewise map of route witnesses which preserves reflexivity. -/
structure Morphism
    {Object : Type uObject}
    (source : Layer.{uObject, uSourceRoute} Object)
    (target : Layer.{uObject, uTargetRoute} Object) where
  mapRoute : forall {left right}, source.Route left right ->
    target.Route left right
  map_refl : forall object, mapRoute (source.refl object) = target.refl object

namespace Morphism

variable {Object : Type uObject}
variable {source : Layer.{uObject, uSourceRoute} Object}
variable {middle : Layer.{uObject, uTargetRoute} Object}
variable {target : Layer.{uObject, uObservation} Object}

/-- Identity morphism of a reflexive route layer. -/
def id (source : Layer.{uObject, uSourceRoute} Object) :
    Morphism source source where
  mapRoute := fun route => route
  map_refl _ := rfl

/-- Composition of reflexivity-preserving route maps. -/
def comp (first : Morphism source middle) (second : Morphism middle target) :
    Morphism source target where
  mapRoute route := second.mapRoute (first.mapRoute route)
  map_refl object := by rw [first.map_refl, second.map_refl]

@[simp] theorem id_mapRoute
    {left right : Object} (route : source.Route left right) :
    (id source).mapRoute route = route := rfl

@[simp] theorem comp_mapRoute
    (first : Morphism source middle) (second : Morphism middle target)
    {left right : Object} (route : source.Route left right) :
    (first.comp second).mapRoute route =
      second.mapRoute (first.mapRoute route) := rfl

variable (morphism : Morphism source middle)

/-- Every target route has a source witness. -/
def Full : Prop :=
  forall left right,
    Function.Surjective
      (fun route : source.Route left right => morphism.mapRoute route)

/-- Distinct source routes remain distinct after mapping. -/
def Faithful : Prop :=
  forall left right,
    Function.Injective
      (fun route : source.Route left right => morphism.mapRoute route)

/-- Every route fibre is carried bijectively. -/
def Exact : Prop :=
  forall left right,
    Function.Bijective
      (fun route : source.Route left right => morphism.mapRoute route)

theorem exact_iff_faithful_and_full :
    morphism.Exact <-> morphism.Faithful ∧ morphism.Full := by
  constructor
  · intro exact
    exact ⟨fun left right => (exact left right).1,
      fun left right => (exact left right).2⟩
  · rintro ⟨faithful, full⟩ left right
    exact ⟨faithful left right, full left right⟩

/-- A thin source makes every route morphism faithful. -/
theorem faithful_of_source_routeUIP
    (uip : RouteUIP source) : morphism.Faithful := by
  intro left right first second _sameTarget
  exact (uip left right).allEq first second

/-- A full map out of a thin source forces the target route layer to be thin. -/
theorem target_routeUIP_of_full
    (sourceUIP : RouteUIP source) (full : morphism.Full) :
    RouteUIP middle := by
  intro left right
  refine ⟨?_⟩
  intro first second
  obtain ⟨firstSource, firstMaps⟩ := full left right first
  obtain ⟨secondSource, secondMaps⟩ := full left right second
  calc
    first = morphism.mapRoute firstSource := firstMaps.symm
    _ = morphism.mapRoute secondSource := by
      exact congrArg morphism.mapRoute
        ((sourceUIP left right).allEq firstSource secondSource)
    _ = second := secondMaps

/-- Hence a route-plural target is an exact obstruction to fullness from a
thin strict layer. -/
theorem not_full_of_sourceUIP_target_not_routeUIP
    (sourceUIP : RouteUIP source) (targetNotUIP : ¬ RouteUIP middle) :
    ¬ morphism.Full :=
  fun full => targetNotUIP (morphism.target_routeUIP_of_full sourceUIP full)

/-- For a thin source, exactness has only one remaining price: fullness. -/
theorem exact_iff_full_of_source_routeUIP
    (uip : RouteUIP source) : morphism.Exact <-> morphism.Full := by
  rw [morphism.exact_iff_faithful_and_full]
  constructor
  · exact fun exact => exact.2
  · exact fun full => ⟨morphism.faithful_of_source_routeUIP uip, full⟩

end Morphism

/-! ## Groupoid-preserving route morphisms -/

/-- A route morphism preserving selected groupoid operations.  The groupoid
laws remain supplied independently for each layer. -/
structure GroupoidMorphism
    {Object : Type uObject}
    {source : Layer.{uObject, uSourceRoute} Object}
    {target : Layer.{uObject, uTargetRoute} Object}
    (sourceGroupoid : RouteGroupoid source)
    (targetGroupoid : RouteGroupoid target)
    extends Morphism source target where
  map_comp : forall {first middle last}
    (earlier : source.Route first middle)
    (later : source.Route middle last),
    mapRoute (sourceGroupoid.comp earlier later) =
      targetGroupoid.comp (mapRoute earlier) (mapRoute later)
  map_inv : forall {sourceObject targetObject}
    (route : source.Route sourceObject targetObject),
    mapRoute (sourceGroupoid.inv route) =
      targetGroupoid.inv (mapRoute route)

/-! ## Observed equality as a route layer -/

/-- Equality after an observation, lifted into `Type` so it can retain the
same endpoint indexing as an arbitrary route layer. -/
def observedEqualityLayer
    {Object : Type uObject} {Observation : Type uObservation}
    (observe : Object -> Observation) : Layer Object where
  Route left right := PLift (observe left = observe right)
  refl _ := ⟨rfl⟩
  Support left right := observe left = observe right
  forget route := route.down

/-- Every sound comparison to observed equality induces a reflexive route
morphism into the corresponding lifted equality layer. -/
def ofIdentityObservationComparison
    {Object : Type uObject} {Observation : Type uObservation}
    {layer : Layer.{uObject, uSourceRoute} Object}
    {observe : Object -> Observation}
    (comparison : IdentityObservationComparison.Comparison layer observe) :
    Morphism layer (observedEqualityLayer observe) where
  mapRoute route := ⟨comparison.toObservedEquality route⟩
  map_refl object := by
    change
      (⟨comparison.toObservedEquality (layer.refl object)⟩ :
        PLift (observe object = observe object)) = ⟨rfl⟩
    exact Subsingleton.elim _ _

/-- Fullness of the lifted route morphism is exactly completeness of observed
equality. -/
theorem observedMorphism_full_iff_complete
    {Object : Type uObject} {Observation : Type uObservation}
    {layer : Layer.{uObject, uSourceRoute} Object}
    {observe : Object -> Observation}
    (comparison : IdentityObservationComparison.Comparison layer observe) :
    (ofIdentityObservationComparison comparison).Full <->
      comparison.Complete := by
  constructor
  · intro full left right sameObservation
    obtain ⟨route, maps⟩ := full left right ⟨sameObservation⟩
    exact ⟨route, congrArg PLift.down maps⟩
  · intro complete left right observedRoute
    obtain ⟨route, maps⟩ := complete left right observedRoute.down
    refine ⟨route, ?_⟩
    change
      (⟨comparison.toObservedEquality route⟩ :
        PLift (observe left = observe right)) = observedRoute
    exact Subsingleton.elim _ _

/-- Faithfulness of the lifted route morphism is exactly faithfulness of the
route-to-equality comparison. -/
theorem observedMorphism_faithful_iff_faithful
    {Object : Type uObject} {Observation : Type uObservation}
    {layer : Layer.{uObject, uSourceRoute} Object}
    {observe : Object -> Observation}
    (comparison : IdentityObservationComparison.Comparison layer observe) :
    (ofIdentityObservationComparison comparison).Faithful <->
      comparison.Faithful := by
  constructor
  · intro faithful left right first second sameEquality
    apply faithful left right
    exact congrArg PLift.up sameEquality
  · intro faithful left right first second sameLiftedEquality
    apply faithful left right
    exact congrArg PLift.down sameLiftedEquality

/-- Exactness agrees in the direct equality comparison and route-morphism
views. -/
theorem observedMorphism_exact_iff_exact
    {Object : Type uObject} {Observation : Type uObservation}
    {layer : Layer.{uObject, uSourceRoute} Object}
    {observe : Object -> Observation}
    (comparison : IdentityObservationComparison.Comparison layer observe) :
    (ofIdentityObservationComparison comparison).Exact <->
      comparison.Exact := by
  constructor
  · intro exact
    have parts :=
      (Morphism.exact_iff_faithful_and_full
        (ofIdentityObservationComparison comparison)).mp exact
    have faithful :=
      (observedMorphism_faithful_iff_faithful comparison).mp parts.1
    have complete :=
      (observedMorphism_full_iff_complete comparison).mp parts.2
    exact comparison.exact_iff_complete_and_routeUIP.mpr
      ⟨complete, comparison.faithful_iff_routeUIP.mp faithful⟩
  · intro exact
    have parts := comparison.exact_iff_complete_and_routeUIP.mp exact
    apply
      (Morphism.exact_iff_faithful_and_full
        (ofIdentityObservationComparison comparison)).mpr
    exact
      ⟨(observedMorphism_faithful_iff_faithful comparison).mpr
          (comparison.faithful_iff_routeUIP.mpr parts.2),
        (observedMorphism_full_iff_complete comparison).mpr parts.1⟩

/-! ## Strict-to-route-plural canary -/

namespace Canary

open Mettapedia.TypeTheory.IdentityRouteCapabilities.Canary

/-- One strict route on the one-point carrier. -/
def strictLayer : Layer Unit where
  Route _ _ := PUnit
  refl _ := PUnit.unit
  Support _ _ := True
  forget _ := trivial

def strictGroupoid : RouteGroupoid strictLayer where
  comp _ _ := PUnit.unit
  inv _ := PUnit.unit
  refl_comp route := by
    change PUnit.unit = route
    cases route
    rfl
  comp_refl route := by
    change PUnit.unit = route
    cases route
    rfl
  assoc _ _ _ := rfl
  inv_comp _ := rfl
  comp_inv _ := rfl

theorem strict_routeUIP : RouteUIP strictLayer :=
  fun _ _ => show Subsingleton PUnit from inferInstance

theorem strict_endpointReflection : EndpointReflection strictLayer := by
  intro source target _route
  cases source
  cases target
  rfl

/-- The canonical strict route maps to the selected reflexive route in the
two-loop layer. -/
def strictToPlural : Morphism strictLayer reflectedPlural where
  mapRoute _ := false
  map_refl _ := rfl

/-- The same map preserves the complete selected groupoid algebra. -/
def strictToPluralGroupoid :
    GroupoidMorphism strictGroupoid reflectedPluralGroupoid where
  toMorphism := strictToPlural
  map_comp _ _ := rfl
  map_inv _ := rfl

theorem strictToPlural_faithful : strictToPlural.Faithful :=
  strictToPlural.faithful_of_source_routeUIP strict_routeUIP

theorem strictToPlural_not_full : ¬ strictToPlural.Full :=
  strictToPlural.not_full_of_sourceUIP_target_not_routeUIP
    strict_routeUIP reflectedPlural_not_uip

theorem strictToPlural_not_exact : ¬ strictToPlural.Exact := by
  rw [strictToPlural.exact_iff_full_of_source_routeUIP strict_routeUIP]
  exact strictToPlural_not_full

/-- Minimal strict/fibrant boundary: strict equality is endpoint-reflecting and
thin; its groupoid map into the plural route layer is faithful and
operation-preserving, but cannot reconstruct or cover the additional route. -/
theorem strict_and_plural_routes_coexist_without_collapse :
    EndpointReflection strictLayer ∧
      RouteUIP strictLayer ∧
      Nonempty
        (GroupoidMorphism strictGroupoid reflectedPluralGroupoid) ∧
      strictToPlural.Faithful ∧
      ¬ strictToPlural.Full ∧
      ¬ strictToPlural.Exact ∧
      ¬ RouteUIP reflectedPlural :=
  ⟨strict_endpointReflection, strict_routeUIP,
    ⟨strictToPluralGroupoid⟩, strictToPlural_faithful,
    strictToPlural_not_full, strictToPlural_not_exact,
    reflectedPlural_not_uip⟩

end Canary

#print axioms Morphism.exact_iff_faithful_and_full
#print axioms Morphism.target_routeUIP_of_full
#print axioms Morphism.exact_iff_full_of_source_routeUIP
#print axioms observedMorphism_full_iff_complete
#print axioms observedMorphism_faithful_iff_faithful
#print axioms observedMorphism_exact_iff_exact
#print axioms Canary.strict_and_plural_routes_coexist_without_collapse

end Mettapedia.TypeTheory.ReflexiveRouteComparison
