import Mathlib.Logic.Equiv.Bool
import Mathlib.Logic.Equiv.Sum
import Mettapedia.TypeTheory.ObserverErasure
import Mettapedia.TypeTheory.RouteTransportDiscriminator

/-!
# Transport in a univalent universe observes its paths

In a lawful transport family over a route groupoid, transport along a route is
an equivalence of fibres (`TransportFamily.transportEquiv`, the map written
`idtoeqv` for a universe).  The family is `Univalent` when this map from routes
to equivalences is a bijection between any two objects.  For the decoding
family of a universe this says that identity of types is equivalence.

**The model.**  For any decoding `El : Code → Type u`, the paths between two
codes are the equivalences of their decoded types (`pathLayer`), composed and
inverted as equivalences (`pathGroupoid`), and transport in the decoding family
applies the path (`decoding`).  Transport sends reflexivity to the identity,
composites to composites and inverses to inverses.  As in the groupoid model of
type theory, the map from paths to equivalences, defined from transport alone,
is the identity; so the decoding family is univalent (`univalence`, `ua`,
`decoding_univalent`).

**Erasure**, in the terms of `NonFactorization.Factors` (an erasure `E` is
admissible for an observer `O` when some readout `Ō` gives `Ō ∘ E = O`):

* `not_factors_transport_of_identifies_loops`: if every automorphism of the
  fibre over a code is the transport of a loop, and some automorphism moves a
  point, then an erasure identifying all loops at that code is not admissible
  for the observer transporting that point;
* `injective_of_supportsReadout_transportObservers`: if routes are determined by
  their transports, an erasure serving every transport observer between two
  objects identifies no two distinct routes;
* `transportFunction_not_factors_through_pathReflection`: the thin reflection
  of every path type of the universe loses the transport observer as soon as
  one decoded type has an automorphism moving a point, while the endpoint
  observer survives (`endpoints_factor_through_pathReflection`).

**The control** (`FiniteUniverse`, summarized by
`FiniteUniverse.univalent_profile_control`): the universe of finite types
generated by `Empty`, `Unit` and `Bool` under sums and products.  Transport
along the identity path of `Bool` fixes `true`, and transport along the path of
`Equiv.boolNot` sends it to `false`.  Every erasure identifying these two loops,
in particular the thin reflection of the loops, the support readout and the
collapse to a point, is not admissible for the observer `p ↦ transport p true`.
Positive twins: the same thin reflection serves the endpoint observer, and at
`Unit`, whose loops form a proposition, it serves every transport observer.
The loops at `Bool` are exactly the identity and negation paths, so the
transport observer at `true` factors through an erasure into a type with
decidable equality exactly when the erasure keeps them apart.  The decoding
family is an explicit transport discriminator for the two loops, so the
universe is not route-UIP and has no decidable identity-route structure, while
no transport family separates loops at `Unit`.  Paths also connect distinct
codes, such as `sum unit unit` and `bool`, so they are not reflected into
equality of codes.  Every decoded type is finite (`mem_elements`).

Unlike the Boolean canary of `RouteTransportDiscriminator`, whose two routes are
codes on a one-point carrier, the loops here are the automorphisms of a type in
a universe whose identity is equivalence.
-/

set_option autoImplicit false

universe uObject uRoute uFiber uErased uCode u

/-! ## Transport along a route is an equivalence -/

namespace Mettapedia.TypeTheory.RouteTransportDiscriminator.TransportFamily

open Mettapedia.GSLT.Core
open Mettapedia.TypeTheory.ScopedIdentity
open Mettapedia.TypeTheory.IdentityRouteCapabilities

variable {Object : Type uObject} {layer : Layer.{uObject, uRoute} Object}
variable {groupoid : RouteGroupoid layer}
variable (family : TransportFamily.{uObject, uRoute, uFiber} layer groupoid)

/-- Transport along a route is an equivalence of fibres, inverted by transport
along the inverse route.  For the decoding family of a universe this is the map
from paths to equivalences (`idtoeqv`). -/
def transportEquiv {source target : Object} (route : layer.Route source target) :
    family.Fibre source ≃ family.Fibre target where
  toFun := family.transport route
  invFun := family.transport (groupoid.inv route)
  left_inv value := by
    rw [← family.transport_comp, groupoid.comp_inv, family.transport_refl]
  right_inv value := by
    rw [← family.transport_comp, groupoid.inv_comp, family.transport_refl]

@[simp] theorem transportEquiv_apply {source target : Object}
    (route : layer.Route source target) (value : family.Fibre source) :
    family.transportEquiv route value = family.transport route value :=
  rfl

/-- Reflexivity transports by the identity equivalence. -/
theorem transportEquiv_refl (object : Object) :
    family.transportEquiv (layer.refl object) = Equiv.refl (family.Fibre object) :=
  Equiv.ext (family.transport_refl object)

/-- A composite route transports by the composite equivalence. -/
theorem transportEquiv_comp {source middle target : Object}
    (earlier : layer.Route source middle) (later : layer.Route middle target) :
    family.transportEquiv (groupoid.comp earlier later) =
      (family.transportEquiv earlier).trans (family.transportEquiv later) :=
  Equiv.ext (family.transport_comp earlier later)

/-- The inverse route transports by the inverse equivalence. -/
theorem transportEquiv_inv {source target : Object}
    (route : layer.Route source target) :
    family.transportEquiv (groupoid.inv route) = (family.transportEquiv route).symm :=
  Equiv.ext fun _ => rfl

/-- A transport family is univalent when, between any two objects, sending a
route to its transport equivalence is a bijection: identity of objects is
equivalence of their fibres. -/
def Univalent : Prop :=
  ∀ source target : Object,
    Function.Bijective (family.transportEquiv (source := source) (target := target))

/-- The transport observers on the routes from `source` to `target`: one
observer for each point of the source fibre, reading its transport. -/
def transportObservers (source target : Object) :
    PolicyFamily (layer.Route source target) where
  Policy := family.Fibre source
  Result := fun _ => family.Fibre target
  decide := fun point route => family.transport route point

end Mettapedia.TypeTheory.RouteTransportDiscriminator.TransportFamily

namespace Mettapedia.TypeTheory.UnivalentUniverseTransport

open Mettapedia.GSLT.Core
open Mettapedia.GSLT.Core.NonFactorization
open Mettapedia.TypeTheory.ScopedIdentity
open Mettapedia.TypeTheory.IdentityRouteCapabilities
open Mettapedia.TypeTheory.DecidableIdentityRouteStructure
open Mettapedia.TypeTheory.RouteTransportDiscriminator
open Mettapedia.TypeTheory.LocallyThinCellReflection
open Mettapedia.TypeTheory.ObserverErasure

/-! ## Transport observers under univalence -/

section TransportObservers

variable {Object : Type uObject} {layer : Layer.{uObject, uRoute} Object}
variable {groupoid : RouteGroupoid layer}
variable (family : TransportFamily.{uObject, uRoute, uFiber} layer groupoid)

/-- If every automorphism of the fibre over `object` is the transport of a loop
(the equivalence-to-path half of univalence there), an automorphism moving a
point gives a loop whose transport of that point differs from its transport
along reflexivity. -/
theorem exists_loop_separated_by_transport {object : Object}
    (realized : Function.Surjective
      (family.transportEquiv (source := object) (target := object)))
    (automorphism : family.Fibre object ≃ family.Fibre object)
    {point : family.Fibre object} (moves : automorphism point ≠ point) :
    ∃ loop : layer.Route object object,
      family.transport loop point ≠ family.transport (layer.refl object) point := by
  obtain ⟨loop, realizes⟩ := realized automorphism
  refine ⟨loop, fun same => moves ?_⟩
  rw [← realizes]
  exact same.trans (family.transport_refl object point)

/-- **The general control.**  If every automorphism of the fibre over `object`
is the transport of a loop and some automorphism moves `point`, then an erasure
that identifies all loops at `object` is not admissible for the observer
transporting `point`: no readout `Ō` satisfies
`Ō (erase loop) = transport loop point`. -/
theorem not_factors_transport_of_identifies_loops {object : Object}
    (realized : Function.Surjective
      (family.transportEquiv (source := object) (target := object)))
    (automorphism : family.Fibre object ≃ family.Fibre object)
    {point : family.Fibre object} (moves : automorphism point ≠ point)
    {Erased : Sort uErased} (erase : layer.Route object object → Erased)
    (identifies : ∀ first second, erase first = erase second) :
    ¬ Factors erase (fun loop => family.transport loop point) := by
  obtain ⟨loop, separated⟩ :=
    exists_loop_separated_by_transport family realized automorphism moves
  exact NonTrivialFiber.not_factors
    { left := loop
      right := layer.refl object
      sameShadow := identifies _ _
      differentValue := separated }

/-- **Transport observers see every route.**  When routes between two objects
are determined by their transport equivalences, an erasure that serves all
transport observers between them identifies no two distinct routes. -/
theorem injective_of_supportsReadout_transportObservers {source target : Object}
    (determined : Function.Injective
      (family.transportEquiv (source := source) (target := target)))
    {Erased : Type uErased} {erase : layer.Route source target → Erased}
    (supports : (family.transportObservers source target).SupportsReadout erase) :
    Function.Injective erase := by
  obtain ⟨realization⟩ := supports
  intro first second same
  apply determined
  apply Equiv.ext
  intro point
  exact (realization.agrees point first).symm.trans
    ((congrArg (realization.run point) same).trans (realization.agrees point second))

end TransportObservers

/-! ## The equivalence universe of a decoding -/

section EquivalenceUniverse

variable {Code : Type uCode} (El : Code → Type u)

/-- The paths of the universe `El`: a path between two codes is an equivalence
of their decoded types.  The support of a path type is mere equivalence. -/
abbrev pathLayer : Layer.{uCode, u} Code where
  Route source target := El source ≃ El target
  refl code := Equiv.refl (El code)
  Support source target := Nonempty (El source ≃ El target)
  forget path := ⟨path⟩

/-- Paths compose and invert as equivalences.  The laws are proved pointwise:
Mathlib's `Equiv.trans_refl`, `Equiv.trans_assoc`, `Equiv.symm_trans_self` and
`Equiv.self_trans_symm` are proved by `grind` and depend on `Classical.choice`. -/
def pathGroupoid : RouteGroupoid (pathLayer El) where
  comp earlier later := earlier.trans later
  inv path := path.symm
  refl_comp _ := Equiv.ext fun _ => rfl
  comp_refl _ := Equiv.ext fun _ => rfl
  assoc _ _ _ := Equiv.ext fun _ => rfl
  inv_comp path := Equiv.ext path.right_inv
  comp_inv path := Equiv.ext path.left_inv

/-- The decoding family of the universe: the fibre over a code is its decoded
type, and transport along a path applies the path's equivalence. -/
abbrev decoding : TransportFamily.{uCode, u, u} (pathLayer El) (pathGroupoid El) where
  Fibre := El
  transport path value := path value
  transport_refl _ _ := rfl
  transport_comp _ _ _ := rfl

/-- Transport along reflexivity is the identity. -/
theorem decoding_transport_refl (code : Code) :
    (decoding El).transport ((pathLayer El).refl code) = id :=
  rfl

/-- Transport along a composite path is the composite of the transports. -/
theorem decoding_transport_comp {source middle target : Code}
    (earlier : (pathLayer El).Route source middle)
    (later : (pathLayer El).Route middle target) :
    (decoding El).transport ((pathGroupoid El).comp earlier later) =
      (decoding El).transport later ∘ (decoding El).transport earlier :=
  rfl

/-- Transport along the inverse path is the inverse equivalence. -/
theorem decoding_transport_inv {source target : Code}
    (path : (pathLayer El).Route source target) :
    (decoding El).transport ((pathGroupoid El).inv path) =
      ⇑(path : El source ≃ El target).symm :=
  rfl

/-- Transport along a path is the path's own equivalence. -/
theorem decoding_transportEquiv {source target : Code}
    (path : (pathLayer El).Route source target) :
    (decoding El).transportEquiv path = path :=
  Equiv.ext fun _ => rfl

/-- **Univalence of the equivalence universe.**  Sending a path to its
transport equivalence is an equivalence between the paths of two codes and the
equivalences of their decodings. -/
def univalence (source target : Code) :
    (pathLayer El).Route source target ≃ (El source ≃ El target) where
  toFun := (decoding El).transportEquiv
  invFun equivalence := equivalence
  left_inv := decoding_transportEquiv El
  right_inv := decoding_transportEquiv El

@[simp] theorem univalence_apply {source target : Code}
    (path : (pathLayer El).Route source target) :
    univalence El source target path = (decoding El).transportEquiv path :=
  rfl

/-- The inverse of the univalence map: an equivalence of decodings as a path. -/
def ua {source target : Code} (equivalence : El source ≃ El target) :
    (pathLayer El).Route source target :=
  (univalence El source target).symm equivalence

/-- Transport along `ua e` is `e`. -/
theorem transportEquiv_ua {source target : Code} (equivalence : El source ≃ El target) :
    (decoding El).transportEquiv (ua El equivalence) = equivalence :=
  (univalence El source target).apply_symm_apply equivalence

/-- Every path is `ua` of its transport. -/
theorem ua_transportEquiv {source target : Code}
    (path : (pathLayer El).Route source target) :
    ua El ((decoding El).transportEquiv path) = path :=
  (univalence El source target).symm_apply_apply path

/-- The decoding family of the equivalence universe is univalent. -/
theorem decoding_univalent : (decoding El).Univalent :=
  fun source target => (univalence El source target).bijective

/-- In the equivalence universe, an erasure of the paths between two codes that
serves every transport observer identifies no two distinct paths. -/
theorem injective_of_supportsReadout_decodingObservers {source target : Code}
    {Erased : Type uErased} {erase : (pathLayer El).Route source target → Erased}
    (supports : ((decoding El).transportObservers source target).SupportsReadout erase) :
    Function.Injective erase :=
  injective_of_supportsReadout_transportObservers (decoding El)
    (decoding_univalent El source target).1 supports

/-! ### Erasing every path of the universe -/

/-- All paths of the universe, with their endpoints. -/
abbrev UniversePath := Σ source target : Code, (pathLayer El).Route source target

/-- The erasure that identifies all parallel paths of the universe: each path
type is replaced by its thin reflection, which keeps the endpoints and whether
a path exists. -/
def pathReflection (path : UniversePath El) :
    Σ source target : Code, ThinReflection ((pathLayer El).Route source target) :=
  ⟨path.1, path.2.1, reflect path.2.2⟩

/-- The endpoint observer of a path. -/
def endpoints (path : UniversePath El) : Code × Code :=
  (path.1, path.2.1)

/-- The transport observer of a path: its transport function between the
decoded types. -/
def transportFunction (path : UniversePath El) :
    Σ source target : Code, (El source → El target) :=
  ⟨path.1, path.2.1, (decoding El).transport path.2.2⟩

/-- The reflection of all paths identifies any two parallel paths. -/
theorem pathReflection_identifies {source target : Code}
    (first second : (pathLayer El).Route source target) :
    pathReflection El ⟨source, target, first⟩ =
      pathReflection El ⟨source, target, second⟩ := by
  change (⟨source, target, reflect first⟩ :
      Σ source target : Code, ThinReflection ((pathLayer El).Route source target)) =
    ⟨source, target, reflect second⟩
  rw [Subsingleton.elim (reflect first) (reflect second)]

/-- Positive twin: the reflection of all paths retains the endpoint observer. -/
theorem endpoints_factor_through_pathReflection :
    Factors (pathReflection El) (endpoints El) :=
  ⟨fun reflected => (reflected.1, reflected.2.1), fun _ => rfl⟩

/-- Parallel paths with equal transport observations have equal transports. -/
theorem transport_eq_of_transportFunction_eq {source target : Code}
    {first second : (pathLayer El).Route source target}
    (same : transportFunction El ⟨source, target, first⟩ =
      transportFunction El ⟨source, target, second⟩) :
    (decoding El).transport first = (decoding El).transport second := by
  simpa only [transportFunction, Sigma.mk.injEq, heq_eq_eq, true_and] using same

/-- If some decoded type has an automorphism moving a point, the reflection of
all paths of the universe is not admissible for the transport observer. -/
theorem transportFunction_not_factors_through_pathReflection {code : Code}
    (automorphism : El code ≃ El code) {point : El code}
    (moves : automorphism point ≠ point) :
    ¬ Factors (pathReflection El) (transportFunction El) :=
  NonTrivialFiber.not_factors
    { left := ⟨code, code, (pathLayer El).refl code⟩
      right := ⟨code, code, automorphism⟩
      sameShadow := pathReflection_identifies El _ _
      differentValue := fun same =>
        moves (congrFun (transport_eq_of_transportFunction_eq El same) point).symm }

end EquivalenceUniverse

/-! ## The universe of finite types -/

namespace FiniteUniverse

/-- Codes of the universe of finite types generated by the empty, unit and
Boolean types under binary sums and products. -/
inductive Code : Type
  | empty
  | unit
  | bool
  | sum (left right : Code)
  | prod (left right : Code)

/-- Decoding of codes. -/
def El : Code → Type
  | .empty => Empty
  | .unit => Unit
  | .bool => Bool
  | .sum left right => El left ⊕ El right
  | .prod left right => El left × El right

/-- A list of the elements of each decoded type. -/
def elements : (code : Code) → List (El code)
  | .empty => []
  | .unit => [()]
  | .bool => [false, true]
  | .sum left right =>
      (elements left).map Sum.inl ++ (elements right).map Sum.inr
  | .prod left right =>
      (elements left).flatMap fun first =>
        (elements right).map fun second => (first, second)

/-- Every decoded type is finite: its elements are listed by `elements`.  (This
is stated with a list because Mathlib's `Fintype` instances for `Unit`, `Bool`,
sums and products depend on `Classical.choice`.) -/
theorem mem_elements : (code : Code) → (value : El code) → value ∈ elements code
  | .empty, value => (value : Empty).elim
  | .unit, () => List.Mem.head _
  | .bool, false => List.Mem.head _
  | .bool, true => List.Mem.tail _ (List.Mem.head _)
  | .sum left _, .inl value =>
      List.mem_append.2 (Or.inl (List.mem_map.2 ⟨value, mem_elements left value, rfl⟩))
  | .sum _ right, .inr value =>
      List.mem_append.2 (Or.inr (List.mem_map.2 ⟨value, mem_elements right value, rfl⟩))
  | .prod left right, (first, second) =>
      List.mem_flatMap.2 ⟨first, mem_elements left first,
        List.mem_map.2 ⟨second, mem_elements right second, rfl⟩⟩

/-! ### Identity of codes is equivalence -/

/-- The distinct codes `sum unit unit` and `bool` are connected by a path. -/
def sumUnitUnitPath : (pathLayer El).Route (.sum .unit .unit) .bool :=
  Equiv.boolEquivPUnitSumPUnit.symm

/-- Hence paths are not reflected into equality of codes. -/
theorem not_endpointReflection : ¬ EndpointReflection (pathLayer El) := fun reflects =>
  Code.noConfusion (reflects sumUnitUnitPath)

/-- Negative example: `empty` and `unit` have no path between them, since their
decodings are not equivalent. -/
theorem no_path_empty_unit (path : (pathLayer El).Route .empty .unit) : False :=
  ((path : Empty ≃ Unit).symm ()).elim

/-! ### The two loops at `Bool` -/

/-- The loops of the universe at `Bool`. -/
abbrev Loop := (pathLayer El).Route Code.bool Code.bool

/-- The identity path of `Bool`. -/
def idPath : Loop :=
  (pathLayer El).refl .bool

/-- The path of the negation equivalence `Equiv.boolNot`. -/
def notPath : Loop :=
  ua El Equiv.boolNot

/-- The transport observer: transport `true` along a loop. -/
def transportObserver (loop : Loop) : Bool :=
  (decoding El).transport loop true

/-- Transport along the identity path fixes `true`. -/
theorem transport_idPath_true : (decoding El).transport idPath true = true :=
  rfl

/-- Transport along the negation path sends `true` to `false`. -/
theorem transport_notPath_true : (decoding El).transport notPath true = false :=
  rfl

/-- **The discriminator.**  The transport observer separates the two loops. -/
theorem transportObserver_separates : transportObserver idPath ≠ transportObserver notPath :=
  Bool.false_ne_true.symm

/-- The identity and negation paths are distinct. -/
theorem idPath_ne_notPath : idPath ≠ notPath := fun same =>
  transportObserver_separates (congrArg transportObserver same)

/-- The loops at `Bool` are exactly the identity and negation paths. -/
theorem loop_eq_idPath_or_notPath (loop : Loop) : loop = idPath ∨ loop = notPath := by
  have injective : Function.Injective (loop : Bool ≃ Bool) := Equiv.injective loop
  cases onTrue : (loop : Bool ≃ Bool) true <;> cases onFalse : (loop : Bool ≃ Bool) false
  · exact absurd (injective (onTrue.trans onFalse.symm)) Bool.false_ne_true.symm
  · exact Or.inr (Equiv.ext fun value => by cases value <;> assumption)
  · exact Or.inl (Equiv.ext fun value => by cases value <;> assumption)
  · exact absurd (injective (onTrue.trans onFalse.symm)) Bool.false_ne_true.symm

/-! ### Erasures of the loops at `Bool` -/

/-- **The erasure theorem.**  An erasure identifying the identity path of `Bool`
with the negation path is not admissible for the transport observer. -/
theorem transportObserver_not_factors_of_identifies {Erased : Sort uErased}
    (erase : Loop → Erased) (identifies : erase idPath = erase notPath) :
    ¬ Factors erase transportObserver :=
  NonTrivialFiber.not_factors
    { left := idPath
      right := notPath
      sameShadow := identifies
      differentValue := transportObserver_separates }

/-- The thin reflection of the loops at `Bool`, which identifies all of them, is
not admissible for the transport observer. -/
theorem transportObserver_not_factors_through_reflection :
    ¬ Factors (reflect (Cell := Loop)) transportObserver :=
  transportObserver_not_factors_of_identifies _ (Subsingleton.elim _ _)

/-- Nor is the support readout, which keeps only mere equivalence. -/
theorem transportObserver_not_factors_through_support :
    ¬ Factors ((pathLayer El).forget (source := .bool) (target := .bool))
      transportObserver :=
  transportObserver_not_factors_of_identifies _ rfl

/-- Nor is the collapse of the loops to a point. -/
theorem transportObserver_not_factors_through_point :
    ¬ Factors (fun _ : Loop => ()) transportObserver :=
  transportObserver_not_factors_of_identifies _ rfl

/-- The general control applies: every automorphism of `Bool` is the transport
of a loop, and negation moves `true`. -/
theorem transportObserver_not_factors_of_identifies_loops {Erased : Sort uErased}
    (erase : Loop → Erased) (identifies : ∀ first second, erase first = erase second) :
    ¬ Factors erase transportObserver :=
  not_factors_transport_of_identifies_loops (decoding El)
    (decoding_univalent El .bool .bool).2 Equiv.boolNot (point := true)
    Bool.false_ne_true erase identifies

/-- The thin reflection does not serve the transport observers of the loops at
`Bool` as a family. -/
theorem transportObservers_not_supported_by_reflection :
    ¬ ((decoding El).transportObservers .bool .bool).SupportsReadout
      (reflect (Cell := Loop)) :=
  PolicyFamily.not_supportsReadout_of_policy_collision _ _
    (first := idPath) (second := notPath) (Subsingleton.elim _ _) true
    transportObserver_separates

/-- **Positive twin.**  The endpoint observer factors through the same thin
reflection. -/
theorem endpoints_factor_through_reflection :
    Factors (reflect (Cell := Loop)) (fun _ : Loop => (Code.bool, Code.bool)) :=
  ⟨fun _ => (.bool, .bool), fun _ => rfl⟩

/-- **Exact admissibility.**  An erasure of the loops at `Bool` into a type
with decidable equality is admissible for the transport observer exactly when
it keeps the identity and negation paths apart. -/
theorem factors_transportObserver_iff {Erased : Sort uErased} [DecidableEq Erased]
    (erase : Loop → Erased) :
    Factors erase transportObserver ↔ erase idPath ≠ erase notPath := by
  constructor
  · intro factors identifies
    exact transportObserver_not_factors_of_identifies erase identifies factors
  · intro separated
    refine ⟨fun erased => decide (erased = erase idPath), fun loop => ?_⟩
    rcases loop_eq_idPath_or_notPath loop with rfl | rfl
    · exact decide_eq_true rfl
    · exact decide_eq_false (Ne.symm separated)

/-! ### The thin fibre at `Unit` -/

/-- The loops at `Unit` form a proposition. -/
instance unitLoops_subsingleton :
    Subsingleton ((pathLayer El).Route Code.unit Code.unit) :=
  ⟨fun _ _ => Equiv.ext fun _ => rfl⟩

/-- **Positive twin at a thin fibre.**  At `Unit`, the thin reflection of the
loops is admissible for every transport observer. -/
theorem unit_transport_factors_through_reflection (point : El .unit) :
    Factors (reflect (Cell := (pathLayer El).Route Code.unit Code.unit))
      (fun loop => (decoding El).transport loop point) :=
  (factorsThrough_iff_factors _).1
    ((factorsThrough_iff_fibreInvariant _).2 fun first second => by
      rw [Subsingleton.elim first second])

/-! ### Transport discriminators -/

/-- The decoding family is an explicit transport discriminator for the two
loops at `Bool`. -/
theorem bool_loops_have_transportDiscriminator :
    HasTransportDiscriminator (pathGroupoid El) idPath notPath :=
  ⟨decoding El, true, transportObserver_separates⟩

/-- No transport family distinguishes loops at `Unit`. -/
theorem unit_loops_have_no_transportDiscriminator
    (first second : (pathLayer El).Route Code.unit Code.unit) :
    ¬ HasTransportDiscriminator (pathGroupoid El) first second := by
  rw [hasTransportDiscriminator_iff_ne]
  exact fun different => different (Subsingleton.elim first second)

/-- The path types of the universe are not all propositions. -/
theorem not_routeUIP : ¬ RouteUIP (pathLayer El) := fun uip =>
  no_transportDiscriminator_of_routeUIP (pathGroupoid El) uip idPath notPath
    bool_loops_have_transportDiscriminator

/-- The universe admits no decidable identity-route structure. -/
theorem no_identityStructure : ¬ Nonempty (Structure (pathLayer El)) :=
  transportDiscriminator_excludes_identityStructure (pathGroupoid El)
    bool_loops_have_transportDiscriminator

/-- The reflection of all paths of the universe is not admissible for the
transport observer. -/
theorem transportFunction_not_factors :
    ¬ Factors (pathReflection El) (transportFunction El) :=
  transportFunction_not_factors_through_pathReflection El (code := .bool) Equiv.boolNot
    (point := true) Bool.false_ne_true

/-- **The univalent-profile control.**  The universe of finite types is
univalent; transport along the identity path and along the negation path of
`Bool` differ on `true`; so the thin reflection of the loops at `Bool` and the
reflection of all paths of the universe are not admissible for transport
observers, while both are admissible for the endpoint observer. -/
theorem univalent_profile_control :
    (decoding El).Univalent ∧
      (decoding El).transport idPath true = true ∧
      (decoding El).transport notPath true = false ∧
      ¬ Factors (reflect (Cell := Loop)) transportObserver ∧
      Factors (reflect (Cell := Loop)) (fun _ : Loop => (Code.bool, Code.bool)) ∧
      ¬ Factors (pathReflection El) (transportFunction El) ∧
      Factors (pathReflection El) (endpoints El) :=
  ⟨decoding_univalent El, transport_idPath_true, transport_notPath_true,
    transportObserver_not_factors_through_reflection, endpoints_factor_through_reflection,
    transportFunction_not_factors, endpoints_factor_through_pathReflection El⟩

end FiniteUniverse

/-! ## Axiom audit -/

#print axioms RouteTransportDiscriminator.TransportFamily.transportEquiv
#print axioms RouteTransportDiscriminator.TransportFamily.transportEquiv_refl
#print axioms RouteTransportDiscriminator.TransportFamily.transportEquiv_comp
#print axioms RouteTransportDiscriminator.TransportFamily.transportEquiv_inv
#print axioms not_factors_transport_of_identifies_loops
#print axioms injective_of_supportsReadout_transportObservers
#print axioms pathGroupoid
#print axioms decoding_transportEquiv
#print axioms univalence
#print axioms transportEquiv_ua
#print axioms ua_transportEquiv
#print axioms decoding_univalent
#print axioms injective_of_supportsReadout_decodingObservers
#print axioms endpoints_factor_through_pathReflection
#print axioms transportFunction_not_factors_through_pathReflection
#print axioms FiniteUniverse.mem_elements
#print axioms FiniteUniverse.not_endpointReflection
#print axioms FiniteUniverse.transport_notPath_true
#print axioms FiniteUniverse.transportObserver_separates
#print axioms FiniteUniverse.loop_eq_idPath_or_notPath
#print axioms FiniteUniverse.transportObserver_not_factors_of_identifies
#print axioms FiniteUniverse.transportObserver_not_factors_through_reflection
#print axioms FiniteUniverse.transportObserver_not_factors_through_support
#print axioms FiniteUniverse.transportObserver_not_factors_through_point
#print axioms FiniteUniverse.transportObserver_not_factors_of_identifies_loops
#print axioms FiniteUniverse.transportObservers_not_supported_by_reflection
#print axioms FiniteUniverse.endpoints_factor_through_reflection
#print axioms FiniteUniverse.factors_transportObserver_iff
#print axioms FiniteUniverse.unit_transport_factors_through_reflection
#print axioms FiniteUniverse.bool_loops_have_transportDiscriminator
#print axioms FiniteUniverse.unit_loops_have_no_transportDiscriminator
#print axioms FiniteUniverse.not_routeUIP
#print axioms FiniteUniverse.no_identityStructure
#print axioms FiniteUniverse.transportFunction_not_factors
#print axioms FiniteUniverse.univalent_profile_control

end Mettapedia.TypeTheory.UnivalentUniverseTransport
