import Mettapedia.GSLT.LanguageDef.GSLTILOccurrenceCells
import Mettapedia.GSLT.LanguageDef.GSLTILElaborationSelection
import Mettapedia.GSLT.LanguageDef.GSLTILEvidenceWorlds
import Mettapedia.GSLT.LanguageDef.GSLTILMultiworldObservation
import Mettapedia.GSLT.LanguageDef.GSLTILCapabilityGeneratedObservation
import Mettapedia.GSLT.LanguageDef.NIKRepresentedRouteObservation

/-!
# Universal structure selected for authored GSLT-IL

The theorem-level comparison between functional indexed semantics,
double-cell compilation, and proof-relevant relational semantics selects a
layered equipment rather than one global functional category.

* occurrence-bearing authored events freely generate surface paths;
* coherent paths lift exactly to cells indexed by both surface and internal
  commands;
* deterministic elaboration is a typed selection capability, exact precisely
  on covered and determinate profiles;
* Type-valued elaboration additionally separates visible outcome determinacy
  from retained proof-history multiplicity;
* forgetting authored occurrences gives the strict proposition-valued wire
  semantics and is provably non-faithful;
* typed loose routes that earn representation are vertically isomorphic to
  companions of uniquely determined tight maps;
* represented operational routes recover the existing indexed path
  fibration, observation transport, compositional direct execution, and the
  least domain generated by explicitly transported collection capabilities;
* raw ambiguous routes remain meaningful without a global elaboration map.

`SelectedUniversalStructure` packages these laws at their actual scope.  It
does not assert that the current Prime returned-fibre syntax already decodes
every GSLT-IL command; that distinct internal-language question retains its
existing exact-image boundary.
-/

namespace Mettapedia.GSLT.LanguageDef.GSLTIL.UniversalStructure

open Mettapedia.GSLT
open Mettapedia.GSLT.Dynamics
open Mettapedia.GSLT.Ultrainfinite
open Mettapedia.GSLT.IndexedOperational
open Mettapedia.GSLT.LooseRelationEquipment
open Mettapedia.GSLT.LanguageDef.GSLTIL.Syntax
open Mettapedia.GSLT.LanguageDef.GSLTIL.FreePath
open Mettapedia.GSLT.LanguageDef.GSLTIL.CoherentCompilation
open Mettapedia.GSLT.LanguageDef.GSLTIL.OccurrenceCells
open Mettapedia.GSLT.LanguageDef.GSLTIL.RouteEquipment
open Mettapedia.GSLT.LanguageDef.GSLTIL.ElaborationSelection
open Mettapedia.GSLT.LanguageDef.GSLTIL.MultiworldObservation
open Mettapedia.OSLF.MeTTaIL.Syntax

universe uObject uEdge uCarrier uTerm uContainer uValue uAuthority

/-- The universal laws actually earned by the finite authored interlingua. -/
structure SelectedUniversalStructure where
  freeExtensionContractible :
    ∀ (program : Program)
      (interpretation : EventInterpretation.{uObject, uEdge} program),
      Nonempty (EventInterpretation.PathExtension interpretation) ∧
        Subsingleton (EventInterpretation.PathExtension interpretation)
  freeExtensionUnique :
    ∀ (program : Program)
      (interpretation : EventInterpretation.{uObject, uEdge} program)
      (candidate : {source target : Pattern} →
        ProgramPath program source target →
          Route interpretation.Edge (interpretation.onObject source)
            (interpretation.onObject target)),
      (∀ object, candidate (.refl object) =
        .refl (interpretation.onObject object)) →
      (∀ {source middle target}
        (event : ProgramEvent program source middle)
        (rest : ProgramPath program middle target),
        candidate (.cons event rest) =
          .cons (interpretation.onEvent event) (candidate rest)) →
      ∀ {source target} (path : ProgramPath program source target),
        candidate path = interpretation.mapPath path
  coherentDoubleCells :
    ∀ {program : Program} {source target : Pattern}
      {path : ProgramPath program source target},
      Nonempty (OccurrenceCompilation path) ↔ Certificate.Compilable path
  typedElaborationSelectionCriterion :
    ∀ {program : Program} (profile : Profile program),
      Nonempty (ExactSelection profile) ↔
        profile.Covered ∧ profile.Determinate
  typedElaborationWorldCriterion :
    ∀ {program : Program} (profile : Profile program),
      Nonempty (ExactSelection profile) ↔
        ∀ command,
          Nonempty (profile.World command) ∧
            Subsingleton (profile.World command)
  typedEvidenceRepresentationCriterion :
    ∀ {program : Program}
      (profile : EvidenceWorlds.Profile program),
      Nonempty (Representation profile.related) ↔
        profile.Covered ∧ profile.OutcomeDeterminate ∧ profile.HistoryThin
  exactRawSelectionCompilesPaths :
    ∀ {program : Program}
      (_selection : ExactSelection (Profile.raw program))
      {source target : Pattern}
      (path : ProgramPath program source target),
      Certificate.Compilable path
  typedRepresentationCriterion :
    ∀ {program : Program} {route : RouteDecl}
      (profile : TypedRouteProfile program route),
      Nonempty profile.License ↔
        Total profile.related ∧ Deterministic profile.related
  representedCompanionLeftInverse :
    ∀ {Source Target : Type uCarrier} {relation : Loose Source Target}
      (representation : Representation relation),
      Cell.vcomp representation.toCompanionCell
          representation.fromCompanionCell = Cell.id relation
  representedCompanionRightInverse :
    ∀ {Source Target : Type uCarrier} {relation : Loose Source Target}
      (representation : Representation relation),
      Cell.vcomp representation.fromCompanionCell
          representation.toCompanionCell =
        Cell.id (companion representation.map)
  operationalComposition :
    ∀ {first middle last : GSLT.{uTerm}}
      (earlier : RepresentedOperationalRoute first middle)
      (later : RepresentedOperationalRoute middle last),
      (RepresentedOperationalRoute.comp earlier later
        ).toOperationalTranslation =
        OperationalTranslation.comp earlier.toOperationalTranslation
          later.toOperationalTranslation
  representedCapabilityDomainUniversal :
    ∀ {source target : GSLT.{uTerm}}
      (route : RepresentedOperationalRoute source target)
      (targetDiscipline :
        GSLTObservation.{uTerm, uContainer, uValue} target)
      (chronological : ChronologicalCapability targetDiscipline.collection)
      (parallel : IndependentParallelCapability targetDiscipline.collection)
      (Independent : targetDiscipline.collection.Container →
        targetDiscipline.collection.Container → Type uAuthority)
      (container : targetDiscipline.collection.Container),
      (route.pullbackCapabilityDomain targetDiscipline chronological parallel
        Independent).contains container ↔
        ∀ closed : ObservationDiscipline.OperationalDomain.CapabilityClosed
          (route.pullbackChronological targetDiscipline chronological)
          (route.pullbackIndependentParallel targetDiscipline parallel)
          Independent,
          closed.contains container
  ambiguousElaborationNoncollapse :
    ∃ program : Program,
      ¬ ∃ elaborate : Pattern → Pattern,
        ∀ surface internal,
          Elaborates program surface internal ↔
            elaborate surface = internal
  rawExactSelectionNoncollapse :
    ∃ program : Program,
      ¬ Nonempty (ExactSelection (Profile.raw program))
  proofHistoryNoncollapse :
    ∃ (program : Program) (source target : Boundary)
      (first second : OccurrenceWireCell program source target),
      first ≠ second ∧
        first.toRetainedWireStep = second.toRetainedWireStep ∧
        (EvidenceWorlds.occurrenceProfile program source target).Covered ∧
        (EvidenceWorlds.occurrenceProfile program source target).OutcomeDeterminate ∧
        ¬ Nonempty
          (Representation
            (EvidenceWorlds.occurrenceProfile program source target).related)
  multiworldObservationNoncollapse :
    ∃ (program : Program) (profile : EvidenceWorlds.Profile program)
      (command : profile.Command),
      (worlds profile command).Faithful ∧
        (outcomes profile command).Lossy
  wireOccurrenceQuotientNonfaithful :
    ∃ (program : Program) (sourceBoundary targetBoundary : Boundary)
      (first second : OccurrenceWireCell program sourceBoundary targetBoundary),
      first ≠ second ∧
        first.toRetainedWireStep = second.toRetainedWireStep

/-- The selected generic GSLT-IL structure, derived entirely from the authored
syntax and its proved semantic comparisons. -/
def selected : SelectedUniversalStructure where
  freeExtensionContractible := by
    intro program interpretation
    exact EventInterpretation.PathExtension.contractible interpretation
  freeExtensionUnique := by
    intro program interpretation candidate onRefl onCons source target path
    exact interpretation.mapPath_unique candidate onRefl onCons path
  coherentDoubleCells := by
    intro program source target path
    exact OccurrenceCompilation.nonempty_iff_compilable
  typedElaborationSelectionCriterion := by
    intro program profile
    exact ExactSelection.nonempty_iff_covered_and_determinate profile
  typedElaborationWorldCriterion := by
    intro program profile
    exact ExactSelection.nonempty_iff_world_fibres_contractible profile
  typedEvidenceRepresentationCriterion := by
    intro program profile
    exact
      EvidenceWorlds.Profile.representable_iff_covered_outcomeDeterminate_historyThin
        profile
  exactRawSelectionCompilesPaths := by
    intro program selection source target path
    exact exact_raw_selection_compiles_every_path selection path
  typedRepresentationCriterion := by
    intro program route profile
    exact profile.license_iff_total_and_deterministic
  representedCompanionLeftInverse := by
    intro Source Target relation representation
    exact representation.fromCompanion_vcomp_toCompanion
  representedCompanionRightInverse := by
    intro Source Target relation representation
    exact representation.toCompanion_vcomp_fromCompanion
  operationalComposition := by
    intro first middle last earlier later
    exact RepresentedOperationalRoute.toOperationalTranslation_comp
      earlier later
  representedCapabilityDomainUniversal := by
    intro source target route targetDiscipline chronological parallel
      Independent container
    exact route.pullbackCapabilityDomain_contains_iff_forall_closed
      targetDiscipline chronological parallel Independent container
  ambiguousElaborationNoncollapse :=
    Mettapedia.GSLT.LanguageDef.GSLTIL.WireCells.exists_program_without_global_functional_elaboration
  rawExactSelectionNoncollapse :=
    exists_program_without_global_exact_selection
  proofHistoryNoncollapse :=
    EvidenceWorlds.exists_program_occurrence_history_nonrepresentable
  multiworldObservationNoncollapse :=
    exists_program_multiworld_observation_boundary
  wireOccurrenceQuotientNonfaithful :=
    OccurrenceCells.DuplicateOccurrenceCanary.exists_distinct_cells_with_equal_wire_steps

/-! ## Consequences stated without unpacking the witness -/

/-- Occurrence-bearing authored paths are genuinely free on their authored
events: for every target edge family and generator interpretation, the type
of identity- and generator-preserving extensions is contractible. -/
theorem program_free_path_initial
    (program : Program)
    (interpretation : EventInterpretation.{uObject, uEdge} program) :
    Nonempty (EventInterpretation.PathExtension interpretation) ∧
      Subsingleton (EventInterpretation.PathExtension interpretation) :=
  EventInterpretation.PathExtension.contractible interpretation

/-- Exact elaboration has strongest true reflection only on its declared
typed profile; no claim is made about rejected raw alternatives. -/
theorem typed_elaboration_strongest_reflection
    {program : Program} {profile : Profile program}
    (selection : ExactSelection profile) (command : profile.Command)
    (internal : Pattern) :
    profile.Accepts command internal ↔
      selection.select command = internal :=
  selection.accepts_iff_selected_eq command internal

/-- Proof-relevant elaboration earns a direct companion exactly when it is
covered, visibly single-valued, and has no unresolved history multiplicity. -/
theorem typed_evidence_representation_criterion
    {program : Program} (profile : EvidenceWorlds.Profile program) :
    Nonempty (Representation profile.related) ↔
      profile.Covered ∧ profile.OutcomeDeterminate ∧ profile.HistoryThin :=
  EvidenceWorlds.Profile.representable_iff_covered_outcomeDeterminate_historyThin
    profile

/-- A unique visible elaboration result does not erase two distinct proof
histories.  The resulting profile is covered and outcome-determinate but is
not exactly representable by one direct companion. -/
theorem visible_outcome_determinacy_does_not_erase_history :
    ∃ (program : Program) (source target : Boundary)
      (first second : OccurrenceWireCell program source target),
      first ≠ second ∧
        first.toRetainedWireStep = second.toRetainedWireStep ∧
        (EvidenceWorlds.occurrenceProfile program source target).Covered ∧
        (EvidenceWorlds.occurrenceProfile program source target).OutcomeDeterminate ∧
        ¬ Nonempty
          (Representation
            (EvidenceWorlds.occurrenceProfile program source target).related) :=
  EvidenceWorlds.exists_program_occurrence_history_nonrepresentable

/-- An authored ambiguous elaboration supports a faithful observer of complete
outcome/history worlds and, over the same retained container, a deliberately
lossy observer of visible outcomes.  The interlingua therefore exposes
ambiguity to capability-indexed observers instead of resolving it globally. -/
theorem program_multiworld_observation_noncollapse :
    ∃ (program : Program) (profile : EvidenceWorlds.Profile program)
      (command : profile.Command),
      (worlds profile command).Faithful ∧
        (outcomes profile command).Lossy :=
  exists_program_multiworld_observation_boundary

/-- On a licensed typed route, the compiled result has the strongest true
extensional reflection: it is equal to a target exactly when the original
proof-relevant route fibre is inhabited. -/
theorem typed_route_strongest_extensional_reflection
    {program : Program} {route : RouteDecl}
    {profile : TypedRouteProfile program route}
    (license : profile.License) (source : profile.Source)
    (target : profile.Target) :
    Nonempty (profile.related source target) ↔
      profile.compile license source = target :=
  profile.related_iff_compiled_eq license source target

/-- Exact representation also determines the compiled execution uniquely;
there cannot be two admitted direct maps for one loose arrow. -/
theorem represented_execution_unique
    {Source Target : Type} {relation : Loose Source Target}
    (first second : Representation relation) :
    first.map = second.map :=
  Representation.map_unique first second

/-- Capability construction commutes with represented GSLT-IL transport at
its strongest honest scope: the pulled domain is characterized as the
intersection of every source domain closed under the transported capabilities
and the unchanged proof-relevant independence family. -/
theorem represented_capability_domain_universal
    {source target : GSLT.{uTerm}}
    (route : RepresentedOperationalRoute source target)
    (targetDiscipline :
      GSLTObservation.{uTerm, uContainer, uValue} target)
    (chronological : ChronologicalCapability targetDiscipline.collection)
    (parallel : IndependentParallelCapability targetDiscipline.collection)
    (Independent : targetDiscipline.collection.Container →
      targetDiscipline.collection.Container → Type uAuthority)
    (container : targetDiscipline.collection.Container) :
    (route.pullbackCapabilityDomain targetDiscipline chronological parallel
      Independent).contains container ↔
      ∀ closed : ObservationDiscipline.OperationalDomain.CapabilityClosed
        (route.pullbackChronological targetDiscipline chronological)
        (route.pullbackIndependentParallel targetDiscipline parallel)
        Independent,
        closed.contains container :=
  route.pullbackCapabilityDomain_contains_iff_forall_closed
    targetDiscipline chronological parallel Independent container

/-- Observation transport and revision-indexed NIK admission are downstream
of represented operational routes; they do not strengthen raw elaboration. -/
def observedRefinementOfRepresentedRoute
    {source target : GSLT}
    (route : RepresentedOperationalRoute source target)
    (sourceMeaning : source.Term → Prop)
    (targetDiscipline : Mettapedia.GSLT.Dynamics.GSLTObservation target) :=
  route.observedImageRefinement sourceMeaning targetDiscipline

#print axioms selected
#print axioms program_free_path_initial
#print axioms typed_elaboration_strongest_reflection
#print axioms typed_evidence_representation_criterion
#print axioms visible_outcome_determinacy_does_not_erase_history
#print axioms program_multiworld_observation_noncollapse
#print axioms typed_route_strongest_extensional_reflection
#print axioms represented_execution_unique
#print axioms represented_capability_domain_universal
#print axioms observedRefinementOfRepresentedRoute

end Mettapedia.GSLT.LanguageDef.GSLTIL.UniversalStructure
