import Mettapedia.GSLT.LanguageDef.GSLTILRouteEquipment

/-!
# The free occurrence-bearing path semantics of authored GSLT-IL

The direct syntax relation is proposition-valued and is therefore the right
reachability interface, but it cannot retain two distinct authored
occurrences with identical visible endpoints.  This module restores the
proof-relevant generators before taking paths.

`AuthoredPath` is the free path category generated by those events.  Its
universal interpreter maps objects and generating events, preserves identity
and append, and is uniquely determined by those two clauses.  Relational
GSLT-IL routes may interpret this free object without becoming functions;
represented typed fibres may subsequently compile it to a direct map.
-/

namespace Mettapedia.GSLT.LanguageDef.GSLTIL.FreePath

open Mettapedia.GSLT.Ultrainfinite
open Mettapedia.GSLT.LanguageDef.GSLTIL.Syntax
open Mettapedia.OSLF.MeTTaIL.Syntax

universe uObject uEdge

/-- One exact authored event.  The row or declaration is data, while list
membership and endpoint equations remain proof fields. -/
inductive AuthoredEvent (program : Program) : Pattern → Pattern → Type where
  | inSpace (rule : SpaceRule) (member : rule ∈ program.spaceRules) :
      AuthoredEvent program (inSpace rule.space rule.source)
        (inSpace rule.space rule.target)
  | underRoute (route : RouteDecl) (rule : SpaceRule)
      (routeMember : route ∈ program.routes)
      (ruleMember : rule ∈ program.spaceRules)
      (sameSpace : rule.space = route.sourceSpace) :
      AuthoredEvent program (routeCall route.name rule.source)
        (routeCall route.name rule.target)
  | applyRoute (route : RouteDecl) (rule : RouteRule)
      (routeMember : route ∈ program.routes)
      (ruleMember : rule ∈ program.routeRules)
      (sameName : rule.name = route.name) :
      AuthoredEvent program (routeCall route.name rule.source)
        (inSpace route.targetSpace rule.target)

namespace AuthoredEvent

/-- Forget occurrence identity only at the proposition-valued reachability
boundary. -/
def erase {program : Program} {source target : Pattern} :
    AuthoredEvent program source target → Step program source target
  | .inSpace _ member => .inSpace member
  | .underRoute _ _ routeMember ruleMember sameSpace =>
      .underRoute routeMember ruleMember sameSpace
  | .applyRoute _ _ routeMember ruleMember sameName =>
      .applyRoute routeMember ruleMember sameName

/-- The authored occurrence carried by a generator. -/
def occurrence {program : Program} {source target : Pattern} :
    AuthoredEvent program source target → Pattern
  | .inSpace rule _ => rule.occurrence
  | .underRoute route _ _ _ _ => route.occurrence
  | .applyRoute _ rule _ _ _ => rule.occurrence

/-- Every direct syntax step has at least one occurrence-bearing generator. -/
theorem ofStep {program : Program} {source target : Pattern}
    (step : Step program source target) :
    Nonempty (AuthoredEvent program source target) := by
  cases step with
  | @inSpace rule member => exact ⟨.inSpace rule member⟩
  | @underRoute route rule routeMember ruleMember sameSpace =>
      exact ⟨.underRoute route rule routeMember ruleMember sameSpace⟩
  | @applyRoute route rule routeMember ruleMember sameName =>
      exact ⟨.applyRoute route rule routeMember ruleMember sameName⟩

theorem nonempty_iff_step {program : Program} {source target : Pattern} :
    Nonempty (AuthoredEvent program source target) ↔
      Step program source target := by
  constructor
  · rintro ⟨event⟩
    exact event.erase
  · exact ofStep

end AuthoredEvent

/-- The proof-relevant free paths generated by one authored program. -/
abbrev AuthoredPath (program : Program) := Route (AuthoredEvent program)

namespace AuthoredPath

/-- Proof-relevant paths erase to the established propositional closure. -/
def toRuns {program : Program} {source target : Pattern} :
    AuthoredPath program source target → Runs program source target
  | .refl state => .refl state
  | .cons event rest => .tail event.erase (toRuns rest)

/-- Every propositional run has at least one occurrence-bearing path. -/
theorem ofRuns {program : Program} {source target : Pattern}
    (run : Runs program source target) :
    Nonempty (AuthoredPath program source target) := by
  induction run with
  | refl state => exact ⟨.refl state⟩
  | tail step rest inductionHypothesis =>
      obtain ⟨event⟩ := AuthoredEvent.ofStep step
      obtain ⟨path⟩ := inductionHypothesis
      exact ⟨.cons event path⟩

theorem nonempty_iff_runs {program : Program} {source target : Pattern} :
    Nonempty (AuthoredPath program source target) ↔
      Runs program source target := by
  constructor
  · rintro ⟨path⟩
    exact toRuns path
  · exact ofRuns

/-- Sequential composition is the free path append. -/
def comp {program : Program} {first middle last : Pattern}
    (earlier : AuthoredPath program first middle)
    (later : AuthoredPath program middle last) :
    AuthoredPath program first last :=
  earlier.append later

@[simp] theorem refl_comp {program : Program} {source target : Pattern}
    (path : AuthoredPath program source target) :
    comp (.refl source) path = path :=
  rfl

@[simp] theorem comp_refl {program : Program} {source target : Pattern}
    (path : AuthoredPath program source target) :
    comp path (.refl target) = path :=
  Route.append_refl path

theorem comp_assoc {program : Program} {first second third fourth : Pattern}
    (left : AuthoredPath program first second)
    (middle : AuthoredPath program second third)
    (right : AuthoredPath program third fourth) :
    comp (comp left middle) right = comp left (comp middle right) :=
  Route.append_assoc left middle right

end AuthoredPath

/-! ## Universal interpretation -/

/-- A choice of semantic objects and semantic edges for every authored
generator. -/
structure EventInterpretation (program : Program) where
  Object : Type uObject
  Edge : Object → Object → Type uEdge
  onObject : Pattern → Object
  onEvent : ∀ {source target}, AuthoredEvent program source target →
    Edge (onObject source) (onObject target)

namespace EventInterpretation

/-- The unique structural extension from generators to free paths. -/
def mapPath {program : Program} (interpretation : EventInterpretation program) :
    {source target : Pattern} → AuthoredPath program source target →
      Route interpretation.Edge (interpretation.onObject source)
        (interpretation.onObject target)
  | _, _, .refl object => .refl (interpretation.onObject object)
  | _, _, .cons event rest =>
      .cons (interpretation.onEvent event) (interpretation.mapPath rest)

@[simp] theorem mapPath_refl {program : Program}
    (interpretation : EventInterpretation program) (object : Pattern) :
    interpretation.mapPath (.refl object) =
      .refl (interpretation.onObject object) :=
  rfl

@[simp] theorem mapPath_cons {program : Program}
    (interpretation : EventInterpretation program)
    {source middle target : Pattern}
    (event : AuthoredEvent program source middle)
    (rest : AuthoredPath program middle target) :
    interpretation.mapPath (.cons event rest) =
      .cons (interpretation.onEvent event) (interpretation.mapPath rest) :=
  rfl

theorem mapPath_append {program : Program}
    (interpretation : EventInterpretation program)
    {source middle target : Pattern}
    (earlier : AuthoredPath program source middle)
    (later : AuthoredPath program middle target) :
    interpretation.mapPath (earlier.append later) =
      (interpretation.mapPath earlier).append
        (interpretation.mapPath later) := by
  induction earlier with
  | refl => rfl
  | cons event rest inductionHypothesis =>
      change
        Route.cons (interpretation.onEvent event)
            (interpretation.mapPath (rest.append later)) =
          Route.cons (interpretation.onEvent event)
            ((interpretation.mapPath rest).append
              (interpretation.mapPath later))
      rw [inductionHypothesis]

/-- Universal uniqueness: any path map preserving identities and generator
extension is the structural interpreter. -/
theorem mapPath_unique {program : Program}
    (interpretation : EventInterpretation program)
    (candidate : {source target : Pattern} →
      AuthoredPath program source target →
        Route interpretation.Edge (interpretation.onObject source)
          (interpretation.onObject target))
    (onRefl : ∀ object, candidate (.refl object) =
      .refl (interpretation.onObject object))
    (onCons : ∀ {source middle target}
      (event : AuthoredEvent program source middle)
      (rest : AuthoredPath program middle target),
      candidate (.cons event rest) =
        .cons (interpretation.onEvent event) (candidate rest)) :
    ∀ {source target} (path : AuthoredPath program source target),
      candidate path = interpretation.mapPath path := by
  intro source target path
  induction path with
  | refl object => exact onRefl object
  | cons event rest inductionHypothesis =>
      rw [onCons event rest, inductionHypothesis]
      rfl

end EventInterpretation

/-! ## Duplicate-occurrence control -/

namespace DuplicateOccurrenceCanary

private def atom (name : String) : Pattern := .apply name []
private def space := atom "space"
private def input := atom "input"
private def output := atom "output"

private def firstRule : SpaceRule :=
  { occurrence := atom "first-occurrence"
    space := space
    source := input
    target := output }

private def secondRule : SpaceRule :=
  { occurrence := atom "second-occurrence"
    space := space
    source := input
    target := output }

private def program : Program :=
  { spaceRules := [firstRule, secondRule]
    routes := []
    routeRules := [] }

private def firstEvent : AuthoredEvent program
    (inSpace space input) (inSpace space output) :=
  .inSpace firstRule (by simp [program])

private def secondEvent : AuthoredEvent program
    (inSpace space input) (inSpace space output) :=
  .inSpace secondRule (by simp [program])

/-- The free generators retain two visibly coincident authored occurrences. -/
theorem events_distinct : firstEvent ≠ secondEvent := by
  intro equal
  have occurrenceEqual := congrArg AuthoredEvent.occurrence equal
  change atom "first-occurrence" = atom "second-occurrence" at occurrenceEqual
  simp [atom] at occurrenceEqual

/-- Proposition-valued reachability deliberately forgets that distinction. -/
theorem erased_events_equal : firstEvent.erase = secondEvent.erase :=
  Subsingleton.elim _ _

end DuplicateOccurrenceCanary

#print axioms AuthoredEvent.nonempty_iff_step
#print axioms AuthoredPath.nonempty_iff_runs
#print axioms AuthoredPath.comp_assoc
#print axioms EventInterpretation.mapPath_append
#print axioms EventInterpretation.mapPath_unique
#print axioms DuplicateOccurrenceCanary.events_distinct
#print axioms DuplicateOccurrenceCanary.erased_events_equal

end Mettapedia.GSLT.LanguageDef.GSLTIL.FreePath
