import Mettapedia.Logic.InstitutionCanary
import Mettapedia.GSLT.LanguageDef.InstitutionConsequence

/-!
# Model-qualified operational-face canary

The closed membership theory generated by the sentence `false` is realized by
a one-state machine whose denoted predicate model is exactly `{false}`.  The
resulting atlas face accepts `false` and rejects `true`; this checks that the
institution-to-GSLT bridge preserves semantic content rather than merely
packaging an arbitrary operational predicate.
-/

set_option autoImplicit false

namespace Mettapedia.GSLT.LanguageDef.InstitutionConsequenceCanary

open CategoryTheory
open scoped CategoryTheory
open Mettapedia.GSLT
open Mettapedia.GSLT.IndexedOperational
open Mettapedia.GSLT.LanguageDef.NIKMetalogic
open Mettapedia.GSLT.LanguageDef.InstitutionConsequence
open Mettapedia.Logic.InstitutionCanary

/-- The semantic theory generated by the Boolean sentence `false`. -/
def falseTheory : PiInstitution.TheoryObject
    (consequenceProjection membershipInstitution) :=
  PiInstitution.generatedTheory
    (consequenceProjection membershipInstitution) Bool {false}

/-- A single operational state denotes the native predicate model `{false}`. -/
def falseFace : StateIndexedModel membershipInstitution falseTheory where
  system := GSLT.discrete Unit
  stateModel := fun _ => CategoryTheory.Discrete.mk ({false} : Set Bool)
  models_theory := by
    intro formula theoremhood _state
    change formula ∈ ({false} : Set Bool)
    exact (membership_entails_iff Bool {false} formula).mp theoremhood

/-- Positive control: the generating sentence is true at the operational
state because its denoted native model contains it. -/
theorem generated_sentence_holds :
    (falseFace.toOperationalModel.interpret false) () := by
  change false ∈ ({false} : Set Bool)
  exact Set.mem_singleton false

/-- Negative control: the other Boolean sentence is not silently admitted. -/
theorem ungenerated_sentence_fails :
    ¬ (falseFace.toOperationalModel.interpret true) () := by
  change true ∈ ({false} : Set Bool) → False
  intro member
  exact Bool.false_ne_true (Set.mem_singleton_iff.mp member).symm

/-- The operational truth test is exactly satisfaction in the native model. -/
theorem operational_reading_is_native_satisfaction (sentence : Bool) :
    (falseFace.toOperationalModel.interpret sentence) () ↔
      membershipInstitution.satisfies Bool
        (falseFace.stateModel
          (Quotient.mk falseFace.system.equations ())) sentence :=
  Iff.rfl

/-! ## Model erasure is genuinely lossy -/

/-- Keep the two isomorphic model representatives distinct. -/
def keepAliasedModel :
    CategoryTheory.Functor IsoAliasedModel IsoAliasedModel where
  obj model := model
  map _ := ()
  map_id _ := rfl
  map_comp _ _ := rfl

/-- Swap the two isomorphic model representatives. -/
def swapAliasedModel :
    CategoryTheory.Functor IsoAliasedModel IsoAliasedModel where
  obj
    | .retained => .omitted
    | .omitted => .retained
  map _ := ()
  map_id _ := rfl
  map_comp _ _ := rfl

/-- One institution endomorphism reads target models without changing their
representative. -/
def keepModelComorphism :
    Mettapedia.Logic.Institution.Comorphism
      isoInvariantInstitution isoInvariantInstitution where
  mapSignature := CategoryTheory.Functor.id OneSignature
  mapSentence :=
    (CategoryTheory.Functor.leftUnitor isoInvariantInstitution.sentence).inv
  mapModel :=
    { app := fun _ => keepAliasedModel.toCatHom
      naturality := by
        intro source target translation
        rfl }
  satisfaction_condition := by
    intro signature targetModel sourceSentence
    exact Iff.rfl

/-- A second endomorphism has the same signature and sentence translation but
swaps the native model representative. -/
def swapModelComorphism :
    Mettapedia.Logic.Institution.Comorphism
      isoInvariantInstitution isoInvariantInstitution where
  mapSignature := CategoryTheory.Functor.id OneSignature
  mapSentence :=
    (CategoryTheory.Functor.leftUnitor isoInvariantInstitution.sentence).inv
  mapModel :=
    { app := fun _ => swapAliasedModel.toCatHom
      naturality := by
        intro source target translation
        rfl }
  satisfaction_condition := by
    intro signature targetModel sourceSentence
    exact Iff.rfl

/-- The two native routes differ on the retained model representative. -/
theorem modelComorphisms_distinct :
    keepModelComorphism ≠ swapModelComorphism := by
  intro routesEqual
  have modelsEqual := congrArg
    (fun route =>
      (route.mapModel.app
        (Opposite.op (CategoryTheory.Discrete.mk ()))).toFunctor.obj
        IsoAliasedModel.retained)
    routesEqual
  change IsoAliasedModel.retained = IsoAliasedModel.omitted at modelsEqual
  cases modelsEqual

/-- Consequence projection forgets the distinct native model actions. -/
theorem modelComorphism_erasures_equal :
    comorphismProjection keepModelComorphism =
      comorphismProjection swapModelComorphism := by
  apply PiInstitution.Comorphism.ext
  · rfl
  · rfl

/-- Bundle the representation-independent institution as an object of the category of institutions. -/
def isoInvariantObject : Mettapedia.Logic.InstitutionCategory.Object where
  Signature := CategoryTheory.Cat.of OneSignature
  logic := isoInvariantInstitution

/-- Negative control for the model-to-consequence functor: two distinct
model-valued arrows become the same consequence arrow. -/
theorem consequenceFunctor_forgets_model_map :
    consequenceFunctor.map
        (show isoInvariantObject ⟶ isoInvariantObject from keepModelComorphism) =
      consequenceFunctor.map
        (show isoInvariantObject ⟶ isoInvariantObject from swapModelComorphism) ∧
      keepModelComorphism ≠ swapModelComorphism :=
  ⟨modelComorphism_erasures_equal, modelComorphisms_distinct⟩

#print axioms falseFace
#print axioms generated_sentence_holds
#print axioms ungenerated_sentence_fails
#print axioms operational_reading_is_native_satisfaction
#print axioms modelComorphisms_distinct
#print axioms modelComorphism_erasures_equal
#print axioms consequenceFunctor_forgets_model_map

end Mettapedia.GSLT.LanguageDef.InstitutionConsequenceCanary
