import Mathlib.CategoryTheory.Discrete.Basic
import Mettapedia.GSLT.LanguageDef.CheckerAuthorityFamily

/-!
# The fail-closed NIK dispatcher as a GSLT

An executable checker can itself be presented as a reduction theory.  The
atomic construction here exposes submission, acceptance, and rejection as
ordinary terms.  It deliberately treats the checker's Boolean replay as one
atomic step; a native implementation may refine that step into decoding, DAG
replay, global-condition checking, or guest-kernel computation and prove a
separate refinement theorem.

The construction is not self-certifying.  For a raw checker it proves only
that reduction agrees with that checker.  Semantic soundness enters only when
the checker belongs to an admitted `AuthorityFamily`.
-/

namespace Mettapedia.GSLT.LanguageDef.NIKGSLT

open Mettapedia.GSLT
open Mettapedia.GSLT.LanguageDef.KernelAuthority
open Mettapedia.GSLT.LanguageDef.CheckerAuthorityFamily

universe uKind uClaim uCertificate uMachine

/-! ## Atomic checker machine -/

namespace Atomic

/-- Public configurations of one fail-closed checker invocation. -/
inductive State (Claim : Type uClaim) (Certificate : Type uCertificate) where
  | submitted (claim : Claim) (certificate : Certificate)
  | accepted (claim : Claim)
  | rejected (claim : Claim)

/-- One atomic checker transition.  A submission has exactly one terminal
successor, selected by the replay result; terminal states have no successors. -/
def Step {Claim : Type uClaim} {Certificate : Type uCertificate}
    (checker : Checker Claim Certificate) :
    State Claim Certificate -> State Claim Certificate -> Prop
  | .submitted claim certificate, .accepted acceptedClaim =>
      acceptedClaim = claim /\ checker.check claim certificate = true
  | .submitted claim certificate, .rejected rejectedClaim =>
      rejectedClaim = claim /\ checker.check claim certificate = false
  | _, _ => False

/-- The GSLT generated by an arbitrary Boolean checker. -/
def theory {Claim : Type uClaim} {Certificate : Type uCertificate}
    (checker : Checker Claim Certificate) : GSLT where
  Term := State Claim Certificate
  equations := ⟨Eq, ⟨Eq.refl, Eq.symm, Eq.trans⟩⟩
  rewrites := Step checker
  rewrites_resp_left := by
    intro source source' target equal step
    cases equal
    exact ⟨target, step, rfl⟩
  rewrites_resp_right := by
    intro source target target' step equal
    cases equal
    exact step

@[simp] theorem submitted_step_accepted_iff
    {Claim : Type uClaim} {Certificate : Type uCertificate}
    (checker : Checker Claim Certificate) (claim : Claim)
    (certificate : Certificate) :
    (theory checker).Step (.submitted claim certificate) (.accepted claim) <->
      checker.check claim certificate = true := by
  simp [GSLT.Step, theory, Step]

@[simp] theorem submitted_step_rejected_iff
    {Claim : Type uClaim} {Certificate : Type uCertificate}
    (checker : Checker Claim Certificate) (claim : Claim)
    (certificate : Certificate) :
    (theory checker).Step (.submitted claim certificate) (.rejected claim) <->
      checker.check claim certificate = false := by
  simp [GSLT.Step, theory, Step]

theorem submitted_step_iff
    {Claim : Type uClaim} {Certificate : Type uCertificate}
    (checker : Checker Claim Certificate) (claim : Claim)
    (certificate : Certificate) (target : (theory checker).Term) :
    (theory checker).Step (.submitted claim certificate) target <->
      (target = .accepted claim /\ checker.check claim certificate = true) \/
      (target = .rejected claim /\ checker.check claim certificate = false) := by
  cases target <;> simp [GSLT.Step, theory, Step]

theorem accepted_noStep
    {Claim : Type uClaim} {Certificate : Type uCertificate}
    (checker : Checker Claim Certificate) (claim : Claim) (target) :
    Not ((theory checker).Step (.accepted claim) target) := by
  cases target <;> simp [GSLT.Step, theory, Step]

theorem rejected_noStep
    {Claim : Type uClaim} {Certificate : Type uCertificate}
    (checker : Checker Claim Certificate) (claim : Claim) (target) :
    Not ((theory checker).Step (.rejected claim) target) := by
  cases target <;> simp [GSLT.Step, theory, Step]

/-- A normal configuration can only reach itself. -/
theorem multiStep_eq_of_noStep
    {system : GSLT} {source target : system.Term}
    (normal : forall next, Not (system.Step source next)) :
    system.MultiStep source target -> target = source
  | .refl _ => rfl
  | .step first _ => (normal _ first).elim

/-- Every finite reduction is either reflexive or exposes its first step. -/
theorem multiStep_refl_or_step
    {system : GSLT} {source target : system.Term} :
    system.MultiStep source target ->
      target = source \/
        exists middle, system.Step source middle /\
          system.MultiStep middle target
  | .refl _ => Or.inl rfl
  | .step first rest => Or.inr ⟨_, first, rest⟩

theorem accepted_multiStep_eq
    {Claim : Type uClaim} {Certificate : Type uCertificate}
    (checker : Checker Claim Certificate) {claim : Claim} {target}
    (path : (theory checker).MultiStep (.accepted claim) target) :
    target = .accepted claim :=
  multiStep_eq_of_noStep (accepted_noStep checker claim) path

theorem rejected_multiStep_eq
    {Claim : Type uClaim} {Certificate : Type uCertificate}
    (checker : Checker Claim Certificate) {claim : Claim} {target}
    (path : (theory checker).MultiStep (.rejected claim) target) :
    target = .rejected claim :=
  multiStep_eq_of_noStep (rejected_noStep checker claim) path

/-- Every path from a submission is either reflexive or reaches the unique
accepted/rejected terminal selected by the checker. -/
theorem submitted_multiStep_classification
    {Claim : Type uClaim} {Certificate : Type uCertificate}
    (checker : Checker Claim Certificate) {claim : Claim}
    {certificate : Certificate} {target}
    (path : (theory checker).MultiStep (.submitted claim certificate) target) :
    target = .submitted claim certificate \/
      (target = .accepted claim /\ checker.check claim certificate = true) \/
      (target = .rejected claim /\ checker.check claim certificate = false) := by
  rcases multiStep_refl_or_step path with reflexive | ⟨middle, first, rest⟩
  · exact Or.inl reflexive
  · rcases (submitted_step_iff checker claim certificate middle).mp first with
      accepted | rejected
    · obtain ⟨rfl, checked⟩ := accepted
      have terminal := accepted_multiStep_eq checker rest
      exact Or.inr (Or.inl ⟨terminal, checked⟩)
    · obtain ⟨rfl, checked⟩ := rejected
      have terminal := rejected_multiStep_eq checker rest
      exact Or.inr (Or.inr ⟨terminal, checked⟩)

/-- Acceptance reachability is exactly Boolean acceptance. -/
theorem submitted_multiStep_accepted_iff
    {Claim : Type uClaim} {Certificate : Type uCertificate}
    (checker : Checker Claim Certificate) (claim : Claim)
    (certificate : Certificate) :
    (theory checker).MultiStep (.submitted claim certificate) (.accepted claim) <->
      checker.check claim certificate = true := by
  constructor
  · intro path
    rcases submitted_multiStep_classification checker path with
      reflexive | accepted | rejected
    · cases reflexive
    · exact accepted.2
    · cases rejected.1
  · intro checked
    exact GSLT.MultiStep.step
      ((submitted_step_accepted_iff checker claim certificate).mpr checked)
      (@GSLT.MultiStep.refl (theory checker) (State.accepted claim))

/-- Rejection reachability is exactly Boolean rejection. -/
theorem submitted_multiStep_rejected_iff
    {Claim : Type uClaim} {Certificate : Type uCertificate}
    (checker : Checker Claim Certificate) (claim : Claim)
    (certificate : Certificate) :
    (theory checker).MultiStep (.submitted claim certificate) (.rejected claim) <->
      checker.check claim certificate = false := by
  constructor
  · intro path
    rcases submitted_multiStep_classification checker path with
      reflexive | accepted | rejected
    · cases reflexive
    · cases accepted.1
    · exact rejected.2
  · intro checked
    exact GSLT.MultiStep.step
      ((submitted_step_rejected_iff checker claim certificate).mpr checked)
      (@GSLT.MultiStep.refl (theory checker) (State.rejected claim))

end Atomic

/-! ## Authority-family NIK -/

namespace Family

variable {Kind : Type uKind} (family : AuthorityFamily Kind)

abbrev State := Atomic.State family.PackedClaim family.PackedCertificate

/-- The fail-closed packed NIK machine for a dependent authority family. -/
def theory [DecidableEq Kind] : GSLT :=
  Atomic.theory family.packedChecker

theorem accepts_iff [DecidableEq Kind]
    (claim : family.PackedClaim)
    (certificate : family.PackedCertificate) :
    (theory family).MultiStep (.submitted claim certificate) (.accepted claim) <->
      family.packedChecker.check claim certificate = true :=
  Atomic.submitted_multiStep_accepted_iff family.packedChecker claim certificate

theorem rejects_iff [DecidableEq Kind]
    (claim : family.PackedClaim)
    (certificate : family.PackedCertificate) :
    (theory family).MultiStep (.submitted claim certificate) (.rejected claim) <->
      family.packedChecker.check claim certificate = false :=
  Atomic.submitted_multiStep_rejected_iff family.packedChecker claim certificate

/-- Reachable NIK acceptance proves the exact certificate scope of the
selected authority. -/
theorem acceptance_implies_certified [DecidableEq Kind]
    {claim : family.PackedClaim}
    {certificate : family.PackedCertificate}
    (path : (theory family).MultiStep
      (.submitted claim certificate) (.accepted claim)) :
    family.packedCertified claim := by
  apply family.packedChecker_sound claim certificate
  exact (accepts_iff family claim certificate).mp path

/-- Semantic soundness is a separate projection from certified scope; it is
not created by the NIK machine itself. -/
theorem acceptance_implies_meaning [DecidableEq Kind]
    {claim : family.PackedClaim}
    {certificate : family.PackedCertificate}
    (path : (theory family).MultiStep
      (.submitted claim certificate) (.accepted claim)) :
    family.packedMeaning claim :=
  family.packedCertified_implies_meaning claim
    (acceptance_implies_certified family path)

/-- Every claim in the exact certified scope has evidence whose NIK execution
reaches acceptance. -/
theorem certified_has_accepting_execution [DecidableEq Kind]
    (claim : family.PackedClaim) (certified : family.packedCertified claim) :
    exists certificate : family.PackedCertificate,
      (theory family).MultiStep (.submitted claim certificate) (.accepted claim) := by
  obtain ⟨certificate, checked⟩ :=
    family.packedChecker_complete claim certified
  exact ⟨certificate, (accepts_iff family claim certificate).mpr checked⟩

end Family

/-! ## Multi-stage implementation refinement

The atomic machine is the semantic contract, not a required implementation
shape.  A decoder, chronological-DAG replay engine, global-condition checker,
or guest kernel may expose arbitrarily many internal configurations.  It
realizes the NIK contract exactly when acceptance and rejection reachability
agree with the declared Boolean checker at the public boundary.

This is deliberately two-sided.  A forward-only simulation would permit an
implementation to omit successful runs, while a backward-only simulation
would permit it to accept certificates rejected by the authority.
-/

namespace Refinement

/-- An implementation GSLT with the same public acceptance and rejection
observations as one checker.  Internal configurations and scheduling remain
implementation-specific. -/
structure Machine {Claim : Type uClaim}
    {Certificate : Type uCertificate}
    (checker : Checker Claim Certificate) where
  theory : GSLT.{uMachine}
  submit : Claim -> Certificate -> theory.Term
  accepted : Claim -> theory.Term
  rejected : Claim -> theory.Term
  accepts_iff : forall claim certificate,
    theory.MultiStep (submit claim certificate) (accepted claim) <->
      checker.check claim certificate = true
  rejects_iff : forall claim certificate,
    theory.MultiStep (submit claim certificate) (rejected claim) <->
      checker.check claim certificate = false

/-- The atomic checker GSLT realizes its own public contract. -/
def atomic {Claim : Type uClaim} {Certificate : Type uCertificate}
    (checker : Checker Claim Certificate) : Machine checker where
  theory := Atomic.theory checker
  submit := Atomic.State.submitted
  accepted := Atomic.State.accepted
  rejected := Atomic.State.rejected
  accepts_iff := Atomic.submitted_multiStep_accepted_iff checker
  rejects_iff := Atomic.submitted_multiStep_rejected_iff checker

/-- Acceptance by any exact machine refinement inherits checker soundness. -/
theorem acceptance_sound
    {Claim : Type uClaim} {Certificate : Type uCertificate}
    {checker : Checker Claim Certificate} {Meaning : Claim -> Prop}
    (machine : Machine checker) (sound : checker.Sound Meaning)
    {claim : Claim} {certificate : Certificate}
    (path : machine.theory.MultiStep
      (machine.submit claim certificate) (machine.accepted claim)) :
    Meaning claim :=
  sound claim certificate ((machine.accepts_iff claim certificate).mp path)

/-- Certificate completeness becomes accepting execution completeness for
every implementation satisfying the exact public refinement contract. -/
theorem meaningful_has_accepting_execution
    {Claim : Type uClaim} {Certificate : Type uCertificate}
    {checker : Checker Claim Certificate} {Meaning : Claim -> Prop}
    (machine : Machine checker)
    (complete : checker.CertificateComplete Meaning)
    (claim : Claim) (meaningful : Meaning claim) :
    exists certificate,
      machine.theory.MultiStep
        (machine.submit claim certificate) (machine.accepted claim) := by
  obtain ⟨certificate, accepted⟩ := complete claim meaningful
  exact ⟨certificate, (machine.accepts_iff claim certificate).mpr accepted⟩

/-- An exact checker authority remains exact after replacing its atomic step
with an arbitrary multi-stage implementation GSLT. -/
theorem authority_correspondence
    {Claim : Type uClaim} {Certificate : Type uCertificate}
    {checker : Checker Claim Certificate} {Meaning : Claim -> Prop}
    (machine : Machine checker) (authority : checker.Authority Meaning)
    (claim : Claim) :
    Meaning claim <->
      exists certificate,
        machine.theory.MultiStep
          (machine.submit claim certificate) (machine.accepted claim) := by
  constructor
  · exact meaningful_has_accepting_execution machine authority.complete claim
  · rintro ⟨certificate, path⟩
    exact acceptance_sound machine authority.sound path

/-- A native implementation of the packed dependent dispatcher is one
multi-stage machine refinement of its fail-closed packed checker. -/
abbrev FamilyMachine {Kind : Type uKind} (family : AuthorityFamily Kind)
    [DecidableEq Kind] :=
  Machine family.packedChecker

theorem family_acceptance_implies_meaning
    {Kind : Type uKind} (family : AuthorityFamily Kind) [DecidableEq Kind]
    (machine : FamilyMachine family)
    {claim : family.PackedClaim}
    {certificate : family.PackedCertificate}
    (path : machine.theory.MultiStep
      (machine.submit claim certificate) (machine.accepted claim)) :
    family.packedMeaning claim := by
  exact acceptance_sound machine
    family.packedAuthorityProjection.sound path

theorem family_certified_has_accepting_execution
    {Kind : Type uKind} (family : AuthorityFamily Kind) [DecidableEq Kind]
    (machine : FamilyMachine family)
    (claim : family.PackedClaim) (certified : family.packedCertified claim) :
    exists certificate,
      machine.theory.MultiStep
        (machine.submit claim certificate) (machine.accepted claim) :=
  meaningful_has_accepting_execution machine
    family.packedChecker_complete claim certified

end Refinement

/-! ## Honest indexed structure

Every authority kind determines its own checker GSLT.  With no declared
translations between judgment kinds this is a functor from the discrete index
category.  Calling it a richer `Ind(GSLT)` would require additional authored
reindexing morphisms and their identity/composition laws; those are not
inferred from tags.
-/

namespace Indexed

open CategoryTheory

variable {Kind : Type uKind} (family : AuthorityFamily Kind)

/-- The checker theory in one judgment fibre. -/
def fiberTheory (kind : Kind) : GSLT :=
  Atomic.theory (family.checker kind)

/-- The genuinely proved indexed object available for an arbitrary authority
family: a discrete diagram of checker GSLTs. -/
def discreteTheoryFamily : CategoryTheory.Discrete Kind ⥤ GSLT :=
  CategoryTheory.Discrete.functor (fun kind => fiberTheory family kind)

@[simp] theorem discreteTheoryFamily_obj (kind : Kind) :
    (discreteTheoryFamily family).obj (CategoryTheory.Discrete.mk kind) =
      fiberTheory family kind :=
  rfl

/-! ## Authored transport between judgment fibres -/

/-- A semantics-preserving translation between two checker fibres.  Boolean
replay must commute exactly; preservation of certified scope and guest meaning
remain separate proof obligations. -/
structure CheckerTranslation (source target : Kind) where
  mapClaim : family.Claim source -> family.Claim target
  mapCertificate : family.Certificate source -> family.Certificate target
  check_commutes : forall claim certificate,
    (family.checker target).check (mapClaim claim) (mapCertificate certificate) =
      (family.checker source).check claim certificate
  certified_preserved : forall claim,
    family.Certified source claim ->
      family.Certified target (mapClaim claim)
  meaning_preserved : forall claim,
    family.Meaning source claim -> family.Meaning target (mapClaim claim)

namespace CheckerTranslation

variable {family : AuthorityFamily Kind} {source target : Kind}
    (translation : CheckerTranslation family source target)

/-- Public checker configurations transport without exposing implementation
state. -/
def stateMap :
    Atomic.State (family.Claim source) (family.Certificate source) ->
      Atomic.State (family.Claim target) (family.Certificate target)
  | .submitted claim certificate =>
      .submitted (translation.mapClaim claim)
        (translation.mapCertificate certificate)
  | .accepted claim => .accepted (translation.mapClaim claim)
  | .rejected claim => .rejected (translation.mapClaim claim)

theorem step_map
    {state next : (fiberTheory family source).Term}
    (step : (fiberTheory family source).Step state next) :
    (fiberTheory family target).Step
      (translation.stateMap state) (translation.stateMap next) := by
  cases state <;> cases next <;>
    simp_all [fiberTheory, Atomic.theory, GSLT.Step, Atomic.Step, stateMap,
      translation.check_commutes]

/-- Every target step out of a translated state comes from a source step.
This is the backward half needed for strong behavioral transport. -/
theorem step_cover
    {state : (fiberTheory family source).Term}
    {targetNext : (fiberTheory family target).Term}
    (step : (fiberTheory family target).Step
      (translation.stateMap state) targetNext) :
    exists sourceNext,
      (fiberTheory family source).Step state sourceNext /\
        targetNext = translation.stateMap sourceNext := by
  cases state with
  | submitted claim certificate =>
      cases targetNext with
      | submitted targetClaim targetCertificate =>
          simp [fiberTheory, Atomic.theory, GSLT.Step, Atomic.Step, stateMap]
            at step
      | accepted targetClaim =>
          simp only [fiberTheory, Atomic.theory, GSLT.Step, Atomic.Step,
            stateMap] at step
          obtain ⟨rfl, checked⟩ := step
          refine ⟨.accepted claim, ?_, rfl⟩
          exact ⟨rfl, by simpa [translation.check_commutes] using checked⟩
      | rejected targetClaim =>
          simp only [fiberTheory, Atomic.theory, GSLT.Step, Atomic.Step,
            stateMap] at step
          obtain ⟨rfl, checked⟩ := step
          refine ⟨.rejected claim, ?_, rfl⟩
          exact ⟨rfl, by simpa [translation.check_commutes] using checked⟩
  | accepted claim =>
      cases targetNext <;>
        simp [fiberTheory, Atomic.theory, GSLT.Step, Atomic.Step, stateMap]
          at step
  | rejected claim =>
      cases targetNext <;>
        simp [fiberTheory, Atomic.theory, GSLT.Step, Atomic.Step, stateMap]
          at step

private theorem bisimilar_map_of_step_map_and_cover
    {sourceTheory targetTheory : GSLT}
    (mapTerm : sourceTheory.Term -> targetTheory.Term)
    (mapStep : forall {left right}, sourceTheory.Step left right ->
      targetTheory.Step (mapTerm left) (mapTerm right))
    (cover : forall {left targetRight},
      targetTheory.Step (mapTerm left) targetRight ->
        exists sourceRight, sourceTheory.Step left sourceRight /\
          targetRight = mapTerm sourceRight)
    {left right : sourceTheory.Term}
    (related : sourceTheory.Bisimilar left right) :
    targetTheory.Bisimilar (mapTerm left) (mapTerm right) := by
  obtain ⟨relation, ⟨forward, backward⟩, related⟩ := related
  let imageRelation : targetTheory.Term -> targetTheory.Term -> Prop :=
    fun first second => exists sourceFirst sourceSecond,
      first = mapTerm sourceFirst /\ second = mapTerm sourceSecond /\
        relation sourceFirst sourceSecond
  refine ⟨imageRelation, ⟨?_, ?_⟩, ?_⟩
  · rintro first second ⟨sourceFirst, sourceSecond, rfl, rfl, sourceRelated⟩
      next firstStep
    obtain ⟨sourceNext, sourceStep, rfl⟩ := cover firstStep
    obtain ⟨secondNext, secondStep, nextRelated⟩ :=
      forward sourceRelated sourceStep
    exact ⟨mapTerm secondNext, mapStep secondStep,
      sourceNext, secondNext, rfl, rfl, nextRelated⟩
  · rintro first second ⟨sourceFirst, sourceSecond, rfl, rfl, sourceRelated⟩
      next secondStep
    obtain ⟨sourceNext, sourceStep, rfl⟩ := cover secondStep
    obtain ⟨firstNext, firstStep, nextRelated⟩ :=
      backward sourceRelated sourceStep
    exact ⟨mapTerm firstNext, mapStep firstStep,
      firstNext, sourceNext, rfl, rfl, nextRelated⟩
  · exact ⟨left, right, rfl, rfl, related⟩

/-- Every lawful checker translation induces a behavioral GSLT morphism. -/
def fiberMorphism : fiberTheory family source ⟶ fiberTheory family target where
  toFun := translation.stateMap
  preserves_bisim := by
    intro left right related
    exact bisimilar_map_of_step_map_and_cover
      (sourceTheory := fiberTheory family source)
      (targetTheory := fiberTheory family target)
      translation.stateMap translation.step_map translation.step_cover related

theorem accepted_evidence_transports
    {claim : family.Claim source}
    {certificate : family.Certificate source}
    (accepted : (family.checker source).check claim certificate = true) :
    (family.checker target).check (translation.mapClaim claim)
      (translation.mapCertificate certificate) = true := by
  rw [translation.check_commutes]
  exact accepted

end CheckerTranslation

/-- An authored category of judgment kinds and coherent translations between
their checker fibres.  This is the data required for a non-discrete indexed
GSLT diagram. -/
structure AuthorityDiagram (Index : Type uKind) [Category Index] where
  family : AuthorityFamily.{uKind, uClaim, uCertificate} Index
  transport : forall {source target : Index}, (source ⟶ target) ->
    CheckerTranslation family source target
  mapClaim_id : forall (kind : Index) (claim : family.Claim kind),
    (transport (𝟙 kind)).mapClaim claim = claim
  mapCertificate_id : forall (kind : Index)
      (certificate : family.Certificate kind),
    (transport (𝟙 kind)).mapCertificate certificate = certificate
  mapClaim_comp : forall {first second third : Index}
      (left : first ⟶ second) (right : second ⟶ third)
      (claim : family.Claim first),
    (transport (left ≫ right)).mapClaim claim =
      (transport right).mapClaim ((transport left).mapClaim claim)
  mapCertificate_comp : forall {first second third : Index}
      (left : first ⟶ second) (right : second ⟶ third)
      (certificate : family.Certificate first),
    (transport (left ≫ right)).mapCertificate certificate =
      (transport right).mapCertificate
        ((transport left).mapCertificate certificate)

namespace AuthorityDiagram

variable {Index : Type uKind} [Category Index]
    (diagram : AuthorityDiagram Index)

theorem stateMap_id (kind : Index)
    (state : (fiberTheory diagram.family kind).Term) :
    (diagram.transport (𝟙 kind)).stateMap state = state := by
  cases state <;>
    simp [CheckerTranslation.stateMap, diagram.mapClaim_id,
      diagram.mapCertificate_id]

theorem stateMap_comp {first second third : Index}
    (left : first ⟶ second) (right : second ⟶ third)
    (state : (fiberTheory diagram.family first).Term) :
    (diagram.transport (left ≫ right)).stateMap state =
      (diagram.transport right).stateMap
        ((diagram.transport left).stateMap state) := by
  cases state <;>
    simp [CheckerTranslation.stateMap, diagram.mapClaim_comp,
      diagram.mapCertificate_comp]

/-- Coherent authored authority transport gives a genuine functor from the
judgment-index category into behavioral GSLTs. -/
def toGSLTFunctor : Index ⥤ GSLT where
  obj kind := fiberTheory diagram.family kind
  map arrow := (diagram.transport arrow).fiberMorphism
  map_id kind := by
    apply GSLT.Morphism.ext
    funext state
    exact diagram.stateMap_id kind state
  map_comp left right := by
    apply GSLT.Morphism.ext
    funext state
    exact diagram.stateMap_comp left right state

end AuthorityDiagram

end Indexed

/-! ## Anti-circularity canary -/

namespace Canary

def unsoundChecker : Checker Unit Unit where
  check _ _ := true

def FalseMeaning (_ : Unit) : Prop := False

theorem unsoundMachine_accepts :
    (Atomic.theory unsoundChecker).MultiStep
      (.submitted () ()) (.accepted ()) :=
  (Atomic.submitted_multiStep_accepted_iff unsoundChecker () ()).mpr rfl

/-- Reifying a checker as a GSLT does not establish semantic soundness. -/
theorem machine_reification_is_not_self_certification :
    (Atomic.theory unsoundChecker).MultiStep
        (.submitted () ()) (.accepted ()) /\
      Not (FalseMeaning ()) :=
  ⟨unsoundMachine_accepts, id⟩

/-! A non-identity transport canary. -/

inductive FlipKind where
  | positive
  | negative
deriving DecidableEq

def flipFamily : AuthorityFamily FlipKind where
  Claim := fun _ => Bool
  Certificate := fun _ => Unit
  checker
    | .positive => { check := fun claim _ => claim }
    | .negative => { check := fun claim _ => !claim }
  Certified
    | .positive => fun claim => claim = true
    | .negative => fun claim => claim = false
  Meaning
    | .positive => fun claim => claim = true
    | .negative => fun claim => claim = false
  projection := by
    intro kind
    cases kind <;> exact
      { authority :=
          { sound := by intro claim certificate accepted; simpa using accepted
            complete := by
              intro claim meaningful
              exact ⟨(), by simp [meaningful]⟩ }
        project := by intro claim certified; exact certified }

/-- Negation is a lawful translation from the positive checker fibre to the
negative checker fibre; acceptance and meaning are both preserved. -/
def flipTranslation : Indexed.CheckerTranslation flipFamily
    .positive .negative where
  mapClaim := not
  mapCertificate := id
  check_commutes := by intro claim certificate; cases claim <;> rfl
  certified_preserved := by
    intro claim certified
    cases claim <;> simp [flipFamily] at certified ⊢
  meaning_preserved := by
    intro claim meaningful
    cases claim <;> simp [flipFamily] at meaningful ⊢

theorem flip_translation_preserves_acceptance :
    (flipFamily.checker .negative).check
      (flipTranslation.mapClaim true)
      (flipTranslation.mapCertificate ()) = true := by
  exact flipTranslation.accepted_evidence_transports rfl

/-- The identity claim map is not a lawful translation between these fibres;
checker commutation is a real condition. -/
theorem identity_map_fails_flip_commutation :
    (flipFamily.checker .negative).check true () !=
      (flipFamily.checker .positive).check true () := by
  decide

end Canary

end Mettapedia.GSLT.LanguageDef.NIKGSLT
