import Mettapedia.GSLT.Core.GSLT
import Mettapedia.GSLT.LanguageDef.EquationSemantics
import Mettapedia.GSLT.LanguageDef.InteractiveCategory
import Mettapedia.GSLT.LanguageDef.WellSorted

/-!
# Semantic iGSLTs derived from interactive language presentations

This module derives a behavioral `GSLT` from the one authored
`LanguageDef` retained by an `InteractivePresentation`:

* the term carrier is the closed, well-sorted fiber at its selected
  interacting sort;
* static equivalence is generated by authored equations;
* primitive reduction is the least relation generated by authored rewrite
  schemas and their recursive congruence premises;
* the exposed GSLT step is saturated by static equivalence at both ends.

The semantic category adds exactly the behavioral obligation that cannot
follow from a bare structural map: preservation of bisimilarity.  The entire
closed carrier is derived from the structural declaration map.
The term map itself remains `mapPattern`; no arbitrary callback or second
syntax is admitted.
-/

namespace Mettapedia.GSLT.LanguageDef

open CategoryTheory
open Mettapedia.GSLT
open Mettapedia.OSLF.Framework.ConstructorCategory
open Mettapedia.OSLF.MeTTaIL.Syntax
open Mettapedia.OSLF.MeTTaIL.Engine
open Mettapedia.OSLF.MeTTaIL.ContextualStep
open EquationSemantics
open WellSorted

namespace InteractivePresentation

/-- The established name-indexed sort corresponding to the exact authored
interacting-sort declaration. -/
def interactingLangSort (presentation : InteractivePresentation) :
    LangSort presentation.presentation.language :=
  authoredSortToLangSort presentation.presentation
    presentation.interactingSort

/-- Closed semantic terms in the selected interacting fiber. -/
abbrev Term (presentation : InteractivePresentation) :=
  ClosedTerm presentation.presentation.language presentation.interactingLangSort

end InteractivePresentation

/-- The default declarative boundary interprets built-in premises and no
external relation tuples.  Languages needing an external relation model may
instantiate `presentedGSLT` with another explicit base evaluator. -/
def defaultBasePremises : BasePremiseEvaluator :=
  engineBasePremises RelationEnv.empty

/-- One authored static-equation step whose two representatives both inhabit
the closed interacting carrier.  Keeping the generator on the subtype, rather
than merely restricting the endpoints of a raw equivalence chain, prevents
ill-sorted intermediate patterns from mediating semantic equality. -/
def presentedEquationGenerator
    (base : BasePremiseEvaluator) (presentation : InteractivePresentation)
    (left right : presentation.Term) : Prop :=
  EquationContextStep base presentation.presentation.language left.1 right.1

/-- Static equations generated within the closed interacting carrier. -/
def presentedEquationSetoid
    (base : BasePremiseEvaluator) (presentation : InteractivePresentation) :
    Setoid presentation.Term where
  r := Relation.EqvGen (presentedEquationGenerator base presentation)
  iseqv :=
    { refl := Relation.EqvGen.refl
      symm := fun relation => Relation.EqvGen.symm _ _ relation
      trans := fun first second => Relation.EqvGen.trans _ _ _ first second }

/-- If an authored presentation has no equation generators, its equation
setoid on the closed interacting fiber is exactly equality. -/
theorem presentedEquationSetoid_iff_eq_of_no_generators
    (base : BasePremiseEvaluator) (presentation : InteractivePresentation)
    (equationsEmpty : presentation.presentation.language.equations = [])
    (left right : presentation.Term) :
    (presentedEquationSetoid base presentation).r left right ↔
      left = right := by
  constructor
  · intro equivalent
    induction equivalent with
    | rel left right step =>
        apply Subtype.ext
        exact (EquationSemantics.equationEquiv_iff_eq_of_no_generators
          equationsEmpty left.1 right.1).mp
            (Relation.EqvGen.rel _ _ step)
    | refl term => rfl
    | symm left right relation inductionHypothesis =>
        exact inductionHypothesis.symm
    | trans left middle right first second firstIH secondIH =>
        exact firstIH.trans secondIH
  · rintro rfl
    exact Relation.EqvGen.refl left

/-- Least authored reduction restricted to two closed terms of the
interacting fiber. -/
def presentedPrimitiveStep
    (base : BasePremiseEvaluator) (presentation : InteractivePresentation)
    (source target : presentation.Term) : Prop :=
  Step base presentation.presentation.language source.1 target.1

/-- Authored reduction saturated by static equivalence at its source and
target, as required by the abstract GSLT interface. -/
def presentedStep
    (base : BasePremiseEvaluator) (presentation : InteractivePresentation)
    (source target : presentation.Term) : Prop :=
  ∃ redex contractum : presentation.Term,
    (presentedEquationSetoid base presentation).r source redex ∧
    presentedPrimitiveStep base presentation redex contractum ∧
    (presentedEquationSetoid base presentation).r contractum target

/-- Equation saturation makes changing the source representative admissible. -/
theorem presentedStep_resp_left
    (base : BasePremiseEvaluator) (presentation : InteractivePresentation) :
    ∀ {source source' target : presentation.Term},
      (presentedEquationSetoid base presentation).r source source' →
      presentedStep base presentation source target →
      ∃ target', presentedStep base presentation source' target' ∧
        (presentedEquationSetoid base presentation).r target target' := by
  intro source source' target sourceEquivalent
  rintro ⟨redex, contractum, redexEquivalent, primitive, targetEquivalent⟩
  refine ⟨target, ⟨redex, contractum, ?_, primitive, targetEquivalent⟩, ?_⟩
  · exact (presentedEquationSetoid base presentation).iseqv.trans
      ((presentedEquationSetoid base presentation).iseqv.symm sourceEquivalent)
      redexEquivalent
  · exact (presentedEquationSetoid base presentation).iseqv.refl target

/-- Equation saturation makes changing the target representative admissible. -/
theorem presentedStep_resp_right
    (base : BasePremiseEvaluator) (presentation : InteractivePresentation) :
    ∀ {source target target' : presentation.Term},
      presentedStep base presentation source target →
      (presentedEquationSetoid base presentation).r target target' →
      presentedStep base presentation source target' := by
  intro source target target'
  rintro ⟨redex, contractum, redexEquivalent, primitive, targetEquivalent⟩
    equivalent
  exact ⟨redex, contractum, redexEquivalent, primitive,
    (presentedEquationSetoid base presentation).iseqv.trans
      targetEquivalent equivalent⟩

/-- Behavioral GSLT induced by one interactive presentation and one explicit
non-contextual premise boundary. -/
def presentedGSLT
    (base : BasePremiseEvaluator) (presentation : InteractivePresentation) :
    GSLT where
  Term := presentation.Term
  equations := presentedEquationSetoid base presentation
  rewrites := presentedStep base presentation
  rewrites_resp_left := presentedStep_resp_left base presentation
  rewrites_resp_right := presentedStep_resp_right base presentation

/-- Default empty-environment semantics of an interactive presentation. -/
def InteractivePresentation.toGSLT
    (presentation : InteractivePresentation) : GSLT :=
  presentedGSLT defaultBasePremises presentation

/-- Every primitive authored reduction embeds into the equation-saturated
GSLT step. -/
theorem primitiveStep_to_presentedStep
    {base : BasePremiseEvaluator} {presentation : InteractivePresentation}
    {source target : presentation.Term}
    (primitive : presentedPrimitiveStep base presentation source target) :
    presentedStep base presentation source target :=
  ⟨source, target,
    (presentedEquationSetoid base presentation).iseqv.refl source,
    primitive,
    (presentedEquationSetoid base presentation).iseqv.refl target⟩

/-! ## The Mathlib category iGSLT -/

/-- An executable binding-flow profile for one exact validated presentation.
The existing `FlowAdmitted` wrapper is retained, and the equality prevents
the profile from silently validating a copied or neighboring language value. -/
structure ExecutionProfile (presentation : ValidatedLanguageDef) where
  relationModes : RelationModeTable
  admitted : LanguageDef.FlowAdmitted relationModes
  exactLanguage : admitted.lang = presentation.language

/-- An iGSLT is the semantic view of one exact interactive presentation.
This wrapper changes the morphism notion without duplicating declaration
data: objects still point to the sole authored `LanguageDef`. -/
structure IGSLT where
  presentation : InteractivePresentation
  executionProfile : ExecutionProfile presentation.presentation

namespace IGSLT

/-- The behavioral GSLT underlying an iGSLT. -/
def toGSLT (theory : IGSLT) : GSLT := theory.presentation.toGSLT

/-- The structural term action restricted to the closed interacting carrier.
Every carrier obligation is derived from the declaration map. -/
def mapClosedTerm {source target : IGSLT}
    (structural : InteractiveMorphism source.presentation target.presentation)
    (term : source.presentation.Term) : target.presentation.Term :=
  ⟨mapPattern structural.structural.symbols term.1,
    ClosedTermWellSorted.map structural.structural
      structural.mapsInteractingSort term.2⟩

/-- A paper-aligned iGSLT morphism: an exact interaction-preserving theory
map whose induced structural term translation preserves behavioral
bisimilarity.  Closed-carrier obligations are theorems of the declaration
map. -/
structure Morphism (source target : IGSLT) where
  structural : InteractiveMorphism source.presentation target.presentation
  preservesBisim : ∀ {left right : source.presentation.Term},
    source.toGSLT.Bisimilar left right →
      target.toGSLT.Bisimilar
        (mapClosedTerm structural left)
        (mapClosedTerm structural right)

namespace Morphism

/-- The term action is forced by the structural presentation map. -/
def mapTerm {source target : IGSLT} (morphism : Morphism source target)
    (term : source.presentation.Term) : target.presentation.Term :=
  mapClosedTerm morphism.structural term

/-- iGSLT morphisms are determined by their structural theory map. -/
@[ext]
theorem ext {source target : IGSLT}
    {first second : Morphism source target}
    (structural : first.structural = second.structural) : first = second := by
  cases first
  cases second
  cases structural
  rfl

/-- Identity iGSLT morphism. -/
def id (theory : IGSLT) : Morphism theory theory where
  structural := InteractiveMorphism.id theory.presentation
  preservesBisim := by
    intro left right equivalent
    simpa [mapClosedTerm, InteractiveMorphism.id, StructuralMorphism.id,
      mapPattern_id]
      using equivalent

/-- The structural component of identity is the declaration-level identity. -/
@[simp]
theorem id_structural (theory : IGSLT) :
    (id theory).structural = InteractiveMorphism.id theory.presentation :=
  rfl

/-- The base structural component of identity is the exact presentation
identity. -/
@[simp]
theorem id_baseStructural (theory : IGSLT) :
    (id theory).structural.structural =
      StructuralMorphism.id theory.presentation.presentation :=
  rfl

/-- Composition of iGSLT morphisms. -/
def comp {first second third : IGSLT}
    (left : Morphism first second) (right : Morphism second third) :
    Morphism first third := by
  let structural :=
    InteractiveMorphism.comp left.structural right.structural
  refine
    { structural := structural
      preservesBisim := ?_ }
  intro source target equivalent
  have firstEquivalent := left.preservesBisim equivalent
  have secondEquivalent := right.preservesBisim firstEquivalent
  have sourceMap :
      mapClosedTerm structural source =
        right.mapTerm (left.mapTerm source) := by
    apply Subtype.ext
    exact mapPattern_comp left.structural.structural.symbols
      right.structural.structural.symbols source.1
  have targetMap :
      mapClosedTerm structural target =
        right.mapTerm (left.mapTerm target) := by
    apply Subtype.ext
    exact mapPattern_comp left.structural.structural.symbols
      right.structural.structural.symbols target.1
  rw [sourceMap, targetMap]
  exact secondEquivalent

/-- Composition exposes composition of the exact interactive maps. -/
@[simp]
theorem comp_structural {first second third : IGSLT}
    (left : Morphism first second) (right : Morphism second third) :
    (comp left right).structural =
      InteractiveMorphism.comp left.structural right.structural :=
  rfl

/-- Composition exposes composition of the exact base presentation maps. -/
@[simp]
theorem comp_baseStructural {first second third : IGSLT}
    (left : Morphism first second) (right : Morphism second third) :
    (comp left right).structural.structural =
      StructuralMorphism.comp left.structural.structural
        right.structural.structural :=
  rfl

@[simp]
theorem mapTerm_id (theory : IGSLT) (term : theory.presentation.Term) :
    (id theory).mapTerm term = term := by
  apply Subtype.ext
  exact mapPattern_id term.1

@[simp]
theorem mapTerm_comp {first second third : IGSLT}
    (left : Morphism first second) (right : Morphism second third)
    (term : first.presentation.Term) :
    (comp left right).mapTerm term = right.mapTerm (left.mapTerm term) := by
  apply Subtype.ext
  exact mapPattern_comp left.structural.structural.symbols
    right.structural.structural.symbols term.1

end Morphism

/-- iGSLTs and their paper-aligned morphisms form a Mathlib category. -/
instance : CategoryTheory.Category IGSLT where
  Hom := Morphism
  id := Morphism.id
  comp := Morphism.comp
  id_comp morphism := by
    apply Morphism.ext
    apply InteractiveMorphism.ext
    rfl
  comp_id morphism := by
    apply Morphism.ext
    apply InteractiveMorphism.ext
    rfl
  assoc first second third := by
    apply Morphism.ext
    apply InteractiveMorphism.ext
    rfl

/-- Forget semantic obligations and retain the exact structural interactive
presentation map. -/
def forgetStructural : CategoryTheory.Functor IGSLT InteractivePresentation where
  obj theory := theory.presentation
  map morphism := morphism.structural
  map_id theory := by
    apply InteractiveMorphism.ext
    rfl
  map_comp left right := by
    apply InteractiveMorphism.ext
    rfl

/-- The semantic functor from paper-aligned iGSLTs to behavioral GSLTs. -/
def semantics : CategoryTheory.Functor IGSLT GSLT where
  obj theory := theory.toGSLT
  map morphism :=
    { toFun := morphism.mapTerm
      preserves_bisim := morphism.preservesBisim }
  map_id theory := by
    apply GSLT.Morphism.ext
    funext term
    change (Morphism.id theory).mapTerm term = term
    exact Morphism.mapTerm_id theory term
  map_comp left right := by
    apply GSLT.Morphism.ext
    funext term
    change (Morphism.comp left right).mapTerm term =
      right.mapTerm (left.mapTerm term)
    exact Morphism.mapTerm_comp left right term

end IGSLT

/-- The strict-core rho presentation regarded as an iGSLT object. -/
def rhoExecutionProfile : ExecutionProfile rhoValidatedLanguageDef where
  relationModes := []
  admitted :=
    { lang := rhoCalc
      admitted := rhoCalc_executionAdmissionErrors_eq_nil }
  exactLanguage := rfl

/-- The strict-core rho presentation regarded as an iGSLT object, using the
empty relation-mode profile admitted by its exact authored definition. -/
def rhoIGSLT : IGSLT :=
  ⟨rhoInteractivePresentation, rhoExecutionProfile⟩

end Mettapedia.GSLT.LanguageDef
