import Mettapedia.GSLT.Core.Composition
import Mettapedia.GSLT.LanguageDef.CalculusAsLanguage
import Mettapedia.GSLT.LanguageDef.EquationSemantics
import Mettapedia.OSLF.Framework.TypeSynthesis

/-!
# Combining a language and its proof calculus inside one GSLT

`LanguageDef` supplies authored term syntax, equations, and rewrites.  An
admitted proof calculus supplies a second GSLT whose terms are proof-obligation
lists and whose rewrites are backward rule applications.  This module combines
those two theories with the canonical `GSLT.disjointSum` construction.

The object-language half is not allowed to forget authored equations.  A
`ReductionRespectsEquations` witness states the two compatibility laws required
by `GSLT`; `of_no_equations` derives the witness for the common exact-syntax
case.  Languages with nonempty equations must prove the real compatibility
law rather than silently receiving syntactic equality.

The result has one carrier, one equation relation, and one rewrite relation.
Each summand embeds faithfully and no reduction crosses between them.  This is
the conservative coproduct totalization.  An extension whose two components
communicate should instead use `GSLT.interactingSum` with explicit interaction
laws.
-/

namespace Mettapedia.GSLT.LanguageDef.TotalGSLT

open Mettapedia.GSLT
open Mettapedia.OSLF.MeTTaIL.Syntax
open Mettapedia.OSLF.MeTTaIL.Engine
open Mettapedia.OSLF.MeTTaIL.ContextualStep
open Mettapedia.OSLF.Framework.TypeSynthesis
open Mettapedia.GSLT.LanguageDef.EquationSemantics
open Mettapedia.GSLT.LanguageDef.InferenceChecker
open Mettapedia.GSLT.LanguageDef.CalculusAsLanguage

/-! ## A five-field language as a GSLT -/

/-- The two laws needed for authored reduction under a relation environment to
descend through the equivalence generated by authored equations. -/
structure ReductionRespectsEquationsUsing
    (relations : RelationEnv) (language : LanguageDef) : Prop where
  source : ∀ {term term' result},
    EquationEquiv (engineBasePremises relations) language term term' →
      langReducesUsing relations language term result →
        ∃ result', langReducesUsing relations language term' result' ∧
          EquationEquiv (engineBasePremises relations) language
            result result'
  target : ∀ {term result result'},
    langReducesUsing relations language term result →
      EquationEquiv (engineBasePremises relations) language
        result result' →
      langReducesUsing relations language term result'

namespace ReductionRespectsEquationsUsing

/-- With no authored equations, reduction compatibility follows because the
generated equation relation is exactly syntactic equality. -/
def of_no_equations (relations : RelationEnv) {language : LanguageDef}
    (empty : language.equations = []) :
    ReductionRespectsEquationsUsing relations language where
  source := by
    intro term term' result equivalent reduction
    have equal :=
      (equationEquiv_iff_eq_of_no_generators empty term term').mp equivalent
    subst term'
    exact ⟨result, reduction, Relation.EqvGen.refl result⟩
  target := by
    intro term result result' reduction equivalent
    have equal :=
      (equationEquiv_iff_eq_of_no_generators empty result result').mp equivalent
    subst result'
    exact reduction

end ReductionRespectsEquationsUsing

/-- The common closed-world specialization with no external relation rows. -/
abbrev ReductionRespectsEquations (language : LanguageDef) :=
  ReductionRespectsEquationsUsing RelationEnv.empty language

namespace ReductionRespectsEquations

/-- Empty-equation compatibility for the closed relation environment. -/
def of_no_equations {language : LanguageDef}
    (empty : language.equations = []) : ReductionRespectsEquations language :=
  ReductionRespectsEquationsUsing.of_no_equations RelationEnv.empty empty

end ReductionRespectsEquations

/-- The GSLT denoted by a five-field language in a specific relation
environment.  This is required for languages whose rewrite premises query
authored logic declarations. -/
def languageGSLTUsing (relations : RelationEnv) (language : LanguageDef)
    (laws : ReductionRespectsEquationsUsing relations language) : GSLT where
  Term := Pattern
  equations := equationSetoid (engineBasePremises relations) language
  rewrites := langReducesUsing relations language
  rewrites_resp_left := laws.source
  rewrites_resp_right := laws.target

@[simp] theorem languageGSLTUsing_step (relations : RelationEnv)
    (language : LanguageDef)
    (laws : ReductionRespectsEquationsUsing relations language)
    (source target : Pattern) :
    (languageGSLTUsing relations language laws).Step source target ↔
      langReducesUsing relations language source target :=
  Iff.rfl

@[simp] theorem languageGSLTUsing_equiv (relations : RelationEnv)
    (language : LanguageDef)
    (laws : ReductionRespectsEquationsUsing relations language)
    (source target : Pattern) :
    (languageGSLTUsing relations language laws).Equiv source target ↔
      EquationEquiv (engineBasePremises relations) language source target :=
  Iff.rfl

/-- The GSLT denoted by a five-field language whose rewrites respect its
authored equation theory. -/
def languageGSLT (language : LanguageDef)
    (laws : ReductionRespectsEquations language) : GSLT :=
  languageGSLTUsing RelationEnv.empty language laws

@[simp] theorem languageGSLT_step (language : LanguageDef)
    (laws : ReductionRespectsEquations language) (source target : Pattern) :
    (languageGSLT language laws).Step source target ↔
      langReducesUsing RelationEnv.empty language source target :=
  Iff.rfl

@[simp] theorem languageGSLT_equiv (language : LanguageDef)
    (laws : ReductionRespectsEquations language) (source target : Pattern) :
    (languageGSLT language laws).Equiv source target ↔
      EquationEquiv (engineBasePremises RelationEnv.empty) language source target :=
  Iff.rfl

/-- In the empty-equation case, the GSLT equivalence is exactly syntactic
equality. -/
theorem languageGSLT_equiv_iff_eq_of_no_equations
    {language : LanguageDef} (empty : language.equations = [])
    (source target : Pattern) :
    (languageGSLT language
        (ReductionRespectsEquations.of_no_equations empty)).Equiv source target ↔
      source = target :=
  equationEquiv_iff_eq_of_no_generators empty source target

/-! ## Canonical conservative combination -/

/-- Inject a language term into a conservative sum. -/
abbrev inLanguage {languageTheory calculusTheory : GSLT}
    (term : languageTheory.Term) :
    (GSLT.disjointSum languageTheory calculusTheory).Term :=
  Sum.inl term

/-- Inject a proof-search state into a conservative sum. -/
abbrev inCalculus {languageTheory calculusTheory : GSLT}
    (term : calculusTheory.Term) :
    (GSLT.disjointSum languageTheory calculusTheory).Term :=
  Sum.inr term

@[simp] theorem disjointSum_left_step (languageTheory calculusTheory : GSLT)
    (source target : languageTheory.Term) :
    (GSLT.disjointSum languageTheory calculusTheory).Step
        (inLanguage source) (inLanguage target) ↔
      languageTheory.Step source target :=
  (GSLT.disjointSumLeft languageTheory calculusTheory).step_iff source target

@[simp] theorem disjointSum_right_step (languageTheory calculusTheory : GSLT)
    (source target : calculusTheory.Term) :
    (GSLT.disjointSum languageTheory calculusTheory).Step
        (inCalculus source) (inCalculus target) ↔
      calculusTheory.Step source target :=
  (GSLT.disjointSumRight languageTheory calculusTheory).step_iff source target

theorem no_left_to_right (languageTheory calculusTheory : GSLT)
    (source : languageTheory.Term) (target : calculusTheory.Term) :
    ¬ (GSLT.disjointSum languageTheory calculusTheory).Step
        (inLanguage source) (inCalculus target) := by
  intro step
  cases step

theorem no_right_to_left (languageTheory calculusTheory : GSLT)
    (source : calculusTheory.Term) (target : languageTheory.Term) :
    ¬ (GSLT.disjointSum languageTheory calculusTheory).Step
        (inCalculus source) (inLanguage target) := by
  intro step
  cases step

private theorem multiStep_stays_right {languageTheory calculusTheory : GSLT}
    {source target : (GSLT.disjointSum languageTheory calculusTheory).Term}
    (steps : (GSLT.disjointSum languageTheory calculusTheory).MultiStep source target)
    (start : calculusTheory.Term) (shape : source = inCalculus start) :
    ∃ finish : calculusTheory.Term,
      target = inCalculus finish ∧ calculusTheory.MultiStep start finish := by
  let motive : ∀ (first second :
      (GSLT.disjointSum languageTheory calculusTheory).Term),
      (GSLT.disjointSum languageTheory calculusTheory).MultiStep first second → Prop :=
    fun first second _ => ∀ (initial : calculusTheory.Term),
      first = inCalculus initial →
        ∃ finish : calculusTheory.Term,
          second = inCalculus finish ∧
            calculusTheory.MultiStep initial finish
  refine GSLT.MultiStep.rec (motive := motive) ?_ ?_ steps start shape
  · intro term initial equal
    subst equal
    exact ⟨initial, rfl, .refl initial⟩
  · intro first _ _ head _ inductionHypothesis initial equal
    subst equal
    cases head with
    | right reduction =>
        obtain ⟨finish, finishShape, rest⟩ := inductionHypothesis _ rfl
        exact ⟨finish, finishShape, .step reduction rest⟩

private theorem right_multiStep_of {languageTheory calculusTheory : GSLT}
    {source target : calculusTheory.Term}
    (steps : calculusTheory.MultiStep source target) :
    (GSLT.disjointSum languageTheory calculusTheory).MultiStep
      (inCalculus source) (inCalculus target) := by
  induction steps with
  | refl term => exact .refl (inCalculus term)
  | step reduction _ inductionHypothesis =>
      exact .step (.right reduction) inductionHypothesis

@[simp] theorem disjointSum_right_multiStep
    (languageTheory calculusTheory : GSLT)
    (source target : calculusTheory.Term) :
    (GSLT.disjointSum languageTheory calculusTheory).MultiStep
        (inCalculus source) (inCalculus target) ↔
      calculusTheory.MultiStep source target := by
  constructor
  · intro steps
    obtain ⟨finish, shape, componentSteps⟩ :=
      multiStep_stays_right steps source rfl
    cases shape
    exact componentSteps
  · exact right_multiStep_of

/-! ## A validated language/calculus definition as one GSLT -/

/-- A validated language and calculus, conservatively combined as one GSLT. -/
def combinedGSLT (checked : ValidatedCalculusLanguageDef)
    (laws : ReductionRespectsEquations checked.1.toLanguageDef) : GSLT :=
  GSLT.disjointSum (languageGSLT checked.1.toLanguageDef laws)
    (proofSearchGSLT checked)

@[simp] theorem combinedGSLT_language_step (checked : ValidatedCalculusLanguageDef)
    (laws : ReductionRespectsEquations checked.1.toLanguageDef)
    (source target : Pattern) :
    (combinedGSLT checked laws).Step
        (inLanguage source) (inLanguage target) ↔
      langReducesUsing RelationEnv.empty checked.1.toLanguageDef source target := by
  exact (disjointSum_left_step
    (languageGSLT checked.1.toLanguageDef laws) (proofSearchGSLT checked)
    source target).trans (languageGSLT_step _ _ _ _)

@[simp] theorem combinedGSLT_calculus_step (checked : ValidatedCalculusLanguageDef)
    (laws : ReductionRespectsEquations checked.1.toLanguageDef)
    (source target : GoalState) :
    (combinedGSLT checked laws).Step
        (inCalculus source) (inCalculus target) ↔
      (proofSearchGSLT checked).Step source target := by
  unfold combinedGSLT
  exact disjointSum_right_step
    (languageGSLT checked.1.toLanguageDef laws) (proofSearchGSLT checked)
    source target

theorem combinedGSLT_no_crossing (checked : ValidatedCalculusLanguageDef)
    (laws : ReductionRespectsEquations checked.1.toLanguageDef)
    (pattern : Pattern) (state : GoalState) :
    ¬ (combinedGSLT checked laws).Step
        (inLanguage pattern) (inCalculus state) ∧
      ¬ (combinedGSLT checked laws).Step
        (inCalculus state) (inLanguage pattern) := by
  unfold combinedGSLT
  exact ⟨no_left_to_right
      (languageGSLT checked.1.toLanguageDef laws) (proofSearchGSLT checked)
      pattern state,
    no_right_to_left
      (languageGSLT checked.1.toLanguageDef laws) (proofSearchGSLT checked)
      state pattern⟩

/-- Derivability is reduction to the empty obligation state inside the
combined GSLT. -/
theorem derivability_iff_combinedGSLT (checked : ValidatedCalculusLanguageDef)
    (laws : ReductionRespectsEquations checked.1.toLanguageDef)
    (goals : GoalState) :
    Nonempty (DerivationList checked goals) ↔
      (combinedGSLT checked laws).MultiStep
        (inCalculus goals) (inCalculus []) := by
  unfold combinedGSLT
  rw [disjointSum_right_multiStep]
  exact derivationList_nonempty_iff_proofSearch checked goals

end Mettapedia.GSLT.LanguageDef.TotalGSLT
