import Mettapedia.GSLT.LanguageDef.WaltersZantemaDAMultiplication

/-!
# Total certified ground normalization for Walters--Zantema DA

The operation-specific strategies already establish the computational content
of paper rules 1--10.  This module composes them into one total strategy for
every well-formed ground term in the generated radix-parametric vocabulary.
It proves existence and uniqueness of the resulting canonical numeral without
claiming strategy-independent RPO termination.
-/

namespace Mettapedia.GSLT.LanguageDef.WaltersZantemaDA

/-- Radix three and radix ten are generated by the same schema used for the
primary radix-two qualification instance. -/
def radixThree : Schema := ⟨3, by omega⟩

def radixTen : Schema := ⟨10, by omega⟩

/-- Every finite instance generated from the DA schema is premise-free. -/
theorem generated_premise_free (schema : Schema) :
    ∀ generated ∈ (language schema).rewrites, generated.premises = [] := by
  intro generated member
  change generated ∈ (authoredRules schema).map AuthoredRule.toRewriteRule at member
  obtain ⟨authored, _, rfl⟩ := List.mem_map.mp member
  rfl

theorem radixThree_rule_count : (language radixThree).rewrites.length = 32 := by
  simpa [language, radixThree] using rewrites_length radixThree

theorem radixTen_rule_count : (language radixTen).rewrites.length = 235 := by
  simpa [language, radixTen] using rewrites_length radixTen

theorem radixThree_premise_free :
    ∀ generated ∈ (language radixThree).rewrites,
      generated.premises = [] :=
  generated_premise_free radixThree

theorem radixTen_premise_free :
    ∀ generated ∈ (language radixTen).rewrites,
      generated.premises = [] :=
  generated_premise_free radixTen

namespace MultiStep

theorem mapMulRight {schema : Schema} (left : SemanticTerm)
    {source target : SemanticTerm} (steps : MultiStep schema source target) :
    MultiStep schema (.mul left source) (.mul left target) := by
  induction steps with
  | refl => exact .refl
  | tail previous finalStep inductionHypothesis =>
      exact .tail inductionHypothesis (.mulRight finalStep)

end MultiStep

/-- Closed, constructor-correct terms of one generated finite DA instance.
Digit and star indices carry the same finite-range obligation as the authored
constructor and rule families. -/
inductive Ground (schema : Schema) : SemanticTerm → Prop where
  | empty : Ground schema .empty
  | digit {index body} :
      index < schema.radix → Ground schema body →
      Ground schema (.digit index body)
  | add {left right} :
      Ground schema left → Ground schema right →
      Ground schema (.add left right)
  | mul {left right} :
      Ground schema left → Ground schema right →
      Ground schema (.mul left right)
  | succ {body} : Ground schema body → Ground schema (.succ body)
  | star {index body} :
      index < schema.radix → Ground schema body →
      Ground schema (.star index body)

theorem digitNumeral_reach (schema : Schema) {index : Nat}
    (indexRange : index < schema.radix) (number : Nat) :
    MultiStep schema (.digit index (encodeTerm schema number))
      (encodeTerm schema (schema.radix * number + index)) := by
  have digitsRange : DigitsInRange schema
      (index :: encodeDigits schema number) := by
    intro digit member
    rcases List.mem_cons.mp member with rfl | member
    · exact indexRange
    · exact (encodeDigits_canonical schema number).1 digit member
  have path := normalizeDigits_reach schema
    (index :: encodeDigits schema number)
  have canonical := normalizeDigits_eq_encodeDigits schema digitsRange
  have decoded :
      decodeDigits schema (index :: encodeDigits schema number) =
        schema.radix * number + index := by
    have encoded := decodeDigits_encodeDigits schema number
    change Nat.ofDigits schema.radix (encodeDigits schema number) =
      number at encoded
    change index + schema.radix *
      Nat.ofDigits schema.radix (encodeDigits schema number) =
        schema.radix * number + index
    rw [encoded, Nat.add_comm]
  simpa [encodeTerm, termOfDigits, canonical, decoded] using path

theorem incrementDigits_denote (schema : Schema) {digits : List Nat}
    (inRange : DigitsInRange schema digits) :
    decodeDigits schema (incrementDigits schema digits) =
      decodeDigits schema digits + 1 := by
  have preserved := multiStep_sound
    (incrementDigits_reach schema inRange) (fun _ => 0)
  simpa [SemanticTerm.denote, termOfDigits_denote] using preserved.symm

theorem successorNumeral_reach (schema : Schema) (number : Nat) :
    MultiStep schema (.succ (encodeTerm schema number))
      (encodeTerm schema (number + 1)) := by
  have sourceRange := (encodeDigits_canonical schema number).1
  have increment := incrementDigits_reach schema sourceRange
  have incrementRange := incrementDigits_in_range schema sourceRange
  have normalization := normalizeDigits_reach schema
    (incrementDigits schema (encodeDigits schema number))
  have canonical := normalizeDigits_eq_encodeDigits schema incrementRange
  have denotation := incrementDigits_denote schema sourceRange
  simpa [encodeTerm, canonical, denotation, decodeDigits_encodeDigits] using
    increment.trans normalization

theorem starNumeral_reach (schema : Schema) {index : Nat}
    (indexRange : index < schema.radix) (number : Nat) :
    MultiStep schema (.star index (encodeTerm schema number))
      (encodeTerm schema (index * number)) := by
  simpa [encodeTerm, decodeDigits_encodeDigits] using
    starDigits_reach schema indexRange
      (encodeDigits_canonical schema number).1

/-- The certified evaluator for the complete ground DA vocabulary.  The
result is a reduction witness to the numeral denoting the source term, not a
host-language computation substituted for authored rewriting. -/
theorem ground_normalizes (schema : Schema) {source : SemanticTerm}
    (ground : Ground schema source) :
    MultiStep schema source
      (encodeTerm schema (source.denote schema (fun _ => 0))) := by
  induction ground with
  | empty =>
      have zeroEncoding : encodeTerm schema 0 = .empty := by
        simp [encodeTerm, encodeDigits, Nat.digits_zero, termOfDigits]
      simpa [SemanticTerm.denote, zeroEncoding] using
        (Relation.ReflTransGen.refl : MultiStep schema .empty .empty)
  | @digit index body indexRange bodyGround inductionHypothesis =>
      exact (MultiStep.mapDigit index inductionHypothesis).trans (by
        simpa [SemanticTerm.denote] using
          digitNumeral_reach schema indexRange
            (body.denote schema (fun _ => 0)))
  | @add left right leftGround rightGround leftInduction rightInduction =>
      have normalizeLeft := MultiStep.mapAddLeft right leftInduction
      have normalizeRight := MultiStep.mapAddRight
        (encodeTerm schema (left.denote schema (fun _ => 0))) rightInduction
      have operation := (encoded_addition_graph schema
        (left.denote schema (fun _ => 0))
        (right.denote schema (fun _ => 0))
        (left.denote schema (fun _ => 0) +
          right.denote schema (fun _ => 0))).2 rfl
      simpa [SemanticTerm.denote] using
        (normalizeLeft.trans normalizeRight).trans operation
  | @mul left right leftGround rightGround leftInduction rightInduction =>
      have normalizeLeft := MultiStep.mapMulLeft right leftInduction
      have normalizeRight := MultiStep.mapMulRight
        (encodeTerm schema (left.denote schema (fun _ => 0))) rightInduction
      have operation := (encoded_multiplication_graph schema
        (left.denote schema (fun _ => 0))
        (right.denote schema (fun _ => 0))
        (left.denote schema (fun _ => 0) *
          right.denote schema (fun _ => 0))).2 rfl
      simpa [SemanticTerm.denote] using
        (normalizeLeft.trans normalizeRight).trans operation
  | @succ body bodyGround inductionHypothesis =>
      exact (MultiStep.mapSucc inductionHypothesis).trans (by
        simpa [SemanticTerm.denote] using successorNumeral_reach schema
          (body.denote schema (fun _ => 0)))
  | @star index body indexRange bodyGround inductionHypothesis =>
      exact (MultiStep.mapStar index inductionHypothesis).trans (by
        simpa [SemanticTerm.denote] using
          starNumeral_reach schema indexRange
            (body.denote schema (fun _ => 0)))

/-- Soundness makes canonical results unique even if another reduction
strategy is used. -/
theorem canonical_result_unique (schema : Schema) {source : SemanticTerm}
    {first second : Nat}
    (firstPath : MultiStep schema source (encodeTerm schema first))
    (secondPath : MultiStep schema source (encodeTerm schema second)) :
    first = second := by
  have firstSound := multiStep_sound firstPath (fun _ => 0)
  have secondSound := multiStep_sound secondPath (fun _ => 0)
  rw [encodeTerm_denote] at firstSound secondSound
  exact firstSound.symm.trans secondSound

private def nestedExample : SemanticTerm :=
  .mul (.add (.digit 1 .empty) (.digit 1 .empty))
    (.succ (.digit 1 .empty))

private theorem nestedExample_ground : Ground radixTwo nestedExample := by
  exact .mul
    (.add (.digit (by simp [radixTwo]) .empty)
      (.digit (by simp [radixTwo]) .empty))
    (.succ (.digit (by simp [radixTwo]) .empty))

/-- Positive whole-vocabulary control: nested addition, successor, and
multiplication normalize through the authored DA rules. -/
theorem radixTwo_nested_example_reaches_four :
    MultiStep radixTwo nestedExample (encodeTerm radixTwo 4) := by
  simpa [nestedExample, SemanticTerm.denote, radixTwo] using
    ground_normalizes radixTwo nestedExample_ground

/-- Negative whole-vocabulary control: the same term cannot normalize to a
different canonical result. -/
theorem radixTwo_nested_example_does_not_reach_three :
    ¬ MultiStep radixTwo nestedExample (encodeTerm radixTwo 3) := by
  intro invented
  have unique := canonical_result_unique radixTwo
    radixTwo_nested_example_reaches_four invented
  omega

#print axioms generated_premise_free
#print axioms ground_normalizes
#print axioms canonical_result_unique
#print axioms radixTwo_nested_example_does_not_reach_three

end Mettapedia.GSLT.LanguageDef.WaltersZantemaDA
