import Mettapedia.GSLT.LanguageDef.MeTTaILPatternMatrixCompilation
import Mettapedia.Languages.MeTTa.PeTTa.MainlineCallGuardCompileCodec
import Mettapedia.Languages.MeTTa.PeTTa.MainlineCallGuardCompileNTT
import Mettapedia.OSLF.MeTTaIL.InterpretedContextualStep

/-!
# Source-derived decision program for the PeTTa call-guard language

The cold call-guard `LanguageDef` is compiled by the generic ordered
pattern-matrix compiler.  The residual decision program carries exact source
rewrite indices.  It performs only conservative constructor dispatch; the
canonical MeTTaIL matcher, premise evaluator, and right-hand-side
instantiator remain the rule continuation.

The main theorem identifies execution of the residual program with the least
contextual reduction generated by the authored call-guard rules.  Forward
coverage and reverse no-invention are then consequences of one equality,
rather than a comparison against a separately authored case table.
-/

set_option autoImplicit false

namespace Mettapedia.Languages.MeTTa.PeTTa.MainlineCallGuardPatternMatrixCompilation

open Mettapedia.OSLF.MeTTaIL.Syntax
open Mettapedia.OSLF.MeTTaIL.ContextualStep
open Mettapedia.OSLF.MeTTaIL.InterpretedContextualStep
open Mettapedia.OSLF.MeTTaIL.Engine
open Mettapedia.OSLF.Framework
open Mettapedia.Languages.MeTTa.PeTTa.MainlineCallGuardOperational
open Mettapedia.Languages.MeTTa.PeTTa.MainlineCallGuardCompileCodec
open Mettapedia.Languages.MeTTa.PeTTa.MainlineCallGuardCompileNTT

namespace SourceCompiler

export Mettapedia.GSLT.LanguageDef.MeTTaILPatternMatrixCompilation.Matrix
  (Head RuleOccurrence ruleAt lowerSubject syntacticOccurrenceAttempt
    ofLanguage compileLanguage compileLanguage_evalAll_eq_rewriteAt
    compileLanguage_candidate_rules_exact)

end SourceCompiler

/-- The independently authored and validated source language. -/
abbrev sourceLanguage : LanguageDef := coldSource.language

/-- Exact source occurrence indices carried by the residual program. -/
abbrev SourceOccurrence := SourceCompiler.RuleOccurrence sourceLanguage

/-- The total generic compilation of the fifteen authored call-guard rows. -/
def decisionTree := SourceCompiler.compileLanguage sourceLanguage

/-- Non-contextual call-guard premise semantics.  It exposes only the narrow
relations authored by the operational language. -/
def premiseBase : BasePremiseEvaluator :=
  engineBasePremises relationEnv

/-- Execute the residual decision program at one contextual depth. -/
def compiledReducts (recursiveFuel : Nat) (source : Pattern) : List Pattern :=
  decisionTree.evalAll
    (SourceCompiler.syntacticOccurrenceAttempt premiseBase sourceLanguage
      (Mettapedia.OSLF.MeTTaIL.InterpretedContextualStep.rewriteAt
        .syntactic premiseBase sourceLanguage recursiveFuel)
      source)
    [SourceCompiler.lowerSubject source]

/-- The residual program is exactly the executable least contextual semantics
of the authored cold call-guard language. -/
theorem compiledReducts_eq_contextualRewriteAt
    (recursiveFuel : Nat) (source : Pattern) :
    compiledReducts recursiveFuel source =
      Mettapedia.OSLF.MeTTaIL.ContextualStep.rewriteAt
        premiseBase sourceLanguage (recursiveFuel + 1) source := by
  calc
    compiledReducts recursiveFuel source =
        Mettapedia.OSLF.MeTTaIL.InterpretedContextualStep.rewriteAt
          .syntactic premiseBase sourceLanguage (recursiveFuel + 1) source :=
      SourceCompiler.compileLanguage_evalAll_eq_rewriteAt
        premiseBase sourceLanguage recursiveFuel source
    _ = Mettapedia.OSLF.MeTTaIL.ContextualStep.rewriteAt
          premiseBase sourceLanguage (recursiveFuel + 1) source :=
      Mettapedia.OSLF.MeTTaIL.InterpretedContextualStep.rewriteAt_syntactic_eq_contextual
        premiseBase sourceLanguage (recursiveFuel + 1) source

/-- At root depth, residual execution is exactly the established authored
premise-aware executor.  This is an equality of complete ordered result lists,
not merely an agreement on whether some result exists. -/
theorem compiledReducts_zero_eq_executor (source : Pattern) :
    compiledReducts 0 source =
      rewriteStepWithPremisesUsing relationEnv language source := by
  rw [compiledReducts_eq_contextualRewriteAt]
  simpa [premiseBase, sourceLanguage, coldSource] using
    (Mettapedia.OSLF.MeTTaIL.ContextualStep.rewriteAt_one_eq_rewriteStepWithPremisesUsing
        relationEnv language source)

/-- Exact bounded relational reading of residual execution. -/
theorem mem_compiledReducts_iff_stepAt
    (recursiveFuel : Nat) (source target : Pattern) :
    target ∈ compiledReducts recursiveFuel source ↔
      StepAt premiseBase sourceLanguage (recursiveFuel + 1) source target := by
  rw [compiledReducts_eq_contextualRewriteAt]
  exact mem_rewriteAt_iff_stepAt

/-- Reverse adequacy: the residual program cannot invent a call-guard
transition absent from the authored `LanguageDef`. -/
theorem compiledReducts_no_invention
    (recursiveFuel : Nat) {source target : Pattern}
    (member : target ∈ compiledReducts recursiveFuel source) :
    TypeSynthesis.langReducesUsing relationEnv sourceLanguage source target := by
  rw [compiledReducts_eq_contextualRewriteAt] at member
  unfold TypeSynthesis.langReducesUsing
  exact
    Mettapedia.OSLF.MeTTaIL.ContextualStep.exists_mem_rewriteAt_iff_step.mp
      ⟨recursiveFuel + 1, by simpa [premiseBase] using member⟩

/-- Forward adequacy: every authored least-contextual transition appears in
the residual program at some finite contextual depth. -/
theorem language_step_covered
    {source target : Pattern}
    (step : TypeSynthesis.langReducesUsing
      relationEnv sourceLanguage source target) :
    exists recursiveFuel, target ∈ compiledReducts recursiveFuel source := by
  have contextual : Step premiseBase sourceLanguage source target := by
    simpa [TypeSynthesis.langReducesUsing, premiseBase]
      using step
  obtain ⟨fuel, member⟩ :=
    Mettapedia.OSLF.MeTTaIL.ContextualStep.exists_mem_rewriteAt_iff_step.mpr
      contextual
  cases fuel with
  | zero =>
      simp [Mettapedia.OSLF.MeTTaIL.ContextualStep.rewriteAt] at member
  | succ recursiveFuel =>
      refine ⟨recursiveFuel, ?_⟩
      rw [compiledReducts_eq_contextualRewriteAt]
      simpa [Nat.succ_eq_add_one] using member

/-- The independent typed cold micro-machine is therefore covered by the
same source-derived decision program. -/
theorem microMachine_step_covered
    {source target : CompileLanguageControl}
    (step : compileLanguageStep? source = some target) :
    exists recursiveFuel,
      encodeCompileLanguageControl target ∈
        compiledReducts recursiveFuel (encodeCompileLanguageControl source) := by
  apply language_step_covered
  simpa [sourceLanguage, coldSource] using language_step_complete step

/-- On the canonical cold-state image, the first residual reduct is exactly
the independently defined micro-machine successor.  This is the deterministic
observation consumed by the generated native cold compiler; the stronger
`compiledReducts_eq_contextualRewriteAt` theorem continues to retain the full
nondeterministic source semantics for arbitrary terms. -/
theorem compiled_first_eq_compileLanguageStep (source : CompileLanguageControl) :
    (compiledReducts 0 (encodeCompileLanguageControl source)).head? =
      (compileLanguageStep? source).map encodeCompileLanguageControl := by
  cases stepEquation : compileLanguageStep? source with
  | none =>
      have noMember : forall wire,
          wire ∉ compiledReducts 0 (encodeCompileLanguageControl source) := by
        intro wire member
        have sourceStep := compiledReducts_no_invention 0 member
        have canonicalStep :
            TypeSynthesis.langReducesUsing relationEnv language
              (encodeCompileLanguageControl source) wire := by
          simpa [sourceLanguage, coldSource] using sourceStep
        obtain ⟨target, targetStep, _wireExact⟩ :=
          (language_step_iff_compileLanguageStep source wire).mp canonicalStep
        rw [stepEquation] at targetStep
        contradiction
      have empty :
          compiledReducts 0 (encodeCompileLanguageControl source) = [] :=
        List.eq_nil_iff_forall_not_mem.mpr noMember
      simp [empty]
  | some target =>
      have sourceStep :
          TypeSynthesis.langReducesUsing relationEnv language
            (encodeCompileLanguageControl source)
            (encodeCompileLanguageControl target) :=
        language_step_complete stepEquation
      have targetMember :
          encodeCompileLanguageControl target ∈
            compiledReducts 0 (encodeCompileLanguageControl source) := by
        rw [compiledReducts_zero_eq_executor]
        exact (language_step_iff_mem_executor _ _).mp sourceStep
      cases reductsEquation :
          compiledReducts 0 (encodeCompileLanguageControl source) with
      | nil =>
          simp [reductsEquation] at targetMember
      | cons first rest =>
          have firstMember :
              first ∈ compiledReducts 0 (encodeCompileLanguageControl source) := by
            simp [reductsEquation]
          have firstSourceStep := compiledReducts_no_invention 0 firstMember
          have firstCanonicalStep :
              TypeSynthesis.langReducesUsing relationEnv language
                (encodeCompileLanguageControl source) first := by
            simpa [sourceLanguage, coldSource] using firstSourceStep
          obtain ⟨firstTarget, firstStep, firstExact⟩ :=
            (language_step_iff_compileLanguageStep source first).mp
              firstCanonicalStep
          have sameTarget : firstTarget = target := by
            rw [stepEquation] at firstStep
            exact Option.some.inj firstStep.symm
          subst firstTarget
          simp [firstExact]

/-- Negative form of no-invention, useful for mutation and hostile-input
tests. -/
theorem rejected_by_source_rejected_by_compiled
    (recursiveFuel : Nat) {source target : Pattern}
    (rejected : Not
      (TypeSynthesis.langReducesUsing
        relationEnv sourceLanguage source target)) :
    target ∉ compiledReducts recursiveFuel source := by
  intro member
  exact rejected (compiledReducts_no_invention recursiveFuel member)

/-! ## Exact source indexing and NTT selection -/

/-- Candidate selection returns exact authored occurrence indices, not copied
rules or names. -/
def candidateOccurrences (source : Pattern) : List SourceOccurrence :=
  decisionTree.evalAll (fun occurrence => [occurrence])
    [SourceCompiler.lowerSubject source]

/-- Candidate occurrence order and multiplicity are exactly those of the
independent matrix scanner. -/
theorem candidateOccurrences_exact (source : Pattern) :
    candidateOccurrences source =
      Mettapedia.GSLT.LanguageDef.OrderedPatternMatrixCompilation.runMatrixAll
        (fun occurrence => [occurrence])
        (SourceCompiler.ofLanguage sourceLanguage)
        [SourceCompiler.lowerSubject source] :=
  SourceCompiler.compileLanguage_candidate_rules_exact sourceLanguage source

/-- Every occurrence carried by the decision program has the source index
type consumed by the selected native-type demand. -/
def occurrenceTyping
    (occurrence : SourceOccurrence)
    (code : CarrierUniverseSignature.Code) :
    ProfiledRewriteOccurrence coldSource :=
  profiledRoot occurrence code

/-- The complete demand contains the star endpoint for every exact source
occurrence. -/
theorem occurrence_star_selected (occurrence : SourceOccurrence) :
    occurrenceTyping occurrence .star ∈ selectedOccurrences := by
  rw [selectedOccurrences]
  rw [List.mem_flatMap]
  exact ⟨occurrence, List.mem_finRange occurrence, by
    simp [occurrenceTyping]⟩

/-- The complete demand also contains the box endpoint for every exact source
occurrence. -/
theorem occurrence_box_selected (occurrence : SourceOccurrence) :
    occurrenceTyping occurrence .box ∈ selectedOccurrences := by
  rw [selectedOccurrences]
  rw [List.mem_flatMap]
  exact ⟨occurrence, List.mem_finRange occurrence, by
    simp [occurrenceTyping]⟩

/-! ## Positive and negative controls -/

private def finishSource : CompileLanguageControl :=
  .running ⟨0⟩ 0 "demo" 0 [] []

private def finishTarget : CompileLanguageControl :=
  .halted (.compiled ⟨⟨0⟩, 0, "demo", 0, []⟩)

/-- A concrete independent micro-machine transition is realized by residual
execution. -/
example :
    exists recursiveFuel,
      encodeCompileLanguageControl finishTarget ∈
        compiledReducts recursiveFuel
          (encodeCompileLanguageControl finishSource) := by
  apply microMachine_step_covered
  rfl

/-- A target rejected by the authored semantics cannot be fabricated by any
residual execution depth. -/
example (recursiveFuel : Nat) (source target : Pattern)
    (rejected : Not
      (TypeSynthesis.langReducesUsing
        relationEnv sourceLanguage source target)) :
    target ∉ compiledReducts recursiveFuel source :=
  rejected_by_source_rejected_by_compiled recursiveFuel rejected

#print axioms compiledReducts_eq_contextualRewriteAt
#print axioms mem_compiledReducts_iff_stepAt
#print axioms compiledReducts_no_invention
#print axioms language_step_covered
#print axioms microMachine_step_covered
#print axioms compiledReducts_zero_eq_executor
#print axioms compiled_first_eq_compileLanguageStep

end Mettapedia.Languages.MeTTa.PeTTa.MainlineCallGuardPatternMatrixCompilation
