import Mettapedia.GSLT.Weighting.Keys
import Mettapedia.GSLT.Weighting.FormulaKeys
import Mettapedia.GSLT.Weighting.WeightTheory
import Mettapedia.GSLT.Weighting.DynamicWeights
import Mettapedia.GSLT.Weighting.Multiplicity
import Mettapedia.GSLT.Weighting.StochasticPi
import Mettapedia.GSLT.Weighting.RateGenerator
import Mettapedia.GSLT.Weighting.QuantumJump
import Mettapedia.GSLT.Weighting.ConfigurationChain

/-! Axiom audit of the weighting modules. -/

#print axioms Mettapedia.GSLT.Weighting.refines_iff_mem_Iic
#print axioms Mettapedia.GSLT.Weighting.Partition.classify_holds
#print axioms Mettapedia.GSLT.Weighting.Partition.classify_eq_iff
#print axioms Mettapedia.GSLT.Weighting.Partition.classify_unique
#print axioms Mettapedia.GSLT.Weighting.Partition.of_classify
#print axioms Mettapedia.GSLT.Weighting.Partition.classify_eq_of_equiv
#print axioms Mettapedia.GSLT.Weighting.Partition.keys_invariant_of_classify
#print axioms Mettapedia.GSLT.Weighting.complete_partition
#print axioms Mettapedia.GSLT.Weighting.KeyControls.not_exhaustive
#print axioms Mettapedia.GSLT.Weighting.KeyControls.not_exclusive
#print axioms Mettapedia.GSLT.Weighting.KeyControls.completed
#print axioms Mettapedia.GSLT.Weighting.PositiveFormula.holds_all_true
#print axioms Mettapedia.GSLT.Weighting.PositiveFormula.exclusivity_not_positive
#print axioms Mettapedia.GSLT.Weighting.FormulaKeys.structural_iff_modalDepth_eq_zero
#print axioms Mettapedia.GSLT.Weighting.FormulaKeys.admissible_of_structural
#print axioms Mettapedia.GSLT.Weighting.FormulaKeys.dia_not_admissible
#print axioms Mettapedia.GSLT.Weighting.FormulaKeys.stop_ne_quote
#print axioms Mettapedia.GSLT.Weighting.FormulaKeys.stopHeaded_not_invariant
#print axioms Mettapedia.GSLT.Weighting.FormulaKeys.headClassification_not_on_classes
#print axioms Mettapedia.GSLT.Weighting.Augmented.next_of_folds_trivial
#print axioms Mettapedia.GSLT.Weighting.Augmented.geometricFactor_of_trivial
#print axioms Mettapedia.GSLT.Weighting.Augmented.base_step
#print axioms Mettapedia.GSLT.Weighting.Augmented.step_of_event
#print axioms Mettapedia.GSLT.Weighting.KeyMap.reindex_keyOf
#print axioms Mettapedia.GSLT.Weighting.Augmented.propensity_eq_sum
#print axioms Mettapedia.GSLT.Weighting.Augmented.totalPropensity_eq_sum_propensity
#print axioms Mettapedia.GSLT.Weighting.Augmented.redexWeight_of_unfunded
#print axioms Mettapedia.GSLT.Weighting.Augmented.redexWeight_of_funded
#print axioms Mettapedia.GSLT.Weighting.Augmented.totalPropensity_eq_funded
#print axioms Mettapedia.GSLT.Weighting.Augmented.totalPropensity_of_exhausted
#print axioms Mettapedia.GSLT.Weighting.Augmented.coalgebra_sum
#print axioms Mettapedia.GSLT.Weighting.Augmented.interpret_step
#print axioms Mettapedia.GSLT.Weighting.Augmented.interpret_step_sound
#print axioms Mettapedia.GSLT.Weighting.Augmented.unfunded_response_retained
#print axioms Mettapedia.GSLT.Weighting.Augmented.interpret_unfold_add
#print axioms Mettapedia.GSLT.Weighting.Augmented.total_interpret_step
#print axioms Mettapedia.GSLT.Weighting.Augmented.interpret_step_coalgebra
#print axioms Mettapedia.GSLT.Weighting.uniform_next
#print axioms Mettapedia.GSLT.Weighting.uniform_step_iff
#print axioms Mettapedia.GSLT.Weighting.uniform_totalPropensity
#print axioms Mettapedia.GSLT.Weighting.DynamicWeights.aThenB_a
#print axioms Mettapedia.GSLT.Weighting.DynamicWeights.bThenA_a
#print axioms Mettapedia.GSLT.Weighting.DynamicWeights.same_term_two_rates
#print axioms Mettapedia.GSLT.Weighting.DynamicWeights.no_term_rate
#print axioms Mettapedia.GSLT.Weighting.DynamicWeights.common_handler_two_rates
#print axioms Mettapedia.GSLT.Weighting.ResumptionControls.loop_occurrences_distinct
#print axioms Mettapedia.GSLT.Weighting.ResumptionControls.cancelling_events_remain
#print axioms Mettapedia.GSLT.Weighting.ResumptionControls.unfunded_events_remain
#print axioms Mettapedia.GSLT.Weighting.ResumptionControls.uniform_events_counted
#print axioms Mettapedia.GSLT.Weighting.ResumptionControls.context_order_changes_matrix_readout
#print axioms Mettapedia.GSLT.Weighting.Multiplicity.selections_two_equal_messages
#print axioms Mettapedia.GSLT.Weighting.Multiplicity.selections_one_message
#print axioms Mettapedia.GSLT.Weighting.Multiplicity.balanced_iff_detailed
#print axioms Mettapedia.GSLT.Weighting.Multiplicity.balanced_multiplicity_iff
#print axioms Mettapedia.GSLT.Weighting.Multiplicity.balanced_identified_iff
#print axioms Mettapedia.GSLT.Weighting.Multiplicity.poisson_ne_geometric
#print axioms Mettapedia.GSLT.Weighting.StochasticPi.card_channel_redexes
#print axioms Mettapedia.GSLT.Weighting.StochasticPi.propensity_eq_activity
#print axioms Mettapedia.GSLT.Weighting.StochasticPi.card_payload_redexes
#print axioms Mettapedia.GSLT.Weighting.StochasticPi.payload_propensity
#print axioms Mettapedia.GSLT.Weighting.StochasticPi.Strictness.same_activity
#print axioms Mettapedia.GSLT.Weighting.StochasticPi.Strictness.payload_keys_strict
#print axioms Mettapedia.GSLT.Weighting.hasSum_matrix_exp
#print axioms Mettapedia.GSLT.Weighting.exp_mulVec_of_mulVec_eq_smul
#print axioms Mettapedia.GSLT.Weighting.pow_apply_nonneg
#print axioms Mettapedia.GSLT.Weighting.exp_apply_nonneg
#print axioms Mettapedia.GSLT.Weighting.rateKernel_nonneg
#print axioms Mettapedia.GSLT.Weighting.generator_apply_of_ne
#print axioms Mettapedia.GSLT.Weighting.generator_apply_self
#print axioms Mettapedia.GSLT.Weighting.generator_offDiag_nonneg
#print axioms Mettapedia.GSLT.Weighting.generator_row_sum
#print axioms Mettapedia.GSLT.Weighting.generator_mulVec_one
#print axioms Mettapedia.GSLT.Weighting.generator_diag_eq
#print axioms Mettapedia.GSLT.Weighting.generator_congr_offDiag
#print axioms Mettapedia.GSLT.Weighting.generator_selfLoop_irrelevant
#print axioms Mettapedia.GSLT.Weighting.generator_diag_eq_neg_totalRate_iff
#print axioms Mettapedia.GSLT.Weighting.generator_diag_ne_neg_totalRate
#print axioms Mettapedia.GSLT.Weighting.sum_mul_generator
#print axioms Mettapedia.GSLT.Weighting.mulVec_one_apply
#print axioms Mettapedia.GSLT.Weighting.generator_isRateMatrix
#print axioms Mettapedia.GSLT.Weighting.rateKernel_generator_isRateMatrix
#print axioms Mettapedia.GSLT.Weighting.generator_ofRateMatrix
#print axioms Mettapedia.GSLT.Weighting.markov_zero
#print axioms Mettapedia.GSLT.Weighting.markov_add
#print axioms Mettapedia.GSLT.Weighting.markov_mulVec_one
#print axioms Mettapedia.GSLT.Weighting.markov_row_sum
#print axioms Mettapedia.GSLT.Weighting.exp_smul_one
#print axioms Mettapedia.GSLT.Weighting.exp_eq_uniformised
#print axioms Mettapedia.GSLT.Weighting.uniformised_nonneg
#print axioms Mettapedia.GSLT.Weighting.uniformised_mulVec_one
#print axioms Mettapedia.GSLT.Weighting.uniformised_isStochastic
#print axioms Mettapedia.GSLT.Weighting.markov_nonneg
#print axioms Mettapedia.GSLT.Weighting.markov_isStochastic
#print axioms Mettapedia.GSLT.Weighting.hasDerivAt_markov
#print axioms Mettapedia.GSLT.Weighting.hasDerivAt_markov'
#print axioms Mettapedia.GSLT.Weighting.hasDerivAt_markov_zero
#print axioms Mettapedia.GSLT.Weighting.conjTranspose_mul_self_apply_self
#print axioms Mettapedia.GSLT.Weighting.conjTranspose_mul_self_apply_of_ne
#print axioms Mettapedia.GSLT.Weighting.mul_mul_conjTranspose_apply_self
#print axioms Mettapedia.GSLT.Weighting.mul_apply_self_of_offDiag
#print axioms Mettapedia.GSLT.Weighting.mul_apply_self_of_offDiag'
#print axioms Mettapedia.GSLT.Weighting.totalRate_transferRate
#print axioms Mettapedia.GSLT.Weighting.lindbladian_phase
#print axioms Mettapedia.GSLT.Weighting.jumpSum_eq_diagonal
#print axioms Mettapedia.GSLT.Weighting.lindbladian_zero_apply_self
#print axioms Mettapedia.GSLT.Weighting.lindbladian_zero_diagonal_apply_of_ne
#print axioms Mettapedia.GSLT.Weighting.sqNorm_smul_single
#print axioms Mettapedia.GSLT.Weighting.noJump_zero_ket
#print axioms Mettapedia.GSLT.Weighting.sqNorm_noJump_zero_ket
#print axioms Mettapedia.GSLT.Weighting.jumpWeight_ket
#print axioms Mettapedia.GSLT.Weighting.sum_jumpWeight_ket
#print axioms Mettapedia.GSLT.Weighting.sum_jumpProbability
#print axioms Mettapedia.GSLT.Weighting.withheldHamiltonian_isHermitian
#print axioms Mettapedia.GSLT.Weighting.normSq_channelJump
#print axioms Mettapedia.GSLT.Weighting.normSq_sourceJump
#print axioms Mettapedia.GSLT.Weighting.normSq_transitionJump
#print axioms Mettapedia.GSLT.Weighting.transferRate_channelJump
#print axioms Mettapedia.GSLT.Weighting.transferRate_sourceJump
#print axioms Mettapedia.GSLT.Weighting.transferRate_transitionJump
#print axioms Mettapedia.GSLT.Weighting.rowSingle_channelJump
#print axioms Mettapedia.GSLT.Weighting.rowSingle_sourceJump
#print axioms Mettapedia.GSLT.Weighting.rowSingle_transitionJump
#print axioms Mettapedia.GSLT.Weighting.colSingle_transitionJump
#print axioms Mettapedia.GSLT.Weighting.channelJump_populations
#print axioms Mettapedia.GSLT.Weighting.sourceJump_populations
#print axioms Mettapedia.GSLT.Weighting.transitionJump_populations
#print axioms Mettapedia.GSLT.Weighting.jumpSum_channelJump
#print axioms Mettapedia.GSLT.Weighting.jumpSum_sourceJump
#print axioms Mettapedia.GSLT.Weighting.jumpSum_transitionJump
#print axioms Mettapedia.GSLT.Weighting.sqNorm_noJump_channelJump
#print axioms Mettapedia.GSLT.Weighting.sqNorm_noJump_sourceJump
#print axioms Mettapedia.GSLT.Weighting.sqNorm_noJump_transitionJump
#print axioms Mettapedia.GSLT.Weighting.totalRate_eq_exitRate_add_selfLoop
#print axioms Mettapedia.GSLT.Weighting.transitionJump_mulVec_ket
#print axioms Mettapedia.GSLT.Weighting.transitionJump_selfLoop_ket
#print axioms Mettapedia.GSLT.Weighting.jumpWeight_transitionJump_ket
#print axioms Mettapedia.GSLT.Weighting.jumpProbability_transitionJump_ket
#print axioms Mettapedia.GSLT.Weighting.sum_jumpProbability_transitionJump_ket
#print axioms Mettapedia.GSLT.Weighting.channelJump_mulVec_ket
#print axioms Mettapedia.GSLT.Weighting.jumpWeight_channelJump_ket
#print axioms Mettapedia.GSLT.Weighting.channelJump_phase
#print axioms Mettapedia.GSLT.Weighting.sourceJump_phase
#print axioms Mettapedia.GSLT.Weighting.transitionJump_phase
#print axioms Mettapedia.GSLT.Weighting.lindbladian_channelJump_phase_indep
#print axioms Mettapedia.GSLT.Weighting.lindbladian_sourceJump_phase_indep
#print axioms Mettapedia.GSLT.Weighting.lindbladian_transitionJump_phase_indep
#print axioms Mettapedia.GSLT.Weighting.lindbladian_transitionJump_diagonal
#print axioms Mettapedia.GSLT.Weighting.Counterexample.rate_nonneg
#print axioms Mettapedia.GSLT.Weighting.Counterexample.not_rowInjective
#print axioms Mettapedia.GSLT.Weighting.Counterexample.L_apply
#print axioms Mettapedia.GSLT.Weighting.Counterexample.jumpSum_eq
#print axioms Mettapedia.GSLT.Weighting.Counterexample.ρDark_eq
#print axioms Mettapedia.GSLT.Weighting.Counterexample.ρDark_mul_self
#print axioms Mettapedia.GSLT.Weighting.Counterexample.trace_ρDark
#print axioms Mettapedia.GSLT.Weighting.Counterexample.ρDark_diag_eq
#print axioms Mettapedia.GSLT.Weighting.Counterexample.lindbladian_ρDark
#print axioms Mettapedia.GSLT.Weighting.Counterexample.lindbladian_ρMix
#print axioms Mettapedia.GSLT.Weighting.Counterexample.classical_prediction
#print axioms Mettapedia.GSLT.Weighting.Counterexample.populations_not_closed
#print axioms Mettapedia.GSLT.Weighting.Counterexample.lindbladian_basis_offDiag
#print axioms Mettapedia.GSLT.Weighting.Counterexample.noJump_ket_zero
#print axioms Mettapedia.GSLT.Weighting.Counterexample.survival_eq
#print axioms Mettapedia.GSLT.Weighting.Counterexample.survival_tendsto
#print axioms Mettapedia.GSLT.Weighting.Counterexample.classical_exitRate
#print axioms Mettapedia.GSLT.Weighting.Counterexample.classical_survival_lt
#print axioms Mettapedia.GSLT.Weighting.Counterexample.sourceJump_populations_fix
#print axioms Mettapedia.GSLT.Weighting.Counterexample.sourceJump_survival
#print axioms Mettapedia.GSLT.Weighting.Branching.sourceJump_creates_coherence
#print axioms Mettapedia.GSLT.Weighting.Branching.transitionJump_no_coherence
#print axioms Mettapedia.GSLT.Weighting.Augmented.geometricFactor_nonneg
#print axioms Mettapedia.GSLT.Weighting.Augmented.coalgebra_nonneg
#print axioms Mettapedia.GSLT.Weighting.Augmented.configuration_chain
#print axioms Mettapedia.GSLT.Weighting.Augmented.generator_diag_of_closed
