import MettaHyperonFull.Minimal.Stdlib
import MettaHyperonFull.Proofs.Correspondence
import MettaHyperonFull.Proofs.Substitution
import Mettapedia.Languages.MeTTa.HE.CanonAbsorbsFreshening

/-!
# Reusable `queryOp` candidate-fold bridge

`Metta.Minimal.queryOp` is the first executable layer above LeaTTa's certified
`KernelStep`/`MopsStep` relation. It does real runtime work that the relation
abstracts away: candidate selection, rule freshening, ambient binding merge, loop
pruning, and item construction.

This module factors the small, reusable fold lemma needed by verified-MeTTa corpus
entries: once a selected candidate contributes a work item at its actual fold
counter, that item is present in the real `queryOp` output. The lemma does not
claim full `mettaEval` scheduler correctness; it is one layer closer to the
running evaluator.
-/

namespace Mettapedia.Languages.MeTTa.LeaTTa.EvaluatorCorrectness.QueryOpBridge

open Metta
open Metta.Minimal
open Mettapedia.Languages.MeTTa.HE.CanonAbsorbsFreshening

/-! ## Static candidate surface -/

/-- On a static world with no runtime `&self` additions, the executable candidate surface
`candidatesW` is exactly the pre-indexed static environment used by `KernelStep`. -/
theorem candidatesW_eq_candidates_of_no_selfExtra
    (env : MinEnv) (w : World) (toEval : Atom)
    (hstatic : w.selfExtra = []) :
    candidatesW env w toEval = env.candidates toEval := by
  unfold candidatesW
  rw [hstatic]
  simp

/-- Initial evaluation starts in a static world, so `candidatesW` and the certified static
candidate index coincide. -/
theorem candidatesW_init_eq_candidates (env : MinEnv) (toEval : Atom) :
    candidatesW env St.init.world toEval = env.candidates toEval := by
  exact candidatesW_eq_candidates_of_no_selfExtra env St.init.world toEval rfl

/-! ## Executable `queryOp` fold surface -/

/-- The one-candidate worklist generated by the executable `queryOp` fold step. -/
def queryOpItemsOfRule (prev : Stack) (toEval : Atom)
    (b : Bindings) (counter : Nat) (p : Atom × Atom) :
    List Item :=
  let (lhs', rhs') := freshenRule counter p.1 p.2
  (matchAtoms lhs' toEval).flatMap fun mb =>
    (Bindings.merge b mb).filterMap fun m =>
      if Bindings.hasLoop m then none
      else some (evalResult prev (instantiate m rhs') m)

/-- Exact membership characterization for the one-candidate executable `queryOp` layer. This is
the generic replacement for per-rule unfolding: every emitted item comes from a freshened match,
a surviving ambient merge, and a non-looping instantiated RHS. -/
theorem mem_queryOpItemsOfRule_iff
    (prev : Stack) (toEval : Atom) (b : Bindings) (counter : Nat) (p : Atom × Atom)
    (item : Item) :
    item ∈ queryOpItemsOfRule prev toEval b counter p ↔
      ∃ mb ∈ matchAtoms (freshenRule counter p.1 p.2).1 toEval,
        ∃ m ∈ Bindings.merge b mb,
          Bindings.hasLoop m = false ∧
            item = evalResult prev (instantiate m (freshenRule counter p.1 p.2).2) m := by
  unfold queryOpItemsOfRule
  cases hfr : freshenRule counter p.1 p.2 with
  | mk lhs' rhs' =>
      simp only [List.mem_flatMap, List.mem_filterMap]
      constructor
      · intro h
        rcases h with ⟨mb, hmb, m, hm, hitem⟩
        by_cases hloop : Bindings.hasLoop m
        · simp [hloop] at hitem
        · simp [hloop] at hitem
          exact ⟨mb, hmb, m, hm, by simpa using hloop, hitem.symm⟩
      · intro h
        rcases h with ⟨mb, hmb, m, hm, hloop, heq⟩
        exact ⟨mb, hmb, m, hm, by simp [hloop, heq]⟩

/-- The accumulator step inside `queryOp`, factored out so membership can be tracked
through the candidate fold directly. -/
def queryOpFoldStep (prev : Stack) (toEval : Atom) (b : Bindings) :
    (List Item × St) → (Atom × Atom) → (List Item × St)
  | acc, p =>
      let items := queryOpItemsOfRule prev toEval b acc.2.counter p
      (acc.1 ++ items, { acc.2 with counter := acc.2.counter + 1 })

/-- Once an item has entered the `queryOp` accumulator, later candidates cannot remove it. -/
theorem queryOpFold_preserves_mem (prev : Stack) (toEval : Atom) (b : Bindings) :
    ∀ cs acc st item,
      item ∈ acc →
        item ∈ ((List.foldl (queryOpFoldStep prev toEval b) (acc, st) cs).1) := by
  intro cs
  induction cs with
  | nil =>
      intro acc st item hmem
      simpa
  | cons _ ps ih =>
      intro acc st item hmem
      simp only [List.foldl_cons]
      exact ih _ _ _ (by simp [hmem])

/-- Processing `n` candidates in `queryOp` advances only the gensym counter by `n`. -/
theorem queryOpFold_counter (prev : Stack) (toEval : Atom) (b : Bindings) :
    ∀ cs acc st,
      ((List.foldl (queryOpFoldStep prev toEval b) (acc, st) cs).2).counter =
        st.counter + List.length cs := by
  intro cs
  induction cs with
  | nil =>
      intro acc st
      simp
  | cons _ ps ih =>
      intro acc st
      simp only [List.foldl_cons, queryOpFoldStep]
      simp [ih, Nat.add_comm, Nat.add_left_comm]

/-- Processing candidates in `queryOp` never mutates the runtime world; it only advances the
fresh-name counter. -/
theorem queryOpFold_world (prev : Stack) (toEval : Atom) (b : Bindings) :
    ∀ cs acc st,
      ((List.foldl (queryOpFoldStep prev toEval b) (acc, st) cs).2).world = st.world := by
  intro cs
  induction cs with
  | nil =>
      intro acc st
      simp
  | cons _ ps ih =>
      intro acc st
      simp only [List.foldl_cons, queryOpFoldStep]
      exact ih _ _

/-- The executable query layer preserves the runtime world. Candidate scanning freshens rule
variables by bumping the counter, but it does not perform effects such as `add-atom`. -/
theorem queryOp_world (env : MinEnv) (st : St) (prev : Stack) (toEval : Atom) (b : Bindings) :
    (queryOp env st prev toEval b).2.world = st.world := by
  unfold queryOp
  by_cases hvar : isVariableHeaded toEval
  · simp [hvar]
  · simp [hvar]
    let folded := List.foldl (queryOpFoldStep prev toEval b) ([], st)
      (candidatesW env st.world toEval)
    change (if folded.1 = [] then ([finItem prev notReducibleA b], folded.2) else folded).2.world =
      st.world
    by_cases hres : folded.1 = []
    · simp [hres, folded, queryOpFold_world]
    · simp [hres, folded, queryOpFold_world]

/-- If the candidate list is split as `pre ++ p :: post`, and `p` contributes `item`
when processed at its actual fold counter, then that item survives into the final
candidate-fold result. -/
theorem mem_queryOpFold_of_split_candidate
    (prev : Stack) (toEval : Atom) (b : Bindings) (st : St)
    (pre post : List (Atom × Atom)) (p : Atom × Atom) (item : Item)
    (hitem :
      item ∈ queryOpItemsOfRule prev toEval b (st.counter + pre.length) p) :
    item ∈ (((pre ++ p :: post).foldl (queryOpFoldStep prev toEval b) ([], st)).1) := by
  rw [List.foldl_append]
  let prefixAcc := pre.foldl (queryOpFoldStep prev toEval b) ([], st)
  have hcounter : prefixAcc.2.counter = st.counter + pre.length := by
    simpa [prefixAcc] using queryOpFold_counter prev toEval b pre [] st
  simp only [List.foldl_cons]
  have hseed :
      item ∈ prefixAcc.1 ++ queryOpItemsOfRule prev toEval b prefixAcc.2.counter p := by
    simp [hcounter, hitem]
  exact queryOpFold_preserves_mem prev toEval b post _ _ _ hseed

/-- Operational lift for the executable query layer: once we know the candidate split and that
the selected candidate contributes an item at its actual fold counter, real `queryOp` contains
that item. -/
theorem queryOp_contains_item_of_splitCandidate
    (env : MinEnv) (st : St) (prev : Stack) (toEval : Atom) (b : Bindings)
    {pre post : List (Atom × Atom)} {p : Atom × Atom} {item : Item}
    (hNotVarHead : isVariableHeaded toEval = false)
    (hsplit : candidatesW env st.world toEval = pre ++ p :: post)
    (hitem : item ∈ queryOpItemsOfRule prev toEval b (st.counter + pre.length) p) :
    item ∈ (queryOp env st prev toEval b).1 := by
  have hmemResults :
      item ∈ ((candidatesW env st.world toEval).foldl
          (queryOpFoldStep prev toEval b) ([], st)).1 := by
    rw [hsplit]
    simpa using
      (mem_queryOpFold_of_split_candidate prev toEval b st pre post p item hitem)
  let folded : List Item × St :=
    (candidatesW env st.world toEval).foldl
      (queryOpFoldStep prev toEval b) ([], st)
  have hfoldedMem : item ∈ folded.1 := by
    simpa [folded] using hmemResults
  have hnonempty : folded.1.isEmpty = false := by
    cases hlist : folded.1 with
    | nil =>
        simp [hlist] at hfoldedMem
    | cons _ _ =>
        simp
  have hqueryOpResults :
      (queryOp env st prev toEval b).1 = folded.1 := by
    unfold queryOp
    rw [hNotVarHead]
    change
      (if folded.1.isEmpty then
          ([finItem prev notReducibleA b], folded.2)
        else
          folded).1 = folded.1
    simp [hnonempty]
  rw [hqueryOpResults]
  exact hfoldedMem

/-- If a non-variable-headed query has no executable candidates, real `queryOp` emits
`NotReducible`. This is the no-rule companion to the split-candidate bridge above; constructor
normal forms such as Peano `S` use this branch in the outer `mettaEval` loop. -/
theorem queryOp_contains_notReducible_of_no_candidates
    (env : MinEnv) (st : St) (prev : Stack) (toEval : Atom) (b : Bindings)
    (hNotVarHead : isVariableHeaded toEval = false)
    (hnone : candidatesW env st.world toEval = []) :
    finItem prev notReducibleA b ∈ (queryOp env st prev toEval b).1 := by
  unfold queryOp
  rw [hNotVarHead]
  rw [hnone]
  simp

/-- Exact structural form of the no-candidate query branch. This is not a concrete trace theorem:
it packages the generic branch law used by the full evaluator to treat constructor normal forms as
inert. -/
theorem queryOp_notReducible_of_no_candidates_eq
    (env : MinEnv) (st : St) (prev : Stack) (toEval : Atom) (b : Bindings)
    (hNotVarHead : isVariableHeaded toEval = false)
    (hnone : candidatesW env st.world toEval = []) :
    queryOp env st prev toEval b = ([finItem prev notReducibleA b], st) := by
  unfold queryOp
  rw [hNotVarHead]
  rw [hnone]
  simp

/-- Component form of `queryOp_contains_item_of_splitCandidate`: once a selected candidate has a
freshened match, an ambient merge that survives loop pruning, and an instantiated RHS, the real
executable `queryOp` output contains the corresponding item.

This is the generic replacement for per-rule recomputation of `matchAtoms` in verified-MeTTa
examples. -/
theorem queryOp_contains_instantiated_item_of_splitCandidate
    (env : MinEnv) (st : St) (prev : Stack) (toEval : Atom) (b : Bindings)
    {pre post : List (Atom × Atom)} {p : Atom × Atom}
    {mb m : Bindings}
    (hNotVarHead : isVariableHeaded toEval = false)
    (hsplit : candidatesW env st.world toEval = pre ++ p :: post)
    (hmatch : mb ∈ matchAtoms (freshenRule (st.counter + pre.length) p.1 p.2).1 toEval)
    (hmerge : m ∈ Bindings.merge b mb)
    (hloop : Bindings.hasLoop m = false) :
    evalResult prev (instantiate m (freshenRule (st.counter + pre.length) p.1 p.2).2) m ∈
      (queryOp env st prev toEval b).1 := by
  apply queryOp_contains_item_of_splitCandidate env st prev toEval b hNotVarHead hsplit
  rw [mem_queryOpItemsOfRule_iff]
  exact ⟨mb, hmatch, m, hmerge, hloop, rfl⟩

/-- Static-KB form of `queryOp_contains_instantiated_item_of_splitCandidate`: the candidate split is
stated over the same static index `KernelStep` uses. -/
theorem queryOp_contains_instantiated_item_of_staticCandidateSplit
    (env : MinEnv) (st : St) (prev : Stack) (toEval : Atom) (b : Bindings)
    {pre post : List (Atom × Atom)} {p : Atom × Atom}
    {mb m : Bindings}
    (hstatic : st.world.selfExtra = [])
    (hNotVarHead : isVariableHeaded toEval = false)
    (hsplit : env.candidates toEval = pre ++ p :: post)
    (hmatch : mb ∈ matchAtoms (freshenRule (st.counter + pre.length) p.1 p.2).1 toEval)
    (hmerge : m ∈ Bindings.merge b mb)
    (hloop : Bindings.hasLoop m = false) :
    evalResult prev (instantiate m (freshenRule (st.counter + pre.length) p.1 p.2).2) m ∈
      (queryOp env st prev toEval b).1 := by
  apply queryOp_contains_instantiated_item_of_splitCandidate env st prev toEval b
    hNotVarHead
  · rw [candidatesW_eq_candidates_of_no_selfExtra env st.world toEval hstatic]
    exact hsplit
  · exact hmatch
  · exact hmerge
  · exact hloop

/-- A split of the static candidate list exposes the selected rule as a candidate. -/
theorem candidate_mem_of_staticCandidateSplit
    (env : MinEnv) (toEval : Atom)
    {pre post : List (Atom × Atom)} {p : Atom × Atom}
    (hsplit : env.candidates toEval = pre ++ p :: post) :
    p ∈ env.candidates toEval := by
  rw [hsplit]
  simp

/-- Every selected static candidate has some prefix/suffix split. The prefix length is the
freshening counter offset used by the executable `queryOp` fold. -/
theorem exists_staticCandidateSplit_of_candidate_mem
    (env : MinEnv) (toEval : Atom) {p : Atom × Atom}
    (hcand : p ∈ env.candidates toEval) :
    ∃ pre post, env.candidates toEval = pre ++ p :: post :=
  List.mem_iff_append.mp hcand

/-! ## Matcher leaf facts for the freshening crossing -/

/-- A variable pattern matches any closed target with the corresponding value binding. This is the
leaf case of the freshened-matcher crossing used by the interpreter-correctness lift. -/
theorem matchAtoms_var_closed_mem (v : String) (target : Atom)
    (hclosed : target.vars = []) :
    [BindingRel.val v target] ∈ matchAtoms (Atom.var v) target := by
  cases target with
  | var w => simp [Atom.vars] at hclosed
  | sym s => simp [matchAtoms, matchAtomsWith]
  | gnd g => simp [matchAtoms, matchAtomsWith]
  | expr xs =>
      simp [Atom.vars] at hclosed
      simp [matchAtoms, matchAtomsWith]

/-- Instantiating a variable under its singleton value binding returns that value. -/
theorem instantiate_singleton_val_var (v : String) (target : Atom) :
    instantiate [BindingRel.val v target] (Atom.var v) = target := by
  simp [instantiate, bindingsToSubst, Metta.Subst.apply, Metta.Subst.lookup]

/-- A singleton value binding to a closed target is never a loop. -/
theorem hasLoop_singleton_val_closed_false (v : String) (target : Atom)
    (hclosed : target.vars = []) :
    Bindings.hasLoop [BindingRel.val v target] = false := by
  cases target with
  | var w => simp [Atom.vars] at hclosed
  | sym s => simp [Bindings.hasLoop]
  | gnd g => simp [Bindings.hasLoop]
  | expr xs =>
      simp [Atom.vars] at hclosed
      simp [Bindings.hasLoop]

/-- Empty ambient bindings preserve a singleton value binding. This is the one-binding base case for
the ambient-merge part of the runtime crossing. -/
theorem singleton_val_mem_merge_empty_left (v : String) (target : Atom) :
    [BindingRel.val v target] ∈ Bindings.merge [] [BindingRel.val v target] := by
  simp [Bindings.merge, Bindings.mergeOne, Bindings.addVarBinding, Bindings.lookupVal,
    Bindings.addValRaw, Bindings.removeVal]

/-! ## Closed symbolic matcher facts -/

/-- Renaming variables is the identity on closed atoms. -/
theorem renBy_eq_self_of_vars_nil (f : VarName → VarName) :
    ∀ a : Atom, a.vars = [] → renBy f a = a := by
  refine Metta.Atom.recAux ?_ ?_ ?_ ?_
  · intro s _
    simp [renBy]
  · intro v h
    simp [Atom.vars] at h
  · intro g _
    simp [renBy]
  · intro xs ih hvars
    simp only [Atom.vars] at hvars
    simp only [renBy_expr]
    have hmap : List.map (renBy f) xs = List.map (fun a => a) xs := by
      apply List.map_congr_left
      intro a ha
      apply ih a ha
      apply List.eq_nil_iff_forall_not_mem.mpr
      intro v hv
      have hvflat : v ∈ (xs.map Atom.vars).flatten := by
        rw [List.mem_flatten]
        exact ⟨a.vars, by rw [List.mem_map]; exact ⟨a, ha, rfl⟩, hv⟩
      rw [hvars] at hvflat
      cases hvflat
    simpa [List.map_id'] using hmap

/-- Symbol-only atoms, possibly nested in expressions. This is the first closed fragment where
`matchAtoms a a` can be proved without assuming reflexivity of grounded payload equality; grounded
float equality may be non-reflexive on NaN, so the generic closed-atom statement would be too strong.
-/
inductive SymbolicClosed : Atom → Prop
  | sym (s : String) : SymbolicClosed (Atom.sym s)
  | expr {xs : List Atom} : (∀ a, a ∈ xs → SymbolicClosed a) → SymbolicClosed (Atom.expr xs)

/-- Symbolic closed atoms have no variables. -/
theorem SymbolicClosed.vars_nil {a : Atom} (h : SymbolicClosed a) : a.vars = [] := by
  induction h with
  | sym s =>
      simp [Atom.vars]
  | expr hchildren ih =>
      apply List.eq_nil_iff_forall_not_mem.mpr
      intro v hv
      rw [Atom.vars, List.mem_flatten] at hv
      rcases hv with ⟨l, hl, hv⟩
      rw [List.mem_map] at hl
      rcases hl with ⟨a, ha, rfl⟩
      have hva : a.vars = [] := ih a ha
      rw [hva] at hv
      cases hv

/-- A symbolic closed atom matches itself with the empty binding set. This is the expression/list
matcher base case needed before generalizing the freshened runtime crossing beyond one variable
leaf. -/
theorem matchAtoms_symbolicClosed_self_empty {a : Atom} (h : SymbolicClosed a) :
    [] ∈ matchAtoms a a := by
  induction h with
  | sym s =>
      simp [matchAtoms, matchAtomsWith]
  | @expr xs hchildren ih =>
      have hlist :
          ∀ ys acc, (∀ a ∈ ys, a ∈ xs) → [] ∈ acc → [] ∈ matchAll none acc ys ys := by
        intro ys
        induction ys with
        | nil =>
            intro acc hsub hacc
            simpa [matchAll] using hacc
        | cons y ys ihys =>
            intro acc hsub hacc
            simp only [matchAll]
            have hyMem : y ∈ xs := hsub y (by simp)
            have hyMatch : [] ∈ matchAtoms y y := ih y hyMem
            have hseed :
                [] ∈ acc.flatMap
                  (fun a => (matchAtoms y y).flatMap fun b => Bindings.merge a b) := by
              rw [List.mem_flatMap]
              refine ⟨[], hacc, ?_⟩
              rw [List.mem_flatMap]
              refine ⟨[], hyMatch, ?_⟩
              simp [Bindings.merge]
            exact ihys _ (fun a ha => hsub a (by simp [ha])) hseed
      change [] ∈ matchAll none [[]] xs xs
      exact hlist xs [[]] (fun a ha => ha) (by simp)

/-- Runtime freshening is literally inert on symbolic closed identity rules. -/
theorem freshenRule_symbolicClosed_id (counter : Nat) {a : Atom} (h : SymbolicClosed a) :
    freshenRule counter a a = (a, a) := by
  unfold freshenRule
  rw [SymbolicClosed.vars_nil h]
  simp

/-- Runtime freshening is literally inert on any variable-free symbolic rule. -/
theorem freshenRule_symbolicClosed_pair_id (counter : Nat) {lhs rhs : Atom}
    (hlhs : SymbolicClosed lhs) (hrhs : SymbolicClosed rhs) :
    freshenRule counter lhs rhs = (lhs, rhs) := by
  unfold freshenRule
  rw [SymbolicClosed.vars_nil hlhs, SymbolicClosed.vars_nil hrhs]
  simp

/-! ## Certified single-step bridge -/

/-! ### Runtime freshening is α-inert -/

def counterSuffix (counter : Nat) (v : String) : String :=
  v ++ "#" ++ toString counter

private theorem counterSuffix_injective (counter : Nat) :
    Function.Injective (counterSuffix counter) := by
  intro x y h
  apply String.ext
  have h' : x.toList ++ ("#" ++ toString counter).toList =
      y.toList ++ ("#" ++ toString counter).toList := by
    simpa [counterSuffix, String.toList_append, List.append_assoc] using congrArg String.toList h
  exact (List.append_left_inj (("#" ++ toString counter).toList)).mp h'

private theorem counterSubst_lookup
    (counter : Nat) :
    ∀ (vars : List String) (v : String),
      Metta.Subst.lookup
          (vars.map fun x => (x, Metta.Atom.var (counterSuffix counter x))) v =
        (vars.find? (fun x => x == v)).map (fun x => Metta.Atom.var (counterSuffix counter x)) := by
  intro vars v
  induction vars with
  | nil =>
      simp [Metta.Subst.lookup]
  | cons x xs ih =>
      by_cases hx : x = v
      · subst hx
        simp [Metta.Subst.lookup]
      · have hbeq : (x == v) = false := by
          simp [hx]
        have hne : v ≠ x := by
          intro h
          exact hx h.symm
        have hbeq' : (v == x) = false := by
          simp [hne]
        simpa [Metta.Subst.lookup, hbeq, hbeq'] using ih

private theorem find?_beq_self_of_mem :
    ∀ (vars : List String) {v : String},
      v ∈ vars → vars.find? (fun x => x == v) = some v := by
  intro vars
  induction vars with
  | nil =>
      intro v hv
      cases hv
  | cons x xs ih =>
      intro v hv
      by_cases hx : x = v
      · subst hx
        simp
      · have hvxs : v ∈ xs := (List.mem_cons.mp hv).resolve_left (fun h => hx h.symm)
        have hbeq : (x == v) = false := by
          simp [hx]
        simpa [hbeq] using ih hvxs

private theorem counterSubst_apply_eq_renBy_of_varsSubset
    (counter : Nat) (vars : List String) :
    ∀ a : Metta.Atom,
      (∀ v ∈ a.vars, v ∈ vars) →
        Metta.Subst.apply
            (vars.map fun x => (x, Metta.Atom.var (counterSuffix counter x))) a =
          renBy (counterSuffix counter) a := by
  refine Metta.Atom.recAux ?_ ?_ ?_ ?_
  · intro s _
    simp [Metta.Subst.apply, renBy]
  · intro v hvars
    have hv : v ∈ vars := hvars v (by simp [Metta.Atom.vars])
    rw [Metta.Subst.apply, counterSubst_lookup]
    have hfind : vars.find? (fun x => x == v) = some v :=
      find?_beq_self_of_mem vars hv
    simp [hfind]
  · intro g _
    simp [Metta.Subst.apply, renBy]
  · intro xs ih hvars
    simp only [Metta.Subst.apply, renBy_expr]
    refine congrArg Metta.Atom.expr (List.map_congr_left ?_)
    intro x hx
    exact ih x hx (fun v hv => hvars v (by
      simp only [Metta.Atom.vars, List.mem_flatten, List.mem_map]
      exact ⟨x.vars, ⟨x, hx, rfl⟩, hv⟩))

/-- Exact form of LeaTTa runtime rule freshening: it is the total variable renaming
`v ↦ v#counter` on both sides of the rule. -/
theorem freshenRule_eq_renBy (counter : Nat) (lhs rhs : Atom) :
    freshenRule counter lhs rhs =
      (renBy (counterSuffix counter) lhs, renBy (counterSuffix counter) rhs) := by
  unfold freshenRule
  cases hvars : lhs.vars ++ rhs.vars with
  | nil =>
      have hnil : lhs.vars = [] ∧ rhs.vars = [] :=
        List.append_eq_nil_iff.mp hvars
      have hl := renBy_eq_self_of_vars_nil (counterSuffix counter) lhs hnil.1
      have hr := renBy_eq_self_of_vars_nil (counterSuffix counter) rhs hnil.2
      simp [hl, hr]
  | cons v vs =>
      simp
      have hsubsetL : ∀ x ∈ lhs.vars, x ∈ v :: vs := by
        intro x hx
        rw [← hvars]
        exact List.mem_append_left rhs.vars hx
      have hsubsetR : ∀ x ∈ rhs.vars, x ∈ v :: vs := by
        intro x hx
        rw [← hvars]
        exact List.mem_append_right lhs.vars hx
      constructor
      · have h := counterSubst_apply_eq_renBy_of_varsSubset counter (v :: vs) lhs hsubsetL
        simpa [counterSuffix] using h
      · have h := counterSubst_apply_eq_renBy_of_varsSubset counter (v :: vs) rhs hsubsetR
        simpa [counterSuffix] using h

/-! ### Runtime freshening and binding-key renaming -/

/-- Rename the variable keys carried by a binding set, leaving bound atom values untouched. Runtime
rule freshening changes rule-variable names, while the matched target values remain in the original
atom language; this is the binding-level companion to `renBy`. -/
def renameBindings (f : VarName → VarName) : Bindings → Bindings
  | [] => []
  | BindingRel.val x a :: rest => BindingRel.val (f x) a :: renameBindings f rest
  | BindingRel.eq x y :: rest => BindingRel.eq (f x) (f y) :: renameBindings f rest

/-- The value-binding keys in a binding set, ignoring equality-only relations. -/
def bindingValueKeys : Bindings → List VarName
  | [] => []
  | BindingRel.val x _ :: rest => x :: bindingValueKeys rest
  | BindingRel.eq _ _ :: rest => bindingValueKeys rest

/-- Binding sets whose value bindings all point to closed atoms, and which contain no equality
relations. This is the no-capture shape produced by matching variable patterns against closed
targets. -/
inductive ClosedValueBindings : Bindings → Prop
  | nil : ClosedValueBindings []
  | val {x : VarName} {a : Atom} {rest : Bindings} :
      a.vars = [] → ClosedValueBindings rest →
        ClosedValueBindings (BindingRel.val x a :: rest)

/-- Renaming binding keys preserves the closed-value shape. -/
theorem ClosedValueBindings.rename {f : VarName → VarName} :
    ∀ {b : Bindings}, ClosedValueBindings b → ClosedValueBindings (renameBindings f b)
  | _, ClosedValueBindings.nil => ClosedValueBindings.nil
  | _, ClosedValueBindings.val hclosed hrest =>
      ClosedValueBindings.val hclosed (ClosedValueBindings.rename hrest)

/-- Closed-value bindings never contain a loop. -/
theorem ClosedValueBindings.hasLoop_false :
    ∀ {b : Bindings}, ClosedValueBindings b → Bindings.hasLoop b = false
  | _, ClosedValueBindings.nil => by
      simp [Bindings.hasLoop]
  | _, ClosedValueBindings.val (a := a) hclosed hrest => by
      have ih := ClosedValueBindings.hasLoop_false hrest
      unfold Bindings.hasLoop at ih ⊢
      cases a with
      | var y =>
          simp [Atom.vars] at hclosed
      | sym s =>
          simp [ih]
      | gnd g =>
          simp [ih]
      | expr xs =>
          simp [ih]

/-- Renamed closed-value bindings also survive runtime loop pruning. -/
theorem ClosedValueBindings.rename_hasLoop_false {f : VarName → VarName} {b : Bindings}
    (h : ClosedValueBindings b) :
    Bindings.hasLoop (renameBindings f b) = false :=
  ClosedValueBindings.hasLoop_false (ClosedValueBindings.rename h)

/-- Closed-value bindings are closed under append. -/
theorem ClosedValueBindings.append :
    ∀ {a b : Bindings}, ClosedValueBindings a → ClosedValueBindings b → ClosedValueBindings (a ++ b)
  | [], b, ClosedValueBindings.nil, hb => by
      simpa using hb
  | BindingRel.val x atom :: rest, b, ClosedValueBindings.val hclosed hrest, hb => by
      simp only [List.cons_append]
      exact ClosedValueBindings.val hclosed (ClosedValueBindings.append hrest hb)

/-- Reversing a closed-value binding set preserves the closed-value shape. -/
theorem ClosedValueBindings.reverse :
    ∀ {b : Bindings}, ClosedValueBindings b → ClosedValueBindings b.reverse
  | [], ClosedValueBindings.nil => ClosedValueBindings.nil
  | BindingRel.val x atom :: rest, ClosedValueBindings.val hclosed hrest => by
      rw [List.reverse_cons]
      exact ClosedValueBindings.append (ClosedValueBindings.reverse hrest)
        (ClosedValueBindings.val hclosed ClosedValueBindings.nil)

/-- Value keys commute with binding-key renaming. -/
theorem bindingValueKeys_renameBindings (f : VarName → VarName) :
    ∀ b : Bindings, bindingValueKeys (renameBindings f b) = (bindingValueKeys b).map f
  | [] => by
      simp [bindingValueKeys, renameBindings]
  | BindingRel.val x a :: rest => by
      simp [bindingValueKeys, renameBindings, bindingValueKeys_renameBindings f rest]
  | BindingRel.eq x y :: rest => by
      simp [bindingValueKeys, renameBindings, bindingValueKeys_renameBindings f rest]

/-- If a key is absent from the value-key surface, direct value lookup does not find it. -/
theorem lookupVal_none_of_not_mem_keys {x : VarName} :
    ∀ {b : Bindings}, x ∉ bindingValueKeys b → Bindings.lookupVal b x = none
  | [], _ => by
      simp [Bindings.lookupVal]
  | BindingRel.val y a :: rest, hnot => by
      have hnotRest : x ∉ bindingValueKeys rest := by
        intro hx
        exact hnot (by simp [bindingValueKeys, hx])
      have hxy : x ≠ y := by
        intro h
        subst h
        exact hnot (by simp [bindingValueKeys])
      have hbeq : (x == y) = false := by
        simp [hxy]
      simp [Bindings.lookupVal, hbeq, lookupVal_none_of_not_mem_keys hnotRest]
  | BindingRel.eq y z :: rest, hnot => by
      have hnotRest : x ∉ bindingValueKeys rest := by
        simpa [bindingValueKeys] using hnot
      simpa [Bindings.lookupVal] using lookupVal_none_of_not_mem_keys hnotRest

/-- If a key is absent from the value-key surface, every `removeVal` filter test succeeds. -/
theorem removeVal_filter_true_of_not_mem {x : VarName} :
    ∀ {b : Bindings}, x ∉ bindingValueKeys b →
      ∀ r ∈ b, (match r with | BindingRel.val y _ => y != x | _ => true) = true
  | [], _, r, hr => by
      cases hr
  | BindingRel.val y a :: rest, hnot, r, hr => by
      cases hr with
      | head =>
          have hyx : y ≠ x := by
            intro h
            subst h
            exact hnot (by simp [bindingValueKeys])
          simp [hyx]
      | tail _ hrRest =>
          have hnotRest : x ∉ bindingValueKeys rest := by
            intro hx
            exact hnot (by simp [bindingValueKeys, hx])
          exact removeVal_filter_true_of_not_mem hnotRest r hrRest
  | BindingRel.eq y z :: rest, hnot, r, hr => by
      have hnotRest : x ∉ bindingValueKeys rest := by
        simpa [bindingValueKeys] using hnot
      cases hr with
      | head =>
          simp
      | tail _ hrRest =>
          exact removeVal_filter_true_of_not_mem hnotRest r hrRest

/-- Removing an absent value key is the identity. -/
theorem removeVal_not_mem_eq_self {x : VarName} {b : Bindings}
    (hnot : x ∉ bindingValueKeys b) :
    Bindings.removeVal b x = b := by
  unfold Bindings.removeVal
  exact List.filter_eq_self.mpr (removeVal_filter_true_of_not_mem hnot)

/-- A one-binding merge into an accumulator with no binding for that key succeeds by raw insertion. -/
theorem mergeOne_singleton_val_of_not_mem {acc : Bindings} {x : VarName} {a : Atom}
    (hnot : x ∉ bindingValueKeys acc) :
    Bindings.mergeOne [acc] (BindingRel.val x a) = [[BindingRel.val x a] ++ acc] := by
  simp [Bindings.mergeOne, Bindings.addVarBinding, lookupVal_none_of_not_mem_keys hnot,
    Bindings.addValRaw, removeVal_not_mem_eq_self hnot]

/-- Closed value bindings with distinct keys merge into an accumulator by prepending each value
binding, hence the final output is the reverse of the incoming binding list followed by the
accumulator. -/
theorem merge_closed_noConflict_mem :
    ∀ {b acc : Bindings}, ClosedValueBindings b → (bindingValueKeys b).Nodup →
      (∀ x ∈ bindingValueKeys b, x ∉ bindingValueKeys acc) →
        b.reverse ++ acc ∈ Bindings.merge acc b
  | [], acc, ClosedValueBindings.nil, _, _ => by
      simp [Bindings.merge]
  | BindingRel.val x a :: rest, acc, ClosedValueBindings.val hclosed hrest, hnodup, hdisj => by
      have hxNotAcc : x ∉ bindingValueKeys acc := hdisj x (by simp [bindingValueKeys])
      have hmergeOne := mergeOne_singleton_val_of_not_mem (acc := acc) (x := x) (a := a) hxNotAcc
      have hnodupParts := List.nodup_cons.mp (by simpa [bindingValueKeys] using hnodup)
      have hxNotRest : x ∉ bindingValueKeys rest := hnodupParts.1
      have hnodupRest : (bindingValueKeys rest).Nodup := hnodupParts.2
      have hdisjRest : ∀ y ∈ bindingValueKeys rest,
          y ∉ bindingValueKeys (BindingRel.val x a :: acc) := by
        intro y hy
        have hyNotAcc : y ∉ bindingValueKeys acc := hdisj y (by simp [bindingValueKeys, hy])
        have hyNeX : y ≠ x := by
          intro h
          subst h
          exact hxNotRest hy
        intro hyMem
        simp [bindingValueKeys] at hyMem
        cases hyMem with
        | inl hyx => exact hyNeX hyx
        | inr hyacc => exact hyNotAcc hyacc
      have ih := merge_closed_noConflict_mem hrest hnodupRest hdisjRest
      unfold Bindings.merge
      simp only [List.foldl_cons]
      rw [hmergeOne]
      simpa [Bindings.merge, List.reverse_cons, List.append_assoc] using ih

/-- Empty-ambient form of `merge_closed_noConflict_mem`. -/
theorem merge_empty_closed_nodup_mem {b : Bindings}
    (hclosed : ClosedValueBindings b) (hnodup : (bindingValueKeys b).Nodup) :
    b.reverse ∈ Bindings.merge [] b := by
  simpa using
    (merge_closed_noConflict_mem (b := b) (acc := []) hclosed hnodup
      (by intro x hx hmem; cases hmem))

/-- Renamed closed value bindings with distinct original keys merge from an empty ambient binding set
to the reversed renamed binding list. -/
theorem merge_empty_renamed_closed_nodup_mem {f : VarName → VarName} (hf : Function.Injective f)
    {b : Bindings} (hclosed : ClosedValueBindings b) (hnodup : (bindingValueKeys b).Nodup) :
    (renameBindings f b).reverse ∈ Bindings.merge [] (renameBindings f b) := by
  apply merge_empty_closed_nodup_mem
  · exact ClosedValueBindings.rename hclosed
  · rw [bindingValueKeys_renameBindings]
    exact List.Nodup.map hf hnodup

/-- Value lookup over appended binding lists checks the left list first, then the right list. -/
theorem lookupVal_append (a b : Bindings) (x : VarName) :
    Bindings.lookupVal (a ++ b) x =
      (Bindings.lookupVal a x).orElse (fun _ => Bindings.lookupVal b x) := by
  induction a with
  | nil =>
      simp [Bindings.lookupVal]
  | cons r rest ih =>
      cases r with
      | val y atom =>
          by_cases hxy : x = y
          · subst hxy
            simp [Bindings.lookupVal]
          · have hbeq : (x == y) = false := by
              simp [hxy]
            simp [Bindings.lookupVal, hbeq, ih]
      | eq y z =>
          simp [Bindings.lookupVal, ih]

/-- A singleton binding for a different key does not affect lookup. -/
theorem lookupVal_singleton_ne {x y : VarName} (hxy : x ≠ y) (a : Atom) :
    Bindings.lookupVal [BindingRel.val y a] x = none := by
  have hbeq : (x == y) = false := by
    simp [hxy]
  simp [Bindings.lookupVal, hbeq]

/-- Reversing a closed-value binding set with distinct keys preserves direct value lookup. -/
theorem lookupVal_reverse_closed_nodup :
    ∀ {b : Bindings}, ClosedValueBindings b → (bindingValueKeys b).Nodup →
      ∀ q, Bindings.lookupVal b.reverse q = Bindings.lookupVal b q
  | [], ClosedValueBindings.nil, _, q => by
      simp [Bindings.lookupVal]
  | BindingRel.val key val :: rest, ClosedValueBindings.val hclosed hrest, hnodup, q => by
      have parts := List.nodup_cons.mp (by simpa [bindingValueKeys] using hnodup)
      have keyNotRest : key ∉ bindingValueKeys rest := parts.1
      have hnodupRest : (bindingValueKeys rest).Nodup := parts.2
      rw [List.reverse_cons, lookupVal_append]
      by_cases hqkey : q = key
      · have hrevNone : Bindings.lookupVal rest.reverse q = none := by
          rw [lookupVal_reverse_closed_nodup hrest hnodupRest]
          exact lookupVal_none_of_not_mem_keys (by simpa [hqkey] using keyNotRest)
        rw [hrevNone]
        simp [Bindings.lookupVal, hqkey]
      · have hrestEq := lookupVal_reverse_closed_nodup hrest hnodupRest q
        have hbeq : (q == key) = false := by
          simp [hqkey]
        rw [hrestEq]
        cases hrestLookup : Bindings.lookupVal rest q <;>
          simp [Bindings.lookupVal, hbeq, hrestLookup]

/-- Looking up a value binding after `bindingsToSubst` agrees with direct `Bindings.lookupVal`.
Equality-only binding relations are ignored by both sides for instantiation. -/
theorem lookup_bindingsToSubst (b : Bindings) (v : VarName) :
    Metta.Subst.lookup (bindingsToSubst b) v = Bindings.lookupVal b v := by
  induction b with
  | nil =>
      simp [bindingsToSubst, Metta.Subst.lookup, Bindings.lookupVal]
  | cons r rest ih =>
      cases r with
      | val x a =>
          by_cases hx : v = x
          · subst hx
            simp [bindingsToSubst, Metta.Subst.lookup, Bindings.lookupVal]
          · have hvx : (v == x) = false := by
              simp [hx]
            simpa [bindingsToSubst, Metta.Subst.lookup, Bindings.lookupVal, hvx] using ih
      | eq x y =>
          simpa [bindingsToSubst, Bindings.lookupVal] using ih

/-- Value lookup commutes with an injective binding-key renaming. -/
theorem lookupVal_renameBindings_injective (f : VarName → VarName) (hf : Function.Injective f) :
    ∀ (b : Bindings) (v : VarName),
      Bindings.lookupVal (renameBindings f b) (f v) = Bindings.lookupVal b v := by
  intro b
  induction b with
  | nil =>
      intro v
      simp [renameBindings, Bindings.lookupVal]
  | cons r rest ih =>
      intro v
      cases r with
      | val x a =>
          by_cases hx : x = v
          · subst hx
            simp [renameBindings, Bindings.lookupVal]
          · have hfx : f v ≠ f x := by
              intro h
              exact hx ((hf h).symm)
            have hbeq1 : (f v == f x) = false := by
              simp [hfx]
            have hbeq2 : (v == x) = false := by
              have hvx : v ≠ x := by
                intro h
                exact hx h.symm
              simp [hvx]
            simpa [renameBindings, Bindings.lookupVal, hbeq1, hbeq2] using ih v
      | eq x y =>
          simpa [renameBindings, Bindings.lookupVal] using ih v

/-- If every variable of `a` is assigned by `b`, then instantiating the renamed atom under the
renamed binding keys agrees exactly with instantiating the original atom under the original keys.

This is the reusable exact-substitution component behind the runtime-freshening to `KernelStep`
crossing for non-escaping RHS variables. -/
theorem instantiate_renBy_of_renamed_bindings
    (f : VarName → VarName) (hf : Function.Injective f) :
    ∀ (b : Bindings) (a : Atom),
      (∀ v ∈ a.vars, ∃ t, Bindings.lookupVal b v = some t) →
        instantiate (renameBindings f b) (renBy f a) = instantiate b a := by
  intro b
  refine Metta.Atom.recAux ?_ ?_ ?_ ?_
  · intro s _
    simp [instantiate, Metta.Subst.apply, renBy]
  · intro v hbound
    rcases hbound v (by simp [Atom.vars]) with ⟨t, ht⟩
    unfold instantiate
    simp only [renBy, Metta.Subst.apply]
    rw [lookup_bindingsToSubst, lookup_bindingsToSubst,
      lookupVal_renameBindings_injective f hf]
    simp [ht]
  · intro g _
    simp [instantiate, Metta.Subst.apply, renBy]
  · intro xs ih hbound
    simp only [instantiate, Metta.Subst.apply, renBy_expr]
    congr 1
    rw [List.map_map]
    apply List.map_congr_left
    intro a ha
    exact ih a ha (fun v hv => hbound v (by
      simp only [Atom.vars, List.mem_flatten, List.mem_map]
      exact ⟨a.vars, ⟨a, ha, rfl⟩, hv⟩))

/-- If two binding sets agree on value lookup for every variable in an atom, instantiation agrees on
that atom. -/
theorem instantiate_eq_of_lookupVal_on_vars :
    ∀ (b1 b2 : Bindings) (a : Atom),
      (∀ v ∈ a.vars, Bindings.lookupVal b1 v = Bindings.lookupVal b2 v) →
        instantiate b1 a = instantiate b2 a := by
  intro b1 b2
  refine Metta.Atom.recAux ?_ ?_ ?_ ?_
  · intro s _
    simp [instantiate, Metta.Subst.apply]
  · intro v hlook
    unfold instantiate
    simp only [Metta.Subst.apply]
    rw [lookup_bindingsToSubst, lookup_bindingsToSubst]
    rw [hlook v (by simp [Atom.vars])]
  · intro g _
    simp [instantiate, Metta.Subst.apply]
  · intro xs ih hlook
    simp only [instantiate, Metta.Subst.apply]
    congr 1
    apply List.map_congr_left
    intro a ha
    exact ih a ha (fun v hv => hlook v (by
      simp only [Atom.vars, List.mem_flatten, List.mem_map]
      exact ⟨a.vars, ⟨a, ha, rfl⟩, hv⟩))

/-- Reversing closed value bindings with distinct keys preserves instantiation. -/
theorem instantiate_reverse_closed_nodup
    {b : Bindings} (hclosed : ClosedValueBindings b) (hnodup : (bindingValueKeys b).Nodup)
    (a : Atom) :
    instantiate b.reverse a = instantiate b a :=
  instantiate_eq_of_lookupVal_on_vars b.reverse b a
    (fun v _ => lookupVal_reverse_closed_nodup hclosed hnodup v)

/-- RHS-specialized form for LeaTTa's `freshenRule`: when the unfreshened core binding covers every
RHS variable, the runtime-freshened RHS instantiated under renamed binding keys is exactly the
certified unfreshened reduct. -/
theorem instantiate_freshenRule_rhs_of_renamed_bindings
    (counter : Nat) (lhs rhs : Atom) (b : Bindings)
    (hbound : ∀ v ∈ rhs.vars, ∃ t, Bindings.lookupVal b v = some t) :
    instantiate (renameBindings (counterSuffix counter) b) (freshenRule counter lhs rhs).2 =
      instantiate b rhs := by
  rw [freshenRule_eq_renBy]
  exact instantiate_renBy_of_renamed_bindings
    (counterSuffix counter) (counterSuffix_injective counter) b rhs hbound

/-- LeaTTa runtime freshening is α-inert on the LHS: canonicalization forgets the fresh counter
suffixes. This is the generic α component needed before relating executable `queryOp` output to
the un-freshened `firedReducts` semantics. -/
theorem freshenRule_alphaEq_fst
    (counter : Nat) (lhs rhs : Metta.Atom) :
    Metta.AlphaEq (Metta.Minimal.freshenRule counter lhs rhs).1 lhs := by
  unfold Metta.AlphaEq
  unfold Metta.Minimal.freshenRule
  cases hvars : lhs.vars ++ rhs.vars with
  | nil =>
      simp
  | cons v vs =>
      simp
      have hsubset : ∀ x ∈ lhs.vars, x ∈ v :: vs := by
        intro x hx
        rw [← hvars]
        exact List.mem_append_left rhs.vars hx
      calc
        Metta.canonicalizeVars
            (Metta.Subst.apply
              ((v, Metta.Atom.var (v ++ "#" ++ counter.repr)) ::
                vs.map fun x => (x, Metta.Atom.var (x ++ "#" ++ counter.repr))) lhs)
            =
              Metta.canonicalizeVars (renBy (counterSuffix counter) lhs) := by
                have happly :=
                  counterSubst_apply_eq_renBy_of_varsSubset counter (v :: vs) lhs hsubset
                simpa [counterSuffix] using congrArg Metta.canonicalizeVars happly
        _ = Metta.canonicalizeVars lhs :=
              canonicalizeVars_renBy_of_injective (counterSuffix_injective counter) lhs

/-- LeaTTa runtime freshening is α-inert on the RHS as well. -/
theorem freshenRule_alphaEq_snd
    (counter : Nat) (lhs rhs : Metta.Atom) :
    Metta.AlphaEq (Metta.Minimal.freshenRule counter lhs rhs).2 rhs := by
  unfold Metta.AlphaEq
  unfold Metta.Minimal.freshenRule
  cases hvars : lhs.vars ++ rhs.vars with
  | nil =>
      simp
  | cons v vs =>
      simp
      have hsubset : ∀ x ∈ rhs.vars, x ∈ v :: vs := by
        intro x hx
        rw [← hvars]
        exact List.mem_append_right lhs.vars hx
      calc
        Metta.canonicalizeVars
            (Metta.Subst.apply
              ((v, Metta.Atom.var (v ++ "#" ++ counter.repr)) ::
                vs.map fun x => (x, Metta.Atom.var (x ++ "#" ++ counter.repr))) rhs)
            =
              Metta.canonicalizeVars (renBy (counterSuffix counter) rhs) := by
                have happly :=
                  counterSubst_apply_eq_renBy_of_varsSubset counter (v :: vs) rhs hsubset
                simpa [counterSuffix] using congrArg Metta.canonicalizeVars happly
        _ = Metta.canonicalizeVars rhs :=
              canonicalizeVars_renBy_of_injective (counterSuffix_injective counter) rhs

/-- A candidate rule and one of its matcher bindings determine a certified indexed-kernel reduct.
This is the small generic bridge from the candidate/matcher side to LeaTTa's `firedReducts`
semantics; freshening, ambient-binding merge, and loop-pruning remain separate obligations for
the executable `queryOp` layer. -/
theorem firedReducts_of_candidate_match
    {atoms : List Atom} {gt : GroundingTable} {toEval lhs rhs : Atom} {b : Bindings}
    (hcand : (lhs, rhs) ∈ (MinEnv.ofAtomsGT atoms gt).candidates toEval)
    (hmatch : b ∈ matchAtoms lhs toEval) :
    instantiate b rhs ∈
      firedReducts ((MinEnv.ofAtomsGT atoms gt).candidates toEval) toEval := by
  rw [Metta.mem_firedReducts]
  exact ⟨(lhs, rhs), hcand, b, hmatch, rfl⟩

/-- Candidate/matcher form of a certified root `KernelStep`. -/
theorem kernelStep_of_candidate_match
    {atoms : List Atom} {gt : GroundingTable} {toEval lhs rhs : Atom} {b : Bindings}
    (hhead : ∃ k, headKey toEval = some k)
    (hcand : (lhs, rhs) ∈ (MinEnv.ofAtomsGT atoms gt).candidates toEval)
    (hmatch : b ∈ matchAtoms lhs toEval) :
    KernelStep atoms gt toEval (instantiate b rhs) :=
  ⟨hhead, firedReducts_of_candidate_match hcand hmatch⟩

/-- Split-index form of `kernelStep_of_candidate_match`, aligned with the executable `queryOp`
fold counter. -/
theorem kernelStep_of_staticCandidateSplit_match
    {atoms : List Atom} {gt : GroundingTable} {toEval lhs rhs : Atom} {b : Bindings}
    {pre post : List (Atom × Atom)}
    (hhead : ∃ k, headKey toEval = some k)
    (hsplit : (MinEnv.ofAtomsGT atoms gt).candidates toEval = pre ++ (lhs, rhs) :: post)
    (hmatch : b ∈ matchAtoms lhs toEval) :
    KernelStep atoms gt toEval (instantiate b rhs) :=
  kernelStep_of_candidate_match hhead
    (candidate_mem_of_staticCandidateSplit (MinEnv.ofAtomsGT atoms gt) toEval hsplit)
    hmatch

/-- The two halves currently proved for one static candidate split: executable `queryOp` emits the
freshened/merged item, while the same unfreshened candidate and matcher witness determine a certified
`KernelStep`.

The remaining runtime-correctness crossing is precisely to derive the unfreshened matcher witness
and relate the two instantiated RHS atoms from the freshened executable components. -/
theorem queryOp_item_and_kernelStep_of_staticCandidateSplit
    {atoms : List Atom} {gt : GroundingTable} {st : St} {prev : Stack}
    {toEval lhs rhs : Atom} {mb m coreB : Bindings}
    {pre post : List (Atom × Atom)}
    (hstatic : st.world.selfExtra = [])
    (hNotVarHead : isVariableHeaded toEval = false)
    (hhead : ∃ k, headKey toEval = some k)
    (hsplit : (MinEnv.ofAtomsGT atoms gt).candidates toEval = pre ++ (lhs, rhs) :: post)
    (hmatchFresh :
      mb ∈ matchAtoms (freshenRule (st.counter + pre.length) lhs rhs).1 toEval)
    (hmerge : m ∈ Bindings.merge [] mb)
    (hloop : Bindings.hasLoop m = false)
    (hmatchCore : coreB ∈ matchAtoms lhs toEval) :
    evalResult prev (instantiate m (freshenRule (st.counter + pre.length) lhs rhs).2) m ∈
        (queryOp (MinEnv.ofAtomsGT atoms gt) st prev toEval []).1 ∧
      KernelStep atoms gt toEval (instantiate coreB rhs) := by
  constructor
  · exact queryOp_contains_instantiated_item_of_staticCandidateSplit
      (MinEnv.ofAtomsGT atoms gt) st prev toEval [] hstatic hNotVarHead hsplit
      hmatchFresh hmerge hloop
  · exact kernelStep_of_staticCandidateSplit_match hhead hsplit hmatchCore

/-- MOPS-facing form of `queryOp_item_and_kernelStep_of_staticCandidateSplit`.

This exposes the same executable `queryOp` item together with LeaTTa's published root MOPS step.
The executable item still carries runtime freshening/merge details; callers remain responsible for
relating it to the certified unfreshened reduct when they need equality of readouts. -/
theorem queryOp_item_and_mopsStep_of_staticCandidateSplit
    {atoms : List Atom} {gt : GroundingTable} {st : St} {prev : Stack}
    {toEval lhs rhs : Atom} {mb m coreB : Bindings}
    {pre post : List (Atom × Atom)}
    (hstatic : st.world.selfExtra = [])
    (hNotVarHead : isVariableHeaded toEval = false)
    (hhead : ∃ k, headKey toEval = some k)
    (hsplit : (MinEnv.ofAtomsGT atoms gt).candidates toEval = pre ++ (lhs, rhs) :: post)
    (hmatchFresh :
      mb ∈ matchAtoms (freshenRule (st.counter + pre.length) lhs rhs).1 toEval)
    (hmerge : m ∈ Bindings.merge [] mb)
    (hloop : Bindings.hasLoop m = false)
    (hmatchCore : coreB ∈ matchAtoms lhs toEval) :
    evalResult prev (instantiate m (freshenRule (st.counter + pre.length) lhs rhs).2) m ∈
        (queryOp (MinEnv.ofAtomsGT atoms gt) st prev toEval []).1 ∧
      MopsStep atoms toEval (instantiate coreB rhs) := by
  rcases queryOp_item_and_kernelStep_of_staticCandidateSplit
    (atoms := atoms) (gt := gt) (st := st) (prev := prev)
    (toEval := toEval) (lhs := lhs) (rhs := rhs) (mb := mb) (m := m)
    (coreB := coreB) (pre := pre) (post := post)
    hstatic hNotVarHead hhead hsplit hmatchFresh hmerge hloop hmatchCore with
    ⟨hmem, hstep⟩
  exact ⟨hmem, kernelStep_iff_mopsStep.mp hstep⟩

/-- Result-equality form of `queryOp_item_and_kernelStep_of_staticCandidateSplit`. The runtime merge
may reorder or normalize bindings, so later B1 lemmas should relate the executable instantiated RHS
to the certified unfreshened reduct by an explicit equality rather than by requiring a particular
binding-list shape. -/
theorem queryOp_item_and_kernelStep_of_staticCandidateSplit_eqResult
    {atoms : List Atom} {gt : GroundingTable} {st : St} {prev : Stack}
    {toEval lhs rhs : Atom} {mb m coreB : Bindings}
    {pre post : List (Atom × Atom)}
    (hstatic : st.world.selfExtra = [])
    (hNotVarHead : isVariableHeaded toEval = false)
    (hhead : ∃ k, headKey toEval = some k)
    (hsplit : (MinEnv.ofAtomsGT atoms gt).candidates toEval = pre ++ (lhs, rhs) :: post)
    (hmatchFresh :
      mb ∈ matchAtoms (freshenRule (st.counter + pre.length) lhs rhs).1 toEval)
    (hmerge : m ∈ Bindings.merge [] mb)
    (hloop : Bindings.hasLoop m = false)
    (hmatchCore : coreB ∈ matchAtoms lhs toEval)
    (hresult :
      instantiate m (freshenRule (st.counter + pre.length) lhs rhs).2 = instantiate coreB rhs) :
    evalResult prev (instantiate coreB rhs) m ∈
        (queryOp (MinEnv.ofAtomsGT atoms gt) st prev toEval []).1 ∧
      KernelStep atoms gt toEval (instantiate coreB rhs) := by
  have hpair := queryOp_item_and_kernelStep_of_staticCandidateSplit
    (st := st) (prev := prev) (toEval := toEval) (lhs := lhs) (rhs := rhs)
    (mb := mb) (m := m) (coreB := coreB) (pre := pre) (post := post)
    hstatic hNotVarHead hhead hsplit hmatchFresh hmerge hloop hmatchCore
  constructor
  · simpa [hresult] using hpair.1
  · exact hpair.2

/-- MOPS-facing result-equality form of `queryOp_item_and_kernelStep_of_staticCandidateSplit`.

Once the executable freshened RHS is proved equal to the certified unfreshened reduct, the actual
`queryOp` item is paired directly with LeaTTa's published MOPS step. -/
theorem queryOp_item_and_mopsStep_of_staticCandidateSplit_eqResult
    {atoms : List Atom} {gt : GroundingTable} {st : St} {prev : Stack}
    {toEval lhs rhs : Atom} {mb m coreB : Bindings}
    {pre post : List (Atom × Atom)}
    (hstatic : st.world.selfExtra = [])
    (hNotVarHead : isVariableHeaded toEval = false)
    (hhead : ∃ k, headKey toEval = some k)
    (hsplit : (MinEnv.ofAtomsGT atoms gt).candidates toEval = pre ++ (lhs, rhs) :: post)
    (hmatchFresh :
      mb ∈ matchAtoms (freshenRule (st.counter + pre.length) lhs rhs).1 toEval)
    (hmerge : m ∈ Bindings.merge [] mb)
    (hloop : Bindings.hasLoop m = false)
    (hmatchCore : coreB ∈ matchAtoms lhs toEval)
    (hresult :
      instantiate m (freshenRule (st.counter + pre.length) lhs rhs).2 = instantiate coreB rhs) :
    evalResult prev (instantiate coreB rhs) m ∈
        (queryOp (MinEnv.ofAtomsGT atoms gt) st prev toEval []).1 ∧
      MopsStep atoms toEval (instantiate coreB rhs) := by
  rcases queryOp_item_and_kernelStep_of_staticCandidateSplit_eqResult
    (atoms := atoms) (gt := gt) (st := st) (prev := prev)
    (toEval := toEval) (lhs := lhs) (rhs := rhs) (mb := mb) (m := m)
    (coreB := coreB) (pre := pre) (post := post)
    hstatic hNotVarHead hhead hsplit hmatchFresh hmerge hloop hmatchCore hresult with
    ⟨hmem, hstep⟩
  exact ⟨hmem, kernelStep_iff_mopsStep.mp hstep⟩

/-- A sharper crossing theorem for the common non-escaping-variable case. If the executable
freshened matcher returns exactly the renamed version of an unfreshened core binding, and that core
binding covers all RHS variables, then the runtime `queryOp` item and certified `KernelStep` reduct
have the same result atom.

This isolates the remaining B1 work: prove matcher equivariance (`hmatchFresh`) and ambient
merge/loop preservation for renamed bindings. -/
theorem queryOp_item_and_kernelStep_of_renamed_coreBinding
    {atoms : List Atom} {gt : GroundingTable} {st : St} {prev : Stack}
    {toEval lhs rhs : Atom} {coreB : Bindings} {pre post : List (Atom × Atom)}
    (hstatic : st.world.selfExtra = [])
    (hNotVarHead : isVariableHeaded toEval = false)
    (hhead : ∃ k, headKey toEval = some k)
    (hsplit : (MinEnv.ofAtomsGT atoms gt).candidates toEval = pre ++ (lhs, rhs) :: post)
    (hmatchFresh : renameBindings (counterSuffix (st.counter + pre.length)) coreB ∈
      matchAtoms (freshenRule (st.counter + pre.length) lhs rhs).1 toEval)
    (hmerge : renameBindings (counterSuffix (st.counter + pre.length)) coreB ∈
      Bindings.merge [] (renameBindings (counterSuffix (st.counter + pre.length)) coreB))
    (hloop :
      Bindings.hasLoop (renameBindings (counterSuffix (st.counter + pre.length)) coreB) = false)
    (hmatchCore : coreB ∈ matchAtoms lhs toEval)
    (hbound : ∀ v ∈ rhs.vars, ∃ t, Bindings.lookupVal coreB v = some t) :
    evalResult prev (instantiate coreB rhs)
          (renameBindings (counterSuffix (st.counter + pre.length)) coreB) ∈
        (queryOp (MinEnv.ofAtomsGT atoms gt) st prev toEval []).1 ∧
      KernelStep atoms gt toEval (instantiate coreB rhs) := by
  have hquery := queryOp_contains_instantiated_item_of_staticCandidateSplit
    (MinEnv.ofAtomsGT atoms gt) st prev toEval [] hstatic hNotVarHead hsplit
    hmatchFresh hmerge hloop
  have hinst := instantiate_freshenRule_rhs_of_renamed_bindings
    (st.counter + pre.length) lhs rhs coreB hbound
  constructor
  · simpa [hinst] using hquery
  · exact kernelStep_of_staticCandidateSplit_match hhead hsplit hmatchCore

/-- Closed-value version of `queryOp_item_and_kernelStep_of_renamed_coreBinding`, with loop-pruning
discharged by the binding shape. Matcher equivariance and empty-ambient merge membership remain the
two explicit B1 obligations. -/
theorem queryOp_item_and_kernelStep_of_renamed_closed_coreBinding
    {atoms : List Atom} {gt : GroundingTable} {st : St} {prev : Stack}
    {toEval lhs rhs : Atom} {coreB : Bindings} {pre post : List (Atom × Atom)}
    (hclosedB : ClosedValueBindings coreB)
    (hstatic : st.world.selfExtra = [])
    (hNotVarHead : isVariableHeaded toEval = false)
    (hhead : ∃ k, headKey toEval = some k)
    (hsplit : (MinEnv.ofAtomsGT atoms gt).candidates toEval = pre ++ (lhs, rhs) :: post)
    (hmatchFresh : renameBindings (counterSuffix (st.counter + pre.length)) coreB ∈
      matchAtoms (freshenRule (st.counter + pre.length) lhs rhs).1 toEval)
    (hmerge : renameBindings (counterSuffix (st.counter + pre.length)) coreB ∈
      Bindings.merge [] (renameBindings (counterSuffix (st.counter + pre.length)) coreB))
    (hmatchCore : coreB ∈ matchAtoms lhs toEval)
    (hbound : ∀ v ∈ rhs.vars, ∃ t, Bindings.lookupVal coreB v = some t) :
    evalResult prev (instantiate coreB rhs)
          (renameBindings (counterSuffix (st.counter + pre.length)) coreB) ∈
        (queryOp (MinEnv.ofAtomsGT atoms gt) st prev toEval []).1 ∧
      KernelStep atoms gt toEval (instantiate coreB rhs) :=
  queryOp_item_and_kernelStep_of_renamed_coreBinding
    (st := st) (prev := prev) (toEval := toEval) (lhs := lhs) (rhs := rhs)
    (coreB := coreB) (pre := pre) (post := post)
    hstatic hNotVarHead hhead hsplit hmatchFresh hmerge
    (ClosedValueBindings.rename_hasLoop_false hclosedB) hmatchCore hbound

/-- Closed-value/no-duplicate-key version with the **actual** empty-ambient merge output. The runtime
merge folds by prepending, so the emitted binding set is the reverse of the renamed matcher binding;
the result atom is still exactly the certified `KernelStep` reduct. -/
theorem queryOp_item_and_kernelStep_of_renamed_closed_coreBinding_reverse
    {atoms : List Atom} {gt : GroundingTable} {st : St} {prev : Stack}
    {toEval lhs rhs : Atom} {coreB : Bindings} {pre post : List (Atom × Atom)}
    (hclosedB : ClosedValueBindings coreB)
    (hnodup : (bindingValueKeys coreB).Nodup)
    (hstatic : st.world.selfExtra = [])
    (hNotVarHead : isVariableHeaded toEval = false)
    (hhead : ∃ k, headKey toEval = some k)
    (hsplit : (MinEnv.ofAtomsGT atoms gt).candidates toEval = pre ++ (lhs, rhs) :: post)
    (hmatchFresh : renameBindings (counterSuffix (st.counter + pre.length)) coreB ∈
      matchAtoms (freshenRule (st.counter + pre.length) lhs rhs).1 toEval)
    (hmatchCore : coreB ∈ matchAtoms lhs toEval)
    (hbound : ∀ v ∈ rhs.vars, ∃ t, Bindings.lookupVal coreB v = some t) :
    evalResult prev (instantiate coreB rhs)
          (renameBindings (counterSuffix (st.counter + pre.length)) coreB).reverse ∈
        (queryOp (MinEnv.ofAtomsGT atoms gt) st prev toEval []).1 ∧
      KernelStep atoms gt toEval (instantiate coreB rhs) := by
  let f := counterSuffix (st.counter + pre.length)
  have hf : Function.Injective f := by
    simpa [f] using counterSuffix_injective (st.counter + pre.length)
  have hclosedRen : ClosedValueBindings (renameBindings f coreB) :=
    ClosedValueBindings.rename hclosedB
  have hnodupRen : (bindingValueKeys (renameBindings f coreB)).Nodup := by
    rw [bindingValueKeys_renameBindings]
    exact List.Nodup.map hf hnodup
  have hmerge : (renameBindings f coreB).reverse ∈ Bindings.merge [] (renameBindings f coreB) := by
    exact merge_empty_renamed_closed_nodup_mem hf hclosedB hnodup
  have hloop : Bindings.hasLoop (renameBindings f coreB).reverse = false :=
    ClosedValueBindings.hasLoop_false (ClosedValueBindings.reverse hclosedRen)
  have hreverseInst :
      instantiate (renameBindings f coreB).reverse
          (freshenRule (st.counter + pre.length) lhs rhs).2 =
        instantiate (renameBindings f coreB) (freshenRule (st.counter + pre.length) lhs rhs).2 :=
    instantiate_reverse_closed_nodup hclosedRen hnodupRen _
  have hfreshInst :
      instantiate (renameBindings f coreB) (freshenRule (st.counter + pre.length) lhs rhs).2 =
        instantiate coreB rhs := by
    simpa [f] using instantiate_freshenRule_rhs_of_renamed_bindings
      (st.counter + pre.length) lhs rhs coreB hbound
  have hresult :
      instantiate (renameBindings f coreB).reverse
          (freshenRule (st.counter + pre.length) lhs rhs).2 =
        instantiate coreB rhs := by
    rw [hreverseInst, hfreshInst]
  exact queryOp_item_and_kernelStep_of_staticCandidateSplit_eqResult
    (st := st) (prev := prev) (toEval := toEval) (lhs := lhs) (rhs := rhs)
    (mb := renameBindings f coreB) (m := (renameBindings f coreB).reverse)
    (coreB := coreB) (pre := pre) (post := post)
    hstatic hNotVarHead hhead hsplit (by simpa [f] using hmatchFresh)
    (by simpa [f] using hmerge) (by simpa [f] using hloop) hmatchCore hresult

/-- Fully discharged leaf crossing: for the identity variable rule `$v ↦ $v`, runtime freshening,
empty ambient merge, and loop pruning produce exactly the same target as the certified unfreshened
`KernelStep`, on a closed symbol-headed query. -/
theorem queryOp_item_and_kernelStep_var_id_closed
    {atoms : List Atom} {gt : GroundingTable} {st : St} {prev : Stack}
    {toEval target : Atom} {v : String} {pre post : List (Atom × Atom)}
    (hclosed : target.vars = [])
    (htarget : toEval = target)
    (hstatic : st.world.selfExtra = [])
    (hNotVarHead : isVariableHeaded toEval = false)
    (hhead : ∃ k, headKey toEval = some k)
    (hsplit : (MinEnv.ofAtomsGT atoms gt).candidates toEval =
      pre ++ (Atom.var v, Atom.var v) :: post) :
    evalResult prev target [BindingRel.val (counterSuffix (st.counter + pre.length) v) target] ∈
        (queryOp (MinEnv.ofAtomsGT atoms gt) st prev toEval []).1 ∧
      KernelStep atoms gt toEval target := by
  subst toEval
  have hmatchFresh :
      [BindingRel.val (counterSuffix (st.counter + pre.length) v) target] ∈
        matchAtoms (freshenRule (st.counter + pre.length) (Atom.var v) (Atom.var v)).1 target := by
    unfold freshenRule
    simp [Atom.vars, Metta.Subst.apply, Metta.Subst.lookup, counterSuffix,
      matchAtoms_var_closed_mem, hclosed]
  have hmerge :
      [BindingRel.val (counterSuffix (st.counter + pre.length) v) target] ∈
        Bindings.merge [] [BindingRel.val (counterSuffix (st.counter + pre.length) v) target] :=
    singleton_val_mem_merge_empty_left _ _
  have hloop :
      Bindings.hasLoop [BindingRel.val (counterSuffix (st.counter + pre.length) v) target] = false :=
    hasLoop_singleton_val_closed_false _ _ hclosed
  have hmatchCore : [BindingRel.val v target] ∈ matchAtoms (Atom.var v) target :=
    matchAtoms_var_closed_mem v target hclosed
  have hpair := queryOp_item_and_kernelStep_of_staticCandidateSplit
    (st := st) (prev := prev) (toEval := target) (lhs := Atom.var v) (rhs := Atom.var v)
    (mb := [BindingRel.val (counterSuffix (st.counter + pre.length) v) target])
    (m := [BindingRel.val (counterSuffix (st.counter + pre.length) v) target])
    (coreB := [BindingRel.val v target]) (pre := pre) (post := post)
    hstatic hNotVarHead hhead hsplit hmatchFresh hmerge hloop hmatchCore
  constructor
  · simpa [freshenRule, Atom.vars, Metta.Subst.apply, Metta.Subst.lookup, counterSuffix,
      instantiate_singleton_val_var] using hpair.1
  · simpa [instantiate_singleton_val_var] using hpair.2

/-- Fully discharged variable-free symbolic-rule crossing. If the static candidate `(lhs, rhs)` has
no variables or grounded payloads, then runtime freshening is inert, empty ambient merge/loop pruning
collapses directly, and the executable `queryOp` item composes directly with LeaTTa's certified
`firedReducts`/`KernelStep` semantics.

The theorem still takes the ordinary `matchAtoms lhs toEval` witness as input; it does not recompute a
particular program rule. -/
theorem queryOp_item_and_kernelStep_symbolic_rule_closed
    {atoms : List Atom} {gt : GroundingTable} {st : St} {prev : Stack}
    {toEval lhs rhs : Atom} {pre post : List (Atom × Atom)}
    (hlhs : SymbolicClosed lhs) (hrhs : SymbolicClosed rhs)
    (hmatch : [] ∈ matchAtoms lhs toEval)
    (hstatic : st.world.selfExtra = [])
    (hNotVarHead : isVariableHeaded toEval = false)
    (hhead : ∃ k, headKey toEval = some k)
    (hsplit : (MinEnv.ofAtomsGT atoms gt).candidates toEval = pre ++ (lhs, rhs) :: post) :
    evalResult prev rhs [] ∈
        (queryOp (MinEnv.ofAtomsGT atoms gt) st prev toEval []).1 ∧
      KernelStep atoms gt toEval rhs := by
  have hfr : freshenRule (st.counter + pre.length) lhs rhs = (lhs, rhs) :=
    freshenRule_symbolicClosed_pair_id (st.counter + pre.length) hlhs hrhs
  have hmatchFresh :
      [] ∈ matchAtoms (freshenRule (st.counter + pre.length) lhs rhs).1 toEval := by
    rw [hfr]
    exact hmatch
  have hmerge : [] ∈ Bindings.merge [] [] := by
    simp [Bindings.merge]
  have hloop : Bindings.hasLoop [] = false := by
    simp [Bindings.hasLoop]
  have hpair := queryOp_item_and_kernelStep_of_staticCandidateSplit
    (st := st) (prev := prev) (toEval := toEval) (lhs := lhs) (rhs := rhs)
    (mb := []) (m := []) (coreB := []) (pre := pre) (post := post)
    hstatic hNotVarHead hhead hsplit hmatchFresh hmerge hloop hmatch
  constructor
  · simpa [hfr, Metta.instantiate_nil] using hpair.1
  · simpa [Metta.instantiate_nil] using hpair.2

/-- Fully discharged closed-symbolic identity crossing: for a static candidate `(a, a)` where `a`
is a symbol-only closed atom, executable `queryOp` emits the same result as the certified
unfreshened `KernelStep`.

This is the expression/list analogue of `queryOp_item_and_kernelStep_var_id_closed`; it composes the
generic `queryOp` fold bridge with `firedReducts`/`KernelStep` instead of recomputing a particular
program rule. -/
theorem queryOp_item_and_kernelStep_symbolic_id_closed
    {atoms : List Atom} {gt : GroundingTable} {st : St} {prev : Stack}
    {toEval target : Atom} {pre post : List (Atom × Atom)}
    (hsym : SymbolicClosed target)
    (htarget : toEval = target)
    (hstatic : st.world.selfExtra = [])
    (hNotVarHead : isVariableHeaded toEval = false)
    (hhead : ∃ k, headKey toEval = some k)
    (hsplit : (MinEnv.ofAtomsGT atoms gt).candidates toEval =
      pre ++ (target, target) :: post) :
    evalResult prev target [] ∈
        (queryOp (MinEnv.ofAtomsGT atoms gt) st prev toEval []).1 ∧
      KernelStep atoms gt toEval target := by
  subst toEval
  have hfr : freshenRule (st.counter + pre.length) target target = (target, target) :=
    freshenRule_symbolicClosed_id (st.counter + pre.length) hsym
  have hmatchFresh :
      [] ∈ matchAtoms (freshenRule (st.counter + pre.length) target target).1 target := by
    rw [hfr]
    exact matchAtoms_symbolicClosed_self_empty hsym
  have hmerge : [] ∈ Bindings.merge [] [] := by
    simp [Bindings.merge]
  have hloop : Bindings.hasLoop [] = false := by
    simp [Bindings.hasLoop]
  have hmatchCore : [] ∈ matchAtoms target target :=
    matchAtoms_symbolicClosed_self_empty hsym
  have hpair := queryOp_item_and_kernelStep_of_staticCandidateSplit
    (st := st) (prev := prev) (toEval := target) (lhs := target) (rhs := target)
    (mb := []) (m := []) (coreB := []) (pre := pre) (post := post)
    hstatic hNotVarHead hhead hsplit hmatchFresh hmerge hloop hmatchCore
  constructor
  · simpa [hfr, Metta.instantiate_nil] using hpair.1
  · simpa [Metta.instantiate_nil] using hpair.2

end Mettapedia.Languages.MeTTa.LeaTTa.EvaluatorCorrectness.QueryOpBridge
