import Mathlib.Data.List.GetD

/-!
# Contextual choice and state handlers

Choice and state do not have one universal interaction.  This module keeps one
free, syntax-independent computation and gives it two explicit handlers:

* `runWorlds` gives every alternative the same parent state and retains a
  branch trace, final private state, and deferred intents;
* `runShared` executes the authored alternative order against one shared state.

`selectCommit` is a third boundary built from `runWorlds`: it commits exactly
one retained world and exposes only that world's deferred intents.  External
effects are therefore data until selection.

The separating examples are load-bearing.  Two increments from state zero
produce observations `[0, 0]` under isolated worlds and `[0, 1]` under shared
state.  The handlers are interpretations of the same computation, but they are
not interchangeable.
-/

namespace Mettapedia.GSLT.Dynamics.ContextualEffectHandlers

set_option autoImplicit false

universe uState uAnswer uOtherAnswer uIntent

/-- The free finite-choice computation generated by state access and deferred
external intents.  `intent` records a request; it does not perform it. -/
inductive Program (State : Type uState) (Answer : Type uAnswer)
    (Intent : Type uIntent) where
  | pure (answer : Answer)
  | choose (left right : Program State Answer Intent)
  | read (next : State -> Program State Answer Intent)
  | write (state : State) (next : Program State Answer Intent)
  | intent (request : Intent) (next : Program State Answer Intent)

namespace Program

/-- Dependent sequencing for the free computation. -/
def bind {State : Type uState} {Answer : Type uAnswer}
    {OtherAnswer : Type uOtherAnswer} {Intent : Type uIntent}
    (program : Program State Answer Intent)
    (next : Answer -> Program State OtherAnswer Intent) :
    Program State OtherAnswer Intent :=
  match program with
  | .pure answer => next answer
  | .choose left right => .choose (bind left next) (bind right next)
  | .read continuation => .read fun state => bind (continuation state) next
  | .write state continuation => .write state (bind continuation next)
  | .intent request continuation => .intent request (bind continuation next)

/-- Functorial mapping derived from sequencing. -/
def map {State : Type uState} {Answer : Type uAnswer}
    {OtherAnswer : Type uOtherAnswer} {Intent : Type uIntent}
    (function : Answer -> OtherAnswer)
    (program : Program State Answer Intent) :
    Program State OtherAnswer Intent :=
  bind program fun answer => .pure (function answer)

@[simp] theorem pure_bind {State : Type uState} {Answer : Type uAnswer}
    {OtherAnswer : Type uOtherAnswer} {Intent : Type uIntent}
    (answer : Answer) (next : Answer -> Program State OtherAnswer Intent) :
    bind (.pure answer) next = next answer :=
  rfl

@[simp] theorem choose_bind {State : Type uState} {Answer : Type uAnswer}
    {OtherAnswer : Type uOtherAnswer} {Intent : Type uIntent}
    (left right : Program State Answer Intent)
    (next : Answer -> Program State OtherAnswer Intent) :
    bind (.choose left right) next = .choose (bind left next) (bind right next) :=
  rfl

end Program

/-- A branch trace records the nested choices leading to one result.  `false`
is the left child and `true` is the right child; the most recent choice is at
the head. -/
abbrev BranchTrace := List Bool

/-- One isolated alternative, including the state and intents needed by a
later observer or commit handler. -/
structure WorldResult (State : Type uState) (Answer : Type uAnswer)
    (Intent : Type uIntent) where
  branch : BranchTrace
  answer : Answer
  state : State
  intents : List Intent
deriving Repr

/-- Evaluate every alternative from its own parent state. -/
def runWorldsAt {State : Type uState} {Answer : Type uAnswer}
    {Intent : Type uIntent} :
    Program State Answer Intent -> State -> BranchTrace ->
      List (WorldResult State Answer Intent)
  | .pure answer, state, branch =>
      [{ branch := branch, answer := answer, state := state, intents := [] }]
  | .choose left right, state, branch =>
      runWorldsAt left state (false :: branch) ++
        runWorldsAt right state (true :: branch)
  | .read next, state, branch => runWorldsAt (next state) state branch
  | .write newState next, _state, branch =>
      runWorldsAt next newState branch
  | .intent request next, state, branch =>
      (runWorldsAt next state branch).map fun result =>
        { result with intents := request :: result.intents }

/-- Rooted isolated-world evaluation. -/
def runWorlds {State : Type uState} {Answer : Type uAnswer}
    {Intent : Type uIntent}
    (program : Program State Answer Intent) (state : State) :
    List (WorldResult State Answer Intent) :=
  runWorldsAt program state []

/-- The result of executing all authored alternatives against one shared
state.  This handler intentionally exposes the authored enumeration order. -/
structure SharedResult (State : Type uState) (Answer : Type uAnswer)
    (Intent : Type uIntent) where
  answers : List Answer
  state : State
  intents : List Intent
deriving Repr

/-- Shared-state, left-to-right interpretation of the same free computation. -/
def runShared {State : Type uState} {Answer : Type uAnswer}
    {Intent : Type uIntent} :
    Program State Answer Intent -> State -> SharedResult State Answer Intent
  | .pure answer, state =>
      { answers := [answer], state := state, intents := [] }
  | .choose left right, state =>
      let leftResult := runShared left state
      let rightResult := runShared right leftResult.state
      { answers := leftResult.answers ++ rightResult.answers
        state := rightResult.state
        intents := leftResult.intents ++ rightResult.intents }
  | .read next, state => runShared (next state) state
  | .write newState next, _state => runShared next newState
  | .intent request next, state =>
      let result := runShared next state
      { result with intents := request :: result.intents }

/-- The observable artifact at a selected-commit boundary. -/
structure Committed (State : Type uState) (Answer : Type uAnswer)
    (Intent : Type uIntent) where
  branch : BranchTrace
  answer : Answer
  state : State
  intents : List Intent
deriving Repr

namespace WorldResult

/-- Forget the fact that a result was merely speculative. -/
def commit {State : Type uState} {Answer : Type uAnswer}
    {Intent : Type uIntent}
    (result : WorldResult State Answer Intent) :
    Committed State Answer Intent where
  branch := result.branch
  answer := result.answer
  state := result.state
  intents := result.intents

end WorldResult

/-- Select one isolated result by occurrence position.  Only the selected
branch's state and intents cross the commit boundary. -/
def selectCommit {State : Type uState} {Answer : Type uAnswer}
    {Intent : Type uIntent}
    (results : List (WorldResult State Answer Intent)) (index : Nat) :
    Option (Committed State Answer Intent) :=
  (results[index]?).map WorldResult.commit

/-- Discarding speculative worlds preserves the parent state. -/
def discardWorlds {State : Type uState} {Answer : Type uAnswer}
    {Intent : Type uIntent}
    (parent : State) (_results : List (WorldResult State Answer Intent)) : State :=
  parent

@[simp] theorem selectCommit_zero {State : Type uState} {Answer : Type uAnswer}
    {Intent : Type uIntent} (head : WorldResult State Answer Intent)
    (tail : List (WorldResult State Answer Intent)) :
    selectCommit (head :: tail) 0 = some head.commit :=
  rfl

@[simp] theorem selectCommit_succ {State : Type uState} {Answer : Type uAnswer}
    {Intent : Type uIntent} (head : WorldResult State Answer Intent)
    (tail : List (WorldResult State Answer Intent)) (index : Nat) :
    selectCommit (head :: tail) (index + 1) = selectCommit tail index := by
  simp [selectCommit]

@[simp] theorem discardWorlds_eq_parent {State : Type uState}
    {Answer : Type uAnswer} {Intent : Type uIntent}
    (parent : State) (results : List (WorldResult State Answer Intent)) :
    discardWorlds parent results = parent :=
  rfl

/-! ## Separating controls -/

namespace Canary

/-- One branch reads a counter and then increments it. -/
def incrementOnce : Program Nat Nat Unit :=
  .read fun seen => .write (seen + 1) (.pure seen)

/-- The same increment is offered twice as alternatives. -/
def twoIncrements : Program Nat Nat Unit :=
  .choose incrementOnce incrementOnce

/-- Isolated alternatives both see their common parent. -/
theorem isolated_increments :
    runWorlds twoIncrements 0 =
      [{ branch := [false], answer := 0, state := 1, intents := [] },
       { branch := [true], answer := 0, state := 1, intents := [] }] :=
  rfl

/-- Shared alternatives communicate through the ambient state. -/
theorem shared_increments :
    runShared twoIncrements 0 =
      { answers := [0, 1], state := 2, intents := [] } :=
  rfl

/-- The two handlers are observably different on one computation. -/
theorem shared_and_isolated_are_distinct :
    (runWorlds twoIncrements 0).map WorldResult.answer !=
      (runShared twoIncrements 0).answers := by
  decide

/-- Two alternatives request different irreversible actions. -/
def twoDeferredIntents : Program Nat Nat Bool :=
  .choose
    (.intent false (.write 1 (.pure 10)))
    (.intent true (.write 2 (.pure 20)))

/-- Exploration retains both intent batches without performing either. -/
theorem both_intents_are_retained :
    runWorlds twoDeferredIntents 0 =
      [{ branch := [false], answer := 10, state := 1, intents := [false] },
       { branch := [true], answer := 20, state := 2, intents := [true] }] :=
  rfl

/-- Selecting the first occurrence exposes no intent from the losing world. -/
theorem selected_commit_excludes_loser_intent :
    (selectCommit (runWorlds twoDeferredIntents 0) 0).map Committed.intents =
      some [false] :=
  rfl

/-- Discarding both speculative worlds cannot alter the parent. -/
theorem discarded_worlds_do_not_commit :
    discardWorlds 0 (runWorlds twoDeferredIntents 0) = 0 :=
  rfl

/-- Authored enumeration is semantic under the shared handler. -/
def writeThenRead : Program Nat Nat Unit :=
  .choose (.write 1 (.pure 10)) (.read fun seen => .pure seen)

/-- The same alternatives in the opposite authored order. -/
def readThenWrite : Program Nat Nat Unit :=
  .choose (.read fun seen => .pure seen) (.write 1 (.pure 10))

/-- Reversing shared alternatives changes what the read observes. -/
theorem shared_choice_order_is_observable :
    (runShared writeThenRead 0).answers = [10, 1] /\
      (runShared readThenWrite 0).answers = [0, 10] :=
  And.intro rfl rfl

end Canary

/-! ## Axiom audit -/

#print axioms Canary.shared_and_isolated_are_distinct
#print axioms Canary.selected_commit_excludes_loser_intent
#print axioms Canary.shared_choice_order_is_observable

end Mettapedia.GSLT.Dynamics.ContextualEffectHandlers
