import Mettapedia.GSLT.Core.GSLT

/-!
# Relational answer evaluation as a GSLT

Open and nondeterministic languages often expose evaluation as a relation

`Evaluates initial request final answers`

rather than as a total function.  The result list contains additional
observable structure: an empty list is a completed run with no answers, list
order may be operationally significant, and duplicate answers are distinct
occurrences.

This module turns that richer relation into a two-stage GSLT:

```
request initial input
  --> completed initial input final answers
  --> answer initial input final answers occurrence
```

The first edge is licensed by the evaluation relation.  The second selects an
exact `Fin answers.length` occurrence, so order and duplicate answer
multiplicity are not quotiented away.  Keeping completion separate from
occurrence emission is essential: a successful empty run remains observable
even though it emits no answer.

The relation itself is `Prop`-valued.  Thus this construction preserves run
endpoints, state, complete answer lists, and answer occurrences, but does not
claim to distinguish multiple derivation proofs with identical run data.  A
future derivation-reified source can enrich this interface without changing
the occurrence layer.
-/

namespace Mettapedia.GSLT.Dynamics.RelationalAnswerEvaluation

open Mettapedia.GSLT

universe uState uRequest uAnswer

/-- A relational evaluator with state change and ordered answer lists. -/
structure RelationalAnswerSource (State : Type uState)
    (Request : Type uRequest) (Answer : Type uAnswer) where
  Evaluates : State → Request → State → List Answer → Prop

variable {State : Type uState} {Request : Type uRequest}
  {Answer : Type uAnswer}

namespace RelationalAnswerSource

/-- One evaluator refines another when it retains every completed run,
including final state and the complete ordered answer list. -/
def Refines (first second : RelationalAnswerSource State Request Answer) : Prop :=
  ∀ initial request final answers,
    first.Evaluates initial request final answers →
      second.Evaluates initial request final answers

/-- No completed runs: the neutral source for additive profile assembly. -/
def empty : RelationalAnswerSource State Request Answer where
  Evaluates := fun _ _ _ _ => False

/-- Additive composition of two operational fragments on the same carrier.

This construction adds alternatives without choosing a privileged fragment.
It intentionally promises only forward simulation of each component: an
extension may add a new run between endpoints already present in the base, so
generic reflection would be false. -/
def union (first second : RelationalAnswerSource State Request Answer) :
    RelationalAnswerSource State Request Answer where
  Evaluates := fun initial request final answers =>
    first.Evaluates initial request final answers ∨
      second.Evaluates initial request final answers

theorem refines_refl (source : RelationalAnswerSource State Request Answer) :
    source.Refines source :=
  fun _ _ _ _ evaluation => evaluation

theorem refines_trans {first second third :
    RelationalAnswerSource State Request Answer}
    (firstSecond : first.Refines second) (secondThird : second.Refines third) :
    first.Refines third :=
  fun _ _ _ _ evaluation =>
    secondThird _ _ _ _ (firstSecond _ _ _ _ evaluation)

theorem empty_refines (source : RelationalAnswerSource State Request Answer) :
    empty.Refines source := by
  intro initial request final answers impossible
  exact impossible.elim

theorem refines_union_left
    (first second : RelationalAnswerSource State Request Answer) :
    first.Refines (first.union second) :=
  fun _ _ _ _ evaluation => Or.inl evaluation

theorem refines_union_right
    (first second : RelationalAnswerSource State Request Answer) :
    second.Refines (first.union second) :=
  fun _ _ _ _ evaluation => Or.inr evaluation

/-- Union is the least common refinement at the relational level. -/
theorem union_least {first second target :
    RelationalAnswerSource State Request Answer}
    (firstTarget : first.Refines target) (secondTarget : second.Refines target) :
    (first.union second).Refines target := by
  intro initial request final answers evaluation
  cases evaluation with
  | inl firstEvaluation =>
      exact firstTarget _ _ _ _ firstEvaluation
  | inr secondEvaluation =>
      exact secondTarget _ _ _ _ secondEvaluation

end RelationalAnswerSource

/-- Terms of the operational theory generated by a relational evaluator.

`completed` deliberately records even an empty answer list.  `answer` records
the whole completed run and an exact occurrence in its ordered list. -/
inductive EvaluationTerm
    (source : RelationalAnswerSource State Request Answer) where
  | request (initial : State) (request : Request)
  | completed (initial : State) (request : Request)
      (final : State) (answers : List Answer)
  | answer (initial : State) (request : Request)
      (final : State) (answers : List Answer)
      (occurrence : Fin answers.length)

namespace EvaluationTerm

/-- The value selected by an occurrence term. -/
def selectedAnswer {source : RelationalAnswerSource State Request Answer} :
    EvaluationTerm source → Option Answer
  | .answer _ _ _ answers occurrence => some (answers.get occurrence)
  | _ => none

/-- Re-index an operational term along a change of evaluator.  All observable
run data is retained; only the source relation that licenses first-stage edges
changes. -/
def rebase {first : RelationalAnswerSource State Request Answer}
    (second : RelationalAnswerSource State Request Answer) :
    EvaluationTerm first → EvaluationTerm second
  | .request initialState input => .request initialState input
  | .completed initialState input finalState answers =>
      .completed initialState input finalState answers
  | .answer initialState input finalState answers occurrence =>
      .answer initialState input finalState answers occurrence

/-- Rebasing is injective because it changes no operational data. -/
theorem rebase_injective
    {first second : RelationalAnswerSource State Request Answer} :
    Function.Injective (rebase second : EvaluationTerm first → EvaluationTerm second) := by
  intro left right equal
  cases left <;> cases right <;> cases equal <;> rfl

@[simp] theorem selectedAnswer_answer
    {source : RelationalAnswerSource State Request Answer}
    (initial : State) (request : Request) (final : State)
    (answers : List Answer) (occurrence : Fin answers.length) :
    selectedAnswer (.answer initial request final answers occurrence :
      EvaluationTerm source) = some (answers.get occurrence) :=
  rfl

end EvaluationTerm

/-- The two kinds of edge generated by relational evaluation.

The `completed` constructor requires evidence of the evaluation relation.
The `emitted` constructor exposes one ordered occurrence without adding a
second source of evaluation authority. -/
inductive EvaluationStep (source : RelationalAnswerSource State Request Answer) :
    EvaluationTerm source → EvaluationTerm source → Prop where
  | completed {initial request final answers}
      (evaluation : source.Evaluates initial request final answers) :
      EvaluationStep source (.request initial request)
        (.completed initial request final answers)
  | emitted {initial request final answers}
      (occurrence : Fin answers.length) :
      EvaluationStep source (.completed initial request final answers)
        (.answer initial request final answers occurrence)

/-- The canonical GSLT generated by a relational answer evaluator. -/
def evaluationGSLT (source : RelationalAnswerSource State Request Answer) : GSLT where
  Term := EvaluationTerm source
  equations := ⟨Eq, ⟨Eq.refl, Eq.symm, Eq.trans⟩⟩
  rewrites := EvaluationStep source
  rewrites_resp_left := by
    intro first first' second equal step
    subst first'
    exact ⟨second, step, rfl⟩
  rewrites_resp_right := by
    intro first second second' step equal
    subst second'
    exact step

/-- Refining an evaluator forward-simulates every generated GSLT step.  This
is the correct generic comparison for additive language/profile extension;
reflection requires a separate conservativity theorem and is not assumed. -/
theorem step_rebase_of_refines
    {first second : RelationalAnswerSource State Request Answer}
    (refines : first.Refines second)
    {source target : (evaluationGSLT first).Term}
    (step : (evaluationGSLT first).Step source target) :
    (evaluationGSLT second).Step (source.rebase second) (target.rebase second) := by
  cases step with
  | completed evaluation =>
      simpa [GSLT.Step, evaluationGSLT, EvaluationTerm.rebase] using
        (EvaluationStep.completed (source := second)
          (refines _ _ _ _ evaluation))
  | emitted occurrence =>
      simpa [GSLT.Step, evaluationGSLT, EvaluationTerm.rebase] using
        (EvaluationStep.emitted (source := second) occurrence)

@[simp] theorem request_step_completed_iff
    (source : RelationalAnswerSource State Request Answer)
    (initial : State) (request : Request) (final : State)
    (answers : List Answer) :
    (evaluationGSLT source).Step (.request initial request)
        (.completed initial request final answers) ↔
      source.Evaluates initial request final answers := by
  constructor
  · intro step
    cases step with
    | completed evaluation => exact evaluation
  · exact EvaluationStep.completed

@[simp] theorem completed_step_answer
    (source : RelationalAnswerSource State Request Answer)
    (initial : State) (request : Request) (final : State)
    (answers : List Answer) (occurrence : Fin answers.length) :
    (evaluationGSLT source).Step
      (.completed initial request final answers)
      (.answer initial request final answers occurrence) :=
  EvaluationStep.emitted occurrence

/-- Request-to-completion is the only first-stage edge shape. -/
theorem request_step_iff_exists_evaluation
    (source : RelationalAnswerSource State Request Answer)
    (initial : State) (request : Request) (target : (evaluationGSLT source).Term) :
    (evaluationGSLT source).Step (.request initial request) target ↔
      ∃ final answers,
        target = .completed initial request final answers ∧
          source.Evaluates initial request final answers := by
  constructor
  · intro step
    cases step with
    | completed evaluation => exact ⟨_, _, rfl, evaluation⟩
  · rintro ⟨final, answers, rfl, evaluation⟩
    exact EvaluationStep.completed evaluation

/-- Completion-to-answer is the only second-stage edge shape. -/
theorem completed_step_iff_exists_occurrence
    (source : RelationalAnswerSource State Request Answer)
    (initial : State) (request : Request) (final : State)
    (answers : List Answer) (target : (evaluationGSLT source).Term) :
    (evaluationGSLT source).Step
        (.completed initial request final answers) target ↔
      ∃ occurrence : Fin answers.length,
        target = .answer initial request final answers occurrence := by
  constructor
  · intro step
    cases step with
    | emitted occurrence => exact ⟨occurrence, rfl⟩
  · rintro ⟨occurrence, rfl⟩
    exact EvaluationStep.emitted occurrence

/-- Successful evaluation with no answers is distinct from failure to
evaluate: it has a completion edge, and that completion is terminal. -/
theorem empty_completion_isNormalForm
    (source : RelationalAnswerSource State Request Answer)
    (initial : State) (request : Request) (final : State) :
    (evaluationGSLT source).IsNormalForm
      (.completed initial request final []) := by
  rintro ⟨target, step⟩
  cases step with
  | emitted occurrence => exact Fin.elim0 occurrence

/-- Emitted answer occurrences are terminal. -/
theorem answer_isNormalForm
    (source : RelationalAnswerSource State Request Answer)
    (initial : State) (request : Request) (final : State)
    (answers : List Answer) (occurrence : Fin answers.length) :
    (evaluationGSLT source).IsNormalForm
      (.answer initial request final answers occurrence) := by
  rintro ⟨target, step⟩
  cases step

/-- A nonempty completed answer list always admits a second-stage edge. -/
theorem nonempty_completion_isRedex
    (source : RelationalAnswerSource State Request Answer)
    (initial : State) (request : Request) (final : State)
    (answers : List Answer) (nonempty : answers ≠ []) :
    (evaluationGSLT source).IsRedex
      (.completed initial request final answers) := by
  cases answers with
  | nil => exact (nonempty rfl).elim
  | cons answer rest =>
      let occurrence : Fin (answer :: rest).length := ⟨0, by simp⟩
      exact ⟨.answer initial request final (answer :: rest) occurrence,
        EvaluationStep.emitted occurrence⟩

/-- Two different positions remain different operational terms even when
they select extensionally equal answer values. -/
theorem answer_occurrence_injective
    (source : RelationalAnswerSource State Request Answer)
    (initial : State) (request : Request) (final : State)
    (answers : List Answer) :
    Function.Injective
      (fun occurrence : Fin answers.length =>
        (EvaluationTerm.answer initial request final answers occurrence :
          EvaluationTerm source)) := by
  intro first second equal
  cases equal
  rfl

end Mettapedia.GSLT.Dynamics.RelationalAnswerEvaluation
