import Mettapedia.GSLT.Core.ClosureCriteria
import Mettapedia.GSLT.Core.OpenTotalityObservation
import Mettapedia.GSLT.Dynamics.SpaceActivationPolicy

/-!
# Space activation is independent of execution closure

An activation policy says which resident occurrences may take one labeled
step.  It does not say which enabled step a controller selects, how many steps
the controller performs, or whether an observation may claim quiescence.

This file connects the existing activation-policy and bounded-driver layers
without identifying them:

* every policy has a GSLT whose rewrites are exactly its labeled steps;
* an activation driver selects exact policy steps and therefore introduces no
  object transition;
* finite closure carries evidence that a bounded run actually completed;
* a bounded observation reports completion or exhaustion without turning an
  exhausted empty prefix into refutation.

The canary is a two-tick machine.  One tick performs a valid activation but
leaves another activation available.  Two ticks reach quiescence.  Thus a VM
tick, a triggered evaluation, and rho-style communication can all inhabit the
same one-step interface while retaining separately authored closure and
observation policies.
-/

set_option autoImplicit false

namespace Mettapedia.GSLT.Dynamics.SpaceExecutionClosureBoundary

open Mettapedia.GSLT
open Mettapedia.GSLT.Core.ClosureCriteria
open Mettapedia.GSLT.Core.OpenTotalityObservation
open Mettapedia.GSLT.Dynamics.SpaceActivationPolicy

universe uStore uOccurrence uTrigger uObservation uReceipt uControl uObservedOccurrence

/-! ## The policy relation as an object GSLT -/

/-- The object theory generated by one activation policy.  Its terms are
physical stores and its one-step relation forgets only the activation label
and receipt.  Existential forgetting preserves every possible policy step;
it does not select a scheduler. -/
def policyGSLT
    {Store : Type uStore} {Occurrence : Type uOccurrence}
    {Trigger : Type uTrigger} {Observation : Type uObservation}
    {Receipt : Type uReceipt}
    (policy : Policy Store Occurrence Trigger Observation Receipt) : GSLT where
  Term := Store
  equations := ⟨Eq, ⟨Eq.refl, Eq.symm, Eq.trans⟩⟩
  rewrites := fun source target =>
    ∃ cause receipt, policy.step source cause target receipt
  rewrites_resp_left := by
    intro source source' target equal step
    subst source'
    exact ⟨target, step, rfl⟩
  rewrites_resp_right := by
    intro source target target' step equal
    subst target'
    exact step

@[simp] theorem policyGSLT_step_iff
    {Store : Type uStore} {Occurrence : Type uOccurrence}
    {Trigger : Type uTrigger} {Observation : Type uObservation}
    {Receipt : Type uReceipt}
    (policy : Policy Store Occurrence Trigger Observation Receipt)
    (source target : Store) :
    (policyGSLT policy).Step source target ↔
      ∃ cause receipt, policy.step source cause target receipt :=
  Iff.rfl

/-- An inert data policy induces a theory with no rewrites.  Residency and
observation therefore do not silently imply evaluation. -/
theorem inert_policy_is_normal
    {Store : Type uStore} {Occurrence : Type uOccurrence}
    {Trigger : Type uTrigger} {Observation : Type uObservation}
    {Receipt : Type uReceipt}
    (resident : Store → Occurrence → Prop)
    (observe : Store → Observation) (store : Store) :
    (policyGSLT
      (Policy.inert (Receipt := Receipt) (Trigger := Trigger)
        resident observe)).IsNormalForm store := by
  rintro ⟨target, cause, receipt, step⟩
  exact step

/-! ## A scheduler is selected evidence, not another semantics -/

/-- One controller-selected move, retaining the exact policy cause and
receipt which justify the physical transition. -/
structure SelectedMove
    {Store : Type uStore} {Occurrence : Type uOccurrence}
    {Trigger : Type uTrigger} {Observation : Type uObservation}
    {Receipt : Type uReceipt}
    (policy : Policy Store Occurrence Trigger Observation Receipt)
    (source : Store) (Control : Type uControl) where
  cause : Cause Trigger Occurrence
  target : Store
  receipt : Receipt
  nextControl : Control
  realized : policy.step source cause target receipt

/-- A deterministic controller selecting at most one exact activation at a
configuration.  The policy itself remains relational and may retain many
alternatives; this structure is one authored selector over that relation. -/
structure ActivationDriver
    {Store : Type uStore} {Occurrence : Type uOccurrence}
    {Trigger : Type uTrigger} {Observation : Type uObservation}
    {Receipt : Type uReceipt}
    (policy : Policy Store Occurrence Trigger Observation Receipt) where
  State : Type uControl
  select : (source : Store) → State →
    Option (SelectedMove policy source State)

namespace ActivationDriver

variable {Store : Type uStore} {Occurrence : Type uOccurrence}
variable {Trigger : Type uTrigger} {Observation : Type uObservation}
variable {Receipt : Type uReceipt}
variable {policy : Policy Store Occurrence Trigger Observation Receipt}

/-- Forget labels only after the selected move has supplied its exact policy
proof.  The resulting hosted driver is sound by construction. -/
def toHostedDriver (driver : ActivationDriver policy) :
    HostedDriver (policyGSLT policy) where
  State := driver.State
  step source control :=
    (driver.select source control).map fun move =>
      (move.target, move.nextControl)
  sound := by
    intro source control target nextControl moved
    cases selected : driver.select source control with
    | none =>
        simp [selected] at moved
    | some move =>
        simp [selected] at moved
        rcases moved with ⟨rfl, rfl⟩
        exact ⟨move.cause, move.receipt, move.realized⟩

@[simp] theorem toHostedDriver_step
    (driver : ActivationDriver policy) (source : Store)
    (control : driver.State) :
    driver.toHostedDriver.step source control =
      (driver.select source control).map fun move =>
        (move.target, move.nextControl) :=
  rfl

/-- Evidence that a particular selected execution reaches an actually
quiescent configuration in finite time.  Termination is not a field of the
activation policy; it is earned by this run-specific witness. -/
structure FiniteClosure (driver : ActivationDriver policy)
    (source : Store) (initialControl : driver.State) where
  fuel : Nat
  target : Store
  finalControl : driver.State
  completed :
    driver.toHostedDriver.runReport source initialControl fuel =
      .completed target finalControl

namespace FiniteClosure

/-- A finite-closure target is quiescent for the selected driver. -/
theorem target_quiescent
    {driver : ActivationDriver policy} {source : Store}
    {initialControl : driver.State}
    (closure : FiniteClosure driver source initialControl) :
    driver.toHostedDriver.step closure.target closure.finalControl = none :=
  driver.toHostedDriver.runReport_completed_quiescent closure.completed

/-- A finite closure retains object-level reachability through exact policy
steps. -/
theorem target_reachable
    {driver : ActivationDriver policy} {source : Store}
    {initialControl : driver.State}
    (closure : FiniteClosure driver source initialControl) :
    (policyGSLT policy).MultiStep source closure.target := by
  have reachable := driver.toHostedDriver.runReport_multiStep
    closure.fuel source initialControl
  simpa [closure.completed] using reachable

end FiniteClosure

/-! ## Honest bounded observations -/

/-- Coverage carried by a closed driver observation. -/
structure QuiescentCoverage (driver : ActivationDriver policy) where
  store : Store
  control : driver.State
  quiescent : driver.toHostedDriver.step store control = none

/-- An exact receipt for one bounded driver invocation. -/
structure ExactRunReceipt (driver : ActivationDriver policy) where
  source : Store
  initialControl : driver.State
  fuel : Nat
  report : BoundedRunReport Store driver.State
  exact : report =
    driver.toHostedDriver.runReport source initialControl fuel

/-- The open-totality observation type for a selected activation driver.
Capture admission remains caller-authored; the base adapter below never
claims that a residual is safe to externalize. -/
abbrev RunObservation
    (driver : ActivationDriver policy)
    (ObservedOccurrence : Type uObservedOccurrence)
    (CaptureAdmitted : (Store × driver.State) → Unit → Prop) :=
  Mettapedia.GSLT.Core.OpenTotalityObservation.Observation ObservedOccurrence
    (Store × driver.State) Unit (QuiescentCoverage driver) Nat
    (ExactRunReceipt driver) Empty CaptureAdmitted

/-- Observe an exact bounded run.  Completion contains a quiescence witness;
exhaustion contains the exact residual report but exports no resumable state
without a separate capture-admission proof. -/
def observeBoundedRun
    (driver : ActivationDriver policy)
    {ObservedOccurrence : Type uObservedOccurrence}
    {CaptureAdmitted : (Store × driver.State) → Unit → Prop}
    (occurrences : List ObservedOccurrence)
    (source : Store) (initialControl : driver.State) (fuel : Nat) :
    RunObservation driver ObservedOccurrence CaptureAdmitted :=
  match reportEquation :
      driver.toHostedDriver.runReport source initialControl fuel with
  | .completed target finalControl =>
      Mettapedia.GSLT.Core.OpenTotalityObservation.Observation.withoutCapture
        occurrences
        (.closed
          { store := target
            control := finalControl
            quiescent :=
              driver.toHostedDriver.runReport_completed_quiescent
                reportEquation })
  | .expired target finalControl =>
      Mettapedia.GSLT.Core.OpenTotalityObservation.Observation.withoutCapture
        occurrences
        (.exhausted fuel
          { source := source
            initialControl := initialControl
            fuel := fuel
            report := .expired target finalControl
            exact := reportEquation.symm })

@[simp] theorem observeBoundedRun_occurrences
    (driver : ActivationDriver policy)
    {ObservedOccurrence : Type uObservedOccurrence}
    {CaptureAdmitted : (Store × driver.State) → Unit → Prop}
    (occurrences : List ObservedOccurrence)
    (source : Store) (initialControl : driver.State) (fuel : Nat) :
    (observeBoundedRun driver (CaptureAdmitted := CaptureAdmitted)
      occurrences source initialControl fuel).occurrences = occurrences := by
  unfold observeBoundedRun
  split <;> rfl

/-- Once a caller separately proves capture admission for the exact expired
configuration, the residual can be exported without changing its exhaustion
status. -/
def captureExpiredRun
    (driver : ActivationDriver policy)
    {ObservedOccurrence : Type uObservedOccurrence}
    {CaptureAdmitted : (Store × driver.State) → Unit → Prop}
    (occurrences : List ObservedOccurrence)
    (source : Store) (initialControl : driver.State) (fuel : Nat)
    (target : Store) (finalControl : driver.State)
    (expired :
      driver.toHostedDriver.runReport source initialControl fuel =
        .expired target finalControl)
    (admitted : CaptureAdmitted (target, finalControl) ()) :
    RunObservation driver ObservedOccurrence CaptureAdmitted :=
  Mettapedia.GSLT.Core.OpenTotalityObservation.Observation.exhaustedCaptured
    occurrences fuel
    { source := source
      initialControl := initialControl
      fuel := fuel
      report := .expired target finalControl
      exact := expired.symm }
    (target, finalControl) () admitted

@[simp] theorem captureExpiredRun_resume
    (driver : ActivationDriver policy)
    {ObservedOccurrence : Type uObservedOccurrence}
    {CaptureAdmitted : (Store × driver.State) → Unit → Prop}
    (occurrences : List ObservedOccurrence)
    (source : Store) (initialControl : driver.State) (fuel : Nat)
    (target : Store) (finalControl : driver.State)
    (expired :
      driver.toHostedDriver.runReport source initialControl fuel =
        .expired target finalControl)
    (admitted : CaptureAdmitted (target, finalControl) ()) :
    (captureExpiredRun driver occurrences source initialControl fuel target
      finalControl expired admitted).resume? =
        some ((target, finalControl), ()) :=
  rfl

end ActivationDriver

/-! ## A two-tick discriminator -/

namespace Canary

inductive Phase where
  | start
  | middle
  | done
deriving DecidableEq, Repr

inductive Worker where
  | advance
deriving DecidableEq, Repr

inductive Receipt where
  | advanced
deriving DecidableEq, Repr

abbrev TickCause := Cause Unit Worker

def tick : TickCause := .requested () .advance

def resident (_phase : Phase) (worker : Worker) : Prop := worker = .advance

inductive TickStep : Phase → TickCause → Phase → Receipt → Prop where
  | first : TickStep .start tick .middle .advanced
  | second : TickStep .middle tick .done .advanced

def tickPolicy : Policy Phase Worker Unit Phase Receipt where
  resident := resident
  enabled source cause := ∃ target receipt, TickStep source cause target receipt
  step := TickStep
  step_enabled step := ⟨_, _, step⟩
  enabled_supported := by
    intro source cause enabled
    rcases enabled with ⟨target, receipt, step⟩
    cases step <;> simp [Cause.Supported, resident, tick]
  observe := id

def tickDriver : ActivationDriver tickPolicy where
  State := Unit
  select source _control :=
    match source with
    | .start =>
        some
          { cause := tick
            target := .middle
            receipt := .advanced
            nextControl := ()
            realized := .first }
    | .middle =>
        some
          { cause := tick
            target := .done
            receipt := .advanced
            nextControl := ()
            realized := .second }
    | .done => none

theorem both_ticks_are_policy_steps :
    tickPolicy.step .start tick .middle .advanced ∧
      tickPolicy.step .middle tick .done .advanced :=
  ⟨TickStep.first, TickStep.second⟩

/-- One VM-style tick is a valid activation but not closure. -/
theorem one_tick_expires :
    tickDriver.toHostedDriver.runReport .start () 1 =
      .expired .middle () :=
  rfl

/-- A second tick reaches an inspected quiescent configuration. -/
theorem two_ticks_complete :
    tickDriver.toHostedDriver.runReport .start () 2 =
      .completed .done () :=
  rfl

def twoTickClosure : ActivationDriver.FiniteClosure tickDriver .start () where
  fuel := 2
  target := .done
  finalControl := ()
  completed := two_ticks_complete

theorem two_tick_target_is_reachable_and_quiescent :
    (policyGSLT tickPolicy).MultiStep .start .done ∧
      tickDriver.toHostedDriver.step .done () = none :=
  ⟨twoTickClosure.target_reachable, twoTickClosure.target_quiescent⟩

/-- Negative control: a valid one-step tick cannot present itself as a closed
run while another tick remains enabled. -/
theorem one_tick_cannot_claim_closure :
    ¬ ∃ target control,
      tickDriver.toHostedDriver.runReport .start () 1 =
        .completed target control := by
  simp [tickDriver, ActivationDriver.toHostedDriver,
    HostedDriver.runReport]

def oneTickObservation :
    ActivationDriver.RunObservation tickDriver Unit
      (fun _configuration _revision => False) :=
  tickDriver.observeBoundedRun [] .start () 1

def twoTickObservation :
    ActivationDriver.RunObservation tickDriver Unit
      (fun _configuration _revision => False) :=
  tickDriver.observeBoundedRun [] .start () 2

/-- Even an empty answer prefix at the one-tick boundary is exhaustion, not
closed absence. -/
theorem one_tick_empty_prefix_is_not_refutation :
    ¬ oneTickObservation.EstablishesClosedAbsence := by
  rintro ⟨_empty, coverage, completion⟩
  cases completion

/-- The same activation policy supports a bounded open observation and a
closed quiescent observation.  Therefore activation does not determine the
execution extent or the observer's closure claim. -/
theorem activation_does_not_determine_closure :
    oneTickObservation.completion ≠ twoTickObservation.completion := by
  intro equal
  cases equal

/-- A quiescent configuration remains complete under every later budget. -/
theorem done_completes_at_every_fuel (fuel : Nat) :
    tickDriver.toHostedDriver.runReport .done () fuel =
      .completed .done () :=
  tickDriver.toHostedDriver.runReport_of_quiescent rfl fuel

/-- A communication capability inhabits the same object-step boundary as a
requested tick, without being identified with it. -/
theorem communication_is_an_object_step :
    (policyGSLT SpaceActivationPolicy.Canary.communication).Step
      [.send, .receive] [.result] :=
  ⟨Cause.communication .send .receive,
    SpaceActivationPolicy.Canary.Receipt.communicated,
    SpaceActivationPolicy.Canary.communication_can_fire⟩

end Canary

#print axioms policyGSLT_step_iff
#print axioms inert_policy_is_normal
#print axioms ActivationDriver.FiniteClosure.target_quiescent
#print axioms ActivationDriver.FiniteClosure.target_reachable
#print axioms ActivationDriver.observeBoundedRun_occurrences
#print axioms ActivationDriver.captureExpiredRun_resume
#print axioms Canary.both_ticks_are_policy_steps
#print axioms Canary.one_tick_expires
#print axioms Canary.two_ticks_complete
#print axioms Canary.two_tick_target_is_reachable_and_quiescent
#print axioms Canary.one_tick_cannot_claim_closure
#print axioms Canary.one_tick_empty_prefix_is_not_refutation
#print axioms Canary.activation_does_not_determine_closure
#print axioms Canary.done_completes_at_every_fuel
#print axioms Canary.communication_is_an_object_step

end Mettapedia.GSLT.Dynamics.SpaceExecutionClosureBoundary
