import Mettapedia.GSLT.Core.GSLT
import Mettapedia.OSLF.Framework.DerivedModalities
import Mettapedia.OSLF.Framework.RewriteSystem

/-!
# OSLF synthesis from an abstract GSLT

The concrete `LanguageDef` synthesis builds its reduction span from the
MeTTaIL reduction engine.  At the mathematical boundary, however, OSLF needs
only the reduction relation of a GSLT.  This module records that direct route:
every GSLT supplies a reduction span, hence the derived diamond/box adjunction.

The construction does not make a relation executable.  Executable evidence
for an edge is a separate proof/checker authority.  This separation is what
allows one OSLF trace theory to cover syntactic rewriting, collection
decomposition, reflective queries, and capability-backed steps without
pretending that all of them use the same matcher.
-/

namespace Mettapedia.OSLF.Framework.GSLTTypeSynthesis

open Mettapedia.GSLT
open Mettapedia.OSLF.Framework.DerivedModalities
open Mettapedia.OSLF.Framework

universe uTheory

/-! ## The OSLF input generated by an abstract GSLT -/

/-- Regard an abstract GSLT as a one-sorted OSLF rewrite system.  Its
equations have already been accounted for by the GSLT step relation. -/
def gsltRewriteSystem (theory : GSLT.{uTheory}) : RewriteSystem where
  Sorts := Unit
  procSort := ()
  Term := fun _ => theory.Term
  Reduces := theory.Step

/-- The graph of the one-step relation of an arbitrary GSLT, as the reduction
span consumed by OSLF change-of-base. -/
def gsltSpan (theory : GSLT.{uTheory}) : ReductionSpan theory.Term where
  Edge := theory.LabeledStep
  source := GSLT.LabeledStep.source
  target := GSLT.LabeledStep.target

/-- Edges of the generated span are exactly GSLT one-step reductions. -/
theorem gsltSpan_edge_iff_step (theory : GSLT.{uTheory})
    (source target : theory.Term) :
    (∃ edge : (gsltSpan theory).Edge,
        (gsltSpan theory).source edge = source ∧
          (gsltSpan theory).target edge = target) ↔
      theory.Step source target := by
  constructor
  · rintro ⟨edge, sourceEq, targetEq⟩
    cases edge with
    | mk edgeSource edgeTarget step =>
        simp only [gsltSpan] at sourceEq targetEq
        subst sourceEq
        subst targetEq
        exact step
  · intro step
    exact ⟨⟨source, target, step⟩, rfl, rfl⟩

/-- OSLF step-future modality generated by a GSLT. -/
def gsltDiamond (theory : GSLT.{uTheory}) :
    (theory.Term → Prop) → theory.Term → Prop :=
  derivedDiamond (gsltSpan theory)

/-- OSLF step-past modality generated by a GSLT. -/
def gsltBox (theory : GSLT.{uTheory}) :
    (theory.Term → Prop) → theory.Term → Prop :=
  derivedBox (gsltSpan theory)

/-- The OSLF adjunction is generated for every GSLT without a
language-specific proof. -/
theorem gsltGalois (theory : GSLT.{uTheory}) :
    GaloisConnection (gsltDiamond theory) (gsltBox theory) :=
  derived_galois (gsltSpan theory)

/-- Concrete meaning of the generated diamond. -/
theorem gsltDiamond_spec (theory : GSLT.{uTheory})
    (predicate : theory.Term → Prop) (source : theory.Term) :
    gsltDiamond theory predicate source ↔
      ∃ target, theory.Step source target ∧ predicate target := by
  simp only [gsltDiamond, derivedDiamond, di, pb, Function.comp, gsltSpan]
  constructor
  · rintro ⟨edge, sourceEq, targetMeaning⟩
    exact ⟨edge.target, sourceEq ▸ edge.step, targetMeaning⟩
  · rintro ⟨target, step, targetMeaning⟩
    exact ⟨⟨source, target, step⟩, rfl, targetMeaning⟩

/-- An exact one-step claim is the generated diamond of the singleton target
predicate.  This is the OSLF/NTT meaning checked by a local step article. -/
theorem gsltDiamond_singleton_iff_step (theory : GSLT.{uTheory})
    (source target : theory.Term) :
    gsltDiamond theory (fun candidate => candidate = target) source ↔
      theory.Step source target := by
  rw [gsltDiamond_spec]
  constructor
  · rintro ⟨candidate, step, rfl⟩
    exact step
  · intro step
    exact ⟨target, step, rfl⟩

/-- Concrete meaning of the generated box.  OSLF's right adjoint is
predecessor-universal, matching the orientation of `derivedBox`. -/
theorem gsltBox_spec (theory : GSLT.{uTheory})
    (predicate : theory.Term → Prop) (target : theory.Term) :
    gsltBox theory predicate target ↔
      ∀ source, theory.Step source target → predicate source := by
  simp only [gsltBox, derivedBox, ui, pb, Function.comp, gsltSpan]
  constructor
  · intro universal source step
    exact universal ⟨source, target, step⟩ rfl
  · rintro universal ⟨source, edgeTarget, step⟩ targetEq
    simp only at targetEq
    subst targetEq
    exact universal source step

/-! ## The full predicate-valued OSLF result -/

/-- Run the abstract OSLF construction on any GSLT.  Native predicates are
all predicates on the GSLT carrier; diamond, box, and their adjunction are
generated solely from its reduction relation. -/
def gsltOSLF (theory : GSLT.{uTheory}) :
    OSLFTypeSystem (gsltRewriteSystem theory) where
  Pred := fun _ => theory.Term → Prop
  frame := fun _ => inferInstance
  satisfies := fun term predicate => predicate term
  diamond := gsltDiamond theory
  diamond_spec := gsltDiamond_spec theory
  box := gsltBox theory
  box_spec := gsltBox_spec theory
  galois := by
    intro first second
    have connection := (gsltGalois theory) first second
    simp only [Pi.le_def] at connection
    exact connection

/-- The rich OSLF native-type carrier generated from an abstract GSLT. -/
abbrev GSLTNativeType (theory : GSLT.{uTheory}) : Type _ :=
  NativeTypeOf (gsltOSLF theory)

/-- The exact-target behavioral native type generated for one target term. -/
def exactTargetNativeType (theory : GSLT.{uTheory}) (target : theory.Term) :
    GSLTNativeType theory where
  sort := ()
  pred := gsltDiamond theory (fun candidate => candidate = target)

/-- Inhabiting the exact-target native type is exactly one GSLT step. -/
theorem satisfies_exactTargetNativeType_iff_step (theory : GSLT.{uTheory})
    (source target : theory.Term) :
    (gsltOSLF theory).satisfies source
        (exactTargetNativeType theory target).pred ↔
      theory.Step source target :=
  gsltDiamond_singleton_iff_step theory source target

end Mettapedia.OSLF.Framework.GSLTTypeSynthesis
