import Mettapedia.GSLT.Logic.HennessyMilnerAdequacy
import Mettapedia.OSLF.Framework.GSLTTypeSynthesis

/-!
# Hennessy--Milner formulas as generated OSLF native types

The generic Hennessy--Milner theorem is stated for an explicit observation
set and labeled step family on a GSLT.  This module connects that theorem to
the native predicate carrier produced by the sole `GSLT -> OSLF`
construction: every full or positive formula denotes an actual generated
native type, and its OSLF satisfaction judgment is its Hennessy--Milner
semantics.

The scope of the adequacy result is deliberately exact.  It quantifies over
the native types generated by the Hennessy--Milner formula language, not over
every predicate on equation classes.  The latter family separates precisely
the equation classes and is therefore generally finer than bisimilarity.
The final canary below proves this boundary instead of hiding it in prose.
-/

set_option autoImplicit false

namespace Mettapedia.OSLF.Framework.HennessyMilnerNativeTypes

open Mettapedia.GSLT
open Mettapedia.GSLT.HennessyMilner
open Mettapedia.OSLF.Framework
open Mettapedia.OSLF.Framework.GSLTTypeSynthesis

universe uAtom uLabel

variable {S : GSLT} (M : System.{uAtom, uLabel} S)

/-! ## The full Hennessy--Milner fragment -/

/-- The invariant generated predicate denoted by a Hennessy--Milner formula. -/
def formulaPredicate (formula : Formula M.Atom M.Label) : EquationPredicate S :=
  invariantPredicate S (M.sat formula) (by
    intro left right equivalent
    exact M.sat_resp formula equivalent)

/-- A Hennessy--Milner formula presented as a native type of the generated
OSLF. -/
def formulaNativeType (formula : Formula M.Atom M.Label) : GSLTNativeType S where
  sort := ()
  pred := formulaPredicate M formula

/-- The native-type satisfaction judgment preserves and reflects formula
satisfaction. -/
@[simp]
theorem satisfies_formulaNativeType_iff
    (formula : Formula M.Atom M.Label) (term : S.Term) :
    (gsltOSLF S).satisfies (S := ()) term (formulaNativeType M formula).pred ↔
      M.sat formula term :=
  Iff.rfl

/-- Hennessy--Milner adequacy stated directly through the generated OSLF
native types. -/
theorem formulaNativeTypes_equivalent_iff_bisimilar
    (finite : M.ImageFiniteModulo) (left right : S.Term) :
    (∀ formula : Formula M.Atom M.Label,
      ((gsltOSLF S).satisfies (S := ()) left (formulaNativeType M formula).pred ↔
       (gsltOSLF S).satisfies (S := ()) right (formulaNativeType M formula).pred)) ↔
      M.Bisimilar left right := by
  change M.LogicallyEquivalent left right ↔ M.Bisimilar left right
  exact M.logicallyEquivalent_iff_bisimilar finite left right

/-! ## The positive fragment -/

/-- The invariant generated predicate denoted by a positive formula. -/
def positiveFormulaPredicate
    (formula : PosFormula M.Atom M.Label) : EquationPredicate S :=
  invariantPredicate S (M.psat formula) (by
    intro left right equivalent
    exact M.psat_resp formula equivalent)

/-- A positive formula presented as a native type of the generated OSLF. -/
def positiveFormulaNativeType
    (formula : PosFormula M.Atom M.Label) : GSLTNativeType S where
  sort := ()
  pred := positiveFormulaPredicate M formula

/-- Generated native-type satisfaction is exactly positive formula
satisfaction. -/
@[simp]
theorem satisfies_positiveFormulaNativeType_iff
    (formula : PosFormula M.Atom M.Label) (term : S.Term) :
    (gsltOSLF S).satisfies (S := ()) term
        (positiveFormulaNativeType M formula).pred ↔
      M.psat formula term :=
  Iff.rfl

/-- The preorder induced by the positive generated native types is exactly
the simulation preorder under image-finiteness modulo equations. -/
theorem positiveFormulaNativeTypes_preorder_iff_similar
    (finite : M.ImageFiniteModulo) (left right : S.Term) :
    (∀ formula : PosFormula M.Atom M.Label,
      (gsltOSLF S).satisfies (S := ()) left
          (positiveFormulaNativeType M formula).pred ->
        (gsltOSLF S).satisfies (S := ()) right
          (positiveFormulaNativeType M formula).pred) ↔
      M.Similar left right := by
  change M.LogicalPreorder left right ↔ M.Similar left right
  exact M.logicalPreorder_iff_similar finite left right

/-! ## The boundary: arbitrary predicates are not the HML fragment -/

/-- The generated native type naming exactly one equation class. -/
def equationClassNativeType (representative : S.Term) : GSLTNativeType S where
  sort := ()
  pred := invariantPredicate S (fun term => S.Equiv term representative) (by
    intro left right equivalent
    constructor
    · intro leftRepresentative
      exact S.equations.iseqv.trans
        (S.equations.iseqv.symm equivalent) leftRepresentative
    · intro rightRepresentative
      exact S.equations.iseqv.trans equivalent rightRepresentative)

/-- Agreement on every generated process native type is exactly equational
equivalence, not behavioral equivalence in general. -/
theorem allNativeTypes_equivalent_iff_equiv (left right : S.Term) :
    (∀ nativeType : GSLTNativeType S,
      ((gsltOSLF S).satisfies (S := ()) left nativeType.pred ↔
       (gsltOSLF S).satisfies (S := ()) right nativeType.pred)) ↔
      S.Equiv left right := by
  constructor
  · intro sameTypes
    have leftHolds :
        (gsltOSLF S).satisfies (S := ()) left
          (equationClassNativeType (S := S) left).pred :=
      S.equations.iseqv.refl left
    have rightHolds :=
      (sameTypes (equationClassNativeType (S := S) left)).mp leftHolds
    exact S.equations.iseqv.symm rightHolds
  · intro equivalent nativeType
    exact nativeType.pred.2 equivalent

/-- Negative canary: two bisimilar terms outside the same equation class are
necessarily separated by a generated native type, so adequacy must not be
claimed for the unrestricted predicate frame. -/
theorem bisimilar_not_equiv_not_allNativeTypes_equivalent
    {left right : S.Term} (bisimilar : M.Bisimilar left right)
    (notEquivalent : ¬ S.Equiv left right) :
    M.Bisimilar left right ∧
      ¬ (∀ nativeType : GSLTNativeType S,
        ((gsltOSLF S).satisfies (S := ()) left nativeType.pred ↔
         (gsltOSLF S).satisfies (S := ()) right nativeType.pred)) := by
  refine ⟨bisimilar, ?_⟩
  intro sameTypes
  exact notEquivalent ((allNativeTypes_equivalent_iff_equiv (S := S) left right).mp sameTypes)

#print axioms satisfies_formulaNativeType_iff
#print axioms formulaNativeTypes_equivalent_iff_bisimilar
#print axioms satisfies_positiveFormulaNativeType_iff
#print axioms positiveFormulaNativeTypes_preorder_iff_similar
#print axioms allNativeTypes_equivalent_iff_equiv
#print axioms bisimilar_not_equiv_not_allNativeTypes_equivalent

end Mettapedia.OSLF.Framework.HennessyMilnerNativeTypes
