import Mettapedia.OSLF.Framework.TypeSynthesis
import Mettapedia.GSLT.Core.NonFactorization

/-!
# Native types: the type theory a language already has

OSLF derives a language's behavioural modalities from its own reduction
relation — `langDiamond` and `langBox` in `TypeSynthesis`, with their Galois
connection falling out automatically.  What that leaves unsaid is the
*spatial* half: the types that come from the term grammar rather than from
reduction, and how the two combine.

This module takes the first step of OSLF → native type theory by naming that
combined type language and giving it a semantics, and then answering the
question the language-purity work needs:

> Which typing judgments are *derived* from a `LanguageDef`, and which are
> genuinely authored information?

The answer is a construction rather than a judgement call.

* **Native types are derived.**  `satisfies_congr` shows the whole semantics
  depends on the language **only through its step relation** — spatial
  formers from the constructors, modal formers from reduction, nothing else.
  So a native type is a *view* of the core fields, never extension data.

* **Authored typing is not.**  `authored_typing_not_determined_by_language`
  exhibits two different typing relations over one and the same language.
  Typing therefore does not factor through the `LanguageDef`, which is
  exactly what makes an authored type system genuine new information rather
  than a redundant restatement.

Those two together are the derivable/residual boundary the extension
architecture needs, and they are the reason a proof calculus belongs in a
fibre over the core rather than inside it: the part that *is* determined is
already available without being stored, and the part that is stored is
provably not determined.
-/

namespace Mettapedia.OSLF.Framework.NativeTypeTheory

open Mettapedia.OSLF.MeTTaIL.Syntax
open Mettapedia.OSLF.Framework
open Mettapedia.OSLF.Framework.TypeSynthesis
open Mettapedia.OSLF.Framework.DerivedModalities
open Mettapedia.GSLT.Core.NonFactorization

/-! ## The native type language

Spatial formers name a constructor and constrain its arguments; modal formers
reuse the operators OSLF already derives; the rest is ordinary propositional
structure. -/

/-- A type of the native theory of some language. -/
inductive NativeType where
  /-- Every term. -/
  | top
  /-- No term. -/
  | bot
  /-- Both. -/
  | and (left right : NativeType)
  /-- Either. -/
  | or (left right : NativeType)
  /-- **Spatial**: headed by a named constructor, with typed arguments. -/
  | headed (constructor : String) (arguments : List NativeType)
  /-- **Behavioural**: some successor satisfies the inner type. -/
  | diamond (inner : NativeType)
  /-- **Behavioural**: every predecessor satisfies the inner type. -/
  | box (inner : NativeType)
deriving Repr

mutual

/-- What it means for a pattern to inhabit a native type.  The modal cases
delegate to the operators OSLF already derives, so nothing about reduction is
restated here. -/
def satisfies (lang : LanguageDef) : NativeType → Pattern → Prop
  | .top, _ => True
  | .bot, _ => False
  | .and left right, pattern => satisfies lang left pattern ∧ satisfies lang right pattern
  | .or left right, pattern => satisfies lang left pattern ∨ satisfies lang right pattern
  | .headed constructor arguments, pattern =>
      ∃ children : List Pattern,
        pattern = .apply constructor children ∧ satisfiesAll lang arguments children
  | .diamond inner, pattern => langDiamond lang (satisfies lang inner) pattern
  | .box inner, pattern => langBox lang (satisfies lang inner) pattern

/-- Pointwise inhabitation of an argument vector. -/
def satisfiesAll (lang : LanguageDef) : List NativeType → List Pattern → Prop
  | [], [] => True
  | argument :: arguments, child :: children =>
      satisfies lang argument child ∧ satisfiesAll lang arguments children
  | _, _ => False

end

/-! ## The spatial fragment is generated by the term grammar -/

/-- Every declared constructor yields a native type: the terms headed by it,
with unconstrained arguments.  This is the sense in which the spatial half of
the theory is *read off* the language rather than written. -/
def constructorTypes (lang : LanguageDef) : List NativeType :=
  lang.terms.map fun rule =>
    NativeType.headed rule.label (rule.params.map fun _ => NativeType.top)

/-- **The spatial fragment factors through `terms`.**  Two languages with the
same constructors generate the same spatial types, so nothing else about a
language contributes to them. -/
theorem constructorTypes_factors_through_terms {first second : LanguageDef}
    (sameTerms : first.terms = second.terms) :
    constructorTypes first = constructorTypes second := by
  simp [constructorTypes, sameTerms]

/-- Stated as a factorization in the criterion's own vocabulary. -/
theorem constructorTypes_factors : Factors LanguageDef.terms constructorTypes :=
  ⟨fun terms => terms.map fun rule =>
      NativeType.headed rule.label (rule.params.map fun _ => NativeType.top),
    fun _ => rfl⟩

/-! ## The whole theory depends only on the step relation

The modal half is delegated to `langDiamond`/`langBox`, which are derived
from reduction.  So the entire semantics is a function of the reduction
relation together with the constructors — and of nothing else a language
carries. -/

mutual

/-- **Native inhabitation is determined by the step relation.**  Two languages
whose derived reductions agree assign every native type the same meaning.
Since `langDiamond` and `langBox` are themselves derived, this says the native
theory adds no information to the language: it is a view. -/
theorem satisfies_congr {first second : LanguageDef}
    (sameStep : langSpan first = langSpan second) :
    ∀ (nativeType : NativeType) (pattern : Pattern),
      satisfies first nativeType pattern ↔ satisfies second nativeType pattern
  | .top, _ => Iff.rfl
  | .bot, _ => Iff.rfl
  | .and left right, pattern => by
      simp only [satisfies]
      exact and_congr (satisfies_congr sameStep left pattern)
        (satisfies_congr sameStep right pattern)
  | .or left right, pattern => by
      simp only [satisfies]
      exact or_congr (satisfies_congr sameStep left pattern)
        (satisfies_congr sameStep right pattern)
  | .headed constructor arguments, pattern => by
      simp only [satisfies]
      constructor
      · rintro ⟨children, shape, inhabited⟩
        exact ⟨children, shape, (satisfiesAll_congr sameStep arguments children).mp inhabited⟩
      · rintro ⟨children, shape, inhabited⟩
        exact ⟨children, shape, (satisfiesAll_congr sameStep arguments children).mpr inhabited⟩
  | .diamond inner, pattern => by
      have inner_eq : satisfies first inner = satisfies second inner :=
        funext fun p => propext (satisfies_congr sameStep inner p)
      have span_eq :
          langSpanUsing MeTTaIL.Engine.RelationEnv.empty first =
            langSpanUsing MeTTaIL.Engine.RelationEnv.empty second := sameStep
      simp only [satisfies, langDiamond, langDiamondUsing, inner_eq, span_eq]
  | .box inner, pattern => by
      have inner_eq : satisfies first inner = satisfies second inner :=
        funext fun p => propext (satisfies_congr sameStep inner p)
      have span_eq :
          langSpanUsing MeTTaIL.Engine.RelationEnv.empty first =
            langSpanUsing MeTTaIL.Engine.RelationEnv.empty second := sameStep
      simp only [satisfies, langBox, langBoxUsing, inner_eq, span_eq]

theorem satisfiesAll_congr {first second : LanguageDef}
    (sameStep : langSpan first = langSpan second) :
    ∀ (arguments : List NativeType) (children : List Pattern),
      satisfiesAll first arguments children ↔ satisfiesAll second arguments children
  | [], [] => Iff.rfl
  | [], _ :: _ => Iff.rfl
  | _ :: _, [] => Iff.rfl
  | argument :: arguments, child :: children => by
      simp only [satisfiesAll]
      exact and_congr (satisfies_congr sameStep argument child)
        (satisfiesAll_congr sameStep arguments children)

end

/-! ## Authored typing is not determined by the language

The complementary half, and the reason a proof calculus is genuine extension
data rather than a redundant restatement. -/

/-- A typing relation over a fixed language: which terms have which types. -/
abbrev AuthoredTyping := Pattern → Pattern → Prop

/-- Two authored typings over one language. -/
def permissiveTyping : AuthoredTyping := fun _ _ => True

def restrictiveTyping : AuthoredTyping := fun _ _ => False

theorem authored_typings_differ : permissiveTyping ≠ restrictiveTyping := by
  intro equal
  have applied : permissiveTyping (.apply "x" []) (.apply "T" []) =
      restrictiveTyping (.apply "x" []) (.apply "T" []) := by rw [equal]
  simp [permissiveTyping, restrictiveTyping] at applied

/-- Pairing a typing with the language it is authored over. -/
abbrev TypedLanguage := LanguageDef × AuthoredTyping

/-- Two typed languages sharing one language and differing in their typing. -/
def authoredFiber (lang : LanguageDef) :
    NonTrivialFiber (fun typed : TypedLanguage => typed.1) (fun typed => typed.2) where
  left := (lang, permissiveTyping)
  right := (lang, restrictiveTyping)
  sameShadow := rfl
  differentValue := authored_typings_differ

/-- **Authored typing does not factor through the language.**  So a type
system written by a user is genuine new information: no function of the
`LanguageDef` recovers it, and it therefore belongs in a fibre over the core
rather than inside it. -/
theorem authored_typing_not_determined_by_language (lang : LanguageDef) :
    ¬ Factors (fun typed : TypedLanguage => typed.1) (fun typed => typed.2) :=
  (authoredFiber lang).not_factors

/-- **The boundary, stated once.**  What the native theory says is derived —
determined by the constructors and the step relation.  What a user authors is
not.  The first needs no storage; the second is exactly what an extension
must carry. -/
theorem derived_and_authored_boundary (lang : LanguageDef) :
    Factors LanguageDef.terms constructorTypes ∧
      ¬ Factors (fun typed : TypedLanguage => typed.1) (fun typed => typed.2) :=
  ⟨constructorTypes_factors, authored_typing_not_determined_by_language lang⟩

end Mettapedia.OSLF.Framework.NativeTypeTheory
