import Mettapedia.GSLT.Dynamics.RelationalAnswerEvaluation
import Mettapedia.OSLF.Framework.GSLTTypeSynthesis

/-!
# OSLF types from relational answer evaluation

This module derives behavioral native types from the richer operational GSLT
of `RelationalAnswerEvaluation`.  A base observation classifies emitted answer
occurrences.  Applying the OSLF diamond twice yields the type of requests that
can complete and emit an answer satisfying that observation.

The construction is generic in the language and in the observation.  It does
not install a particular authored type system as universal: a dialect may use
syntax shapes, provenance, resource facts, an authored typing judgment, or a
combination as its base observations.
-/

namespace Mettapedia.OSLF.Framework.RelationalAnswerTypeSynthesis

open Mettapedia.GSLT.Dynamics.RelationalAnswerEvaluation
open Mettapedia.OSLF.Framework.GSLTTypeSynthesis

universe uState uRequest uAnswer

variable {State : Type uState} {Request : Type uRequest}
  {Answer : Type uAnswer}

/-- Lift an observation of a concrete emitted answer to the operational term
carrier.  Requests and completions do not satisfy an answer observation. -/
def emittedAnswerSatisfies
    (source : RelationalAnswerSource State Request Answer)
    (observation : State → Request → State → Answer → Prop) :
    EvaluationTerm source → Prop
  | .answer initial request final answers occurrence =>
      observation initial request final (answers.get occurrence)
  | _ => False

/-- Requests that can complete and then emit an answer satisfying the base
observation.  Both diamonds are generated by OSLF from the operational GSLT. -/
def producesAnswerSatisfying
    (source : RelationalAnswerSource State Request Answer)
    (observation : State → Request → State → Answer → Prop) :
    EquationPredicate (evaluationGSLT source) :=
  semanticDiamond (evaluationGSLT source)
    (semanticDiamond (evaluationGSLT source)
      (saturatePredicate (evaluationGSLT source)
        (emittedAnswerSatisfies source observation)))

/-- Exact operational characterization of the derived two-stage native
predicate.  The witness retains final state, the whole ordered answer list,
and the precise occurrence. -/
theorem producesAnswerSatisfying_request_iff
    (source : RelationalAnswerSource State Request Answer)
    (observation : State → Request → State → Answer → Prop)
    (initial : State) (request : Request) :
    producesAnswerSatisfying source observation (.request initial request) ↔
      ∃ (final : State) (answers : List Answer),
        ∃ occurrence : Fin answers.length,
          source.Evaluates initial request final answers ∧
            observation initial request final (answers.get occurrence) := by
  change gsltDiamond (evaluationGSLT source)
      (semanticDiamond (evaluationGSLT source)
        (saturatePredicate (evaluationGSLT source)
          (emittedAnswerSatisfies source observation))).1
      (.request initial request) ↔ _
  rw [gsltDiamond_spec]
  constructor
  · rintro ⟨middle, firstStep, middleMeaning⟩
    cases firstStep with
    | completed evaluation =>
        change gsltDiamond (evaluationGSLT source)
          (saturatePredicate (evaluationGSLT source)
            (emittedAnswerSatisfies source observation)).1 _ at middleMeaning
        rw [gsltDiamond_spec] at middleMeaning
        obtain ⟨target, secondStep, targetMeaning⟩ := middleMeaning
        have observed : emittedAnswerSatisfies source observation target :=
          (saturatePredicate_apply_iff_of_equiv_iff_eq
            (evaluationGSLT source) (fun _ _ => Iff.rfl)
            (emittedAnswerSatisfies source observation) target).1 targetMeaning
        cases secondStep with
        | emitted occurrence =>
            exact ⟨_, _, occurrence, evaluation, observed⟩
  · rintro ⟨final, answers, occurrence, evaluation, observed⟩
    refine ⟨.completed initial request final answers,
      EvaluationStep.completed evaluation, ?_⟩
    change gsltDiamond (evaluationGSLT source)
      (saturatePredicate (evaluationGSLT source)
        (emittedAnswerSatisfies source observation)).1
      (.completed initial request final answers)
    rw [gsltDiamond_spec]
    refine ⟨.answer initial request final answers occurrence,
      EvaluationStep.emitted occurrence, ?_⟩
    exact (saturatePredicate_apply_iff_of_equiv_iff_eq
      (evaluationGSLT source) (fun _ _ => Iff.rfl)
      (emittedAnswerSatisfies source observation) _).2 observed

/-- Package the derived predicate as a native OSLF type over the one-sorted
evaluation GSLT. -/
def producesAnswerNativeType
    (source : RelationalAnswerSource State Request Answer)
    (observation : State → Request → State → Answer → Prop) :
    GSLTNativeType (evaluationGSLT source) :=
  { sort := ()
    pred := producesAnswerSatisfying source observation }

/-- Base observations are monotone: strengthening the observation narrows the
derived request type. -/
theorem producesAnswerSatisfying_mono
    (source : RelationalAnswerSource State Request Answer)
    {weaker stronger : State → Request → State → Answer → Prop}
    (refines : ∀ initial request final answer,
      stronger initial request final answer →
        weaker initial request final answer) :
    ∀ term,
      producesAnswerSatisfying source stronger term →
        producesAnswerSatisfying source weaker term := by
  intro term meaning
  change gsltDiamond (evaluationGSLT source)
      (semanticDiamond (evaluationGSLT source)
        (saturatePredicate (evaluationGSLT source)
          (emittedAnswerSatisfies source stronger))).1 term at meaning
  change gsltDiamond (evaluationGSLT source)
      (semanticDiamond (evaluationGSLT source)
        (saturatePredicate (evaluationGSLT source)
          (emittedAnswerSatisfies source weaker))).1 term
  rw [gsltDiamond_spec] at meaning ⊢
  obtain ⟨middle, firstStep, middleMeaning⟩ := meaning
  refine ⟨middle, firstStep, ?_⟩
  change gsltDiamond (evaluationGSLT source)
      (saturatePredicate (evaluationGSLT source)
        (emittedAnswerSatisfies source stronger)).1 middle at middleMeaning
  change gsltDiamond (evaluationGSLT source)
      (saturatePredicate (evaluationGSLT source)
        (emittedAnswerSatisfies source weaker)).1 middle
  rw [gsltDiamond_spec] at middleMeaning ⊢
  obtain ⟨target, secondStep, targetMeaning⟩ := middleMeaning
  refine ⟨target, secondStep, ?_⟩
  have observed : emittedAnswerSatisfies source stronger target :=
    (saturatePredicate_apply_iff_of_equiv_iff_eq
      (evaluationGSLT source) (fun _ _ => Iff.rfl)
      (emittedAnswerSatisfies source stronger) target).1 targetMeaning
  apply (saturatePredicate_apply_iff_of_equiv_iff_eq
    (evaluationGSLT source) (fun _ _ => Iff.rfl)
    (emittedAnswerSatisfies source weaker) target).2
  cases target with
  | answer initial request final answers occurrence =>
      exact refines initial request final (answers.get occurrence) observed
  | request initial request => exact observed.elim
  | completed initial request final answers => exact observed.elim

/-- Additive extension of the operational source preserves every derived
request type.  This is the compositionality law needed to grow a dialect from
core semantics through profile layers without invalidating earlier native
typing results. -/
theorem producesAnswerSatisfying_request_mono_source
    {first second : RelationalAnswerSource State Request Answer}
    (refines : first.Refines second)
    (observation : State → Request → State → Answer → Prop)
    (initial : State) (request : Request) :
    producesAnswerSatisfying first observation (.request initial request) →
      producesAnswerSatisfying second observation (.request initial request) := by
  rw [producesAnswerSatisfying_request_iff,
    producesAnswerSatisfying_request_iff]
  rintro ⟨final, answers, occurrence, evaluation, observed⟩
  exact ⟨final, answers, occurrence,
    refines _ _ _ _ evaluation, observed⟩

end Mettapedia.OSLF.Framework.RelationalAnswerTypeSynthesis
