import Mettapedia.Languages.ProcessCalculi.RhoCalculus.LanguageDefSemanticAgreement
import Mettapedia.OSLF.Framework.GSLTTypeSynthesis
import Mettapedia.GSLT.LanguageDef.TwoNTTCoherence

/-!
# The rho-calculus instance of the canonical OSLF construction

Rho does not have a hand-written, equation-blind OSLF instance. Its public
OSLF is generated by the same `GSLT -> OSLFTypeSystem` construction as every
other calculus. The input GSLT is the closed, well-sorted semantic object
derived from `rhoCalc` together with its admitted reflection profile.

Consequently:

* structural equations are retained by the GSLT setoid;
* reduction is saturated at both endpoints by those equations;
* native predicates are exactly equation-invariant predicates, equivalently
  predicates on equation classes; and
* the Galois connection is the generic OSLF theorem, not a parallel rho-only
  implementation.
-/

namespace Mettapedia.OSLF.Framework.RhoInstance

open Mettapedia.OSLF.Framework
open Mettapedia.OSLF.Framework.GSLTTypeSynthesis
open Mettapedia.GSLT.LanguageDef
open Mettapedia.GSLT.LanguageDef.TwoNTTCoherence
open Mettapedia.Languages.ProcessCalculi.RhoCalculus.LanguageDefSemanticAgreement

/-- The presentation-derived, reflection-aware rho GSLT used by OSLF. -/
abbrev rhoGSLT := rhoReflectiveGSLT

/-- Rho's one-sorted semantic rewrite system, obtained from its GSLT. -/
def rhoRewriteSystem : RewriteSystem :=
  rhoInterpretedPresentation.toRewriteSystemUsing defaultBasePremises

/-- The sole public rho OSLF instance. -/
def rhoOSLF : OSLFTypeSystem rhoRewriteSystem :=
  rhoInterpretedPresentation.toOSLFUsing defaultBasePremises

/-- The generic GSLT-to-NTT construction instantiated on rho's explicitly
interpreted, equation-saturated semantic presentation. -/
def rhoGeneratedNTT : GeneratedNTT :=
  generateNTT rhoGSLT

/-- The public rho OSLF is definitionally generated from the GSLT denoted by
the same explicitly interpreted presentation. -/
theorem rhoOSLF_eq_gsltOSLF : rhoOSLF = gsltOSLF rhoGSLT :=
  rfl

/-- Rho's modal adjunction is the generic equation-respecting OSLF
adjunction specialized to its presentation-derived GSLT. -/
theorem rho_mathlib_galois :
    GaloisConnection
      (semanticDiamond rhoGSLT)
      (semanticBox rhoGSLT) :=
  semanticGalois rhoGSLT

/-- Positive control: communication remains observable in the generated
rho OSLF. -/
theorem rhoOSLF_sees_communication :
    (gsltOSLF rhoGSLT).satisfies (S := ())
      presentedClosedCommSource
      (exactTargetNativeType rhoGSLT presentedClosedCommTarget).pred :=
  gsltOSLF_sees_communication

/-- Rho communication inhabits the native type produced by the literal
generic GSLT-to-NTT constructor. -/
theorem rhoGeneratedNTT_sees_communication :
    rhoGeneratedNTT.2.satisfies (S := ())
      Mettapedia.Languages.ProcessCalculi.RhoCalculus.LanguageDefSemanticAgreement.presentedClosedCommSource
      (exactTargetNativeType rhoGSLT
        Mettapedia.Languages.ProcessCalculi.RhoCalculus.LanguageDefSemanticAgreement.presentedClosedCommTarget).pred := by
  exact rhoOSLF_sees_communication

/-- Negative control: static equation saturation does not manufacture a
free-drop reduction. -/
theorem rhoOSLF_keeps_freeDrop_inert :
    ¬(gsltOSLF rhoGSLT).satisfies (S := ())
      presentedClosedFreeDrop
      (semanticDiamond rhoGSLT
        (saturatePredicate rhoGSLT (fun _ => True))) :=
  gsltOSLF_keeps_freeDrop_inert

/-- Semantic rho predicates cannot distinguish two representatives of the
same structural-equation class. -/
theorem rhoOSLF_cannot_distinguish_presentations
    (predicate : EquationPredicate rhoGSLT) :
    (gsltOSLF rhoGSLT).satisfies (S := ())
        presentedClosedCommTarget predicate ↔
      (gsltOSLF rhoGSLT).satisfies (S := ())
        presentedClosedNil predicate :=
  by
    simpa only [rhoGSLT] using
      (Mettapedia.Languages.ProcessCalculi.RhoCalculus.LanguageDefSemanticAgreement.gsltOSLF_cannot_distinguish_presentations
        predicate)

#print axioms rho_mathlib_galois
#print axioms rhoOSLF_eq_gsltOSLF
#print axioms rhoOSLF_sees_communication
#print axioms rhoGeneratedNTT_sees_communication
#print axioms rhoOSLF_keeps_freeDrop_inert
#print axioms rhoOSLF_cannot_distinguish_presentations

end Mettapedia.OSLF.Framework.RhoInstance
