import Mettapedia.OSLF.Framework.SortedTypedInstrumentKitProbeReadout
import Mettapedia.OSLF.Framework.SortedTypedPartialStructuralObservations

/-!
# The observational ceiling on the typed generated subalgebra of a kit

Actual ask IPOs recover the complete typed tuple of a matched right value.
The locally admitted get labels recursively recover each child at its own
sort. That equality earns purity of the matched child before the original
unit-rule alternative is excluded. Only the left source value requires a
representative hereditarily generated by opened heads; the supported right
value is arbitrary native syntax.

Administrative origins are explicitly inhabited. No source-sort inhabitance,
unique get output, faithful ground action, or current-view adequacy for
unopened source values is assumed.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false

noncomputable section

namespace Mettapedia.OSLF.Framework.SortedTypedInstruments.Kit

open _root_.CategoryTheory
open Mettapedia.OSLF.SortedCommutative
open Mettapedia.GSLT.RedexRelativeCongruence

universe u v w z

variable {source : Mettapedia.OSLF.SortedConstructors.Signature.{u,v}}
  {Parallel : source.Srt → Prop} {OriginalOrigins : Type z} {NativeOrigins : Type w}
variable (opened : Policy source Parallel)
  (originalRules : OriginalOrigins → ReactionRule (.origin : SourceCategory source Parallel))

theorem value_class_supported {sort : Srt source Parallel}
    (supplied : ValueClass (source := source) (Parallel := Parallel) sort)
    (supported : ArrowSupported opened (RawArrow.value supplied :
      (.origin : ContextCategory source Parallel) ⟶ .interface sort)) : ClassSupported opened supplied :=
  (class_supported_iff_weight_zero opened supplied).mpr
    ((arrow_supported_iff_weight_zero opened _).mp supported)

private theorem generated_constructor_reconstruction
    (origins : Nonempty NativeOrigins) (head : SourceHead source Parallel) (permission : opened head)
    (arguments : (position : Fin (headArity head)) → Term source Parallel (headInput head position))
    (childRecovery : ∀ position
      (right : ValueClass (source := source) (Parallel := Parallel) (.original (headInput head position)))
      (rightSupported : ClassSupported opened right),
      IPOBisimilar (categoryRules (NativeOrigins := NativeOrigins) originalRules opened)
        (value (classOf (embed (arguments position))) ⟨_, embed_supported opened _, rfl⟩)
        (value right rightSupported) → classOf (embed (arguments position)) = right)
    (right : ValueClass (source := source) (Parallel := Parallel) (.original (headOutput head)))
    (rightSupported : ClassSupported opened right)
    (related : IPOBisimilar (categoryRules (NativeOrigins := NativeOrigins) originalRules opened)
      (value (classOf (sourceNode head (fun position => embed (arguments position))))
        ⟨_, (sourceNode_supported_iff opened head _).mpr
          (fun position => embed_supported opened (arguments position)), rfl⟩)
      (value right rightSupported)) :
    classOf (sourceNode head (fun position => embed (arguments position))) = right := by
  obtain ⟨origin⟩ := origins
  let embedded : Arguments head := fun position => embed (arguments position)
  have children : ∀ position, Supported opened (embedded position) :=
    fun position => embed_supported opened (arguments position)
  have askStep := ask_step opened originalRules origin head embedded permission children
  obtain ⟨matched, matchedStep, tupleRelated⟩ := ipoBisimilar_forward related askStep
  obtain ⟨matchedArrow, matchedSupport⟩ := matched
  cases matchedArrow with
  | value matched =>
    have matchedSupported := value_class_supported opened matched matchedSupport
    obtain ⟨_matchedOrigin, before, rightRead, wholeTarget⟩ :=
      ask_step_readout opened originalRules head permission right rightSupported matched matchedSupported matchedStep
    subst matched
    have beforeChildren : ∀ position, Supported opened (before position) :=
      ((bundle_supported_iff opened head before).mp
        ((classOf_supported_iff opened (bundle head before)).mp matchedSupported)).2
    have coordinates : ∀ position, classOf (embedded position) = classOf (before position) := by
      intro position
      have getStep := get_step opened originalRules origin head embedded position permission children
      obtain ⟨after, afterStep, childRelated⟩ := ipoBisimilar_forward tupleRelated getStep
      obtain ⟨afterArrow, afterSupport⟩ := after
      cases afterArrow with
      | value after =>
        have afterSupported := value_class_supported opened after afterSupport
        have recovered := childRecovery position after afterSupported childRelated
        have pureAfter : classObserverCount after = 0 := by
          rw [← recovered]
          exact classObserverCount_embedding (classOf (arguments position))
        have actualCoordinate := (get_pure_result_readout opened originalRules
          head before position permission beforeChildren after afterSupported pureAfter afterStep).2
        exact recovered.trans actualCoordinate
    exact (sourceNode_class_congruence head embedded before coordinates).trans rightRead.symm

private theorem raw_generated_reconstruction
    (origins : Nonempty NativeOrigins) {sort : source.Srt} (left : Term source Parallel sort) :
    StructuralObservations.Supported opened left →
      ∀ (right : ValueClass (source := source) (Parallel := Parallel) (.original sort))
        (rightSupported : ClassSupported opened right),
        IPOBisimilar (categoryRules (NativeOrigins := NativeOrigins) originalRules opened)
          (value (classOf (embed left)) ⟨_, embed_supported opened left, rfl⟩)
          (value right rightSupported) → classOf (embed left) = right := by
  apply @Term.rec source Parallel
    (fun sort left => StructuralObservations.Supported opened left →
      ∀ (right : ValueClass (source := source) (Parallel := Parallel) (.original sort))
        (rightSupported : ClassSupported opened right),
        IPOBisimilar (categoryRules (NativeOrigins := NativeOrigins) originalRules opened)
          (value (classOf (embed left)) ⟨_, embed_supported opened left, rfl⟩)
          (value right rightSupported) → classOf (embed left) = right) (t := left)
  · intro sort parallel supported right rightSupported related
    exact generated_constructor_reconstruction opened originalRules origins (.unit sort parallel) supported
      (fun position => Fin.elim0 position) (fun position => Fin.elim0 position) right rightSupported related
  · intro sort parallel first second firstInduction secondInduction supported right rightSupported related
    let arguments : Fin 2 → Term source Parallel sort := Fin.cases first (fun _ => second)
    have recoveries : ∀ position
        (after : ValueClass (source := source) (Parallel := Parallel) (.original sort))
        (afterSupported : ClassSupported opened after),
        IPOBisimilar (categoryRules (NativeOrigins := NativeOrigins) originalRules opened)
          (value (classOf (embed (arguments position))) ⟨_, embed_supported opened _, rfl⟩)
          (value after afterSupported) → classOf (embed (arguments position)) = after := by
      intro position
      fin_cases position
      · exact firstInduction supported.2.1
      · exact secondInduction supported.2.2
    exact generated_constructor_reconstruction opened originalRules origins (.properCut sort parallel) supported.1
      arguments recoveries right rightSupported related
  · intro constructor arguments inductionHypothesis supported right rightSupported related
    exact generated_constructor_reconstruction opened originalRules origins (.ordinary constructor) supported.1
      arguments (fun position => inductionHypothesis position (supported.2 position)) right rightSupported related

theorem observer_bisimilar_iff_embedded_equal_of_generated (origins : Nonempty NativeOrigins)
    {sort : source.Srt} (left : Class source Parallel sort)
    (generated : StructuralObservations.Generated opened left)
    (right : ValueClass (source := source) (Parallel := Parallel) (.original sort))
    (rightSupported : ClassSupported opened right) :
    IPOBisimilar (categoryRules (NativeOrigins := NativeOrigins) originalRules opened)
      (value (classEmbedding left) (classEmbedding_supported opened left))
      (value right rightSupported) ↔ classEmbedding left = right := by
  constructor
  · obtain ⟨representative, supported, rfl⟩ := generated
    exact raw_generated_reconstruction opened originalRules origins representative supported right rightSupported
  · intro same
    subst right
    exact ipoBisimilar_refl _ _

theorem observer_bisimilar_iff_source_equal_of_generated (origins : Nonempty NativeOrigins)
    {sort : source.Srt} (first second : Class source Parallel sort)
    (generated : StructuralObservations.Generated opened first) :
    IPOBisimilar (categoryRules (NativeOrigins := NativeOrigins) originalRules opened)
      (value (classEmbedding first) (classEmbedding_supported opened first))
      (value (classEmbedding second) (classEmbedding_supported opened second)) ↔ first = second :=
  (observer_bisimilar_iff_embedded_equal_of_generated opened originalRules origins first generated
    (classEmbedding second) (classEmbedding_supported opened second)).trans
      ⟨fun same => classEmbedding_injective same, fun same => congrArg classEmbedding same⟩

theorem partialLogicalEquivalent_iff_actual_observer_of_generated (origins : Nonempty NativeOrigins)
    {sort : source.Srt} (first second : Class source Parallel sort)
    (generated : StructuralObservations.Generated opened first) :
    StructuralObservations.PartialLogicalEquivalent opened first second ↔
      IPOBisimilar (categoryRules (NativeOrigins := NativeOrigins) originalRules opened)
        (value (classEmbedding first) (classEmbedding_supported opened first))
        (value (classEmbedding second) (classEmbedding_supported opened second)) :=
  (StructuralObservations.partialLogicalEquivalent_iff_equal_of_generated opened first second generated).trans
    (observer_bisimilar_iff_source_equal_of_generated opened originalRules origins first second generated).symm

end Mettapedia.OSLF.Framework.SortedTypedInstruments.Kit
