import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryStaticSemanticCutProvider
import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryStaticDeepSemanticCutProvider
import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostStaticProcessBoundary
import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryMatchedFramesRestorationApex
import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryMatchedFramesProvenancedAlignment
import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryBoundVariableExposure
import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryObjectReduction
import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryCanonicalOccurrencePathSupport

/-!
# Routes for the left-collapsing arm of the rho semantic-cut provider

`RhoCanonicalStaticPairBridgeCase.leftCollapsing` retains the exact static
root of the left endpoint together with the syntactic collapsing certificate
of its compact pattern.  Three semantic-cut constructors are indexed by that
bridge case, and this module supplies the entry point of each one from data a
provider actually holds.

* `CostRegionTree.staticRootView_of_rootIsStatic` turns the executable root
  observation into the cast-stable static view, so the right endpoint is
  classified without dependent elimination at the call site.
* `RhoCanonicalStaticPairSemanticCut.leftStaticEnclosingOfPlanStops` reaches
  the same-colour constructor from raw canonical equality alone.  Unlike the
  root-aligned entry point, no `CanonicalRootAligned` premise is available in
  a collapsing arm, so the raw descent is generated by
  `canonicalStopAligned_of_canonicalize_eq_below` at a measure strictly above
  the endpoint pair: a collapsing root is itself a canonical stop, so the
  root pair must be inside the retained stop relation.
* `RhoCollapsingLeafExposure.rigidBVarOfSourceCanonicalAtBoundVariable`
  removes the structural endpoint premise whenever the right endpoint is
  literally a bound variable.

`nonempty_rhoCanonicalStaticPairSemanticCut_leftCollapsing_of_routes` then
composes the three entry points into the exact left-collapsing conclusion of
`RhoCanonicalStaticPair.HasSemanticCut`, so the arm's residual
content is precisely the three route premises and nothing else.

## The two-premise form, and why it is the one to use

The plan-stop route above carries a measure, and a collapsing root is itself
a canonical stop, so that route can only be stated one above the endpoint
pair.  `not_rhoCanonicalRawStop_endpoints_at_endpointMeasure` records why:
no raw stop relation measured at the endpoint pair contains that pair.

That constraint is a property of routes through plan stops, not of the arm.
`leftStaticEnclosing` asks for a `RhoMatchedStaticFramesApex`, not for a
measured callback, and `RhoMatchedStaticFramesApex.ofRestorationAligned`
builds one from a restoration certificate alone.  Since
`RhoStaticFramesRestorationAligned` is indexed by two *independent* colours,
the same certificate also serves the cross-colour constructor.  Hence
`nonempty_rhoCanonicalStaticPairSemanticCut_leftCollapsing_of_restorationRoutes`
needs two premises where the plan-stop form needs three, consumes no
canonical equality, and involves no measure at all.  The right-collapsing
theorem mirrors it exactly.

Composed with `CostHereditaryObjectReduction` and the already-proved
support-preservation law, this leaves the rho cost layer domain object standing on
exactly two node-local obligations, `RhoStaticViewsRestorationAlignedInDomain`
and `RhoCollapsingLeaf.HasExposure`.
-/

namespace Mettapedia.GSLT.LanguageDef

open Mettapedia.GSLT.LanguageDef.WellSorted
open Mettapedia.OSLF.MeTTaIL.Syntax

/-- The executable static-root observation exposes a cast-stable view.

`CostRegionTree.rootIsStatic` is defined by one match on the retained
constructor, so a positive observation determines the tree up to that
constructor and every index equality of the view is definitional. -/
noncomputable def CostRegionTree.staticRootView_of_rootIsStatic
    {source : CIGSLT} {targetFree : FreeTypeContext}
    {available outer : List TypeExpr} {pattern : Pattern} {type : TypeExpr}
    (tree : CostRegionTree source targetFree available outer pattern type)
    (static : tree.rootIsStatic = true) :
    Σ color, tree.StaticRootView color := by
  cases tree with
  | static node children =>
      exact ⟨_,
        { node := node
          children := children
          patternEq := rfl
          availableEq := rfl
          typeEq := rfl
          treeEq := rfl }⟩
  | bvar lookup => simp [CostRegionTree.rootIsStatic] at static
  | fvar lookup => simp [CostRegionTree.rootIsStatic] at static
  | neutralApplicationOrdinary _ _ _ _ _ _ _ =>
      simp [CostRegionTree.rootIsStatic] at static
  | neutralApplicationQuote _ _ _ _ _ _ _ =>
      simp [CostRegionTree.rootIsStatic] at static
  | lambda body => simp [CostRegionTree.rootIsStatic] at static
  | multiLambda body => simp [CostRegionTree.rootIsStatic] at static
  | subst body replacement => simp [CostRegionTree.rootIsStatic] at static
  | collection children => simp [CostRegionTree.rootIsStatic] at static

/-- A tree indexed by a bound variable is retained structurally: a static
region root is certified to be an application or a collection. -/
theorem CostRegionTree.rootIsStatic_eq_false_of_bvar
    {source : CIGSLT} {targetFree : FreeTypeContext}
    {available outer : List TypeExpr} {index : Nat} {type : TypeExpr}
    (tree : CostRegionTree source targetFree available outer (.bvar index)
      type) :
    tree.rootIsStatic = false := by
  apply Bool.eq_false_of_not_eq_true
  intro static
  rcases tree.pattern_shape_of_rootIsStatic static with
    ⟨wireName, arguments, impossible⟩ | ⟨collectionType, elements, rest,
      impossible⟩ <;> cases impossible

end Mettapedia.GSLT.LanguageDef

namespace Mettapedia.Languages.ProcessCalculi.RhoCalculus

open Mettapedia.GSLT.LanguageDef
open Mettapedia.GSLT.LanguageDef.WellSorted
open Mettapedia.OSLF.MeTTaIL.Syntax
open Mettapedia.OSLF.MeTTaIL.ReflectiveCanonical
open Mettapedia.Languages.ProcessCalculi.RhoCalculus.LanguageDefContinuedInteraction

namespace RhoCollapsingLeafExposure

/-- Rigid exposure against a literal bound-variable endpoint.

The endpoint normal form is no longer a premise: a tree indexed by a bound
variable is retained by the bound-variable constructor, whose normalization
is that same variable. -/
noncomputable def rigidBVarOfSourceCanonicalAtBoundVariable
    {color : CostStaticColor} {targetFree : FreeTypeContext}
    {rightAvailable rightOuter : List TypeExpr}
    (node : CostStaticRegionNode rhoCIGSLT color targetFree)
    (children : CostRegionBoundaryTrees rhoCIGSLT targetFree color
      node.finiteBoundaryTable)
    {index : Nat} {rightType : TypeExpr}
    (right : CostRegionTree rhoCIGSLT targetFree rightAvailable rightOuter
      (.bvar index) rightType)
    (sourceIndex : Nat)
    (collapse :
      let values := children.normalizeValues
        (normalizeStatic := rhoHereditaryStaticNormalizer)
      canonicalize rhoReflectivePresentation
          (node.reifiedSourceFrame
            (CostStaticAtomEnvironment.ofInventory
              (node.semanticAtomEnvironment values).1)).1 =
        .bvar sourceIndex)
    (indexEq : node.thinning.embedIndexAt 0 sourceIndex = index) :
    RhoCollapsingLeafExposure node children right := by
  refine rigidBVarOfSourceCanonical node children right sourceIndex collapse ?_
  rw [indexEq]
  let view := right.structuralRootView right.rootIsStatic_eq_false_of_bvar
  cases view with
  | bvar lookup => simp [CostRegionTree.normalize]

end RhoCollapsingLeafExposure

namespace RhoCanonicalStaticPairSemanticCut

/-- Same-colour left-collapsing cut from the plan-stop restoration callback.

A collapsing root has no `CanonicalRootAligned` certificate, so the raw
canonical descent consumed by the provenanced apex is generated directly
from canonical equality.  That descent stops at the endpoint pair itself,
hence the retained stop relation is measured strictly above
`sizeOf leftPattern + sizeOf rightPattern`; the callback must therefore
cover the root pair and not only its proper subpairs. -/
noncomputable def leftStaticEnclosingOfPlanStops
    {declarationColor color : CostStaticColor}
    {targetFree : FreeTypeContext}
    {available outer : List TypeExpr}
    {leftPattern rightPattern : Pattern} {type : TypeExpr}
    {left : CostRegionTree rhoCIGSLT targetFree available outer leftPattern
      type}
    {right : CostRegionTree rhoCIGSLT targetFree available outer rightPattern
      type}
    (leftView : left.StaticRootView color)
    (rightView : right.StaticRootView color)
    (collapsing : CollapsingRoot
      (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
        rhoReflectivePresentation.toReflectivePresentationDecl)
      leftPattern)
    (canonical :
      canonicalize
          (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
            rhoReflectivePresentation.toReflectivePresentationDecl)
          leftPattern =
        canonicalize
          (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
            rhoReflectivePresentation.toReflectivePresentationDecl)
          rightPattern)
    (planStops :
      RhoStaticPlanStopCommonApex leftView rightView declarationColor
        (RhoCanonicalRawStop declarationColor
          (sizeOf leftPattern + sizeOf rightPattern + 1))) :
    RhoCanonicalStaticPairSemanticCut declarationColor left right
      (.leftCollapsing color leftView collapsing) := by
  refine .leftStaticEnclosing leftView collapsing rightView
    (RhoMatchedStaticFramesApex.ofProvenancedRawAlignment leftView rightView
      declarationColor (rawStop :=
        RhoCanonicalRawStop declarationColor
          (sizeOf leftPattern + sizeOf rightPattern + 1)) ?_ planStops)
  have nodeCanonical :
      canonicalize
          (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
            rhoReflectivePresentation.toReflectivePresentationDecl)
          leftView.node.term.1 =
        canonicalize
          (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
            rhoReflectivePresentation.toReflectivePresentationDecl)
          rightView.node.term.1 := by
    rw [leftView.patternEq, rightView.patternEq]
    exact canonical
  have below :
      sizeOf leftView.node.term.1 + sizeOf rightView.node.term.1 <
        sizeOf leftPattern + sizeOf rightPattern + 1 := by
    rw [leftView.patternEq, rightView.patternEq]
    exact Nat.lt_succ_self _
  exact canonicalStopAligned_of_canonicalize_eq_below _ nodeCanonical below

end RhoCanonicalStaticPairSemanticCut

/-- The endpoint pair of a left-collapsing arm is itself a retained raw stop.

Canonical equality plus a collapsing left root is exactly the leaf case of
the raw canonical descent, so the plan-stop callback of a collapsing arm is
asked about the endpoints themselves and not only about proper subpairs. -/
theorem rhoCanonicalRawStop_endpoints_of_leftCollapsing
    {declarationColor : CostStaticColor} {leftPattern rightPattern : Pattern}
    (collapsing : CollapsingRoot
      (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
        rhoReflectivePresentation.toReflectivePresentationDecl)
      leftPattern)
    (canonical :
      canonicalize
          (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
            rhoReflectivePresentation.toReflectivePresentationDecl)
          leftPattern =
        canonicalize
          (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
            rhoReflectivePresentation.toReflectivePresentationDecl)
          rightPattern) :
    RhoCanonicalRawStop declarationColor
      (sizeOf leftPattern + sizeOf rightPattern + 1) leftPattern
      rightPattern :=
  ⟨⟨Or.inl collapsing, canonical⟩, Nat.lt_succ_self _⟩

/-- The endpoint pair is outside every raw stop relation measured at the
endpoint pair itself.

Consequently a plan-stop callback whose relation is
`RhoCanonicalRawStop declarationColor (sizeOf leftPattern + sizeOf rightPattern)`
never covers the collapsing root, and the strictly-decreasing recursion that
produces such a callback cannot supply the collapsing arm. -/
theorem not_rhoCanonicalRawStop_endpoints_at_endpointMeasure
    {declarationColor : CostStaticColor}
    {leftPattern rightPattern : Pattern} :
    ¬ RhoCanonicalRawStop declarationColor
        (sizeOf leftPattern + sizeOf rightPattern) leftPattern rightPattern :=
  fun stop => Nat.lt_irrefl _ stop.2

/-- The left-collapsing provider arm reduced to its three route premises.

The right endpoint is classified by its own executable root observation:
same-colour static, different-colour static, or structural.  Each branch is
the entry point of exactly one semantic-cut constructor indexed by
`.leftCollapsing`, so no configuration of the arm escapes the three
premises. -/
theorem nonempty_rhoCanonicalStaticPairSemanticCut_leftCollapsing_of_routes
    {declarationColor : CostStaticColor}
    {targetFree : FreeTypeContext} {available outer : List TypeExpr}
    {leftPattern rightPattern : Pattern} {type : TypeExpr}
    {left : CostRegionTree rhoCIGSLT targetFree available outer leftPattern
      type}
    {right : CostRegionTree rhoCIGSLT targetFree available outer rightPattern
      type}
    {leftColor : CostStaticColor}
    (leftView : left.StaticRootView leftColor)
    (collapsing : CollapsingRoot
      (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
        rhoReflectivePresentation.toReflectivePresentationDecl)
      leftPattern)
    (canonical :
      canonicalize
          (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
            rhoReflectivePresentation.toReflectivePresentationDecl)
          leftPattern =
        canonicalize
          (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
            rhoReflectivePresentation.toReflectivePresentationDecl)
          rightPattern)
    (sameColorRoute : ∀ rightView : right.StaticRootView leftColor,
      RhoStaticPlanStopCommonApex leftView rightView declarationColor
        (RhoCanonicalRawStop declarationColor
          (sizeOf leftPattern + sizeOf rightPattern + 1)))
    (crossColorRoute : ∀ {rightColor : CostStaticColor}
      (rightView : right.StaticRootView rightColor), leftColor ≠ rightColor →
      RhoStaticFramesRestorationAligned leftView rightView)
    (structuralRoute : right.rootIsStatic = false →
      Nonempty (RhoCollapsingLeafExposure leftView.node leftView.children
        right)) :
    Nonempty (RhoCanonicalStaticPairSemanticCut declarationColor left right
      (.leftCollapsing leftColor leftView collapsing)) := by
  by_cases rightStatic : right.rootIsStatic = true
  · obtain ⟨rightColor, rightView⟩ :=
      right.staticRootView_of_rootIsStatic rightStatic
    by_cases sameColor : leftColor = rightColor
    · subst sameColor
      exact ⟨RhoCanonicalStaticPairSemanticCut.leftStaticEnclosingOfPlanStops
        leftView rightView collapsing canonical (sameColorRoute rightView)⟩
    · exact ⟨.leftCrossColorEnclosing leftView collapsing rightView sameColor
        (crossColorRoute rightView sameColor)⟩
  · obtain ⟨exposure⟩ :=
      structuralRoute (Bool.eq_false_of_not_eq_true rightStatic)
    exact ⟨.leftEnclosing leftView collapsing exposure⟩

/-- **The left-collapsing arm from two premises.**

Both static branches consume the *same* certificate.
`RhoStaticFramesRestorationAligned` is indexed by two independent colours, so
stating it needs no colour hypothesis, and the same-colour branch reaches its
enclosing apex through `RhoMatchedStaticFramesApex.ofRestorationAligned`
rather than through a measured plan-stop callback.

Two consequences worth recording.  Canonical equality of the roots is not
consumed at all: an enclosing cut is terminal at the collapsing root, so the
arm never descends and never needs a raw stop.  And no strictly-decreasing
measure appears, so the endpoint-measure obstruction above constrains only
routes that pass through plan stops, not this arm. -/
theorem nonempty_rhoCanonicalStaticPairSemanticCut_leftCollapsing_of_restorationRoutes
    {declarationColor : CostStaticColor}
    {targetFree : FreeTypeContext} {available outer : List TypeExpr}
    {leftPattern rightPattern : Pattern} {type : TypeExpr}
    {left : CostRegionTree rhoCIGSLT targetFree available outer leftPattern
      type}
    {right : CostRegionTree rhoCIGSLT targetFree available outer rightPattern
      type}
    {leftColor : CostStaticColor}
    (leftView : left.StaticRootView leftColor)
    (collapsing : CollapsingRoot
      (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
        rhoReflectivePresentation.toReflectivePresentationDecl)
      leftPattern)
    (restorationRoute : ∀ {rightColor : CostStaticColor}
      (rightView : right.StaticRootView rightColor),
      RhoStaticFramesRestorationAligned leftView rightView)
    (structuralRoute : right.rootIsStatic = false →
      Nonempty (RhoCollapsingLeafExposure leftView.node leftView.children
        right)) :
    Nonempty (RhoCanonicalStaticPairSemanticCut declarationColor left right
      (.leftCollapsing leftColor leftView collapsing)) := by
  by_cases rightStatic : right.rootIsStatic = true
  · obtain ⟨rightColor, rightView⟩ :=
      right.staticRootView_of_rootIsStatic rightStatic
    by_cases sameColor : leftColor = rightColor
    · subst sameColor
      exact ⟨.leftStaticEnclosing leftView collapsing rightView
        (RhoMatchedStaticFramesApex.ofRestorationAligned leftView rightView
          (restorationRoute rightView))⟩
    · exact ⟨.leftCrossColorEnclosing leftView collapsing rightView sameColor
        (restorationRoute rightView)⟩
  · obtain ⟨exposure⟩ :=
      structuralRoute (Bool.eq_false_of_not_eq_true rightStatic)
    exact ⟨.leftEnclosing leftView collapsing exposure⟩

/-- **The right-collapsing arm from the same two premises.**

The exact mirror: the collapsing endpoint is now the right one, the surviving
endpoint is classified by its own root observation, and the three
`.rightCollapsing`-indexed constructors are reached by the same certificates.
Note the restoration certificate keeps its `leftView rightView` argument
order in both arms, because that order is fixed by the cospan and not by
which endpoint collapsed. -/
theorem nonempty_rhoCanonicalStaticPairSemanticCut_rightCollapsing_of_restorationRoutes
    {declarationColor : CostStaticColor}
    {targetFree : FreeTypeContext} {available outer : List TypeExpr}
    {leftPattern rightPattern : Pattern} {type : TypeExpr}
    {left : CostRegionTree rhoCIGSLT targetFree available outer leftPattern
      type}
    {right : CostRegionTree rhoCIGSLT targetFree available outer rightPattern
      type}
    {rightColor : CostStaticColor}
    (rightView : right.StaticRootView rightColor)
    (collapsing : CollapsingRoot
      (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
        rhoReflectivePresentation.toReflectivePresentationDecl)
      rightPattern)
    (restorationRoute : ∀ {leftColor : CostStaticColor}
      (leftView : left.StaticRootView leftColor),
      RhoStaticFramesRestorationAligned leftView rightView)
    (structuralRoute : left.rootIsStatic = false →
      Nonempty (RhoCollapsingLeafExposure rightView.node rightView.children
        left)) :
    Nonempty (RhoCanonicalStaticPairSemanticCut declarationColor left right
      (.rightCollapsing rightColor rightView collapsing)) := by
  by_cases leftStatic : left.rootIsStatic = true
  · obtain ⟨leftColor, leftView⟩ :=
      left.staticRootView_of_rootIsStatic leftStatic
    by_cases sameColor : leftColor = rightColor
    · subst sameColor
      exact ⟨.rightStaticEnclosing rightView collapsing leftView
        (RhoMatchedStaticFramesApex.ofRestorationAligned leftView rightView
          (restorationRoute leftView))⟩
    · exact ⟨.rightCrossColorEnclosing rightView collapsing leftView sameColor
        (restorationRoute leftView)⟩
  · obtain ⟨exposure⟩ :=
      structuralRoute (Bool.eq_false_of_not_eq_true leftStatic)
    exact ⟨.rightEnclosing rightView collapsing exposure⟩

/-! ## The provider from two semantic obligations

The three bridge cases between them consume exactly two certificates.  Naming
them makes the provider's remaining content visible: everything else in the
dispatch is root observation and constructor selection. -/

/-- The provider's strictly-smaller recursion callback, named once so the
obligations below can carry it without restating the telescope.

Threading it is not a convenience.  Withholding it makes an obligation
strictly stronger than its call site requires, and in one case fatally so:
`RhoCollapsingLeafExposure` pins the partner's normal form to the collapsed
node's (`RhoCollapsingLeafExposure.normalize_eq`), so a callback-free exposure
obligation *is* mixed-pair hereditary-normalization soundness — the very thing
the cost layer seal exists to establish.  Every producer in the tree whose partner
pattern is unconstrained takes this callback; the ones that do not, pin the
partner to a variable or demand a pre-built normalization alignment. -/
def RhoPairCloseSmaller (declarationColor : CostStaticColor)
    (targetFree : FreeTypeContext) (parentMeasure : Nat) : Prop :=
  ∀ {childAvailable childOuter : List TypeExpr}
    {leftChild rightChild : Pattern} {childType : TypeExpr},
    ReflectiveWellSorted.OpenPatternWellSorted
        rhoCIGSLT.costWholeReflectionProfile rhoCIGSLT.costWholeLanguage
        targetFree childAvailable childType leftChild →
    ReflectiveWellSorted.OpenPatternWellSorted
        rhoCIGSLT.costWholeReflectionProfile rhoCIGSLT.costWholeLanguage
        targetFree childAvailable childType rightChild →
    canonicalize
        (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
          rhoReflectivePresentation.toReflectivePresentationDecl)
        leftChild =
      canonicalize
        (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
          rhoReflectivePresentation.toReflectivePresentationDecl)
        rightChild →
    sizeOf leftChild + sizeOf rightChild < parentMeasure →
    rhoCanonicalRecursiveTypeDomain.Admissible childType →
    Nonempty (CostCanonicalPairElaboration rhoCIGSLT
      rhoHereditaryNormalizationKernel targetFree childAvailable childOuter
      leftChild rightChild childType)

/-- **Obligation A — restoration alignment.**  Two static root views of a
canonically equal pair are restoration-aligned.  The two colours are
independent, so this single statement serves the aligned arm and the static
branch of both collapsing arms. -/
def RhoStaticViewsRestorationAlignedInDomain
    (declarationColor : CostStaticColor) : Prop :=
  ∀ {targetFree : FreeTypeContext} {available outer : List TypeExpr}
    {leftPattern rightPattern : Pattern} {type : TypeExpr}
    {left : CostRegionTree rhoCIGSLT targetFree available outer leftPattern
      type}
    {right : CostRegionTree rhoCIGSLT targetFree available outer rightPattern
      type}
    {leftColor rightColor : CostStaticColor}
    (leftView : left.StaticRootView leftColor)
    (rightView : right.StaticRootView rightColor),
    canonicalize
        (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
          rhoReflectivePresentation.toReflectivePresentationDecl)
        leftPattern =
      canonicalize
        (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
          rhoReflectivePresentation.toReflectivePresentationDecl)
        rightPattern →
    RhoStaticFramesRestorationAligned leftView rightView

/-- **Obligation B — collapsing leaf exposure.**  A collapsing static root
whose partner endpoint has a non-static root exposes that partner as a leaf.
Stated with the collapsed endpoint first, so both collapsing arms use it with
the canonical equation oriented from their own side. -/
def RhoCollapsingLeaf.HasExposure
    (declarationColor : CostStaticColor) : Prop :=
  ∀ {targetFree : FreeTypeContext} {available outer : List TypeExpr}
    {collapsedPattern otherPattern : Pattern} {type : TypeExpr}
    {collapsed : CostRegionTree rhoCIGSLT targetFree available outer
      collapsedPattern type}
    {other : CostRegionTree rhoCIGSLT targetFree available outer otherPattern
      type}
    {color : CostStaticColor}
    (view : collapsed.StaticRootView color),
    rhoCanonicalRecursiveTypeDomain.Admissible type →
    ReflectiveWellSorted.OpenPatternWellSorted
        rhoCIGSLT.costWholeReflectionProfile rhoCIGSLT.costWholeLanguage
        targetFree available type collapsedPattern →
    ReflectiveWellSorted.OpenPatternWellSorted
        rhoCIGSLT.costWholeReflectionProfile rhoCIGSLT.costWholeLanguage
        targetFree available type otherPattern →
    RhoPairCloseSmaller declarationColor targetFree
      (sizeOf collapsedPattern + sizeOf otherPattern) →
    CollapsingRoot
        (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
          rhoReflectivePresentation.toReflectivePresentationDecl)
        collapsedPattern →
    other.rootIsStatic = false →
    canonicalize
        (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
          rhoReflectivePresentation.toReflectivePresentationDecl)
        collapsedPattern =
      canonicalize
        (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
          rhoReflectivePresentation.toReflectivePresentationDecl)
        otherPattern →
    Nonempty (RhoCollapsingLeafExposure view.node view.children other)

/-! ### The weaker split of obligation A

Obligation A above asks for restoration alignment from canonical equality
alone.  Neither arm needs it in that strength: the aligned arm holds a
`CanonicalRootAligned` certificate, and each collapsing arm holds a
`CollapsingRoot` certificate for its own endpoint.  Splitting A along that
line gives two strictly weaker obligations, so a proof attempt is never
burdened with configurations its call site cannot produce. -/

/-- **Obligation A1 — aligned roots.**  Two same-colour views of a
root-aligned pair are restoration-aligned, given the ambient typing and the
recursion the provider already holds. -/
def RhoAlignedViewsRestorationAlignedInDomain
    (declarationColor : CostStaticColor) : Prop :=
  ∀ {targetFree : FreeTypeContext} {available outer : List TypeExpr}
    {leftPattern rightPattern : Pattern} {type : TypeExpr}
    {left : CostRegionTree rhoCIGSLT targetFree available outer leftPattern
      type}
    {right : CostRegionTree rhoCIGSLT targetFree available outer rightPattern
      type}
    {color : CostStaticColor}
    (leftView : left.StaticRootView color)
    (rightView : right.StaticRootView color),
    rhoCanonicalRecursiveTypeDomain.Admissible type →
    ReflectiveWellSorted.OpenPatternWellSorted
        rhoCIGSLT.costWholeReflectionProfile rhoCIGSLT.costWholeLanguage
        targetFree available type leftPattern →
    ReflectiveWellSorted.OpenPatternWellSorted
        rhoCIGSLT.costWholeReflectionProfile rhoCIGSLT.costWholeLanguage
        targetFree available type rightPattern →
    RhoPairCloseSmaller declarationColor targetFree
      (sizeOf leftPattern + sizeOf rightPattern) →
    CanonicalRootAligned
        (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
          rhoReflectivePresentation.toReflectivePresentationDecl)
        leftPattern rightPattern →
    RhoStaticFramesRestorationAligned leftView rightView

/-- **Obligation A2 — one collapsing endpoint.**  When either endpoint of a
canonically equal pair has a collapsing root, the two views are
restoration-aligned.  The colours are independent, because a collapsing arm
may face a partner of either colour. -/
def RhoCollapsingViewsRestorationAlignedInDomain
    (declarationColor : CostStaticColor) : Prop :=
  ∀ {targetFree : FreeTypeContext} {available outer : List TypeExpr}
    {leftPattern rightPattern : Pattern} {type : TypeExpr}
    {left : CostRegionTree rhoCIGSLT targetFree available outer leftPattern
      type}
    {right : CostRegionTree rhoCIGSLT targetFree available outer rightPattern
      type}
    {leftColor rightColor : CostStaticColor}
    (leftView : left.StaticRootView leftColor)
    (rightView : right.StaticRootView rightColor),
    rhoCanonicalRecursiveTypeDomain.Admissible type →
    ReflectiveWellSorted.OpenPatternWellSorted
        rhoCIGSLT.costWholeReflectionProfile rhoCIGSLT.costWholeLanguage
        targetFree available type leftPattern →
    ReflectiveWellSorted.OpenPatternWellSorted
        rhoCIGSLT.costWholeReflectionProfile rhoCIGSLT.costWholeLanguage
        targetFree available type rightPattern →
    RhoPairCloseSmaller declarationColor targetFree
      (sizeOf leftPattern + sizeOf rightPattern) →
    (CollapsingRoot
        (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
          rhoReflectivePresentation.toReflectivePresentationDecl)
        leftPattern ∨
      CollapsingRoot
        (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
          rhoReflectivePresentation.toReflectivePresentationDecl)
        rightPattern) →
    canonicalize
        (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
          rhoReflectivePresentation.toReflectivePresentationDecl)
        leftPattern =
      canonicalize
        (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
          rhoReflectivePresentation.toReflectivePresentationDecl)
        rightPattern →
    RhoStaticFramesRestorationAligned leftView rightView

/-- The strong obligation A implies the collapsing half of the split.

The aligned half follows too, but its proof lives downstream:
`canonicalize_eq_of_canonicalRootAligned` (`CostHereditaryAlignedRestoration`)
derives canonical equality from root alignment by routing through
`canonicalStopAligned_of_root_aligned`, and
`RhoStaticViewsRestorationAlignedInDomain.toAligned` there completes the
implication.  So A1 and A2 really are a weakening of A, in both halves. -/
theorem RhoStaticViewsRestorationAlignedInDomain.toCollapsing
    {declarationColor : CostStaticColor}
    (restoration : RhoStaticViewsRestorationAlignedInDomain declarationColor) :
    RhoCollapsingViewsRestorationAlignedInDomain declarationColor :=
  fun leftView rightView _admissible _leftWellSorted _rightWellSorted
      _closeSmaller _collapsing canonical =>
    restoration leftView rightView canonical

/-- **The provider from the two obligations.**

Every bridge case is discharged: the aligned arm by `matchedOfRestorationAligned`,
each collapsing arm by its restoration-route theorem above.  None of the
recursion parameters — admissibility, well-sortedness, the static root shape,
or the strictly-smaller callback — is consumed, because an enclosing or
matched cut is terminal at the classified root. -/
theorem rhoCanonicalStaticPair_hasSemanticCut_of_obligations
    {declarationColor : CostStaticColor}
    (restoration : RhoStaticViewsRestorationAlignedInDomain declarationColor)
    (exposure : RhoCollapsingLeaf.HasExposure declarationColor) :
    RhoCanonicalStaticPair.HasSemanticCut declarationColor := by
  intro targetFree available outer leftPattern rightPattern type admissible
    leftWellSorted rightWellSorted canonical _staticShape closeSmaller
    left right rootCase
  have close : RhoPairCloseSmaller declarationColor targetFree
      (sizeOf leftPattern + sizeOf rightPattern) := closeSmaller
  have closeSwapped : RhoPairCloseSmaller declarationColor targetFree
      (sizeOf rightPattern + sizeOf leftPattern) := by
    rw [Nat.add_comm]; exact close
  cases rootCase with
  | leftCollapsing leftColor leftView collapsing =>
      exact
        nonempty_rhoCanonicalStaticPairSemanticCut_leftCollapsing_of_restorationRoutes
          leftView collapsing
          (fun rightView => restoration leftView rightView canonical)
          (fun rightStructural =>
            exposure leftView admissible leftWellSorted rightWellSorted close
              collapsing rightStructural canonical)
  | rightCollapsing rightColor rightView collapsing =>
      exact
        nonempty_rhoCanonicalStaticPairSemanticCut_rightCollapsing_of_restorationRoutes
          rightView collapsing
          (fun leftView => restoration leftView rightView canonical)
          (fun leftStructural =>
            exposure rightView admissible rightWellSorted leftWellSorted
              closeSwapped collapsing leftStructural canonical.symm)
  | aligned color leftView rightView roots =>
      exact ⟨RhoCanonicalStaticPairSemanticCut.matchedOfRestorationAligned
        leftView rightView roots (restoration leftView rightView canonical)⟩

/-- **The provider from the split obligations.**

The same dispatch as above, but each arm draws on the certificate it actually
holds: the aligned arm on its `CanonicalRootAligned` root certificate, each
collapsing arm on its own `CollapsingRoot` certificate together with canonical
equality.  This is the form to discharge, since neither premise is asked to
cover configurations its call site cannot produce. -/
theorem rhoCanonicalStaticPair_hasSemanticCut_of_splitObligations
    {declarationColor : CostStaticColor}
    (alignedRestoration :
      RhoAlignedViewsRestorationAlignedInDomain declarationColor)
    (collapsingRestoration :
      RhoCollapsingViewsRestorationAlignedInDomain declarationColor)
    (exposure : RhoCollapsingLeaf.HasExposure declarationColor) :
    RhoCanonicalStaticPair.HasSemanticCut declarationColor := by
  intro targetFree available outer leftPattern rightPattern type admissible
    leftWellSorted rightWellSorted canonical _staticShape closeSmaller
    left right rootCase
  have close : RhoPairCloseSmaller declarationColor targetFree
      (sizeOf leftPattern + sizeOf rightPattern) := closeSmaller
  have closeSwapped : RhoPairCloseSmaller declarationColor targetFree
      (sizeOf rightPattern + sizeOf leftPattern) := by
    rw [Nat.add_comm]; exact close
  cases rootCase with
  | leftCollapsing leftColor leftView collapsing =>
      exact
        nonempty_rhoCanonicalStaticPairSemanticCut_leftCollapsing_of_restorationRoutes
          leftView collapsing
          (fun rightView =>
            collapsingRestoration leftView rightView admissible leftWellSorted
              rightWellSorted close (Or.inl collapsing) canonical)
          (fun rightStructural =>
            exposure leftView admissible leftWellSorted rightWellSorted close
              collapsing rightStructural canonical)
  | rightCollapsing rightColor rightView collapsing =>
      exact
        nonempty_rhoCanonicalStaticPairSemanticCut_rightCollapsing_of_restorationRoutes
          rightView collapsing
          (fun leftView =>
            collapsingRestoration leftView rightView admissible leftWellSorted
              rightWellSorted close (Or.inr collapsing) canonical)
          (fun leftStructural =>
            exposure rightView admissible rightWellSorted leftWellSorted
              closeSwapped collapsing leftStructural canonical.symm)
  | aligned color leftView rightView roots =>
      exact ⟨RhoCanonicalStaticPairSemanticCut.matchedOfRestorationAligned
        leftView rightView roots
        (alignedRestoration leftView rightView admissible leftWellSorted
          rightWellSorted close roots)⟩

/-! ## The rho cost layer laws and domain object over the two obligations

`CostHereditaryObjectReduction` reduces the object to the per-colour provider
together with `RhoCostStaticReflectiveSupportPreserving`, and that second
input is already proved outright by
`rhoHereditaryStaticNormalizer_preservesReflectiveSupport_path`.  Composing it
with the dispatcher leaves obligations A and B as the whole remaining content
of the rho cost layer seal. -/

/-- **The rho cost layer object laws from obligations A and B alone.** -/
noncomputable def rhoHereditaryCompactOpenNormalizerLaws_ofRestorationAndExposure
    (restoration : ∀ color, RhoStaticViewsRestorationAlignedInDomain color)
    (exposure : ∀ color, RhoCollapsingLeaf.HasExposure color) :
    Cost.CompactOpenNormalizer.Laws rhoCIGSLT
      rhoCostNormalizeOpenHereditarySupported :=
  rhoHereditaryCompactOpenNormalizerLaws_ofSemanticLaws
    (fun color =>
      rhoCanonicalStaticPair_hasSemanticCut_of_obligations
        (restoration color) (exposure color))
    rhoHereditaryStaticNormalizer_preservesReflectiveSupport_path

/-- **The rho cost layer domain object from obligations A and B alone.**

This is the seal target.  Supplying `restoration` and `exposure` produces a
`Cost.Layer` with no further hypotheses. -/
noncomputable def rhoHereditaryCostLayer_ofRestorationAndExposure
    (restoration : ∀ color, RhoStaticViewsRestorationAlignedInDomain color)
    (exposure : ∀ color, RhoCollapsingLeaf.HasExposure color) :
    Cost.Layer :=
  rhoHereditaryCostLayer_ofSemanticLaws
    (fun color =>
      rhoCanonicalStaticPair_hasSemanticCut_of_obligations
        (restoration color) (exposure color))
    rhoHereditaryStaticNormalizer_preservesReflectiveSupport_path

/-- **The rho cost layer domain object over the split obligations.**

The operative seal statement.  Discharging A1, A2 and B — each a node-local
claim about two static root views — produces `Cost.Layer` with no
remaining hypotheses. -/
noncomputable def rhoHereditaryCostLayer_ofSplitObligations
    (alignedRestoration :
      ∀ color, RhoAlignedViewsRestorationAlignedInDomain color)
    (collapsingRestoration :
      ∀ color, RhoCollapsingViewsRestorationAlignedInDomain color)
    (exposure : ∀ color, RhoCollapsingLeaf.HasExposure color) :
    Cost.Layer :=
  rhoHereditaryCostLayer_ofSemanticLaws
    (fun color =>
      rhoCanonicalStaticPair_hasSemanticCut_of_splitObligations
        (alignedRestoration color) (collapsingRestoration color)
        (exposure color))
    rhoHereditaryStaticNormalizer_preservesReflectiveSupport_path

/-- The cost layer object laws over the split obligations. -/
noncomputable def rhoHereditaryCompactOpenNormalizerLaws_ofSplitObligations
    (alignedRestoration :
      ∀ color, RhoAlignedViewsRestorationAlignedInDomain color)
    (collapsingRestoration :
      ∀ color, RhoCollapsingViewsRestorationAlignedInDomain color)
    (exposure : ∀ color, RhoCollapsingLeaf.HasExposure color) :
    Cost.CompactOpenNormalizer.Laws rhoCIGSLT
      rhoCostNormalizeOpenHereditarySupported :=
  rhoHereditaryCompactOpenNormalizerLaws_ofSemanticLaws
    (fun color =>
      rhoCanonicalStaticPair_hasSemanticCut_of_splitObligations
        (alignedRestoration color) (collapsingRestoration color)
        (exposure color))
    rhoHereditaryStaticNormalizer_preservesReflectiveSupport_path

end Mettapedia.Languages.ProcessCalculi.RhoCalculus
