import Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostHereditaryCollapsingRestoration

/-!
# The cross-colour collapsing residual of the rho static-pair provider

`RhoCollapsingCrossColorViewsRestorationAlignedInDomain` is the half of
obligation A2 whose two static root views carry different colours.  This
module records the structural facts that decide how that residual may be
closed, and in particular why the flat whole-frame route is the only one its
call sites can offer.
-/

namespace Mettapedia.GSLT.LanguageDef

open Mettapedia.OSLF.MeTTaIL.Syntax
open WellSorted

/-- **A static region plan never places a bound variable where the ambient
available context is empty.**

The `.bvar` constructor of `CostStaticRegionPlan` carries
`sourceIndex < (sourceContextOfTarget source color targetAvailable).length`,
and the source fibre of the empty target context is empty.  This is the
structural form of the quotation seal: the `.application` constructor hands
its children the empty available context exactly when its authored label is
the reflective quote constructor, so no bound variable survives directly
underneath a quotation. -/
theorem CostStaticRegionPlan.not_bvar_of_available_nil
    {source : CIGSLT} {color : CostStaticColor}
    {targetFree : FreeTypeContext}
    {sourceBound targetBound : List TypeExpr}
    {thinning : CostStaticBinderThinning source color sourceBound targetBound}
    {outer : Mettapedia.OSLF.MeTTaIL.DerivedContexts.OneHoleContext}
    {index : Nat} {sourceType : TypeExpr}
    (plan : CostStaticRegionPlan source color targetFree sourceBound
      targetBound thinning [] outer (.bvar index) sourceType) : False := by
  cases plan with
  | bvar sourceIndex lookup correspondence availableScope =>
      simp [CostStaticBinderThinning.sourceContextOfTarget] at availableScope

end Mettapedia.GSLT.LanguageDef

namespace Mettapedia.Languages.ProcessCalculi.RhoCalculus

open Mettapedia.GSLT.LanguageDef
open Mettapedia.GSLT.LanguageDef.WellSorted
open Mettapedia.OSLF.MeTTaIL.Syntax
open Mettapedia.OSLF.MeTTaIL.ReflectiveCanonical
open Mettapedia.OSLF.Framework.ConstructorCategory
open Mettapedia.GSLT.LanguageDef.ReflectionExtension
open Mettapedia.GSLT.LanguageDef.CostHereditaryCanonical
open Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostCanonicalLaws
open Mettapedia.Languages.ProcessCalculi.RhoCalculus.LanguageDefContinuedInteraction

/-- **The rho `Name` fibre is generated by the quotation constructor alone.**

`rhoCalc` declares six term constructors and exactly one of them has category
`Name`; its label is the authored reflective quote constructor.  Every static
root in the `Name` fibre is therefore a quotation, whatever its colour. -/
theorem rhoCalc_label_eq_quote_of_category_name
    {rule : Mettapedia.OSLF.MeTTaIL.Syntax.GrammarRule}
    (membership : rule ∈ rhoCalc.terms)
    (category : rule.category = "Name") : rule.label = "NQuote" := by
  simp only [rhoCalc, List.mem_cons, List.not_mem_nil, or_false] at membership
  rcases membership with rfl | rfl | rfl | rfl | rfl | rfl <;> simp_all

/-- The authored rho quote constructor is the label of the unique `Name`
constructor. -/
theorem rhoReflectivePresentation_quoteConstructor :
    rhoReflectivePresentation.toReflectivePresentationDecl.quoteConstructor =
      "NQuote" := by
  rfl

/-- Quotation is observed by the authored reflection profile. -/
theorem rho_isQuoteConstructor_quote :
    ReflectiveContextSupport.isQuoteConstructor rhoCIGSLT.reflection.1
      "NQuote" = true := by
  decide

/-- **The rho `Name` fibre admits no collection root.**

Only `PPar` carries a bare collection parameter and its authored category is
`Proc`, so the complete candidate family that a `.collection` static root
would have to select from is empty in the `Name` fibre. -/
theorem rho_costStaticCollectionTypingChoices_name_eq_nil
    (color : CostStaticColor) (targetFree : FreeTypeContext)
    (targetBound : List TypeExpr) (collectionType : CollType)
    (elements : List Pattern) :
    costStaticCollectionTypingChoices rhoCIGSLT color targetFree targetBound
        collectionType elements
        (mapTypeExpr (color.symbols rhoCIGSLT) (.base "Name")) = [] := by
  unfold costStaticCollectionTypingChoices
  rw [decodeCostStaticTypeExpr_mapTypeExpr]
  simp only [bareCostStaticCollectionTypingChoices]
  apply List.filterMap_eq_nil_iff.mpr
  intro rule membership
  have shape : WellSorted.bareCollectionElementType? rule collectionType
      (.base "Name") = none := by
    revert membership
    simp only [show rhoCIGSLT.theory.presentation.presentation.language =
      rhoCalc from rfl, rhoCalc, List.mem_cons, List.not_mem_nil, or_false]
    rintro (rfl | rfl | rfl | rfl | rfl | rfl) <;>
      simp [WellSorted.bareCollectionElementType?, TypeExpr.name, TypeExpr.proc,
        TypeExpr.bag, TypeExpr.funType, TypeExpr.baseType]
  simp [shape]

/-! ## The shared non-interacting fibre is the `Name` fibre -/

/-- rho's interacting sort is `Proc`. -/
theorem rho_interactingSort_name :
    rhoCIGSLT.theory.presentation.interactingSort.1.name = "Proc" := by
  rfl

/-- A rho sort outside the interacting sort is the `Name` sort. -/
theorem rho_sourceSort_eq_name_of_ne_interacting
    {sort : LangSort rhoCIGSLT.theory.presentation.presentation.language}
    (notInteracting :
      sort.1 ≠ rhoCIGSLT.theory.presentation.interactingSort.1.name) :
    sort.1 = "Name" := by
  rw [rho_interactingSort_name] at notInteracting
  have membership : sort.1 ∈
      rhoCIGSLT.theory.presentation.presentation.language.types.map
        (fun declaration => declaration.name) := sort.2
  revert membership
  simp only [show rhoCIGSLT.theory.presentation.presentation.language =
    rhoCalc from rfl, rhoCalc, List.map_cons, List.map_nil, List.mem_cons,
    List.not_mem_nil, or_false]
  rintro (h | h)
  · exact absurd (by simpa [TypeDecl.plain] using h) notInteracting
  · simpa [TypeDecl.plain] using h

/-- In the `Name` fibre either static colour action agrees with the colour's
reflective name sort. -/
theorem rho_mapLangSort_eq_nameSort (color : CostStaticColor)
    {sort : LangSort rhoCIGSLT.theory.presentation.presentation.language}
    (nameSort : sort.1 = "Name") :
    (color.mapLangSort rhoCIGSLT sort).1 =
      (costStaticReflectivePresentationDecl rhoCIGSLT color
        rhoReflectivePresentation.toReflectivePresentationDecl).nameSort := by
  rw [costStaticReflectivePresentationDecl_eq_map]
  cases color <;>
    simp [CostStaticColor.mapLangSort,
      ReflectionExtension.mapReflectivePresentation, nameSort,
      CostStaticColor.reflectiveSymbols, CostStaticColor.symbols,
      costBaseStaticReflectiveSymbols, costWrappedStaticReflectiveSymbols,
      costBaseStaticSymbols, costWrappedStaticSymbols,
      costBaseLanguageDefSymbolMap, rhoReflectivePresentation]

/-- The authored rho reflective presentation is a member of the generated
whole-Cost reflection profile at either colour. -/
theorem rho_costStaticReflectivePresentationDecl_mem (color : CostStaticColor) :
    costStaticReflectivePresentationDecl rhoCIGSLT color
        rhoReflectivePresentation.toReflectivePresentationDecl ∈
      rhoCIGSLT.costWholeReflectionProfile.presentations := by
  have sourceMembership :
      rhoReflectivePresentation.toReflectivePresentationDecl ∈
        rhoCIGSLT.reflection.1.presentations := by
    change rhoReflectivePresentation.toReflectivePresentationDecl ∈
      ReflectionExtension.rhoReflectionProfile.presentations
    simp [ReflectionExtension.rhoReflectionProfile]
  simpa using
    costStaticReflectivePresentationDecl_mem rhoCIGSLT color
      rhoReflectivePresentation.toReflectivePresentationDecl sourceMembership

/-- Each colour's reflective erasure/reinsertion labels lie in that colour's
constructor image. -/
theorem rho_reflectiveConstructorsAllowed_color (color : CostStaticColor) :
    ReflectiveConstructorsAllowed
      (fun constructor => ∃ sourceConstructor,
        decodeCostStaticConstructor color constructor = some sourceConstructor)
      (costStaticReflectivePresentationDecl rhoCIGSLT color
        rhoReflectivePresentation.toReflectivePresentationDecl) where
  quote := by
    rw [show (costStaticReflectivePresentationDecl rhoCIGSLT color
        rhoReflectivePresentation.toReflectivePresentationDecl).quoteConstructor =
          (color.symbols rhoCIGSLT).constructor
            rhoReflectivePresentation.quoteConstructor by
      simp [costStaticReflectivePresentationDecl_eq_map,
        mapReflectivePresentation]]
    exact ⟨_, decodeCostStaticConstructor_symbols rhoCIGSLT color _⟩
  drop := by
    rw [show (costStaticReflectivePresentationDecl rhoCIGSLT color
        rhoReflectivePresentation.toReflectivePresentationDecl).dropConstructor =
          (color.symbols rhoCIGSLT).constructor
            rhoReflectivePresentation.dropConstructor by
      simp [costStaticReflectivePresentationDecl_eq_map,
        mapReflectivePresentation]]
    exact ⟨_, decodeCostStaticConstructor_symbols rhoCIGSLT color _⟩
  parallelUnit := by
    rw [show (costStaticReflectivePresentationDecl rhoCIGSLT color
        rhoReflectivePresentation.toReflectivePresentationDecl
        ).parallelUnitConstructor =
          (color.symbols rhoCIGSLT).constructor
            rhoReflectivePresentation.parallelUnitConstructor by
      simp [costStaticReflectivePresentationDecl_eq_map,
        mapReflectivePresentation]]
    exact ⟨_, decodeCostStaticConstructor_symbols rhoCIGSLT color _⟩

/-- **Shape of a canonical `Name`-fibre frame.**

A `Name`-fibre static node's keyed canonical target frame is a bound
variable, a semantic atom, or an application whose head is that node's own
colour spelling of an authored constructor.  Binders are excluded by the base
result type, pending substitution by the object carrier, and collections by
`rho_no_collection_at_reflectiveNameSort`.

This is what makes the flat leaf the only alignment route across colours: the
`.lambda`, `.multiLambda`, `.subst` and `.collection` steps of
`PatternLeafAligned` have no frame to act on, and the `.apply` step would need
one constructor to lie in both colour images at once. -/
theorem rhoNameFibre_canonicalFrame_shape
    {color : CostStaticColor} {targetFree : FreeTypeContext}
    (node : CostStaticRegionNode rhoCIGSLT color targetFree)
    {values : TypedCostRegionBoundaryTable.Values rhoCIGSLT color targetFree
      node.boundaryTable}
    (inventory : CostStaticParameterInventory rhoCIGSLT color targetFree
      node.boundaryTable values node.skeleton.1)
    (nameSort : node.sourceSort.1 = "Name") :
    (∃ index, node.canonicalizeReifiedTargetFrame
          (CostStaticAtomEnvironment.ofInventory inventory)
          (costStaticReflectivePresentationDecl rhoCIGSLT color
            rhoReflectivePresentation.toReflectivePresentationDecl) =
        .bvar index) ∨
      (∃ name, node.canonicalizeReifiedTargetFrame
          (CostStaticAtomEnvironment.ofInventory inventory)
          (costStaticReflectivePresentationDecl rhoCIGSLT color
            rhoReflectivePresentation.toReflectivePresentationDecl) =
        .fvar name) ∨
      ∃ wireName arguments sourceConstructor,
        node.canonicalizeReifiedTargetFrame
            (CostStaticAtomEnvironment.ofInventory inventory)
            (costStaticReflectivePresentationDecl rhoCIGSLT color
              rhoReflectivePresentation.toReflectivePresentationDecl) =
          .apply wireName arguments ∧
        decodeCostStaticConstructor color wireName = some sourceConstructor := by
  obtain ⟨typed, _⟩ :=
    Mettapedia.Languages.ProcessCalculi.RhoCalculus.CostStaticRegionNode.canonicalizeReifiedTargetFrame_supportSafe
      node (CostStaticAtomEnvironment.ofInventory inventory)
      (Mettapedia.GSLT.LanguageDef.CostStaticRegionNode.semanticAtom_typeMap
        node values inventory)
  rw [rho_mapLangSort_eq_nameSort color nameSort] at typed
  have object : WellSorted.isObjectPattern
      (node.canonicalizeReifiedTargetFrame
        (CostStaticAtomEnvironment.ofInventory inventory)
        (costStaticReflectivePresentationDecl rhoCIGSLT color
          rhoReflectivePresentation.toReflectivePresentationDecl)) = true := by
    unfold Mettapedia.GSLT.LanguageDef.CostStaticRegionNode.canonicalizeReifiedTargetFrame
    refine canonicalizeByAt_isObjectPattern _ _ _ _ ?_
    rw [← node.reifiedTargetFrame_pattern
      (CostStaticAtomEnvironment.ofInventory inventory)]
    exact (node.reifiedTargetFrame
      (CostStaticAtomEnvironment.ofInventory inventory)).2.1.2.2.1
  have within : ConstructorsWithin
      (fun constructor => ∃ sourceConstructor,
        decodeCostStaticConstructor color constructor = some sourceConstructor)
      (node.canonicalizeReifiedTargetFrame
        (CostStaticAtomEnvironment.ofInventory inventory)
        (costStaticReflectivePresentationDecl rhoCIGSLT color
          rhoReflectivePresentation.toReflectivePresentationDecl)) := by
    unfold Mettapedia.GSLT.LanguageDef.CostStaticRegionNode.canonicalizeReifiedTargetFrame
    rw [← canonicalizeByDepths_ignoreScope
      (Mettapedia.GSLT.LanguageDef.CostStaticRegionNode.semanticPatternKeyAt
        (CostStaticAtomEnvironment.ofInventory inventory))
      (costStaticReflectivePresentationDecl rhoCIGSLT color
        rhoReflectivePresentation.toReflectivePresentationDecl)
      node.targetBound.length 0]
    refine (CostHereditaryCanonical.constructorsWithin_canonicalizeByDepths_iff
      _ _ (rho_reflectiveConstructorsAllowed_color color) _ 0 _).mpr ?_
    rw [← node.reifiedTargetFrame_pattern
      (CostStaticAtomEnvironment.ofInventory inventory)]
    exact node.reifiedTargetFrame_constructorsWithinColor
      (CostStaticAtomEnvironment.ofInventory inventory)
  cases frameShape : node.canonicalizeReifiedTargetFrame
      (CostStaticAtomEnvironment.ofInventory inventory)
      (costStaticReflectivePresentationDecl rhoCIGSLT color
        rhoReflectivePresentation.toReflectivePresentationDecl) with
  | bvar index => exact Or.inl ⟨index, rfl⟩
  | fvar name => exact Or.inr (Or.inl ⟨name, rfl⟩)
  | apply wireName arguments =>
      rw [frameShape] at within
      obtain ⟨⟨sourceConstructor, decoded⟩, _⟩ := within
      exact Or.inr (Or.inr ⟨wireName, arguments, sourceConstructor, rfl, decoded⟩)
  | lambda binder body => rw [frameShape] at typed; cases typed
  | multiLambda arity binders body => rw [frameShape] at typed; cases typed
  | subst body replacement =>
      rw [frameShape] at object
      simp [WellSorted.isObjectPattern] at object
  | collection collectionType elements rest =>
      rw [frameShape] at typed
      exact absurd typed (rho_no_collection_at_reflectiveNameSort _
        (rho_costStaticReflectivePresentationDecl_mem color))

/-- One generated constructor name never lies in two distinct colour
namespaces. -/
theorem decodeCostStaticConstructor_color_disjoint
    {leftColor rightColor : CostStaticColor} (different : leftColor ≠ rightColor)
    {constructor leftSource rightSource : String}
    (leftDecoded :
      decodeCostStaticConstructor leftColor constructor = some leftSource)
    (rightDecoded :
      decodeCostStaticConstructor rightColor constructor = some rightSource) :
    False := by
  rw [decodeCostStaticConstructor_eq_some_iff] at leftDecoded rightDecoded
  cases leftColor <;> cases rightColor
  · exact different rfl
  · exact costBaseConstructorName_ne_wrapped leftSource rightSource
      (leftDecoded.symm.trans rightDecoded)
  · exact costBaseConstructorName_ne_wrapped rightSource leftSource
      (rightDecoded.symm.trans leftDecoded)
  · exact different rfl

/-- **The flat leaf is the only cross-colour alignment route in the rho `Name`
fibre.**

`RhoStaticFramesRestorationAligned.ofFramesRestoreTogether` produces the
alignment from a single `RestoresTogether` on the two reified canonical
frames.  In the different-colour `Name` fibre that route is not merely
sufficient: it is forced.  The binder, `subst` and collection steps of
`PatternLeafAligned` have no frame to act on there, the `bvar` step relates a
pattern to itself, and the `apply` step would put one wire name in both colour
namespaces at once. -/
theorem rhoCrossColorNameFibre_framesRestoreTogether_of_restorationAligned
    {targetFree : FreeTypeContext} {available outer : List TypeExpr}
    {leftPattern rightPattern : Pattern} {type : TypeExpr}
    {left : CostRegionTree rhoCIGSLT targetFree available outer leftPattern
      type}
    {right : CostRegionTree rhoCIGSLT targetFree available outer rightPattern
      type}
    {leftColor rightColor : CostStaticColor}
    (leftView : left.StaticRootView leftColor)
    (rightView : right.StaticRootView rightColor)
    (different : leftColor ≠ rightColor)
    (leftName : leftView.node.sourceSort.1 = "Name")
    (rightName : rightView.node.sourceSort.1 = "Name")
    (aligned : RhoStaticFramesRestorationAligned leftView rightView) :
    let leftEnvironment := CostStaticAtomEnvironment.ofInventory
      (leftView.node.semanticAtomEnvironment
        (leftView.children.normalizeValues
          (normalizeStatic := rhoHereditaryStaticNormalizer))).1
    let rightEnvironment := CostStaticAtomEnvironment.ofInventory
      (rightView.node.semanticAtomEnvironment
        (rightView.children.normalizeValues
          (normalizeStatic := rhoHereditaryStaticNormalizer))).1
    let cospan := leftEnvironment.semanticKeyCospan rightEnvironment
    ReflectiveContextSupport.RestoresTogether
      rhoCIGSLT.costWholeReflectionProfile cospan.commonSupport
        cospan.commonAssignment
        (cospan.reifyWith leftEnvironment.lookupAtom? cospan.leftSlot
          (leftView.node.canonicalizeReifiedTargetFrame leftEnvironment
            (costStaticReflectivePresentationDecl rhoCIGSLT leftColor
              rhoReflectivePresentation.toReflectivePresentationDecl)))
        (cospan.reifyWith rightEnvironment.lookupAtom? cospan.rightSlot
          (rightView.node.canonicalizeReifiedTargetFrame rightEnvironment
            (costStaticReflectivePresentationDecl rhoCIGSLT rightColor
              rhoReflectivePresentation.toReflectivePresentationDecl))) := by
  intro leftEnvironment rightEnvironment cospan
  have leftShape := rhoNameFibre_canonicalFrame_shape leftView.node
    (leftView.node.semanticAtomEnvironment
      (leftView.children.normalizeValues
        (normalizeStatic := rhoHereditaryStaticNormalizer))).1 leftName
  have rightShape := rhoNameFibre_canonicalFrame_shape rightView.node
    (rightView.node.semanticAtomEnvironment
      (rightView.children.normalizeValues
        (normalizeStatic := rhoHereditaryStaticNormalizer))).1 rightName
  have alignment : PatternLeafAligned
      (fun leftLeaf rightLeaf =>
        ReflectiveContextSupport.RestoresTogether
          rhoCIGSLT.costWholeReflectionProfile cospan.commonSupport
            cospan.commonAssignment
            (cospan.reifyWith leftEnvironment.lookupAtom? cospan.leftSlot
              leftLeaf)
            (cospan.reifyWith rightEnvironment.lookupAtom? cospan.rightSlot
              rightLeaf))
      (leftView.node.canonicalizeReifiedTargetFrame leftEnvironment
        (costStaticReflectivePresentationDecl rhoCIGSLT leftColor
          rhoReflectivePresentation.toReflectivePresentationDecl))
      (rightView.node.canonicalizeReifiedTargetFrame rightEnvironment
        (costStaticReflectivePresentationDecl rhoCIGSLT rightColor
          rhoReflectivePresentation.toReflectivePresentationDecl)) := aligned
  rcases leftShape with ⟨leftIndex, leftEq⟩ | ⟨leftAtom, leftEq⟩ |
      ⟨leftWire, leftArguments, leftSource, leftEq, leftDecoded⟩ <;>
    rcases rightShape with ⟨rightIndex, rightEq⟩ | ⟨rightAtom, rightEq⟩ |
        ⟨rightWire, rightArguments, rightSource, rightEq, rightDecoded⟩ <;>
      rw [leftEq, rightEq] at alignment ⊢ <;>
        cases alignment <;>
          first
            | assumption
            | (simp only [CostStaticAtomKeyCospan.reifyWith]
               exact ReflectiveContextSupport.RestoresTogether.refl _ _ _ _)
            | exact absurd rightDecoded (fun rightDecoded =>
                decodeCostStaticConstructor_color_disjoint different leftDecoded
                  rightDecoded)

/-! ## Obligation A2x has exactly one residual -/

/-- **The flat form of obligation A2x.**

Identical telescope to `RhoCollapsingCrossColorViewsRestorationAlignedInDomain`
with the proof-relevant alignment replaced by the single depth-uniform
restoration equation on the two reified canonical frames. -/
def RhoCollapsingCrossColorFramesRestoreTogetherInDomain
    (declarationColor : CostStaticColor) : Prop :=
  ∀ {targetFree : FreeTypeContext} {available outer : List TypeExpr}
    {leftPattern rightPattern : Pattern} {type : TypeExpr}
    {left : CostRegionTree rhoCIGSLT targetFree available outer leftPattern
      type}
    {right : CostRegionTree rhoCIGSLT targetFree available outer rightPattern
      type}
    {leftColor rightColor : CostStaticColor}
    (leftView : left.StaticRootView leftColor)
    (rightView : right.StaticRootView rightColor),
    leftColor ≠ rightColor →
    leftView.node.sourceSort.1 = rightView.node.sourceSort.1 →
    leftView.node.sourceSort.1 ≠
      rhoCIGSLT.theory.presentation.interactingSort.1.name →
    rhoCanonicalRecursiveTypeDomain.Admissible type →
    ReflectiveWellSorted.OpenPatternWellSorted
        rhoCIGSLT.costWholeReflectionProfile rhoCIGSLT.costWholeLanguage
        targetFree available type leftPattern →
    ReflectiveWellSorted.OpenPatternWellSorted
        rhoCIGSLT.costWholeReflectionProfile rhoCIGSLT.costWholeLanguage
        targetFree available type rightPattern →
    RhoPairCloseSmaller declarationColor targetFree
      (sizeOf leftPattern + sizeOf rightPattern) →
    (CollapsingRoot
        (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
          rhoReflectivePresentation.toReflectivePresentationDecl)
        leftPattern ∨
      CollapsingRoot
        (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
          rhoReflectivePresentation.toReflectivePresentationDecl)
        rightPattern) →
    canonicalize
        (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
          rhoReflectivePresentation.toReflectivePresentationDecl)
        leftPattern =
      canonicalize
        (costStaticReflectivePresentationDecl rhoCIGSLT declarationColor
          rhoReflectivePresentation.toReflectivePresentationDecl)
        rightPattern →
    (let leftEnvironment := CostStaticAtomEnvironment.ofInventory
      (leftView.node.semanticAtomEnvironment
        (leftView.children.normalizeValues
          (normalizeStatic := rhoHereditaryStaticNormalizer))).1
    let rightEnvironment := CostStaticAtomEnvironment.ofInventory
      (rightView.node.semanticAtomEnvironment
        (rightView.children.normalizeValues
          (normalizeStatic := rhoHereditaryStaticNormalizer))).1
    let cospan := leftEnvironment.semanticKeyCospan rightEnvironment
    ReflectiveContextSupport.RestoresTogether
      rhoCIGSLT.costWholeReflectionProfile cospan.commonSupport
        cospan.commonAssignment
        (cospan.reifyWith leftEnvironment.lookupAtom? cospan.leftSlot
          (leftView.node.canonicalizeReifiedTargetFrame leftEnvironment
            (costStaticReflectivePresentationDecl rhoCIGSLT leftColor
              rhoReflectivePresentation.toReflectivePresentationDecl)))
        (cospan.reifyWith rightEnvironment.lookupAtom? cospan.rightSlot
          (rightView.node.canonicalizeReifiedTargetFrame rightEnvironment
            (costStaticReflectivePresentationDecl rhoCIGSLT rightColor
              rhoReflectivePresentation.toReflectivePresentationDecl))))

/-- The flat residual discharges obligation A2x. -/
theorem rhoCollapsingCrossColorViewsRestorationAlignedInDomain_of_framesRestoreTogether
    {declarationColor : CostStaticColor}
    (flat : RhoCollapsingCrossColorFramesRestoreTogetherInDomain
      declarationColor) :
    RhoCollapsingCrossColorViewsRestorationAlignedInDomain declarationColor := by
  intro targetFree available outer leftPattern rightPattern type left right
    leftColor rightColor leftView rightView different sourceSortEq
    notInteracting admissible leftWellSorted rightWellSorted closeSmaller
    collapsing canonical
  exact RhoStaticFramesRestorationAligned.ofFramesRestoreTogether leftView
    rightView
    (flat leftView rightView different sourceSortEq notInteracting admissible
      leftWellSorted rightWellSorted closeSmaller collapsing canonical)

/-- **Obligation A2x is not merely implied by the flat residual — it is that
residual.**

Together with the previous theorem this pins the cross-colour half of A2 to a
single depth-uniform restoration equation between the two reified canonical
frames.  No weaker structural route through `PatternLeafAligned` survives in
the shared non-interacting fibre. -/
theorem rhoCollapsingCrossColorFramesRestoreTogetherInDomain_of_restorationAligned
    {declarationColor : CostStaticColor}
    (aligned : RhoCollapsingCrossColorViewsRestorationAlignedInDomain
      declarationColor) :
    RhoCollapsingCrossColorFramesRestoreTogetherInDomain declarationColor := by
  intro targetFree available outer leftPattern rightPattern type left right
    leftColor rightColor leftView rightView different sourceSortEq
    notInteracting admissible leftWellSorted rightWellSorted closeSmaller
    collapsing canonical
  exact rhoCrossColorNameFibre_framesRestoreTogether_of_restorationAligned
    leftView rightView different
    (rho_sourceSort_eq_name_of_ne_interacting notInteracting)
    (rho_sourceSort_eq_name_of_ne_interacting (sourceSortEq ▸ notInteracting))
    (aligned leftView rightView different sourceSortEq notInteracting
      admissible leftWellSorted rightWellSorted closeSmaller collapsing
      canonical)

end Mettapedia.Languages.ProcessCalculi.RhoCalculus
