import Mettapedia.GSLT.Core.LooseRelationEquipment

/-!
# Proof-relevant cognitive schematics

A cognitive schematic is the typed shape commonly written

```text
context and procedure -> goal
```

The procedure is operational, so the conjunction is not modeled as an
ordinary product of two inert propositions.  A context supplies evidence at a
source state, a proof-relevant loose arrow supplies an execution occurrence,
and a goal asks for evidence at the resulting state.

The resulting universal shape is a cell

```text
context ⊙ procedure ==> goal
```

in the loose-relation equipment.  Its predicate-transformer presentation is
`context -> mustPrecondition procedure goal`.  We also expose the distinct
constructive `mayPrecondition`: branching systems must not silently identify
"every outcome succeeds" with "a successful outcome can be selected".

`Schematic` contains only a candidate context/procedure/goal triple.
`MustAchieve` and `MayAchieve` are separate certificates.  Probabilistic
evidence, attention, priority, resource cost, authorization, and runtime
completion receipts are deliberately not fields of the candidate.

The presentation is architecture-neutral.  GSLT execution paths, cognitive
skills, problem-solving methods, tool workflows, and multi-agent protocols may
all instantiate the loose procedure relation without becoming the definition
of the interface.

References:

* Ben Goertzel, Cassio Pennachin, and Nil Geisweiller,
  *Engineering General Intelligence, Part 1*, section 8.2.3.
* Ben Goertzel with Gabriel Axel Montes, *The Consciousness Explosion*,
  chapter 7, on context-relative and open-ended motivations.
* Bart Jacobs, *Categorical Logic and Type Theory*, on indexed predicates.
* Dijkstra/Hoare predicate-transformer semantics for effectful computation.
-/

namespace Mettapedia.CognitiveArchitecture.CognitiveSchematic

open Mettapedia.GSLT.LooseRelationEquipment

universe u

/-- A proof-relevant predicate.  Its inhabitants are evidence for the
predicate at a state, rather than a collapsed Boolean answer. -/
abbrev EvidencePredicate (State : Type u) := State -> Type u

/-- Proof-relevant entailment between predicates on the same state carrier. -/
abbrev Entails {State : Type u}
    (antecedent consequent : EvidencePredicate State) : Type u :=
  forall {state}, antecedent state -> consequent state

/-- A universe-polymorphic unit object used to present a predicate as a loose
arrow into its state carrier. -/
abbrev UnitObject : Type u := PUnit.{u + 1}

/-- A candidate cognitive schematic.  Constructing this record asserts no
correctness: analysis may support it, refute it, revise it, or leave it open. -/
structure Schematic (Source Target : Type u) where
  context : EvidencePredicate Source
  procedure : Loose Source Target
  goal : EvidencePredicate Target

namespace Schematic

variable {Source Middle Target : Type u}

/-- Demonic or total achievement: every retained execution occurrence from a
context witness produces goal evidence. -/
abbrev MustAchieve (schematic : Schematic Source Target) : Type u :=
  forall {source target},
    schematic.context source ->
    schematic.procedure source target ->
    schematic.goal target

/-- Angelic or strategic achievement: from every context witness, one
successful target and its exact execution occurrence can be selected. -/
abbrev MayAchieve (schematic : Schematic Source Target) : Type u :=
  forall {source},
    schematic.context source ->
    Sigma fun target =>
      schematic.procedure source target × schematic.goal target

/-- One completed occurrence of a schematic.  Unlike `MayAchieve`, this is a
receipt for one particular source, target, and proof-relevant execution.  It
does not assert that the schematic succeeds for every admissible context. -/
structure Completion (schematic : Schematic Source Target) where
  source : Source
  contextWitness : schematic.context source
  target : Target
  execution : schematic.procedure source target
  goalWitness : schematic.goal target

/-- A may-achievement certificate produces an exact completed occurrence for
each supplied context witness. -/
def MayAchieve.complete
    {schematic : Schematic Source Target}
    (certificate : schematic.MayAchieve)
    {source : Source} (contextWitness : schematic.context source) :
    schematic.Completion := by
  obtain ⟨target, execution, goalWitness⟩ := certificate contextWitness
  exact ⟨source, contextWitness, target, execution, goalWitness⟩

/-- The weakest must-style precondition generated by a proof-relevant
procedure and a goal. -/
def mustPrecondition
    (procedure : Loose Source Target) (goal : EvidencePredicate Target) :
    EvidencePredicate Source :=
  fun source => forall {target}, procedure source target -> goal target

/-- The constructive may-style precondition.  It retains the chosen target,
execution occurrence, and goal witness. -/
def mayPrecondition
    (procedure : Loose Source Target) (goal : EvidencePredicate Target) :
    EvidencePredicate Source :=
  fun source => Sigma fun target => procedure source target × goal target

/-- Currying a must-style achievement certificate yields exactly an entailment
from the declared context to the must precondition.  This is the
proof-relevant weakest-precondition universal property used by the interface. -/
def mustAchieveEquivEntails (schematic : Schematic Source Target) :
    schematic.MustAchieve ≃
      Entails schematic.context
        (mustPrecondition schematic.procedure schematic.goal) where
  toFun certificate :=
    fun {source} contextWitness {target} execution =>
      certificate (source := source) (target := target)
        contextWitness execution
  invFun entailment :=
    fun {source target} contextWitness execution =>
      entailment (state := source) contextWitness
        (target := target) execution
  left_inv _ := rfl
  right_inv _ := rfl

/-- The analogous currying law for constructive may-style achievement. -/
def mayAchieveEquivEntails (schematic : Schematic Source Target) :
    schematic.MayAchieve ≃
      Entails schematic.context
        (mayPrecondition schematic.procedure schematic.goal) where
  toFun certificate := fun contextWitness => certificate contextWitness
  invFun entailment := fun contextWitness => entailment contextWitness
  left_inv _ := rfl
  right_inv _ := rfl

/-- Present a context predicate as a pointed loose arrow. -/
abbrev contextLoose (schematic : Schematic Source Target) :
    Loose UnitObject Source :=
  fun _ source => schematic.context source

/-- Present a goal predicate as a pointed loose arrow. -/
abbrev goalLoose (schematic : Schematic Source Target) :
    Loose UnitObject Target :=
  fun _ target => schematic.goal target

/-- A must-style achievement certificate is a cell from the horizontally
composed context and procedure to the goal. -/
def MustAchieve.toCell {schematic : Schematic Source Target}
    (certificate : schematic.MustAchieve) :
    Cell (_root_.id : UnitObject -> UnitObject)
      (_root_.id : Target -> Target)
      (comp schematic.contextLoose schematic.procedure)
      schematic.goalLoose where
  map witness := certificate witness.2.1 witness.2.2

/-- Read a cell `context ⊙ procedure ==> goal` as a must-style achievement
certificate. -/
def MustAchieve.ofCell {schematic : Schematic Source Target}
    (cell :
      Cell (_root_.id : UnitObject -> UnitObject)
        (_root_.id : Target -> Target)
        (comp schematic.contextLoose schematic.procedure)
        schematic.goalLoose) :
    schematic.MustAchieve := by
  intro source target contextWitness execution
  exact cell.map (source := PUnit.unit) (target := target)
    ⟨source, contextWitness, execution⟩

/-- The informal schematic judgment and the equipment-cell presentation carry
exactly the same data. -/
def mustAchieveEquivCell (schematic : Schematic Source Target) :
    schematic.MustAchieve ≃
      Cell (_root_.id : UnitObject -> UnitObject)
        (_root_.id : Target -> Target)
        (comp schematic.contextLoose schematic.procedure)
        schematic.goalLoose where
  toFun := MustAchieve.toCell
  invFun := MustAchieve.ofCell
  left_inv certificate := by
    funext source target contextWitness execution
    rfl
  right_inv cell := by
    apply Cell.ext
    intro anchor target witness
    rcases witness with ⟨source, contextWitness, execution⟩
    cases anchor
    rfl

/-- Sequentially compose candidate schematics.  Compatibility of the
intermediate predicates is evidence required by certificate composition, not
hidden data required merely to state the candidate. -/
def chain
    (first : Schematic Source Middle) (second : Schematic Middle Target) :
    Schematic Source Target where
  context := first.context
  procedure := comp first.procedure second.procedure
  goal := second.goal

/-- Must-style achievement is closed under sequential composition when the
first goal entails the second context. -/
def MustAchieve.chain
    {first : Schematic Source Middle} {second : Schematic Middle Target}
    (firstCertificate : first.MustAchieve)
    (secondCertificate : second.MustAchieve)
    (handoff : forall {middle}, first.goal middle -> second.context middle) :
    (Schematic.chain first second).MustAchieve := by
  intro source target contextWitness execution
  exact secondCertificate
    (handoff (firstCertificate contextWitness execution.2.1))
    execution.2.2

/-- May-style achievement is closed under sequential composition while
retaining the selected middle state and both execution occurrences. -/
def MayAchieve.chain
    {first : Schematic Source Middle} {second : Schematic Middle Target}
    (firstCertificate : first.MayAchieve)
    (secondCertificate : second.MayAchieve)
    (handoff : forall {middle}, first.goal middle -> second.context middle) :
    (Schematic.chain first second).MayAchieve := by
  intro source contextWitness
  obtain ⟨middle, firstExecution, firstGoal⟩ :=
    firstCertificate contextWitness
  obtain ⟨target, secondExecution, secondGoal⟩ :=
    secondCertificate (handoff firstGoal)
  exact
    ⟨target, ⟨middle, firstExecution, secondExecution⟩, secondGoal⟩

/-- Sequential weakest-precondition calculation for must semantics.  The law
is an equivalence because proof-relevant horizontal composition retains its
Sigma-shaped route witness. -/
def mustPreconditionComp
    (first : Loose Source Middle) (second : Loose Middle Target)
    (goal : EvidencePredicate Target) (source : Source) :
    mustPrecondition (comp first second) goal source ≃
      mustPrecondition first (mustPrecondition second goal) source where
  toFun certificate :=
    fun {middle} firstExecution {target} secondExecution =>
      certificate ⟨middle, firstExecution, secondExecution⟩
  invFun certificate :=
    fun {target} execution => certificate execution.2.1 execution.2.2
  left_inv certificate := by
    funext target execution
    rfl
  right_inv certificate := by
    funext middle firstExecution target secondExecution
    rfl

/-- Sequential weakest-precondition calculation for may semantics. -/
def mayPreconditionComp
    (first : Loose Source Middle) (second : Loose Middle Target)
    (goal : EvidencePredicate Target) (source : Source) :
    mayPrecondition (comp first second) goal source ≃
      mayPrecondition first (mayPrecondition second goal) source where
  toFun witness :=
    ⟨witness.2.1.1, witness.2.1.2.1,
      ⟨witness.1, witness.2.1.2.2, witness.2.2⟩⟩
  invFun witness :=
    ⟨witness.2.2.1,
      ⟨witness.1, witness.2.1, witness.2.2.2.1⟩,
      witness.2.2.2.2⟩
  left_inv _ := rfl
  right_inv _ := rfl

/-- Replace the context of a candidate without changing its procedure or goal. -/
def withContext (schematic : Schematic Source Target)
    (context : EvidencePredicate Source) : Schematic Source Target where
  context := context
  procedure := schematic.procedure
  goal := schematic.goal

/-- Replace the goal of a candidate without changing its context or procedure. -/
def withGoal (schematic : Schematic Source Target)
    (goal : EvidencePredicate Target) : Schematic Source Target where
  context := schematic.context
  procedure := schematic.procedure
  goal := goal

/-- A must certificate transports to a stronger context. -/
def MustAchieve.strengthenContext {schematic : Schematic Source Target}
    (certificate : schematic.MustAchieve)
    (context : EvidencePredicate Source)
    (strengthening : forall {source}, context source -> schematic.context source) :
    (schematic.withContext context).MustAchieve := by
  intro source target contextWitness execution
  exact certificate (strengthening contextWitness) execution

/-- A may certificate transports to a stronger context. -/
def MayAchieve.strengthenContext {schematic : Schematic Source Target}
    (certificate : schematic.MayAchieve)
    (context : EvidencePredicate Source)
    (strengthening : forall {source}, context source -> schematic.context source) :
    (schematic.withContext context).MayAchieve := by
  intro source contextWitness
  exact certificate (strengthening contextWitness)

/-- A must certificate transports to a weaker goal. -/
def MustAchieve.weakenGoal {schematic : Schematic Source Target}
    (certificate : schematic.MustAchieve)
    (goal : EvidencePredicate Target)
    (weakening : forall {target}, schematic.goal target -> goal target) :
    (schematic.withGoal goal).MustAchieve := by
  intro source target contextWitness execution
  exact weakening (certificate contextWitness execution)

/-- A may certificate transports to a weaker goal. -/
def MayAchieve.weakenGoal {schematic : Schematic Source Target}
    (certificate : schematic.MayAchieve)
    (goal : EvidencePredicate Target)
    (weakening : forall {target}, schematic.goal target -> goal target) :
    (schematic.withGoal goal).MayAchieve := by
  intro source contextWitness
  obtain ⟨target, execution, goalWitness⟩ := certificate contextWitness
  exact ⟨target, execution, weakening goalWitness⟩

/-- The identity procedure is a candidate from any predicate to itself. -/
def skip (predicate : EvidencePredicate Source) : Schematic Source Source where
  context := predicate
  procedure := identity
  goal := predicate

/-- Identity achieves its predicate under must semantics. -/
def skipMust (predicate : EvidencePredicate Source) :
    (skip predicate).MustAchieve := by
  intro source target contextWitness same
  cases same.down.down
  exact contextWitness

/-- Identity achieves its predicate under may semantics. -/
def skipMay (predicate : EvidencePredicate Source) :
    (skip predicate).MayAchieve := by
  intro source contextWitness
  exact ⟨source, ⟨⟨rfl⟩⟩, contextWitness⟩

end Schematic

/-! ## Positive and negative controls -/

namespace Canary

/-- A branch may return either Boolean outcome, while only `true` meets the
goal. -/
def branching : Schematic Unit Bool where
  context := fun _ => Unit
  procedure := fun _ _ => Unit
  goal := fun outcome => if outcome then Unit else Empty

/-- Positive control: the successful branch can be selected. -/
def branchingMay : branching.MayAchieve := by
  intro _ _
  exact ⟨true, (), ()⟩

/-- Negative control: existence of a successful branch does not establish
that every branch succeeds. -/
theorem branching_not_must : IsEmpty branching.MustAchieve := by
  constructor
  intro certificate
  exact Empty.elim
    (certificate (source := ()) (target := false) () ())

/-- A candidate with no execution occurrence.  Candidate formation remains
possible even when no achievement certificate exists. -/
def unavailable : Schematic Unit Unit where
  context := fun _ => Unit
  procedure := fun _ _ => Empty
  goal := fun _ => Unit

/-- Negative control: a proposed procedure is not an execution receipt. -/
theorem unavailable_not_may : IsEmpty unavailable.MayAchieve := by
  constructor
  intro certificate
  obtain ⟨_target, execution, _goal⟩ := certificate (source := ()) ()
  exact Empty.elim execution

inductive DuplicateOccurrence where
  | first
  | second
  deriving DecidableEq

/-- Two equal source/target values retain distinct procedure occurrences. -/
def duplicated : Schematic Unit Unit where
  context := fun _ => Unit
  procedure := fun _ _ => DuplicateOccurrence
  goal := fun _ => Unit

def chooseFirst : duplicated.MayAchieve := by
  intro _ _
  exact ⟨(), .first, ()⟩

def chooseSecond : duplicated.MayAchieve := by
  intro _ _
  exact ⟨(), .second, ()⟩

def chosenOccurrence (certificate : duplicated.MayAchieve) :
    DuplicateOccurrence :=
  (certificate (source := ()) ()).2.1

/-- Positive occurrence canary: equal result values do not collapse distinct
execution witnesses. -/
theorem duplicate_choices_remain_distinct :
    chosenOccurrence chooseFirst != chosenOccurrence chooseSecond := by
  decide

end Canary

#print axioms Schematic.mustAchieveEquivCell
#print axioms Schematic.mustAchieveEquivEntails
#print axioms Schematic.mayAchieveEquivEntails
#print axioms Schematic.mustPreconditionComp
#print axioms Schematic.mayPreconditionComp
#print axioms Canary.branching_not_must
#print axioms Canary.unavailable_not_may
#print axioms Canary.duplicate_choices_remain_distinct

end Mettapedia.CognitiveArchitecture.CognitiveSchematic
