import Mettapedia.GSLT.ProgrammableSpaces
import Mettapedia.Logic.KernelFoundationManifest
import Lean.Util.CollectAxioms

/-!
# Dependency qualification for programmable spaces

This command checks every checked declaration, including private declarations,
in every owner module listed below. It rejects owned axioms and all transitive
axioms except `propext`, `Quot.sound`, and the exact inherited `Classical.choice`
endpoints below. Constructive modules have no such endpoints. The inherited
uses come from existing source codecs, cursor machinery and finite/counting
library comparisons; they are not object-language choice laws.

Compiler-only entries are reported separately. The listed compiler runtime
counterparts must have the exact listed safe origins with matching owner,
universes and types; neither category receives mathematical proof credit.
This qualification does not verify emitted machine code or a native provider.

Compile this module with `lake build Mettapedia.GSLT.ProgrammableSpacesQualification`.
The complete per-declaration dependencies are emitted by the command.
-/

open Lean Elab Command

run_cmd do
  let modules : Array Name := #[
    `Mettapedia.GSLT.Core.ProgrammableSpace,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge,
    `Mettapedia.GSLT.Core.ProgrammableSpaceInference,
    `Mettapedia.GSLT.Core.ProgrammableSpaceInferenceControls,
    `Mettapedia.GSLT.Core.ProgrammableSpaceReachability,
    `Mettapedia.GSLT.Core.ProgrammableSpaceStorage,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Grammar,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceAtomCoding,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceEvidence,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceEvidenceBatch,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceEvidenceConsumers,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceEvidenceControls,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceEvidenceDependence,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceEvidenceFinite,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceEvidenceInference,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceEvidenceMaterial,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceEvidenceMaterialControls,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceEvidenceOccurrenceControls,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceEvidenceReadings,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceInferenceMaterial,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2KeyReadings,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMaterial,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMaterialControls,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMaterialFamilies,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMaterialInstances,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceReadings]
  let classicalEndpoints : Array Name := #[
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.Controls.compiled_support_forgets_duplicate_premise,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.Controls.exact_saturated_support,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.Controls.exact_saturated_support._proof_1_1,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.Controls.finite_execution_reaches_two,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.Controls.finite_execution_reaches_two._proof_1_1,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.Controls.finite_execution_refuses_unreachable,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.Controls.finite_execution_refuses_unreachable._proof_1_1,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.Controls.ordered_positions_are_retained,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.Controls.saturated,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.authoredTheory,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.authoredTheory.eq_1,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.authored_closure_eq_saturation,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.authored_derivation_iff_compiled,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.authored_derivation_to_compiled,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.compileRule,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.compileRule.eq_1,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.compiledProgram,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.compiled_derivation_to_authored,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.compiled_rule_iff,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.fair_support_eq_saturation,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.finite_facts_available,
    `Mettapedia.GSLT.Core.ProgrammableSpaceHornBridge.finite_fair_run_eventually_exact,
    `Mettapedia.GSLT.Core.ProgrammableSpaceInferenceControls.ProvenanceAndCost.support_erases_derivation_multiplicity,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.Workspace,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.actual_rewrite_action,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.afterRewrite,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.atoms,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.both_agendas_registered,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.data_alone_does_not_execute,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.initial,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.initial.eq_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.languages,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.policies,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.registered,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.registered.eq_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.retained_event_has_source_and_policy,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.rewritePosition,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.rewritePosition._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.rewriteSession,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.rewrite_admitted,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.rewrite_event_in_mixed_store,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.rewrite_keeps_transaction,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.scopes_retained,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.transactionPolicy,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.transactionPosition,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.transactionPosition._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.transactionSession,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.transaction_admitted,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.transaction_event_in_mixed_store,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.transaction_event_in_mixed_store._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceInstances.transaction_event_in_mixed_store._proof_1_2,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.Admitted,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.Advance,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.Advance.casesOn,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.Advance.commit,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.Advance.rec,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.Advance.recOn,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.Observes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.Receipt.after,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.admitted_has_no_guards,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.admitted_iff_grammar,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.advance_preserves_physical_support,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.advance_source_step,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.committed_does_not_fire,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.completed_receipt_unique,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.event_iff_selected_firing,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.language,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.load,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.loadParsed,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.load_support_nodup,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.rendered_bytes_load_exactly,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.selected_has_event,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2.selected_source_step,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.captured_payload_keeps_inner_scope,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.captured_payload_keeps_inner_scope._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_facts,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_facts._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_facts._proof_1_2,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_facts._proof_1_3,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_facts._proof_1_4,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_facts._proof_1_5,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_facts._proof_1_6,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_facts._proof_1_7,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_facts._proof_1_8,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_step,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_step._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_step._proof_1_2,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_step._proof_1_3,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_step._proof_1_4,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_step._proof_1_5,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_step._proof_1_6,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_step._proof_1_7,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_step._proof_1_8,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.cycle_zero,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.expectedFacts,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.facts,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.generated_local_becomes_next_input,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.generated_local_becomes_next_input._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.oneShot_consumer_first,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.oneShot_consumer_first._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.oneShot_order_observable,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.oneShot_producer_first,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.oneShot_producer_first._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.output_local_directive_runs,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.output_local_directive_runs._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.run,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.run_add_store,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.run_cycle,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.run_zero_store,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.standing_both_orders_reach_all_facts,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.standing_both_orders_reach_all_facts._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.standing_both_orders_reach_all_facts._proof_1_2,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.standing_eventual_agreement,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.standing_eventually_never_quiescent,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.standing_still_has_work,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.standing_still_has_work._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.standing_still_has_work._proof_1_2,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Grammar.all_unarySink_decodes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Grammar.btm_cursor_rows,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Grammar.btm_source_rows,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Grammar.grammar_decodes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Grammar.supported_parsing_fields,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Grammar.unarySink_decodes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.actual_private_step,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.actual_publication,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.actual_two_grant_run,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.checkpoint100,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.checkpoint100._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.continued_cursor_finishes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.empty_explicit_input_admitted,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.erasure_without_reversal_is_wrong,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.erasure_without_reversal_is_wrong._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.exact_atomic_source_comparison,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.explicitRows,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.explicit_finalization,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.explicit_finalization._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.explicit_selected,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.explicit_selected._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.explicit_self_read_keeps_authored_input,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.explicit_self_read_keeps_authored_input._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.explicit_source_admitted,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.explicit_source_admitted._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.finished,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.full_source_rows,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.malformed_btm_not_admitted,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.normalization_changes_reflective_observation,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.normalization_changes_reflective_observation._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.packet100,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.packet100._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.partial_answer_stays_private,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.partial_answer_stays_private._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.pausedPacket?,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.pausedPacket?.match_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.public_source_positions,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.public_source_positions._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.raw_stack_positions,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.raw_stack_positions._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2GrammarControls.start,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.Result,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.allowance,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.collect_complete,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.completed_finalize,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.completed_rows,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.finalize,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.initial,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.live,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.packet,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.pause_resume,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.paused_cannot_publish,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.publish,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.publish_complete,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.publish_sound,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.run,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.run_observation,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Matching.snapshot,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.Controls.actual_live_support_is_different,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.Controls.actual_owned_view,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.Controls.actual_owned_view._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.Controls.actual_private_reconstruction,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.Controls.actual_publication_releases_owned_directive,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.Controls.actual_reconstruction,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.StoreView.reconstruct,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.matching_reconstruction,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.observe,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.observe.match_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.physical_support_changes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.private_step_retains_logical_support,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.reconstruction_iff_present,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.selected_atom_present,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.selected_material_reconstruction,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.selected_reconstruction,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.take,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Ownership.taken_key_is_not_live,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls.generated_activation_uses_captured_result,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls.generated_activation_uses_captured_result._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls.joinRows,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls.join_has_actual_event,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls.join_has_actual_event._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls.join_has_actual_event._proof_1_2,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls.join_source_admitted,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls.join_source_admitted._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls.publication_preserves_support_not_derivation_multiplicity,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls.publication_preserves_support_not_derivation_multiplicity._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls.two_paths_emit_same_conclusion,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls.two_paths_emit_same_conclusion._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls.two_paths_have_distinct_substitutions,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls.two_paths_have_distinct_substitutions._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls.two_paths_retain_physical_positions,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ReceiptControls.two_paths_retain_physical_positions._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Advance,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Advance.casesOn,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Advance.commit,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Advance.pause,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Advance.rec,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Advance.recOn,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.AtomicTransition,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint._sizeOf_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint._sizeOf_inst,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.afterPause,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.afterPause._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.before,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.casesOn,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.completed_rows,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.ctorIdx,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.finite_completion,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.finite_completion._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.granted,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.mk,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.mk._flat_ctor,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.mk.inj,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.mk.injEq,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.mk.noConfusion,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.mk.sizeOf_spec,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.noConfusion,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.noConfusionType,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.packet,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.pause_then_resume,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.privateRows,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.privateRows.match_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.reached,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.rec,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.recOn,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.remainingSyntax,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.request,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.resume,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.resume_exact,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.spent,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.start,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.start._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Checkpoint.zero_grant,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.FinishedFor,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Observes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Observes.match_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.PacketFor,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual._sizeOf_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual._sizeOf_inst,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.casesOn,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.committed.elim,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.committed.inj,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.committed.injEq,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.committed.noConfusion,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.committed.sizeOf_spec,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.ctorElim,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.ctorElimType,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.ctorIdx,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.matching,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.matching.elim,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.matching.inj,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.matching.injEq,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.matching.noConfusion,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.matching.sizeOf_spec,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.noConfusion,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.noConfusionType,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.rec,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Residual.recOn,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.Transition,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.advance_refines_atomic,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.atomicConfiguration,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.atomicResidual,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.atomicResidual.match_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.committed_does_not_fire,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.completed_source_step,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.language,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.pending_does_not_publish,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.private_step_preserves_store,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.run_refines_atomic_run,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.selected_checkpoint_has_publication,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.stale_snapshot_cannot_step,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Resumable.transition_refines_atomic_run,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.actual_publication,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.actual_two_grant_run,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.all_answers_are_not_exhaustion,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.all_answers_are_not_exhaustion._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.changed_store_rejects_old_cursor,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.checkpoint100,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.checkpoint100._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.checkpoint150,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.checkpoint150._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.continued_cursor_finishes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.finished,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.first_grant_has_private_answer,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.first_grant_has_private_answer._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.first_grant_is_actual_private_step,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.next_private_grant_retains_both_paths,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.packet100,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.packet100._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.packet150,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.packet150._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.pausedPacket?,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.pausedPacket?.match_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.public_observation_has_both_paths,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.restarting_loses_bounded_completion,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.selected,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.selected._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.start,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.two_grants_have_atomic_source_meaning,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2ResumableControls.zero_budget_is_not_publication,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.Advance,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.Advance.casesOn,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.Advance.commit,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.Advance.rec,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.Advance.recOn,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.Observes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.admitted_iff_grammar,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.admitted_sinks,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.advance_preserves_physical_support,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.advance_source_step,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.after,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.committed_does_not_fire,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.completed_finalize,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.completed_receipt_unique,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.event_iff_selected_firing,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.finalization_ordered_writes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.finalization_source_agreement,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.finalize,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.fire,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.language,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.selected_has_event,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.selected_source_step,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.sourceStep,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.sourceStep.eq_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.sourceStep.eq_2,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.unary_sink_allowed,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajor.unary_sinks_allowed,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.actualRows,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.actual_atomic_publication,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.actual_private_step,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.actual_publication,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.actual_two_grant_run,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.actual_write_order,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.actual_write_order._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.admitted,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.admitted._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.checkpoint10,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.checkpoint10._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.continued_cursor_finishes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.disjointRows,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.disjoint_actual_values,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.disjoint_actual_values._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.disjoint_mixed_effects_agree,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.disjoint_mixed_effects_agree._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.exact_atomic_comparison,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.finished,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.native_finalization,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.native_finalization._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.observed_outcomes_separate,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.observed_outcomes_separate._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.original_explicit_positive_agrees,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.original_explicit_positive_agrees._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.packet10,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.packet10._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.pausedPacket?,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.pausedPacket?.match_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.physical_origins,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.physical_origins._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.selected,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.selected._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.source_finalization,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.source_finalization._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.start,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.support_separation,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorControls.support_separation._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.Advance,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.Advance.casesOn,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.Advance.commit,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.Advance.pause,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.Advance.rec,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.Advance.recOn,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.AtomicTransition,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.Checkpoint,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.FinishedFor,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.Observes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.Observes.match_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.PacketFor,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.Residual,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.Transition,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.advance_refines_atomic,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.atomicConfiguration,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.atomicResidual,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.atomicResidual.match_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.committed_does_not_fire,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.completed_source_step,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.language,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.pending_does_not_publish,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.private_step_preserves_store,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.run_refines_atomic_run,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.selected_checkpoint_has_publication,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.stale_snapshot_cannot_step,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorResumable.transition_refines_atomic_run,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.Independent,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.Independent.eq_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.Write.apply,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.Write.onSupport,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.Write.onSupport.eq_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.Write.onSupport.eq_2,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.add_fold_support,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.add_fold_support._simp_1_10,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.add_fold_support._simp_1_9,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.commuting_orders,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.execute_support,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.independent_commutes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.independent_commutes._simp_1_10,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.independent_commutes._simp_1_9,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.one,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.one.eq_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.remove_fold_support,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.remove_fold_support._simp_1_10,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.remove_fold_support._simp_1_11,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.remove_fold_support._simp_1_9,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.row,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.row.eq_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.row_ordered_writes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.rows,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.rows.eq_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.rows_nodup,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.rows_ordered_writes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.single_source_sink_support,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.source_agreement,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.source_ordered_writes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.staging_support,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.staging_support._simp_1_2,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.staging_support._simp_1_3,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.subtract_support,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.subtract_support._simp_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.subtract_support._simp_1_2,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.subtract_support._simp_1_3,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.support,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.support.eq_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.support_cons,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.support_insert,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.support_nil,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.support_remove,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.support_remove._simp_1_2,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.support_remove._simp_1_5,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.union_support,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.union_support._simp_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.union_support._simp_1_2,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.write_nodup,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2RowMajorWrites.write_support,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.Material.actualContinuation,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.Material.actualContinuation._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.Material.beforeState,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.Material.beforeState._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.Material.empty_source_has_no_continuation,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.Material.material_decodes_actual_continuation,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.Material.private_and_foreign_steps_preserve_current_support,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.Material.publication_adds_declared_fact,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.Material.publication_adds_declared_fact._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.Material.publication_has_material_continuation,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.Material.read,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.Workspace,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.actual_commit,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.actual_history_is_sound,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.actual_interleaved_run,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.actual_pause,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.afterCommit,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.afterPause,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.afterRewrite,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.after_commit_started,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.after_pause_started,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.after_rewrite_started,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.atoms,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.changed_store_blocks_held_packet,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.changed_store_blocks_held_packet._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.checkpoint100,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.checkpoint100._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.checkpoint100._proof_2,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.commitEvent,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.commitReceipt,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.commit_step,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.committedSession,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.completed_rows_keep_actual_origins,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.completed_rows_keep_actual_origins._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.completion_exact,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.completion_exact._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.distinct_accounts_and_three_events,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.execution_keeps_scopes_and_origins,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.exhausted_publication_observed,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.finished,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.finished._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.finishedResult?,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.finished_get,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.first_grant_retains_private_answer,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.first_grant_retains_private_answer._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.held_packet_survives_beta,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.initial,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.initialCheckpoint,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.languages,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.lower_budget_rejects_actual_commit,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.packet100,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.packet100._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.partial_rows_are_not_an_outcome,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.pauseEvent,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.pause_exact,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.pause_step,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.pausedPacket?,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.pausedPacket?.match_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.pausedSession,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.paused_get,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.policies,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.publication,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.publication_has_atomic_source_meaning,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.publication_store,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.publication_store._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.registered,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.registered_started,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.resultAtoms,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.rewriteEvent,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.rewritePosition,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.rewritePosition._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.rewriteSession,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.rewrite_admitted,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.rewrite_step,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.rewrittenSession,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.selected,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.selected._proof_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.transactionPolicy,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.transactionPosition,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.transactionPosition._proof_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.transactionSession,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceResumableInstances.transaction_admitted,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite.Lambda.beta_adapter,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite.Lambda.beta_event,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite.SourceEvent,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite.adapter_exact,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite.adapter_exact.match_1_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite.adapter_exact.match_1_3,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite.depthPolicy,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite.depth_policy_accounts,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite.executed_has_receipt,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite.foreign_exec_inert,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite.language,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite.receipt_exists_iff_source_reduct,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite.request_admitted,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite.source_event_executes,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite.source_event_scoped,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceRewrite.store_preserved,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.another_language_stays_data,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.bound_and_free_distinct,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.collection_remainder_retained,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.decode,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.decode.eq_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.decode.eq_2,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.decode_encode,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.encode,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.encode.eq_1,
    `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.encode_injective,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.actual_ground_instance,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.actual_source_origins,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.actual_template_matching,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.actual_template_matching._proof_1_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.different_receipts,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.different_roots,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.fact_cannot_recover_proof,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.facts_equal,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.first,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.firstIndex,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.firstIndex._proof_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.lookup_checked,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.lookup_checked._proof_1_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.native_typed_readouts,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.not_origin_separated,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.same_material_fact_distinct_proof,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.second,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.secondIndex,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.secondIndex._proof_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.shared_origin,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceHorn.ActualJoin.valid,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.actual_material_rows_differ,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.actual_rows,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.actual_rows._proof_1_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.both_emit_reachable,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.both_emit_reachable._proof_1_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.both_origins_are_material_members,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.fact_support_cannot_recover_rows,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.first,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.first._proof_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.first_source_origins,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.first_source_origins._proof_1_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.material_batch_retains_two_rows,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.native_join_readouts,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.published_support_is_single_result,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.receipt,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.row_count,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.same_fact_support_two_material_rows,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.second,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.second._proof_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.second_source_origins,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.second_source_origins._proof_1_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.shared_query_occurrence,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.shared_query_occurrence._proof_1_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.substitutions_differ,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2EvidenceMaterial.ActualJoin.substitutions_differ._proof_1_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.Workspace,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.actualContinuation,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.actualContinuation._proof_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.actual_account_and_publication,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.actual_account_and_publication._proof_1_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.actual_pause_step,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.actual_publication_is_material_member,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.actual_publication_step,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.actual_run,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.afterCommit,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.afterPause,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.after_commit_started,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.after_pause_started,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.beforeState,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.beforeState._proof_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.commitEvent,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.commitReceipt,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.committedSession,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.cursor_and_source_witness_order,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.decoder_recovers_actual_continuation,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.empty_source_has_no_continuation,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.events_are_source_and_policy_valid,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.initial,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.languages,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.observation_keeps_original_literal,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.observations,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.observations.match_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.original_explicit_literal_retained,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.original_scope_and_occurrence_retained,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.pauseEvent,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.pausedSession,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.policies,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.polls_are_observable,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.polls_are_observable._proof_1_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.private_rows_are_not_an_outcome,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.publication,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.publication_is_an_outcome,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.read,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.registered,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.registered_started,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.session,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2GrammarMaterial.source_admitted,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2KeyReadings.keySupport,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2KeyReadings.keySupport.eq_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2KeyReadings.keySupport_eq_iff_support,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2KeyReadings.variable_key_reading_identifies_names,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2KeyReadings.variable_key_reading_identifies_names._proof_1_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.Workspace,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.actualContinuation,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.actualContinuation._proof_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.actual_history_is_sound,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.actual_pause_step,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.actual_poll_account,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.actual_publication_is_material_member,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.actual_publication_step,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.actual_run,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.afterCommit,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.afterPause,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.after_commit_started,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.after_pause_started,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.beforeState,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.beforeState._proof_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.commitEvent,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.commitReceipt,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.committedSession,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.commuting_finalizers_material_agreement,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.conflicting_effects_key_material_separate,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.cursorPolicy,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.decoder_recovers_actual_continuation,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.disjoint_effects_material_agreement,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.initial,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.insufficient_budget_refuses_publication,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.languages,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.observations,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.observations.match_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.original_literal_and_physical_origins_retained,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.original_scope_and_occurrence_retained,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.pauseEvent,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.pausedSession,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.policies,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.publication,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.publication_observed_in_declared_profile,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.publication_reveals_middle_fact,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.publication_reveals_middle_fact._proof_1_1,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.read,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.registered,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.registered_started,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.session,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.source_admitted,
    `Mettapedia.GSLT.Logic.ProgrammableSpaceMM2OrderedMaterial.unfinished_rows_stay_private,
    `Mettapedia.GSLT.ProgrammableSpaceEvidence.Controls.actual_production_count,
    `Mettapedia.GSLT.ProgrammableSpaceEvidence.Controls.actual_production_count._proof_1_1,
    `Mettapedia.GSLT.ProgrammableSpaceEvidence.Controls.actual_production_receipts,
    `Mettapedia.GSLT.ProgrammableSpaceEvidence.card_premiseChoices,
    `Mettapedia.GSLT.ProgrammableSpaceEvidence.inputBag,
    `Mettapedia.GSLT.ProgrammableSpaceEvidence.mem_producedReceipts,
    `Mettapedia.GSLT.ProgrammableSpaceEvidence.premiseChoices,
    `Mettapedia.GSLT.ProgrammableSpaceEvidence.premiseChoices._f,
    `Mettapedia.GSLT.ProgrammableSpaceEvidence.premiseChoices._sunfold,
    `Mettapedia.GSLT.ProgrammableSpaceEvidence.premiseChoices.eq_1,
    `Mettapedia.GSLT.ProgrammableSpaceEvidence.premiseChoices.eq_2,
    `Mettapedia.GSLT.ProgrammableSpaceEvidence.premiseChoices.eq_def,
    `Mettapedia.GSLT.ProgrammableSpaceEvidence.producedReceipts,
    `Mettapedia.GSLT.ProgrammableSpaceEvidence.producedReceipts.eq_1,
    `Mettapedia.GSLT.ProgrammableSpaceEvidence.produced_count,
    `Mettapedia.GSLT.ProgrammableSpaceEvidence.produced_fact,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialControls.actual_beta_has_material_continuation,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialControls.betaContinuation,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialControls.betaContinuation._proof_1,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialControls.empty_continuation_fibre_is_empty,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialControls.fabricated_rewrite_is_excluded,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.actual_computation_changes_declared_account,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.actual_computation_changes_declared_account._proof_1_1,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.actual_computation_keeps_current_facts,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.afterState,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.afterState._proof_1,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.agendaView,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.agendaView.eq_1,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.beforeState,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.beforeState._proof_1,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.behaviour_preserves_support,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.coalgebra,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.current_facts_do_not_determine_observed_behaviour,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.factInterpretation,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.factRead,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.factRead.eq_1,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.factValue,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.fact_read_is_declared,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.fact_value_kernel,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.family,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.observationList,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.observationList.eq_1,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.policyOutcomeInterpretation,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.policyOutcomeRead,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.policyOutcomeRead.eq_1,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.policy_outcome_behaviour_preserves_support,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.registered_started,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.transactionView,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.workView,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.workView.match_1,
    `Mettapedia.GSLT.ProgrammableSpaceMaterialInstances.workView.match_3,
    `Mettapedia.Languages.ProcessCalculi.MORK.MorkSupportNodup.eq_1,
    `Mettapedia.Languages.ProcessCalculi.MORK.cMatchInputSpecMork.eq_1,
    `Mettapedia.Languages.ProcessCalculi.MORK.cMatchInputSpecMork.eq_2,
    `Mettapedia.Languages.ProcessCalculi.MORK.cMatchSourceFactorMork.eq_1,
    `Mettapedia.Languages.ProcessCalculi.MORK.cMatchSourceFactorMork.eq_2,
    `Mettapedia.Languages.ProcessCalculi.MORK.cMatchSourceFactorMork.eq_3,
    `Mettapedia.Languages.ProcessCalculi.MORK.cMatchSourceFactorsMork.eq_1,
    `Mettapedia.Languages.ProcessCalculi.MORK.cMatchSourceFactorsMork.eq_2,
    `Mettapedia.Languages.ProcessCalculi.MORK.cMatchSourceFactorsMork.eq_def,
    `Mettapedia.Languages.ProcessCalculi.MORK.cRuleScopedSourceWorkQueueStep.eq_1,
    `Mettapedia.Languages.ProcessCalculi.MORK.cRuleScopedSourceWorkQueueStep.eq_2,
    `Mettapedia.Languages.ProcessCalculi.MORK.decodeSupportedSourceExec.eq_1,
    `Mettapedia.Languages.ProcessCalculi.MORK.extractSupportedSourceExecFact.eq_1,
    `Mettapedia.Languages.ProcessCalculi.MORK.stageRuleScopedSink.eq_1]
  let runtimeEndpoints : Array (Name × Name) := #[
    (`Mettapedia.GSLT.Core.ProgrammableSpaceInference.iterate._unsafe_rec, `Mettapedia.GSLT.Core.ProgrammableSpaceInference.iterate),
    (`Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.advancePhase._unsafe_rec, `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceMM2Controls.advancePhase),
    (`Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.atomWire._unsafe_rec, `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.atomWire),
    (`Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.atomsWire._unsafe_rec, `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.atomsWire),
    (`Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.wireAtoms._unsafe_rec, `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.wireAtoms),
    (`Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.wireAtom._unsafe_rec, `Mettapedia.GSLT.LanguageDef.ProgrammableSpaceSyntax.wireAtom),
    (`Mettapedia.GSLT.Logic.ProgrammableSpaceAtomCoding.listGraph._unsafe_rec, `Mettapedia.GSLT.Logic.ProgrammableSpaceAtomCoding.listGraph),
    (`Mettapedia.GSLT.Logic.ProgrammableSpaceAtomCoding.graph._unsafe_rec, `Mettapedia.GSLT.Logic.ProgrammableSpaceAtomCoding.graph),
    (`Mettapedia.GSLT.ProgrammableSpaceEvidence.Derivation.origins._unsafe_rec, `Mettapedia.GSLT.ProgrammableSpaceEvidence.Derivation.origins),
    (`Mettapedia.GSLT.ProgrammableSpaceEvidence.Derivation.rules._unsafe_rec, `Mettapedia.GSLT.ProgrammableSpaceEvidence.Derivation.rules),
    (`Mettapedia.GSLT.ProgrammableSpaceEvidence.Finite.firstIndex._unsafe_rec, `Mettapedia.GSLT.ProgrammableSpaceEvidence.Finite.firstIndex),
    (`Mettapedia.GSLT.ProgrammableSpaceEvidence.Finite.unique._unsafe_rec, `Mettapedia.GSLT.ProgrammableSpaceEvidence.Finite.unique),
    (`Mettapedia.GSLT.ProgrammableSpaceEvidence.Material.spine._unsafe_rec, `Mettapedia.GSLT.ProgrammableSpaceEvidence.Material.spine),
    (`Mettapedia.GSLT.ProgrammableSpaceEvidence.Material.treeGraph._unsafe_rec, `Mettapedia.GSLT.ProgrammableSpaceEvidence.Material.treeGraph),
    (`Mettapedia.GSLT.ProgrammableSpaceEvidence.premiseChoices._unsafe_rec, `Mettapedia.GSLT.ProgrammableSpaceEvidence.premiseChoices)]
  let allowed := #[``propext, ``Quot.sound]
  unless modules.toList.eraseDups.length == modules.size &&
      classicalEndpoints.toList.eraseDups.length == classicalEndpoints.size &&
      runtimeEndpoints.toList.eraseDups.length == runtimeEndpoints.size do
    throwError "duplicate qualification inventory entry"
  let env ← getEnv
  let loadedModules := env.header.moduleNames
  let mut observedClassical : Array Name := #[]
  let mut observedRuntime : Array (Name × Name) := #[]
  let mut totalSafe := 0
  let mut totalTheorems := 0
  let mut totalPrivate := 0
  let mut totalCompiler := 0
  for imported in loadedModules do
    let rendered := imported.toString
    if rendered.startsWith "Mettapedia.GSLT." &&
        rendered.contains ".ProgrammableSpace" &&
        imported != `Mettapedia.GSLT.ProgrammableSpaces &&
        imported != `Mettapedia.GSLT.ProgrammableSpacesQualification &&
        !modules.contains imported then
      throwError "unqualified programmable-space owner module {imported}"
    if rendered.contains "PrimeCandidate" || rendered.contains "Megalodon" ||
        rendered.contains "MessyWIP" || rendered.startsWith "Mettapedia.Archive" then
      throwError "forbidden foundation dependency {imported}"
    logInfo m!"IMPORT {imported}"
  for moduleName in modules do
    let some moduleIndex := loadedModules.toList.idxOf? moduleName
      | throwError "missing owner module {moduleName}"
    let moduleData := env.header.moduleData[moduleIndex]!
    let names := (moduleData.constNames ++ moduleData.extraConstNames).toList.eraseDups
    let mut safe := 0
    let mut theorems := 0
    let mut privateEntries := 0
    let mut compilerOnly := 0
    let mut runtime := 0
    let mut chosen := 0
    for declarationName in names do
      let some info := env.checked.get.find? declarationName | do
        unless moduleData.extraConstNames.contains declarationName do
          throwError "unavailable kernel declaration {declarationName}"
        compilerOnly := compilerOnly + 1
        logInfo m!"COMPILER_ONLY {declarationName}; owner {moduleName}; checked term absent; excluded from mathematical declaration counts"
        continue
      if info.isUnsafe || info.isPartial then
        let some safeOrigin := Mettapedia.Logic.KernelFoundationManifest.runtimeCounterpart? env declarationName
          | throwError "runtime counterpart does not match exact owner, type and universe {declarationName}"
        unless runtimeEndpoints.contains (declarationName, safeOrigin) do
          throwError "unqualified runtime implementation {declarationName}"
        let some origin := env.checked.get.find? safeOrigin
          | throwError "missing safe runtime origin {safeOrigin}"
        if origin.isUnsafe || origin.isPartial then
          throwError "runtime origin is not kernel-safe {safeOrigin}"
        let originDependencies ← liftCoreM <| collectAxioms safeOrigin
        for dependency in originDependencies do
          unless allowed.contains dependency ||
              (dependency == ``Classical.choice && classicalEndpoints.contains safeOrigin) do
            throwError "unpermitted runtime origin dependency {safeOrigin}: {dependency}"
        let runtimeDependencies ← liftCoreM <| collectAxioms declarationName
        for dependency in runtimeDependencies do
          unless allowed.contains dependency ||
              (dependency == ``Classical.choice && classicalEndpoints.contains safeOrigin) do
            throwError "unpermitted runtime implementation dependency {declarationName}: {dependency}"
        observedRuntime := observedRuntime.push (declarationName, safeOrigin)
        runtime := runtime + 1
        logInfo m!"RUNTIME {declarationName}; safe structural origin {safeOrigin}; origin dependencies {originDependencies.toList}; runtime dependencies {runtimeDependencies.toList}; no theorem credit"
        continue
      if info matches .axiomInfo _ then throwError "owned axiom {declarationName}"
      let dependencies ← liftCoreM <| collectAxioms declarationName
      for dependency in dependencies do
        unless allowed.contains dependency ||
            (dependency == ``Classical.choice && classicalEndpoints.contains declarationName) do
          throwError "unpermitted transitive axiom {declarationName}: {dependency}"
      if dependencies.contains ``Classical.choice then
        observedClassical := observedClassical.push declarationName
        chosen := chosen + 1
      safe := safe + 1
      if info matches .thmInfo _ then theorems := theorems + 1
      if declarationName.toString.startsWith "_private." then privateEntries := privateEntries + 1
      logInfo m!"AUDIT {declarationName}; kind {Mettapedia.Logic.KernelFoundationManifest.declarationKind info}; private {declarationName.toString.startsWith "_private."}; dependencies {dependencies.toList}"
    unless safe > 0 do throwError "empty owner module {moduleName}"
    totalSafe := totalSafe + safe
    totalTheorems := totalTheorems + theorems
    totalPrivate := totalPrivate + privateEntries
    totalCompiler := totalCompiler + compilerOnly
    logInfo m!"MODULE {moduleName}; SAFE {safe}; THEOREMS {theorems}; PRIVATE {privateEntries}; RUNTIME {runtime}; COMPILER_ONLY {compilerOnly}; CHOICE {chosen}; CHOICE_FREE {safe-chosen}"
  for endpoint in classicalEndpoints do
    unless observedClassical.contains endpoint do throwError "stale Choice endpoint {endpoint}"
  for endpoint in runtimeEndpoints do
    unless observedRuntime.contains endpoint do throwError "stale runtime endpoint {endpoint}"
  unless modules.size == 46 && totalSafe == 2574 && totalTheorems == 1324 &&
      totalPrivate == 228 && totalCompiler == 1661 && observedRuntime.size == 15 &&
      observedClassical.size == 771 do
    throwError "owned declaration inventory changed"
  logInfo m!"PASS SAFE {totalSafe}; THEOREMS {totalTheorems}; PRIVATE {totalPrivate}; RUNTIME {observedRuntime.size}; COMPILER_ONLY {totalCompiler}; CHOICE {observedClassical.size}; CHOICE_FREE {totalSafe-observedClassical.size}; NO OWNED AXIOMS OR ADMISSIONS"
