import Mettapedia.Languages.MeTTa.Prime.GSLTILTypedEvidenceRoutePolicyComposition
import Mettapedia.GSLT.LanguageDef.NIKPolicyFamilyAdmission

/-!
# Provenance-retaining reached histories for typed evidence routes

`ReachedHistory` is the propositionally certified image of a route on one
history fibre.  That is the right state space for asking whether a suffix can
answer a declared policy on every state the prefix may reach.  Its membership
proof is nevertheless in `Prop`: it does not retain which source history
produced a reached target history.

Exact replay, occurrence-sensitive receipts, and provenance cache keys need a
stronger carrier.  `ProvenancedReachedHistory` retains both endpoint histories
as data together with the route equation.  Forgetting the source endpoint
lands in `ReachedHistory`.  The forgetful map is injective exactly when the
route reflects complete source histories; a checked collapsing route proves
that policy-image adequacy does not imply provenance adequacy.

Provenance transports constructionally through route composition and is
coherent under reassociation.  Thus NIK may use the smaller propositional
image for a policy-relative native realization while requiring the stronger
carrier for replay or provenance-sensitive caching.
-/

set_option autoImplicit false

namespace Mettapedia.Languages.MeTTa.Prime.GSLTILTypedEvidenceRouteProvenance

open Mettapedia.GSLT.Core
open Mettapedia.GSLT.LanguageDef
open Mettapedia.GSLT.LanguageDef.GSLTIL.EvidenceWorlds
open Mettapedia.GSLT.LanguageDef.GSLTIL.TypedEvidenceRoutes
open Mettapedia.GSLT.LanguageDef.GSLTIL.TypedEvidenceRoutes.TypedEvidenceRoute
open Mettapedia.GSLT.LanguageDef.NIKPolicyFamilyAdmission
open Mettapedia.GSLT.LanguageDef.NIKRouteAdmission
open Mettapedia.Languages.MeTTa.Prime.GSLTILTypedEvidenceRoutePolicySelection
open Mettapedia.Languages.MeTTa.Prime.GSLTILTypedEvidenceRoutePolicyComposition
open Mettapedia.Languages.MeTTa.Prime.GSLTILTypedEvidenceRoutePolicyComposition.RoutePolicyRealization

variable {sourcePresentation middlePresentation targetPresentation
    lastPresentation : ValidatedLanguageDef}
variable {source : EvidenceProfileOver sourcePresentation}
  {middle : EvidenceProfileOver middlePresentation}
  {target : EvidenceProfileOver targetPresentation}
  {last : EvidenceProfileOver lastPresentation}
variable {command : source.profile.Command}

/-- A reached target history together with the source history which produced
it.  The source and target endpoints are runtime data; `mapsTo` checks their
relationship. -/
structure ProvenancedReachedHistory
    (route : TypedEvidenceRoute source target)
    (command : source.profile.Command) where
  sourceHistory : SourceHistory source command
  targetHistory : SourceHistory target (route.mapCommand command)
  mapsTo : (route.atCommand command).mapHistory sourceHistory = targetHistory

namespace ProvenancedReachedHistory

/-- Canonical provenance generated by running a route on one source history. -/
def ofSource
    (route : TypedEvidenceRoute source target)
    (command : source.profile.Command)
    (history : SourceHistory source command) :
    ProvenancedReachedHistory route command where
  sourceHistory := history
  targetHistory := (route.atCommand command).mapHistory history
  mapsTo := rfl

@[simp] theorem ofSource_sourceHistory
    (route : TypedEvidenceRoute source target)
    (command : source.profile.Command)
    (history : SourceHistory source command) :
    (ofSource route command history).sourceHistory = history :=
  rfl

@[simp] theorem ofSource_targetHistory
    (route : TypedEvidenceRoute source target)
    (command : source.profile.Command)
    (history : SourceHistory source command) :
    (ofSource route command history).targetHistory =
      (route.atCommand command).mapHistory history :=
  rfl

/-- Provenance records are extensionally determined by their retained source
history; the target is checked to be its route image. -/
@[ext] theorem ext
    {route : TypedEvidenceRoute source target}
    {command : source.profile.Command}
    {first second : ProvenancedReachedHistory route command}
    (sourceEqual : first.sourceHistory = second.sourceHistory) :
    first = second := by
  cases first with
  | mk firstSource firstTarget firstMaps =>
      cases second with
      | mk secondSource secondTarget secondMaps =>
          dsimp at sourceEqual
          cases sourceEqual
          have targetEqual : firstTarget = secondTarget :=
            firstMaps.symm.trans secondMaps
          cases targetEqual
          rfl

/-- The provenance carrier retains exactly a source history plus its computed
route image; no source occurrence is quotiented away. -/
def equivSource
    (route : TypedEvidenceRoute source target)
    (command : source.profile.Command) :
    ProvenancedReachedHistory route command ≃ SourceHistory source command where
  toFun := sourceHistory
  invFun := ofSource route command
  left_inv := fun _provenance => ext rfl
  right_inv := fun _history => rfl

/-- Forget the source endpoint while retaining a propositionally certified
member of the route image. -/
def toReached
    {route : TypedEvidenceRoute source target}
    {command : source.profile.Command}
    (provenance : ProvenancedReachedHistory route command) :
    ReachedHistory route command :=
  ⟨provenance.targetHistory,
    ⟨provenance.sourceHistory, provenance.mapsTo⟩⟩

@[simp] theorem toReached_value
    {route : TypedEvidenceRoute source target}
    {command : source.profile.Command}
    (provenance : ProvenancedReachedHistory route command) :
    provenance.toReached.1 = provenance.targetHistory :=
  rfl

/-- Every propositionally reached history has some provenance record.  This
is a proposition, not an executable section which reconstructs forgotten
source data from a target key. -/
theorem toReached_surjective
    (route : TypedEvidenceRoute source target)
    (command : source.profile.Command) :
    Function.Surjective
      (toReached : ProvenancedReachedHistory route command →
        ReachedHistory route command) := by
  rintro ⟨targetHistory, sourceHistory, mapsTo⟩
  exact ⟨⟨sourceHistory, targetHistory, mapsTo⟩, rfl⟩

/-- Exact boundary: forgetting source provenance is injective exactly when
the route map itself reflects complete source histories. -/
theorem toReached_injective_iff_mapHistory_injective
    (route : TypedEvidenceRoute source target)
    (command : source.profile.Command) :
    Function.Injective
        (toReached : ProvenancedReachedHistory route command →
          ReachedHistory route command) ↔
      Function.Injective (route.atCommand command).mapHistory := by
  constructor
  · intro forgetInjective firstSource secondSource mappedEqual
    have provenanceEqual :
        toReached (ofSource route command firstSource) =
          toReached (ofSource route command secondSource) := by
      apply Subtype.ext
      exact mappedEqual
    exact congrArg sourceHistory (forgetInjective provenanceEqual)
  · intro historyInjective first second reachedEqual
    apply ext
    apply historyInjective
    calc
      (route.atCommand command).mapHistory first.sourceHistory =
          first.targetHistory := first.mapsTo
      _ = second.targetHistory := congrArg Subtype.val reachedEqual
      _ = (route.atCommand command).mapHistory second.sourceHistory :=
        second.mapsTo.symm

/-- World reflection is therefore sufficient for lossless provenance
forgetting on ordered histories. -/
theorem toReached_injective_of_reflectsWorlds
    (route : TypedEvidenceRoute source target)
    (command : source.profile.Command)
    (reflects : (route.atCommand command).ReflectsWorlds) :
    Function.Injective
      (toReached : ProvenancedReachedHistory route command →
        ReachedHistory route command) :=
  (toReached_injective_iff_mapHistory_injective route command).2
    (EvidenceWorldMap.mapHistory_injective (route.atCommand command) reflects)

/-! ## Exact provenance as a distinct policy capability -/

/-- The complete provenance-replay policy returns the retained source
history, not merely its mapped target image. -/
def replayFamily
    (route : TypedEvidenceRoute source target)
    (command : source.profile.Command) :
    PolicyFamily (ProvenancedReachedHistory route command) where
  Policy := Unit
  Result := fun _ => SourceHistory source command
  decide := fun _ provenance => provenance.sourceHistory

/-- Identity has a direct, constructional provenance replay runner. -/
def identityReplayRealization
    (profile : EvidenceProfileOver sourcePresentation)
    (command : profile.profile.Command) :
    (replayFamily (TypedEvidenceRoute.id profile) command).ReadoutRealization
      (toReached :
        ProvenancedReachedHistory (TypedEvidenceRoute.id profile) command →
          ReachedHistory (TypedEvidenceRoute.id profile) command) where
  run := fun _ reached => reached.1
  agrees := by
    intro _policy provenance
    change provenance.targetHistory = provenance.sourceHistory
    have mapsTo := provenance.mapsTo
    rw [atCommand_id_mapHistory] at mapsTo
    exact mapsTo.symm

theorem identity_supports_provenance_replay
    (profile : EvidenceProfileOver sourcePresentation)
    (command : profile.profile.Command) :
    (replayFamily (TypedEvidenceRoute.id profile) command).SupportsReadout
      (toReached :
        ProvenancedReachedHistory (TypedEvidenceRoute.id profile) command →
          ReachedHistory (TypedEvidenceRoute.id profile) command) :=
  ⟨identityReplayRealization profile command⟩

/-- Retain identity's executable provenance runner at one NIK dependency
revision.  The admission stores the runner; activation does not replay a
checker. -/
def identityReplayAdmissionAt
    (profile : EvidenceProfileOver sourcePresentation)
    (command : profile.profile.Command)
    (dependencies : DependencySystem)
    (revision : dependencies.Revision) :
    PolicyFamilyAdmittedAt dependencies revision
      (replayFamily (TypedEvidenceRoute.id profile) command)
      (toReached :
        ProvenancedReachedHistory (TypedEvidenceRoute.id profile) command →
          ReachedHistory (TypedEvidenceRoute.id profile) command) where
  realization := identityReplayRealization profile command

/-- Current activation runs the retained provenance function directly. -/
@[simp] theorem identityReplayAdmissionAt_run
    (profile : EvidenceProfileOver sourcePresentation)
    (command : profile.profile.Command)
    (dependencies : DependencySystem)
    (admittedRevision currentRevision : dependencies.Revision)
    (current : dependencies.SameDependencies admittedRevision currentRevision)
    (provenance :
      ProvenancedReachedHistory (TypedEvidenceRoute.id profile) command) :
    ((identityReplayAdmissionAt profile command dependencies admittedRevision
      ).activate current).runKey () provenance.toReached =
        provenance.sourceHistory := by
  change provenance.targetHistory = provenance.sourceHistory
  have mapsTo := provenance.mapsTo
  rw [atCommand_id_mapHistory] at mapsTo
  exact mapsTo.symm

/-! ## Constructional transport and associativity -/

/-- Extend one provenance record through a suffix while retaining the
original source endpoint. -/
def mapThrough
    {earlier : TypedEvidenceRoute source middle}
    (provenance : ProvenancedReachedHistory earlier command)
    (later : TypedEvidenceRoute middle target) :
    ProvenancedReachedHistory (TypedEvidenceRoute.comp earlier later) command where
  sourceHistory := provenance.sourceHistory
  targetHistory :=
    (later.atCommand (earlier.mapCommand command)).mapHistory
      provenance.targetHistory
  mapsTo := by
    calc
      ((TypedEvidenceRoute.comp earlier later).atCommand command).mapHistory
          provenance.sourceHistory =
        (later.atCommand (earlier.mapCommand command)).mapHistory
          ((earlier.atCommand command).mapHistory provenance.sourceHistory) :=
        atCommand_comp_mapHistory earlier later command provenance.sourceHistory
      _ = (later.atCommand (earlier.mapCommand command)).mapHistory
          provenance.targetHistory :=
        congrArg
          (later.atCommand (earlier.mapCommand command)).mapHistory
          provenance.mapsTo

@[simp] theorem mapThrough_sourceHistory
    {earlier : TypedEvidenceRoute source middle}
    (provenance : ProvenancedReachedHistory earlier command)
    (later : TypedEvidenceRoute middle target) :
    (provenance.mapThrough later).sourceHistory = provenance.sourceHistory :=
  rfl

@[simp] theorem mapThrough_targetHistory
    {earlier : TypedEvidenceRoute source middle}
    (provenance : ProvenancedReachedHistory earlier command)
    (later : TypedEvidenceRoute middle target) :
    (provenance.mapThrough later).targetHistory =
      (later.atCommand (earlier.mapCommand command)).mapHistory
        provenance.targetHistory :=
  rfl

/-- Forgetting after provenance transport agrees with the suffix readout on
the propositionally reached image. -/
@[simp] theorem toReached_mapThrough_value
    {earlier : TypedEvidenceRoute source middle}
    (provenance : ProvenancedReachedHistory earlier command)
    (later : TypedEvidenceRoute middle target) :
    (provenance.mapThrough later).toReached.1 =
      suffixReadoutOnReached earlier later command provenance.toReached :=
  rfl

/-- The two parenthesizations of three typed-route maps agree on complete
histories. -/
theorem comp_assoc_mapHistory
    (first : TypedEvidenceRoute source middle)
    (second : TypedEvidenceRoute middle target)
    (third : TypedEvidenceRoute target last)
    (command : source.profile.Command)
    (history : SourceHistory source command) :
    ((TypedEvidenceRoute.comp
        (TypedEvidenceRoute.comp first second) third).atCommand command).mapHistory
          history =
      ((TypedEvidenceRoute.comp first
        (TypedEvidenceRoute.comp second third)).atCommand command).mapHistory
          history := by
  simp only [atCommand_comp_mapHistory]
  rfl

/-- Canonical reassociation keeps both provenance endpoints and changes only
the route-parenthesization proof. -/
def reassociate
    (first : TypedEvidenceRoute source middle)
    (second : TypedEvidenceRoute middle target)
    (third : TypedEvidenceRoute target last)
    (command : source.profile.Command) :
    ProvenancedReachedHistory
        (TypedEvidenceRoute.comp (TypedEvidenceRoute.comp first second) third)
        command ≃
      ProvenancedReachedHistory
        (TypedEvidenceRoute.comp first (TypedEvidenceRoute.comp second third))
        command where
  toFun := fun provenance =>
    { sourceHistory := provenance.sourceHistory
      targetHistory := provenance.targetHistory
      mapsTo := (comp_assoc_mapHistory first second third command
        provenance.sourceHistory).symm.trans provenance.mapsTo }
  invFun := fun provenance =>
    { sourceHistory := provenance.sourceHistory
      targetHistory := provenance.targetHistory
      mapsTo := (comp_assoc_mapHistory first second third command
        provenance.sourceHistory).trans provenance.mapsTo }
  left_inv := fun _provenance => ext rfl
  right_inv := fun _provenance => ext rfl

/-- Provenance transport is associative up to the canonical route
reassociation, so cache identity does not depend on compilation parentheses. -/
theorem mapThrough_assoc
    (first : TypedEvidenceRoute source middle)
    (second : TypedEvidenceRoute middle target)
    (third : TypedEvidenceRoute target last)
    (command : source.profile.Command)
    (provenance : ProvenancedReachedHistory first command) :
    reassociate first second third command
        ((provenance.mapThrough second).mapThrough third) =
      provenance.mapThrough (TypedEvidenceRoute.comp second third) := by
  apply ext
  rfl

end ProvenancedReachedHistory

/-! ## Lossy-policy versus exact-provenance controls -/

namespace Canary

open ProvenancedReachedHistory
open Mettapedia.Languages.MeTTa.Prime.GSLTILTypedEvidenceWorldPrograms.SignatureEvidenceInterpretation.Canary
open Mettapedia.Languages.MeTTa.Prime.GSLTILTypedEvidenceWorldNIKSelection.Canary
open Mettapedia.Languages.MeTTa.Prime.GSLTILTypedEvidenceRoutePolicySelection.Canary

abbrev CollapseProvenance :=
  ProvenancedReachedHistory collapseRoute ()

def firstCollapseProvenance : CollapseProvenance :=
  ofSource collapseRoute () [firstWorld]

def secondCollapseProvenance : CollapseProvenance :=
  ofSource collapseRoute () [secondWorld]

/-- The two source proof histories remain distinct runtime provenance. -/
theorem collapse_provenances_distinct :
    firstCollapseProvenance ≠ secondCollapseProvenance := by
  intro equal
  exact sourceSingletonHistories_distinct
    (congrArg sourceHistory equal)

/-- Their propositionally reached target keys are nevertheless equal. -/
theorem collapse_forgets_provenance :
    firstCollapseProvenance.toReached =
      secondCollapseProvenance.toReached := by
  apply Subtype.ext
  rfl

/-- Hence the propositionally certified reached image is not an exact replay
or provenance cache key for this sound forward route. -/
theorem collapse_toReached_not_injective :
    ¬ Function.Injective
      (toReached : CollapseProvenance → ReachedHistory collapseRoute ()) := by
  intro injective
  exact collapse_provenances_distinct
    (injective collapse_forgets_provenance)

/-- Complete source-provenance replay is correctly refused from the collapsed
reached key. -/
theorem collapse_refuses_provenance_replay :
    ¬ (replayFamily collapseRoute ()).SupportsReadout
      (toReached : CollapseProvenance → ReachedHistory collapseRoute ()) := by
  apply (replayFamily collapseRoute ()).not_supportsReadout_of_policy_collision
    (toReached : CollapseProvenance → ReachedHistory collapseRoute ())
    collapse_forgets_provenance ()
  exact sourceSingletonHistories_distinct

/-- The refusal reaches NIK's revision-indexed admission boundary: no
dependency revision can turn the collapsed reached key into an exact
provenance capability. -/
theorem collapse_has_no_provenance_admission
    (dependencies : DependencySystem)
    (revision : dependencies.Revision) :
    ¬ Nonempty
      (PolicyFamilyAdmittedAt dependencies revision
        (replayFamily collapseRoute ())
        (toReached : CollapseProvenance → ReachedHistory collapseRoute ())) := by
  rintro ⟨admission⟩
  exact collapse_refuses_provenance_replay ⟨admission.realization⟩

/-- The same route remains useful for the length policy on its propositional
image.  Policy adequacy and provenance adequacy are distinct capabilities. -/
theorem policy_image_support_does_not_mint_provenance_replay :
    SupportsSourcePolicies collapseRoute () lengthFamily ∧
      ¬ (replayFamily collapseRoute ()).SupportsReadout
        (toReached : CollapseProvenance → ReachedHistory collapseRoute ()) :=
  ⟨collapse_supports_length, collapse_refuses_provenance_replay⟩

end Canary

#print axioms ProvenancedReachedHistory.equivSource
#print axioms ProvenancedReachedHistory.toReached_surjective
#print axioms ProvenancedReachedHistory.toReached_injective_iff_mapHistory_injective
#print axioms ProvenancedReachedHistory.toReached_injective_of_reflectsWorlds
#print axioms ProvenancedReachedHistory.identity_supports_provenance_replay
#print axioms ProvenancedReachedHistory.identityReplayAdmissionAt_run
#print axioms ProvenancedReachedHistory.mapThrough
#print axioms ProvenancedReachedHistory.comp_assoc_mapHistory
#print axioms ProvenancedReachedHistory.reassociate
#print axioms ProvenancedReachedHistory.mapThrough_assoc
#print axioms Canary.collapse_provenances_distinct
#print axioms Canary.collapse_forgets_provenance
#print axioms Canary.collapse_toReached_not_injective
#print axioms Canary.collapse_refuses_provenance_replay
#print axioms Canary.collapse_has_no_provenance_admission
#print axioms Canary.policy_image_support_does_not_mint_provenance_replay

end Mettapedia.Languages.MeTTa.Prime.GSLTILTypedEvidenceRouteProvenance
