import Mathlib.CategoryTheory.PathCategory.Basic
import Mettapedia.Languages.MeTTa.Prime.FiniteLanguageOperationSignature
import Mettapedia.Languages.MeTTa.Prime.InternalDataTransport
import Mettapedia.Languages.MeTTa.Prime.IndexedLanguageChange
import Mettapedia.Languages.MeTTa.Pure.Intrinsic.DeclarationSpec

/-!
# Prime syntax for the current language-operation fragment

The semantic Data action already accepts an arbitrary structural language
route.  This module supplies the converse, syntax-first direction for the
current selected Zero/Prime region:

* primitive authored routes form a quiver;
* Mathlib's path category is the freely composed operation syntax;
* interpretation into the current GSLT-IL stage category is fully faithful;
* the same paths are encoded by declaration-aware, typed `PureTm` terms; and
* executing an encoded route uses the existing internal Data transport.

The syntax is specified without referring to the semantic action.  In
particular, there is no primitive reverse route.  Full faithfulness is proved
for the selected fragment rather than postulated by defining the fragment as
the image of the semantic map.
-/

namespace Mettapedia.Languages.MeTTa.Prime.LanguageOperationSyntax

open CategoryTheory
open scoped CategoryTheory
open Mettapedia.GSLT
open Mettapedia.GSLT.IndexedOperational
open Mettapedia.Languages.MeTTa.StagedReflective
open Mettapedia.Languages.MeTTa.Prime.DataFibration
open Mettapedia.Languages.MeTTa.Prime.DataFibration.ValidatedLanguageData
open Mettapedia.Languages.MeTTa.Prime.IndexedLanguageChange
open Mettapedia.Languages.MeTTa.Prime.InternalDataTransport
open Mettapedia.Languages.MeTTa.Pure.Intrinsic.Syntax
open Mettapedia.Languages.MeTTa.Pure.Intrinsic.Context
open Mettapedia.Languages.MeTTa.Pure.Intrinsic.DeclarationEnv
open Mettapedia.Languages.MeTTa.Pure.Intrinsic.DeclarationSemantics
open Mettapedia.Languages.MeTTa.Pure.Intrinsic.DeclarationSpec
open Mettapedia.Languages.MeTTa.Pure.Intrinsic.Renaming
open Mettapedia.Languages.MeTTa.Pure.Intrinsic.Substitution

/-! ## Free syntax generated by the proper current route -/

abbrev Language := CurrentLanguageHandle

def languageTypeName : DeclName := `Prime.Language
def routeTypeName : DeclName := `Prime.Language.Route
def zeroName : DeclName := `Prime.Language.zero
def primeName : DeclName := `Prime.Language.prime
def identityName : DeclName := `Prime.Language.Route.id
def composeName : DeclName := `Prime.Language.Route.compose
def promoteName : DeclName := `Prime.Language.Route.promote

def languageIndex : Fin 2 ≃ Language where
  toFun index := if index = 0 then .zero else .prime
  invFun
    | .zero => 0
    | .prime => 1
  left_inv index := by
    fin_cases index <;> rfl
  right_inv language := by
    cases language <;> rfl

def languageNameEmbedding : Language ↪ DeclName where
  toFun
    | .zero => zeroName
    | .prime => primeName
  inj' := by
    intro first second equal
    cases first <;> cases second <;> simp_all [zeroName, primeName]

def routeNameEmbedding : Fin 1 ↪ DeclName where
  toFun _ := promoteName
  inj' := by
    intro first second _
    exact Subsingleton.elim first second

/-- The current authored package as an instance of the generic finite
language-operation presentation. -/
abbrev currentOperationSignature :
    Mettapedia.Languages.MeTTa.Prime.FiniteLanguageOperationSignature.Signature where
  Language := Language
  languageCount := 2
  routeCount := 1
  names :=
    { languageType := languageTypeName
      routeType := routeTypeName
      identity := identityName
      compose := composeName }
  languageIndex := languageIndex
  languageName := languageNameEmbedding
  routeName := routeNameEmbedding
  source := fun _ => .zero
  target := fun _ => .prime
  presentation := currentLanguagePresentation
  routeMorphism := fun _ =>
    Mettapedia.Languages.MeTTa.Prime.LanguageDef.currentZeroToPrimePresentation
  declaredNamesNodup := by decide

abbrev Generator := currentOperationSignature.Generator

instance currentLanguageOperationQuiver : Quiver Language :=
  currentOperationSignature.operationQuiver

/-- Independently generated, intrinsically endpoint-indexed route syntax. -/
abbrev Program := currentOperationSignature.Program

abbrev identityProgram (language : Language) : Program language language :=
  currentOperationSignature.identityProgram language

abbrev promoteProgram : Program .zero .prime :=
  currentOperationSignature.namedProgram 0

/-- A numerical rank used only to establish the normal forms of the current
acyclic syntax. -/
def rank : Language → Nat
  | .zero => 0
  | .prime => 1

theorem generator_source_eq {source target : Language}
    (generator : Generator source target) : source = .zero := by
  exact match generator with
    | .named _ => rfl

theorem generator_target_eq {source target : Language}
    (generator : Generator source target) : target = .prime := by
  exact match generator with
    | .named _ => rfl

theorem generator_eq_promote (generator : Generator .zero .prime) :
    generator = .named 0 := by
  exact match generator with
    | .named route => by
        have routeEq : route = 0 := Subsingleton.elim _ _
        subst route
        rfl

@[simp]
theorem generator_rank {source target : Language}
    (generator : Generator source target) :
    rank target = rank source + 1 := by
  rw [generator_source_eq generator, generator_target_eq generator]
  rfl

theorem program_rank {source target : Language}
    (program : Program source target) :
    rank target = rank source + program.length := by
  induction program with
  | nil => simp
  | cons prior generator inductionHypothesis =>
      rw [generator_rank generator, inductionHypothesis]
      simp only [Quiver.Path.length_cons]
      omega

theorem zero_loop_eq_identity (program : Program .zero .zero) :
    program = identityProgram .zero := by
  apply Quiver.Path.eq_nil_of_length_zero
  have ranks := program_rank program
  simp [rank] at ranks
  exact ranks.symm

theorem prime_loop_eq_identity (program : Program .prime .prime) :
    program = identityProgram .prime := by
  apply Quiver.Path.eq_nil_of_length_zero
  have ranks := program_rank program
  simp [rank] at ranks
  exact ranks

theorem zero_prime_eq_promote (program : Program .zero .prime) :
    program = promoteProgram := by
  have ranks := program_rank program
  have lengthOne : program.length = 1 := by
    simpa [rank] using ranks.symm
  obtain ⟨middle, generator, suffix, suffixLength, decomposition⟩ :=
    Quiver.Path.eq_toPath_comp_of_length_eq_succ program lengthOne
  have middleEq : middle = .prime := generator_target_eq generator
  subst middle
  have generatorEq : generator = .named 0 := generator_eq_promote generator
  subst generator
  have suffixNil : suffix = Quiver.Path.nil :=
    Quiver.Path.eq_nil_of_length_zero suffix suffixLength
  subst suffixNil
  change program = Quiver.Hom.toPath
    (@Mettapedia.Languages.MeTTa.Prime.FiniteLanguageOperationSignature.Signature.Generator.named
      currentOperationSignature 0)
  exact decomposition

theorem no_prime_zero_program : IsEmpty (Program .prime .zero) := by
  constructor
  intro program
  have ranks := program_rank program
  simp [rank] at ranks
  omega

/-! ## Exact interpretation into the selected GSLT-IL operation category -/

def operationStage : Language → Stage
  | .zero => .zero
  | .prime => .prime

def interpretGenerator {source target : Language} :
    Generator source target →
      (operationStage source ⟶ operationStage target)
  | .named route => by
      have routeEq : route = 0 := Subsingleton.elim _ _
      subst route
      exact StageHom.promote

def generatorInterpretation : Language ⥤q Stage where
  obj := operationStage
  map := interpretGenerator

/-- Interpret freely composed Prime operation syntax as GSLT-IL routes. -/
def gsltInterpretation :
    CategoryTheory.Functor (CategoryTheory.Paths Language) Stage :=
  CategoryTheory.Paths.lift generatorInterpretation

/-- Reify every selected GSLT-IL operation back into the independent path
syntax. -/
def reifyGSLT {source target : Language} :
    (operationStage source ⟶ operationStage target) → Program source target := by
  cases source <;> cases target
  · intro _
    exact identityProgram .zero
  · intro _
    exact promoteProgram
  · intro route
    cases route
  · intro _
    exact identityProgram .prime

@[simp]
theorem reify_map {source target : Language}
    (program : Program source target) :
    reifyGSLT (gsltInterpretation.map program) = program := by
  cases source <;> cases target
  · exact (zero_loop_eq_identity program).symm
  · exact (zero_prime_eq_promote program).symm
  · exact (no_prime_zero_program.false program).elim
  · exact (prime_loop_eq_identity program).symm

@[simp]
theorem map_reify {source target : Language}
    (route : operationStage source ⟶ operationStage target) :
    gsltInterpretation.map (reifyGSLT route) = route := by
  cases source <;> cases target <;> cases route <;> rfl

/-- The current Prime operation syntax is neither weaker nor more permissive
than the selected GSLT-IL operation category. -/
def gsltInterpretationFullyFaithful : gsltInterpretation.FullyFaithful where
  preimage := reifyGSLT
  map_preimage := map_reify
  preimage_map := reify_map

theorem no_reverse_gslt_operation_has_syntax :
    IsEmpty (Program .prime .zero) :=
  no_prime_zero_program

/-- Interpreting a Prime route yields an actual step of the GSLT-IL indexed
command calculus, not merely an arrow in an unrelated category. -/
def applyProgramStep
    (model : Mettapedia.Languages.MeTTa.Prime.Language.QueryFirstModel)
    {source target : Language} (program : Program source target)
    (state : SemanticTerm
      ((diagram model).obj (operationStage source)).theory) :
    Command.Step (diagram model)
      (.via (gsltInterpretation.map program) state)
      (.at (operationStage target)
        (transportTerm (diagram model)
          (gsltInterpretation.map program) state)) :=
  .applyVia (gsltInterpretation.map program) state

/-! ## Structural interpretation and the existing Data action -/

/-- The same syntax interpreted in the actual category of validated authored
language definitions. -/
def structuralInterpretation :
    CategoryTheory.Functor (CategoryTheory.Paths Language)
      Mettapedia.GSLT.LanguageDef.ValidatedLanguageDef :=
  currentOperationSignature.structuralInterpretation

/-- Execute a syntactic language operation through the already existing
Prime-internal Data transport. -/
def runProgram {source target : Language}
    (program : Program source target)
    (value : FibreTranslation.AllData
      (fibre (currentLanguagePresentation source))) :
    FibreTranslation.AllData (fibre (currentLanguagePresentation target)) :=
  internalTransport PUnit.unit
    (currentLanguagePresentation source)
    (currentLanguagePresentation target)
    (structuralInterpretation.map program) value

@[simp]
theorem run_identity (language : Language)
    (value : FibreTranslation.AllData
      (fibre (currentLanguagePresentation language))) :
    runProgram (identityProgram language) value = value := by
  change internalTransport PUnit.unit
    (currentLanguagePresentation language)
    (currentLanguagePresentation language)
    (CategoryTheory.CategoryStruct.id (currentLanguagePresentation language))
    value = value
  exact internalTransport_id (currentLanguagePresentation language) value

@[simp]
theorem run_comp {first middle last : Language}
    (earlier : Program first middle) (later : Program middle last)
    (value : FibreTranslation.AllData
      (fibre (currentLanguagePresentation first))) :
    runProgram (Quiver.Path.comp earlier later) value =
      runProgram later (runProgram earlier value) := by
  unfold runProgram
  have mapComp :
      structuralInterpretation.map (Quiver.Path.comp earlier later) =
        CategoryTheory.CategoryStruct.comp
          (structuralInterpretation.map earlier)
          (structuralInterpretation.map later) :=
    structuralInterpretation.map_comp earlier later
  rw [mapComp]
  exact internalTransport_comp
    (structuralInterpretation.map earlier)
    (structuralInterpretation.map later) value

/-! ## Declaration-aware Pure syntax -/

abbrev languageType : PureTm n := currentOperationSignature.languageType

abbrev languageTerm (language : Language) : PureTm n :=
  currentOperationSignature.languageTerm language

abbrev routeType (source target : PureTm n) : PureTm n :=
  currentOperationSignature.routeType source target

abbrev routeTypeFormer : PureTm 0 :=
  currentOperationSignature.routeTypeFormer

abbrev identityType : PureTm 0 :=
  currentOperationSignature.identityType

abbrev composeType : PureTm 0 :=
  currentOperationSignature.composeType

abbrev operationSpecs : List DeclSpec :=
  currentOperationSignature.operationSpecs

abbrev operationDeclEnv : DeclEnv :=
  currentOperationSignature.operationDeclEnv

abbrev identityTerm (language : Language) : PureTm 0 :=
  currentOperationSignature.identityTerm language

abbrev composeTerm (first middle last : Language)
    (earlier later : PureTm 0) : PureTm 0 :=
  currentOperationSignature.composeTerm first middle last earlier later

/-- Compile independent route paths into ordinary closed Pure syntax. -/
abbrev encodeProgram {source target : Language}
    (program : Program source target) : PureTm 0 :=
  currentOperationSignature.encodeProgram program

/-! ## Executable recognition of the Prime fragment -/

/-- A closed operation whose endpoints have been recovered from Prime syntax. -/
abbrev DecodedProgram := currentOperationSignature.DecodedProgram

/-- Transport a path across proved endpoint equalities. -/
abbrev reindexProgram {source target newSource newTarget : Language}
    (sourceEq : source = newSource) (targetEq : target = newTarget) :
    Program source target → Program newSource newTarget :=
  currentOperationSignature.reindexProgram sourceEq targetEq

/-- Compose decoded routes only when their recovered endpoints agree with the
three endpoint arguments written in the Prime term.  Thus endpoint annotations
are checked data, not decoration. -/
abbrev composeDecoded? (first middle last : Language)
    (earlier later : DecodedProgram) : Option DecodedProgram :=
  currentOperationSignature.composeDecoded? first middle last earlier later

/-- Recover a language endpoint from the two current closed Prime constants. -/
abbrev decodeLanguageTerm? : PureTm 0 → Option Language :=
  currentOperationSignature.decodeLanguageTerm?

@[simp]
theorem decodeLanguageTerm_languageTerm (language : Language) :
    decodeLanguageTerm? (languageTerm language) = some language := by
  exact currentOperationSignature.decodeLanguageTerm_languageTerm language

theorem decodeLanguageTerm_eq_some {term : PureTm 0} {language : Language}
    (accepted : decodeLanguageTerm? term = some language) :
    term = languageTerm language := by
  exact currentOperationSignature.decodeLanguageTerm_eq_some accepted

/-- Executable, syntax-directed recognizer for the current Prime operation
fragment.  It mentions only Prime constants and their term shape; it does not
consult the GSLT interpretation. -/
abbrev decodeProgram? : PureTm 0 → Option DecodedProgram :=
  currentOperationSignature.decodeProgram?

@[simp]
theorem composeDecoded_programs {first middle last : Language}
    (earlier : Program first middle) (later : Program middle last) :
    composeDecoded? first middle last
        { source := first, target := middle, program := earlier }
        { source := middle, target := last, program := later } =
      some
        { source := first
          target := last
          program := Quiver.Path.comp earlier later } := by
  exact currentOperationSignature.composeDecoded_programs earlier later

/-- Every independently generated route has a closed Prime spelling which the
syntax-directed recognizer recovers exactly. -/
@[simp]
theorem decodeProgram_encodeProgram {source target : Language}
    (program : Program source target) :
    decodeProgram? (encodeProgram program) =
      some { source := source, target := target, program := program } := by
  exact currentOperationSignature.decodeProgram_encodeProgram program

/-- Positive executable witness: promotion is recognized with exact
endpoints. -/
example : decodeProgram? (encodeProgram promoteProgram) =
    some
      { source := .zero
        target := .prime
        program := promoteProgram } := by
  exact decodeProgram_encodeProgram promoteProgram

/-- Negative executable witness: a route type is not itself a route program. -/
example : decodeProgram? (.const routeTypeName) = none := by
  simp [Mettapedia.Languages.MeTTa.Prime.FiniteLanguageOperationSignature.Signature.decodeProgram?,
    Mettapedia.Languages.MeTTa.Prime.FiniteLanguageOperationSignature.Signature.decodeRouteName?,
    Mettapedia.Languages.MeTTa.Prime.FiniteLanguageOperationSignature.Signature.decodeIndex?,
    routeNameEmbedding, routeTypeName, promoteName]

/-- Negative executable witness: a composition whose written middle endpoint
disagrees with its first subroute is rejected. -/
example : decodeProgram?
    (composeTerm .zero .zero .prime
      (encodeProgram promoteProgram) (encodeProgram promoteProgram)) = none := by
  exact currentOperationSignature.decodeProgram_compose_rejects_earlier_target
    promoteProgram promoteProgram (by decide)

@[simp] theorem typeOf_languageType :
    typeOf? operationDeclEnv languageTypeName = some .u0 := by decide

@[simp] theorem typeOf_routeType :
    typeOf? operationDeclEnv routeTypeName = some routeTypeFormer := by decide

@[simp] theorem typeOf_zero :
    typeOf? operationDeclEnv zeroName = some languageType := by decide

@[simp] theorem typeOf_prime :
    typeOf? operationDeclEnv primeName = some languageType := by decide

@[simp] theorem typeOf_identity :
    typeOf? operationDeclEnv identityName = some identityType := by decide

@[simp] theorem typeOf_compose :
    typeOf? operationDeclEnv composeName = some composeType := by decide

@[simp] theorem typeOf_promote :
    typeOf? operationDeclEnv promoteName =
      some (routeType (languageTerm .zero) (languageTerm .prime)) := by decide

theorem operationSpecs_signatureWellFormed :
    SignatureWellFormed operationSpecs :=
  currentOperationSignature.operationSpecs_signatureWellFormed

theorem hasType_languageTerm (language : Language) :
    HasTypeDecl operationDeclEnv .nil (languageTerm language) languageType :=
  currentOperationSignature.hasType_languageTerm language

theorem hasType_identityTerm (language : Language) :
    HasTypeDecl operationDeclEnv .nil (identityTerm language)
      (routeType (languageTerm language) (languageTerm language)) :=
  currentOperationSignature.hasType_identityTerm language

theorem hasType_promote :
    HasTypeDecl operationDeclEnv .nil (.const promoteName)
      (routeType (languageTerm .zero) (languageTerm .prime)) := by
  change HasTypeDecl currentOperationSignature.operationDeclEnv .nil
    (currentOperationSignature.routeTerm (0 : Fin 1))
    (currentOperationSignature.routeType
      (currentOperationSignature.languageTerm .zero)
      (currentOperationSignature.languageTerm .prime))
  exact currentOperationSignature.hasType_routeTerm (0 : Fin 1)

theorem hasType_composeTerm (first middle last : Language)
    (earlier later : PureTm 0)
    (earlierTyped : HasTypeDecl operationDeclEnv .nil earlier
      (routeType (languageTerm first) (languageTerm middle)))
    (laterTyped : HasTypeDecl operationDeclEnv .nil later
      (routeType (languageTerm middle) (languageTerm last))) :
    HasTypeDecl operationDeclEnv .nil
      (composeTerm first middle last earlier later)
      (routeType (languageTerm first) (languageTerm last)) := by
  exact currentOperationSignature.hasType_composeTerm first middle last
    earlier later earlierTyped laterTyped

/-- Every generated operation program is an independently typechecked closed
Prime term at its exact route type. -/
theorem encodeProgram_typed {source target : Language}
    (program : Program source target) :
    HasTypeDecl operationDeclEnv .nil (encodeProgram program)
      (routeType (languageTerm source) (languageTerm target)) :=
  currentOperationSignature.encodeProgram_typed program

/-- Every term accepted by the independent syntactic recognizer is a
well-typed Prime operation at the endpoints recovered by that recognizer. -/
theorem decodeProgram_typed (term : PureTm 0) (decoded : DecodedProgram)
    (accepted : decodeProgram? term = some decoded) :
    HasTypeDecl operationDeclEnv .nil term
      (routeType (languageTerm decoded.source)
        (languageTerm decoded.target)) :=
  currentOperationSignature.decodeProgram_typed term decoded accepted

/-- The independently definable Prime fragment: closed terms accepted by the
syntax-directed recognizer, paired with the endpoints and path it recovered. -/
abbrev RecognizedOperation := currentOperationSignature.RecognizedOperation

namespace RecognizedOperation

/-- Recognition carries an exact Prime typing derivation. -/
theorem wellTyped (operation : RecognizedOperation) :
    HasTypeDecl operationDeclEnv .nil operation.term
      (routeType (languageTerm operation.decoded.source)
        (languageTerm operation.decoded.target)) :=
  decodeProgram_typed operation.term operation.decoded operation.recognized

/-- The semantic operation represented by a recognized Prime term. -/
def toGSLT (operation : RecognizedOperation) :
    operationStage operation.decoded.source ⟶
      operationStage operation.decoded.target :=
  gsltInterpretation.map operation.decoded.program

/-- A recognized Prime operation acts as an actual GSLT-IL command step. -/
def applyStep (operation : RecognizedOperation)
    (model : Mettapedia.Languages.MeTTa.Prime.Language.QueryFirstModel)
    (state : SemanticTerm
      ((diagram model).obj
        (operationStage operation.decoded.source)).theory) :
    Command.Step (diagram model)
      (.via operation.toGSLT state)
      (.at (operationStage operation.decoded.target)
        (transportTerm (diagram model) operation.toGSLT state)) :=
  .applyVia operation.toGSLT state

end RecognizedOperation

theorem reverse_route_term_is_not_generated
    (term : PureTm 0)
    (generated : ∃ program : Program .prime .zero,
      encodeProgram program = term) : False := by
  obtain ⟨program, _⟩ := generated
  exact no_prime_zero_program.false program

#print axioms gsltInterpretationFullyFaithful
#print axioms decodeProgram_encodeProgram
#print axioms decodeProgram_typed
#print axioms run_comp

end Mettapedia.Languages.MeTTa.Prime.LanguageOperationSyntax
