import Mettapedia.Languages.MeTTa.LeaTTa.Corpus.SelfInterp.Base

open MeTTaIL Mettapedia.Languages.MeTTa.LeaTTa.Corpus.SelfInterp

/- The generator proposes intermediate terms. Each generated equality is
   independently checked by Lean's kernel when its module is built. -/

private partial def renderCategory : Cat → String
  | .idCat name => "(.idCat " ++ reprStr name ++ ")"
  | .listOf category => "(.listOf " ++ renderCategory category ++ ")"
  | .arrow domain codomain => "(.arrow " ++ renderCategory domain ++ " " ++ renderCategory codomain ++ ")"
  | .prod categories => "(.prod [" ++ String.intercalate ", " (categories.map renderCategory) ++ "])"

private def renderLabel : Label → String
  | .id name => "(.id " ++ reprStr name ++ ")"
  | .wild => ".wild"
  | .listE category => "(.listE " ++ renderCategory category ++ ")"
  | .listCons category => "(.listCons " ++ renderCategory category ++ ")"
  | .listOne category => "(.listOne " ++ renderCategory category ++ ")"

private partial def renderTerm : AST → String
  | .sexp label arguments =>
      "(.sexp " ++ renderLabel label ++ " [" ++
        String.intercalate ", " (arguments.map renderTerm) ++ "])"
  | .var path => "(.var (" ++ reprStr path ++ "))"
  | .subst body replacement path => "(.subst " ++ renderTerm body ++ " " ++
      renderTerm replacement ++ " (" ++ reprStr path ++ "))"

private def generate (directory : System.FilePath) (name inputSource expectedSource : String)
    (input : AST) (chunks : Nat) : IO Unit := do
  let mut current := input
  let mut output := "import Mettapedia.Languages.MeTTa.LeaTTa.Corpus.SelfInterp.Base\n\n"
  output := output ++ "/- Generated by scripts/generate_self_interp_checkpoints.lean.\n   Every intermediate reduction is kernel checked. -/\n\n"
  let scope := "Mettapedia.Languages.MeTTa.LeaTTa.Corpus.SelfInterp.Checkpoints." ++ name
  output := output ++ "namespace " ++ scope ++ "\nopen MeTTaIL\n\n"
  output := output ++ "set_option maxRecDepth 50000\nset_option maxHeartbeats 20000000\n\n"
  output := output ++ "private def state0 : AST := " ++ inputSource ++ "\n"
  for index in [:chunks] do
    let next := eval pMI 100 current
    output := output ++ "private def state" ++ toString (index+1) ++ " : AST := " ++ renderTerm next ++ "\n"
    output := output ++ "private theorem step" ++ toString index ++ " : eval pMI 100 state" ++ toString index ++ " = state" ++ toString (index+1) ++ " := by rfl\n\n"
    current := next
  output := output ++ "theorem evaluated : eval pMI " ++ toString (chunks*100) ++ " (" ++ inputSource ++ ") =\n    " ++ expectedSource ++ " := by\n  calc\n"
  for index in [:chunks-1] do
    let remaining := (chunks-index-1)*100
    output := output ++ "    _ = eval pMI " ++ toString remaining ++ " state" ++ toString (index+1) ++ " :=\n"
    output := output ++ "      (eval_add pMI 100 " ++ toString remaining ++ " state" ++ toString index ++ ").trans\n"
    output := output ++ "        (congrArg (eval pMI " ++ toString remaining ++ ") step" ++ toString index ++ ")\n"
  output := output ++ "    _ = state" ++ toString chunks ++ " := step" ++ toString (chunks-1) ++ "\n"
  output := output ++ "    _ = " ++ expectedSource ++ " := by rfl\n\n"
  output := output ++ "theorem normal : IsNormal pMI (" ++ expectedSource ++ ") := by rfl\n\nend " ++ scope ++ "\n"
  IO.FS.createDirAll directory
  IO.FS.writeFile (directory / (name ++ ".lean")) output

def main (args : List String) : IO Unit := do
  let [directory] := args | throw (IO.userError "Usage: lake env lean --run scripts/generate_self_interp_checkpoints.lean OUTPUT_DIRECTORY")
  generate directory "Reverse" "miRun rulesRev (miRev miList012) (fuel 40)"
    "Cons (S (S Z)) (Cons (S Z) (Cons Z Nil))"
    (miRun rulesRev (miRev miList012) (fuel 40)) 15
  generate directory "ReverseInvolution" "miEval rulesRev (miRev (miRev miList012)) (fuel 40)"
    "MIDone miList012"
    (miEval rulesRev (miRev (miRev miList012)) (fuel 40)) 26
