import Mettapedia.Languages.MeTTa.PrimeComparisons
import Mettapedia.Languages.MeTTa.PrimeCandidates.DevelopmentPlan

/-! Readout of the broad candidate-specification inventory. This is not the
higher-order MeTTa integration agenda or its readiness measure. -/

open Mettapedia.Languages.MeTTa
open PrimeCandidates.Specification
open PrimeCandidates.DevelopmentPlan

/-- Source gates are evaluated afresh, not copied from a previous build log.
Their result is reporting data; it never supplies a proof of semantics. -/
def freshSourceGates : IO (List String) := do
  let result ← IO.Process.output {
    cmd := "python3"
    args := #["scripts/check_prime_spec_boundary.py", "--passed-gates"] }
  if result.exitCode != 0 then
    IO.println "Some source/collection checks failed; only individually passing gates are counted below."
    IO.println result.stderr
  let passed := (result.stdout.splitOn "\n").filter (! ·.isEmpty)
  return if structurallyValid obligations then "ledger.structure" :: passed else passed

def reportStudy : IO Unit := do
  let gates ← freshSourceGates
  IO.println "Active objective: integrated higher-order MeTTa mathematics through HOL/HOTG, DTT, OSLF/GSLT-IL and NIK. The metatheory paper states the mathematical scope; working notes are maintained separately."
  IO.println "The following is the broad Prime specification inventory, not a prerequisite checklist or completion percentage for HO experimentation. Unsettled global binding/evaluation defaults do not block a pinned, qualified fragment."
  IO.println s!"Broad specification inventory {version}: {(closedIds gates).length}/{obligations.length} scoped rows closed."
  let theoremRows := obligations.countP fun row =>
    match row.progress with
    | .proved _ => true
    | _ => false
  let mechanicalRows := obligations.countP fun row =>
    match row.progress with
    | .sourceGate id => gates.contains id
    | _ => false
  IO.println s!"Closure breakdown: {theoremRows} theorem-backed rows + {mechanicalRows} fresh mechanical gates."
  IO.println s!"Development direction: {(developmentResolvedIds gates).length}/{obligations.length} rows closed or selected for development; selected but unqualified: {selectedPendingIds gates}."
  IO.println "The development-direction count is not the proof-closure count. Selection never changes a row's acceptance condition or supplies a theorem."
  IO.println "This denominator measures this specification plan, not all future Prime research or runtime readiness."
  for milestone in milestones do
    let (closed, total) := counts gates milestone
    IO.println s!"  {repr milestone}: {closed}/{total} closed ({100 * closed / total}%); {partialCount milestone} partial"
  IO.println s!"Fresh mechanical gate results: {gates}"
  IO.println "Dependency-ready rows of the broad inventory (not the active HO priority order):"
  for row in availableNext gates do
    IO.println s!"  {row.id}: {row.acceptance}"
  IO.println "Remaining broad-inventory rows and their internal predecessors:"
  for row in outstanding gates do
    let unmet := row.dependsOn.filter (!(closedIds gates).contains ·)
    IO.println s!"  {row.id}: waiting on {unmet}"
    match row.progress with
    | .partialEvidence _ gap | .unresolved gap => IO.println s!"    Gap: {gap}"
    | .sourceGate id => IO.println s!"    Gate not passed: {id}"
    | .proved _ => pure ()
  IO.println "Decision evidence and selection records:"
  for decision in decisions do
    let current := study decision
    IO.println s!"  {repr decision}: claims {current.constraints.map (·.id)}; selection {repr current.selection}"
  IO.println s!"Unproved inspected CeTTa correspondences: {repr PrimeComparisons.remainingCorrespondences}"
  IO.println s!"No inspected comparison: {repr PrimeComparisons.decisionsWithoutInspectedComparison}"
  IO.println s!"Experimental draft review: {PrimeCeTTaCurrent.ScopedJudgmentDraft.reviewedProbes.length} probe topics; {PrimeCeTTaCurrent.ScopedJudgmentDraft.recordedRuns.length} recorded runs; {(PrimeCeTTaCurrent.ScopedJudgmentDraft.recordedRuns.map (fun run => run.outputs.length)).sum} literal outputs."
  IO.println s!"Later draft inspection: {PrimeCeTTaCurrent.ScopedJudgmentDraftSecondPass.observations.length} source observations and {PrimeCeTTaCurrent.ScopedJudgmentDraftSecondPass.recordedRuns.length} isolated existing-binary probe with {PrimeCeTTaCurrent.ScopedJudgmentDraftSecondPass.rawRecordRun.outputs.length} literal outputs; no C rebuild or full gate."
  IO.println s!"Original family-only semantic collection: {PrimeCandidates.SharedJudgmentSemanticRequirements.requirements.length} native clauses plus {PrimeCandidates.SharedJudgmentSemanticRequirements.declarationRequirements.length} declaration clauses, indexed by the same assembly/formed-context interpretation/universe/type/service/declaration data."
  for requirement in PrimeCandidates.SharedJudgmentSemanticRequirements.requirements do
    IO.println s!"  {requirement.id}: source references {PrimeCandidates.SharedJudgmentSemanticRequirements.Requirement.references requirement}"
  for requirement in PrimeCandidates.SharedJudgmentSemanticRequirements.declarationRequirements do
    IO.println s!"  {requirement.id}: source references {PrimeCandidates.SharedJudgmentSemanticRequirements.DeclarationRequirement.references requirement}"
  IO.println "These are collected obligations, not proofs of joint qualification or a complete six-family specification. Required declaration instances belong to the caller; a missing entry cannot evade coverage."
  IO.println "Actual native quotient attachment: 28/31 component clauses have proofs on identical data: SEM-ADM-001–007, SEM-TY-001–010, SEM-ID-001–003/006 and SEM-U-001–007. SEM-DECL-002–004 share that interpretation; SEM-DECL-001 requires actual installed instances. See ADM-053–056, ID-038–053 and HOST-096–107 for proof-bearing evidence."
  IO.println "The original required four-face specimen is now qualified on this same quotient interpretation (HO-067–070), including its input and native-surface contracts. This is not an unrestricted future service family."
  IO.println "The old canonical family-only exact attachment remains refuted at SEM-ID-004 in its original model; SEM-ID-005/007 are not separately refuted. The retained-input operation covers every independently admitted native tuple, computes on reflexivity and commutes with every semantic substitution, including all equal transported methods. DEC-ID-20260912 selects scoped identity and optional original-presentation references. Its separate fixed Boolean/J fragment is now qualified by FORK-ID-QUALIFIED-001, without adding global K/UIP or a conversion rule."
  IO.println s!"Retained native profile: {PrimeCandidates.SharedJudgmentRetainedSemanticRequirements.requirements.length}/{PrimeCandidates.SharedJudgmentRetainedSemanticRequirements.requirements.length} semantic clauses jointly proved, with seven source, six original service and four declaration clauses on Controls.commonCandidate (ASM-RETAINED-NATIVE-001). This is a closed component, not closure of the full six-family ASM-005 obligation."
  IO.println "OBS-038–040 narrow inconclusive-result views by actual consumers: status sometimes factors through answers; submitted-work inspection does not. Retained context-indexed payloads support it without selecting a global empty-result policy."
  IO.println "OBS-041–047 connect explicit versioned/live context references to the existing typed backend, with publication stability, pure finite-footprint inspection and a native substitution square. The live-binding control changes the actual output; no default reference mode or mutable-heap semantics is selected."
  IO.println "OBS-048–055 connect scoped reference changes to the existing state/choice/intent program and ground refinement: scope restoration is not rollback, a rejected proposal preserves the old context without becoming a solution, and a captured reference differs from delayed lookup and frozen contents. Explicitly resolved reference-value binding agrees with direct role use as an effect-program law; a surface binding may instead pass the role computation. Neither an eager surface convention nor a C defect follows from that value law."
  IO.println "OBS-056–059 lift relocation into the actual named native service interpreter: exact backend agreement, a source/context substitution square before effect observation, dependent result admission, nonidentity typed substitution and matching/HOL service controls. Origin inspection is preserved while live evaluation changes between executions; missing evaluation does not fall back to origin. Named resolution is at entry, not yet table mutation/re-resolution within execution. No surface convention, asynchronous read policy or new FORK-OBS closure is selected."
  IO.println "OBS-060–066 connect computed ground binding coproducts and their compatible-input completion functor to the Empty laws: conflicts have no common extension, yet identical rejection supports different reporting handlers. Ordinary data differs from no answers; an explicit boundary can observe finite absence while ordinary success sequencing cannot. Values alone cannot restore discarded coverage/faults in the finite outcome model. Ground names are not general term unification or fresh lexical binders. No failure-reporting default or runtime outcome record follows."
  IO.println "HO-071–073 add an actual object-HOL map-fusion proof, symbolic instantiation and higher-order application. A swapped-order candidate fits empty and diagonal samples but is refuted in a model of the full original theory. This is not an implemented general learner or imported Lean guest."
  IO.println "HO-074–076 carry that same induction proof through the actual predicate-family interpretation: arbitrary predicates of fused/unfused results give equivalent refinements preserving the input list. Standard-model arbitrary functions and lists are covered; no predicate decision procedure is assumed. Wrong-order samples cannot supply a uniform fusion section; separately, the equation-only junk model cannot supply induction or map-length sections. This is semantic dependent consumption, not yet native proof inhabitation or HOTG adequacy."
  IO.println "HOST-109–113 connect actual HOL predicates and proofs to dependent semantic families: substitution commutes, quantifiers characterize inhabited sections/sums, and a higher-order intersection proof transports an actual refinement witness. A varying Boolean predicate has an inhabited and an empty fibre. Truth sections do not retain distinct proof strategies. The optional envelope comparison gives semantic code inhabitation, not yet native dependent proof syntax or the full HOTG interpretation."
  IO.println "HOST-114–116 add actual proof substitution, universal identity/composition proof trees and their coherent actions on refinement witnesses. Sections and refinement maps commute with substitution of the proof and its satisfied assumptions. A non-ground lambda predicate retains its free parameter across binders; changing that parameter changes membership. These are laws of the actual Henkin family interpretation, not a full native DTT/HOTG/GSLT-IL triangle."
  IO.println "HOST-117–119 construct a retained-proof compiler for hypotheses, implication and universal quantification. Successful compilation preserves the complete native judgment; mixed object/proof environments commute with substitution and proof application computes by native beta. Quantified transitivity and the application of actual higher-order induction exercise it. Unsupported rules return no term. The decoder extension's full model, conversion boundaries and attachment of the complete equality-based fusion proof remain open."
  IO.println "HOST-120–122 connect actual ZF sets, higher-order HOL predicates and dependent refinements: seven set-theory formulas are validated independently, separated sets commute with substitution, and retained implication proofs induce coherent inclusions. Empty fibres and the absence of an internal universal set are proved in this same model. These claims alone do not supply HOTG UnivOf or a common native dependent interpretation."
  IO.println "HO-077–080 connect directed native List beta/iota execution, generated finite-reachability OSLF observation and the actual HOL induction/congruence proof's output refinements. Native constructor observations are coherent and respect interpreted context substitution. Correct composition is observed and the wrong constructor output is rejected. This does not claim all-execution/effect/cost equivalence, textual LanguageDef adequacy, a common full DTT/HOTG model or native dependent proof inhabitation."
  IO.println "HOST-123–124 give noncollapse results for the decoder extension and compose its typed beta laws with the actual proof compiler. Pi/Sigma remain separate from universe heads, distinct universe levels are not identified, and the compiler's proof-argument substitution has the same complete judgment before and after beta. The expansion used for separation is one-way and untyped, not a semantic model. The stronger exact-decoder conversion and preservation results are in HOST-133."
  IO.println "HOST-125–128 construct inaccessible-rank closed sets and least universe enclosures. Cofinal inaccessibles are an explicit sufficient relative assumption for total UnivOf, not an established existence theorem or selected global theory strength. Four actual HOL universe laws extend the same seven-formula set model; old predicates keep their meanings and new predicates may mention UnivOf. Iterating UnivOf cannot be idempotent. A concrete higher-level least empty-set enclosure requires no cofinal assumption. Exact imported HOTG source adequacy and the common native dependent interpretation remain open."
  IO.println "HOST-129–130 construct actual retained HOL proofs comparing primitive equality with HOL predicate equality. Predicate reflexivity, transitivity and consumption compile to native proof inhabitants; the primitive comparison itself remains unsupported by the compiler and does not identify HOL equality with native Id. A round trip preserves admission but changes the retained proof tree."
  IO.println "HO-081–083 independently formation-type the actual native map, its applications and both fusion endpoints in one native List/HOL declaration environment. Complete paths and the HOL-proof refinement observation compose there. A wrong output is well typed but rejected by the semantic observation. Endpoint typing is not unrestricted mixed-profile subject reduction; abstract HOL sequences are not identified with native List, and the full native fusion proof and HOTG/model composition remain open."
  IO.println "HOST-131 traverses actual retained source-proof substitution and proves that it agrees with native compilation, including universal specialization/beta with the same complete judgment. HOST-132 interprets retained predicate equality through actual separated-set and refinement maps, with substitution coherence and changed-parameter refusal in the same universe model."
  IO.println "HOST-133 constructs complete development and Church-Rosser for exactly the existing two HOL decoder equations, derives Pi/Sigma component conversion and full formation-sensitive subject reduction, with no added completion rules. This is not normalization, a semantic consistency model, or unrestricted preservation after installing other native computation families."
  IO.println "HOST-134–135 give a genuinely alternative logical signature: equality is a typed native predicate expression whose use computes by beta and the unchanged proof decoder. Constructorwise native semantics independently agrees with Henkin equality on admissible environments, with native-substitution coherence and unequal-operand rejection. This is expression semantics, not a model of arbitrary dependent proof terms or a global equality selection."
  IO.println "HOST-136–137 construct actual set-coded dependent products/sums and a seed-relative cumulative universe family under the already explicit cofinal-inaccessible assumption. Graph decoding has both inverse laws, dependent pairs use actual Kuratowski pairs, products/sums lie at maximum input level, and successor universes code their predecessors. One empty fibre kills a product but need not kill the sum. Native term, identity and inductive interpretation still require further construction."
  IO.println "HOST-138–139 construct the alternative constructive-equality compiler and prove source adequacy of its complete represented conclusions. The original retained mapFusionProof now compiles, including its induction application; its five original assumptions remain explicit inputs. The same output proposition has independently constructed native Henkin semantics and source-justified truth. This is not an interpretation of arbitrary native proof inhabitants or a construction of those five native theory witnesses."
  IO.println "HOST-140–141 construct actual set-coded contextual terms with dependent product/pair beta and eta, substitution, and the same contextual Tarski hierarchy. A noninjective substitution and a wrong-result control exercise dependence. This is not yet a model of all native syntax: the earlier entire external HOL set carrier must be represented at a larger ambient universe, rather than treated as an internal universal set."
  IO.println "HOST-142–143 construct that larger carrier code without a cardinal hypothesis: actual membership, powerset, union, separation and replacement commute with decoding, including classification of every larger subset of a lifted set. A same-level code is impossible. Placement in the fixed unbounded target tower separately states its larger-ambient cofinal-inaccessible hypothesis. HOST-144 admits actual mixed List motives and HOL predicates through generic elimination and proof introduction."
  IO.println "HOST-145 proves full formed subject reduction of the exact mixed HOL/native rules and admission at every observed finite endpoint. Pi/Sigma conversion boundaries use a separately sound auxiliary development; no completed roots are installed for execution. An authored-step duplicated-metadata peak joins, split metadata blocks the root, and a nonempty map runs beneath a formed proof binder. Raw execution confluence, normalization and textual LanguageDef adequacy are not claimed."
  IO.println "HOST-146 constructs the actual least-universe operation on the lifted carrier and proves agreement with the original lower-ambient UnivOf, including minimality and non-idempotence. Its larger-ambient global comparison states the extra hypothesis separately."
  IO.println "HO-086 interprets the original retained HOL map-fusion compiler output into actual native List/map and applies all five original theory inputs: induction from the native eliminator and the four map/length equations from computation. The resulting judgment has an empty context; countType supplies a concrete small element carrier without claiming a natural-number interpretation of that declaration. Whole-model soundness and conservativity remain separate."
  IO.println "HOST-147–150 join composed declaration interpretations, actual HOL set/graph syntax semantics, the same set-coded CwF, and retained proof/refinement consumption with substitution. HOST-151 proves a genuine incompatibility of that graph assembly: canonical truth fibres and graph products are equivalent but not strictly equal. HOST-152 constructs weak decoders and first-class contextual proof consumers; HOST-153–155 construct uniform trace products, literal logical decoding beneath arbitrary code-dependent families, and closure in the same actual universe hierarchy. This repairs those decoder components without selecting a global encoding or claiming full native soundness."
  IO.println "HOST-156–157 construct actual set-coded dependent lists and prove their internal universe membership using a separate natural-index seed. Closed V_omega is an actual counterexample to list closure from the earlier finite set-closure conditions alone. HOST-158 and HOST-160 interpret every original HOL term through recursive trace arrows, agree with the same set model and source substitution, and attach the literal proof decoder to actual imp/all source expressions and retained proofs."
  IO.println "HOST-159 interprets the exact original mapFusionProof over actual set-coded lists with all five original theory assumptions independently discharged, then carries arbitrary predicate witnesses through separated-set graph/trace consumers. A wrong-composition HOL sentence is false in the same model. HOST-161 independently constructs trace-coded contextual list elimination, proves computation and substitution, and compares its actual application with the graph eliminator. The compiled-native term's full set interpretation remains to be connected."
  IO.println "HO-088 executes all thirty original canonical binding schemas through the generic recursive rule-data interpreter, exactly realizing arbitrary native weakening and capture-avoiding beta without a substitution callback. HO-089 decomposes the unchanged full native step/derivation into computation and its separately exact universe-level equality query; executing only the computational component is not full step adequacy."
  IO.println "HO-090 joins the binding rules, ten computation roots and fifteen legal native context positions in one flat fifty-five-rule LanguageDef. Closed helper queries have exactly unchanged output lists, including order and multiplicity. Every native computational step and finite derivation is realized. Reverse soundness of arbitrary matcher outputs is not yet included; completeness alone is not operational adequacy."
  IO.println "HO-087 uses the original compiled native fusion proof at arbitrary native f/g/xs and P : List E -> prop, carrying h : Prf(P unfused) to Prf(P fused) in an independently formed context. No source-expression restriction applies to the caller. E remains closed and small; arbitrary universe families and identification with native Id are not claimed."
  IO.println "HO-084 puts the actual native compiler, decoder and native List execution in one declaration/computation environment through explicit rule morphisms. A compiled predicate consumer and a nonempty native map calculation share a formed telescope. This is joint admission/computation, not an identification of abstract HOL sequences with native List or compilation of the full primitive-equality fusion proof."
  IO.println "ID-058–061 give observer-relative transport replacement through the induced loop, a constructed coherent monoid-indexed instance and genuine noninvertible substitution controls. Parallel application values agree while route inspection distinguishes evidence. This does not identify native J proofs or select global UIP."
  IO.println "ID-062–065 construct optional original-reference recovery, stable publication and equivalent representative reconstruction, with missing/overwritten/wrong-store controls. A reference alone supplies no proof authority."
  IO.println "ID-066–073 construct actual native J congruence, conditional export/discharge and retained proof application through independently typed named bindings. ID-074–082 construct native path algebra, closed weak-constancy and decidable-equality Hedberg proof terms, and a derived Boolean region for variable endpoints and paths. ID-083–084 connect that derived proof to retained inspection and nonidentity named substitution in the same Boolean rules."
  IO.println "ID-085–091 and FORK-ID-QUALIFIED-001 close the selected identity contract on that same actual fragment: all seven roots and contextual steps preserve admitted displayed types; Pi/Sigma conversion boundaries are proved; native J, scoped assumptions, conditional export/discharge, named substitution and retained views share one nontrivial quotient interpretation. Native Id(p,q) is inhabited while the paths' conversion classes remain distinct. General normalization, future datatype/guest profiles and C refinement remain separate."
  IO.println "The pinned scoped-identity C audit records three public-interface failures and one constructive control. Source inspection found record serialization/hashing and recursive dependency work on known-proof reuse, not proof-checker replay; available counters do not measure that work."
  IO.println "A later 2026-09-13 draft report states that the three interface defects were repaired and adds structural definitions. Those later runtime claims are not independently rerun by this theory qualification; historical pinned evidence is not a claim about the new binary."
  IO.println "ADM-057–058 add a separate recursion-admission boundary: Boolean false/negation satisfies true predicate induction and injective succession but cannot support the natural-number height recurrence. An actual natural-number fold supplies the positive existence and uniqueness control. Reading apparent constructors from induction syntax alone is insufficient; this is not a reproduced C exploit or closure of FORK-ADM."
  IO.println "Recorded observations are not all-input conformance, freshly rerun C tests or candidate selection."
  IO.println "Collection build coverage is a separate source gate; theorem audits and successful target builds are separate verification evidence."

#eval reportStudy

-- The finite example checks evidence against actual semantic requirements.
#eval Mettapedia.TypeTheory.DesignStudy.EvaluationStudy.demandEvidence.remaining
