import Mettapedia.Logic.TheoryModel.Basic

/-!
# Gradual types as sets of static types

Abstracting Gradual Typing (Garcia, Clark and Tanter, POPL 2016) reads a
gradual type `G` as the set `γ G` of static types it may stand for, with the
unknown type `?` standing for every static type.  Here concretisation is a
satisfaction relation, `Conc T G` ("the static type `T` is a completion of
`G`"), so the theory–model Galois connection applies to it directly:

* `γ G` is the model class of the one-sentence theory `{G}`
  (`concretisation_eq_models`);
* **precision** `G ⊑ G'` is inclusion of concretisations
  (`prec_iff_concretisation_subset`), i.e. entailment `{G} ⊨ G'`;
* **consistency** `G ∼ G'` is non-empty intersection of concretisations
  (`consis_iff_exists_conc`), i.e. the theory `{G, G'}` has a model
  (`consis_iff_models_nonempty`).

**Abstraction.**  The abstraction `α K` of a non-empty set `K` of static
types is the most precise gradual type whose concretisation contains `K`.  In
the theory–model reading, the theory `theoryOf Conc K` (the gradual types
covering `K`) is the up-set generated by `α K` (`theoryOf_alpha`), so the
AGT Galois connection `K ⊆ γ G ↔ α K ⊑ G` is the theory–model connection
followed by taking the least element of a principal theory
(`alpha_galois`), and `γ ∘ α` is the elementary hull
(`concretisation_alpha_eq_hull`).
* For finite `K`, `α` is computed by anti-unification (`join`, `alpha`),
  without choice.
* For arbitrary non-empty `K`, `α K` exists (`exists_abstraction`); this is
  the one deliberately classical declaration.
* **Exactly why `α` is partial**: the theory of the empty class is all gradual
  types, which has no least element, because no gradual type has empty
  concretisation (`no_abstraction_empty`).  This matches AGT's "`α(∅)` is
  undefined".

**Meet** (`meet`) computes the concretisation of an intersection
(`conc_meet_iff`) and is defined exactly on consistent pairs
(`meet_isSome_iff`).

**Pairwise and joint.**  For gradual types, pairwise consistency implies
joint consistency (`helly`): unknowns are independent, so each position is
constrained separately.  With *shared* unknowns (type variables that may
repeat) this fails: `x → x`, `Int → y` and `z → Bool` are pairwise consistent
and jointly inconsistent (`SharedUnknowns.pairwise`, `SharedUnknowns.not_joint`).
-/

set_option autoImplicit false

namespace Mettapedia.OSLF.Programs.GradualTypes

open Mettapedia.Logic.TheoryModel

/-! ## Static and gradual types -/

/-- Static types. -/
inductive SType where
  | int
  | bool
  | arr (dom cod : SType)
  deriving DecidableEq

/-- Gradual types: the static formers and the unknown type. -/
inductive GType where
  | unknown
  | int
  | bool
  | arr (dom cod : GType)
  deriving DecidableEq

/-- A static type read as a gradual type. -/
def SType.toG : SType → GType
  | .int => .int
  | .bool => .bool
  | .arr a b => .arr a.toG b.toG

/-- **Concretisation** as satisfaction: `Conc T G` says the static type `T`
is one of the types `G` may stand for. -/
inductive Conc : SType → GType → Prop
  | unknown (T : SType) : Conc T .unknown
  | int : Conc .int .int
  | bool : Conc .bool .bool
  | arr {a b : SType} {A B : GType} : Conc a A → Conc b B → Conc (.arr a b) (.arr A B)

/-- The concretisation `γ G`. -/
def concretisation (G : GType) : Set SType := {T | Conc T G}

/-- **`γ G` is the model class of the theory `{G}`.** -/
theorem concretisation_eq_models (G : GType) : concretisation G = models Conc {G} := by
  ext T
  exact ⟨fun h _ hmem => hmem ▸ h, fun h => h rfl⟩

theorem conc_arr_iff {a b : SType} {A B : GType} :
    Conc (.arr a b) (.arr A B) ↔ Conc a A ∧ Conc b B :=
  ⟨fun h => by cases h with | arr ha hb => exact ⟨ha, hb⟩, fun h => .arr h.1 h.2⟩

/-- A static type stands only for itself. -/
theorem conc_toG_iff {T U : SType} : Conc T U.toG ↔ T = U := by
  induction U generalizing T with
  | int => exact ⟨fun h => by cases h; rfl, by rintro rfl; exact .int⟩
  | bool => exact ⟨fun h => by cases h; rfl, by rintro rfl; exact .bool⟩
  | arr a b iha ihb =>
    constructor
    · intro h
      cases h with
      | arr ha hb => rw [iha.mp ha, ihb.mp hb]
    · rintro rfl
      exact .arr (iha.mpr rfl) (ihb.mpr rfl)

/-- A canonical completion of every gradual type. -/
def witness : GType → SType
  | .unknown => .int
  | .int => .int
  | .bool => .bool
  | .arr A B => .arr (witness A) (witness B)

/-- Every gradual type has a completion. -/
theorem conc_witness : ∀ G : GType, Conc (witness G) G
  | .unknown => .unknown _
  | .int => .int
  | .bool => .bool
  | .arr A B => .arr (conc_witness A) (conc_witness B)

theorem concretisation_nonempty (G : GType) : (concretisation G).Nonempty :=
  ⟨witness G, conc_witness G⟩

/-! ## Precision -/

/-- **Precision**: `Prec G G'` says `G` is at least as precise as `G'`. -/
inductive Prec : GType → GType → Prop
  | unknown (G : GType) : Prec G .unknown
  | int : Prec .int .int
  | bool : Prec .bool .bool
  | arr {A B A' B' : GType} : Prec A A' → Prec B B' → Prec (.arr A B) (.arr A' B')

theorem Prec.refl : ∀ G : GType, Prec G G
  | .unknown => .unknown _
  | .int => .int
  | .bool => .bool
  | .arr A B => .arr (Prec.refl A) (Prec.refl B)

theorem Prec.conc {G G' : GType} (h : Prec G G') {T : SType} (hT : Conc T G) : Conc T G' := by
  induction h generalizing T with
  | unknown => exact .unknown _
  | int => exact hT
  | bool => exact hT
  | arr _ _ iha ihb =>
    cases hT with
    | arr ha hb => exact .arr (iha ha) (ihb hb)

/-- **Precision is inclusion of concretisations.** -/
theorem prec_iff_concretisation_subset {G G' : GType} :
    Prec G G' ↔ concretisation G ⊆ concretisation G' := by
  constructor
  · intro h T hT
    exact h.conc hT
  · intro h
    induction G' generalizing G with
    | unknown => exact .unknown _
    | int =>
      cases G with
      | unknown => exact absurd (h (Conc.unknown .bool)) nofun
      | int => exact .int
      | bool => exact absurd (h Conc.bool) nofun
      | arr A B => exact absurd (h (conc_witness (.arr A B))) nofun
    | bool =>
      cases G with
      | unknown => exact absurd (h (Conc.unknown .int)) nofun
      | int => exact absurd (h Conc.int) nofun
      | bool => exact .bool
      | arr A B => exact absurd (h (conc_witness (.arr A B))) nofun
    | arr A' B' iha ihb =>
      cases G with
      | unknown => exact absurd (h (Conc.unknown .int)) nofun
      | int => exact absurd (h Conc.int) nofun
      | bool => exact absurd (h Conc.bool) nofun
      | arr A B =>
        refine .arr (iha fun T hT => ?_) (ihb fun T hT => ?_)
        · exact (conc_arr_iff.mp (h (Conc.arr hT (conc_witness B)))).1
        · exact (conc_arr_iff.mp (h (Conc.arr (conc_witness A) hT))).2

/-- Precision is entailment in the theory–model reading. -/
theorem prec_iff_entails {G G' : GType} : Prec G G' ↔ Entails Conc {G} G' := by
  rw [prec_iff_concretisation_subset]
  exact ⟨fun h _ hm => h (hm rfl), fun h T hT => h fun _ hmem => hmem ▸ hT⟩

theorem Prec.trans {G G' G'' : GType} (first : Prec G G') (second : Prec G' G'') :
    Prec G G'' :=
  prec_iff_concretisation_subset.mpr fun _ hT => second.conc (first.conc hT)

theorem Prec.antisymm {G G' : GType} (first : Prec G G') (second : Prec G' G) : G = G' := by
  induction first with
  | unknown G => cases second; rfl
  | int => rfl
  | bool => rfl
  | arr _ _ iha ihb =>
    cases second with
    | arr ha hb => rw [iha ha, ihb hb]

/-- A static type is a completion of `G` exactly when it is more precise. -/
theorem conc_iff_prec_toG {T : SType} {G : GType} : Conc T G ↔ Prec T.toG G := by
  rw [prec_iff_concretisation_subset]
  constructor
  · intro h U hU
    rw [conc_toG_iff.mp hU]
    exact h
  · intro h
    exact h (conc_toG_iff.mpr rfl)

/-! ## Consistency -/

/-- Consistency, by the rules of Siek and Taha. -/
inductive Consis : GType → GType → Prop
  | unknownLeft (G : GType) : Consis .unknown G
  | unknownRight (G : GType) : Consis G .unknown
  | int : Consis .int .int
  | bool : Consis .bool .bool
  | arr {A B A' B' : GType} : Consis A A' → Consis B B' → Consis (.arr A B) (.arr A' B')

theorem Consis.symm {G G' : GType} (h : Consis G G') : Consis G' G := by
  induction h with
  | unknownLeft => exact .unknownRight _
  | unknownRight => exact .unknownLeft _
  | int => exact .int
  | bool => exact .bool
  | arr _ _ iha ihb => exact .arr iha ihb

/-- **Consistency is non-empty intersection of concretisations** (the
consistent lifting of equality). -/
theorem consis_iff_exists_conc {G G' : GType} :
    Consis G G' ↔ ∃ T, Conc T G ∧ Conc T G' := by
  constructor
  · intro h
    induction h with
    | unknownLeft G => exact ⟨witness G, .unknown _, conc_witness G⟩
    | unknownRight G => exact ⟨witness G, conc_witness G, .unknown _⟩
    | int => exact ⟨.int, .int, .int⟩
    | bool => exact ⟨.bool, .bool, .bool⟩
    | arr _ _ iha ihb =>
      obtain ⟨a, ha, ha'⟩ := iha
      obtain ⟨b, hb, hb'⟩ := ihb
      exact ⟨.arr a b, .arr ha hb, .arr ha' hb'⟩
  · rintro ⟨T, hT, hT'⟩
    induction hT generalizing G' with
    | unknown => exact .unknownLeft _
    | int => cases hT' with | unknown => exact .unknownRight _ | int => exact .int
    | bool => cases hT' with | unknown => exact .unknownRight _ | bool => exact .bool
    | arr _ _ iha ihb =>
      cases hT' with
      | unknown => exact .unknownRight _
      | arr ha hb => exact .arr (iha ha) (ihb hb)

/-- **Consistency is consistency of the two-sentence theory**: `{G, G'}` has a
model. -/
theorem consis_iff_models_nonempty {G G' : GType} :
    Consis G G' ↔ (models Conc {G, G'}).Nonempty := by
  rw [consis_iff_exists_conc]
  constructor
  · rintro ⟨T, hT, hT'⟩
    refine ⟨T, fun H hH => ?_⟩
    rcases hH with rfl | rfl
    · exact hT
    · exact hT'
  · rintro ⟨T, hT⟩
    exact ⟨T, hT (Or.inl rfl), hT (Or.inr rfl)⟩

/-- Consistency is monotone for precision: making types less precise never
loses consistency. -/
theorem Consis.mono {A B A' B' : GType} (h : Consis A B) (hA : Prec A A') (hB : Prec B B') :
    Consis A' B' := by
  obtain ⟨T, hT, hT'⟩ := consis_iff_exists_conc.mp h
  exact consis_iff_exists_conc.mpr ⟨T, hA.conc hT, hB.conc hT'⟩

/-- Consistency is not transitive: `Int ∼ ?` and `? ∼ Bool`, but not
`Int ∼ Bool`. -/
theorem consis_not_transitive :
    Consis .int .unknown ∧ Consis .unknown .bool ∧ ¬ Consis .int .bool :=
  ⟨.unknownRight _, .unknownLeft _, nofun⟩

/-! ## Meet -/

/-- The meet in precision: the gradual type whose concretisation is the
intersection. -/
def meet : GType → GType → Option GType
  | .unknown, G => some G
  | .int, .unknown => some .int
  | .int, .int => some .int
  | .bool, .unknown => some .bool
  | .bool, .bool => some .bool
  | .arr A B, .unknown => some (.arr A B)
  | .arr A B, .arr A' B' =>
    match meet A A', meet B B' with
    | some M, some N => some (.arr M N)
    | _, _ => none
  | _, _ => none

theorem meet_unknown_right (G : GType) : meet G .unknown = some G := by
  cases G <;> rfl

theorem meet_arr {A B A' B' : GType} :
    meet (.arr A B) (.arr A' B') =
      match meet A A', meet B B' with
      | some M, some N => some (.arr M N)
      | _, _ => none :=
  rfl

theorem meet_arr_eq_some {A B A' B' M : GType} :
    meet (.arr A B) (.arr A' B') = some M ↔
      ∃ M₁ M₂, meet A A' = some M₁ ∧ meet B B' = some M₂ ∧ M = .arr M₁ M₂ := by
  rw [meet_arr]
  constructor
  · intro h
    rcases h₁ : meet A A' with _ | M₁ <;> rcases h₂ : meet B B' with _ | M₂ <;>
      simp only [h₁, h₂, reduceCtorEq, Option.some.injEq] at h
    exact ⟨M₁, M₂, rfl, rfl, h.symm⟩
  · rintro ⟨M₁, M₂, h₁, h₂, rfl⟩
    simp only [h₁, h₂]

/-- **The meet computes the intersection of concretisations.** -/
theorem conc_meet_iff : ∀ {G G' M : GType}, meet G G' = some M →
    ∀ T, Conc T M ↔ Conc T G ∧ Conc T G'
  | .unknown, G', M, h, T => by
      cases h
      exact ⟨fun hT => ⟨.unknown _, hT⟩, fun hT => hT.2⟩
  | .int, .unknown, M, h, T => by
      cases h
      exact ⟨fun hT => ⟨hT, .unknown _⟩, fun hT => hT.1⟩
  | .int, .int, M, h, T => by
      cases h
      exact ⟨fun hT => ⟨hT, hT⟩, fun hT => hT.1⟩
  | .bool, .unknown, M, h, T => by
      cases h
      exact ⟨fun hT => ⟨hT, .unknown _⟩, fun hT => hT.1⟩
  | .bool, .bool, M, h, T => by
      cases h
      exact ⟨fun hT => ⟨hT, hT⟩, fun hT => hT.1⟩
  | .arr A B, .unknown, M, h, T => by
      cases h
      exact ⟨fun hT => ⟨hT, .unknown _⟩, fun hT => hT.1⟩
  | .arr A B, .arr A' B', M, h, T => by
      obtain ⟨M₁, M₂, h₁, h₂, rfl⟩ := meet_arr_eq_some.mp h
      constructor
      · intro hT
        cases hT with
        | arr ha hb =>
          have ha' := (conc_meet_iff h₁ _).mp ha
          have hb' := (conc_meet_iff h₂ _).mp hb
          exact ⟨.arr ha'.1 hb'.1, .arr ha'.2 hb'.2⟩
      · rintro ⟨hT, hT'⟩
        cases hT with
        | arr ha hb =>
          cases hT' with
          | arr ha' hb' =>
            exact .arr ((conc_meet_iff h₁ _).mpr ⟨ha, ha'⟩) ((conc_meet_iff h₂ _).mpr ⟨hb, hb'⟩)
  | .int, .bool, M, h, _ => by cases h
  | .int, .arr _ _, M, h, _ => by cases h
  | .bool, .int, M, h, _ => by cases h
  | .bool, .arr _ _, M, h, _ => by cases h
  | .arr _ _, .int, M, h, _ => by cases h
  | .arr _ _, .bool, M, h, _ => by cases h

/-- **The meet is defined exactly on consistent pairs.** -/
theorem meet_isSome_iff {G G' : GType} : (∃ M, meet G G' = some M) ↔ Consis G G' := by
  constructor
  · rintro ⟨M, h⟩
    obtain ⟨T, hT⟩ : ∃ T, Conc T M := ⟨witness M, conc_witness M⟩
    exact consis_iff_exists_conc.mpr ⟨T, ((conc_meet_iff h T).mp hT).1, ((conc_meet_iff h T).mp hT).2⟩
  · intro h
    induction h with
    | unknownLeft G => exact ⟨G, rfl⟩
    | unknownRight G => exact ⟨G, meet_unknown_right G⟩
    | int => exact ⟨.int, rfl⟩
    | bool => exact ⟨.bool, rfl⟩
    | arr _ _ iha ihb =>
      obtain ⟨M₁, h₁⟩ := iha
      obtain ⟨M₂, h₂⟩ := ihb
      exact ⟨.arr M₁ M₂, meet_arr_eq_some.mpr ⟨M₁, M₂, h₁, h₂, rfl⟩⟩

/-- The meet is the greatest lower bound in precision. -/
theorem prec_meet_iff {G G' M : GType} (h : meet G G' = some M) (L : GType) :
    Prec L M ↔ Prec L G ∧ Prec L G' := by
  simp only [prec_iff_concretisation_subset]
  constructor
  · intro hL
    exact ⟨fun T hT => ((conc_meet_iff h T).mp (hL hT)).1,
      fun T hT => ((conc_meet_iff h T).mp (hL hT)).2⟩
  · rintro ⟨hG, hG'⟩ T hT
    exact (conc_meet_iff h T).mpr ⟨hG hT, hG' hT⟩

/-- The meet is monotone for precision. -/
theorem meet_mono {A B A' B' M : GType} (h : meet A B = some M) (hA : Prec A A')
    (hB : Prec B B') : ∃ M', meet A' B' = some M' ∧ Prec M M' := by
  have consistent : Consis A' B' :=
    (meet_isSome_iff.mp ⟨M, h⟩).mono hA hB
  obtain ⟨M', h'⟩ := meet_isSome_iff.mpr consistent
  refine ⟨M', h', (prec_meet_iff h' M).mpr ⟨?_, ?_⟩⟩
  · exact (((prec_meet_iff h M).mp (Prec.refl M)).1).trans hA
  · exact (((prec_meet_iff h M).mp (Prec.refl M)).2).trans hB

/-! ## Abstraction -/

/-- The join in precision (anti-unification of two gradual types). -/
def join : GType → GType → GType
  | .int, .int => .int
  | .bool, .bool => .bool
  | .arr A B, .arr A' B' => .arr (join A A') (join B B')
  | _, _ => .unknown

theorem prec_join_left : ∀ G G' : GType, Prec G (join G G')
  | .unknown, _ => .unknown _
  | .int, .unknown => .unknown _
  | .int, .int => .int
  | .int, .bool => .unknown _
  | .int, .arr _ _ => .unknown _
  | .bool, .unknown => .unknown _
  | .bool, .int => .unknown _
  | .bool, .bool => .bool
  | .bool, .arr _ _ => .unknown _
  | .arr _ _, .unknown => .unknown _
  | .arr _ _, .int => .unknown _
  | .arr _ _, .bool => .unknown _
  | .arr A B, .arr A' B' => .arr (prec_join_left A A') (prec_join_left B B')

theorem prec_join_right : ∀ G G' : GType, Prec G' (join G G')
  | .unknown, .unknown => .unknown _
  | .unknown, .int => .unknown _
  | .unknown, .bool => .unknown _
  | .unknown, .arr _ _ => .unknown _
  | .int, .unknown => .unknown _
  | .int, .int => .int
  | .int, .bool => .unknown _
  | .int, .arr _ _ => .unknown _
  | .bool, .unknown => .unknown _
  | .bool, .int => .unknown _
  | .bool, .bool => .bool
  | .bool, .arr _ _ => .unknown _
  | .arr _ _, .unknown => .unknown _
  | .arr _ _, .int => .unknown _
  | .arr _ _, .bool => .unknown _
  | .arr A B, .arr A' B' => .arr (prec_join_right A A') (prec_join_right B B')

/-- The join is the least upper bound in precision. -/
theorem join_least : ∀ {G G' L : GType}, Prec G L → Prec G' L → Prec (join G G') L
  | _, _, .unknown, _, _ => .unknown _
  | .int, .int, .int, _, _ => .int
  | .bool, .bool, .bool, _, _ => .bool
  | .arr _ _, .arr _ _, .arr _ _, .arr hA hB, .arr hA' hB' =>
      .arr (join_least hA hA') (join_least hB hB')
  | .unknown, _, .int, h, _ => nomatch h
  | .unknown, _, .bool, h, _ => nomatch h
  | .unknown, _, .arr _ _, h, _ => nomatch h
  | .int, .unknown, .int, _, h => nomatch h
  | .int, .bool, .int, _, h => nomatch h
  | .int, .arr _ _, .int, _, h => nomatch h
  | .bool, .unknown, .bool, _, h => nomatch h
  | .bool, .int, .bool, _, h => nomatch h
  | .bool, .arr _ _, .bool, _, h => nomatch h
  | .int, _, .bool, h, _ => nomatch h
  | .int, _, .arr _ _, h, _ => nomatch h
  | .bool, _, .int, h, _ => nomatch h
  | .bool, _, .arr _ _, h, _ => nomatch h
  | .arr _ _, _, .int, h, _ => nomatch h
  | .arr _ _, _, .bool, h, _ => nomatch h
  | .arr _ _, .unknown, .arr _ _, _, h => nomatch h
  | .arr _ _, .int, .arr _ _, _, h => nomatch h
  | .arr _ _, .bool, .arr _ _, _, h => nomatch h

/-- **The abstraction of a non-empty finite set** `{T} ∪ Ts`, by
anti-unification. -/
def alpha (T : SType) (Ts : List SType) : GType :=
  Ts.foldl (fun G U => join G U.toG) T.toG

/-- The finite set `{T} ∪ Ts`. -/
def finiteClass (T : SType) (Ts : List SType) : Set SType :=
  {U | U ∈ T :: Ts}

private theorem foldl_join_prec_iff (L : GType) :
    ∀ (Ts : List SType) (G : GType),
      Prec (Ts.foldl (fun G U => join G U.toG) G) L ↔ Prec G L ∧ ∀ U ∈ Ts, Prec U.toG L
  | [], G => by simp
  | U :: Ts, G => by
      rw [List.foldl_cons, foldl_join_prec_iff L Ts]
      constructor
      · rintro ⟨hjoin, hrest⟩
        refine ⟨(prec_join_left G U.toG).trans hjoin, ?_⟩
        intro V hV
        rcases List.mem_cons.mp hV with rfl | hV
        · exact (prec_join_right G V.toG).trans hjoin
        · exact hrest V hV
      · rintro ⟨hG, hall⟩
        exact ⟨join_least hG (hall U (List.mem_cons_self ..)),
          fun V hV => hall V (List.mem_cons_of_mem _ hV)⟩

/-- **The AGT Galois connection** (soundness and optimality of `α`):
`K ⊆ γ G ↔ α K ⊑ G` for a non-empty finite `K`. -/
theorem alpha_galois (T : SType) (Ts : List SType) (G : GType) :
    finiteClass T Ts ⊆ concretisation G ↔ Prec (alpha T Ts) G := by
  rw [alpha, foldl_join_prec_iff]
  constructor
  · intro h
    exact ⟨conc_iff_prec_toG.mp (h (List.mem_cons_self ..)),
      fun U hU => conc_iff_prec_toG.mp (h (List.mem_cons_of_mem _ hU))⟩
  · rintro ⟨hT, hall⟩ U hU
    rcases List.mem_cons.mp hU with rfl | hU
    · exact conc_iff_prec_toG.mpr hT
    · exact conc_iff_prec_toG.mpr (hall U hU)

/-- Soundness of `α`. -/
theorem alpha_sound (T : SType) (Ts : List SType) :
    finiteClass T Ts ⊆ concretisation (alpha T Ts) :=
  (alpha_galois T Ts _).mpr (Prec.refl _)

/-- **The theory of a non-empty finite class is the up-set of its
abstraction.** -/
theorem theoryOf_alpha (T : SType) (Ts : List SType) :
    theoryOf Conc (finiteClass T Ts) = {G | Prec (alpha T Ts) G} := by
  ext G
  exact alpha_galois T Ts G

/-- **`γ ∘ α` is the elementary hull** of the theory–model connection. -/
theorem concretisation_alpha_eq_hull (T : SType) (Ts : List SType) :
    concretisation (alpha T Ts) = models Conc (theoryOf Conc (finiteClass T Ts)) := by
  ext U
  constructor
  · intro hU G hG
    exact ((alpha_galois T Ts G).mp hG).conc hU
  · intro hU
    exact hU (alpha_sound T Ts)

/-- A class of static types has an abstraction when its theory has a least
element in precision. -/
def IsAbstraction (K : Set SType) (G : GType) : Prop :=
  K ⊆ concretisation G ∧ ∀ G', K ⊆ concretisation G' → Prec G G'

theorem isAbstraction_alpha (T : SType) (Ts : List SType) :
    IsAbstraction (finiteClass T Ts) (alpha T Ts) :=
  ⟨alpha_sound T Ts, fun G' h => (alpha_galois T Ts G').mp h⟩

/-- **Exactly why `α` is partial**: the empty class has no abstraction,
because the theory of the empty class is every gradual type and no gradual
type is below both `Int` and `Bool`. -/
theorem no_abstraction_empty (G : GType) : ¬ IsAbstraction ∅ G := by
  rintro ⟨_, least⟩
  have hInt := least .int (Set.empty_subset _)
  have hBool := least .bool (Set.empty_subset _)
  cases hInt
  cases hBool

/-- The generalisations of a static type `T`: the gradual types of which `T`
is a completion. -/
def generalisations : SType → List GType
  | .int => [.unknown, .int]
  | .bool => [.unknown, .bool]
  | .arr a b =>
    .unknown :: (generalisations a).flatMap fun A => (generalisations b).map fun B => .arr A B

theorem mem_generalisations_iff : ∀ {T : SType} {G : GType}, G ∈ generalisations T ↔ Conc T G
  | .int, G => by
      cases G <;> simp [generalisations] <;> first | exact .unknown _ | exact .int | nofun
  | .bool, G => by
      cases G <;> simp [generalisations] <;> first | exact .unknown _ | exact .bool | nofun
  | .arr a b, G => by
      cases G with
      | unknown => simp [generalisations, Conc.unknown]
      | int => simp [generalisations]; nofun
      | bool => simp [generalisations]; nofun
      | arr A B =>
        simp only [generalisations, List.mem_cons, reduceCtorEq, false_or, List.mem_flatMap,
          List.mem_map, GType.arr.injEq]
        rw [conc_arr_iff, ← mem_generalisations_iff, ← mem_generalisations_iff]
        constructor
        · rintro ⟨A', hA', B', hB', rfl, rfl⟩
          exact ⟨hA', hB'⟩
        · rintro ⟨hA, hB⟩
          exact ⟨A, hA, B, hB, rfl, rfl⟩

/-- Meet of a list, starting from the unknown type. -/
def meetList : List GType → Option GType
  | [] => some .unknown
  | G :: Gs => (meetList Gs).bind (meet G)

theorem conc_meetList : ∀ {Gs : List GType} {M : GType}, meetList Gs = some M →
    ∀ T, Conc T M ↔ ∀ G ∈ Gs, Conc T G
  | [], M, h, T => by
      cases h
      simp [Conc.unknown]
  | G :: Gs, M, h, T => by
      simp only [meetList] at h
      rcases hrest : meetList Gs with _ | N
      · simp [hrest] at h
      · simp only [hrest, Option.bind_some] at h
        rw [conc_meet_iff h T, conc_meetList hrest T]
        simp

/-- A common completion makes every meet of a list defined. -/
theorem meetList_isSome_of_common : ∀ {Gs : List GType} {T : SType},
    (∀ G ∈ Gs, Conc T G) → ∃ M, meetList Gs = some M
  | [], _, _ => ⟨.unknown, rfl⟩
  | G :: Gs, T, h => by
      obtain ⟨N, hN⟩ := meetList_isSome_of_common (T := T) fun G' hG' =>
        h G' (List.mem_cons_of_mem _ hG')
      have consistent : Consis G N :=
        consis_iff_exists_conc.mpr ⟨T, h G (List.mem_cons_self ..),
          (conc_meetList hN T).mpr fun G' hG' => h G' (List.mem_cons_of_mem _ hG')⟩
      obtain ⟨M, hM⟩ := meet_isSome_iff.mpr consistent
      exact ⟨M, by simp only [meetList, hN, Option.bind_some, hM]⟩

/-- **Every non-empty class of static types has an abstraction** (AGT's
Definition 5 on arbitrary sets).  Deciding which generalisations of a member
cover the class uses classical logic. -/
theorem exists_abstraction (K : Set SType) (hK : K.Nonempty) :
    ∃ G, IsAbstraction K G := by
  classical
  obtain ⟨T₀, hT₀⟩ := hK
  let covering := (generalisations T₀).filter fun G => decide (K ⊆ concretisation G)
  have member : ∀ {G}, G ∈ covering ↔ K ⊆ concretisation G := by
    intro G
    simp only [covering, List.mem_filter, decide_eq_true_eq, mem_generalisations_iff]
    exact ⟨fun h => h.2, fun h => ⟨h hT₀, h⟩⟩
  obtain ⟨M, hM⟩ := meetList_isSome_of_common (Gs := covering) (T := T₀)
    fun G hG => member.mp hG hT₀
  refine ⟨M, fun U hU => (conc_meetList hM U).mpr fun G hG => member.mp hG hU, ?_⟩
  intro G' hG'
  exact prec_iff_concretisation_subset.mpr fun T hT =>
    (conc_meetList hM T).mp hT G' (member.mpr hG')

/-! ## Pairwise and joint consistency -/

/-- A type consistent with two consistent types is consistent with their
meet. -/
theorem consis_meet {G : GType} : ∀ {A B : GType}, Consis G A → Consis G B → Consis A B →
    ∃ M, meet A B = some M ∧ Consis G M := by
  induction G with
  | unknown =>
    intro A B _ _ hAB
    obtain ⟨M, hM⟩ := meet_isSome_iff.mpr hAB
    exact ⟨M, hM, .unknownLeft _⟩
  | int =>
    intro A B hA hB _
    cases hA <;> cases hB
    · exact ⟨.unknown, rfl, .unknownRight _⟩
    · exact ⟨.int, rfl, .int⟩
    · exact ⟨.int, rfl, .int⟩
    · exact ⟨.int, rfl, .int⟩
  | bool =>
    intro A B hA hB _
    cases hA <;> cases hB
    · exact ⟨.unknown, rfl, .unknownRight _⟩
    · exact ⟨.bool, rfl, .bool⟩
    · exact ⟨.bool, rfl, .bool⟩
    · exact ⟨.bool, rfl, .bool⟩
  | arr G₁ G₂ ih₁ ih₂ =>
    intro A B hA hB hAB
    cases hA with
    | unknownRight =>
      obtain ⟨M, hM⟩ := meet_isSome_iff.mpr hAB
      cases hM
      exact ⟨B, rfl, hB⟩
    | arr hA₁ hA₂ =>
      cases hB with
      | unknownRight =>
        exact ⟨_, meet_unknown_right _, .arr hA₁ hA₂⟩
      | arr hB₁ hB₂ =>
        cases hAB with
        | arr hAB₁ hAB₂ =>
          obtain ⟨M₁, hM₁, hG₁⟩ := ih₁ hA₁ hB₁ hAB₁
          obtain ⟨M₂, hM₂, hG₂⟩ := ih₂ hA₂ hB₂ hAB₂
          exact ⟨.arr M₁ M₂, meet_arr_eq_some.mpr ⟨M₁, M₂, hM₁, hM₂, rfl⟩, .arr hG₁ hG₂⟩

private theorem meetList_consis : ∀ {Gs : List GType} {G : GType},
    (∀ A ∈ Gs, Consis G A) → (∀ A ∈ Gs, ∀ B ∈ Gs, Consis A B) →
      ∃ M, meetList Gs = some M ∧ Consis G M
  | [], _, _, _ => ⟨.unknown, rfl, .unknownRight _⟩
  | A :: Gs, G, hG, hpair => by
      have tail : ∀ B ∈ Gs, ∀ C ∈ Gs, Consis B C := fun B hB C hC =>
        hpair B (List.mem_cons_of_mem _ hB) C (List.mem_cons_of_mem _ hC)
      obtain ⟨N, hN, hGN⟩ := meetList_consis (G := G)
        (fun B hB => hG B (List.mem_cons_of_mem _ hB)) tail
      obtain ⟨N', hN', hAN⟩ := meetList_consis (G := A)
        (fun B hB => hpair A (List.mem_cons_self ..) B (List.mem_cons_of_mem _ hB)) tail
      rw [hN] at hN'
      cases hN'
      obtain ⟨M, hM, hGM⟩ := consis_meet (hG A (List.mem_cons_self ..)) hGN hAN
      exact ⟨M, by simp only [meetList, hN, Option.bind_some, hM], hGM⟩

/-- **Helly property for gradual types**: pairwise consistency of a finite
family implies a common completion. -/
theorem helly {Gs : List GType} (pairwise : ∀ A ∈ Gs, ∀ B ∈ Gs, Consis A B) :
    ∃ T, ∀ G ∈ Gs, Conc T G := by
  obtain ⟨M, hM, _⟩ := meetList_consis (G := .unknown) (fun _ _ => .unknownLeft _) pairwise
  exact ⟨witness M, (conc_meetList hM _).mp (conc_witness M)⟩

/-- The same, in the theory–model reading: a pairwise consistent finite
theory of gradual types has a model. -/
theorem models_nonempty_of_pairwise {Gs : List GType}
    (pairwise : ∀ A ∈ Gs, ∀ B ∈ Gs, (models Conc {A, B}).Nonempty) :
    (models Conc {G | G ∈ Gs}).Nonempty := by
  obtain ⟨T, hT⟩ := helly fun A hA B hB => consis_iff_models_nonempty.mpr (pairwise A hA B hB)
  exact ⟨T, fun G hG => hT G hG⟩

/-! ### Control: shared unknowns -/

namespace SharedUnknowns

/-- Gradual types whose unknowns are named, so that one unknown may occur
twice. -/
inductive Pattern where
  | var
  | int
  | bool
  | arr (dom cod : Pattern)

/-- Instantiate the unknown of a pattern. -/
def Pattern.instantiate (T : SType) : Pattern → SType
  | .var => T
  | .int => .int
  | .bool => .bool
  | .arr p q => .arr (p.instantiate T) (q.instantiate T)

/-- Concretisation of a pattern: its instances. -/
def ConcPat (T : SType) (p : Pattern) : Prop :=
  ∃ U, p.instantiate U = T

/-- `x → x`: the unknown occurs twice. -/
def diag : Pattern := .arr .var .var

/-- `Int → y`. -/
def intDom : Pattern := .arr .int .var

/-- `z → Bool`. -/
def boolCod : Pattern := .arr .var .bool

/-- **The three patterns are pairwise consistent.** -/
theorem pairwise :
    (ConcPat (.arr .int .int) diag ∧ ConcPat (.arr .int .int) intDom) ∧
      (ConcPat (.arr .bool .bool) diag ∧ ConcPat (.arr .bool .bool) boolCod) ∧
      (ConcPat (.arr .int .bool) intDom ∧ ConcPat (.arr .int .bool) boolCod) :=
  ⟨⟨⟨.int, rfl⟩, ⟨.int, rfl⟩⟩, ⟨⟨.bool, rfl⟩, ⟨.bool, rfl⟩⟩, ⟨⟨.bool, rfl⟩, ⟨.int, rfl⟩⟩⟩

/-- **The three patterns are jointly inconsistent.** -/
theorem not_joint : ¬ ∃ T, ConcPat T diag ∧ ConcPat T intDom ∧ ConcPat T boolCod := by
  rintro ⟨T, ⟨U, rfl⟩, ⟨V, hV⟩, ⟨W, hW⟩⟩
  simp only [diag, intDom, boolCod, Pattern.instantiate, SType.arr.injEq] at hV hW
  obtain ⟨hU, _⟩ := hV
  obtain ⟨_, hU'⟩ := hW
  rw [← hU] at hU'
  exact SType.noConfusion hU'

end SharedUnknowns

end Mettapedia.OSLF.Programs.GradualTypes
