import Mettapedia.Languages.MeTTa.TypeTheory.CumulativeTower.AuthoredIndexedFamilyReceiptNaturality

/-!
# Constructional native kernels generated by authored indexed families

An authored family may have three different computational faces which must not
be conflated:

* raw equation occurrences, closed under every syntactic substitution;
* typed instances of its canonical schemas, closed under typed substitution;
* an optional proof that every raw equation from a typed source preserves
  typing.

The last face needs an independent inversion or conversion-coherence theorem.
It is not required to obtain the stronger constructional face used by native
typed programs.  This module packages one intrinsically typed occurrence for
each authored schema and derives all of its typed substitution instances.  The
result is a judgment-indexed computation whose preservation invariant is part
of its state type.  Its steps realize into the existing proof-relevant native
computation without replaying a checker.
-/

set_option autoImplicit false

namespace Mettapedia.Languages.MeTTa.TypeTheory.CumulativeTower
namespace AuthoredIndexedFamilyConstruction

open AuthoredDeclarationSignature
open AuthoredIndexedFamilyPresentation
open AuthoredIndexedFamilyReceiptNaturality
open AuthoredIndexedFamilyTypedConversion
open Mettapedia.TypeTheory
open Mettapedia.TypeTheory.JudgmentalEquality
open Presentation
open Presentation.Declaration
open Presentation.Declaration.ComputationAuthority

/-! ## Typed source presentations -/

/-- A source-directed family whose canonical authored equations are themselves
typed native steps.  Naturality says that the authored/native receipt
comparison respects later substitution.  No uniform claim about all raw
syntactic instances is included. -/
structure TypedNativePresentation (presented : PresentedCandidate) where
  naturality : ReceiptNaturality presented
  canonical :
    ∀ index : Fin
        (equationSchemas (elaborate presented.source)).length,
      let schema :=
        (equationSchemas (elaborate presented.source)).get index
      TypedOccurrence presented schema.context schema.left schema.right
        schema.type
  canonicalAuthored :
    ∀ index : Fin
        (equationSchemas (elaborate presented.source)).length,
      (canonical index).authored =
        EquationOccurrence.canonical
          (equationSchemas (elaborate presented.source)) index

/-- Both endpoint typings of one schema position in the complete authored
source.  The index ranges over the source presentation, rather than over one
family candidate's local iota-clause list: a declaration world may contain
several mutually available native families. -/
structure TypedAuthoredSchema (presented : PresentedCandidate)
    (schema : EquationSchema) where
  sourceTyping :
    HasType (extendRules Tower.rules presented.candidate.signature)
      schema.context schema.left schema.type
  targetTyping :
    HasType (extendRules Tower.rules presented.candidate.signature)
      schema.context schema.right schema.type

/-- A source-wide finite inventory proving that every authored equation
schema has typed endpoints in the selected candidate view.  This is strictly
weaker than uniform preservation of arbitrary raw equation occurrences, but
exactly sufficient to generate the constructional native kernel. -/
structure ExhaustiveTypedSchemaInventory
    (presented : PresentedCandidate) where
  entry : ∀ index : Fin
      (equationSchemas (elaborate presented.source)).length,
    let schema :=
      (equationSchemas (elaborate presented.source)).get index
    TypedAuthoredSchema presented schema

namespace ExhaustiveTypedSchemaInventory

variable {presented : PresentedCandidate}

/-- The typed occurrence canonically generated by one source-wide inventory
position. -/
noncomputable def canonicalOccurrence
    (inventory : ExhaustiveTypedSchemaInventory presented)
    (index : Fin
      (equationSchemas (elaborate presented.source)).length) :
    let schema :=
      (equationSchemas (elaborate presented.source)).get index
    TypedOccurrence presented schema.context schema.left schema.right
      schema.type where
  authored := EquationOccurrence.canonical
    (equationSchemas (elaborate presented.source)) index
  sourceTyping := (inventory.entry index).sourceTyping
  targetTyping := (inventory.entry index).targetTyping

@[simp] theorem canonicalOccurrence_authored
    (inventory : ExhaustiveTypedSchemaInventory presented)
    (index : Fin
      (equationSchemas (elaborate presented.source)).length) :
    (inventory.canonicalOccurrence index).authored =
      EquationOccurrence.canonical
        (equationSchemas (elaborate presented.source)) index := by
  rfl

/-- Exact source coverage: every authored schema position constructs a typed
occurrence, including schemas belonging to another family in the same
declaration world. -/
theorem coversEveryAuthoredSchema
    (inventory : ExhaustiveTypedSchemaInventory presented)
    (index : Fin
      (equationSchemas (elaborate presented.source)).length) :
    Nonempty
      (let schema :=
        (equationSchemas (elaborate presented.source)).get index
       TypedOccurrence presented schema.context schema.left schema.right
         schema.type) :=
  ⟨inventory.canonicalOccurrence index⟩

/-- Receipt naturality plus exhaustive typed schema coverage generates the
complete constructional native presentation. -/
noncomputable def toTypedNativePresentation
    (inventory : ExhaustiveTypedSchemaInventory presented)
    (naturality : ReceiptNaturality presented) :
    TypedNativePresentation presented where
  naturality := naturality
  canonical := inventory.canonicalOccurrence
  canonicalAuthored := inventory.canonicalOccurrence_authored

end ExhaustiveTypedSchemaInventory

namespace TypedOccurrenceOps

variable {n : Nat} {presented : PresentedCandidate}
    {context : Tower.Ctx n} {left right sourceType targetType : Tower.Tm n}

/-- Change only the displayed type of a typed occurrence along the exact
directed tail relation of the declarative typing judgment.  The authored and
native computation receipts remain unchanged. -/
def adjust
    (occurrence : TypedOccurrence presented context left right sourceType)
    (adjustment : TypeAdjustment
      (extendRules Tower.rules presented.candidate.signature)
      sourceType targetType) :
    TypedOccurrence presented context left right targetType where
  authored := occurrence.authored
  sourceTyping := occurrence.sourceTyping.adjust adjustment
  targetTyping := occurrence.targetTyping.adjust adjustment

@[simp] theorem adjust_authored
    (occurrence : TypedOccurrence presented context left right sourceType)
    (adjustment : TypeAdjustment
      (extendRules Tower.rules presented.candidate.signature)
      sourceType targetType) :
    (adjust occurrence adjustment).authored = occurrence.authored :=
  rfl

@[simp] theorem adjust_nativeEvidence
    (occurrence : TypedOccurrence presented context left right sourceType)
    (adjustment : TypeAdjustment
      (extendRules Tower.rules presented.candidate.signature)
      sourceType targetType) :
    (adjust occurrence adjustment).nativeEvidence =
      occurrence.nativeEvidence :=
  rfl

end TypedOccurrenceOps

namespace TypedNativePresentation

variable {presented : PresentedCandidate}

/-- Typed substitution of a canonical authored schema constructs a native
typed occurrence directly.  Both endpoint derivations are transported with
the receipt. -/
def instantiate (typed : TypedNativePresentation presented)
    (index : Fin (equationSchemas (elaborate presented.source)).length)
    {m : Nat} (targetContext : Tower.Ctx m)
    (substitution : Sub Tower.Head
      ((equationSchemas (elaborate presented.source)).get index).arity m)
    (substitutionTyped : CtxMor
      (extendRules Tower.rules presented.candidate.signature)
      ((equationSchemas
        (elaborate presented.source)).get index).context
      targetContext substitution) :
    let schema :=
      (equationSchemas (elaborate presented.source)).get index
    TypedOccurrence presented targetContext
      (Presentation.subst substitution schema.left)
      (Presentation.subst substitution schema.right)
      (Presentation.subst substitution schema.type) :=
  (typed.canonical index).substitute substitution substitutionTyped

/-- The constructed occurrence retains the exact authored schema position and
substitution. -/
theorem instantiate_authored (typed : TypedNativePresentation presented)
    (index : Fin (equationSchemas (elaborate presented.source)).length)
    {m : Nat} (targetContext : Tower.Ctx m)
    (substitution : Sub Tower.Head
      ((equationSchemas (elaborate presented.source)).get index).arity m)
    (substitutionTyped : CtxMor
      (extendRules Tower.rules presented.candidate.signature)
      ((equationSchemas
        (elaborate presented.source)).get index).context
      targetContext substitution) :
    (typed.instantiate index targetContext substitution
      substitutionTyped).authored =
      (EquationOccurrence.canonical
        (equationSchemas (elaborate presented.source)) index).substitute
          substitution := by
  simp only [instantiate,
    AuthoredIndexedFamilyTypedConversion.TypedOccurrence.substitute]
  rw [typed.canonicalAuthored]

/-- Native realization commutes exactly with typed substitution.  This is an
equality of retained receipts, not merely of their propositional support. -/
theorem instantiate_nativeEvidence
    (typed : TypedNativePresentation presented)
    (index : Fin (equationSchemas (elaborate presented.source)).length)
    {m : Nat} (targetContext : Tower.Ctx m)
    (substitution : Sub Tower.Head
      ((equationSchemas (elaborate presented.source)).get index).arity m)
    (substitutionTyped : CtxMor
      (extendRules Tower.rules presented.candidate.signature)
      ((equationSchemas
        (elaborate presented.source)).get index).context
      targetContext substitution) :
    (typed.instantiate index targetContext substitution
      substitutionTyped).nativeEvidence =
      presented.candidate.computation.substitute substitution
        (typed.canonical index).nativeEvidence := by
  exact
    AuthoredIndexedFamilyTypedConversion.TypedOccurrence.nativeEvidence_substitute
      typed.naturality (typed.canonical index) substitution substitutionTyped

/-- A typed schema instance may be displayed at any type reached by the
declarative judgment's directed tail rules. -/
def instantiateAdjusted (typed : TypedNativePresentation presented)
    (index : Fin (equationSchemas (elaborate presented.source)).length)
    {m : Nat} (targetContext : Tower.Ctx m)
    (substitution : Sub Tower.Head
      ((equationSchemas (elaborate presented.source)).get index).arity m)
    (substitutionTyped : CtxMor
      (extendRules Tower.rules presented.candidate.signature)
      ((equationSchemas
        (elaborate presented.source)).get index).context
      targetContext substitution)
    {displayedType : Tower.Tm m}
    (adjustment : TypeAdjustment
      (extendRules Tower.rules presented.candidate.signature)
      (Presentation.subst substitution
        ((equationSchemas
          (elaborate presented.source)).get index).type)
      displayedType) :
    let schema :=
      (equationSchemas (elaborate presented.source)).get index
    TypedOccurrence presented targetContext
      (Presentation.subst substitution schema.left)
      (Presentation.subst substitution schema.right)
      displayedType :=
  TypedOccurrenceOps.adjust
    (typed.instantiate index targetContext substitution substitutionTyped)
    adjustment

/-! ## The constructional computation and its native realization -/

/-- One source-generated step between already typed states.  The witness keeps
the authored schema position, the typed substitution, both endpoint equations,
and the displayed-type adjustment. -/
structure ConstructedStep (typed : TypedNativePresentation presented)
    {typingIndex : TypingIndex Tower.Head}
    (source target : NativeIndexedState presented typingIndex) : Type where
  schemaIndex :
    Fin (equationSchemas (elaborate presented.source)).length
  substitution : Sub Tower.Head
    ((equationSchemas
      (elaborate presented.source)).get schemaIndex).arity
    typingIndex.arity
  substitutionTyped : CtxMor
    (extendRules Tower.rules presented.candidate.signature)
    ((equationSchemas
      (elaborate presented.source)).get schemaIndex).context
    typingIndex.context substitution
  sourceEquation :
    Presentation.subst substitution
      ((equationSchemas
        (elaborate presented.source)).get schemaIndex).left = source.1
  targetEquation :
    Presentation.subst substitution
      ((equationSchemas
        (elaborate presented.source)).get schemaIndex).right = target.1
  typeAdjustment : TypeAdjustment
    (extendRules Tower.rules presented.candidate.signature)
    (Presentation.subst substitution
      ((equationSchemas
        (elaborate presented.source)).get schemaIndex).type)
    typingIndex.type

namespace ConstructedStep

/-- Recover the complete typed authored occurrence represented by a
constructional step. -/
def toTypedOccurrence
    {typed : TypedNativePresentation presented}
    {typingIndex : TypingIndex Tower.Head}
    {source target : NativeIndexedState presented typingIndex}
    (step : ConstructedStep typed source target) :
    TypedOccurrence presented typingIndex.context source.1 target.1
      typingIndex.type := by
  let occurrence := typed.instantiateAdjusted step.schemaIndex
    typingIndex.context step.substitution step.substitutionTyped
    step.typeAdjustment
  dsimp only at occurrence
  rw [step.sourceEquation, step.targetEquation] at occurrence
  exact occurrence

/-- The authored occurrence retained directly by a constructional step. -/
def authoredOccurrence
    {typed : TypedNativePresentation presented}
    {typingIndex : TypingIndex Tower.Head}
    {source target : NativeIndexedState presented typingIndex}
    (step : ConstructedStep typed source target) :
    EquationOccurrence (equationSchemas (elaborate presented.source))
      source.1 target.1 where
  index := step.schemaIndex
  substitution := step.substitution
  sourceEquation := step.sourceEquation
  targetEquation := step.targetEquation

/-- Recovering a typed occurrence does not alter the exact authored schema
position or its retained substitution. -/
theorem toTypedOccurrence_authored
    {typed : TypedNativePresentation presented}
    {typingIndex : TypingIndex Tower.Head}
    {source target : NativeIndexedState presented typingIndex}
    (step : ConstructedStep typed source target) :
    step.toTypedOccurrence.authored = step.authoredOccurrence := by
  rcases source with ⟨sourceTerm, sourceTyping⟩
  rcases target with ⟨targetTerm, targetTyping⟩
  rcases step with
    ⟨schemaIndex, substitution, substitutionTyped, sourceEquation,
      targetEquation, adjustment⟩
  dsimp at sourceEquation targetEquation
  subst sourceTerm
  subst targetTerm
  simp [toTypedOccurrence, authoredOccurrence, instantiateAdjusted,
    TypedOccurrenceOps.adjust]
  rw [typed.instantiate_authored]
  apply EquationOccurrence.ext <;> rfl

/-- Forget only the source-construction witness to obtain the native family
step. -/
def toNativeStep
    {typed : TypedNativePresentation presented}
    {typingIndex : TypingIndex Tower.Head}
    {source target : NativeIndexedState presented typingIndex}
    (step : ConstructedStep typed source target) :
    NativeIndexedStep presented source target :=
  step.toTypedOccurrence.nativeEvidence

/-- Typed ambient substitution preserves the constructional source of a native
step.  The authored schema position is unchanged; the retained schema
substitution is composed with the ambient substitution, both endpoint
derivations are transported, and the displayed-type adjustment is substituted
in the same direction. -/
def substitute
    {typed : TypedNativePresentation presented}
    {typingIndex : TypingIndex Tower.Head}
    {source target : NativeIndexedState presented typingIndex}
    (step : ConstructedStep typed source target)
    {m : Nat} (targetContext : Tower.Ctx m)
    (substitution : Sub Tower.Head typingIndex.arity m)
    (substitutionTyped : CtxMor
      (extendRules Tower.rules presented.candidate.signature)
      typingIndex.context targetContext substitution) :
    let targetIndex : TypingIndex Tower.Head :=
      ⟨m, targetContext, Presentation.subst substitution typingIndex.type⟩
    let substitutedSource : NativeIndexedState presented targetIndex :=
      ⟨Presentation.subst substitution source.1,
        ⟨source.2.down.substitute substitutionTyped⟩⟩
    let substitutedTarget : NativeIndexedState presented targetIndex :=
      ⟨Presentation.subst substitution target.1,
        ⟨target.2.down.substitute substitutionTyped⟩⟩
    ConstructedStep typed substitutedSource substitutedTarget where
  schemaIndex := step.schemaIndex
  substitution := Presentation.subComp substitution step.substitution
  substitutionTyped := CtxMor.comp step.substitutionTyped substitutionTyped
  sourceEquation := by
    rw [← Presentation.subst_subComp, step.sourceEquation]
  targetEquation := by
    rw [← Presentation.subst_subComp, step.targetEquation]
  typeAdjustment := by
    simpa only [Presentation.subst_subComp] using
      step.typeAdjustment.substitute substitution

end ConstructedStep

/-- The source-generated family kernel.  Preservation is structural: both
endpoints are inhabitants of the same complete typing fibre. -/
def constructionalComputation
    (typed : TypedNativePresentation presented) :
    JudgmentalComputation (TypingIndex Tower.Head) where
  State := NativeIndexedState presented
  Step := fun source target => ConstructedStep typed source target

/-- Every constructional step realizes in the existing proof-relevant native
family computation. -/
def realizeStep (typed : TypedNativePresentation presented)
    {typingIndex : TypingIndex Tower.Head}
    {source target : NativeIndexedState presented typingIndex}
    (step : (constructionalComputation typed).Step source target) :
    (nativeIndexedComputation presented).Step source target :=
  step.toNativeStep

/-- Every canonical typed schema is itself a constructional step.  This is
the identity instance at the schema telescope; no boundary checker is
replayed. -/
noncomputable def canonicalConstructedStep
    (typed : TypedNativePresentation presented)
    (index : Fin
      (equationSchemas (elaborate presented.source)).length) :
    (constructionalComputation typed).Step
      (typed.canonical index).sourceState
      (typed.canonical index).targetState where
  schemaIndex := index
  substitution := Presentation.ids
  substitutionTyped := CtxMor.identity _ _
  sourceEquation := Presentation.subst_ids _
  targetEquation := Presentation.subst_ids _
  typeAdjustment := by
    simp only [Presentation.subst_ids,
      AuthoredIndexedFamilyTypedConversion.TypedOccurrence.index]
    exact .refl _

/-- A canonical source schema therefore has a native realization in exactly
the same complete typing fibre. -/
noncomputable def canonicalNativeStep
    (typed : TypedNativePresentation presented)
    (index : Fin
      (equationSchemas (elaborate presented.source)).length) :
    (nativeIndexedComputation presented).Step
      (typed.canonical index).sourceState
      (typed.canonical index).targetState :=
  typed.realizeStep (typed.canonicalConstructedStep index)

/-- The realization acts structurally on complete conversion trees, retaining
all intermediate typed states and their association tree. -/
def realizeConversion (typed : TypedNativePresentation presented)
    {typingIndex : TypingIndex Tower.Head}
    {source target : NativeIndexedState presented typingIndex} :
    ConversionEvidence (constructionalComputation typed) source target →
      ConversionEvidence (nativeIndexedComputation presented) source target
  | .step step => .step (typed.realizeStep step)
  | .refl state =>
      ConversionEvidence.refl
        (computation := nativeIndexedComputation presented) state
  | .symm path =>
      ConversionEvidence.symm
        (computation := nativeIndexedComputation presented)
        (typed.realizeConversion path)
  | .trans first second =>
      ConversionEvidence.trans
        (computation := nativeIndexedComputation presented)
        (typed.realizeConversion first) (typed.realizeConversion second)

@[simp] theorem realizeConversion_step
    (typed : TypedNativePresentation presented)
    {typingIndex : TypingIndex Tower.Head}
    {source target : NativeIndexedState presented typingIndex}
    (step : (constructionalComputation typed).Step source target) :
    typed.realizeConversion
        (ConversionEvidence.step
          (computation := constructionalComputation typed) step) =
      ConversionEvidence.step
        (computation := nativeIndexedComputation presented)
        (typed.realizeStep step) := by
  rfl

end TypedNativePresentation

/-! ## Native List and identity instance -/

namespace NativeList

open AuthoredIndexedFamilyReceiptNaturality.NativeList
open NativeIndexedFamilies.Intrinsic
open NativeIndexedFamilySource

@[simp] theorem presented_source_equation_schemas :
    equationSchemas
        (elaborate nativeListPresentedCandidate.source) = nativeSchemas := by
  change equationSchemas (elaborate nativeListInventory.source) = nativeSchemas
  rw [nativeListInventory.elaborate_source]
  rfl

/-- Canonical cons computation with its authored occurrence and both endpoint
derivations. -/
noncomputable def canonicalConsTypedOccurrence :
    TypedOccurrence nativeListPresentedCandidate contextAPZSHeadTail
      consIotaLeft consIotaRight consIotaResultType where
  authored := nativeListPresentedCandidate.receiptEquiv.symm
    consIotaReceipt.evidence
  sourceTyping := consIotaReceipt.sourceTyping
  targetTyping := consIotaReceipt.targetTyping

/-- Canonical identity computation with its authored occurrence and both
endpoint derivations. -/
noncomputable def canonicalIdentityTypedOccurrence :
    TypedOccurrence nativeListPresentedCandidate contextAXPD
      identityIotaLeft identityIotaRight identityIotaResultType where
  authored := nativeListPresentedCandidate.receiptEquiv.symm
    identityIotaReceipt.evidence
  sourceTyping := identityIotaReceipt.sourceTyping
  targetTyping := identityIotaReceipt.targetTyping

@[simp] theorem canonicalCons_nativeEvidence :
    canonicalConsTypedOccurrence.nativeEvidence =
      consIotaReceipt.evidence := by
  exact nativeListPresentedCandidate.receiptEquiv.apply_symm_apply _

@[simp] theorem canonicalIdentity_nativeEvidence :
    canonicalIdentityTypedOccurrence.nativeEvidence =
      identityIotaReceipt.evidence := by
  exact nativeListPresentedCandidate.receiptEquiv.apply_symm_apply _

/-- All three authored schemas of the native List/identity declaration world
have typed endpoints.  The source-wide inventory performs the finite case
analysis once; the generic construction supplies canonical occurrences and
the resulting native presentation. -/
noncomputable def typedSchemaInventory :
    ExhaustiveTypedSchemaInventory nativeListPresentedCandidate where
  entry := by
    intro index
    revert index
    rw [presented_source_equation_schemas]
    intro index
    change Fin 3 at index
    refine Fin.cases ?_ (fun later => ?_) index
    · exact {
        sourceTyping := nilIotaReceipt.sourceTyping
        targetTyping := nilIotaReceipt.targetTyping }
    · refine Fin.cases ?_ (fun latest => ?_) later
      · exact {
          sourceTyping := consIotaReceipt.sourceTyping
          targetTyping := consIotaReceipt.targetTyping }
      · refine Fin.cases ?_ (fun impossible => Fin.elim0 impossible) latest
        exact {
          sourceTyping := identityIotaReceipt.sourceTyping
          targetTyping := identityIotaReceipt.targetTyping }

noncomputable def canonicalTypedOccurrence :=
  typedSchemaInventory.canonicalOccurrence

/-- The canonical typed occurrences retain the exact authored identity
occurrences, rather than merely some receipt with the same endpoints. -/
theorem canonicalTypedOccurrence_authored
    (index : Fin
      (equationSchemas
        (elaborate nativeListPresentedCandidate.source)).length) :
    (canonicalTypedOccurrence index).authored =
      EquationOccurrence.canonical
        (equationSchemas
          (elaborate nativeListPresentedCandidate.source)) index := by
  exact typedSchemaInventory.canonicalOccurrence_authored index

/-- Prime's authored List/identity source therefore generates a
constructional native kernel without assuming uniform preservation of its raw
syntactic equation closure. -/
noncomputable def typedNativePresentation :
    TypedNativePresentation nativeListPresentedCandidate :=
  typedSchemaInventory.toTypedNativePresentation nativeListReceiptNaturality

def nilSchemaIndex : Fin
    (equationSchemas
      (elaborate nativeListPresentedCandidate.source)).length :=
  ⟨0, by rw [presented_source_equation_schemas]; decide⟩

@[simp] theorem get_nilSchemaIndex :
    (equationSchemas
      (elaborate nativeListPresentedCandidate.source)).get nilSchemaIndex =
        nilEquation := by
  simp [nilSchemaIndex, presented_source_equation_schemas, nativeSchemas]

/-- Positive control: the canonical nil equation is one source-generated
constructional step, retaining its exact schema position and typed identity
substitution. -/
noncomputable def canonicalNilConstructedStep :
    (TypedNativePresentation.constructionalComputation
      typedNativePresentation).Step
        (typedNativePresentation.canonical nilSchemaIndex).sourceState
        (typedNativePresentation.canonical nilSchemaIndex).targetState :=
  typedNativePresentation.canonicalConstructedStep nilSchemaIndex

/-- The same canonical nil construction has a proof-relevant step in the
existing native family computation. -/
noncomputable def canonicalNilNativeStep :
    (nativeIndexedComputation nativeListPresentedCandidate).Step
      (typedNativePresentation.canonical nilSchemaIndex).sourceState
      (typedNativePresentation.canonical nilSchemaIndex).targetState :=
  typedNativePresentation.canonicalNativeStep nilSchemaIndex

/-- Negative control: the raw untyped nil equation exists, but its left
endpoint cannot inhabit any constructional-kernel state at the proposed
displayed type.  Therefore no native constructional step can start there. -/
theorem raw_untyped_nil_has_no_constructional_source
    (type : Tower.Tm 0) :
    Nonempty
        (EquationOccurrence nativeSchemas untypedNilLeft undeclaredElement) ∧
      ¬ ∃ source : NativeIndexedState nativeListPresentedCandidate
          ⟨0, (.nil : Tower.Ctx 0), type⟩,
        source.1 = untypedNilLeft := by
  refine ⟨⟨untypedNilOccurrence⟩, ?_⟩
  rintro ⟨⟨term, typing⟩, termEquation⟩
  change term = untypedNilLeft at termEquation
  subst term
  exact untypedNilLeft_not_hasType type typing.down

end NativeList

/-! ## Shared Nat/Vec declaration world -/

namespace NativeNatVec

open AuthoredIndexedFamilyReceiptNaturality.NativeNatVec
open NativeNaturalVectorFamilies
open NativeNaturalVectorFamilySource

@[simp] theorem nat_presented_source_equation_schemas :
    equationSchemas (elaborate natPresentedCandidate.source) = schemas := by
  change equationSchemas (elaborate natInventory.source) = schemas
  rw [natInventory.elaborate_source]
  rfl

@[simp] theorem vec_presented_source_equation_schemas :
    equationSchemas (elaborate vecPresentedCandidate.source) = schemas := by
  change equationSchemas (elaborate vecInventory.source) = schemas
  rw [vecInventory.elaborate_source]
  rfl

/-- Every schema in the shared declaration world has typed endpoints when
viewed through the Nat candidate.  The inventory intentionally includes Vec
computation because the candidate is a view of one declaration world, not a
private rule registry. -/
noncomputable def natTypedSchemaInventory :
    ExhaustiveTypedSchemaInventory natPresentedCandidate where
  entry := by
    intro index
    revert index
    rw [nat_presented_source_equation_schemas]
    intro index
    change Fin 4 at index
    refine Fin.cases ?_ (fun later => ?_) index
    · exact {
        sourceTyping := natZeroIotaReceipt.sourceTyping
        targetTyping := natZeroIotaReceipt.targetTyping }
    · refine Fin.cases ?_ (fun later => ?_) later
      · exact {
          sourceTyping := natSuccIotaReceipt.sourceTyping
          targetTyping := natSuccIotaReceipt.targetTyping }
      · refine Fin.cases ?_ (fun latest => ?_) later
        · exact {
            sourceTyping := vecNilIotaReceipt.sourceTyping
            targetTyping := vecNilIotaReceipt.targetTyping }
        · refine Fin.cases ?_ (fun impossible => Fin.elim0 impossible) latest
          exact {
            sourceTyping := vecConsIotaReceipt.sourceTyping
            targetTyping := vecConsIotaReceipt.targetTyping }

noncomputable def natCanonicalTypedOccurrence :=
  natTypedSchemaInventory.canonicalOccurrence

@[simp] theorem natCanonicalTypedOccurrence_authored
    (index : Fin
      (equationSchemas (elaborate natPresentedCandidate.source)).length) :
    (natCanonicalTypedOccurrence index).authored =
      EquationOccurrence.canonical
        (equationSchemas (elaborate natPresentedCandidate.source)) index := by
  exact natTypedSchemaInventory.canonicalOccurrence_authored index

noncomputable def natTypedNativePresentation :
    TypedNativePresentation natPresentedCandidate :=
  natTypedSchemaInventory.toTypedNativePresentation natReceiptNaturality

/-- The Vec candidate supplies a second view of the same four typed schemas.
Its source identity and receipt naturality remain those of the Vec view. -/
noncomputable def vecTypedSchemaInventory :
    ExhaustiveTypedSchemaInventory vecPresentedCandidate where
  entry := by
    intro index
    revert index
    rw [vec_presented_source_equation_schemas]
    intro index
    change Fin 4 at index
    refine Fin.cases ?_ (fun later => ?_) index
    · exact {
        sourceTyping := natZeroIotaReceipt.sourceTyping
        targetTyping := natZeroIotaReceipt.targetTyping }
    · refine Fin.cases ?_ (fun later => ?_) later
      · exact {
          sourceTyping := natSuccIotaReceipt.sourceTyping
          targetTyping := natSuccIotaReceipt.targetTyping }
      · refine Fin.cases ?_ (fun latest => ?_) later
        · exact {
            sourceTyping := vecNilIotaReceipt.sourceTyping
            targetTyping := vecNilIotaReceipt.targetTyping }
        · refine Fin.cases ?_ (fun impossible => Fin.elim0 impossible) latest
          exact {
            sourceTyping := vecConsIotaReceipt.sourceTyping
            targetTyping := vecConsIotaReceipt.targetTyping }

noncomputable def vecCanonicalTypedOccurrence :=
  vecTypedSchemaInventory.canonicalOccurrence

@[simp] theorem vecCanonicalTypedOccurrence_authored
    (index : Fin
      (equationSchemas (elaborate vecPresentedCandidate.source)).length) :
    (vecCanonicalTypedOccurrence index).authored =
      EquationOccurrence.canonical
        (equationSchemas (elaborate vecPresentedCandidate.source)) index := by
  exact vecTypedSchemaInventory.canonicalOccurrence_authored index

noncomputable def vecTypedNativePresentation :
    TypedNativePresentation vecPresentedCandidate :=
  vecTypedSchemaInventory.toTypedNativePresentation vecReceiptNaturality

/-- Negative control for the abstraction boundary: neither family's local
iota-clause registry exhausts the shared authored source.  A source-wide
inventory is therefore not interchangeable with a family-local registry. -/
theorem local_iota_clause_lists_do_not_exhaust_shared_source :
    natCandidate.iotaClauses.length ≠
        (equationSchemas
          (elaborate natPresentedCandidate.source)).length ∧
      vecCandidate.iotaClauses.length ≠
        (equationSchemas
          (elaborate vecPresentedCandidate.source)).length := by
  constructor
  · rw [nat_presented_source_equation_schemas]
    simp [natCandidate, natIotaClauses, schemas]
  · rw [vec_presented_source_equation_schemas]
    simp [vecCandidate, vecIotaClauses, schemas]

def natZeroSchemaIndex : Fin
    (equationSchemas (elaborate natPresentedCandidate.source)).length :=
  ⟨0, by rw [nat_presented_source_equation_schemas]; decide⟩

/-- The Vec-nil schema as a position in the Nat view's complete authored
source. -/
def vecNilThroughNatViewSchemaIndex : Fin
    (equationSchemas (elaborate natPresentedCandidate.source)).length :=
  ⟨2, by rw [nat_presented_source_equation_schemas]; decide⟩

def vecNilSchemaIndex : Fin
    (equationSchemas (elaborate vecPresentedCandidate.source)).length :=
  ⟨2, by rw [vec_presented_source_equation_schemas]; decide⟩

/-- Positive controls from both candidate views of the common source. -/
noncomputable def canonicalNatZeroNativeStep :=
  natTypedNativePresentation.canonicalNativeStep natZeroSchemaIndex

/-- Positive cross-family control: the source-wide Nat view constructs the
Vec-nil computation even though Vec-nil is absent from Nat's local iota-clause
list. -/
noncomputable def canonicalVecNilThroughNatViewNativeStep :=
  natTypedNativePresentation.canonicalNativeStep
    vecNilThroughNatViewSchemaIndex

noncomputable def canonicalVecNilNativeStep :=
  vecTypedNativePresentation.canonicalNativeStep vecNilSchemaIndex

/-- The shared raw Nat equation cannot enter the constructional state fibre
through the Nat view merely because its untyped occurrence exists. -/
theorem raw_untyped_nat_has_no_constructional_source
    (type : Tower.Tm 0) :
    Nonempty (EquationOccurrence schemas untypedNatZeroLeft zeroTm) ∧
      ¬ ∃ source : NativeIndexedState natPresentedCandidate
          ⟨0, (.nil : Tower.Ctx 0), type⟩,
        source.1 = untypedNatZeroLeft := by
  refine ⟨⟨untypedNatZeroOccurrence⟩, ?_⟩
  rintro ⟨⟨term, typing⟩, termEquation⟩
  change term = untypedNatZeroLeft at termEquation
  subst term
  exact untypedNatZeroLeft_not_hasType type typing.down

end NativeNatVec

/-! ## Axiom audit -/

#print axioms ExhaustiveTypedSchemaInventory.canonicalOccurrence
#print axioms ExhaustiveTypedSchemaInventory.coversEveryAuthoredSchema
#print axioms ExhaustiveTypedSchemaInventory.toTypedNativePresentation
#print axioms TypedOccurrenceOps.adjust
#print axioms TypedNativePresentation.instantiate
#print axioms TypedNativePresentation.instantiate_authored
#print axioms TypedNativePresentation.instantiate_nativeEvidence
#print axioms TypedNativePresentation.ConstructedStep.toTypedOccurrence
#print axioms TypedNativePresentation.ConstructedStep.toTypedOccurrence_authored
#print axioms TypedNativePresentation.ConstructedStep.substitute
#print axioms TypedNativePresentation.canonicalConstructedStep
#print axioms TypedNativePresentation.canonicalNativeStep
#print axioms TypedNativePresentation.realizeConversion
#print axioms TypedNativePresentation.realizeConversion_step
#print axioms NativeList.typedSchemaInventory
#print axioms NativeList.typedNativePresentation
#print axioms NativeList.canonicalNilConstructedStep
#print axioms NativeList.canonicalNilNativeStep
#print axioms NativeList.raw_untyped_nil_has_no_constructional_source
#print axioms NativeNatVec.natTypedSchemaInventory
#print axioms NativeNatVec.vecTypedSchemaInventory
#print axioms NativeNatVec.natTypedNativePresentation
#print axioms NativeNatVec.vecTypedNativePresentation
#print axioms NativeNatVec.local_iota_clause_lists_do_not_exhaust_shared_source
#print axioms NativeNatVec.canonicalNatZeroNativeStep
#print axioms NativeNatVec.canonicalVecNilThroughNatViewNativeStep
#print axioms NativeNatVec.canonicalVecNilNativeStep
#print axioms NativeNatVec.raw_untyped_nat_has_no_constructional_source

end AuthoredIndexedFamilyConstruction
end Mettapedia.Languages.MeTTa.TypeTheory.CumulativeTower
