import Mettapedia.MachineLearning.NeuralNetworks.WorkspaceDecoder.RoutedCaromContinuousChannel
import Mathlib.Analysis.Calculus.Deriv.Prod

/-!
# Routed CAROM: autonomous semiflow realization

A compatible list of continuous phases need not arise from one autonomous
dynamical system.  This module makes the missing premise explicit: every phase
evolution must be the same semiflow.  Under that premise, phasewise execution
is exactly the shared flow at the sum of the phase durations.

The positive fixture is generated by one smooth autonomous vector field.  Its
progress coordinate advances at unit speed while its transverse coordinate
contracts exponentially.  Two consecutive phase certificates cut one orbit
into positive dwell intervals and end in an observation-absorbing region.

This is not a generalized Lotka--Volterra or trained-router realization.
-/

namespace Mettapedia.MachineLearning.NeuralNetworks.WorkspaceDecoder

open Function Set

namespace RoutedCarom

universe uState uObservation

variable {State : Type uState} [NormedAddCommGroup State]
  {Observation : Type uObservation}

/-- Total elapsed time of a finite phase channel. -/
def continuousChannelDuration (observe : State → Observation) :
    List (ContinuousMetastablePhase observe) → ℝ
  | [] => 0
  | phase :: phases => phase.duration + continuousChannelDuration observe phases

theorem continuousChannelDuration_nonneg
    (observe : State → Observation)
    (phases : List (ContinuousMetastablePhase observe)) :
    0 ≤ continuousChannelDuration observe phases := by
  induction phases with
  | nil => simp [continuousChannelDuration]
  | cons phase phases ih =>
      simp only [continuousChannelDuration]
      exact add_nonneg phase.duration_pos.le ih

/-- A continuous channel is autonomous when all of its declared phases are
restrictions of one common semiflow.  Initial entry and phase compatibility
are retained as separate obligations. -/
structure AutonomousContinuousChannel (observe : State → Observation) where
  evolution : ℝ → State → State
  evolution_zero : ∀ state, evolution 0 state = state
  evolution_add : ∀ first second state,
    0 ≤ first → 0 ≤ second →
      evolution (first + second) state =
        evolution second (evolution first state)
  evolution_continuous : ∀ state, Continuous fun time => evolution time state
  phases : List (ContinuousMetastablePhase observe)
  phase_evolution_eq : ∀ phase, phase ∈ phases → phase.evolution = evolution
  initial : State
  initial_entry : ChannelInitialEntry observe initial phases
  compatible : PhaseChainCompatible observe phases

/-- An autonomous channel's phasewise runner is the shared semiflow evaluated
at the sum of the phase durations. -/
theorem AutonomousContinuousChannel.run_eq_evolution_duration
    (channel : AutonomousContinuousChannel (State := State) observe) :
    runContinuousChannel observe channel.initial channel.phases =
      channel.evolution
        (continuousChannelDuration observe channel.phases) channel.initial := by
  suffices hrun : ∀ phases : List (ContinuousMetastablePhase observe),
      phases ⊆ channel.phases → ∀ initial,
        runContinuousChannel observe initial phases =
          channel.evolution (continuousChannelDuration observe phases) initial by
    exact hrun channel.phases (List.Subset.refl _) channel.initial
  intro phases hsubset
  induction phases with
  | nil =>
      intro initial
      simp [runContinuousChannel, continuousChannelDuration,
        channel.evolution_zero]
  | cons phase phases ih =>
      intro initial
      have hphase : phase.evolution = channel.evolution :=
        channel.phase_evolution_eq phase (hsubset (by simp))
      have htail : phases ⊆ channel.phases := by
        intro member hmember
        exact hsubset (by simp [hmember])
      rw [runContinuousChannel]
      rw [hphase]
      rw [ih htail]
      rw [← channel.evolution_add phase.duration
        (continuousChannelDuration observe phases) initial
        phase.duration_pos.le (continuousChannelDuration_nonneg observe phases)]
      rfl

/-- The existing phase-composition theorem supplies the ordered dwell
itinerary for every autonomous channel. -/
theorem AutonomousContinuousChannel.dwellItinerary_eq_centers
    (channel : AutonomousContinuousChannel (State := State) observe) :
    List.map observe
        (continuousChannelDwellStates observe channel.initial channel.phases) =
      List.map observe (continuousChannelCenters observe channel.phases) :=
  continuousChannelDwellItinerary_eq_centers observe channel.phases
    channel.initial channel.initial_entry channel.compatible

/-- Merely sharing one phase list does not produce an autonomous realization;
the witness must identify every phase evolution with one function. -/
def HasSharedContinuousEvolution (observe : State → Observation)
    (phases : List (ContinuousMetastablePhase observe)) : Prop :=
  ∃ evolution : ℝ → State → State,
    ∀ phase, phase ∈ phases → phase.evolution = evolution

/-! ## One smooth autonomous realization -/

/-- State coordinates are progress along the channel and transverse error. -/
abbrev LinearAutonomousChannelState := ℝ × ℝ

/-- Smooth autonomous vector field: unit longitudinal velocity and linear
transverse attraction. -/
def linearAutonomousChannelVectorField
    (state : LinearAutonomousChannelState) : LinearAutonomousChannelState :=
  (1, -state.2)

/-- Exact flow of `linearAutonomousChannelVectorField`. -/
noncomputable def linearAutonomousChannelFlow (time : ℝ)
    (state : LinearAutonomousChannelState) : LinearAutonomousChannelState :=
  (state.1 + time, Real.exp (-time) * state.2)

theorem linearAutonomousChannelFlow_zero
    (state : LinearAutonomousChannelState) :
    linearAutonomousChannelFlow 0 state = state := by
  simp [linearAutonomousChannelFlow]

theorem linearAutonomousChannelFlow_add
    (first second : ℝ) (state : LinearAutonomousChannelState) :
    linearAutonomousChannelFlow (first + second) state =
      linearAutonomousChannelFlow second
        (linearAutonomousChannelFlow first state) := by
  simp only [linearAutonomousChannelFlow, Prod.mk.injEq]
  constructor
  · ring
  · rw [show -(first + second) = -second + -first by ring, Real.exp_add]
    ring

theorem linearAutonomousChannelFlow_continuous
    (state : LinearAutonomousChannelState) :
    Continuous fun time => linearAutonomousChannelFlow time state := by
  unfold linearAutonomousChannelFlow
  fun_prop

/-- The advertised vector field really is the time derivative of the shared
flow at every time and initial state. -/
theorem linearAutonomousChannelFlow_hasDerivAt
    (time : ℝ) (state : LinearAutonomousChannelState) :
    HasDerivAt (fun elapsed => linearAutonomousChannelFlow elapsed state)
      (linearAutonomousChannelVectorField
        (linearAutonomousChannelFlow time state)) time := by
  have hfirst : HasDerivAt (fun elapsed : ℝ => state.1 + elapsed) 1 time := by
    exact (hasDerivAt_id time).const_add state.1
  have hsecond :
      HasDerivAt (fun elapsed : ℝ => Real.exp (-elapsed) * state.2)
        (-(Real.exp (-time) * state.2)) time := by
    simpa [neg_mul] using
      ((Real.hasDerivAt_exp (-time)).comp time (hasDerivAt_neg time)).mul_const
        state.2
  simpa [linearAutonomousChannelFlow, linearAutonomousChannelVectorField]
    using hfirst.prodMk hsecond

inductive LinearAutonomousChannelObservation
  | first
  | second
  | halt
  deriving DecidableEq, Repr

/-- Observation reads only longitudinal progress.  Once progress reaches two,
all later states have the halt observation although hidden transverse state may
continue to contract. -/
noncomputable def linearAutonomousChannelObserve
    (state : LinearAutonomousChannelState) :
    LinearAutonomousChannelObservation :=
  if state.1 < 1 then .first else if state.1 < 2 then .second else .halt

private def transverseError (state : LinearAutonomousChannelState) : ℝ :=
  ‖state.2‖

private def channelActivation (state : LinearAutonomousChannelState) : ℝ :=
  3 - state.1

private theorem linearFlow_transverseError
    (time : ℝ) (state : LinearAutonomousChannelState) :
    transverseError (linearAutonomousChannelFlow time state) =
      Real.exp (-time) * transverseError state := by
  simp only [transverseError, linearAutonomousChannelFlow]
  rw [norm_mul, Real.norm_eq_abs, abs_of_pos (Real.exp_pos _)]

/-- First restriction of the shared flow: progress zero to one, with a
positive observation dwell and nontrivial transverse contraction. -/
noncomputable def autonomousLinearPhaseFirst :
    ContinuousMetastablePhase linearAutonomousChannelObserve where
  evolution := linearAutonomousChannelFlow
  center := (1 / 2, 0)
  entryRegion := {state | state.1 = 0 ∧ ‖state.2‖ ≤ 1}
  tubeRegion := {state | 0 ≤ state.1 ∧ state.1 ≤ 1 ∧ ‖state.2‖ ≤ 1}
  observationRegion := {state | 1 / 4 ≤ state.1 ∧ state.1 ≤ 3 / 4}
  exitRegion := {state | state.1 = 1 ∧ ‖state.2‖ ≤ 1}
  duration := 1
  dwellStart := 1 / 4
  dwellEnd := 3 / 4
  duration_pos := by norm_num
  dwellStart_nonneg := by norm_num
  dwell_nonempty := by norm_num
  dwellEnd_le_duration := by norm_num
  transverseError := transverseError
  transverseRate := 1
  initialTransverseBound := 1
  transverseRate_pos := by norm_num
  initialTransverseBound_nonneg := by norm_num
  activation := channelActivation
  activationFloor := 2
  evolution_zero := linearAutonomousChannelFlow_zero
  evolution_add := by
    intro first second state _ _
    exact linearAutonomousChannelFlow_add first second state
  evolution_continuous := linearAutonomousChannelFlow_continuous
  transverseError_nonneg := fun state => norm_nonneg _
  entry_transverse_le := by
    intro state hstate
    exact hstate.2
  transverse_attraction := by
    intro state hstate time _
    rw [linearFlow_transverseError]
    simpa [transverseError] using
      (mul_le_mul_of_nonneg_left hstate.2 (Real.exp_pos (-time)).le)
  stays_in_tube := by
    intro state hstate time htime
    simp only [Set.mem_setOf_eq, linearAutonomousChannelFlow]
    rw [hstate.1]
    constructor
    · linarith [htime.1]
    constructor
    · linarith [htime.2]
    · rw [norm_mul, Real.norm_eq_abs, abs_of_pos (Real.exp_pos _)]
      calc
        Real.exp (-time) * ‖state.2‖ ≤ Real.exp (-time) * 1 :=
          mul_le_mul_of_nonneg_left hstate.2 (Real.exp_pos _).le
        _ ≤ 1 := by
          rw [mul_one, Real.exp_le_one_iff]
          linarith [htime.1]
  dwells_in_observation_region := by
    intro state hstate time htime
    simp only [Set.mem_setOf_eq, linearAutonomousChannelFlow]
    rw [hstate.1]
    simpa using htime
  observation_constant := by
    intro state hstate
    have hstateFirst : state.1 < 1 := by linarith [hstate.2]
    calc
      linearAutonomousChannelObserve state = .first := by
        simp [linearAutonomousChannelObserve, hstateFirst]
      _ = linearAutonomousChannelObserve (1 / 2, 0) := by
        norm_num [linearAutonomousChannelObserve]
  exits := by
    intro state hstate
    simp only [Set.mem_setOf_eq, linearAutonomousChannelFlow]
    rw [hstate.1]
    constructor
    · norm_num
    · rw [norm_mul, Real.norm_eq_abs, abs_of_pos (Real.exp_pos _)]
      calc
        Real.exp (-1) * ‖state.2‖ ≤ Real.exp (-1) * 1 :=
          mul_le_mul_of_nonneg_left hstate.2 (Real.exp_pos _).le
        _ ≤ 1 := by
          rw [mul_one, Real.exp_le_one_iff]
          norm_num
  activation_floor := by
    intro state hstate time htime
    simp only [channelActivation, linearAutonomousChannelFlow]
    rw [hstate.1]
    linarith [htime.2]

/-- Second restriction of the same flow: progress one to two. -/
noncomputable def autonomousLinearPhaseSecond :
    ContinuousMetastablePhase linearAutonomousChannelObserve where
  evolution := linearAutonomousChannelFlow
  center := (3 / 2, 0)
  entryRegion := {state | state.1 = 1 ∧ ‖state.2‖ ≤ 1}
  tubeRegion := {state | 1 ≤ state.1 ∧ state.1 ≤ 2 ∧ ‖state.2‖ ≤ 1}
  observationRegion := {state | 5 / 4 ≤ state.1 ∧ state.1 ≤ 7 / 4}
  exitRegion := {state | state.1 = 2 ∧ ‖state.2‖ ≤ 1}
  duration := 1
  dwellStart := 1 / 4
  dwellEnd := 3 / 4
  duration_pos := by norm_num
  dwellStart_nonneg := by norm_num
  dwell_nonempty := by norm_num
  dwellEnd_le_duration := by norm_num
  transverseError := transverseError
  transverseRate := 1
  initialTransverseBound := 1
  transverseRate_pos := by norm_num
  initialTransverseBound_nonneg := by norm_num
  activation := channelActivation
  activationFloor := 1
  evolution_zero := linearAutonomousChannelFlow_zero
  evolution_add := by
    intro first second state _ _
    exact linearAutonomousChannelFlow_add first second state
  evolution_continuous := linearAutonomousChannelFlow_continuous
  transverseError_nonneg := fun state => norm_nonneg _
  entry_transverse_le := by
    intro state hstate
    exact hstate.2
  transverse_attraction := by
    intro state hstate time _
    rw [linearFlow_transverseError]
    simpa [transverseError] using
      (mul_le_mul_of_nonneg_left hstate.2 (Real.exp_pos (-time)).le)
  stays_in_tube := by
    intro state hstate time htime
    simp only [Set.mem_setOf_eq, linearAutonomousChannelFlow]
    rw [hstate.1]
    constructor
    · linarith [htime.1]
    constructor
    · linarith [htime.2]
    · rw [norm_mul, Real.norm_eq_abs, abs_of_pos (Real.exp_pos _)]
      calc
        Real.exp (-time) * ‖state.2‖ ≤ Real.exp (-time) * 1 :=
          mul_le_mul_of_nonneg_left hstate.2 (Real.exp_pos _).le
        _ ≤ 1 := by
          rw [mul_one, Real.exp_le_one_iff]
          linarith [htime.1]
  dwells_in_observation_region := by
    intro state hstate time htime
    simp only [Set.mem_setOf_eq, linearAutonomousChannelFlow]
    rw [hstate.1]
    norm_num at htime ⊢
    constructor <;> linarith [htime.1, htime.2]
  observation_constant := by
    intro state hstate
    unfold linearAutonomousChannelObserve
    have hstateNotFirst : ¬ state.1 < 1 := by linarith [hstate.1]
    have hstateSecond : state.1 < 2 := by linarith [hstate.2]
    norm_num [hstateNotFirst, hstateSecond]
  exits := by
    intro state hstate
    simp only [Set.mem_setOf_eq, linearAutonomousChannelFlow]
    rw [hstate.1]
    constructor
    · norm_num
    · rw [norm_mul, Real.norm_eq_abs, abs_of_pos (Real.exp_pos _)]
      calc
        Real.exp (-1) * ‖state.2‖ ≤ Real.exp (-1) * 1 :=
          mul_le_mul_of_nonneg_left hstate.2 (Real.exp_pos _).le
        _ ≤ 1 := by
          rw [mul_one, Real.exp_le_one_iff]
          norm_num
  activation_floor := by
    intro state hstate time htime
    simp only [channelActivation, linearAutonomousChannelFlow]
    rw [hstate.1]
    linarith [htime.2]

noncomputable def autonomousLinearContinuousChannel :
    AutonomousContinuousChannel linearAutonomousChannelObserve where
  evolution := linearAutonomousChannelFlow
  evolution_zero := linearAutonomousChannelFlow_zero
  evolution_add := by
    intro first second state _ _
    exact linearAutonomousChannelFlow_add first second state
  evolution_continuous := linearAutonomousChannelFlow_continuous
  phases := [autonomousLinearPhaseFirst, autonomousLinearPhaseSecond]
  phase_evolution_eq := by
    intro phase hphase
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hphase
    rcases hphase with rfl | rfl <;> rfl
  initial := (0, 1)
  initial_entry := by
    simp [ChannelInitialEntry, autonomousLinearPhaseFirst]
  compatible := by
    simp only [PhaseChainCompatible]
    constructor
    · intro state hstate
      exact hstate
    · trivial

theorem autonomousLinearContinuousChannel_itinerary :
    List.map linearAutonomousChannelObserve
        (continuousChannelDwellStates linearAutonomousChannelObserve
          autonomousLinearContinuousChannel.initial
          autonomousLinearContinuousChannel.phases) =
      [.first, .second] := by
  rw [autonomousLinearContinuousChannel.dwellItinerary_eq_centers]
  norm_num [autonomousLinearContinuousChannel, continuousChannelCenters,
    autonomousLinearPhaseFirst, autonomousLinearPhaseSecond,
    linearAutonomousChannelObserve]

theorem autonomousLinearContinuousChannel_run_eq :
    runContinuousChannel linearAutonomousChannelObserve
        autonomousLinearContinuousChannel.initial
        autonomousLinearContinuousChannel.phases =
      linearAutonomousChannelFlow 2 (0, 1) := by
  rw [autonomousLinearContinuousChannel.run_eq_evolution_duration]
  norm_num [autonomousLinearContinuousChannel, continuousChannelDuration,
    autonomousLinearPhaseFirst, autonomousLinearPhaseSecond]

/-- The same autonomous flow has an observation-absorbing halt after the two
certified phases, even though its hidden transverse coordinate keeps moving. -/
theorem autonomousLinearContinuousChannel_observation_halt
    (time : ℝ) (htime : 0 ≤ time) :
    linearAutonomousChannelObserve
        (linearAutonomousChannelFlow time
          (runContinuousChannel linearAutonomousChannelObserve
            autonomousLinearContinuousChannel.initial
            autonomousLinearContinuousChannel.phases)) = .halt := by
  rw [autonomousLinearContinuousChannel_run_eq]
  simp only [linearAutonomousChannelFlow]
  unfold linearAutonomousChannelObserve
  have hnotFirst : ¬ (2 + time : ℝ) < 1 := by linarith
  have hnotSecond : ¬ (2 + time : ℝ) < 2 := by linarith
  simp [hnotFirst, hnotSecond]

/-! ## Negative boundary -/

/-- The compatible two-phase fixture from the preceding module is not
autonomous: its two phase evolutions disagree on the same time/state input. -/
theorem continuousTwoPhaseChannel_has_no_shared_evolution :
    ¬ HasSharedContinuousEvolution continuousPhaseObservation
      continuousTwoPhaseChannel := by
  rintro ⟨evolution, hshared⟩
  have hone := hshared continuousPhaseOne (by
    simp [continuousTwoPhaseChannel])
  have hzero := hshared continuousPhaseZero (by
    simp [continuousTwoPhaseChannel])
  have hequal : continuousPhaseOne.evolution 1 1 =
      continuousPhaseZero.evolution 1 1 := by
    rw [hone, hzero]
  simp only [continuousPhaseOne, continuousPhaseZero, expContractionFlow,
    sub_self, mul_zero, add_zero, zero_add, sub_zero, mul_one] at hequal
  have hlt : Real.exp (-1) < 1 := by
    rw [Real.exp_lt_one_iff]
    norm_num
  linarith

#print axioms AutonomousContinuousChannel.run_eq_evolution_duration
#print axioms AutonomousContinuousChannel.dwellItinerary_eq_centers
#print axioms linearAutonomousChannelFlow_hasDerivAt
#print axioms autonomousLinearContinuousChannel_itinerary
#print axioms autonomousLinearContinuousChannel_observation_halt
#print axioms continuousTwoPhaseChannel_has_no_shared_evolution

end RoutedCarom

end Mettapedia.MachineLearning.NeuralNetworks.WorkspaceDecoder
